### ISSUE TITLE
lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts:

### ISSUE THREAD

**Issue by He-Pin** [sbt/sbt#5519] opened 2020-04-30 02:49 UTC
using 
![image](https://user-images.githubusercontent.com/501740/80666891-41345200-8ad0-11ea-9ad6-9eec6351edca.png)

```
Extracting structure failed
stack trace is suppressed; run last akka-actor-tests / updateSbtClassifiers for the full output
(akka-actor-tests / updateSbtClassifiers) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
https://repo1.maven.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava-sources.jar: not found: https://repo1.maven.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava-sources.jar
Total time: 29 s, completed 2020年4月30日 上午10:46:54

```

**Comment by eed3si9n** [comment] 2020-04-30 18:19
This is a duplicate of https://github.com/sbt/sbt/issues/5501

**Closed as completed by eed3si9n** 2020-04-30 18:19 UTC
