### ISSUE TITLE
Cross-build ("+") command doesn't take aliases

### ISSUE THREAD

**Issue by kzys** [sbt/sbt#2776] opened 2016-10-11 03:50 UTC
While I was looking #1074, I realized that 1.0.x's `+` command doesn't work with aliases, unlike 0.13.x.
## steps

Start sbt 1.0.x and run `+` with an alias like below.

```
> show sbtVersion
[info] 1.0.0-SNAPSHOT
> alias foo = compile
> + foo
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: foo (similar: fork, doc, onLoad)
[error] ++  2.11.8 sbt-1074/foo
[error]                        ^
>
```
## problem

`+` command doesn't work with aliases.
## expectation

It was working on 0.13.x.

```
> show sbtVersion
[info] 0.13.11
> alias foo = compile
> + foo
[info] Setting version to 2.10.6
[info] Reapplying settings...
[info] Set current project to sbt-1074 (in build file:/Users/kazuyoshi/sbt-1074/)
[info] Updating {file:/Users/kazuyoshi/sbt-1074/}sbt-1074...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[success] Total time: 0 s, completed Oct 10, 2016 8:45:31 PM
[info] Setting version to 2.10.6
[info] Reapplying settings...
[info] Set current project to sbt-1074 (in build file:/Users/kazuyoshi/sbt-1074/)
>
```

**Comment by dwijnand** [comment] 2016-10-11 06:27
I assume this is a little fall out from #2613, so paging @jroper, perhaps he knows why (or feels nerd-sniped into figuring it out =D).

**Comment by jroper** [comment] 2016-10-13 07:51
I'm not sure that it can work with aliases. So before, cross building was dumb, it changed the scala version build wide, even if some sub projects didn't support that scala version. Then it would issue the "thing" that the user requested, be it a command, task or alias, build wide.  If some sub projects didn't support that scala version (eg, because they were an sbt plugin and so could only build against Scala 2.10), then everything would blow up.

So now, when you tell it to cross build, for each scala version, it will gather all the sub projects that can be built against that scala version (based on their own crossScalaVersion setting), set the scala version for those projects, and then issue the specified task against each of those projects.  That's the change that's causing this, the thing the user requests has to be a task, it can't be a command or an alias (which I'm guessing is just a dynamically configured command, I haven't actually looked at how aliases are configured), since commands and aliases don't get scoped to projects.

My thoughts on this - cross building commands or aliases is not something we want to support - since the definition of what cross building is now doesn't make sense in that context.  So I'd say it's not a bug or a regression, but rather a by design change in behaviour that was necessary to make cross building intelligent, rather than a hack.

**Comment by dwijnand** [comment] 2016-10-13 12:42
Is that restriction in sbt-doge as well? /cc @eed3si9n 

Because I know of several projects that use "validate" or "verify" aliases to sequentially call tasks.

**Comment by dwijnand** [comment] 2017-06-28 11:03
I read and understood the situation here more clearly now.

This is indeed a consequence of making `+` work more correctly. Builds the previously defined a "validate" or "verify" alias to call a sequence of tasks would have to define "validate" and "verify" as a task now instead (probably using Def.sequential).

**Comment by eed3si9n** [comment] 2017-08-14 23:34
I love my doge, and I stand by it as a superior behavior compared to 0.13's `+`, but I have to own up to the fact that it occasionally bites people, at least when they try to composed it with commands -- something ppl do often for release. I am reopening this with Documentation tag.

To be closed when the release note is updated.

**Comment by jroper** [comment] 2017-08-15 04:48
Maybe we could implement something such that the new cross compilation can detect whether a command or a task is being run (or maybe try a task first then fall back to command), and if it's a task, then just implement the old behaviour, changing the scala version at the build level. We could even do some validation in there, so if it is running a command, but it finds that different sub projects have different cross build versions, we can warn the user about the potential unexpected behaviour that they'll get when cross building is done at the build level not on a per project level.

**Comment by jroper** [comment] 2017-08-15 04:57
Also, at a minimum, we can definitely improve the error reporting here.

**Comment by eed3si9n** [comment] 2017-08-28 18:01
Fixed in https://github.com/sbt/sbt/pull/3446

**Closed as completed by eed3si9n** 2017-08-28 18:01 UTC
Labels: documentation, Regression
