### ISSUE TITLE
False positive in the inconsistent duplicate warnings

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#1933] opened 2015-03-22 23:29 UTC
# steps

1) Given `sbt.version=0.13.8`, setup `build.sbt` as:

```
scalaVersion := "2.11.6"
libraryDependencies += "org.scoverage" %% "scalac-scoverage-runtime" % "1.0.4" % "provided"
```

2) Invoke `updateClassifiers`
# problem

```
[warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
[warn]  * org.scala-lang:scala-library:(2.11.6, 2.11.4)
```
# expectation

No warnings.
# note

Original report below:

@fommil indicates [on the mailing lists](https://groups.google.com/d/topic/sbt-dev/61J8cnQrsxU/discussion) (and @sslavic [as well](https://groups.google.com/d/msg/sbt-dev/w6dx6WWyAOE/0aJv8pbD9_gJ)) that there seems to be a false positive in the inconsistent duplicate warnings.

From Sam's post:

> Since upgrading to sbt 0.13.8 I get a _lot_ of errors of this nature (i.e. same thing repeated over and over):

```
[warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
[warn]  * org.scala-lang:scala-library:(2.11.6, 2.11.4)
[warn]  * org.scala-lang.modules:scala-parser-combinators_2.11:(1.0.1, 1.0.2, 1.0.3)
[warn]  * org.scala-lang.modules:scala-xml_2.11:(1.0.1, 1.0.3)
```

> I'm actually depending on explicit versions of all these libraries so I believe this is a bug in the warning code.

Running `gen-ensime` on the [ensime-server](https://github.com/ensime/ensime-server) build will reproduce the problem.

**Comment by fommil** [comment] 2015-03-23 07:37
Good point actually, this now occurs on the ensime master branch, since we upgraded sbt

**Comment by ijuma** [comment] 2015-03-23 13:40
It would be good to know if there is a workaround for this without disabling all eviction warnings or whether downgrading back to 0.13.7 is the only way to get rid of the excessive warnings.

**Comment by jsuereth** [comment] 2015-03-24 11:10
It looks like transitive eviction is leaking warnings here.

I.e. you're seeing the various evictions which take place when looking for your dependencies.   These should not all be showing up as root level, though, I think.

**Comment by dwijnand** [comment] 2015-03-24 11:12
Any ideas why this only occurs when `% "provided"`? Even `% "test"` doesn't cause it..

**Comment by EECOLOR** [comment] 2015-04-07 08:26
We have similar warnings with this project setup:

`build.sbt`

``` scala
lazy val root = project.in( file(".") )
  .enablePlugins( PlayScala )
  .settings (
            name := "project",
    scalaVersion := "2.11.5",
         version := "0.1-SNAPSHOT"
  )
```

`project/play.sbt`

``` scala
logLevel := Level.Warn

resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.8")
```

`project/build.properties`

``` scala
sbt.version=0.13.8
```

**Comment by gbranchaudrubenovitch** [comment] 2015-04-16 21:10
We also have the same kind of warnings with:

`build.sbt`

```
lazy val projectSettings = Seq(
  name := "atlas",
  version := "1.0",
  organization := "my-company",
  scalaVersion := "2.11.6"
)

lazy val librairies = Seq(
  "org.scalatest" %% "scalatest" % "2.2.4" % "test"
)

lazy val atlas = (project in file("."))
  .settings(projectSettings: _*)
  .settings(libraryDependencies ++= librairies)
```

`/project/plugins.sbt`

```
logLevel := Level.Warn
resolvers += Classpaths.sbtPluginReleases
addSbtPlugin("org.scoverage" %% "sbt-scoverage" % "1.0.4")
```

`/project/properties.sbt`

```
sbt.version=0.13.8
```

Workarounds we found:
- downgrade to `sbt 0.13.7` or
- set `logLevel := Level.Error`

**Comment by lucianenache** [comment] 2015-07-14 09:33
Having this issue too, with 2.11.7 and 2.11.6 under Intellij. Has anyone found the cause yet ?

**Comment by OndrejSpanel** [comment] 2015-07-14 10:49
I seem to get the same warning when including Jackson 2.5.0 - 2.5.3 against project containing Scala 2.11.7. The warning is:

> ```
>    [warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
>     [warn]  * org.scala-lang:scala-reflect:(2.11.4, 2.11.7)
> ```

**Comment by sslavic** [comment] 2015-07-14 11:39
Guys, try latest sbt 0.13.9 release candidate https://groups.google.com/forum/#!topic/sbt-dev/XNz6Ht-chd8

**Comment by OndrejSpanel** [comment] 2015-07-14 12:15
I have tried it (added sbt.version=0.13.9-RC2 into build.properties) but I still get the same warning as before on my IntellIJ SBT project refresh:

> 14:13:52 SBT project import
>          [warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
>          [warn]  \* org.scala-lang:scala-reflect:(2.11.4, 2.11.7)

When using 0.13.7 the issue is not seen.

**Comment by gbranchaudrubenovitch** [comment] 2015-07-14 14:39
I tried it with `0.13.9-RC2` and still got the same warnings.
This was with the project I showed in my previous comment.

**Comment by lucianenache** [comment] 2015-07-17 08:34
For me a work around was downgrading to `0.13.7`

**Comment by sfosdal** [comment] 2015-08-14 20:31
me as well. 0.13.8, 0.13.9 all gave the same msgs

**Comment by doctapp** [comment] 2015-08-21 14:11
+1

**Comment by altoic** [comment] 2015-08-22 18:31
Odd I am on 0.13.7 add I still get this message:
2:25:27 PM SBT project import
           [warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
           [warn]  \* org.scala-lang:scala-reflect:(2.11.2, 2.11.7)
           [warn]  \* org.scala-lang.modules:scala-xml_2.11:(1.0.2, 1.0.4)

**Comment by nelsonblaha** [comment] 2015-09-09 15:47
I get this in IntelliJ only with the following:

```
[warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
[warn]  * org.scala-lang:scala-reflect:(2.11.2, 2.11.7)
[warn]  * org.scala-lang.modules:scala-xml_2.11:(1.0.3, 1.0.4)
```

sbt 0.13.9. build.sbt for the main project is:

```
"com.typesafe.akka"        %% "akka-actor"              % "2.3.12",
  "io.spray"                 %% "spray-can"               % sprayVersion,
  "io.spray"                 %% "spray-routing"           % sprayVersion,
  "io.spray"                 %% "spray-testkit"           % sprayVersion,
  "io.spray"                 %% "spray-client"            % sprayVersion,
  "io.spray"                 %% "spray-json"              % "1.3.2",
  "org.scalatest"            %% "scalatest"               % "2.2.4" % "test",
  "org.elasticsearch"         % "elasticsearch"           % "1.7.1",
  "com.sksamuel.elastic4s"   %% "elastic4s-core"          % "1.7.0",
  "com.github.seratch"       %% "awscala"                 % "0.5.+")
```

It seems possibly relevant that I have a submodule with the following build.sbt dependencies:

```
"org.scala-lang"               %  "scala-reflect"         % scalaVersion.value,
  "com.github.seratch"           %% "awscala"               % "0.5.3"
```

**Comment by gurghet** [comment] 2015-09-11 12:49
+1

**Comment by danishin** [comment] 2015-09-15 06:41
+1

**Comment by dsarosi** [comment] 2015-09-17 01:43
+1

**Comment by dermatologist** [comment] 2015-09-17 06:55
It's scalatest!

**Comment by gurghet** [comment] 2015-09-17 13:37
Dermatologists pls elaborate

**Comment by bkstha** [comment] 2015-09-22 08:38
+1

**Comment by chaotic3quilibrium** [comment] 2015-09-22 16:46
Using IntelliJ (14.1.4) with the Scala plugin (1.5.3), I am receiving this warning:  

```
11:35:21 AM SBT project import
            [warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
            [warn]  * org.scala-lang.modules:scala-xml_2.11:(1.0.5, 1.0.4)
```

...after giving SBT a build.sbt file containing this content:  

```
name := "Test"

version := "1.0"

scalaVersion := "2.11.7"

scalacOptions := Seq("-unchecked", "-deprecation", "-encoding", "utf8")

//scala
libraryDependencies += "org.scala-lang"         % "scala-reflect"       % "2.11.7"

libraryDependencies += "org.scala-lang.modules" % "scala-xml_2.11"      % "1.0.5"

libraryDependencies += "net.databinder"         % "dispatch-core_2.11"  % "0.8.10"
```

When I alter the build.sbt file by changing the second libraryDependencies line to read...:

```
libraryDependencies += "org.scala-lang.modules" % "scala-xml_2.11"      % "1.0.4"
```

..., the warning disappears.  

I'm not versed enough in this area of Scala to know why this is occurring. I'd REALLY like to be using the latest version of scala-xml, i.e. 1.0.5, but don't feel skilled enough to know the consequences of ignoring the build.sbt warning. Any guidance on this would be very much appreciated.  

**UPDATE:**  

I had the wrong version of dispatch-core_2.11 specified. I've now changed the libraryDependencies lines to look like this...:

```
libraryDependencies += "org.scala-lang.modules"  % "scala-xml_2.11"      % "1.0.4"

libraryDependencies += "net.databinder.dispatch" % "dispatch-core_2.11"  % "0.11.3"
```

..., and the warning disappears.

BTW, if I remove the scala-xml_2.11 line (comment it out), the error reappears, albeit with a slightly different version conflict:

```
11:56:33 AM SBT project import
            [warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
            [warn]  * org.scala-lang.modules:scala-xml_2.11:(1.0.1, 1.0.4)
```

Something somewhere sure seems very "stuck" to the 1.0.4 version of scala-xml.

**Comment by godenji** [comment] 2015-10-06 14:55
+1 get this via sbt> eclipse with `EclipseKeys.withSource := true` flag set in my build; don't recall this occurring previously.

sbt 0.13.9, scala 2.11.7, play 2.4.3

**Comment by qmg-gkalogiros** [comment] 2015-10-21 09:00
+1

**Comment by helena** [comment] 2015-10-21 12:46
I've tried every SBT config I can think of to work around / force the version I want, in several projects, differing dependencies - no joy. I'm using latest scala and sbt versions in all.
Looking forward to 0.13.10 :)

**Comment by BardurArantsson** [comment] 2015-10-21 17:28
Btw, can we please stop with the +1's without any additional information? All you're doing is spamming countless (well, 24 at the current count) people with nothing interesting. Usually a "+1" can serve as a good reminder/notice to the maintainers that something is of interest to more than just them + reporter, but the spam is a bit ridiculous.[1]

I'm sure the SBT maintainers already realize that this is a big annoyance for everyone.

[1] Yes, GitHub should add a simple "vote up" button, but until such time...

**Comment by alwqx** [comment] 2015-10-28 07:01
+1
- scala 2.11.7
- sbt 0.13.8
  with the same issue.and my output is:

```
[warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
           [warn]  * org.scala-lang:scala-compiler:(2.10.0, 2.11.7)
           [warn]  * org.scala-lang:scala-library:(2.11.7, 2.10.4)
           [warn]  * commons-beanutils:com... (show balloon)
```

now I can't carry on my project

**Comment by eed3si9n** [comment] 2015-10-28 10:02
So this was a "feature" that I introduced in 0.13.8 in response to #1634. Using the repro steps set up by Dale, here's what you see when you run `show updateClassifiers`:

```
[warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
[warn]  * org.scala-lang:scala-library:(2.11.6, 2.11.4)
[info]  compile:
[info]  org.scala-lang:scala-library
[info]      - 2.11.6
[info]          (Artifact(scala-library,doc,jar,Some(javadoc),ArraySeq(),None,Map()),/Users/eugene/.ivy2/cache/org.scala-lang/scala-library/docs/scala-library-2.11.6-javadoc.jar)
[info]          (Artifact(scala-library,src,jar,Some(sources),ArraySeq(),None,Map()),/Users/eugene/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.11.6-sources.jar)
[info]          (Artifact(scala-library,jar,jar,None,ArraySeq(),None,Map()),/Users/eugene/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar)
[info]          status: release
[info]          publicationDate: Wed Feb 25 20:01:05 EST 2015
[info]          resolver: sbt-chain
[info]          artifactResolver: sbt-chain
[info]          evicted: false
...
[info]  provided:
...
[info]  org.scala-lang:scala-library
[info]      - 2.11.4
[info]          (Artifact(scala-library,src,jar,Some(sources),ArraySeq(),None,Map()),/Users/eugene/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.11.4-sources.jar)
[info]          (Artifact(scala-library,doc,jar,Some(javadoc),ArraySeq(),None,Map()),/Users/eugene/.ivy2/cache/org.scala-lang/scala-library/docs/scala-library-2.11.4-javadoc.jar)
[info]          status: release
[info]          publicationDate: Thu Oct 23 11:34:51 EDT 2014
[info]          resolver: sbt-chain
[info]          artifactResolver: sbt-chain
[info]          evicted: false
```

This shows that both Compile configuration and Provided configuration are pulling in scala-library, but with different versions. inconsistentDuplicateWarning  method (https://github.com/sbt/sbt/blob/0.13.9/ivy/src/main/scala/sbt/Ivy.scala#L534-L555) either needs to be smarter about configurations or needs to be commented out.

**Comment by conchz** [comment] 2015-10-29 03:10
+1

> - scala 2.11.7
> - sbt 0.13.9 with the same issue.

```
SBT project import
    [warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
    [warn]  * org.scalatra.scalate:scalate-core_2.11:(1.7.1, 1.7.0)
    [warn]  * org.scalatra.scalate:scalate-util_2.11:(1.7.1, 1.7.0)
    [warn]  * org.slf4j:slf4j-api:(1.7.12, 1.6.1)
```

**Comment by BardurArantsson** [comment] 2015-10-29 05:22
@dolphineor ... but see those might actually be interesting because you really have no idea if they're binary-compatible or not, whereas the scala ones _are_ binary compatible[1]. With any random library you have no such guarantees and in _those_ cases the warning is _valuable_.

[1] At least the Scala compiler folks have build infrastructure that tries to ensure that and pretty rigorous attempts code review-wise, etc. etc.

**Comment by conchz** [comment] 2015-10-29 06:11
@BardurArantsson I'm careless, for one jar, different dependency used different version caused this. Thanks for reminding me.

**Comment by igorzg** [comment] 2015-11-11 23:25
+1 on 0.13.8 and 0.13.9

``` scala
"org.specs2" %% "specs2-core" % "3.6.5" % "test"
```

**Comment by invkrh** [comment] 2015-11-13 16:05
+1 =>  0.13.9

**Comment by eed3si9n** [comment] 2015-12-03 22:55
Fixed by #2258 in 0.13 and sbt/librarymanagement#11  in 1.0.

**Closed as completed by eed3si9n** 2015-12-03 22:55 UTC
Labels: area/library_management

**Comment by Lvctao** [comment] 2016-06-07 04:49
What's the answer?

**Comment by EECOLOR** [comment] 2016-06-07 18:42
@Lvctao 42

**Comment by badkk** [comment] 2016-10-14 08:46
+1 => 0.13.8 &&scala: 2.11.8
