### ISSUE TITLE
sbt new g8 integration has newline issues

### ISSUE THREAD

**Issue by devshorts** [sbt/sbt#3541] opened 2017-09-15 22:06 UTC
When creating a new g8 scaffold from sbt, newlines and password integration behave oddly with keyboard input

## steps
sbt new <private repo>

## problem
sbt new prompts for ssh key but for each password key emits a newline and doesn't actually accept the password

![image](https://user-images.githubusercontent.com/1799346/30505057-3dc90b2a-9a27-11e7-8430-bfa64c4e68fe.png)

To work around this I had to copy my password to clipboard and paste it.  Even then newlines behaved oddly

## expectation
Password is accepted and newlines appear as normal

## notes

sbt version: 1.0.1

**Comment by eed3si9n** [comment] 2017-09-15 22:09
I'd be happy to keep this open as a reference, but likely the problem is coming from Giter8 trying to hit GitHub, not sbt.

**Comment by devshorts** [comment] 2017-09-15 22:15
The password stuff used to work in sbt 0.13.15 though, I guess I'm not sure how sbt and giter8 integrate together to tell what is responsible for what

**Comment by krnhotwings** [comment] 2019-11-08 17:02
Just came across this bug myself in sbt 1.3.3. Can confirm that it also used to work in sbt 0.13.x

I don't think it's coming from giter8 because the g8 CLI seems to work fine. However, I came across issue #5063 that described similar behavior. The workaround, which I tested and can confirm works, is to add the `--supershell=false` argument:

```sh
sbt --supershell=false new ...
```

**Comment by AlexeySoshin** [comment] 2021-06-23 13:28
Had this issue with `sbt 1.4.0`, resolved in `sbt 1.5.4` 

No need for `--supershell=false` anymore.

**Comment by eed3si9n** [comment] 2021-06-23 14:01
Nice

**Closed as completed by eed3si9n** 2021-06-23 14:01 UTC
