### ISSUE TITLE
sbt launcher terminates BSP server when sbt is not on path

### ISSUE THREAD

**Issue by jastice** [sbt/sbt#6176] opened 2020-11-27 18:29 UTC
When starting the sbt launcher from an environment that does not have the sbt script in the path, and no sbt server is running, the launcher script simply terminates after printing `[info] server was not detected. starting an instance`. This is the case when starting from IntelliJ IDEA.

## steps

1. start IntelliJ with Scala plugin from the UI (on Mac?)
2. import an sbt project configured to 1.4.x as BSP, choose "sbt" and not "sbt with Bloop" if prompted

alternatively if that doesn't repro:
1. start IntelliJ from a script, but set PATH to not include the sbt script
2. as above

## problem

1. the import will time out
2. in the build toolwindow, we see only
```[info] server was not detected. starting an instance```

In the background, what happens is that the sbt launcher simply terminates if it doesn't find the sbt launcher on the path.

## expectation

* the server should be able to be started from the same JVM used to start the launcher
* the sbt script should not be necessary at all, as sbt may not even have been installed on the system

**Comment by eatkins** [comment] 2020-11-27 20:33
> the server should be able to be started from the same JVM used to start the launcher

The problem with this expectation is that it makes the behavior of `sbt -bsp` very different from `sbt --client -bsp`. The latter is not started with a jvm at all so if is to be able to launch a server, it must be able to find either an sbt script or the launcher jar. Right now, the script can be provided to sbt as a command line argument and I just added #6177 to make the launcher jar available. Since bsp is an experimental feature, I feel like the best solution is for intellij to set that argument in the next version and say that 1.4.5 or greater is required for bsp support.

**Comment by jastice** [comment] 2020-11-27 21:17
Thanks! Actually IntelliJ simply uses the command line defined in `.bsp/sbt.json`, which gets generated by sbt itself. So this would have to also be fixed sbt-side. @adpi2 should know where :)

**Comment by eed3si9n** [comment] 2020-11-27 23:56
Here's what my `.bsp/sbt.json` contains:

> $ cat .bsp/sbt.json
> {"name":"sbt","version":"1.4.4","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/Users/eed3si9n/.sdkman/candidates/java/8.0.232.hs-adpt/jre/bin/java","-Xms100m","-Xmx100m","-classpath","/Users/eed3si9n/.sdkman/candidates/sbt/1.4.3/bin/sbt-launch.jar","xsbt.boot.Boot","-bsp"]}

This file is specific to my machine, so I'm not sure if the expectation 2

> the sbt script should not be necessary at all, as sbt may not even have been installed on the system 

could work.

Could we think of a workflow like the follows?:
1. Check if the server is already running by checking for [`./project/target/active.json`](https://www.scala-sbt.org/1.x/docs/sbt-server.html#Server+discovery+and+authentication).
2. If the server is running, use `.bsp/sbt.json` to connect to the running server.
3. If the server is NOT running, IntelliJ can start an instance of sbt session, wait for `./project/target/active.json`, and use `.bsp/sbt.json` to connect to the running server.
4. Import the build via BSP.
5. If IntelliJ started the server, shutdown the server.

**Comment by eatkins** [comment] 2020-11-28 04:54
What is the motivation for the new workflow rather than just updating the command in the bsp.json to work reliably? Intellij running `sbt -bsp` seems to already do pretty much what it describes afaict (whether or not #5 holds depends on how the `sbt -bsp` process exits).

WRT step #5 in the workflow, I dislike that behavior in metals (https://github.com/scalameta/metals-feature-requests/issues/165) but I’m less familiar with the intellij use case. Basically I think sbt startup time is so bad that we should always keep the server up, at least by default.

**Comment by eed3si9n** [comment] 2020-11-28 05:42
> What is the motivation for the new workflow rather than just updating the command in the bsp.json to work reliably?

I guess in general, I want to give the least amount of responsibility to `-bsp` command, and I think of them as programs that connect to an existing server; and I'd like to be in charge of the lifecycle of when the starts and ends. For me this is not really a new thing, and that's how I documented IntelliJ import feature in https://eed3si9n.com/sbt-1.4.0 as well.

This might be influenced by my own personal situation where I tend to hop between one build to another all the time:

```
$ ls -l ~/work | wc -l
     155
$ ls -l ~/work/plugins | wc -l
      46
$ ls -l ~/work/sbt-modules | wc -l
      36
```

In general, I think the user interface that started a daemon program should provide a way of shutting down the daemon. Currently the only UI we have for shutdown is `sbtn shutdown`.

For those users who want to interact with some build primarily via IntelliJ (or Metals), the fact that build is done via sbt is an implementation detail they can happily forget once their code tab completes. For them, I don't think there's a benefit in keeping the server running whereas the downside is needless battery and RAM drain.

**Comment by eatkins** [comment] 2020-11-28 06:24
Thanks for the elaboration. I do see the merits to the workflow the more that I think about it. If I understand correctly, it sounds like intellij would be responsible for checking the state of project/target/active.json and provisionally starting the server? That is actually not an easy problem and it was a nontrivial amount of work to get that reliably. Would every bsp compatible tool have to implement its own version of this logic? A big part of the reason I like doing all of this in `sbt -bsp` is that it standardizes this logic and makes it easy to onboard new tools. A lot of kinks were ironed out in the development of sbtn.

For the intellij use case, sure there are people who may only interact with intellij but I'm sure that many users are using a mix of intellij tools and sbt tasks at the command line. Even if you're only running a few commands in the sbt shell every day, it is really nice to always have a server ready. My viewpoint is that every time I avoid an sbt startup, I smile inside. Every time I have to wait through yet another interminable startup, I frown. As a result, I am motivated to keep the server open unless it is absolutely necessary to close it or the user asked to. But that is perhaps an extreme perspective.

> For them, I don't think there's a benefit in keeping the server running whereas the downside is needless battery and RAM drain.

Fair points in general although sbt now uses almost no cpu while idling and the ram can be swapped out. I haven't noticed either of these problems myself but I also haven't tried to measure it.

**Comment by adpi2** [comment] 2020-11-28 13:28
I am in favor of giving the least responsibility to IntelliJ because of the motivation behind BSP:
> to reduce the effort required by tooling developers to integrate between available IDEs and build tools ([source](https://build-server-protocol.github.io/docs/specification.html#motivation))

So basically if `sbt -bsp` does manage the startup of the sbt server by itself it benefits Metals, IntelliJ and it makes easier for new tools to integrate as well.

> This might be influenced by my own personal situation where I tend to hop between one build to another all the time:
> In general, I think the user interface that started a daemon program should provide a way of shutting down the daemon. Currently the only UI we have for shutdown is sbtn shutdown.

That's a fair point though. I am also having more than 3 sbt projects running almost all the time, jumping from one to another and I don't like:
- having many sbt shells + IDE open all the time
- startup time when sbt is not running anymore

But that's a personal situation and not all people have the same. I wouldn't be surprised that people in the industry work on a single project for months.

I like the idea promoted by @eatkins, that an sbt server should survive its client. Also because I can customize the `serverIdleTimeout` depending on my own usage.

If I work on the same project everyday I would choose a long `serverIdleTimeout`. But if I am jumping from one project to another I would choose a low `serverIdleTimeout`, saving CPU and ram for other projects.

More concretely I think #6177 is the good approach for this issue.

**Comment by eed3si9n** [comment] 2020-11-28 17:54
@eatkins @adpi2 I will defer the decision on this to you guys since you both have more hands-on experience on using BSP.

> If I work on the same project everyday I would choose a long `serverIdleTimeout`. But if I am jumping from one project to another I would choose a low `serverIdleTimeout`, saving CPU and ram for other projects.

That's a good point. The current default is like 7 days? I'd be less concerned if this was like 8h. I would almost want a machine-wide FIFO queue of headless sbt servers with size 1.

**Comment by jastice** [comment] 2020-11-30 09:27
As a side note, the IntelliJ BSP implementations keeps server connections open, across multiple projects, up to a timeout (currently 10 minutes). The BSP server itself is of course free to maintain sbt server instances longer than that, but I'd expect it to be transparent to the clients. The client having to check sbt-specific details and launching the server manually violates this expectation. On the other hand, the client should also be able to directly control server lifetime. 

The way it works right now is fine in regards to this, except for the requirement that sbt be installed on the system and available in the path.

**Comment by ckipp01** [comment] 2020-12-02 07:48
Regarding a couple mentions of the build client shutting down the server, one of the common complaints that we've gotten with Metals, and also common requests, is for it to better manage Bloop and add the option to shut it down on exit (when we've started it). People seem to really dislike something spinning up and staying alive in the background when they are unaware of it. Now if it just sits idle, most won't even notice, but if it starts to eat away at your CPU/RAM, then it's no bueno. 

Sorry we haven't responding to your feature request yet @eatkins! but something I know on the Metals side that we'd want to be really careful of if we did something like this would be to ensure that the `serverIdleTimeout` is easily set and probably defaulted low. I know for myself, it's not uncommon to be in and out of 20 projects in a week easily. I'd hate to have 20 servers kept alive, or even half that. I say this mainly because I actually don't know how to set `serverIdleTimeout` and a quick search on google for `sbt serverIdleTimeout` and a quick look on ~[the sbt server page](https://www.scala-sbt.org/1.x/docs/sbt-server.html)~ (I realize now this was the language server page) returns me nothing. So imo it's safe to say newer users will have no idea how to set this. All this to say, I'd just caution with behavior that keeps the server alive when a BSP client starts it unless it's really clear to the user that it's happening and very clear to them how to control it.

EDIT: From @eed3si9n's point,

> Could we think of a workflow like the follows?:
    - Check if the server is already running by checking for ./project/target/active.json.
    - If the server is running, use .bsp/sbt.json to connect to the running server.
    - If the server is NOT running, IntelliJ can start an instance of sbt session, wait for ./project/target/active.json, and use .bsp/sbt.json to connect to the running server.

O, I also forgot to mention. _If_ this does become the desired flow, I would sort of hope that it could just be easily handled by sbt instead of on the client side. I know that's one thing I really enjoy about Bloop launcher is that I don't really need to have custom logic for these three steps, but instead the launcher will detect if a server is running or not, and if so, just make the bsp connection, if not, start it and then make the connection. That way us on the Metals side and @jastice on the IntelliJ side won't have to duplicate the same logic that you have outlined here. So I agree with the sentiment behind the quote @adpi2 listed.

**Comment by eatkins** [comment] 2020-12-02 15:40
One approach for handling the server idle timeout would be to add logging when a client connection is shut down due to an idle timeout and/or print a message when the server starts up when it was shutdown by the idle timeout the next time it boots. Then you could set a relatively short idle timeout by default but print instructions for the user to configure their build (or global sbt settings) to disable this behavior. Another approach would be to add a setting that's like `bspAutoShutdown` or something that the tool can query with a bsp command. If it's true, the tool will shutdown a server that it launched when it exits, otherwise it would leave it running.

Not to in any way minimize anyone's needs, but I think oss library and tool developers are by far the most likely to be regularly working in multiple sbt repositories. These are also the users who are the most likely to report bugs which makes their use cases overrepresented in issues. I think @adpi2's intuition about industry users is spot on. I worked for 5 years at a company with a monorepo and I never used sbt in any other project until I left that job.

I try to optimize for the single repo user because that is the user who probably understands sbt the least and I want to optimize for their experience. At my old job, scala was only used for a subset of computationally expensive backend jobs. This meant that many developers only occasionally used scala. Their experience was generally quite negative because of the poor sbt performance. It is much easier to teach someone to run `sbt test` then to explain why they probably need to devote a separate terminal to sbt and use `sbt ~test` or keep an open sbt shell. With the thin client, we can dramatically improve things for those kinds of users by having them run `sbt --client test` or `sbtn test`. What I don't like about auto shutdown is that now if one of those users is using metals, they have a good experience where while they iterate on their work, they can quickly run `sbt --client test` in their terminal window. But as soon as they close their editor, all of a sudden the behavior is different and they have to suffer through the sbt startup again. Personally I find inconsistent performance very frustrating and if I didn't know anything about sbt and wasn't particularly inclined to work with it (because I only needed to use scala occasionally), I would begrudgingly use it but be annoyed and try to find ways to not use it. The consequence of this at my old job was that lots of stuff ended up being written in rails that was much better suited to scala because most developers already knew ruby and couldn't easily optimize their workflow with sbt. I figured out how to optimize my workflow so that it was much faster to develop scala than rails but I couldn't get many other developers on board.

**Comment by eatkins** [comment] 2020-12-02 15:45
I should add that the entire scala ecosystem is much better than it was when I was at that job from 2012-2017. Metals didn't even really exist then and would have been a huge improvement for me. All of our tests queried a database so I couldn't develop on my local machine and did all of my work on vim connected to a remote server. As a result, pretty much the only tools I had were syntax highlighting and `sbt ~test` (code navigation was ctrl+z; git grep $method). I made it work, but things are a lot better with metals or intellij (which I didn't use at the time because of the remote database problem).

**Comment by okouyad** [comment] 2021-01-23 10:07
@eatkins My question is a bit unrelated to the specific subject of the issue and i apologies for tha.  I was not sure where to post it for you to see. I'm currently trying to figure out how to use My IDE (Intellij) or any other for the matter as a client, while having SBT running on a remote machine. Same issue as you some work restriction for some member of my team. 

I wonder: 

1 - How did you make that work, back then ? Did you have a file sync software as well ? 

2 - Would it be possible to do that with SBT and BSP today ?

3 - I am researching the issue, if you have any recommendation, i would greatly appreciate

**Comment by jastice** [comment] 2021-02-01 14:49
> @eatkins My question is a bit unrelated to the specific subject of the issue and i apologies for tha. I was not sure where to post it for you to see. I'm currently trying to figure out how to use My IDE (Intellij) or any other for the matter as a client, while having SBT running on a remote machine. 

On IntelliJ side, this isn't really supported at the moment - paths are assumed to be local. so unfortunately BSP won't help with working with remote projects from IntelliJ, for the moment.

**Comment by ianknowles** [comment] 2021-03-02 19:39
Import doesn't work in IntelliJ 2020.3 when IntelliJ is managing SBT (1.4.7) and JDK (12) installs. The only way to successfully import a BSP project is to install standalone versions and include them on system PATH. Otherwise you get the unhelpful `[info] server was not detected. starting an instance` message followed by `Problem executing BSP job.`

Jetbrains issue https://youtrack.jetbrains.com/issue/SCL-18292.

Is IntelliJ failing to set PATH to point at its managed installs? or does SBT ignore them and use the system PATH?

**Comment by adpi2** [comment] 2021-03-03 08:27
@ianknowles In the coming 1.5.0 version of sbt, we use the `--sbt-launch-jar` option to start the sbt server using the IntelliJ managed version, whether sbt is on the path or not.

You can try it out:
1. set `sbt.version=1.5.0-M2` in you `project/build.properties` file
2. remove the `.bsp` folder
3. Re-import the project in IntelliJ: `File > New > Project From Existing Sources... > Select your project folder > BSP`

**Comment by Reeebuuk** [comment] 2021-03-15 08:03
For example moving https://github.com/lunatech-labs/lunatech-scala-2-to-scala3-course/tree/main/exercises to 1.5.0-M2 and removing the dotty plugin didn't help for me.
I'm trying to import it as bsp project and getting the error @ianknowles has. 

BTW have never run Scala 3 or BSP project so maybe there is something related to that as well?

**Comment by adpi2** [comment] 2021-03-15 10:36
@Reeebuuk I tried to reproduce in https://github.com/lunatech-labs/lunatech-scala-2-to-scala3-course/pull/74 and it worked for me.

You can notice that I had to fix the sbt build definition to be able to load sbt.

Does it solve your problem?

**Comment by Reeebuuk** [comment] 2021-03-15 11:00
@adpi2 sorry I wasn't clear enough of where is the issue.
I can also compile it via sbt but intelliJ is getting the error above.

When you say `fix the sbt build definition` what does that imply?

**Comment by adpi2** [comment] 2021-03-15 11:59
> When you say fix the sbt build definition what does that imply?

If you can compile, then it's okay, it should work.

Can you share the content of `.bsp/sbt.json`?

**Comment by Reeebuuk** [comment] 2021-03-15 12:02
Sure no problem.

`{"name":"sbt","version":"1.5.0-M2","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/Users/reee/Library/Java/JavaVirtualMachines/openjdk-15.0.2/Contents/Home/bin/java","-Xms100m","-Xmx100m","-classpath","/Users/reee/Library/Application Support/JetBrains/IntelliJIdea2020.3/plugins/Scala/launcher/sbt-launch.jar","xsbt.boot.Boot","-bsp","--sbt-launch-jar=/Users/reee/Library/Application Support/JetBrains/IntelliJIdea2020.3/plugins/Scala/launcher/sbt-launch.jar"]}`

**Comment by adpi2** [comment] 2021-03-15 12:39
I tried again to reproduce using the same sbt version and IntelliJIdea version than yours, but it seems to work.

So maybe you can try to run:
```
/Users/reee/Library/Java/JavaVirtualMachines/openjdk-15.0.2/Contents/Home/bin/java -Xms100m -Xmx100m -classpath /Users/reee/Library/Application Support/JetBrains/IntelliJIdea2020.3/plugins/Scala/launcher/sbt-launch.jar xsbt.boot.Boot -bsp --sbt-launch-jar=/Users/reee/Library/Application Support/JetBrains/IntelliJIdea2020.3/plugins/Scala/launcher/sbt-launch.jar
```

This is the command that comes from your `.bsp/sbt.json`. You should see something like:
```
[info] server was not detected. starting an instance
[info] welcome to sbt 1.5.0-M2 (AdoptOpenJDK Java 11.0.7)
[info] loading global plugins from /home/piquerez/.sbt/1.0/plugins
[info] loading settings for project exercises-build-build from metals.sbt ...
[info] loading project definition from /home/piquerez/lunatech-labs/lunatech-scala-2-to-scala3-course/exercises/project/project
[info] loading settings for project exercises-build from metals.sbt ...
[info] loading project definition from /home/piquerez/lunatech-labs/lunatech-scala-2-to-scala3-course/exercises/project
[info] compiling 9 Scala sources to /home/piquerez/lunatech-labs/lunatech-scala-2-to-scala3-course/exercises/project/target/scala-2.12/sbt-1.0/classes ...

...
...

[info] sbt server started at local:///home/piquerez/.sbt/1.0/server/928d99a363a3685a5695/sock
[info] started sbt server
```

**Comment by Reeebuuk** [comment] 2021-03-15 12:42
Oho there is some progress...
I have Scala plugin version 2020.3.21 installed.

`reee@Krunoslavs-MacBook-Pro exercises % /Users/reee/Library/Java/JavaVirtualMachines/openjdk-15.0.2/Contents/Home/bin/java -Xms100m -Xmx100m -classpath /Users/reee/Library/Application Support/JetBrains/IntelliJIdea2020.3/plugins/Scala/launcher/sbt-launch.jar xsbt.boot.Boot -bsp --sbt-launch-jar=/Users/reee/Library/Application Support/JetBrains/IntelliJIdea2020.3/plugins/Scala/launcher/sbt-launch.jar
Error: Could not find or load main class Support.JetBrains.IntelliJIdea2020.3.plugins.Scala.launcher.sbt-launch.jar
Caused by: java.lang.ClassNotFoundException: Support.JetBrains.IntelliJIdea2020.3.plugins.Scala.launcher.sbt-launch.jar`

seems that `Application Support` folder wasn't escaped properly so

`reee@Krunoslavs-MacBook-Pro exercises % /Users/reee/Library/Java/JavaVirtualMachines/openjdk-15.0.2/Contents/Home/bin/java -Xms100m -Xmx100m -classpath /Users/reee/Library/"Application Support"/JetBrains/IntelliJIdea2020.3/plugins/Scala/launcher/sbt-launch.jar xsbt.boot.Boot -bsp --sbt-launch-jar=/Users/reee/Library/"Application Support"/JetBrains/IntelliJIdea2020.3/plugins/Scala/launcher/sbt-launch.jar`

is producing just:
`[info] server was not detected. starting an instance`

and exits

**Comment by adpi2** [comment] 2021-03-15 13:22
Ok so clearly sbt does not handle the space in the launch jar path correctly when parsing the option or when launching the server. I am on it.

**Comment by adpi2** [comment] 2021-03-17 16:34
@Reeebuuk can you try to run this in your project:

```
/Users/reee/Library/Java/JavaVirtualMachines/openjdk-15.0.2/Contents/Home/bin/java -Xms100m -Xmx100m -classpath "/Users/reee/Library/Application Support/JetBrains/IntelliJIdea2020.3/plugins/Scala/launcher/sbt-launch.jar" xsbt.boot.Boot -bsp --sbt-launch-jar=/Users/reee/Library/Application%20Support/JetBrains/IntelliJIdea2020.3/plugins/Scala/launcher/sbt-launch.jar
```

**Comment by Reeebuuk** [comment] 2021-03-17 16:42
Works like a charm.

`[info] started sbt server`

**Closed as completed** 2021-03-17 21:44 UTC
Labels: area/server, area/ide
