### ISSUE TITLE
[sbt 1.5.0-M2] testing a project after a source change results in exception

### ISSUE THREAD

**Issue by nunotmalheiro** [sbt/sbt#6339] opened 2021-02-26 11:17 UTC
## steps

1. Create an sbt 1.5.0-M2 project, with scala 3.0.0-RC1 and with scalatest or munit libraries
2. Add an A object in main/scala:

```scala
object A:
  def toInt(s: String): Int =  s.toInt
```

3. Add a testA object in test/scala (munit or scalatest):

```scala
class testA extends munit.FunSuite:
  test("Test toInt") {
    assertEquals(A.toInt("10"), 10)
  }
```

4. test on sbt, and it will test without problem
5. change the source of the testA file to, for instance:

```scala
class testA extends munit.FunSuite:
  test("Test toInt") {
    assertEquals(A.toInt("15"), 15)
  }
```

6. test again on sbt and it will fail with an exception

## problem

The test fails with the following:

```
[error] ## Exception when compiling 1 sources to /tmp/scala3-example-project/target/scala-3.0.0-RC1/test-classes
[error] java.lang.IllegalArgumentException: requirement failed: Source file '/tmp/scala3-example-project/target/scala-3.0.0-RC1/test-classes/testA.tasty' does not exist.
[error] scala.Predef$.require(Predef.scala:281)
[error] sbt.io.IO$.copyFile(IO.scala:895)
[error] sbt.io.IO$.move(IO.scala:1118)
[error] sbt.internal.inc.ClassFileManager$TransactionalClassFileManager.move(ClassFileManager.scala:241)
[error] sbt.internal.inc.ClassFileManager$TransactionalClassFileManager.$anonfun$deleteImpl$6(ClassFileManager.scala:200)
[error] scala.collection.Iterator.foreach(Iterator.scala:943)
[error] scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] sbt.internal.inc.ClassFileManager$TransactionalClassFileManager.deleteImpl(ClassFileManager.scala:200)
[error] sbt.internal.inc.ClassFileManager$TransactionalClassFileManager.delete(ClassFileManager.scala:191)
[error] xsbti.compile.WrappedClassFileManager.delete(WrappedClassFileManager.java:45)
[error] sbt.internal.inc.IncrementalCommon$.pruneClassFilesOfInvalidations(IncrementalCommon.scala:840)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:93)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:501)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:587)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:491)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2301)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2258)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2254)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] java.base/java.lang.Thread.run(Thread.java:834)
[error]            
[error] stack trace is suppressed; run last Test / compileIncremental for the full output
[error] (Test / compileIncremental) java.lang.IllegalArgumentException: requirement failed: Source file '/tmp/scala3-example-project/target/scala-3.0.0-RC1/test-classes/testA.tasty' does not exist.
[error] Total time: 0 s, completed Feb 26, 2021, 11:04:12 AM`
```

The exception says that the tasty file does not exist, but it does exist. If the tasty file is removed by and if the clean command is issued before the test, the test succeeds,
This problem does not exist with sbt 1.4.7 and dotty plugin.

## expectation

The tests should succeed.
This is not a problem with the compile command. If I compile and then change the code and compile again, the compilation is successful.

**Comment by eed3si9n** [comment] 2021-02-26 17:47
I think this is a duplicate of https://github.com/sbt/zinc/issues/964, which @adpi2 fixed in https://github.com/sbt/zinc/pull/965

**Closed as completed by eed3si9n** 2021-02-26 17:47 UTC
Labels: area/scala3
