### ISSUE TITLE
Cached resolution: OutOfMemoryException

### ISSUE THREAD

**Issue by rtimush** [sbt/sbt#1721] opened 2014-11-11 17:41 UTC
On a rather complex project with many subproject and dependencies, running `update` with cached resolution fails with OutOfMemoryException even with 3GB heap (without cached resolution it definitely doesn't fail on 2GB and probably will work with 1GB).

Memory dump analysis shows that a 700MB byte array was created and held under `sbinary.JavaOutput`.

It would be nice if this array was at least split into pieces.

SBT version: 0.13.7-RC3

**Comment by OlegYch** [comment] 2015-02-10 15:44
here are my numbers:
in a build consisting of about 20 projects with cached resolution enabled the size of the cache (in streams/$global/update) reaches 190 mbs for the largest project, by comparison the jar created with sbt-assembly for that project is around 150 mbs
enabling cached resolution causes 'update' to run out of 3gb heap (normally compile on the same project takes around 2gbs), and also causes 'compile' with no modified sources to take ~20s instead of ~5s
on the bright side, update with cached resolution takes about 15s and 150s without it

**Comment by easel** [comment] 2015-02-27 02:56
I'm seeing the same thing on 13.7 and 13.8-M5, roughly 10 sub-projects and sbt update won't complete without -Xmx > 3.5g.

**Comment by eed3si9n** [comment] 2015-02-27 03:22
I wonder if this is a variant of #1760.
Also anyone has public project I can run to reproduce? #1763 came with repro test.

**Comment by OlegYch** [comment] 2015-02-27 08:57
yes im pretty sure this is the same as #1763

**Comment by easel** [comment] 2015-02-27 18:41
Pretty sure this is the same issue as #1763, i saw that first and ended up posting on this one.

**Comment by eed3si9n** [comment] 2015-02-27 18:44
I am closing this in favor of #1763 since that one comes with repro steps.

**Closed as completed by eed3si9n** 2015-02-27 18:44 UTC
Labels: area/library_management
