### ISSUE TITLE
Contributor handbook (developer guide)

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3552] opened 2017-09-16 19:24 UTC
We should review and update developer guide in terms of:
- which repos to check out
- how to build sbt from source
- how to test freshly baked sbt locally
- where to send pr

**Comment by jvican** [comment] 2017-09-17 14:45
In my experience, contributors usually get OOM exceptions when running the test suite. Would be good to show them how to work around that too.

**Comment by dwijnand** [comment] 2018-07-02 13:16
Duplicate of #3950

**Closed as completed by dwijnand** 2018-07-02 13:16 UTC
Labels: documentation
