### ISSUE TITLE
whatDependsOn creates very large string and OOMs on large project

### ISSUE THREAD

**Issue by will-sargent-eero** [sbt/sbt#7360] opened 2023-08-24 18:45 UTC
## steps

Have a very large project
Use `whatDependsOn`

## problem

```
[actorcluster] $ whatDependsOn org.slf4j slf4j-api 2.0.0-alpha1
[warn] /Users/wsargen/.eero/artifactory-write.credentials not found, please add to filesystem if you wish to write to artifactory
[info] shutting down sbt server
java.lang.OutOfMemoryError: Required array length 2147483639 + 47 is too large
	at java.base/jdk.internal.util.ArraysSupport.hugeLength(ArraysSupport.java:649)
	at java.base/jdk.internal.util.ArraysSupport.newLength(ArraysSupport.java:642)
	at java.base/java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:257)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:229)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:582)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:179)
	at scala.collection.mutable.StringBuilder.append(StringBuilder.scala:203)
	at scala.collection.TraversableOnce$appender$1.apply(TraversableOnce.scala:419)
	at scala.collection.TraversableOnce$appender$1.apply(TraversableOnce.scala:410)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableOnce.addString(TraversableOnce.scala:424)
	at scala.collection.TraversableOnce.addString$(TraversableOnce.scala:407)
	at scala.collection.AbstractTraversable.addString(Traversable.scala:108)
	at scala.collection.TraversableOnce.mkString(TraversableOnce.scala:377)
	at scala.collection.TraversableOnce.mkString$(TraversableOnce.scala:376)
	at scala.collection.AbstractTraversable.mkString(Traversable.scala:108)
	at scala.collection.TraversableOnce.mkString(TraversableOnce.scala:379)
	at scala.collection.TraversableOnce.mkString$(TraversableOnce.scala:379)
	at scala.collection.AbstractTraversable.mkString(Traversable.scala:108)
	at sbt.internal.Graph$.toAscii(SettingGraph.scala:124)
	at sbt.internal.graph.rendering.AsciiTree$.$anonfun$asciiTree$1(AsciiTree.scala:29)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at sbt.internal.graph.rendering.AsciiTree$.asciiTree(AsciiTree.scala:23)
	at sbt.plugins.DependencyTreeSettings$.$anonfun$baseFullReportingSettings$21(DependencyTreeSettings.scala:147)
	at scala.collection.immutable.List.map(List.scala:293)
	at sbt.plugins.DependencyTreeSettings$.$anonfun$baseFullReportingSettings$18(DependencyTreeSettings.scala:145)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
	at sbt.Execute.work(Execute.scala:292)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
[error] [launcher] error during sbt launcher: java.lang.OutOfMemoryError: Required array length 2147483639 + 47 is too large
```

## expectation

no oom plz

**Comment by eed3si9n** [comment] 2023-09-05 15:31
Thanks for the report.
Not sure if it's at all related, but there's also https://github.com/sbt/sbt/issues/6886

**Comment by will-sargent-eero** [comment] 2023-09-05 20:57
#6886 sounds very similar

**Comment by SethTisue** [comment] 2024-11-20 13:51
it seems like a reasonably safe bet that this is a duplicate of #6886

**Closed as not planned** 2024-11-20 13:53 UTC
Labels: Duplicate, area/library_management
