### ISSUE TITLE
Sbt always adds `-bootclasspath`, even if there is one

### ISSUE THREAD

**Issue by dragos** [sbt/sbt#762] opened 2013-05-22 12:08 UTC
This may not be the preferred way to pass a different Scala library, but I need to do this from the Eclipse plugin. On the command line, one can use `-bootclasspath` to tell the compiler to use a different Scala library than the one used to _run_ the compiler.

I noticed that Sbt can "port" some entries in the `-classpath` to `-bootclasspath`, but it looks for a jar named `scala-library`. The Scala library can be a class folder, for example when developing the compiler inside an IDE, the library is simply the output folder of the library project.

build.sbt:

```
name := "foo"

scalacOptions ++= "-bootclasspath" :: "/tmp/nonexistant" :: Nil
```

When I set the log level to debug, I see that Sbt adds the bootclasspath anyway:

```
[debug] Calling Scala compiler with arguments  (CompilerInterface):
[debug]     -bootclasspath
[debug]     /tmp/nonexistant
[debug]     -d
[debug]     /Volumes/Thunderbolt_SSD/dragos/workspace/sbt-test/target/scala-2.9.2/classes
[debug]     -bootclasspath
[debug]     /Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/lib/JObjC.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/jre/classes:/Users/dragos/.sbt/boot/scala-2.9.2/lib/scala-library.jar
[debug]     -classpath
[debug]     /Volumes/Thunderbolt_SSD/dragos/workspace/sbt-test/target/scala-2.9.2/classes
```

**Comment by louisjiang** [comment] 2016-10-26 09:27
[debug] Calling Scala compiler with arguments  (CompilerInterface):
[debug] 	-language:implicitConversions
[debug] 	-bootclasspath
[debug] 	/root/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.8.jar:/root/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.8.jar:/root/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.8.jar
[debug] 	-bootclasspath
[debug] 	/usr/local/java/jdk1.8.0_77/jre/lib/resources.jar:/usr/local/java/jdk1.8.0_77/jre/lib/rt.jar:/usr/local/java/jdk1.8.0_77/jre/lib/sunrsasign.jar:/usr/local/java/jdk1.8.0_77/jre/lib/jsse.jar:/usr/local/java/jdk1.8.0_77/jre/lib/jce.jar:/usr/local/java/jdk1.8.0_77/jre/lib/charsets.jar:/usr/local/java/jdk1.8.0_77/jre/lib/jfr.jar:/usr/local/java/jdk1.8.0_77/jre/classes:/root/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.8.jar
[debug] 	-classpath
[debug] 	/workspace/totem/totem-example/target/scala-2.11/classes:/workspace/totem/totem-processor/target/scala-2.11/classes:/workspace/totem/totem-invoker/target/scala-2.11/classes:/workspace/totem/totem-protocol/target/scala-2.11/classes:/workspace/totem/totem-lang/target/scala-2.11/classes:/workspace/totem/totem-serialization/target/scala-2.11/classes:/workspace/totem/totem-annotation/target/scala-2.11/classes:/workspace/totem/totem-akka-transport-netty4/target/scala-2.11/classes:/workspace/totem/totem-registry/target/scala-2.11/classes:/workspace/totem/totem-cluster-invoker/target/scala-2.11/classes:/workspace/totem/totem-plugin/target/scala-2.11/classes:/workspace/totem/totem-cache/target/scala-2.11/classes:/workspace/totem/totem-store/target/scala-2.11/classes:/workspace/totem/totem-scheduler/target/scala-2.11/aspectj/classes:/root/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.8.jar:/root/.ivy2/cache/org.log4s/log4s_2.11/jars/log4s_2.11-1.3.0.jar:/root/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.21.jar:/root/.ivy2/cache/org.apache.logging.log4j/log4j-api/jars/log4j-api-2.5.jar:/root/.ivy2/cache/org.apache.logging.log4j/log4j-core/jars/log4j-core-2.5.jar:/root/.ivy2/cache/org.apache.logging.log4j/log4j-slf4j-impl/jars/log4j-slf4j-impl-2.5.jar:/root/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-3.0.1.jar:/root/.ivy2/cache/com.esotericsoftware/reflectasm/bundles/reflectasm-1.11.3.jar:/root/.ivy2/cache/org.ow2.asm/asm-all/jars/asm-all-5.1.jar:/root/.ivy2/cache/org.javassist/javassist/bundles/javassist-3.20.0-GA.jar:/root/.ivy2/cache/org.objenesis/objenesis/jars/objenesis-2.4.jar:/root/.ivy2/cache/com.alibaba/fastjson/jars/fastjson-1.2.17.jar:/root/.ivy2/cache/com.lmax/disruptor/jars/disruptor-3.3.5.jar:/root/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.9.4.jar:/root/.ivy2/cache/org.joda/joda-convert/jars/joda-convert-1.8.1.jar:/root/.ivy2/cache/org.xerial.snappy/snappy-java/bundles/snappy-java-1.1.2.6.jar:/root/.ivy2/cache/net.jpountz.lz4/lz4/jars/lz4-1.3.0.jar:/root/.ivy2/cache/com.esotericsoftware/kryo/bundles/kryo-4.0.0.jar:/root/.ivy2/cache/org.apache.commons/commons-pool2/jars/commons-pool2-2.4.2.jar:/root/.ivy2/cache/javax.inject/javax.inject/jars/javax.inject-1.jar:/root/.ivy2/cache/io.netty/netty-all/jars/netty-all-4.1.5.Final.jar:/root/.ivy2/cache/io.netty/netty/bundles/netty-3.10.6.Final.jar:/root/.ivy2/cache/com.typesafe.akka/akka-cluster_2.11/jars/akka-cluster_2.11-2.4.11.jar:/root/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.11/jars/akka-slf4j_2.11-2.4.11.jar:/root/.ivy2/cache/org.isomorphism/token-bucket/jars/token-bucket-1.7.jar:/root/.ivy2/cache/com.typesafe.akka/akka-http-experimental_2.11/jars/akka-http-experimental_2.11-2.4.11.jar:/root/.ivy2/cache/io.dropwizard.metrics/metrics-core/bundles/metrics-core-3.1.2.jar:/root/.ivy2/cache/org.fusesource.leveldbjni/leveldbjni-linux64/jars/leveldbjni-linux64-1.8.jar:/root/.ivy2/cache/org.rocksdb/rocksdbjni/jars/rocksdbjni-4.11.2.jar:/root/.ivy2/cache/com.github.pathikrit/better-files_2.11/jars/better-files_2.11-2.16.0.jar:/root/.ivy2/cache/com.github.ben-manes.caffeine/caffeine/jars/caffeine-2.3.3.jar:/root/.ivy2/cache/org.aspectj/aspectjrt/jars/aspectjrt-1.8.9.jar:/root/.ivy2/cache/org.quartz-scheduler/quartz/jars/quartz-2.2.3.jar:/root/.ivy2/cache/org.jsoup/jsoup/jars/jsoup-1.9.2.jar:/root/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.4.jar:/root/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.8.jar:/root/.ivy2/cache/com.esotericsoftware/minlog/bundles/minlog-1.3.0.jar:/root/.ivy2/cache/com.typesafe.akka/akka-remote_2.11/jars/akka-remote_2.11-2.4.11.jar:/root/.ivy2/cache/com.google.guava/guava/bundles/guava-18.0.jar:/root/.ivy2/cache/com.typesafe.akka/akka-http-core_2.11/jars/akka-http-core_2.11-2.4.11.jar:/root/.ivy2/cache/org.fusesource.leveldbjni/leveldbjni/jars/leveldbjni-1.8.jar:/root/.ivy2/cache/c3p0/c3p0/jars/c3p0-0.9.1.1.jar:/root/.ivy2/cache/io.aeron/aeron-driver/jars/aeron-driver-1.0.1.jar:/root/.ivy2/cache/org.uncommons.maths/uncommons-maths/jars/uncommons-maths-1.2.2a.jar:/root/.ivy2/cache/com.typesafe.akka/akka-protobuf_2.11/jars/akka-protobuf_2.11-2.4.11.jar:/root/.ivy2/cache/com.typesafe.akka/akka-stream_2.11/jars/akka-stream_2.11-2.4.11.jar:/root/.ivy2/cache/com.typesafe.akka/akka-parsing_2.11/jars/akka-parsing_2.11-2.4.11.jar:/root/.ivy2/cache/org.iq80.leveldb/leveldb-api/jars/leveldb-api-0.6.jar:/root/.ivy2/cache/org.fusesource.hawtjni/hawtjni-runtime/jars/hawtjni-runtime-1.9.jar:/root/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.4.11.jar:/root/.ivy2/cache/io.aeron/aeron-client/jars/aeron-client-1.0.1.jar:/root/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.0.jar:/root/.ivy2/cache/com.typesafe/ssl-config-akka_2.11/bundles/ssl-config-akka_2.11-0.2.1.jar:/root/.ivy2/cache/org.scala-lang.modules/scala-java8-compat_2.11/bundles/scala-java8-compat_2.11-0.7.0.jar:/root/.ivy2/cache/org.agrona/Agrona/jars/Agrona-0.5.4.jar:/root/.ivy2/cache/com.typesafe/ssl-config-core_2.11/bundles/ssl-config-core_2.11-0.2.1.jar:/root/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.4.jar:/root/.ivy2/cache/com.typesafe/config/bundles/config-1.3.0.jar
[debug] Scala compilation took 1.322583056 s
[debug] Attempting to call com.sun.tools.javac.api.JavacTool@5e975486 directly...
java.lang.RuntimeException: java.lang.NoSuchMethodError: scala.collection.JavaConversions$.asScalaSet(Ljava/util/Set;)Lscala/collection/mutable/Set;
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at sbt.compiler.javac.LocalJavaCompiler.run(LocalJava.scala:77)
	at sbt.compiler.javac.JavaCompilerAdapter.compileWithReporter(JavaCompilerAdapter.scala:31)
	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply$mcV$sp(AnalyzingJavaCompiler.scala:65)
	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(AnalyzingJavaCompiler.scala:65)
	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(AnalyzingJavaCompiler.scala:65)
	at sbt.compiler.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:93)
	at sbt.compiler.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:64)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:60)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(MixedAnalyzingCompiler.scala:60)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(MixedAnalyzingCompiler.scala:60)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
	at sbt.compiler.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:59)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
	at sbt.inc.Incremental$.compile(Incremental.scala:71)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:152)
	at sbt.Compiler$.compile(Compiler.scala:138)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:860)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:851)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:849)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: scala.collection.JavaConversions$.asScalaSet(Ljava/util/Set;)Lscala/collection/mutable/Set;
	at io.totem.processor.ApiProcessor.process(ApiProcessor.scala:29)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at sbt.compiler.javac.LocalJavaCompiler.run(LocalJava.scala:77)

**Comment by louisjiang** [comment] 2016-10-26 09:28
```
[debug] Getting org.scala-sbt:compiler-interface:0.13.12:component from component compiler for Scala 2.11.8
[debug] Getting org.scala-sbt:compiler-interface:0.13.12:component from component compiler for Scala 2.11.8
[debug] Running cached compiler 45741bb1, interfacing (CompilerInterface) with Scala compiler version 2.11.8
[debug] Calling Scala compiler with arguments  (CompilerInterface):
[debug]     -language:implicitConversions
[debug]     -bootclasspath
[debug]     /root/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.8.jar:/root/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.8.jar:/root/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.8.jar
[debug]     -bootclasspath
[debug]     /usr/local/java/jdk1.8.0_77/jre/lib/resources.jar:/usr/local/java/jdk1.8.0_77/jre/lib/rt.jar:/usr/local/java/jdk1.8.0_77/jre/lib/sunrsasign.jar:/usr/local/java/jdk1.8.0_77/jre/lib/jsse.jar:/usr/local/java/jdk1.8.0_77/jre/lib/jce.jar:/usr/local/java/jdk1.8.0_77/jre/lib/charsets.jar:/usr/local/java/jdk1.8.0_77/jre/lib/jfr.jar:/usr/local/java/jdk1.8.0_77/jre/classes:/root/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.8.jar
[debug]     -classpath
[debug]     /workspace/totem/totem-example/target/scala-2.11/classes:/workspace/totem/totem-processor/target/scala-2.11/classes:/workspace/totem/totem-invoker/target/scala-2.11/classes:/workspace/totem/totem-protocol/target/scala-2.11/classes:/workspace/totem/totem-lang/target/scala-2.11/classes:/workspace/totem/totem-serialization/target/scala-2.11/classes:/workspace/totem/totem-annotation/target/scala-2.11/classes:/workspace/totem/totem-akka-transport-netty4/target/scala-2.11/classes:/workspace/totem/totem-registry/target/scala-2.11/classes:/workspace/totem/totem-cluster-invoker/target/scala-2.11/classes:/workspace/totem/totem-plugin/target/scala-2.11/classes:/workspace/totem/totem-cache/target/scala-2.11/classes:/workspace/totem/totem-store/target/scala-2.11/classes:/workspace/totem/totem-scheduler/target/scala-2.11/aspectj/classes:/root/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.8.jar:/root/.ivy2/cache/org.log4s/log4s_2.11/jars/log4s_2.11-1.3.0.jar:/root/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.21.jar:/root/.ivy2/cache/org.apache.logging.log4j/log4j-api/jars/log4j-api-2.5.jar:/root/.ivy2/cache/org.apache.logging.log4j/log4j-core/jars/log4j-core-2.5.jar:/root/.ivy2/cache/org.apache.logging.log4j/log4j-slf4j-impl/jars/log4j-slf4j-impl-2.5.jar:/root/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-3.0.1.jar:/root/.ivy2/cache/com.esotericsoftware/reflectasm/bundles/reflectasm-1.11.3.jar:/root/.ivy2/cache/org.ow2.asm/asm-all/jars/asm-all-5.1.jar:/root/.ivy2/cache/org.javassist/javassist/bundles/javassist-3.20.0-GA.jar:/root/.ivy2/cache/org.objenesis/objenesis/jars/objenesis-2.4.jar:/root/.ivy2/cache/com.alibaba/fastjson/jars/fastjson-1.2.17.jar:/root/.ivy2/cache/com.lmax/disruptor/jars/disruptor-3.3.5.jar:/root/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.9.4.jar:/root/.ivy2/cache/org.joda/joda-convert/jars/joda-convert-1.8.1.jar:/root/.ivy2/cache/org.xerial.snappy/snappy-java/bundles/snappy-java-1.1.2.6.jar:/root/.ivy2/cache/net.jpountz.lz4/lz4/jars/lz4-1.3.0.jar:/root/.ivy2/cache/com.esotericsoftware/kryo/bundles/kryo-4.0.0.jar:/root/.ivy2/cache/org.apache.commons/commons-pool2/jars/commons-pool2-2.4.2.jar:/root/.ivy2/cache/javax.inject/javax.inject/jars/javax.inject-1.jar:/root/.ivy2/cache/io.netty/netty-all/jars/netty-all-4.1.5.Final.jar:/root/.ivy2/cache/io.netty/netty/bundles/netty-3.10.6.Final.jar:/root/.ivy2/cache/com.typesafe.akka/akka-cluster_2.11/jars/akka-cluster_2.11-2.4.11.jar:/root/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.11/jars/akka-slf4j_2.11-2.4.11.jar:/root/.ivy2/cache/org.isomorphism/token-bucket/jars/token-bucket-1.7.jar:/root/.ivy2/cache/com.typesafe.akka/akka-http-experimental_2.11/jars/akka-http-experimental_2.11-2.4.11.jar:/root/.ivy2/cache/io.dropwizard.metrics/metrics-core/bundles/metrics-core-3.1.2.jar:/root/.ivy2/cache/org.fusesource.leveldbjni/leveldbjni-linux64/jars/leveldbjni-linux64-1.8.jar:/root/.ivy2/cache/org.rocksdb/rocksdbjni/jars/rocksdbjni-4.11.2.jar:/root/.ivy2/cache/com.github.pathikrit/better-files_2.11/jars/better-files_2.11-2.16.0.jar:/root/.ivy2/cache/com.github.ben-manes.caffeine/caffeine/jars/caffeine-2.3.3.jar:/root/.ivy2/cache/org.aspectj/aspectjrt/jars/aspectjrt-1.8.9.jar:/root/.ivy2/cache/org.quartz-scheduler/quartz/jars/quartz-2.2.3.jar:/root/.ivy2/cache/org.jsoup/jsoup/jars/jsoup-1.9.2.jar:/root/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.4.jar:/root/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.8.jar:/root/.ivy2/cache/com.esotericsoftware/minlog/bundles/minlog-1.3.0.jar:/root/.ivy2/cache/com.typesafe.akka/akka-remote_2.11/jars/akka-remote_2.11-2.4.11.jar:/root/.ivy2/cache/com.google.guava/guava/bundles/guava-18.0.jar:/root/.ivy2/cache/com.typesafe.akka/akka-http-core_2.11/jars/akka-http-core_2.11-2.4.11.jar:/root/.ivy2/cache/org.fusesource.leveldbjni/leveldbjni/jars/leveldbjni-1.8.jar:/root/.ivy2/cache/c3p0/c3p0/jars/c3p0-0.9.1.1.jar:/root/.ivy2/cache/io.aeron/aeron-driver/jars/aeron-driver-1.0.1.jar:/root/.ivy2/cache/org.uncommons.maths/uncommons-maths/jars/uncommons-maths-1.2.2a.jar:/root/.ivy2/cache/com.typesafe.akka/akka-protobuf_2.11/jars/akka-protobuf_2.11-2.4.11.jar:/root/.ivy2/cache/com.typesafe.akka/akka-stream_2.11/jars/akka-stream_2.11-2.4.11.jar:/root/.ivy2/cache/com.typesafe.akka/akka-parsing_2.11/jars/akka-parsing_2.11-2.4.11.jar:/root/.ivy2/cache/org.iq80.leveldb/leveldb-api/jars/leveldb-api-0.6.jar:/root/.ivy2/cache/org.fusesource.hawtjni/hawtjni-runtime/jars/hawtjni-runtime-1.9.jar:/root/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.4.11.jar:/root/.ivy2/cache/io.aeron/aeron-client/jars/aeron-client-1.0.1.jar:/root/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.0.jar:/root/.ivy2/cache/com.typesafe/ssl-config-akka_2.11/bundles/ssl-config-akka_2.11-0.2.1.jar:/root/.ivy2/cache/org.scala-lang.modules/scala-java8-compat_2.11/bundles/scala-java8-compat_2.11-0.7.0.jar:/root/.ivy2/cache/org.agrona/Agrona/jars/Agrona-0.5.4.jar:/root/.ivy2/cache/com.typesafe/ssl-config-core_2.11/bundles/ssl-config-core_2.11-0.2.1.jar:/root/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.4.jar:/root/.ivy2/cache/com.typesafe/config/bundles/config-1.3.0.jar
[debug] Scala compilation took 1.322583056 s
[debug] Attempting to call com.sun.tools.javac.api.JavacTool@5e975486 directly...
java.lang.RuntimeException: java.lang.NoSuchMethodError: scala.collection.JavaConversions$.asScalaSet(Ljava/util/Set;)Lscala/collection/mutable/Set;
    at com.sun.tools.javac.main.Main.compile(Main.java:553)
    at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
    at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
    at sbt.compiler.javac.LocalJavaCompiler.run(LocalJava.scala:77)
    at sbt.compiler.javac.JavaCompilerAdapter.compileWithReporter(JavaCompilerAdapter.scala:31)
    at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply$mcV$sp(AnalyzingJavaCompiler.scala:65)
    at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(AnalyzingJavaCompiler.scala:65)
    at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(AnalyzingJavaCompiler.scala:65)
    at sbt.compiler.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:93)
    at sbt.compiler.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:64)
    at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:60)
    at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(MixedAnalyzingCompiler.scala:60)
    at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(MixedAnalyzingCompiler.scala:60)
    at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
    at sbt.compiler.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:59)
    at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
    at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
    at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
    at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
    at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
    at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
    at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
    at sbt.inc.Incremental$.compile(Incremental.scala:71)
    at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
    at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
    at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
    at sbt.Compiler$.compile(Compiler.scala:152)
    at sbt.Compiler$.compile(Compiler.scala:138)
    at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:860)
    at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:851)
    at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:849)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: scala.collection.JavaConversions$.asScalaSet(Ljava/util/Set;)Lscala/collection/mutable/Set;
    at io.totem.processor.ApiProcessor.process(ApiProcessor.scala:29)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
    at com.sun.tools.javac.main.Main.compile(Main.java:523)
    at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
    at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
    at sbt.compiler.javac.LocalJavaCompiler.run(LocalJava.scala:77)
    at sbt.compiler.javac.JavaCompilerAdapter.compileWithReporter(JavaCompilerAdapter.scala:31)
    at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply$mcV$sp(AnalyzingJavaCompiler.scala:65)
    at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(AnalyzingJavaCompiler.scala:65)
    at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(AnalyzingJavaCompiler.scala:65)
    at sbt.compiler.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:93)
    at sbt.compiler.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:64)
    at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:60)
```

**Comment by jvican** [comment] 2017-07-07 11:41
@dragos Was this fixed at any point or do you still want this to be fixed?

**Comment by dragos** [comment] 2017-07-07 13:24
I don't think it was fixed, but I haven't tried it recently. Feel free to move to the backlog or close as won't fix :)

**Comment by jvican** [comment] 2017-07-07 15:20
Do you think this is worth fixing? :) If the use case doesn't really make sense anymore (because we have better tools), we may want to close it or put it in the backlog as you said. If you think it can still be useful I'll port it to Zinc's repository.

**Comment by dragos** [comment] 2017-07-07 19:08
I don't think this is hard to fix, and it would help anyone who tries to integrate with Zinc... so I'd vote for a fix rather than a won't fix.

**Comment by jvican** [comment] 2017-07-08 14:22
Ported to Zinc, this can be closed.

**Closed as completed** 2017-07-08 14:37 UTC
Labels: area/incremental_compiler
