### ISSUE TITLE
sbt download link not functioning

### ISSUE THREAD

**Issue by JoeHegarty** [sbt/sbt#3108] opened 2017-04-16 19:28 UTC
## steps
Attempt to download SBT from the official website: http://www.scala-sbt.org/download.html

For example:
```
$ wget https://dl.bintray.com/sbt/native-packages/sbt/0.13.15/sbt-0.13.15.tgz
```
## problem
Returns 403 Forbidden. This is also true of the zip package
```
$ wget https://dl.bintray.com/sbt/native-packages/sbt/0.13.15/sbt-0.13.15.tgz
--2017-04-16 12:25:58--  https://dl.bintray.com/sbt/native-packages/sbt/0.13.15/sbt-0.13.15.tgz
Resolving dl.bintray.com... 108.168.243.150
Connecting to dl.bintray.com|108.168.243.150|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2017-04-16 12:25:58 ERROR 403: Forbidden.
```
## expectation
Download link should function as expected

## notes
I've confirmed this is happening when I request from various ISPs so it doesn't seem specific to me.

**Comment by olafurpg** [comment] 2017-04-16 19:55
I'm getting 403 errors too when resolving other bintray-hosted sbt plugins, for example sbt-site 1.2.0 https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbt/sbt-site/scala_2.10/sbt_0.13/1.2.0/ivys/ivy.xml ( cc/ https://github.com/scalameta/tutorial/issues/11). I thought bintray might be down, but http://status.bintray.com/ says it's not.

**Comment by eed3si9n** [comment] 2017-04-16 19:57
Bintray has put on rate-limit on sbt organization. I'm guessing that we have gone over some OSS allowance.

**Comment by jvican** [comment] 2017-04-16 20:02
I'm getting the same error too when resolving sbt-pgp.

**Comment by emaxedon** [comment] 2017-04-16 20:19
Phew, ok it's not just me. xD

**Comment by bitsnaps** [comment] 2017-04-16 21:25
I'm getting the same error from binary, is there any way to build sbt from source?

**Comment by jvican** [comment] 2017-04-17 11:27
@eed3si9n Have you contacted Bintray to solve this issue?
  
My CI is blocked on this: https://platform-ci.scala-lang.org/scalacenter/sbt-release-early/32. I cannot push local commits and release versions of my plugin until CI is green.

**Comment by eed3si9n** [comment] 2017-04-17 14:05
Yes. The rate-limiting has been lifted.

**Comment by jvican** [comment] 2017-04-17 14:06
Thank you. I confirm it's gone.

**Comment by eed3si9n** [comment] 2017-04-17 18:52
Bintray is putting rate-limit on again..

**Comment by evictor** [comment] 2017-04-17 19:32
Long term solution planned for this?

EDIT (to not cause further notifs): This is happening for me right now while building out a new CI.

**Comment by levismiller** [comment] 2017-04-17 20:17
I'm getting the 503 again now as well

**Comment by kpmeen** [comment] 2017-04-17 20:24
Only noticed this because I updated to the latest versions of some plugins. It's possible to continue working locally with old versions, but CI breaks.

**Comment by evictor** [comment] 2017-04-17 20:36
It would be nice if there were binaries available at mirrors instead of the one bintray source that keeps 403ing. I Googled a little bit but I can't find mirrors.

**Comment by eed3si9n** [comment] 2017-04-17 20:41
Here are the installers for 0.13.15:

https://downloads.typesafe.com/sbt/0.13.15/sbt-0.13.15.tgz
https://downloads.typesafe.com/sbt/0.13.15/sbt-0.13.15.zip
https://downloads.typesafe.com/sbt/0.13.15/sbt-0.13.15.msi

**Comment by ScottTRogers** [comment] 2017-04-17 21:07
It is currently working again.

**Comment by eed3si9n** [comment] 2017-04-17 22:08
Our Bintray repositories are operational again. This was apparently caused by our transfer usage quadrupling recently. We will figure out the long term plan going forward.

**Closed as completed by eed3si9n** 2017-04-17 22:08 UTC

**Comment by minnsoe** [comment] 2017-04-19 00:48
Bintray is 403ing again. The brew formula for sbt pulls from bintray and `brew install sbt` is failing as a result.

**Comment by eed3si9n** [comment] 2017-04-19 06:20
Homebrew is now switched to use GitHub Releases.

**Comment by John-Steidley** [comment] 2017-04-19 18:17
@eed3si9n "This was apparently caused by our transfer usage quadrupling recently."

This is probably related to the massive change in package size. `sbt-0.13.13.deb` is 1 MB, `sbt-0.13.15.deb` is 66.9MB.

**Comment by outime** [comment] 2017-04-27 08:11
It's happening again.

**Comment by asdreno** [comment] 2017-04-27 09:17
Getting a 403 when trying to access: https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.play/sbt-plugin/scala_2.10/sbt_0.13/2.5.14/ivys/ivy.xml

**Comment by omervk** [comment] 2017-04-27 09:20
+1. Trying to get https://dl.bintray.com/sbt/native-packages/sbt/0.13.13/sbt-0.13.13.zip 403's.

**Comment by jhoffma** [comment] 2017-04-27 09:43
Hey guys! Pls do something with it. Can't download https://dl.bintray.com/sbt/sbt-plugin-releases/com.github.gseitz/sbt-release/scala_2.10/sbt_0.13/1.0.3/jars/sbt-release.jar. My CI is failing...

**Comment by kpmeen** [comment] 2017-04-27 10:14
this is starting to become really troublesome :-(

**Comment by omervk** [comment] 2017-04-27 10:58
Looks like it's working at the moment

**Comment by syndbg** [comment] 2017-07-19 09:12
Rate limit issues with bintray again.

**Comment by OutToLearn** [comment] 2017-12-30 11:28
Not able to download the SBT from the website all of this week. :(

**Comment by onelogindavidkayal** [comment] 2017-12-30 18:09
I had to comment out the repo to make things on my system happy for now:

`
root@DavidMint ~ # grep -R dl.bintray.com /etc/apt
/etc/apt/sources.list.d/nekomit-originals.list:#deb https://dl.bintray.com/nekomit/deb-originals xenial main
`

When can I re-enable this repo?

**Comment by eed3si9n** [comment] 2018-01-02 20:35
@OutToLearn @onelogindavidkayal 

I am not aware of any Bintray issues as of today. Which repository or URLs are you guys having problem?

**Comment by roman3017** [comment] 2018-01-15 01:44
When running `apt update` on xenial:

```
E: The repository 'https://dl.bintray.com/sbt/debian  Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by eed3si9n** [comment] 2018-01-15 03:25
I just recalculated the signature.

**Comment by roman3017** [comment] 2018-01-15 05:28
@eed3si9n: It works now, thank you very much.

**Comment by kdbeall** [comment] 2018-02-09 22:00
@eed3si9n 

```E: The repository 'https://dl.bintray.com/sbt/debian  Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by kdbeall** [comment] 2018-02-09 22:01
@eed3si9n Having the same issue as @roman3017

**Comment by eed3si9n** [comment] 2018-02-09 22:06
Let me recalculate the signature.

**Comment by kdbeall** [comment] 2018-02-09 22:17
@eed3si9n Can this process be automated?

**Comment by eed3si9n** [comment] 2018-02-09 22:18
Well it's supposed to be automated, but Bintray seems to be messing it up.

**Comment by Iro2412** [comment] 2018-03-08 15:54
Please the same problem is happening again : 
W: The repository 'https://dl.bintray.com/sbt/debian  Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Help ! Thank you

**Comment by ghost** [comment] 2018-04-24 11:49
We have massive problems with bintray, too (routing / availability) and our CI is failing too. Is it possible to host the important sbt artifacts on another repository where this stupid restrictions don't apply? (maybe maven central?)

**Comment by ErunamoJAZZ** [comment] 2018-05-12 15:42
I am getting the same error in debian.

**Comment by jarrodu** [comment] 2019-02-22 13:41
And again. :cry:

**Comment by vvviiimmm** [comment] 2019-05-20 10:04
And again...

**Comment by eed3si9n** [comment] 2019-05-20 15:45
I'll resign again. I don't know how it's losing the signature.
Given that this issue reports various other issues, in the future let's use https://github.com/sbt/sbt/issues/3883 for "E: The repository 'https://dl.bintray.com/sbt/debian  Release' is not signed." issue.
