### ISSUE TITLE
Duplicate JSON-RPC responses

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5612] opened 2020-06-14 19:51 UTC
## steps

Hook sbt server up with Metals

## problem

I have been using metals in a project where I have been testing a new sbt feature and noticed that I am seeing a lot of BSP related errors due to duplicate json responses. It seems like a number of the tasks, e.g. `bspBuildTargetSources` do their own reporting for the request id which causes an error like

```
[error] unmatched json response for requestId Some(2): {"status":"Done","channelName":"network-1","execId":"2","commandQueue":["shell"],"exitCode":0}
```
to be reported.

## expectation

No duplicate JSON-RPC responses

## note

The double reporting is coming from the automatic event logging in MainLoop.scala as part of task evaluation:
https://github.com/sbt/sbt/blob/c3d6260f52dd5594075d3969f7d37ab67e353c5c/main/src/main/scala/sbt/MainLoop.scala#L198-L206
This will duplicate the reporting that is done in the custom task definitions, e.g. https://github.com/sbt/sbt/blob/c3d6260f52dd5594075d3969f7d37ab67e353c5c/main/src/main/scala/sbt/internal/server/BuildServerProtocol.scala#L102-L112

Eugene wrote:
So "Done" is coming from the [sbt/exec](https://www.scala-sbt.org/1.x/docs/sbt-server.html#request) that I added around https://github.com/sbt/sbt/commit/892e25d23f27e56d7b9a1e8609b890a63718f13c and Dale extended it in https://github.com/sbt/sbt/pull/3991.

I guess prior to https://github.com/sbt/sbt/pull/5443, we could assume that all commands are downstream of `sbt/exec` request, but now not so much... so we need a way to mark `Exec` that it requires a "Done" response or not.

_Originally posted by @eatkins in https://github.com/sbt/sbt/pull/5538#issuecomment-643720705_

**Comment by adpi2** [comment] 2020-06-15 07:22
@eatkins @eed3si9n I am really surprised by this behavior and I cannot experience it myself on the current develop branch.

Before the BSP PR #5538 was merged I did #5549 to prevent duplicate response. So basically I have added a `pendingRequests` map in `NetworkChannel` that retains the json-RPC requests that are yet to be answered. As soon as a request is answered by a call to `respondEvent` it is removed from the `pendingRequests` map and it cannot be replied anymore.

In the case of `bspBuildTargetSources`, the `ScalacOptionsResult` is sent first then the `doneEvent` should be filtered out.

@eatkins Can you please share your code so that I can have a look and try to understand what's happening?

**Comment by eed3si9n** [comment] 2020-06-15 14:53
There's now 1.4.0-M1 out of the develop branch as of yesterday.

**Comment by eatkins** [comment] 2020-06-17 15:56
@adpi2 I have experienced this with a simple project on which I have been testing #5620. It is possible that I have introduced a regression in that PR (building your own version of #5620 is a bit annoying so I wouldn't expect you to attempt to debug off of that). Nevertheless, I think logging an error if we attempt to send multiple reports for the same exec is a problem if we also do auto-reporting of execs in MainLoop. The error logging is bothersome and what is happening isn't even an error; it is sbt sanely honoring the fact that a result was already reported and not sending a second report. I see the current error logging as being more like an assertion: useful for debugging but generally not something you want on in production. Perhaps a way to resolve this is to add a flag to `CommandExchange.respondStatus` that suppresses error logging for duplicates? Then we could set that flag to true when it is called in `MainLoop.processCommand`.

**Comment by eatkins** [comment] 2020-06-17 16:00
Oh, I will add that my metals support is provided by coc.nvim. When I open a source file with nvim, eventually some bsp commands run that cause the errors I've described. I was quite surprised that my version of metals was using bsp with sbt at all. I also notice the errors prominently because I have an active sbt session in a different tmux pane of my terminal. Could it be that they aren't as noticeable if you are using vscode or a different ide?

**Comment by adpi2** [comment] 2020-06-18 16:09
Actually the current severity of this log is `debug` and not `error`:
https://github.com/sbt/sbt/blob/9f9bb9daa275458f3e55f87c432c599947a71b69/main/src/main/scala/sbt/internal/server/NetworkChannel.scala#L301-L303

So I think we can close this issue.

**Comment by eed3si9n** [comment] 2020-06-18 16:15
Even if there's a safety net, I think doing

```scala
 StandardMain.exchange.respondStatus(doneEvent) 
```

is no longer a good idea unless we know for sure the request is waiting for it.

**Comment by eatkins** [comment] 2020-06-21 19:28
I'm not seeing this anymore so I am going to close this.

**Closed as completed by eatkins** 2020-06-21 19:28 UTC
Labels: area/server
