### ISSUE TITLE
https://dl.bintray.com/sbt/debian/InRelease  403  Forbidden

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#6584] opened 2021-07-08 07:54 UTC
## steps
CI is failing due to the error. 
https://dl.bintray.com/sbt/debian/InRelease  403  Forbidden
The repository 'https://dl.bintray.com/sbt/debian  InRelease' is not signed.

**Comment by SethTisue** [comment] 2021-07-08 16:56
duplicate of #6582 and #6583

**Closed as completed by SethTisue** 2021-07-08 16:56 UTC
Labels: Duplicate
