### ISSUE TITLE
Nondeterministic NPE in sbt.internal.util.StringTypeTag$.typeToString

### ISSUE THREAD

**Issue by tpolecat** [sbt/sbt#3714] opened 2017-11-05 21:18 UTC
This happened on Travis with the tpolecat/tut build on 0.6.x at commit 24912ffd211b5f4a2aa1e8b138912c3b5f52fc87. 

Can't reproduce. It's nondeterministic. So just FYI in case it's something obvious, otherwise feel free to close.

```scala
# Executing command line:
java
-Xms2048M
-Xmx2048M
-Xss6M
-XX:MaxPermSize=512M
-jar
/home/travis/.sbt/launchers/1.0.0-RC3/sbt-launch.jar
++2.13.0-M1
core/compile
core/publishLocal
...

[info] Updating {file:/home/travis/build/tpolecat/tut/}core...
[info] Done updating.
[error] java.lang.NullPointerException
[error] 	at sbt.internal.util.StringTypeTag$.typeToString(StringTypeTag.scala:27)
[error] 	at sbt.internal.util.StringTypeTag$.apply(StringTypeTag.scala:15)
[error] 	at sbt.internal.util.ManagedLogger.registerStringCodec(ManagedLogger.scala:39)
[error] 	at sbt.internal.util.ManagedLogger.<init>(ManagedLogger.scala:45)
[error] 	at sbt.util.LogExchange.logger(LogExchange.scala:32)
[error] 	at sbt.internal.LogManager$.defaultLogger(LogManager.scala:122)
[error] 	at sbt.internal.LogManager$DefaultLogManager.apply(LogManager.scala:99)
[error] 	at sbt.internal.LogManager$.$anonfun$construct$1(LogManager.scala:47)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:173)
[error] 	at sbt.std.TaskStreams.log(Streams.scala:88)
[error] 	at sbt.std.TaskStreams.log$(Streams.scala:88)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log$lzycompute(Streams.scala:137)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:137)
[error] 	at sbt.Defaults$.$anonfun$compileInputsSettings$2(Defaults.scala:1434)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (core/compile:compile::compilerReporter) java.lang.NullPointerException
[error] Total time: 2 s, completed Nov 5, 2017 9:02:38 PM
```

## notes

sbt version: 1.0.0-RC3

**Comment by xuwei-k** [comment] 2017-11-09 05:09
- https://github.com/sbt/util/commit/b2be0f766ac58454a0b095c03610342c4e9704e2
- https://github.com/sbt/util/issues/119
- https://github.com/sbt/sbt/issues/3445

**Comment by dwijnand** [comment] 2017-11-09 08:48
Thanks @xuwei-k. Merged upstream at https://github.com/sbt/util/pull/121.

**Comment by eed3si9n** [comment] 2017-11-16 21:20
Closing this as Duplicate of https://github.com/sbt/util/issues/119 and https://github.com/sbt/sbt/issues/3445.

https://github.com/sbt/util/pull/121 should be part of current stable 1.0.3.

**Closed as completed by eed3si9n** 2017-11-16 21:20 UTC
Labels: Duplicate
