### ISSUE TITLE
`sbt new` does not work on windows

### ISSUE THREAD

**Issue by MasseGuillaume** [sbt/sbt#3724] opened 2017-11-09 13:57 UTC
I did not test this myself but it's reported here: https://github.com/scalatra/scalatra/issues/745

**Comment by takezoe** [comment] 2017-11-09 17:14
@MasseGuillaume Thanks for the catch! I tested `sbt new` on Windiws and it worked fine, so I guess it caused by his sbt installation. I'll handle https://github.com/scalatra/scalatra/issues/745, so this issue should be closed.

**Comment by eed3si9n** [comment] 2017-11-17 07:57
I am closing this until we have a better reproduction steps.
We are aware that `bc` command that's used in recent releases of `sbt` bash script has problems on git-bash/Cygwin and it's been addressed here - https://github.com/sbt/sbt-launcher-package/pull/199

**Closed as completed by eed3si9n** 2017-11-17 07:57 UTC

**Comment by takezoe** [comment] 2017-11-22 05:16
It looks to be caused by old version of JGit.
I raised an issue about this in giter8: https://github.com/foundweekends/giter8/issues/352
