### ISSUE TITLE
Class not found: xsbt/ExtractAPI

### ISSUE THREAD

**Issue by tomasherman** [sbt/sbt#5472] opened 2020-03-16 17:35 UTC
## steps

When cross compiling using https://github.com/twilio/sbt-guardrail. However, i don't see any line about their custom code which is why i assume it's SBT issue:

```
  [error] java.lang.NoClassDefFoundError: xsbt/ExtractAPI
18:25:28
  [error] 	at xsbt.API$ApiPhase.processScalaUnit(API.scala:51)
18:25:28
  [error] 	at xsbt.API$ApiPhase.processUnit(API.scala:46)
18:25:28
  [error] 	at xsbt.API$ApiPhase.apply(API.scala:45)
18:25:28
  [error] 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:452)
18:25:28
  [error] 	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:397)
18:25:28
  [error] 	at xsbt.API$ApiPhase.run(API.scala:34)
18:25:28
  [error] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1506)
18:25:28
  [error] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
18:25:28
  [error] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
18:25:28
  [error] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1614)
18:25:28
  [error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
18:25:28
  [error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
18:25:28
  [error] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:39)
18:25:28
  [error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:25:28
  [error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:25:28
  [error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:25:28
  [error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
18:25:28
  [error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
18:25:28
  [error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
18:25:28
  [error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
18:25:28
  [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
18:25:28
  [error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
18:25:28
  [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
18:25:28
  [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
18:25:28
  [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
18:25:28
  [error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
18:25:28
  [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
18:25:28
  [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
18:25:28
  [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
18:25:28
  [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
18:25:28
  [error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
18:25:28
  [error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
18:25:28
  [error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
18:25:28
  [error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
18:25:28
  [error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
18:25:28
  [error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
18:25:28
  [error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
18:25:28
  [error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
18:25:28
  [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
18:25:28
  [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
18:25:28
  [error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
18:25:28
  [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
18:25:28
  [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
18:25:28
  [error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1762)
18:25:28
  [error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1735)
18:25:28
  [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
18:25:28
  [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
18:25:28
  [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
18:25:28
  [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
18:25:28
  [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
18:25:28
  [error] 	at sbt.Execute.work(Execute.scala:290)
18:25:28
  [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
18:25:28
  [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
18:25:28
  [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
18:25:28
  [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
18:25:28
  [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
18:25:28
  [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
18:25:28
  [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
18:25:28
  [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
18:25:28
  [error] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by eed3si9n** [comment] 2020-03-16 17:50
@tomasherman Do you have a sample project we can use to reproduce and validate this issue on our machine or on Travis CI?

**Comment by pauljamescleary** [comment] 2020-03-30 14:22
Seeing this same issue.  Seems to be an intermittent error though, sometimes it builds and others it does not.  I cleared CI caches and it still happens intermittently.

**Comment by pauljamescleary** [comment] 2020-03-30 16:07
Update: I am suspecting on my end some kind of interplay between scalafix and scalajs sbt plugins.  When I have `isDevMode = true` for scalajs, everything works fine.  When `isDevMode = false` for scalajs, I get strange build failures.  

If I remove scalafix, everything seems to be fine.

**Comment by tomasherman** [comment] 2020-03-30 18:05
we are using scalafix aswell - im not really sure though how to replicate this :(

**Comment by QAFabianHuch** [comment] 2020-04-06 10:51
I'm getting the same error when I compile my project (which doesn't use scalafix) giving SBT not enough memory. Works fine if increase the memory.

**Comment by eed3si9n** [comment] 2020-04-06 15:16
@QAFabianHuch 

> Works fine if increase the memory.

This is a useful info. Maybe others can try bumping up the memory and see if the issues goes away.

**Comment by alifirat** [comment] 2020-07-08 15:10
@QAFabianHuch @eed3si9n I had the same issue and indeed increasing the memory was enough to resolve the issue.

**Comment by eed3si9n** [comment] 2020-07-14 10:55
ok. I'm closing this issue for now then.

**Closed as completed** 2020-07-14 10:56 UTC
