### ISSUE TITLE
Unclosed files carry over between scripted tests (at least on windows)

### ISSUE THREAD

**Issue by raboof** [sbt/sbt#6042] opened 2020-11-02 16:42 UTC
## steps

Since 1.4.0, the scripted tests for paradox at appveyor fail with:

```
[info] Running 19 / 19 (100.00%) scripted tests with RunFromSourceMain
[info] Running paradox/custom-configuration
[info] Running paradox/custom-directive
[info] Running paradox/default-theme
[info] [info] welcome to sbt 1.4.0 (Oracle Corporation Java 1.8.0_162)
[info] [info] loading settings for project sbt_9f2594d5-build from plugins.sbt ...
[info] [info] loading project definition from C:\Users\appveyor\AppData\Local\Temp\1\sbt_9f2594d5\project
[info] [info] loading settings for project docs from build.sbt ...
[info] [info] set current project to Paradox Default Theme Test (in build file:/C:/Users/appveyor/AppData/Local/Temp/1/sbt_9f2594d5/)
[info] [error] Unexpected top-level pages (pages that do no have a parent in the Table of Contents).
[info] [error] If this is intentional, update the `paradoxRoots` sbt setting to reflect the new expected roots.
[info] [error] Current ToC roots: [index.html, sub/unindexed.html, test.html]
[info] [error] Specified ToC roots: [index.html, sub/unindexed.html]
[info] [error] Paradox failed with 1 errors
[info] [error] (Compile / paradoxMarkdownToHtml) com.lightbend.paradox.sbt.ParadoxPlugin$ParadoxException
[info] [error] Total time: 1 s, completed Oct 5, 2020 1:54:39 AM
[error] x paradox/default-theme 
[error]  Cause of test exception: {line 1}  Command failed: paradox failed
```

The `paradox/default-theme` test fails because it finds an unexpected `test.html`. `test.html` is an expected output of the previous scripted test, `paradox/custom-directive`.

## problem

Artifacts from one scripted test appear to leak into the next. I'm not sure yet if it's the sources or the target resources - I don't have a windows machine handy to easily test this with, and it works fine on linux...

## expectation

I expected scripted tests to be independent.

**Comment by eatkins** [comment] 2020-11-02 16:44
This looks like a problem with paradox, not sbt. That being said, scripted tests generally run in alphabetical order on windows and in a random order on other platforms which is probably why you see the problem only on windows.

**Comment by raboof** [comment] 2020-11-02 19:11
I'll see if I can come up with a more targeted reproducer (or indeed confirm this as a problem with paradox, though I have my doubts ;) )

**Comment by eatkins** [comment] 2020-11-02 20:45
Ok. I stand corrected. For performance reasons, the scripted plugin now reuses the same directory for all of the tests. To make this work, between each test, it blows away all of the files in the test directory and then calls `reload`. The problem is that sbt can't actually delete some of the files on windows, like index.html, because some other process has a handle to them. Here is an example stack trace:
```
java.nio.file.FileSystemException: C:\Users\micro\AppData\Local\Temp\sbt_c46b041\src\docs2\paradox\index.md: The process cannot access  
the file because it is being used by another process.                                                                                   
                                                                                                                                        
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)                                                 
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)                                                   
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)                                                  
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)                                          
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)                                    
        at java.nio.file.Files.deleteIfExists(Files.java:1165)                                                                          
        at sbt.scriptedtest.ScriptedTests.$anonfun$runBatchedTests$8(ScriptedTests.scala:245)     
```
Does paradox shell out to another process during scripted tests? If so, it may be necessary to ensure that process has exited when the tests are complete.

It wasn't necessarily intentional that we changed the default behavior in 1.3.13 vs 1.4.0. I am looking into why that is and if there is a way to override it.

**Comment by raboof** [comment] 2020-11-02 21:06
> The problem is that sbt can't actually delete some of the files on windows, like index.html, because some other process has a handle to them

I noticed the same thing. Turns out we were incorrectly holding on to them, so it was *also* a problem in paradox ;).

> Here is an example stack trace

Hmm, I don't see those in the paradox appveyor output at all - were those hidden by default?

> I am looking into why that is and if there is a way to override it.

Great! In the mean time I fixed the unclosed stream so this is not an urgent problem for me anymore. Do you want to keep this open anyway?

**Comment by eatkins** [comment] 2020-11-02 21:16
> Hmm, I don't see those in the paradox appveyor output at all - were those hidden by default?

I added a stack trace print to a local sbt build so they wouldn't be visible to you.

> Great! In the mean time I fixed the unclosed stream so this is not an urgent problem for me anymore. Do you want to keep this open anyway?

Yes, let's leave this open in case someone else has a similar problem and can't work around it.

**Comment by eatkins** [comment] 2020-11-05 15:52
Now that #6054 is merged, there is a workaround to the problem of sbt being unable to delete some files on windows. Builds can add `scriptedBatchExecution := false` to their project to restore the pre-1.4.0 semantics where each scripted test gets a fresh sbt instance (which means the tests tend to be much slower but each test is completely isolated).

**Closed as completed by eatkins** 2020-11-05 15:52 UTC
