### ISSUE TITLE
bin/sbt-launch-lib.bash introduces unnecessary bc dependency

### ISSUE THREAD

**Issue by camilojimenez** [sbt/sbt#3767] opened 2017-11-25 04:53 UTC
## steps

running sbt without bc installed results on an error:

      docker run -it ubuntu bash
      # inside the container:
      apt-get update; apt-get -y install default-jdk curl
      curl -L https://github.com/sbt/sbt/releases/download/v1.0.3/sbt-1.0.3.tgz | tar -zxf -
      ./sbt/bin/sbt

results on::

      /sbt/bin/sbt-launch-lib.bash: line 207: bc: command not found
     
      The java installation you have is not up to date
      requires at least version 1.6+, you have
      version 1.8
    
      Please go to http://www.java.com/getjava/ and download
      a valid Java Runtime and install before running .

## problem

bin/sbt-launch-lib.bash uses bc to check the jdk version, introducing an unnecessary dependency

## expectation

bc can be eliminated as a dependency by using bash comparisons

## notes

If deemed appropriate, I can contribute write the MR necessary for this change

sbt version: v1.0.3

**Comment by eed3si9n** [comment] 2017-11-26 19:39
Duplicate of https://github.com/sbt/sbt-launcher-package/issues/198

**Closed as completed by eed3si9n** 2017-11-26 19:39 UTC
