### ISSUE TITLE
Sbt 1.3.0 copies jar files to `/tmp/sbt_xyz` (and doesn't clean up after itself)

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#5074] opened 2019-09-12 09:49 UTC
It shouldn't copy any jar files there in the first place.

If that's a solution for the problem of jars changing behind your back then that's usually a non-problem for most artifacts. If you work with locally published (SNAPSHOT) artifacts the situation might be different but in any case it shouldn't be the default behavior.

**Comment by eed3si9n** [comment] 2019-09-12 21:36
@jrudolph Could you elaborate on the reproduction steps? Is this for `run` (`bgRun`)?

**Comment by eatkins** [comment] 2019-09-13 18:52
My feeling is that sbt should only write into `~/.sbt` and the project target directories. I tried to refactor BackgroundJobService so that the temp directory was configurable, but it was a bit difficult because DefaultBackgroundJobService is a singleton.

**Comment by eatkins** [comment] 2019-09-13 18:53
There are three places where sbt calls `IO.createTemporaryDirectory` and ideally we could rework things so that these write into sbt managed directories rather than `java.io.tmpdir`.

**Comment by eatkins** [comment] 2019-12-13 17:03
Fixed in #5259 (https://github.com/sbt/sbt/pull/5259/commits/73a196798f0573608d4adf472606eed576a307c0).

**Closed as completed by eatkins** 2019-12-13 17:03 UTC
