### ISSUE TITLE
Windows 7 "Error during sbt execution: No Scala version specified or detected"

### ISSUE THREAD

**Issue by paddy3rb** [sbt/sbt#1951] opened 2015-04-02 09:58 UTC
Launcing sbt clean from command prompt in windows 7 (32 bit) but ending up with getting "Error during sbt execution: No Scala version specified or detected". I'm running with - Scala 2.10.4, sbt-0.13.7, jdk1.7.0_75. I've set SCALA_HOME, SBT_HOME appropriately

> tried with deleting ~/.sbt/boot - no use
> tried with updating -scala-home, -scala-version in c:/Prog~/sbt/conf/sbtopts - no use
> adding repositories as mentioned in issue 1117, but no use
> Can any one help me get out of this..?

**Comment by eed3si9n** [comment] 2015-04-09 20:20
Likely a duplicate of #1117. Do you have `repositories` file and/or Nexus proxy setup?

**Comment by djx314** [comment] 2017-09-17 13:24
Upgrade to 1.0.2 and use win7 and cause the same problem. I think it's a huge bug.

**Comment by djx314** [comment] 2017-09-17 19:38
I delete ~/.ivy2 and slove the problem. It seems that it't the nessary step to upgrade sbt 0.13.x to 1.0.x.

**Comment by conchz** [comment] 2017-11-08 07:05
windows7 & sbt 1.0.3, the same problem occurred.

**Comment by djx314** [comment] 2017-11-09 10:00
@lavenderx Remove ~/.ivy2 and ~/.sbt and not to use the common sbt.bat
Just use the `sbt-launch.jar` and write a sbt.bat like
```scala
java -jar "yourPath/sbt-launch.jar"
```
Have a try on it.

**Comment by eed3si9n** [comment] 2018-08-06 20:06
Could either of you have a project that I can use to reproduce this behavior? Does it happen with any sbt project using the latest sbt?

**Comment by eed3si9n** [comment] 2019-10-02 02:49
I am closing this due to inactivity, but if this is still relevant let us know with more details (reproduction steps etc).

**Closed as completed by eed3si9n** 2019-10-02 02:49 UTC
Labels: Needs Reproduction Test Case, area/windows
