### ISSUE TITLE
Make pluginParser working with autoplugins (for plugin command)

### ISSUE THREAD

**Issue by jaceklaskowski** [sbt/sbt#1464] opened 2014-07-24 21:41 UTC
As per [the discussion in sbt-dev](https://groups.google.com/d/msg/sbt-dev/oiypIgdCHtY/_WcAMWi5j2oJ), executing `plugin` command with no autoplugin specified gives an error message:

```
> plugin
[error] plugin usage:
[error]
[error]
[error] plugin
[error]       ^
```

**Comment by eed3si9n** [comment] 2014-08-01 23:37
Duplicate of #1416 fixed by #1426.

**Closed as completed by eed3si9n** 2014-08-01 23:37 UTC
Labels: Duplicate
