### ISSUE TITLE
SSLHandshakeException when creating a Dotty template

### ISSUE THREAD

**Issue by kikofernandez** [sbt/sbt#4554] opened 2019-03-06 11:16 UTC
It seems like `sbt` points to the wrong Type Safe repository when creating a Dotty template.

## steps

1. I create a Dotty template, as explained in [here](http://dotty.epfl.ch/docs/usage/getting-started.html): `sbt new lampepfl/dotty.g8`.

2. I run the command `sbt` and get errors.

## problem

I get errors related to not finding the dependency (I think).
Here is the [full output](https://gist.github.com/kikofernandez/d97a572530fd67d340f2aeaa2158259b) and below just a small snippet:

```
::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]     Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]         ch.epfl.lamp:sbt-dotty:0.3.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn]     Note: Unresolved dependencies path:
[warn]         ch.epfl.lamp:sbt-dotty:0.3.0 (scalaVersion=2.12, sbtVersion=1.0) (/Users/kikofernandezreyes/Code/Godot/godotty/project/plugins.sbt#L1-2)
[warn]           +- default:godotty-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: ch.epfl.lamp#sbt-dotty;0.3.0: Resolution failed several times for dependency: ch.epfl.lamp#sbt-dotty;0.3.0 {compile=[default(compile)]}::
```

## expectation

I was expecting to run `sbt` successfully or any other `sbt` command, such as compilation.
I am able to by-pass the issue by adding the `sbtPlugin := false` at the end of the `plugins.sbt`, which look like:

```
addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.3.0")
sbtPlugin := false
```
## notes

sbt version: *1.2.8*
Can this somehow be related to #3100 ?

P.S. Please, feel free to update the description with more meaningful information.

**Comment by eed3si9n** [comment] 2019-03-06 20:40
It seems like the underlying problem is SSLHandshakeException.

> javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Are you using Ubuntu? If so could you make sure to use Java 8, or Java 11 with certificates etc?

**Comment by Kordalien** [comment] 2019-03-09 23:15
I don't think the SSL handshake is the problem; after trying to debug this issue for myself, I noticed some key points: the resolver failures come back as 
```
[error] 	typesafe-ivy-releases: unable to get resource for ch.epfl.lamp#sbt-dotty;0.3.0: res=https://repo.typesafe.com/typesafe/ivy-releases/ch.epfl.lamp/sbt-dotty/scala_2.12/sbt_1.0/0.3.0/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for ch.epfl.lamp#sbt-dotty;0.3.0: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/ch.epfl.lamp/sbt-dotty/scala_2.12/sbt_1.0/0.3.0/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	typesafe-ivy-releases: unable to get resource for ch.epfl.lamp#sbt-dotty;0.3.0: res=https://repo.typesafe.com/typesafe/ivy-releases/ch.epfl.lamp/sbt-dotty/0.3.0/jars/sbt-dotty.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
which is expected-- the dotty sbt plugin is hosted on maven central (http://repo1.maven.org/maven2/ch/epfl/lamp/sbt-dotty_2.12_1.0/0.3.0/). 

Running in debug mode and searching out dotty gives us an interesting behavior:
```
[debug] 	local: no ivy file found for ch.epfl.lamp#sbt-dotty;0.3.0
[debug] 		tried https://repo1.maven.org/maven2/ch/epfl/lamp/sbt-dotty_2.12_1.0/0.3.0/sbt-dotty-0.3.0.pom
[debug] 	public: found md file for ch.epfl.lamp#sbt-dotty;0.3.0
[debug] 		=> https://repo1.maven.org/maven2/ch/epfl/lamp/sbt-dotty_2.12_1.0/0.3.0/sbt-dotty-0.3.0.pom (0.3.0)
[debug] downloading https://repo1.maven.org/maven2/ch/epfl/lamp/sbt-dotty_2.12_1.0/0.3.0/sbt-dotty-0.3.0.pom ...
[debug] 	public: downloading https://repo1.maven.org/maven2/ch/epfl/lamp/sbt-dotty_2.12_1.0/0.3.0/sbt-dotty-0.3.0.pom
[debug] 	public: downloading https://repo1.maven.org/maven2/ch/epfl/lamp/sbt-dotty_2.12_1.0/0.3.0/sbt-dotty-0.3.0.pom.sha1
[debug] sha1 OK for https://repo1.maven.org/maven2/ch/epfl/lamp/sbt-dotty_2.12_1.0/0.3.0/sbt-dotty-0.3.0.pom
[debug] 	[SUCCESSFUL ] ch.epfl.lamp#sbt-dotty;0.3.0!sbt-dotty.pom(pom.original) (112ms)
[debug] 		tried https://repo.typesafe.com/typesafe/ivy-releases/ch.epfl.lamp/sbt-dotty/0.3.0/jars/sbt-dotty.jar
```


Even though the package is found in maven central, it fails the download through `repo.typesafe`.
(These output were Generated on a mac running Mojave 10.14, which afaik does not have an issue with the certificates for the typesafe repo). 
I also manually checked both `repo.typesafe` and `repo.scala-sbt.org`, and neither host sbt-dotty, so the fact that it fails out in the middle of the maven fallback seems to be an issue.

It is possible the structure of the files in maven is part of the issue, as while the path acts as if it were `ch.epfl.lamp:sbt-dotty_2.12_1.0:0.3.0`, the files at the end of that path correspond to 
what would be expected from `ch.epfl.lamp:sbt-dotty:0.3.0` (And, correspondingly, a command like mvn dependency:get -Dartifact=ch.epfl.lamp:dotty-sbt_2.12_1.0:0.3.0) will also fail. (though SBT gets further correctly identifying the pom where maven does not)

**Comment by kikofernandez** [comment] 2019-03-11 10:14
Hi, I am using OSX Mojave 10.14.3 and Java 8.
As mentioned, I only know that it does not get the package from maven central, which was hinted by @smarter. Thanks for looking into this.

**Comment by Kordalien** [comment] 2019-03-12 02:22
I can add a little more information from another debugging session: I tried manually adding maven central as a resolver, which caused the error message to become:
```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: ch.epfl.lamp#sbt-dotty;0.2.6: Resolution failed several times for dependency: ch.epfl.lamp#sbt-dotty;0.2.6 {compile=[default(compile)]}:: 
[error] 	typesafe-ivy-releases: unable to get resource for ch.epfl.lamp#sbt-dotty;0.2.6: res=https://repo.typesafe.com/typesafe/ivy-releases/ch.epfl.lamp/sbt-dotty/scala_2.12/sbt_1.0/0.2.6/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for ch.epfl.lamp#sbt-dotty;0.2.6: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/ch.epfl.lamp/sbt-dotty/scala_2.12/sbt_1.0/0.2.6/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	typesafe-ivy-releases: unable to get resource for ch.epfl.lamp#sbt-dotty;0.2.6: res=https://repo.typesafe.com/typesafe/ivy-releases/ch.epfl.lamp/sbt-dotty/0.2.6/jars/sbt-dotty.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	typesafe-ivy-releases: unable to get resource for ch.epfl.lamp#sbt-dotty;0.2.6: res=https://repo.typesafe.com/typesafe/ivy-releases/ch.epfl.lamp/sbt-dotty/0.2.6/jars/sbt-dotty.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
Note that the last two (which should have been default maven central and manually added maven central) refer to typesafe-ivy-releases, I think somehting is cause SBT to rewrite the URL to the typesafe ivy repository. This is also in line with the fact that pom resolution completes, but not jar resolution, while on the first pass at the typesafe repository, the initial search path fails.

**Comment by eed3si9n** [comment] 2019-03-21 22:36
I am macOS as well, and the template works for me.

```
$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

Ivy goes through the resolvers to find the artifact, so if one is erroring out that could prevent the resolution from going forward.

**Comment by Kordalien** [comment] 2019-03-21 23:58
When I tried, I wasn't using the template, just declaring it as an SBT plugin in my project. SBT seems to resolve other resources from typesafe-ivy-releases fine, and as I noted above, I can clearly se SBT finding the information in maven central, then switching back to try to download the actual jar from typesafe-ivy-releases. 

Perhaps I should open a new issue related to that; it seems like the problem I am facing is expected: if the resource is found in maven central, it should finish downloading from maven central, not switch abck to a different resolver and error out.

(I just tested again, trying to download the plugin still fails for the same reasons).

@eed3si9n Did the dotty perhaps resolve from your ivy cache instead of from the internet?

**Comment by eed3si9n** [comment] 2019-09-29 21:14
To make sure I don't have things cached on my machine, I just used a fresh Ubuntu image on Docker, and was able to install AdoptOpenJDK JDK 11, sbt 1.3.2, and run the Dotty template.

https://gist.github.com/eed3si9n/ef7a4972539c8014c662e1e6d021bf81

```
[info] Done packaging.
[info] Running Main
Hello world!
I was compiled by dotty :)
[success] Total time: 14 s, completed Sep 29, 2019, 9:09:40 PM
```

For now I am going to close this issue, but it might be useful to reproduce this on Travis CI or some other repeatable infrastructure to figure out what might be going on?

**Closed as completed by eed3si9n** 2019-09-29 21:14 UTC
Labels: needs info
