### ISSUE TITLE
Java main methods do not run in SBT 1.1.1

### ISSUE THREAD

**Issue by dhinojosa** [sbt/sbt#4001] opened 2018-03-10 19:49 UTC
(See the guidelines for contributing, linked above)

## steps

1. Create a simple sbt project
2. Create a simple class in java inside of src/main/java
3. In the SBT shell execute run

## problem

SBT should recognize the main method in Java. This works fine with a project running 1.1.0, but not 1.1.1

## expectation

It should recognize the main method, and run it.

## notes

sbt version: 1.1.1

**Comment by dwijnand** [comment] 2018-03-13 16:03
I can't reproduce the issue:

```
15:59:38 $ cat project/build.properties
sbt.version=1.1.1

15:59:42 $ cat build.sbt
scalaVersion := "2.12.4"

15:59:45 $ cat src/main/java/t/Main.java
package t;

class Main {
  public static void main(String[] args) {
    System.out.println("Hello World!");
  }
}

15:59:49 $ sbt
[info] Loading settings from idea.sbt,global-plugins.sbt ...
[info] Loading global plugins from /Users/dnw/.dotfiles/.sbt/1.0/plugins
[info] Loading project definition from /s/t-java-main/project
[info] Updating ProjectRef(uri("file:/s/t-java-main/project/"), "t-java-main-build")...
[info] Done updating.
[info] Loading settings from build.sbt ...
[info] Set current project to t-java-main (in build file:/s/t-java-main/)
[info] sbt server started at local:///Users/dnw/.sbt/1.0/server/079f5d1de18a4f33d950/sock
> run
[info] Updating ...
[info] Done updating.
[info] Compiling 1 Java source to /s/t-java-main/target/scala-2.12/classes ...
[info] Done compiling.
[info] Packaging /s/t-java-main/target/scala-2.12/t-java-main_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Running t.Main
Hello World!
```

what are we doing differently?

closing, for now, on the assumption that there is no bug.

**Closed as completed by dwijnand** 2018-03-13 16:03 UTC

**Comment by lespea** [comment] 2018-12-07 16:14
It appears this happens if `crossPaths := false` is set

**Comment by dhinojosa** [comment] 2018-12-08 00:47
@dwijnand I think this was just forgotten to be closed. It has been working for a while. What's weird is that it indeed was broken, maybe I did have `crossPaths`. Regardless, good that it is closed, I have moved on to later and greater sbt versions and everything runs well. Thanks!
