### ISSUE TITLE
makePom omits scope

### ISSUE THREAD

**Issue by htmldoug** [sbt/sbt#2002] opened 2015-05-06 03:59 UTC
The makePom omits `<scope>test</scope>` when there are multiple libraryDependencies with the same group + artifactId + version, but different classifiers.
## Steps
1. `git clone https://github.com/htmldoug/sbt-bug-pom-missing-scope.git`
2. `sbt makePom`
3. Open the generated pom.xml
4. Observe that the dependency entry for `"guava-tests" % "18.0" % "test" classifier "tests"` is missing a `<scope>test</scope>` element.
## Problems

The following library dependencies... 

``` scala
libraryDependencies += "com.google.guava" % "guava-tests" % "18.0"
libraryDependencies += "com.google.guava" % "guava-tests" % "18.0" % "test" classifier "tests"
```

... produce a pom dependency with a missing `<scope>test</scope>`.

``` xml
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava-tests</artifactId>
    <version>18.0</version>
    <classifier>tests</classifier>
</dependency>
```
## Expectations

The dependency with configuration "test" should produce a pom entry with `<scope>test</scope>`. 
### Interaction issue?

On its own, the following produces the correct result.

``` scala
libraryDependencies += "com.google.guava" % "guava-tests" % "18.0" % "test" classifier "tests"
```

``` xml
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava-tests</artifactId>
    <version>18.0</version>
    <classifier>tests</classifier>
    <scope>test</scope>
</dependency>
```

It's only when you add a libraryDependency with the same group + artifactId + version in compile configuration _in addition_ to the test configuration with the classifier, that the problem occurs. 
### pom generation vs dependencyClasspath

dependencyClasspath and test:dependencyClasspath appear okay. This may be isolated to the pom generation.

```
> export dependencyClasspath
/Users/doug/.sbt/boot/scala-2.10.4/lib/scala-library.jar:
/Users/doug/.ivy2/cache/com.google.guava/guava-tests/jars/guava-tests-18.0.jar:
/Users/doug/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-1.3.9.jar

> export test:dependencyClasspath
/code/sbt-bug-classifier-pom/target/scala-2.10/classes:
/Users/doug/.sbt/boot/scala-2.10.4/lib/scala-library.jar:
/Users/doug/.ivy2/cache/com.google.guava/guava-tests/jars/guava-tests-18.0-tests.jar:
/Users/doug/.ivy2/cache/com.google.guava/guava-tests/jars/guava-tests-18.0.jar:
/Users/doug/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-1.3.9.jar
```

**Comment by jsuereth** [comment] 2015-05-12 01:33
Yeah, this looks to be a limitaiton in MakePom.scala that can be solved.

**Comment by cunei** [comment] 2015-05-13 00:05
The issue stems from the pom generation. Specifically, from this bit of code:
https://github.com/sbt/sbt/blob/f334d76f70bb6ba2befc38b414f13776d0b119ac/ivy/src/main/scala/sbt/MakePom.scala#L244-L258
In particular, the culprit is `getScopeAndOptional` at line 250.
Here is some diagnostic debugging. In the case of just:

```
libraryDependencies += "com.google.guava" % "guava-tests" % "18.0" % "test" classifier "tests"
```

the various values before the call to `makeDependencyElem()` at line 257 are:

```
---------------
artifact   : DA:guava-tests.jar(jar) ([*])
artconfigs : *
configs    : test
dependency :
  dependency: com.google.guava#guava-tests;18.0 {test=[default(compile)]}
scope      : Some(test)
optional   : false
classifier : Some(tests)
type       : None
---------------
```

Notice that the list of "configs" contains only test. The generation of the `scope` item only looks at the list of config, hence "test" is returned.

However, in the case of

```
libraryDependencies += "com.google.guava" % "guava-tests" % "18.0"
libraryDependencies += "com.google.guava" % "guava-tests" % "18.0" % "test" classifier "tests"
```

the two are combined into a `MergedDescriptors` dependency. The values now are:

```
---------------
artifact   : DA:guava-tests.jar(jar) ([compile])
artconfigs : compile
configs    : compile
dependency :
  sbt.ivyint.MergedDescriptors@5494e20f
   dependency: com.google.guava#guava-tests;18.0 {compile=[default(compile)]}
   dependency: com.google.guava#guava-tests;18.0 {test=[default(compile)]}
scope      : Some(compile)
optional   : false
classifier : None
type       : None
---------------
artifact   : DA:guava-tests.jar(jar) ([*])
artconfigs : *
configs    : compile,test
dependency :
  sbt.ivyint.MergedDescriptors@5494e20f
   dependency: com.google.guava#guava-tests;18.0 {compile=[default(compile)]}
   dependency: com.google.guava#guava-tests;18.0 {test=[default(compile)]}
scope      : Some(compile)
optional   : false
classifier : Some(tests)
type       : None
---------------
```

The same dependency is used twice to generate the two pom elements. The classifier changes
because it is directly extracted from the accompanying `DependencyArtifactDescriptor`.
In the second case, the artifact descriptor list of configs is `"*"`, therefore the list of configs is
taken instead from the dependency: `compile,test`. At this point, `getScopeAndOptional`
selects `Some(compile)`, and the scope is not printed.
I suppose `getScopeAndOptional` could be tweaked a bit, or the list of configs passed to
it could be selected differently. That needs some decisions related to dependency management
however; /cc @eed3si9n @jsuereth

**Comment by jsuereth** [comment] 2015-05-13 15:29
So to clarify a bit, when you write:

``` scala
libraryDependencies += "com.google.guava" % "guava-tests" % "18.0"
libraryDependencies += "com.google.guava" % "guava-tests" % "18.0" % "test" classifier "tests"
```

You're actually (under the scenes) creating this:

``` scala
libraryDependencies += 
  ("com.google.guava" % "guava-tests" % "18.0" % "compile->compile;test->test").
     artifacts(Artifact("guava-tests", Some("tests"), "jar", "jar"), Artifact("guava-tests", None, "jar", "jar"))
```

That is, in Ivy vernacular:
1. I have one dependency on the guava-tests moudle
2. I want the compile-artifacts of the module to be on my compiles scope, and the test artifacts of the module to be on my test scope.
3. I only want two artifacts, the "tests" classifier and the basic jar.

What sbt's "merge descriptors" does is allow users to be "less ivy" and "more maven" in how they specify dependencies, and sbt will unify the concept of artifact-based dependnecy back into ivy's "module" based dependency tracking.

Now, add in how Ivy handles maven artifacts ->  Artifacts are associated with ALL configurations, except for specifically handled ones.   So, as Toni shows, the `artconfigs` value is `*`, meaning the `tests` classifier artifact is assigned to ALL the configurations of the module.

When you only have ONE artifact for that module, all is good because we only see/care about the "test->compile" configuration.   sbt's "MakePom" code can handle this.   The issue is if we have two, then when merging them we're merging them _acurrately_ but hte original DSL was too inspecific.  We're ending up with the following equivalent definition:

```
libraryDependencies += 
  ("com.google.guava" % "guava-tests" % "18.0" % "compile->compile;test->compile").
     artifacts(Artifact("guava-tests", Some("tests"), "jar", "jar"), Artifact("guava-tests", None, "jar", "jar"))
```

As you can see, this means that the guava-tests jar, which is mapped to configuration `*`, will show up on both the compile and test classpaths, as well as show up in the POM as being on the compile classpath.

While we may have hacked ivy around so the tests jar DOESN'T actually show up in the compile classpath in sbt, the data is still wrong, and we're seeing that in the MakePom code.

## Solutions

_Option 1_

We could attack the issue here, and try to outline what configuratoin we think the Artifact should be mapped to:   https://github.com/sbt/sbt/blob/0.13/ivy/src/main/scala/sbt/Ivy.scala#L612-L619

That is, we could try to do post-processing on `libraryDependencies` and pre-detect "merge" dependencies, where we try to adjust the configuration mappings ahead of time.  We may also have to go into Ivy's "maven" code and ensure that tests artifacts are always assigned to the test configuration (but I suspect it's actually sbt code that is incorrectly overriding that).

_Option 2_
We could adjust merge descriptors to detect the case where  a classified artifact is merged with the default on, and check the configuration / explciitly migrate that artifacts into a configuration to avoid the issue.

This feels more hacky, but it actually could be the merge descriptors logic is faulty now, leading to this situation to begin with.

**Comment by greenrd** [comment] 2015-08-04 18:36
Possible duplicate of #1500.

**Comment by fommil** [comment] 2015-10-31 12:22
:+1: this impacts neo4j

**Comment by fommil** [comment] 2015-10-31 12:22
so what's the workaround?

**Comment by fommil** [comment] 2015-10-31 12:52
I've tried this

``` scala
      "org.neo4j" % "neo4j-kernel" % "2.3.0",
      ("org.neo4j" % "neo4j-kernel" % "2.3.0" % "test,it").artifacts(
        Artifact("neo4j-kernel", "tests")
      ),
```

but the sources and javadocs for the `tests` classifier do not show up in the `updateClassifiers` report. I'll file it as a separate bug.

**Comment by dwijnand** [comment] 2016-09-22 12:22
Fixed in https://github.com/sbt/sbt/pull/2642, part of sbt 0.13.12.

**Closed as completed by dwijnand** 2016-09-22 12:22 UTC
Labels: area/maven_integration
