### ISSUE TITLE
java.lang.IllegalAccessError: class X cannot access its superinterface Y

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4592] opened 2019-03-31 15:36 UTC
## steps

- git clone librarymanagement
- Run sbt using a recent nightly
- test

## problem

```
[info] sbt.internal.librarymanagement.ManagedChecksumsSpec *** ABORTED ***
[info]   java.lang.IllegalAccessError: class org.apache.ivy.plugins.parser.m2.ReplaceMavenConfigurationMappings$$anon$1 cannot access its superinterface org.apache.ivy.plugins.parser.m2.PomModuleDescriptorBuilder$ConfMapper
[info]   at java.lang.ClassLoader.defineClass1(Native Method)
[info]   at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[info]   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[info]   at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[info]   at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info]   ...
[error] java.lang.IllegalAccessError: class org.apache.ivy.plugins.parser.m2.ReplaceMavenConfigurationMappings$$anon$1 cannot access its superinterface org.apache.ivy.plugins.parser.m2.PomModuleDescriptorBuilder$ConfMapper
[error] 	at java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[error] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[error] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at org.apache.ivy.plugins.parser.m2.ReplaceMavenConfigurationMappings$.<init>(ReplaceMavenConfigurationMappings.scala:42)
[error] 	at org.apache.ivy.plugins.parser.m2.ReplaceMavenConfigurationMappings$.<clinit>(ReplaceMavenConfigurationMappings.scala)
[error] 	at sbt.internal.librarymanagement.CustomPomParser$.<init>(CustomPomParser.scala:65)
[error] 	at sbt.internal.librarymanagement.CustomPomParser$.<clinit>(CustomPomParser.scala)
[error] 	at sbt.internal.librarymanagement.IvySbt.settings$lzycompute(Ivy.scala:112)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$settings(Ivy.scala:85)
[error] 	at sbt.internal.librarymanagement.IvySbt.mkIvy(Ivy.scala:181)
[error] 	at sbt.internal.librarymanagement.IvySbt.ivy$lzycompute(Ivy.scala:188)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$ivy(Ivy.scala:188)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:202)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:78)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:191)
[error] 	at sbt.internal.librarymanagement.ManagedChecksumsSpec.$anonfun$new$1(ManagedChecksumsSpec.scala:54)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[error] 	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[error] 	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[error] 	at org.scalatest.Transformer.apply(Transformer.scala:22)
[error] 	at org.scalatest.Transformer.apply(Transformer.scala:20)
[error] 	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
[error] 	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[error] 	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[error] 	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
[error] 	at org.scalatest.FlatSpecLike.invokeWithFixture$1(FlatSpecLike.scala:1680)
[error] 	at org.scalatest.FlatSpecLike.$anonfun$runTest$1(FlatSpecLike.scala:1692)
[error] 	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[error] 	at org.scalatest.FlatSpecLike.runTest(FlatSpecLike.scala:1692)
[error] 	at org.scalatest.FlatSpecLike.runTest$(FlatSpecLike.scala:1674)
[error] 	at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1685)
[error] 	at org.scalatest.FlatSpecLike.$anonfun$runTests$1(FlatSpecLike.scala:1750)
[error] 	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[error] 	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
[error] 	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[error] 	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
[error] 	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[error] 	at org.scalatest.FlatSpecLike.runTests(FlatSpecLike.scala:1750)
[error] 	at org.scalatest.FlatSpecLike.runTests$(FlatSpecLike.scala:1749)
[error] 	at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1685)
[error] 	at org.scalatest.Suite.run(Suite.scala:1147)
[error] 	at org.scalatest.Suite.run$(Suite.scala:1129)
[error] 	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
[error] 	at org.scalatest.FlatSpecLike.$anonfun$run$1(FlatSpecLike.scala:1795)
[error] 	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[error] 	at org.scalatest.FlatSpecLike.run(FlatSpecLike.scala:1795)
[error] 	at org.scalatest.FlatSpecLike.run$(FlatSpecLike.scala:1793)
[error] 	at org.scalatest.FlatSpec.run(FlatSpec.scala:1685)
[error] 	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[error] 	at sbt.TestRunner.runTest$1(TestFramework.scala:126)
[error] 	at sbt.TestRunner.run(TestFramework.scala:137)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:296)
[error] 	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:259)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:296)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:296)
[error] 	at sbt.TestFunction.apply(TestFramework.scala:308)
[error] 	at sbt.Tests$.processRunnable$1(Tests.scala:347)
[error] 	at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:353)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:268)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:277)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:268)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (lmIvy / Test / executeTests) java.lang.IllegalAccessError: class org.apache.ivy.plugins.parser.m2.ReplaceMavenConfigurationMappings$$anon$1 cannot access its superinterface org.apache.ivy.plugins.parser.m2.PomModuleDescriptorBuilder$ConfMapper
```

## expectation

Test runs

## notes

Ivy tries to load a class and fails.

```
Test / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.ScalaInstance
```

fixes the issue.

**Comment by eed3si9n** [comment] 2019-03-31 15:50
There are also a few builds in sbt community build that's showing up with potential classpath issues:
- https://github.com/sbt/sbt-validator/issues/41
- https://github.com/sbt/sbt-validator/issues/42
- https://github.com/sbt/sbt-validator/issues/43

**Comment by eatkins** [comment] 2019-03-31 15:56
Great. Hopefully we can track these down then. My naive guess is that there is an ordering issue. It's also possible that we should only use the scala instance in the ScalaInstance strategy.

**Comment by eatkins** [comment] 2019-03-31 22:37
I have a simple scripted test now that reproduces the issue.

**Comment by eatkins** [comment] 2019-04-01 00:36
I know the cause: libraryManagement has an explicit dependency on "org.scala-sbt.ivy" % "ivy" % "2.3.0-sbt-cb9cc189e9f3af519f9f102e6c5d446488ff6832". When the test fails, some of the classes in that jar were loaded by the scala instance classloader while others were loaded by the layered classloader. Also, I discovered that that jar would appear twice in the class path: once in the .ivy2 local cache and once in the sbt boot directory. I am starting to wonder if the sbt boot directory causes more problems than it's worth.

**Comment by eed3si9n** [comment] 2019-04-01 13:36
If sbt's boot directory (new metabuild classpath?) is leaking out to librarymanagement's test, that sounds like a bug.

**Comment by eatkins** [comment] 2019-04-01 14:13
https://github.com/sbt/sbt/commit/1e960b324c83e0e1b67d2405211e511f6f6c4cc9 causes the boot classpath to leak into the run task.

**Comment by eatkins** [comment] 2019-04-01 15:06
BTW, I really don't know the history around the boot directory. I'm sure there is a good reason that it's there. It has just been sort of an annoyance for me because it's yet another cache that has to be independently managed from .ivy2 or .coursier that seems to serve a similar purpose. It also makes sbt development somewhat more cumbersome because if you use snapshot builds you have to constantly do reboot full.

**Comment by eed3si9n** [comment] 2019-04-02 18:11
@eatkins 

> 1e960b3 causes the boot classpath to leak into the run task.

Do you know which part?

**Comment by eatkins** [comment] 2019-04-02 18:55
https://github.com/sbt/sbt/blob/8e1ebda36aab2b79f4b6cae1bf6263b194d2edd2/main/src/main/scala/sbt/Defaults.scala#L1320-L1323 causes the classpath passed into ScalaRun.run to contain jars in the boot directory. This was causing me issues with caching the runtime layer and the test layer because test does not use the boot directory. I figured out a workaround, but I don't really understand the purpose of copying the dependencies into the boot directory vs. just using the jars in the .ivy2 cache and/or using the scala instance (which already uses the boot directory) as the parent classloader.

**Comment by eed3si9n** [comment] 2019-04-02 21:42
Boot directory copying is an implementation detail of sbt launcher (https://github.com/sbt/launcher), which internally uses Ivy to resolve the coordinate specified by [launcherconfig](https://www.scala-sbt.org/1.x/docs/Launcher-Configuration.html). Ivy cache is mutable, so to ensure stable behavior and to reduce lock contention it's copying the resulting artifacts into the boot directory. This allows multiple instances of sbt to run (on different builds).

https://github.com/sbt/sbt/commit/1e960b324c83e0e1b67d2405211e511f6f6c4cc9, which is part of #2936 (`bgRun`) does lighter version of that for user's application. It's copying the user's application classpath so the state (i.e. sbt shell) can move on to do other things, like compilation of other code.

**Comment by eatkins** [comment] 2019-04-02 21:58
Ok. Thanks for the explanation. That makes sense. The run and runMain tasks are interesting because they are actually run in the foreground so its somewhat unlikely that the user inadvertently blows away the classpath. I don't really want to mess with the those defaults though. This means that the runtime layer cannot be shared with the test layer unless the user both sets ClassLoaderLayeringStrategy.ShareRuntimeDependenciesLayerWithTestDependencies and sets bgCopyClasspath := false. I can add that to the scaladocs for the classloader layering strategies.

**Comment by eatkins** [comment] 2019-04-03 00:08
This cannot be fixed using a layered classloader without significant work. It is a limitation of the jvm. The reason the test fails is because library management opens the `org.apache.ivy.plugins.parser.m2` package which is primarily provied by `ivy-2.3.0-sbt-cb9cc189e9f3af519f9f102e6c5d446488ff6832.jar`. It then defines an instance of an `org.apache.ivy.plugins.parser.m2` package private interface. You cannot access package private classes across classloaders. There is no straightforward way to fix this without additional reflection and/or bytecode manipulations.

**Comment by eatkins** [comment] 2019-04-03 00:09
IMO the right thing to do is just explicitly define the classLoaderLayeringStrategy when we update the library management sbt version. There will be other builds that run into this problem, but I added an error message in https://github.com/sbt/sbt/pull/4601/commits/8199dd114d5ff59bd5cc6cc7b22773432d95a1fd so that it hopefully won't be too difficult for users to fix.

**Comment by eed3si9n** [comment] 2019-04-03 01:20
> IMO the right thing to do is just explicitly define the classLoaderLayeringStrategy when we update the library management sbt version. There will be other builds that run into this problem, but I added an error message in 8199dd1 so that it hopefully won't be too difficult for users to fix.

Do you think sbt/sbt-validator#41, sbt/sbt-validator#42, and sbt/sbt-validator#43 are also running into a variation of this issue?

**Comment by eed3si9n** [comment] 2019-04-04 16:33
This related only tangentially, but since Scala 2.13.x collection uses serialization proxy pattern, and because ScalaTest is using Java serialization, it seems even 2 layer cake of sbt 1.2.x might be an issue (a variation of #89) for Scala 2.13.0-RC1.
See https://github.com/sbt/zinc/pull/651#issuecomment-479969522

**Comment by eatkins** [comment] 2019-09-20 18:16
This was resolved by making the default layering strategy ScalaLibrary.

**Closed as completed by eatkins** 2019-09-20 18:16 UTC
Labels: Regression
