### ISSUE TITLE
Authentication for a proxy repository

### ISSUE THREAD

**Issue by gmalouf** [sbt/sbt#731] opened 2013-04-16 15:06 UTC
I am using sbt 0.12.2 currently for our builds at work.  We've recently set up a proxy repository (JFrog's hosted artifactory to be specific) where we need authentication and ssl support in order to access our binaries.

I followed the instructions on setting up sbt to use proxy repositories from http://www.scala-sbt.org/release/docs/Detailed-Topics/Proxy-Repositories.html.  There is no mention of how to get username/ encrypted passwords to be fed to sbt, so I tried adding the credentials the way I would for a normal repository (like a global plugin).  I added something like the following to my global.sbt:

credentials += Credentials("Artifactory Realm", "company.artifactoryonline.com", "@myusername@", "@myencryptedpassword@")

I am seeing the following in the debug log:

[debug] try to get credentials for: Artifactory Re...@company.artifactoryonline.com
[debug] authentication: k='Artifactory Re...@company.artifactoryonline.com' c='null'
[debug] HTTP response status: 401 url=https://company.artifactoryonline.com/company/libs-releases/net/virtual-void/sbt-dependency-graph_2.9.2_0.12/0.7.0/sbt-dependency-graph-0.7.0.pom
[debug] CLIENT ERROR: Unauthorized url=https://company.artifactoryonline.com/company/libs-releases/net/virtual-void/sbt-dependency-graph_2.9.2_0.12/0.7.0/sbt-dependency-graph-0.7.0.pom

It seems like sbt is NOT seeing my credentials in the global ~/.sbt/ directory...which led me to think there is a special case for proxy repositories. 

I did test the credentials via our web browser against identical urls and they work fine.

Josh has since confirmed my suspicions that sbt itself does not read this file for it's own build repositories at this time.  

I think some type of reference in the .sbt/repositories file would be a good solution for this issue - in the meantime is there a simple workaround?

**Comment by gmalouf** [comment] 2013-07-23 15:01
I take it this is still the case in sbt 0.12.4?

**Comment by jsuereth** [comment] 2013-07-23 15:03
yes.   Still working on a more principled solution.  I'm actually working on trying to remove the need for security realm in ivy first.   Sorry for any inconvenience here...

**Comment by gmalouf** [comment] 2013-07-23 15:06
Understood; my workaround today is to move the repositories file to an alternate location when downloading a new sbt release.

**Comment by jsuereth** [comment] 2013-07-23 15:10
Actually, if you use the sbt 0.13.0-RC3 launcher, it looks like you can specify credentials now:

https://github.com/sbt/sbt/commit/96e5a7957c830430f85b6b89d7bbe07824ebfc4b

Albeit, I'd like a nicer solution eventually, that should work for now.

**Comment by harrah** [comment] 2013-07-23 19:37
Pretty sure that has been in there since 0.11.3-2.  At the bottom of the commit message, you can see the tags with that commit included.

**Comment by hsn10** [comment] 2013-12-12 09:12
is this https://github.com/sbt/sbt/commit/96e5a7957c830430f85b6b89d7bbe07824ebfc4b documented somewhere?

**Comment by hsn10** [comment] 2013-12-12 10:21
I can not get it work. Can you add debug messages to Update.scala line 52 - "Reading properties file"
and at line 60 if all needed properties are defined "boot Credentials loaded"?

**Comment by jsuereth** [comment] 2014-08-08 15:48
Closing as duplicate of #731

**Closed as completed by jsuereth** 2014-08-08 15:48 UTC

**Comment by dwijnand** [comment] 2015-02-25 06:38
Duplicate of #576
