### ISSUE TITLE
super shell will print evey  progress log but overwrite the same line like a progress bar.

### ISSUE THREAD

**Issue by greatmengqi** [sbt/sbt#5066] opened 2019-09-10 15:47 UTC
## steps
sbt version: 1.3.0

## problem
while I run a task in new super shell , it will print some sentences like "| => global-plugins-build / update 0s". these sentence are so many that I can't read nomoral logs.

## notes
mac os 10.14.6
java 1.8

**Comment by eed3si9n** [comment] 2019-09-10 18:41
@greatmengqi Thanks for the report. For us to actually work on this, we would need more info and a way to reproduce the problem on our machines.

1. Do you have a public project that demonstrates the issue. For example does it happen using akka/akka or something?
2. Could you use https://asciinema.org/ or some other means to record your screen when this happens plz?

**Comment by eed3si9n** [comment] 2019-09-10 18:47
For reference see

[![asciicast](https://asciinema.org/a/ghMoo4BNCKMCjbykBM18hRnuy.svg)](https://asciinema.org/a/ghMoo4BNCKMCjbykBM18hRnuy)

 attached to https://github.com/sbt/sbt/pull/5023#issuecomment-527249288.

super shell progress lines overwrites themselves, but _as long as sbt logger is used_ the log output should scroll up on a separate section.

**Comment by greatmengqi** [comment] 2019-09-11 02:30
I make a temp repository on git hub .the adress is :[pic for sbt](https://github.com/greatmengqi/PicForSbt.git). In this repository I make a small video to record the logs when I start sbt in IDEA .
the start command ：
`/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin/java -server -Xmx1024M -Didea.managed=true -Dfile.encoding=UTF-8 -jar "/Users/chenmengqi/Library/Application Support/IntelliJIdea2019.1/Scala/launcher/sbt-launch.jar" --addPluginSbtFile=/private/var/folders/y4/ff7xp6qd73d73k_t4kd7jn8h0000gn/T/idea1397.sbt "; set ideaPort in Global := 56866 ; idea-shell"
`

**Comment by greatmengqi** [comment] 2019-09-11 02:35
In fact ,if I don't start sbt in IDEA ,just start sbt in terminal.it works normally. so I'm not sure what happened on it.

**Comment by eatkins** [comment] 2019-09-11 02:40
I think newer versions of IDEA turn off super shell.

**Comment by greatmengqi** [comment] 2019-09-11 02:49
> I think newer versions of IDEA turn off super shell.

I don't think so . I add the option "-Dsbt.supershell=false",it work well.so I think new version of IDEA does not turn off super shell default. you need turn off it by your self

**Comment by eatkins** [comment] 2019-09-11 02:55
I am running 2019.2 and the command issued by intellij starts with: `/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=localhost:55109,suspend=n,server=y -Xdebug -server -Dsbt.supershell=false -Xms2048M -Xmx2048M -Xss2M -Xmx4048M -Didea.managed=true -Dfile.encoding=UTF-8 -jar`
I don't set any launch parameters:
<img width="670" alt="Screen Shot 2019-09-10 at 7 54 49 PM" src="https://user-images.githubusercontent.com/2658825/64664728-e2b54900-d404-11e9-936d-91dd49c4e4f4.png">

**Comment by greatmengqi** [comment] 2019-09-11 03:05
> I am running 2019.2 and the command issued by intellij starts with: `/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=localhost:55109,suspend=n,server=y -Xdebug -server -Dsbt.supershell=false -Xms2048M -Xmx2048M -Xss2M -Xmx4048M -Didea.managed=true -Dfile.encoding=UTF-8 -jar`
> I don't set any launch parameters:
> <img alt="Screen Shot 2019-09-10 at 7 54 49 PM" width="670" src="https://user-images.githubusercontent.com/2658825/64664728-e2b54900-d404-11e9-936d-91dd49c4e4f4.png">

I'm sorry , I can't see your picture.did it work normally?

**Comment by greatmengqi** [comment] 2019-09-11 03:11
> I am running 2019.2 and the command issued by intellij starts with: `/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=localhost:55109,suspend=n,server=y -Xdebug -server -Dsbt.supershell=false -Xms2048M -Xmx2048M -Xss2M -Xmx4048M -Didea.managed=true -Dfile.encoding=UTF-8 -jar`
> I don't set any launch parameters:
> <img alt="Screen Shot 2019-09-10 at 7 54 49 PM" width="670" src="https://user-images.githubusercontent.com/2658825/64664728-e2b54900-d404-11e9-936d-91dd49c4e4f4.png">
Maybe you're right. the same command I support before, works well in terminal.

**Comment by greatmengqi** [comment] 2019-09-11 03:50
I update my IDEA to 2019.2 and turn on super shell ,it still works unnormal.

![image](https://user-images.githubusercontent.com/24458013/64667087-26529600-d48b-11e9-9dbd-68f680edfbaa.png)

**Comment by eatkins** [comment] 2019-09-11 04:07
Why are you turning on supershell explicitly for IDEA?

**Comment by eatkins** [comment] 2019-09-11 04:09
I haven’t tested supershell from within IDEA, but the feature is only designed to be used with fully ansi compatible terminal emulators. I don’t know that the built in intellij terminal emulator is fully compliant.

**Comment by greatmengqi** [comment] 2019-09-11 04:39
> I haven’t tested supershell from within IDEA, but the feature is only designed to be used with fully ansi compatible terminal emulators. I don’t know that the built in intellij terminal emulator is fully compliant.

I understand，Thank you for you patiently explain

**Comment by eed3si9n** [comment] 2019-09-11 14:19
Looks like there isn't much we can do on our side, so I am closing this.

**Closed as completed by eed3si9n** 2019-09-11 14:19 UTC
Labels: Needs Reproduction Test Case, area/shell

**Comment by tiongl** [comment] 2019-09-27 17:48
@greatmengqi I think -Dsbt.supershell=false fixes it.
