### ISSUE TITLE
sbt compile failed if there is a directory named xxx.scala

### ISSUE THREAD

**Issue by Atry** [sbt/sbt#3054] opened 2017-03-29 02:16 UTC
(See the guidelines for contributing, linked above)

## steps

```
echo > build.sbt
mkdir xxx.scala
sbt compile
```

## problem

```
[info] Loading global plugins from /Users/twer/.sbt/0.13/plugins
[info] Set current project to tmp (in build file:/private/tmp/)
[info] Updating {file:/private/tmp/}tmp...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /private/tmp/target/scala-2.10/classes...
[error] source file '/private/tmp/xxx.scala' could not be found
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 1 s, completed 2017-3-29 10:15:24
```

## expectation

Expect no error

**Comment by Atry** [comment] 2017-03-29 02:20
Looks like this bug has been fixed in https://github.com/sbt/sbt/commit/a6e31a0dc7be809e8774a4acb8d6be6a43654b6b

Is it possible to backport it to 0.13.x branch?

**Comment by dwijnand** [comment] 2017-03-29 02:59
Yeah, that would be a welcome contribution to 0.13.

**Comment by eed3si9n** [comment] 2017-03-30 19:02
So this is a duplicate of #2552 that hasn't been backported to 0.13.

**Closed as completed** 2017-03-31 03:40 UTC
Labels: Duplicate, help wanted
