### ISSUE TITLE
Scripted name clashing

### ISSUE THREAD

**Issue by doncorsean-private** [sbt/sbt#3812] opened 2017-12-14 20:06 UTC
#https://github.com/foundweekends/giter8/issues/360

# problem
Scripted is hardcoded to use a file called `test`. When using giter8 to create a play template with a `test` folder the scripted tests fail as scripted finds the `test` dir and not the script named `test` 

## expectation
be able to run scripted tests against projects that define a test directory. could be as simple as changing the filename scripted is looking for to scriptedTest or similar.

**Comment by xuwei-k** [comment] 2017-12-19 04:49
https://github.com/sbt/sbt/issues/630 ?

**Comment by dwijnand** [comment] 2017-12-19 07:25
Oh wow, a three digit issue.

Duplicate of #630.

**Closed as completed by dwijnand** 2017-12-19 07:25 UTC
