### ISSUE TITLE
Too many warnings on our code base

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3512] opened 2017-09-10 19:37 UTC
We have too many warnings on our code base to that point it's just adding noise to daily coding or CI. The warnings make sense only if we take some actions.
Could we set fatal warning for Scala 2.12 and turn *off* warnings until we clean up the code?

The especially noisy one is the unused pattern matching variable one. Due to bincompat, we will always have unused constructors etc.

**Comment by freeman42x** [comment] 2017-09-15 10:51
I'll be working on this for the Scala Spree taking place in Dublin right now if that is ok

**Comment by freeman42x** [comment] 2017-10-20 16:05
Some warnings are caused by sbt-contraband generated code, for example:

```
[warn] /home/neo/Forks/sbt/protocol/src/main/contraband-scala/sbt/internal/langserver/ClientCapabilities.scala:12:8: pattern var x in method equals is never used; `x@_' suppresses this warning
[warn]   case x: ClientCapabilities => true
```

**Comment by SethTisue** [comment] 2017-10-20 17:07
perhaps https://github.com/ghik/silencer would be helpful here

**Comment by freeman42x** [comment] 2017-10-20 17:33
@SethTisue that plugin might be useful for some other issues but how would it work for files generated by sbt-contraband?

And to be honest it is unlikely that most warnings should be silenced - if any. The problem should - if possible - be solved at the root.

**Comment by freeman42x** [comment] 2017-10-21 00:33
For:

```
[warn] /home/neo/Forks/sbt/testing/src/main/scala/sbt/TestReportListener.scala:28:21: parameter value test in method contentLogger is never used
[warn]   def contentLogger(test: TestDefinition): Option[ContentLogger] = None
```

```scala
trait TestReportListener {
  def contentLogger(test: TestDefinition): Option[ContentLogger] = None
}
```

I'll use this unless someone comes with a proper solution:

```scala
trait TestReportListener {
  def contentLogger(test: TestDefinition): Option[ContentLogger] = { locally(test); None }
}
```

**Comment by eed3si9n** [comment] 2017-10-21 00:35
@razvan-panda Maybe it should be noted with a comment that `locally(test)` is just there to suppress the warning.

**Comment by freeman42x** [comment] 2017-10-21 00:37
@eed3si9n I can add that but it should be clear enough based on the source of `locally`.
There are a ton of these kinds of errors.
Might be a better idea to just use what @SethTisue suggested: https://github.com/ghik/silencer

**Comment by freeman42x** [comment] 2017-10-21 18:59
Related: https://github.com/sbt/sbt/pull/3658
Need to possibly re-enable warnings that have been disabled in that MR.

**Comment by dwijnand** [comment] 2017-12-20 10:46
In large parts resolved with https://github.com/sbt/sbt/pull/3807.

There's a few more to do, but I stopped myself going down a rabbit hole (in sbt-contraband's impl) to ship the value added in https://github.com/sbt/sbt/pull/3807.

**Closed as completed by dwijnand** 2017-12-20 10:46 UTC
Labels: Meta task
