### ISSUE TITLE
Allow cross-building of multiple Scala 3 releases by using the full scalaVersion in the crossTarget directory

### ISSUE THREAD

**Issue by smarter** [sbt/sbt#6415] opened 2021-03-25 23:15 UTC
Currently, the target directory for a given Scala version is `target/scala-${scalaBinaryVersion}`, this means that one shouldn't have two different Scala versions with the same binary version in `crossScalaVersion`, otherwise they'll keep overwriting each other classfiles (I don't know what wold happen exactly, does sbt manages to delete the target directory content when switching version?).
This hasn't really been a problem sufficient so far, but Scala 3 is coming and I think there's valid usecases for cross-compiling between multiple compiler versions:
- If I maintain a library, I may want to cross-compile between 3.0 (this is the minimum version I support and the one I'll publish binaries for) and 3.1 (I won't publish artifacts compiled with it, but I want to make sure it passes my CI)
- In general, I may want to cross-compile between the latest stable version (e.G. 3.0.0) and the latest RC version (e.g. 3.0.1-RC1), to provide feedback on the RC before the release.

To accommodate these usecases, I propose changing `crossTarget` to append the full `scalaVersion` to the target directory name instead of just the `scalaBinaryVersion`. If we want the change to be less disruptive, we could keep the current behavior for Scala 2 and only use the full version for Scala 3. What do you think? /cc @adpi2

**Comment by adpi2** [comment] 2021-03-26 10:06
Thanks @smarter for sharing your thoughts. It is indeed a valid concern, though I am not 100% convinced by the arguments.

> If I maintain a library, I may want to cross-compile between 3.0 (this is the minimum version I support and the one I'll publish binaries for) and 3.1 (I won't publish artifacts compiled with it, but I want to make sure it passes my CI)

AFAIK the official story is that 3.0 and 3.1 are strictly binary compatible. If that's correct, why would you not bump to 3.1?

> In general, I may want to cross-compile between the latest stable version (e.G. 3.0.0) and the latest RC version (e.g. 3.0.1-RC1), to provide feedback on the RC before the release.

On one hand, it's indeed important the community is active in testing RCs and we should make sure it does not corrupt their binaries. On the other hand it is kind of a niche feature because most projects won't be cross-compiled to RCs. Also it is obvious that RCs are dangerous.

So I am not sure if we should do something or not. If we do something I would be in favor of making an exception just for pre-release versions like RCs, Milestones and snapshots.

@sjrd, @eed3si9n What do you think?

**Comment by sjrd** [comment] 2021-03-26 11:59
I don't have a strong opinion. The current behavior has already always been nonsensical for compiler plugins, for example, which compile under full versions. And yet it's never been a real problem for compiler plugins, so it probably won't become a problem now.

From a logical point of view, `crossTarget` should depend on `crossVersion`, and not just `binaryVersion`, since a library is supposed to be compiled once per cross version.

Or else, we could use the full `scalaVersion`, sure.

Or, you know, it could also be independent of the Scala version altogether, since there's no evidence that it causes any issue.

**Comment by adpi2** [comment] 2021-03-26 12:26
> The current behavior has already always been nonsensical for compiler plugins, for example, which compile under full versions. And yet it's never been a real problem for compiler plugins, so it probably won't become a problem now.

The sbt philosophy is to provide a default configuration for the majority and leave it open for the minority. So the question becomes what default behavior do we want?

> From a logical point of view, crossTarget should depend on crossVersion, and not just binaryVersion, since a library is supposed to be compiled once per cross version.

I don't know exactly what is `crossVersion`. But it seems to me that the project matrix feature solves our problem (and others). I wish it becomes the default and replace `crossVersions`.

**Comment by sjrd** [comment] 2021-03-26 12:43
`crossVersion` is the `CrossVersion` with which your artifact is going to be published. This is a critically important concept, that project-matrix does not replace in any way. Compiler plugins must set their `crossVersion` to `CrossVersion.full`. Scala.js projects are configured to have `crossVersion` be `CrossVersion.binary("", "_sjs1")`, so that they are published using the right suffixes.

**Comment by smarter** [comment] 2021-03-26 13:02
> AFAIK the official story is that 3.0 and 3.1 are strictly binary compatible. If that's correct, why would you not bump to 3.1?

Because artifacts built against 3.1 cannot be used from 3.0, it means your users need to upgrade if you upgrade, this shouldn't be a big issue (it matches what Scala.js does), but it's something that some library authors were concerned about when we discussed this scheme with them.

> If we do something I would be in favor of making an exception just for pre-release versions like RCs, Milestones and snapshots.

That partially addresses the problem, but I'm still concerned by what would happen if someone tried to cross between 3.0 and 3.1 then, at a minimum we need to make sure that neither compiler can see the output of the other one, otherwise you could get all sort of issues, using different directories seems like the simplest solution for achieving this.

**Comment by eed3si9n** [comment] 2021-03-26 14:28
Is this a duplicate of https://github.com/sbt/sbt/issues/5097?

**Comment by smarter** [comment] 2021-03-26 14:31
Not exactly, I'm advocating for crossTarget to use the full scalaVersion even with the default non-full CrossVersion

**Comment by eed3si9n** [comment] 2021-03-26 14:39
ok. I'm open to the idea of `scalaVersion` as the cross target directory at all times to accommodate cross building of _binary-compatible_ Scala versions. It makes sense to me, like testing against multiple JDKs.

**Comment by eed3si9n** [comment] 2021-03-26 14:46
@sjrd 

> I don't have a strong opinion. The current behavior has already always been nonsensical for compiler plugins, for example, which compile under full versions. And yet it's never been a real problem for compiler plugins, so it probably won't become a problem now.

I think it's in part due to the fact that not all compiler plugin authors have been using `CrossVersion.full`, but thanks to recent Scala 2.12 binary breakage, more plugins authors may switch to using `full` and run into https://github.com/sbt/sbt/issues/5097

**Comment by eed3si9n** [comment] 2021-03-29 04:44
@smarter As I implemented this change, it dawned on me that this is going to be a big breaking change for any tests or Bash scripts out there that might be relying on the exact location of the output JAR.

I don't think I should make this change until sbt 2.0 without some opt-in setting.

**Comment by smarter** [comment] 2021-03-29 08:38
In my original message I suggested:
> If we want the change to be less disruptive, we could keep the current behavior for Scala 2 and only use the full version for Scala 3.

To accommodate existing scripts which hardcode the target directory.

**Closed as completed** 2021-04-02 14:55 UTC
Labels: Enhancement, area/cross_building, area/scala3
