### ISSUE TITLE
Debian installation fails: The repository 'https://dl.bintray.com/sbt/debian  Release' is not signed

### ISSUE THREAD

**Issue by dragisak** [sbt/sbt#3883] opened 2018-01-15 03:11 UTC
`apt update ` fails on Ubuntu 17.10

    echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
    deb https://dl.bintray.com/sbt/debian /
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
    Executing: /tmp/apt-key-gpghome.eBicDUYVIc/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
    gpg: key 99E82A75642AC823: "sbt build tool <scalasbt@gmail.com>" not changed
    gpg: Total number processed: 1
    gpg:              unchanged: 1
    sudo apt-get update
    ... 
    Get:12 https://dl.bintray.com/sbt/debian  Release [815 B]                                                             
    Ign:13 https://dl.bintray.com/sbt/debian  Release.gpg                                                                         
    Reading package lists... Done        
    E: The repository 'https://dl.bintray.com/sbt/debian  Release' is not signed.
    N: Updating from such a repository can't be done securely, and is therefore disabled by default.
    N: See apt-secure(8) manpage for repository creation and user configuration details.
\

**Comment by eed3si9n** [comment] 2018-01-15 03:26
Duplicate of https://github.com/sbt/sbt-launcher-package/issues/208.
It should be fixed now.

**Closed as completed by eed3si9n** 2018-01-15 03:26 UTC
Labels: area/linux
