### ISSUE TITLE
(Compile / packageSrc) java.util.zip.ZipException: duplicate entry

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4591] opened 2019-03-31 03:34 UTC
## steps

1. git clone dotty
2. git checkout e4c4e0aae27c1316cae0e63278d7e4549f2890ea
3. open sbt with a recent nightly
4. sbt-dotty/publishLocal

## problem

```
sbt:dotty> sbt-dotty/publishLocal
[info] Wrote /xxx/dotty/sbt-dotty/target/scala-2.12/sbt-1.0/sbt-dotty-0.3.2-SNAPSHOT.pom
[error] java.util.zip.ZipException: duplicate entry: dotty/tools/sbtplugin/DottyPlugin.scala
[error] 	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
[error] 	at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
[error] 	at sbt.io.IO$.addFileEntry$1(IO.scala:653)
[error] 	at sbt.io.IO$.$anonfun$writeZip$3(IO.scala:662)
[error] 	at sbt.io.IO$.$anonfun$writeZip$3$adapted(IO.scala:662)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sbt.io.IO$.writeZip(IO.scala:662)
[error] 	at sbt.io.IO$.$anonfun$archive$1(IO.scala:616)
[error] 	at sbt.io.IO$.$anonfun$archive$1$adapted(IO.scala:613)
[error] 	at sbt.io.IO$.$anonfun$withZipOutput$1(IO.scala:698)
[error] 	at sbt.io.IO$.$anonfun$withZipOutput$1$adapted(IO.scala:687)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.io.IO$.withZipOutput(IO.scala:687)
[error] 	at sbt.io.IO$.archive(IO.scala:613)
[error] 	at sbt.io.IO$.jar(IO.scala:589)
[error] 	at sbt.Package$.makeJar(Package.scala:164)
[error] 	at sbt.Package$.$anonfun$apply$4(Package.scala:99)
[error] 	at sbt.Package$.$anonfun$apply$4$adapted(Package.scala:97)
[error] 	at sbt.util.Tracked$.$anonfun$outputChanged$1(Tracked.scala:101)
[error] 	at sbt.Package$.apply(Package.scala:108)
[error] 	at sbt.Defaults$.$anonfun$packageTask$1(Defaults.scala:1286)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:268)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:277)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:268)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

## expectation

works.

## notes

```
sbt:sbt-dotty> show Compile/unmanagedSourceDirectories
[info] * /xxx/dotty/sbt-dotty/src-2.12
[info] * /xxx/dotty/sbt-dotty/src
[info] * /xxx/dotty/sbt-dotty/src
[info] * /xxx/dotty/sbt-dotty/src-sbt-1.0
[info] * /xxx/dotty/sbt-dotty/../language-server/src/dotty/tools/languageserver/config
```

**Comment by eatkins** [comment] 2019-03-31 06:58
Almost surely my fault. Should be an easy fix I’d think though.

**Comment by eatkins** [comment] 2019-03-31 16:16
I couldn't reproduce off of the latest origin/develop. I am pretty sure this was fixed in https://github.com/sbt/sbt/pull/4512/commits/c72005fd2b5be05df1df40acd6a0a158b9355b9b
If you look at the changes I made in GlobLister.scala, I aggregate the globs to ensure that I don't return duplicate entries in `globs.all`.

**Closed as completed by eatkins** 2019-03-31 16:16 UTC
Labels: Regression
