### ISSUE TITLE
InvocationTargetException while launching from maven-local repo that is missing JAR files

### ISSUE THREAD

**Issue by spencerhakim** [sbt/sbt#6764] opened 2021-12-28 20:31 UTC
## steps

1. Update a  project's `build.properties` to use sbt 1.6.0
2. Run any sbt command (such as `sbt shell` or `sbt clean`)

## problem

sbt prints a stack trace and exits with error code 1

## expectation

sbt successfully performs the command

## notes

I'm upgrading from 1.5.8 and experiencing this across multiple projects. Tried clearing the `./project/project` and `./project/target` folders from my projects, as well as the various generated folders in `~/.sbt/1.0`, but it made no difference. Only thing that might be unusual about my setup is that I use a private repository for work, and have `SBT_CREDENTIALS="$HOME/.sbt/.credentials"` defined, as well as a `~/.sbt/repositories` and `~/.sbt/1.0/credentials.sbt` (which simply contains `credentials += Credentials(Path.userHome / ".sbt" / ".credentials")`)

```
$> sbt --debug shell

[addSbt] arg = '-debug'
[residual] arg = 'shell'
[sbt_options] declare -a sbt_options=()
[process_args] java_version = '11'
[addMemory] arg = '1024'
[addJava] arg = '-Xms1024m'
[addJava] arg = '-Xmx1024m'
[addJava] arg = '-Xss4M'
[addJava] arg = '-XX:ReservedCodeCacheSize=128m'
[addJava] arg = '-Dsbt.script=/usr/local/Cellar/sbt/1.6.0/libexec/bin/sbt'
[copyRt] java9_rt = '/Users/shakim/.sbt/1.0/java9-rt-ext-amazon_com_inc__11_0_13/rt.jar'
[addJava] arg = '-Dscala.ext.dirs=/Users/shakim/.sbt/1.0/java9-rt-ext-amazon_com_inc__11_0_13'
# Executing command line:
java
-Dfile.encoding=UTF-8
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-Dsbt.script=/usr/local/Cellar/sbt/1.6.0/libexec/bin/sbt
-Dscala.ext.dirs=/Users/shakim/.sbt/1.0/java9-rt-ext-amazon_com_inc__11_0_13
-jar
/usr/local/Cellar/sbt/1.6.0/libexec/bin/sbt-launch.jar
-debug
shell

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at sbt.internal.XMainConfiguration.makeConfiguration(XMainConfiguration.java:103)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:46)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sbt.internal.XMainConfiguration.makeConfiguration(XMainConfiguration.java:85)
	... 13 more
Caused by: java.lang.NullPointerException
	at java.base/java.util.ArrayDeque.addLast(ArrayDeque.java:304)
	at java.base/java.util.ArrayDeque.add(ArrayDeque.java:495)
	at java.base/jdk.internal.loader.URLClassPath.<init>(URLClassPath.java:155)
	at java.base/jdk.internal.loader.URLClassPath.<init>(URLClassPath.java:172)
	at java.base/java.net.URLClassLoader.<init>(URLClassLoader.java:120)
	at sbt.internal.JLineLoader.<init>(JLineLoader.java:15)
	at sbt.internal.MetaBuildLoader.makeLoader(MetaBuildLoader.java:152)
	... 18 more
[error] [launcher] error during sbt launcher: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
```

**Comment by eed3si9n** [comment] 2021-12-28 22:19
@spencerhakim Thanks for the report.

There was indeed a change related to `SBT_CREDENTIALS` in https://github.com/sbt/sbt/pull/6724, so I wonder if we're hitting some initialization issues. In particular, I wonder if the following should be a `def` or `lazy val`:

https://github.com/sbt/sbt/blob/45aa8cb75c71dccf4116a0de6baefd665f5f517d/main/src/main/scala/sbt/internal/SysProp.scala#L221-L222

@daddykotex Does sbt 1.6.0 work for you?

**Comment by daddykotex** [comment] 2021-12-28 23:59
I've upgraded my reproduction test to 1.6.0 and did a few tests. Here are the results:

- [x] 1.6.0 - no credentials, no repositories, blank installation, java 8
- [x] 1.6.0 - your setup: SBT_CREDENTIALS, repositories file, credentials file and credentials.sbt setting, java 8
- [x] 1.6.0 - your setup: SBT_CREDENTIALS, repositories file, credentials file and credentials.sbt setting, java 11

```
> docker run -it --link nexus:nexus --entrypoint /bin/bash  sbt-1.6.0-2-j11
root@a3e59bd1004a:/reproduction# mkdir -p /root/.sbt/1.0/plugins
root@a3e59bd1004a:/reproduction# sbt --dnug test
copying runtime jar...
^C^[[A[info] [launcher] getting org.scala-sbt sbt 1.6.0  (this may take some time)...
^Croot@a3e59bd1004a:/reproduction# sbt --debug test
[addSbt] arg = '-debug'
[residual] arg = 'test'
[sbt_options] declare -a sbt_options=()
[process_args] java_version = '11'
[addMemory] arg = '1024'
[addJava] arg = '-Xms1024m'
[addJava] arg = '-Xmx1024m'
[addJava] arg = '-Xss4M'
[addJava] arg = '-XX:ReservedCodeCacheSize=128m'
[addJava] arg = '-Dsbt.script=/usr/local/bin/sbt'
[copyRt] java9_rt = '/root/.sbt/1.0/java9-rt-ext-eclipse_adoptium_11_0_13/rt.jar'
copying runtime jar...
[addJava] arg = '-Dscala.ext.dirs=/root/.sbt/1.0/java9-rt-ext-eclipse_adoptium_11_0_13'
# Executing command line:
java
-Dfile.encoding=UTF-8
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-Dsbt.script=/usr/local/bin/sbt
-Dscala.ext.dirs=/root/.sbt/1.0/java9-rt-ext-eclipse_adoptium_11_0_13
-jar
/opt/sbt/bin/sbt-launch.jar
-debug
test

[info] [launcher] getting org.scala-sbt sbt 1.6.0  (this may take some time)...
[info] [launcher] getting Scala 2.12.15 (for sbt)...
[debug] not up to date. inChanged = true, force = false
[debug] Updating ProjectRef(uri("file:/root/.sbt/1.0/plugins/"), "global-plugins")...
[info] Updating
https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.pom
  100.0% [##########] 19.4 KiB (32.5 KiB / s)
[info] Resolved  dependencies
[info] Fetching artifacts of
[info] Fetched artifacts of
[debug] Done updating ProjectRef(uri("file:/root/.sbt/1.0/plugins/"), "global-plugins")
[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 0 products, 0 sources, 0 libraries
[debug] current source = Set()
[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[debug] Full compilation, no sources in previous analysis.
[debug] Created transactional ClassFileManager with tempDir = /root/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes.bak
[debug] Removing the temporary directory used for backing up class files: /root/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes.bak
[debug] Copy resource mappings:
[debug]
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] not up to date. inChanged = true, force = false
[debug] Updating ProjectRef(uri("file:/reproduction/project/"), "reproduction-build")...
[debug] Done updating ProjectRef(uri("file:/reproduction/project/"), "reproduction-build")
[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 0 products, 0 sources, 0 libraries
[debug] current source = Set()
[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[debug] Full compilation, no sources in previous analysis.
[debug] Created transactional ClassFileManager with tempDir = /reproduction/project/target/scala-2.12/sbt-1.0/classes.bak
[debug] Removing the temporary directory used for backing up class files: /reproduction/project/target/scala-2.12/sbt-1.0/classes.bak
[debug] Copy resource mappings:
[debug]
[debug] Copy resource mappings:
[debug]
[debug] not up to date. inChanged = true, force = false
[debug] Updating ...
[info] Updating
http://nexus:8081/repository/maven-public/com/typesafe/config/1.4.1/config-1.4.1.pom
  100.0% [##########] 2.2 KiB (77.8 KiB / s)
[info] Resolved  dependencies
[info] Updating
http://nexus:8081/repository/maven-public/jline/jline/2.14.6/jline-2.14.6.pom
  100.0% [##########] 19.4 KiB (462.5 KiB / s)
[info] Resolved  dependencies
[info] Fetching artifacts of
http://nexus:8081/repository/maven-public/com/typesafe/config/1.4.1/config-1.4.1.jar
  100.0% [##########] 288.3 KiB (7.6 MiB / s)
http://nexus:8081/repository/maven-public/jline/jline/2.14.6/jline-2.14.6.jar
  100.0% [##########] 262.5 KiB (6.9 MiB / s)
[info] Fetched artifacts of
[debug] Done updating
[debug] Copy resource mappings:
[debug]
[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 0 products, 0 sources, 0 libraries
[debug] current source = Set(${BASE}/src/main/scala/Main.scala)
[debug] > initialChanges = InitialChanges(Changes(added = Set(${BASE}/src/main/scala/Main.scala), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[debug] Full compilation, no sources in previous analysis.
[debug] all 1 sources are invalidated
[debug] Created transactional ClassFileManager with tempDir = /reproduction/target/scala-2.12/classes.bak
[debug] Initial set of included nodes:
[debug] Recompiling all sources: number of invalidated sources > 50.0% of all sources
[debug] About to delete class files:
[debug] We backup class files:
[debug] compilation cycle 1
[info] compiling 1 Scala source to /reproduction/target/scala-2.12/classes ...
[debug] Getting org.scala-sbt:compiler-bridge_2.12:1.6.0:compile for Scala 2.12.15
http://nexus:8081/repository/maven-public/org/scala-sbt/compiler-bridge_2.12/1.6.0/compiler-bridge_2.12-1.6.0-sources.jar
  100.0% [##########] 52.8 KiB (2.7 MiB / s)
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.15. Compiling...
[debug] Creating plain compiler interface for 2.12.15.
[debug]   > Arguments:
[debug] 	-d
[debug] 	/tmp/sbt_3f8576a5
[debug] 	-nowarn
[debug] 	-bootclasspath
[debug] 	/root/.sbt/boot/scala-2.12.15/lib/scala-library.jar
[debug] 	-classpath
[debug] 	/root/.cache/coursier/v1/http/admin%40nexus%3A8081/repository/maven-public/org/scala-sbt/compiler-interface/1.6.0/compiler-interface-1.6.0.jar:/root/.cache/coursier/v1/http/admin%40nexus%3A8081/repository/maven-public/org/scala-sbt/util-interface/1.6.0/util-interface-1.6.0.jar:/root/.cache/coursier/v1/http/admin%40nexus%3A8081/repository/maven-public/org/scala-sbt/compiler-bridge_2.12/1.6.0/compiler-bridge_2.12-1.6.0-sources.jar:/root/.sbt/boot/scala-2.12.15/lib/scala-xml_2.12-1.0.6.jar:/root/.sbt/boot/scala-2.12.15/lib/scala-compiler.jar:/root/.sbt/boot/scala-2.12.15/lib/scala-reflect.jar
[debug] 	/tmp/sbt_814462c6/scala/ZincCompat.scala
[debug] 	/tmp/sbt_814462c6/xsbt/API.scala
[debug] 	/tmp/sbt_814462c6/xsbt/AbstractZincFile.scala
[debug] 	/tmp/sbt_814462c6/xsbt/Analyzer.scala
[debug] 	/tmp/sbt_814462c6/xsbt/CallbackGlobal.scala
[debug] 	/tmp/sbt_814462c6/xsbt/ClassName.scala
[debug] 	/tmp/sbt_814462c6/xsbt/Compat.scala
[debug] 	/tmp/sbt_814462c6/xsbt/CompilerBridge.scala
[debug] 	/tmp/sbt_814462c6/xsbt/ConsoleBridge.scala
[debug] 	/tmp/sbt_814462c6/xsbt/DelegatingReporter.scala
[debug] 	/tmp/sbt_814462c6/xsbt/Dependency.scala
[debug] 	/tmp/sbt_814462c6/xsbt/ExtractAPI.scala
[debug] 	/tmp/sbt_814462c6/xsbt/ExtractUsedNames.scala
[debug] 	/tmp/sbt_814462c6/xsbt/GlobalHelpers.scala
[debug] 	/tmp/sbt_814462c6/xsbt/InteractiveConsoleBridge.scala
[debug] 	/tmp/sbt_814462c6/xsbt/InteractiveConsoleFactoryBridge.scala
[debug] 	/tmp/sbt_814462c6/xsbt/InteractiveConsoleHelper.scala
[debug] 	/tmp/sbt_814462c6/xsbt/InteractiveConsoleResponse.scala
[debug] 	/tmp/sbt_814462c6/xsbt/JarUtils.scala
[debug] 	/tmp/sbt_814462c6/xsbt/JavaUtils.scala
[debug] 	/tmp/sbt_814462c6/xsbt/LocalToNonLocalClass.scala
[debug] 	/tmp/sbt_814462c6/xsbt/LocateClassFile.scala
[debug] 	/tmp/sbt_814462c6/xsbt/Log.scala
[debug] 	/tmp/sbt_814462c6/xsbt/Message.scala
[debug] 	/tmp/sbt_814462c6/xsbt/PlainNioFile.scala
[debug] 	/tmp/sbt_814462c6/xsbt/ScaladocBridge.scala
[debug]
[info]   Compilation completed in 11.771s.
[debug] [zinc] Running cached compiler 70fea1b6 for Scala compiler version 2.12.15
[debug] [zinc] The Scala compiler is invoked with:
[debug] 	-bootclasspath
[debug] 	/root/.sbt/boot/scala-2.12.15/lib/scala-library.jar
[debug] 	-classpath
[debug] 	/reproduction/target/scala-2.12/classes:/root/.cache/coursier/v1/http/admin%40nexus%3A8081/repository/maven-public/com/typesafe/config/1.4.1/config-1.4.1.jar
[debug] Scala compilation took 12.9224222 s
[debug] done compiling
[debug] Registering generated classes:
[debug] 	Main.class
[debug] 	Main$delayedInit$body.class
[debug] 	Main$.class
[debug] Removing the temporary directory used for backing up class files: /reproduction/target/scala-2.12/classes.bak
[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 0 products, 0 sources, 0 libraries
[debug] current source = Set()
[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[debug] Full compilation, no sources in previous analysis.
[debug] Created transactional ClassFileManager with tempDir = /reproduction/target/scala-2.12/test-classes.bak
[debug] Removing the temporary directory used for backing up class files: /reproduction/target/scala-2.12/test-classes.bak
[debug] Framework implementation 'org.scalacheck.ScalaCheckFramework' not present.
[debug] Framework implementation 'org.specs2.runner.Specs2Framework' not present.
[debug] Framework implementation 'org.specs2.runner.SpecsFramework' not present.
[debug] Framework implementation 'org.specs.runner.SpecsFramework' not present.
[debug] Framework implementation 'org.scalatest.tools.Framework' not present.
[debug] Framework implementation 'org.scalatest.tools.ScalaTestFramework' not present.
[debug] Framework implementation 'com.novocode.junit.JUnitFramework' not present.
[debug] Framework implementation 'munit.Framework' not present.
[debug] Subclass fingerprints: List()
[debug] Annotation fingerprints: List()
root@a3e59bd1004a:/reproduction#
```

here is the output of one run as an example.

**Comment by daddykotex** [comment] 2021-12-29 00:00
I see that we don't use the same JVM. I use temurin (for java 8 and java 11)

**Comment by spencerhakim** [comment] 2021-12-29 00:37
Played around with my setup some more and found the following:

- With `SBT_CREDENTIALS` unset and an empty `~/.sbt`, 1.6.0 booted successfully
- Restoring `SBT_CREDENTIALS` and the various repository/credential files WITHOUT deleting any of the newly created files in `~/.sbt`, 1.6.0 booted successfully
- Renamed `~/.sbt/boot` to `~/.sbt/boot.works` after 1.6.0 has already booted successfully, launcher downloads sbt 1.6.0 and scala 2.12.5 again, then fails with the same stack trace as it did in my original post
- Unsetting _just_ `SBT_CREDENTIALS` did not get it working again

At this point I ran a diff on the two boot dirs:

```
$> diff -ur boot.works boot
Only in boot.works/scala-2.12.15/lib: scala-xml_2.12-1.0.6.jar
Only in boot.works/scala-2.12.15/org.scala-sbt/sbt/1.6.0: jna-5.8.0.jar
Only in boot.works/scala-2.12.15/org.scala-sbt/sbt/1.6.0: jna-platform-5.8.0.jar
```

After a bit of experimenting with different combinations of the env var and `~/.sbt` files, it seems that the presence of my `repositories` file is the trigger for this issue, as removing it while leaving everything else allows 1.6.0 to download/boot successfully (though it then fails to find our private packages, but that's to be expected), so here it is for reference:

```
[repositories]
  local
  maven-local
  corp-ivy-releases: https://nexus3.corp.net/nexus/content/groups/ivy-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  corp-mvn-releases: https://nexus3.corp.net/nexus/content/groups/public/
```

**Comment by eed3si9n** [comment] 2021-12-29 03:40
@spencerhakim Is your launcher the latest? Here's what I have:

```
$ sbt --script-version
1.6.0
$ sbt --launcher-version
sbt launcher version 1.3.3
```

JNA should be on the dependency graph via IO - https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.6.0/io_2.12-1.6.0.pom.

Also could you try removing corp-ivy-releases entry? (Assuming Maven Central is mirrored as-is)

**Comment by spencerhakim** [comment] 2021-12-29 04:41
Yep, running the latest launcher and getting the same version numbers as you. Removing `corp-ivy-releases` did not help. Both `corp-ivy-releases` and `corp-mvn-releases` are proxy groups, as described [here](https://help.sonatype.com/repomanager3/nexus-repository-administration/repository-management#RepositoryManagement-RepositoryGroup); Maven Central is in there somewhere.

**Comment by spencerhakim** [comment] 2021-12-29 16:38
I realized this is a manifestation of an issue that I've seen occasionally pop up during normal development, though I've never seen it affect the sbt boot process before. Best I can figure, the steps to reproduce this are as follows:

0. At some point, Maven (or maybe IntelliJ?) is used and various dependencies are cached in `~/.m2/repository`. For some reason, some artifacts only have their .POM downloaded, but not the .JAR (I'm not familiar enough with the inner workings of Maven/IntelliJ to understand why either tool might do this, maybe just for metadata retrieval?). This isn't a network error or an issue with our private repository, Maven projects all build and execute correctly; it would seem that the .JARs weren't downloaded simply because they weren't needed
![20211229_112641-CapturFiles](https://user-images.githubusercontent.com/606857/147683763-aa5da190-86ae-4c44-bf14-9fa0d350cff8.jpg)
1. sbt (or Coursier?) attempts to retrieve a dependency, first checking `local` and then `maven-local`
2. sbt (or Coursier) finds the .POM of the desired artifact in the local Maven cache and assumes it's a POM-only artifact since there is no matching .JAR file present. The dependency is considered satisfied
3. Eventually, either `scalac` will error out during the build process while complaining about not being able to find some symbols, or the JVM will throw a runtime exception involving the classloader when testing or otherwise executing the project

This issue has been known to my team for some time, but we also know to quickly work around it by just deleting the relevant cached artifact folders (such as `~/.m2/repository/net/java/dev/jna`) and compiling again. Like I said above, I've just never seen it affect the sbt boot process before, so I don't know if this is a new issue or if I just happened to get unlucky this time.

**Comment by eed3si9n** [comment] 2021-12-29 17:04
So the problem is putting `maven-local` into the `repositories` file then, not something intrinsic to sbt 1.6.0?

When dependency resolvers are trying to figure out the dependency graph, it would grab the POM files first, and then the version could get evicted so the cache directory is only that, and isn't guaranteed to function as a repository, I think. I've run into this myself while trying to create an offline image of some version n, and later realize it would fail badly for version n + 1.

**Comment by spencerhakim** [comment] 2021-12-29 17:42
> So the problem is putting `maven-local` into the `repositories` file then, not something intrinsic to sbt 1.6.0?

Correct. Unfortunately `maven-local` is a necessity for us, as we often need to work with local snapshots of a Maven project that is a dependency of an sbt project, otherwise I'd just remove it from our `repositories` file.

At this point I guess this issue can be closed, unless you'd rather repurpose it into a ticket for the issue of having an incomplete cache? Not even sure if that's an sbt issue or a Coursier issue.

**Comment by eed3si9n** [comment] 2021-12-29 17:55
Maybe you can add it at the end.

I'm closing this issue for now since sbt doesn't write things into maven-local other than via publishM2.

**Closed as completed by eed3si9n** 2021-12-29 17:55 UTC
Labels: area/proxy
