### ISSUE TITLE
sbt-launch.jar can't download sbt from password protected repo

### ISSUE THREAD

**Issue by hsn10** [sbt/sbt#807] opened 2013-07-08 16:42 UTC
if i override repositories in ~/.sbt/repositories then sbt-launch do not sets access password as defined in ~/.sbt/nexus.sbt and entire bootstrap process ends with:

 :: org.scala-sbt#sbt;0.12.4: not found

**Comment by jsuereth** [comment] 2013-07-09 15:52
Ah, the launcher uses a slightly altered mechanism of resolving artifacts than sbt itself.   I'll try to add a feature such that you can specify passwords to the launcher via some mechanism, and these can be exposed to the sbt build as well.

**Comment by jsuereth** [comment] 2013-07-09 15:54
Also, this is a duplicate of #731

**Closed as completed by jsuereth** 2013-07-09 15:54 UTC
Labels: Enhancement

**Comment by hsn10** [comment] 2013-07-09 15:59
It would be better to distribute entire app instead of downloader.

**Comment by jsuereth** [comment] 2013-07-09 16:03
Try activator: http://www.typesafe.com/platform/getstarted

Just a nice shell on sbt with all the necssary artifacts local.  If I have time, we may retrofit the sbt packages to have the same mechanism.
