### ISSUE TITLE
Windows ARM issue

### ISSUE THREAD

**Issue by arjenw** [sbt/sbt#7865] opened 2024-11-04 10:50 UTC
## steps

When starting SBT I get the following stack trace:
```
java.lang.UnsatisfiedLinkError: 'long org.fusesource.jansi.internal.Kernel32.GetStdHandle(int)'
        at org.fusesource.jansi.internal.Kernel32.GetStdHandle(Native Method)
        at sbt.internal.util.WindowsSupport$.getConsoleMode(WindowsInputStream.scala:21)
        at sbt.internal.util.JLine3$.setEnableProcessInput(JLine3.scala:208)
        at sbt.internal.util.JLine3$.enterRawMode(JLine3.scala:218)
        at sbt.internal.util.Terminal$ConsoleTerminal.enterRawMode(Terminal.scala:925)
        at sbt.internal.util.Terminal$ConsoleTerminal.<init>(Terminal.scala:878)
        at sbt.internal.util.Terminal$.newConsoleTerminal(Terminal.scala:816)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:396)
        at sbt.xMain$.withStreams$1(Main.scala:89)
        at sbt.xMain$.run(Main.scala:124)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
        at sbt.xMain.run(Main.scala:48)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.UnsatisfiedLinkError: 'long org.fusesource.jansi.internal.Kernel32.GetStdHandle(int)'
``` 

System:
* SBT 1.10.5
* Windows 11 (ARM version)
* Running on Parallels
* Running on Apple Mac M1 (arm64)

## problem

See above.

Jansi-2.4.1 claims to have support for Windows ARM. However, the JAR SBT supplies (in folder `~\.sbt\boot\scala-2.12.20\org.scala-sbt\sbt\1.10.5`) is version 2.4.0 (which is weird as SBT's `project/Dependencies.scala` defines jansi version 2.4.1).

Workaround is to start SBT using:
```
sbt -Djline.terminal=none
```

## expectation

SBT should start successfully of course.

**Comment by Friendseeker** [comment] 2024-11-04 18:34
The cause of the issue is likely due to https://github.com/sbt/sbt/pull/7811, for which we removed the JLine Jansi terminal provider, as that removed provider depends on Jansi 2.4.1.

> However, the JAR SBT supplies (in folder ~\.sbt\boot\scala-2.12.20\org.scala-sbt\sbt\1.10.5) is version 2.4.0 (which is weird as SBT's project/Dependencies.scala defines jansi version 2.4.1).

Probably because sbt native client is a separate project, and that `jansi` is used as native client dependency.

Fix pending in https://github.com/sbt/sbt/pull/7867. Shall test it manually later today.

**Comment by Friendseeker** [comment] 2024-11-05 07:12
I am utterly confused. I have Parallel Desktop Windows 11 on my M1 MacBook, and I cannot reproduce the issue.

```
PS C:\Users\jiahuitan\sbt> sbt
[info] [launcher] getting org.scala-sbt sbt 1.10.5  (this may take some time)...
[info] [launcher] getting Scala 2.12.20 (for sbt)...
[info] welcome to sbt 1.10.5 (Eclipse Adoptium Java 23.0.1)
[info] loading settings for project sbt-build from plugins.sbt ...
[info] loading project definition from C:\Users\jiahuitan\sbt\project
```

While I do think your observation is valid, I do feel like we need to dig slightly deeper into the issue to understand what exactly is going on.

**Comment by mkurz** [comment] 2024-11-05 07:25
@Friendseeker Are you running Windows ARM?

**Comment by Friendseeker** [comment] 2024-11-05 07:31
> @Friendseeker Are you running Windows ARM?

Yes. Thanks to your comment, I found the cause

```
PS C:\Users\jiahuitan> where.exe java
C:\Users\jiahuitan\AppData\Local\Coursier\cache\arc\https\github.com\adoptium\temurin11-binaries\releases\download\jdk-11.0.25%252B9\OpenJDK11U-jdk_x64_windows_hotspot_11.0.25_9.zip\jdk-11.0.25+9\bin\java.exe
C:\Users\jiahuitan\AppData\Local\Coursier\cache\arc\https\github.com\adoptium\temurin23-binaries\releases\download\jdk-23.0.1%252B11\OpenJDK23U-jdk_x64_windows_hotspot_23.0.1_11.zip\jdk-23.0.1+11\bin\java.exe
```

Trust in coursier misplaced, it installed ... amd64 versions of JDK....

I was wondering why sbt is so slow on Parallel Desktop uhhhhhh

**Comment by Friendseeker** [comment] 2024-11-17 05:52
As a quick update, with #7876 merged, sbt no longer depends on `org.fusesource.jansi` directly which means the particular exception `java.lang.UnsatisfiedLinkError: 'long org.fusesource.jansi.internal.Kernel32.GetStdHandle(int)` is fixed.

However sbt still depends on `org.fusesource.jansi` 2.4.0 transitively (via sbt's dependency on [JLine2](https://github.com/sbt/jline2)) and that may cause a `java.lang.UnsatisfiedLinkError` elsewhere. (e.g. `sbt console` for a Scala 2.12 project). That is addressed with https://github.com/sbt/jline2/pull/6, and will be fixed once https://github.com/sbt/jline2 makes a new release.

**Closed as completed by Friendseeker** 2024-11-17 05:52 UTC

**Comment by arjenw** [comment] 2024-11-20 12:59
Thanks for fixing this so quickly! Really appreciated!

**Comment by Friendseeker** [comment] 2024-12-05 19:15
@eed3si9n Shall we make a new JLine 2 release from https://github.com/sbt/jline2/commit/9a88bc413e2b34a4580c001c654d1a7f4f65bf18?

**Comment by eed3si9n** [comment] 2024-12-06 04:36
Done - it should be available in an hour or so.
