### ISSUE TITLE
Retry when fetching artifact from remote resolver (maven for example)

### ISSUE THREAD

**Issue by hagaiovadia** [sbt/sbt#7200] opened 2023-04-04 14:50 UTC
Hi,
There is any retry mechanism built in for sbt?
While sbt fetches artifacts from resolvers it fails on the first attempt and then fail the whole build:

```[2023-04-04T12:37:08.627Z] 	Server access Error: Connection timed out (Connection timed out) url=https://XXXX.XXXX.XXXX/repository/maven-public/org/scala-sbt/sbt/1.6.2/sbt-1.6.2.pom```

The same mechanism is already implemented for publishing:
https://github.com/sbt/librarymanagement/pull/340

Gradle already doing retries automatically:
https://docs.gradle.org/current/userguide/dependency_resolution.html#sub:http-retries

Also, some tech notes might help and I'll be happy to add this feature myself.

**Comment by eed3si9n** [comment] 2023-04-04 21:03
This is a duplicate of https://github.com/sbt/sbt/issues/6685 / https://github.com/coursier/coursier/issues/2217.
> Coursier does retry under some circumstances (see https://github.com/coursier/coursier/pull/507/commits/869d7c628edcd9315a43f75d87614198146ce6bb), but I guess not for  `java.net.ConnectException`.

**Closed as not planned by eed3si9n** 2023-04-04 21:03 UTC

**Comment by hagay3** [comment] 2023-04-15 16:30
@eed3si9n 
10x for the feedback.
Following this thread https://github.com/coursier/coursier/issues/2733#issuecomment-1497082178 
Did retry need to be implemented in [coursier](https://github.com/coursier/coursier) or [sbt-coursier](https://github.com/coursier/sbt-coursier) ?
I'm just not familiar with sbt dependencies.
