### ISSUE TITLE
sbtTransformHash breaks ivy caching

### ISSUE THREAD

**Issue by jroper** [sbt/sbt#2042] opened 2015-05-29 05:54 UTC
For some artifacts (I'm not sure which), sbt adds a `e:sbtTransformHash` element to the ivy data in the cache.  When ivy attempts to parse it, this causes it to fail with a parsing exception:

```
java.text.ParseException: [[Fatal Error] ivy-4.0.xml:21:23: The prefix "e" for element "e:sbtTransformHash" is not bound. in file:/Users/jroper/.ivy2/cache/com.google.inject.extensions/guice-assistedinject/ivy-4.0.xml
]
    at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser$AbstractParser.checkErrors(AbstractModuleDescriptorParser.java:89)
    at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorParser$Parser.parse(XmlModuleDescriptorParser.java:277)
    at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorParser.parseDescriptor(XmlModuleDescriptorParser.java:117)
    at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser.parseDescriptor(AbstractModuleDescriptorParser.java:48)
    at org.apache.ivy.core.cache.DefaultRepositoryCacheManager$MyModuleDescriptorProvider.provideModule(DefaultRepositoryCacheManager.java:714)
    at org.apache.ivy.core.cache.ModuleDescriptorMemoryCache.getStale(ModuleDescriptorMemoryCache.java:68)
    at org.apache.ivy.core.cache.ModuleDescriptorMemoryCache.get(ModuleDescriptorMemoryCache.java:57)
    at org.apache.ivy.core.cache.DefaultRepositoryCacheManager.getMdFromCache(DefaultRepositoryCacheManager.java:723)
    at org.apache.ivy.core.cache.DefaultRepositoryCacheManager.doFindModuleInCache(DefaultRepositoryCacheManager.java:639)
    at org.apache.ivy.core.cache.DefaultRepositoryCacheManager.findModuleInCache(DefaultRepositoryCacheManager.java:597)
    at sbt.IvySbt$$anon$2.findModuleInCache(Ivy.scala:364)
    at org.apache.ivy.plugins.resolver.AbstractResolver.findModuleInCache(AbstractResolver.java:352)
    at sbt.ivyint.SbtChainResolver.protected$findModuleInCache(SbtChainResolver.scala:102)
    at sbt.ivyint.SbtChainResolver$$anonfun$5.apply(SbtChainResolver.scala:102)
    at sbt.ivyint.SbtChainResolver$$anonfun$5.apply(SbtChainResolver.scala:100)
    at scala.Option.orElse(Option.scala:257)
    at sbt.ivyint.SbtChainResolver.doGetDependency(SbtChainResolver.scala:100)
    at sbt.ivyint.SbtChainResolver.getDependency(SbtChainResolver.scala:73)
    at sbt.ivyint.SbtChainResolver$$anonfun$6.apply(SbtChainResolver.scala:134)
    at sbt.ivyint.SbtChainResolver$$anonfun$6.apply(SbtChainResolver.scala:122)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at sbt.ivyint.SbtChainResolver.doGetDependency(SbtChainResolver.scala:122)
    at sbt.ivyint.SbtChainResolver.getDependency(SbtChainResolver.scala:73)
    at org.apache.ivy.core.resolve.IvyNode.loadData(IvyNode.java:169)
    at org.apache.ivy.core.resolve.VisitNode.loadData(VisitNode.java:292)
    at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:714)
    at org.apache.ivy.core.resolve.ResolveEngine.doFetchDependencies(ResolveEngine.java:799)
    at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:722)
    at org.apache.ivy.core.resolve.ResolveEngine.getDependencies(ResolveEngine.java:594)
    at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:234)
    at org.apache.ivy.Ivy.resolve(Ivy.java:517)
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:279)
```

The effect of this is that resolving the ivy data from the cache _always_ fails, hence every time an update is run, ivy must go out to the internet, making it impossible to build such a project with no internet connection.

On Play, as shown above, we see this issue in particular with `guice-assistedinject`.

**Comment by jroper** [comment] 2015-05-29 06:17
I think I've worked the problem out - `guice-assistedinject` is inheriting this property from its parent pom, `com.google.inject.extensions:extensions-parent`.  sbt is only adding the extra namespace to artifacts that it directly adds to the project itself, so when an artifact has a parent pom with this property, it gets the property, without getting the namespace.  That's possibly actually a bug in ivy, but I'm guessing we can work around it in sbt by always adding the namespace to every ivy xml file.

**Comment by dwijnand** [comment] 2015-05-29 06:51
Duplicate of #1856 for which there's an in-flight PR: #2012

**Closed as completed by dwijnand** 2015-05-29 06:51 UTC
