### ISSUE TITLE
The super shell does not play well with Giter8

### ISSUE THREAD

**Issue by agilesteel** [sbt/sbt#5145] opened 2019-10-02 17:12 UTC
## steps
sbt version: *1.3.2*

## problem
When using a Giter8 template with `sbt new scala/scala-seed.g8` (or any other template)

1. the template field **values** are not shown when typing even though they are applied
2. the lines are not broken between the entered template fields (note that the `scala-seed` template has only 1 template field so a bigger template is required to reproduce this one)

## expectation
`sbt new scala/scala-seed.g8` should behave the same as
`sbt --supershell=false new scala/scala-seed.g8`

## notes

1. The entered values are applied correctly so this is just a UX issue
2. `sbt --supershell=false new scala/scala-seed.g8` works exactly like it is supposed to so it is a perfect workaround

**Comment by eed3si9n** [comment] 2019-10-02 17:30
@agilesteel Thanks for the report! I think this is a duplicate of https://github.com/sbt/sbt/issues/5063.
Feel free to comment there to add more info.

**Closed as completed by eed3si9n** 2019-10-02 17:30 UTC
