### ISSUE TITLE
sbt constructs wrong path for specific / timestamped snapshot versions

### ISSUE THREAD

**Issue by martinburger** [sbt/sbt#1325] opened 2014-05-12 07:43 UTC
**Background**

I am developing a Play 2.2.3 application; the Play build system uses sbt.

I am using Sonatype Nexus OSS to manage various libraries built and deployed by Maven. At the moment, I am deploying _snapshot versions_ of those libraries.  For instance:

```
<groupId>myGroup</groupId>
<artifactId>myArtifact</artifactId>
<version>0.1-SNAPSHOT</version>
```

The Play application depends on snapshot versions of those libraries.

**Intention**

In the Play project, I want to use a _specific_ (thus, "timestamped") snapshot version of a dependency -- say `0.1-20140509.053703-1` -- instead of the latest one as specified by `0.1-SNAPSHOT`.

**Issue**

While the latter works perfectly well, sbt seems to be unable to resolve the specific version. At least sbt constructs the URL pointing to that specific version faultily: The name of the directory that contains the artifact ends with the actual timestamp instead of string `SNAPSHOT`.

**Example**

I created a new Play application and added the following dependency in file `build.sbt`: `libraryDependencies += "myGroup" % "myArtifact" % "0.1-20140509.053703-1"`

When resolving that dependency, sbt constructs URLs ending with `myGroup/myArtifact/0.1-20140509.053703-1/myArtifact-0.1-20140509.053703-1.pom`.

Note that the 3rd path component is `0.1-20140509.053703-1`. Thus, the directory containing artifact `myArtifact` incorrectly contains the timestamp as well.

The _correct_ directory name would be `0.1-SNAPSHOT`; thus, using `SNAPSHOT` instead of the actual timestamp. The complete correct URL would thus end with `myGroup/myArtifact/0.1-SNAPSHOT/myArtifact-0.1-20140509.053703-1.pom`.

Referring to the latest snapshot version instead by using dependency entry `libraryDependencies += "myGroup" % "myArtifact" % "0.1-SNAPSHOT"` works. The URLs end with `0.1-SNAPSHOT/myArtifact-0.1-SNAPSHOT.pom`.

**References**

I reported the above issue at [Stack Overfow](http://stackoverflow.com/q/23563675/66981). However, I haven't got any answer so far.

**Comment by cunei** [comment] 2014-05-15 00:16
The behavior that you describe is actually expected. The pom path, in case fixed versions are used, is built according to a fixed pattern, in which the version of the pom file and that of the directory are identical.
Snapshots are resolved differently; the fact that the repository manager (Artifactory, for instance) uses a collection of timestamped files is mostly an internal detail: a reference to -SNAPSHOT is automatically converted to the most recent timestamp, but the timestamped files cannot be accessed as regular versioned artifacts. At least, this is my understanding.
In any event, sbt correctly tries to access the artifact using the standard Maven access pattern, so this is not a bug, from what I can tell.

**Comment by martinburger** [comment] 2014-05-15 01:36
Well, I think using such "timestamped" (or, locked) snapshot versions is a common use case. There is even a plugin that simplifies the process of locking snapshots: http://mojo.codehaus.org/versions-maven-plugin/examples/lock-snapshots.html

**Comment by jsuereth** [comment] 2014-05-15 15:07
I believe this may be a duplicate of #1322.  Ivy itself never migrated to maven's new snapshot system, and so we're at the whims of what it can handle.

**Closed as completed by jsuereth** 2014-05-15 15:07 UTC

**Comment by martinburger** [comment] 2014-06-03 08:31
FYI - I created [IVY-1476](https://issues.apache.org/jira/browse/IVY-1476) as I was not able to find an existing Ivy issue that would handle this problem.

**Comment by raajay** [comment] 2017-06-26 01:37
@martinburger  I am having the same issue. Did you manage to find any workarounds?

**Comment by dfosticupgrade** [comment] 2018-02-09 15:57
same issue
did anybody figured it out without changing repository configuration?
