### ISSUE TITLE
1.4.0-RC1: Bash shell will not echo after running sbt script

### ISSUE THREAD

**Issue by esamson** [sbt/sbt#5882] opened 2020-09-22 08:56 UTC
## steps

1. Update `build.properties` to 1.4.0-RC1
2. Run `sbt compile`.
3. Once back at the shell prompt, run any other shell command, like `ls`.

## problem

* The shell will not echo characters typed at the shell prompt.
* The shell does accept the characters and will run the command.
* Hitting return will just repeat the prompt on the same line in the shell.

## expectation

Shell prompt unharmed.

## notes

Seems like #2963 is back. Running `stty echo` brings shell back to normal.

**Comment by raboof** [comment] 2020-09-22 09:15
I see this behaviour as well,  but this sounds like a duplicate of the already-closed report at #5827?

**Comment by eed3si9n** [comment] 2020-09-22 12:54
Yea. It's a duplicate of https://github.com/sbt/sbt/issues/5827 for 1.4.0-RC1. Stay tuned for RC2.

**Closed as completed by eed3si9n** 2020-09-22 12:54 UTC
