### ISSUE TITLE
SBT doesn't recompile code when referenced case class signature changes

### ISSUE THREAD

**Issue by mszygenda** [sbt/sbt#4316] opened 2018-08-10 15:08 UTC
## steps

- Define case class which has parameters with default values

**a.scala**

```scala
case class A(
  name: String,
  property1: String = ""
)
```

- Create instance of the class (separate file)

**main.scala**

```scala
object main {
	def main(args: Array[String]) {
		println(A("Using defaults"))
        }
}
```

- Run the application (sbt run). Sbt will compile both classes and everything will work fine.

- Now change class A to look like this:

```scala
case class A(
  name: String,
  property1: String = "",
  property2: String = ""
)
```

- Run the application (sbt run)

SBT output:
```
[info] Compiling 1 Scala source to /tmp/test/target/scala-2.12/classes ...

info] Running main 
[error] (run-main-0) java.lang.NoSuchMethodError: A.<init>(Ljava/lang/String;Ljava/lang/String;)V
[error] java.lang.NoSuchMethodError: A.<init>(Ljava/lang/String;Ljava/lang/String;)V
[error] 	at main$.main(main.scala:3)
[error] 	at main.main(main.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 2 s, completed Aug 10, 2018, 4:54:12 PM
```

## problem

Program crashes in runtime with NoSuchMethodError exception.

## expectation

SBT should recompile both sources (a.scala and main.scala) since case class signature changed (since default params are syntactic sugar only)

## notes

The problem seems to be that sbt recompiled just the "a.scala", while it also should recompile main.scala (since default params are just syntactic sugar - and signature  of the apply method changes)

sbt version: *1.2.1* (but I reproduced it with 1.1.4 as well)

**I created a script to reproduce the bug in the repo (reproduce.sh)**

https://github.com/mszygenda/sbt-case-class-recompilation-issue

**Comment by jvican** [comment] 2018-08-10 16:28
I'm aware of this error. It's solely due to the default arguments and I had a reproduction somewhere in my disk. I'll try to fix it in Zinc over the weekend.

**Comment by eed3si9n** [comment] 2018-08-10 21:07
@mszygenda Thanks for the detailed bug report with repro project!

I also feel like this has come up in a discussion before. If I remember correctly @smarter mentioned that Dotty includes the hash of default value into the API info.

**Comment by smarter** [comment] 2019-04-06 22:34
@jvican Should this issue be moved to the sbt/zinc repo ?

**Comment by smarter** [comment] 2019-04-06 22:37
I guess this should actually be closed since https://github.com/sbt/zinc/pull/572 was merged, though it seems this hasn't made it to any released version of sbt yet.

**Closed as completed** 2019-04-28 19:47 UTC
Labels: area/incremental_compiler
