### ISSUE TITLE
Spurious full-project recompilation after whitespace change

### ISSUE THREAD

**Issue by dragos** [sbt/sbt#642] opened 2013-01-16 10:54 UTC
After adding a space on [line 19 in this file](https://github.com/scala-ide/scala-ide/blob/master/org.scala-ide.sdt.core/src/scala/tools/eclipse/hyperlink/text/detector/BaseHyperlinkDetector.scala#L19) triggers a full recompilation of my project, in three steps.

I'm using a nightly Scala IDE for 2.10.0, with an Sbt build off 0.13, hash `935267b96b28bd0ae5c21c90923cb8ecf21c0b48`.

The (huge) log file is [here](https://gist.github.com/4546321).

**Comment by gkossakowski** [comment] 2013-01-16 17:52
@harrah FYI: I'm looking into that today.

**Comment by gkossakowski** [comment] 2013-01-17 08:16
@dragos: just to make sure, you are using Scala compiler from 2.10.x branch, right?

**Comment by dragos** [comment] 2013-01-17 12:59
Scala 2.10.0, **not** 2.10.1-SNAPSHOT.

**Comment by dragos** [comment] 2013-01-22 09:39
I built using the [api-diff branch](https://github.com/gkossakowski/xsbt/tree/api-diff) and the IDE with support for that is in [this branch](https://github.com/gkossakowski/scala-ide/commits/sbt-inc) + [my pull request](https://github.com/gkossakowski/scala-ide/pull/2).

Unfortunately, the API diff is not sensitive enough, the diff is empty (or just an empty new line): https://gist.github.com/4593263#file-gistfile1-txt-L67 In usual cases (like adding a public method), the diff does indeed pick it up and I see it in the logs.

To test it, just add a space in in [BaseHyperlinkDetector.scala](https://github.com/scala-ide/scala-ide/blob/master/org.scala-ide.sdt.core/src/scala/tools/eclipse/hyperlink/text/detector/BaseHyperlinkDetector.scala#L19), save, build.

**Comment by gkossakowski** [comment] 2013-01-23 00:21
@dragos: I managed to reproduce it using my custom build of sbt incremental compiler! Now it should be a lot easier to debug.

**Comment by gkossakowski** [comment] 2013-01-23 01:59
@dragos: I managed to [fix](https://github.com/gkossakowski/xsbt/commit/b09d986e199f67905ac61db07ba2abd5bf631c12) the `ShowAPI` so it gives you non-empty diff:

``` patch
013-01-22 17:46:45,722 DEBUG [Worker-29] - EclipseSbtBuildManager - Detected a change in a public API:
--- /Users/grek/scala/scala-ide/org.scala-ide.sdt.core/src/scala/tools/eclipse/hyperlink/text/detector/BaseHyperlinkDetector.scala
+++ /Users/grek/scala/scala-ide/org.scala-ide.sdt.core/src/scala/tools/eclipse/hyperlink/text/detector/BaseHyperlinkDetector.scala
@@ -27,11 +27,11 @@
 final def !=(x$1: java.lang.this#Object): scala.this#Boolean
 final def ##(): scala.this#Int
 final def synchronized[ java.lang.Object.T0 >: scala.this#Nothing <: scala.this#Any](x$1: <java.lang.Object.T0>): <java.lang.Object.T0>
 final def $isInstanceOf[ java.lang.Object.T0 >: scala.this#Nothing <: scala.this#Any](): scala.this#Boolean
 final def $asInstanceOf[ java.lang.Object.T0 >: scala.this#Nothing <: scala.this#Any](): <java.lang.Object.T0>
-@scala.this#throws[<scala.throws.T>]( = (classOf[java.lang.IllegalArgumentException])) @scala.this#throws[<scala.throws.T>]( = (classOf[java.lang.IllegalStateException])) final def setContext(x$1: org.eclipse.core.runtime.this#IAdaptable): scala.this#Unit
+@scala.this#throws( = (classOf[java.lang.IllegalArgumentException])) @scala.this#throws( = (classOf[java.lang.IllegalStateException])) final def setContext(x$1: org.eclipse.core.runtime.this#IAdaptable): scala.this#Unit
 def dispose(): scala.this#Unit
 protected[org.eclipse.jface.text.hyperlink] final def getAdapter(x$1: java.lang.this#Class[<java.lang.Class.?0>] forSome { type  java.lang.Class.?0 >: scala.this#Nothing <: scala.this#Any}): java.lang.this#Object
 protected abstract def runDetectionStrategy(scu: scala.tools.eclipse.this#InteractiveCompilationUnit, textEditor: org.eclipse.ui.texteditor.this#ITextEditor, currentSelection: org.eclipse.jface.text.this#IRegion): scala.collection.immutable.this#List[org.eclipse.jface.text.hyperlink.this#IHyperlink]
 def <init>(): scala.tools.eclipse.hyperlink.text.detector.this#BaseHyperlinkDetector
 override final def detectHyperlinks(viewer: org.eclipse.jface.text.this#ITextViewer, currentSelection: org.eclipse.jface.text.this#IRegion, canShowMultipleHyperlinks: scala.this#Boolean): scala.this#Array[org.eclipse.jface.text.hyperlink.this#IHyperlink]
```

That looks very promising! I'll try to minimize it and figure out why we lose those type parameters here.

**Comment by gkossakowski** [comment] 2013-01-23 07:11
@dragos: see https://issues.scala-lang.org/browse/SI-7010 and https://issues.scala-lang.org/browse/SI-7009

**Comment by dragos** [comment] 2013-01-23 15:27
Cool, means we need a 2.10.1 build when this is fixed? Thanks!

**Comment by gkossakowski** [comment] 2013-01-23 17:36
@dragos: I still need to dig more into this. I think there might be even more issues related to `@throws` but definitively I'll try to address this in 2.10.1 if possible.

**Comment by dragos** [comment] 2013-01-23 18:16
Excellent. We'll aim for 2.10.1 with our final release, so hopefully the fix will be in. I prefer this to an Sbt-side fix, so we can ship with the same version of Sbt as our last milestone.

**Comment by gkossakowski** [comment] 2013-01-24 01:23
@dragos: I tried to come up with a fix on sbt side but I don't see any way to do that. The problem is that sbt is merely reading an information from Scala and it's the compiler that was synthesizing broken `@throws` annotations that would have different types depending on initialization order. See my fix in scala/scala#1961 for details.

At the time sbt tries to extract information about annotations it's too late to force infos so we would get deterministic results for APIs. I could think of some really ugly, special case for `@throws` in sbt API extractor but this should be considered as last resort.

**Comment by dragos** [comment] 2013-01-24 10:46
@gkossakowski, thanks for the explanation. I was actually _happy_ the fix isn't on the Sbt side ;-)

I wonder though, shouldn't Sbt ignore annotations altogether? I can see some very special ones that could be white-listed, like `@BeanProperty` &co. But even that one might affect the outcome of the typer, so any extra getters are already part of the API. In the general case, annotations don't change the signature of a method.

**Comment by gkossakowski** [comment] 2013-01-24 22:02
@dragos the very `@throws` changes signature of a method (as seen from Java) so if you have mixed Java/Scala project you want to trigger recompilation on annotation change.
Moreover, we don't only care about bytecode level signatures but also about up-to-date type checking results of dependent source files. For example, if you add `@deprecated` annotation to your method, all source files that depend (e.g. call) that method should be recompiled so you get up-to-date deprecation warnings.

**Comment by harrah** [comment] 2013-01-25 15:09
Should this be closed as scalac-side only, then?

**Comment by gkossakowski** [comment] 2013-01-25 22:00
Yes. We should close it (I don't have right do that).

**Closed as completed** 2013-01-27 18:36 UTC
