### ISSUE TITLE
"Not a simple type" breaks -Xfatal-warnings

### ISSUE THREAD

**Issue by puffnfresh** [sbt/sbt#1475] opened 2014-07-29 23:07 UTC
When enabling `-Xfatal-warnings`:

```
scalacOptions += "-Xfatal-warnings"
```

Our build no longer works because of "Not a simple type" warnings, which actually come from sbt, rather than scalac:

```
[error] Not a simple type:
[error]     Type: scalaz.Unapply[scalaz.Bind,M[Option[com.simpleenergy.api.meter.RollupKey]]]{type M[X] = M[X]; type A = Option[com.simpleenergy.api.meter.RollupKey]} (class scala.reflect.internal.Types$RefinedType0)
[error]     Transformed: class xsbti.api.Structure
[error] Not a simple type:
[error]     Type: scalaz.Unapply[scalaz.Bind,M[List[com.simpleenergy.api.meter.service.TemporalUsageId]]]{type M[X] = M[X]; type A = List[com.simpleenergy.api.meter.service.TemporalUsageId]} (class scala.reflect.internal.Types$RefinedType0)
[error]     Transformed: class xsbti.api.Structure
[error] Not a simple type:
[error]     Type: scalaz.Unapply[scalaz.Bind,M[scala.collection.immutable.Set[com.simpleenergy.api.meter.RollupKey]]]{type M[X] = M[X]; type A = scala.collection.immutable.Set[com.simpleenergy.api.meter.RollupKey]} (class scala.reflect.internal.Types$RefinedType0)
[error]     Transformed: class xsbti.api.Structure
```

It would be very useful if sbt's warnings did not trigger fatal-warnings.

**Comment by jsuereth** [comment] 2014-07-29 23:15
@gkossakowski This looks like something with API extraction.

@puffnfresh any chance we can get a small reproducible test project?

**Comment by puffnfresh** [comment] 2014-07-30 01:02
build.sbt

``` scala
libraryDependencies += "org.scalaz" %% "scalaz-core" % "7.1.0-RC2"

scalacOptions += "-Xfatal-warnings"
```

src/main/scala/Example.scala

``` scala
import scalaz.Id.Id
import scalaz.Kleisli._

object T {
  val f = kleisliU { (_: Unit) =>
    (): Id[Unit]
  }
}
```

Gives:

```
[error] Not a simple type:
[error]     Type: scalaz.Unapply[scalaz.Bind,scalaz.Id.Id[Unit]]{type M[X] = scalaz.Id.Id[X]; type A = Unit} (class scala.reflect.internal.Types$RefinedType0)
[error]     Transformed: class xsbti.api.Structure
```

**Comment by gkossakowski** [comment] 2014-07-30 09:24
Duplicate of #830.

The unfortunate interaction with `-Xfatal-warnings` hasn't been reported before. I'll comment on that in the other issue.

**Closed as completed by gkossakowski** 2014-07-30 09:24 UTC
Labels: Duplicate, area/incremental_compiler
