### ISSUE TITLE
SSLHandshakeException when downloading dependencies

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [sbt/sbt#5520] opened 2020-04-30 06:56 UTC
## steps

SBT 1.3.10

build.sbt excerpt:

```scala
ThisBuild / scalaVersion     := "2.13.1"
ThisBuild / version          := "0.1.0-SNAPSHOT"
ThisBuild / organization     := "com.example"
ThisBuild / organizationName := "example"

lazy val root = (project in file("."))
  .settings(
    name := "sbt-5520",
    resolvers ++= Seq(
      ("geosolutions" at "http://maven.geo-solutions.it/").withAllowInsecureProtocol(true),
      "Osgeo Repo" at "https://nexus.osgeo.org/repository/Geoserver-releases/",
            ("geomajas" at "http://maven.geomajas.org")
    ),
    libraryDependencies ++= Seq(
      "org.geotools" % "gt-swing" % "21.0"
    )
  )
```

## problem

Dependencies aren't downloaded.
Here is the error shown, even after removing `~/.cache/coursier`:

```
download error: Caught javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching repo.osgeo.org found. (No subject alternative DNS name matching nexus.osgeo.org found.) while downloading 
```

If I change nexus.osgeo.org for repo.osgeo.org, the result is the same.

## expectation

All dependencies are downloaded like Maven does.

## notes

Example equivalent Maven POM file that works ok:
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mycompany.app</groupId>
  <artifactId>my-apl</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>Maven Quick Start Archetype</name>
  <url>http://maven.apache.org</url>
  <repositories>
    <repository>
      <id>geoserver</id>
      <name>geoserver</name>
      <url>https://nexus.osgeo.org/repository/Geoserver-releases/</url>
    </repository>
    <repository>
      <id>geo</id>
      <name>geo</name>
      <url>http://maven.geomajas.org/</url>
    </repository>  
  </repositories>
  <dependencies>
    <dependency>
      <groupId>org.geotools</groupId>
      <artifactId>gt-swing</artifactId>
      <version>21.0</version>
    </dependency>  
  </dependencies>
<build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.1.2</version>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <phase>package</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}/jars</outputDirectory>
              <overWriteReleases>true</overWriteReleases>
              <overWriteSnapshots>true</overWriteSnapshots>
              <overWriteIfNewer>true</overWriteIfNewer>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

Related bug for Ammonite, that also uses Coursier: https://github.com/coursier/coursier/issues/1692

**Comment by DavidPerezIngeniero** [comment] 2020-04-30 09:53
`"jgridshift" % "jgridshift" % "1.0"` from Maven repository http://maven.geomajas.org/, is a simpler case and exhibits the same bug.
Maven works ok, but SBT fails.

**Comment by eed3si9n** [comment] 2020-05-01 16:17
I cannot reproduce your SSLHandshakeException. Instead what I'm seeing is a checksum violation.

<details>

<summary>

```
[error] stack trace is suppressed; run last update for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading jgridshift:jgridshift:1.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/eed3si9n/.ivy2/local/jgridshift/jgridshift/1.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/jgridshift/jgridshift/1.0/jgridshift-1.0.pom
[error]   not found: http://maven.geo-solutions.it/jgridshift/jgridshift/1.0/jgridshift-1.0.pom
[error]   not found: https://nexus.osgeo.org/repository/Geoserver-releases/jgridshift/jgridshift/1.0/jgridshift-1.0.pom
[error]   wrong checksum: /Users/eed3si9n/.coursier/cache/v1/http/maven.geomajas.org/jgridshift/jgridshift/1.0/jgridshift-1.0.pom (expected SHA-1 b1368a983af519d0e6ecd8dcbfee651016501f0d in /Users/eed3si9n/.coursier/cache/v1/http/maven.geomajas.org/jgridshift/jgridshift/1.0/jgridshift-1.0.pom.sha1, got 88f8cf93af6666f7378131236f8227e48344fed2)
[error] Total time: 11 s, completed May 1, 2020 12:11:04 PM
```

</summary>

```scala
sbt:sbt-5520> update
[warn] insecure HTTP request is deprecated 'http://maven.geomajas.org'; switch to HTTPS or opt-in as ("geomajas" at "http://maven.geomajas.org").withAllowInsecureProtocol(true)
[warn] insecure HTTP request is deprecated 'http://maven.geomajas.org'; switch to HTTPS or opt-in as ("geomajas" at "http://maven.geomajas.org").withAllowInsecureProtocol(true)
[info] Updating
https://nexus.osgeo.org/repository/Geoserver-releases/org/geotools/gt-swing/21.0/gt-swing-21.0.pom
  100.0% [##########] 5.1 KiB (9.3 KiB / s)
....
[info] Resolved  dependencies
[warn]
[warn]  Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last update for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading jgridshift:jgridshift:1.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/eed3si9n/.ivy2/local/jgridshift/jgridshift/1.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/jgridshift/jgridshift/1.0/jgridshift-1.0.pom
[error]   not found: http://maven.geo-solutions.it/jgridshift/jgridshift/1.0/jgridshift-1.0.pom
[error]   not found: https://nexus.osgeo.org/repository/Geoserver-releases/jgridshift/jgridshift/1.0/jgridshift-1.0.pom
[error]   wrong checksum: /Users/eed3si9n/.coursier/cache/v1/http/maven.geomajas.org/jgridshift/jgridshift/1.0/jgridshift-1.0.pom (expected SHA-1 b1368a983af519d0e6ecd8dcbfee651016501f0d in /Users/eed3si9n/.coursier/cache/v1/http/maven.geomajas.org/jgridshift/jgridshift/1.0/jgridshift-1.0.pom.sha1, got 88f8cf93af6666f7378131236f8227e48344fed2)
[error] Total time: 11 s, completed May 1, 2020 12:11:04 PM
sbt:sbt-5520> last
[debug] > Exec(update, Some(2d0a4ec3-5777-42da-a40c-45b747226cc6), Some(CommandSource(console0)))
[debug] Evaluating tasks: checkBuildSources
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[debug] Evaluating tasks: update
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[warn] insecure HTTP request is deprecated 'http://maven.geomajas.org'; switch to HTTPS or opt-in as ("geomajas" at "http://maven.geomajas.org").withAllowInsecureProtocol(true)
[warn] insecure HTTP request is deprecated 'http://maven.geomajas.org'; switch to HTTPS or opt-in as ("geomajas" at "http://maven.geomajas.org").withAllowInsecureProtocol(true)
[info] Updating
[info] Resolved  dependencies
[warn]
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading jgridshift:jgridshift:1.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/eed3si9n/.ivy2/local/jgridshift/jgridshift/1.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/jgridshift/jgridshift/1.0/jgridshift-1.0.pom
[error]   not found: http://maven.geo-solutions.it/jgridshift/jgridshift/1.0/jgridshift-1.0.pom
[error]   not found: https://nexus.osgeo.org/repository/Geoserver-releases/jgridshift/jgridshift/1.0/jgridshift-1.0.pom
[error]   wrong checksum: /Users/eed3si9n/.coursier/cache/v1/http/maven.geomajas.org/jgridshift/jgridshift/1.0/jgridshift-1.0.pom (expected SHA-1 b1368a983af519d0e6ecd8dcbfee651016501f0d in /Users/eed3si9n/.coursier/cache/v1/http/maven.geomajas.org/jgridshift/jgridshift/1.0/jgridshift-1.0.pom.sha1, got 88f8cf93af6666f7378131236f8227e48344fed2)
[error]   at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:247)
[error]   at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:216)
[error]   at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]   at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:216)
[error]   at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]   at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error]   at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error]   at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]   at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error]   at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]   at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error]   at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error]   at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]   at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error]   at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
[error]   at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]   at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]   at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]   at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]   at sbt.Execute.work(Execute.scala:290)
[error]   at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]   at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading jgridshift:jgridshift:1.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/eed3si9n/.ivy2/local/jgridshift/jgridshift/1.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/jgridshift/jgridshift/1.0/jgridshift-1.0.pom
[error]   not found: http://maven.geo-solutions.it/jgridshift/jgridshift/1.0/jgridshift-1.0.pom
[error]   not found: https://nexus.osgeo.org/repository/Geoserver-releases/jgridshift/jgridshift/1.0/jgridshift-1.0.pom
[error]   wrong checksum: /Users/eed3si9n/.coursier/cache/v1/http/maven.geomajas.org/jgridshift/jgridshift/1.0/jgridshift-1.0.pom (expected SHA-1 b1368a983af519d0e6ecd8dcbfee651016501f0d in /Users/eed3si9n/.coursier/cache/v1/http/maven.geomajas.org/jgridshift/jgridshift/1.0/jgridshift-1.0.pom.sha1, got 88f8cf93af6666f7378131236f8227e48344fed2)
[error] Total time: 11 s, completed May 1, 2020 12:11:04 PM
[debug] > Exec(shell, None, None)
[debug] Evaluating tasks: checkBuildSources
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
```

</details>

If in fact the checksum is incorrect, I think Coursier is doing the right thing.

**Comment by eed3si9n** [comment] 2020-05-01 16:21
See also this workaround from 2012 - https://github.com/dwins/geoscript.scala/issues/19

**Comment by DavidPerezIngeniero** [comment] 2020-05-05 08:24
This is precisely the workaround I had used.
As Maven doesn't complain, the repository author doesn't know about the problem.

**Comment by eed3si9n** [comment] 2020-05-05 22:52
If you're sure that the artifacts are not hacked, then you can opt-out of the checksum currently as follows:

```scala
    csrConfiguration := csrConfiguration.value.withChecksums(Vector()),
```

**Comment by eed3si9n** [comment] 2020-05-29 17:23
I'm closing this since I think it's working as designed.

**Closed as completed by eed3si9n** 2020-05-29 17:23 UTC
Labels: area/library_management
