### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by eximius313** [sbt/sbt#3968] opened 2018-02-23 15:35 UTC
## steps
1) Upgrade to sbt 1.1.1
2) Run Play application

## problem
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/C:/Users/user/.sbt/boot/scala-2.12.4/org.scala-sbt/sbt/1.1.1/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

## expectation
no warning is being shown

## notes
sbt version: `1.1.1`

**Comment by dwijnand** [comment] 2018-02-23 16:10
Duplicate of sbt/zinc#459.

**Closed as completed by dwijnand** 2018-02-23 16:10 UTC
