### ISSUE TITLE
Exception when compiling Java sources with SBT 1.7.0

### ISSUE THREAD

**Issue by asflierl** [sbt/sbt#6969] opened 2022-07-11 08:39 UTC
## steps

- clone https://github.com/asflierl/java-compiler-fail.git
- run `sbt "clean;compile"`

## problem

```
> clean;compile
[info] compiling 150 Java sources to /home/asflierl/proj/java-compiler-fail/target/scala-2.13/classes ...
[error] ## Exception when compiling 150 sources to /home/asflierl/proj/java-compiler-fail/target/scala-2.13/classes
[error] java.lang.ArrayIndexOutOfBoundsException: Index 14939 out of bounds for length 61
[error] sbt.internal.inc.classfile.Parser$$anon$1.toUTF8(Parser.scala:91)
[error] sbt.internal.inc.classfile.Parser$$anon$1.parseAnnotation$1(Parser.scala:158)
[error] sbt.internal.inc.classfile.Parser$$anon$1.$anonfun$annotationsReferences$7(Parser.scala:165)
[error] scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
[error] sbt.internal.inc.classfile.Parser$$anon$1.$anonfun$annotationsReferences$4(Parser.scala:164)
[error] scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
[error] scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[error] scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[error] scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
[error] scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
[error] scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
[error] scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:198)
[error] sbt.internal.inc.classfile.Parser$$anon$1.annotationsReferences(Parser.scala:136)
[error] sbt.internal.inc.classfile.Parser$$anon$1.types(Parser.scala:119)
[error] sbt.internal.inc.classfile.JavaAnalyze$.$anonfun$apply$31(JavaAnalyze.scala:177)
[error] scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error] scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error] scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error] scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error] scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error] scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error] scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] sbt.internal.inc.classfile.JavaAnalyze$.$anonfun$apply$16(JavaAnalyze.scala:177)
[error] sbt.internal.inc.classfile.JavaAnalyze$.$anonfun$apply$16$adapted(JavaAnalyze.scala:108)
[error] scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
[error] scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
[error] scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
[error] scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
[error] scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
[error] scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
[error] scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
[error] sbt.internal.inc.classfile.JavaAnalyze$.apply(JavaAnalyze.scala:108)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$21(AnalyzingJavaCompiler.scala:215)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$21$adapted(AnalyzingJavaCompiler.scala:207)
[error] scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
[error] scala.collection.immutable.List.foreach(List.scala:431)
[error] scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$19(AnalyzingJavaCompiler.scala:207)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:262)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:207)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$2(MixedAnalyzingCompiler.scala:103)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$2$adapted(MixedAnalyzingCompiler.scala:91)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$1(MixedAnalyzingCompiler.scala:91)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileJava(MixedAnalyzingCompiler.scala:61)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileJava0$1(MixedAnalyzingCompiler.scala:198)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:179)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:177)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:463)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:418)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:405)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:171)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2364)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2314)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2312)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] java.base/java.lang.Thread.run(Thread.java:833)
[error]
[error] stack trace is suppressed; run last Compile / compileIncremental for the full output
[error] (Compile / compileIncremental) java.lang.ArrayIndexOutOfBoundsException: Index 14939 out of bounds for length 61
```

## expectation

Java sources are compiled without compiler exception.

## notes

I tried this with SBT 1.6.2 and SBT 1.7.0-RC2 and both worked. Only occurs with SBT 1.7.0.
I am using JDK 17.

**Comment by sjbahmani** [comment] 2022-07-11 12:19
somthing like that with this exception:

```
[error] ## Exception when compiling 282 sources to /home/me/sbt-proj/target/scala-2.13/classes
[error] java.lang.AssertionError: assumption failed: Constant pool entry is not a UTF8 type: 254
[error] scala.Predef$.assume(Predef.scala:256)
[error] sbt.internal.inc.classfile.Parser$$anon$1.toUTF8(Parser.scala:92)
[error] sbt.internal.inc.classfile.Parser$$anon$1.parseAnnotation$1(Parser.scala:158)
[error] sbt.internal.inc.classfile.Parser$$anon$1.$anonfun$annotationsReferences$7(Parser.scala:165)
[error] scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
[error] sbt.internal.inc.classfile.Parser$$anon$1.$anonfun$annotationsReferences$4(Parser.scala:164)
[error] scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
[error] scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[error] scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[error] scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
[error] scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
[error] scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
[error] scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:198)
[error] sbt.internal.inc.classfile.Parser$$anon$1.annotationsReferences(Parser.scala:136)
[error] sbt.internal.inc.classfile.Parser$$anon$1.types(Parser.scala:119)
[error] sbt.internal.inc.classfile.JavaAnalyze$.$anonfun$apply$31(JavaAnalyze.scala:177)
[error] scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error] scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error] scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error] scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error] scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error] scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error] scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] sbt.internal.inc.classfile.JavaAnalyze$.$anonfun$apply$16(JavaAnalyze.scala:177)
[error] sbt.internal.inc.classfile.JavaAnalyze$.$anonfun$apply$16$adapted(JavaAnalyze.scala:108)
[error] scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
[error] scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
[error] scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
[error] scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
[error] scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
[error] scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
[error] scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
[error] sbt.internal.inc.classfile.JavaAnalyze$.apply(JavaAnalyze.scala:108)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$21(AnalyzingJavaCompiler.scala:215)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$21$adapted(AnalyzingJavaCompiler.scala:207)
[error] scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
[error] scala.collection.immutable.List.foreach(List.scala:431)
[error] scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$19(AnalyzingJavaCompiler.scala:207)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:262)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:207)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$2(MixedAnalyzingCompiler.scala:103)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$2$adapted(MixedAnalyzingCompiler.scala:91)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$1(MixedAnalyzingCompiler.scala:91)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileJava(MixedAnalyzingCompiler.scala:61)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileJava0$1(MixedAnalyzingCompiler.scala:198)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:179)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:177)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:463)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:418)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:405)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:171)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2364)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2314)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2312)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] java.base/java.lang.Thread.run(Thread.java:833)
[error]            
[error] java.lang.AssertionError: assumption failed: Constant pool entry is not a UTF8 type: 254
[error] 	at scala.Predef$.assume(Predef.scala:256)
[error] 	at sbt.internal.inc.classfile.Parser$$anon$1.toUTF8(Parser.scala:92)
[error] 	at sbt.internal.inc.classfile.Parser$$anon$1.parseAnnotation$1(Parser.scala:158)
[error] 	at sbt.internal.inc.classfile.Parser$$anon$1.$anonfun$annotationsReferences$7(Parser.scala:165)
[error] 	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
[error] 	at sbt.internal.inc.classfile.Parser$$anon$1.$anonfun$annotationsReferences$4(Parser.scala:164)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
[error] 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[error] 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[error] 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
[error] 	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:198)
[error] 	at sbt.internal.inc.classfile.Parser$$anon$1.annotationsReferences(Parser.scala:136)
[error] 	at sbt.internal.inc.classfile.Parser$$anon$1.types(Parser.scala:119)
[error] 	at sbt.internal.inc.classfile.JavaAnalyze$.$anonfun$apply$31(JavaAnalyze.scala:177)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.internal.inc.classfile.JavaAnalyze$.$anonfun$apply$16(JavaAnalyze.scala:177)
[error] 	at sbt.internal.inc.classfile.JavaAnalyze$.$anonfun$apply$16$adapted(JavaAnalyze.scala:108)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
[error] 	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
[error] 	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
[error] 	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
[error] 	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
[error] 	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
[error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
[error] 	at sbt.internal.inc.classfile.JavaAnalyze$.apply(JavaAnalyze.scala:108)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$21(AnalyzingJavaCompiler.scala:215)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$21$adapted(AnalyzingJavaCompiler.scala:207)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$19(AnalyzingJavaCompiler.scala:207)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:262)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:207)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$2(MixedAnalyzingCompiler.scala:103)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$2$adapted(MixedAnalyzingCompiler.scala:91)
[error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$1(MixedAnalyzingCompiler.scala:91)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileJava(MixedAnalyzingCompiler.scala:61)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileJava0$1(MixedAnalyzingCompiler.scala:198)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:179)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:177)
[error] 	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:463)
[error] 	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] 	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] 	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:418)
[error] 	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
[error] 	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:405)
[error] 	at sbt.internal.inc.Incremental$.apply(Incremental.scala:171)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2364)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2314)
[error] 	at sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] 	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2312)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (Compile / compileIncremental) java.lang.AssertionError: assumption failed: Constant pool entry is not a UTF8 type: 254

```

work properly with 1.6.2 and 1.7.0-RC2

**Comment by eed3si9n** [comment] 2022-07-11 13:14
@asflierl Thanks for the report!

**Comment by mkurz** [comment] 2022-07-11 13:33
Can't compile Play with sbt 1.7 as well: https://github.com/playframework/playframework/pull/11349

https://github.com/playframework/playframework/runs/7281244256?check_suite_focus=true#step:9:5395:
```
java.lang.AssertionError: assumption failed: Constant pool entry is not a UTF8 type: 13
````

**Comment by SethTisue** [comment] 2022-07-11 13:48
thanks @asflierl, @mkurz, and @sbahmani for the reports

Looks like a regression due to my Java annotation processing changes in zinc (https://github.com/sbt/zinc/pull/1079) that I'll need to address promptly — and we'll need zinc 1.7.1 and sbt 1.7.1 releases.

The Scala 2 community build actually caught this last night: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3800/artifact/logs/playframework-build.log

But since the zinc change was merged after sbt 1.7.0-RC2, it wasn't caught in time.

**Comment by eed3si9n** [comment] 2022-07-11 13:53
> But since the zinc change was merged after sbt 1.7.0-RC2, it wasn't caught in time.

Sorry, I was impatient here. I should've cut another RC.

**Comment by SethTisue** [comment] 2022-07-11 13:55
No worries... at least the problem manifests at build time and with a nicely searchable message/stacktrace 🤷

**Comment by asflierl** [comment] 2022-07-11 16:45
also 1.7.0-RC2 exists as a good fallback with almost all of the features :)

**Comment by SethTisue** [comment] 2022-07-11 22:40
Andreas's example minimizes to:

```scala
libraryDependencies += "javax.xml.bind" % "jaxb-api" % "2.3.1"
```

```java
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
class Diagram {
    @XmlAttribute(name = "id")
    @XmlID String id;
}
```

(though the minimization gives `EOFException` instead of `ArrayIndexOutOfBoundsException`)

note that the annotations in question are in Java 8 stdlib, but moved out as of 11

**Comment by SethTisue** [comment] 2022-07-11 23:03
minimization without external dependencies:

```java
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
@Retention(RetentionPolicy.RUNTIME)
public @interface Annotation1 {
  String name();
}
```

```java
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
@Retention(RetentionPolicy.RUNTIME)
public @interface Annotation2 { }
```

```java
class Diagram {
    @Annotation1(name = "id")
    @Annotation2 String id;
}
```

**Comment by SethTisue** [comment] 2022-07-12 01:44
PR sbt/zinc#1111

**Comment by eed3si9n** [comment] 2022-07-12 02:52
I published Zinc 1.7.1, and locally confirmed that it fixes the java-compiler-fail repro project.

**Closed as completed** 2022-07-12 03:17 UTC
Labels: Regression

**Comment by asflierl** [comment] 2022-07-12 05:50
Thank you for the quick fix.

**Comment by mkurz** [comment] 2022-07-12 07:02
Thanks!
