### ISSUE TITLE
Incremental compilation inside docker container broken since SBT 1.1.0

### ISSUE THREAD

**Issue by doczir** [sbt/sbt#4168] opened 2018-05-18 22:07 UTC
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps

1. Create a new scala project with `sbt new scala/scala-seed.g8` (make sure SBT version is at least 1.1.0)
2. Add a Dockerfile to the root of the generated project with the following content
```
FROM hseeberger/scala-sbt:8u171_2.12.6_1.1.5

WORKDIR /sbt-bug

ADD build.sbt /sbt-bug/build.sbt
ADD src /sbt-bug/src
ADD project/build.properties /sbt-bug/project/build.properties
ADD project/Dependencies.scala /sbt-bug/project/Dependencies.scala

RUN sbt compile test:compile
```
3. Run `docker build -t sbtbug .` inside the project directory
4. Run `docker run -i -t sbtbug sbt test` to enter the container

## problem
Running the tests recompiles everything because SBT invalidates the class files in the target folder, which were compiled during the build of the docker image.

## expectation
SBT should use the class files in the target directory to run the tests and it should not recompile everything

## notes

SBT version: >= 1.1.0

This happens since version 1.1.0. With 1.0.4 and below it works as expected. While debugging the issue I observed that putting compile and test both in the Dockerfile, as two `RUN` commands, also reproduces the issue. This leads me to believe that this issue is caused by some strange interaction between SBT and the layered file system in docker.

**Comment by varunkvv** [comment] 2018-06-28 18:11
I just want to add, I was able to reproduce through compression / decompression. Don't need containers.

On my project (let's call it `scala-project`):

1. compile scala-project. then compile again - it will use incremental compilation, and no recompilation is actually going to happen
2. compress it (on macos 10.13.5 zip functionality if that matterrs)
3. delete the original scala-project folder
4. decompress it into the scala-project folder - preserving the name and absolute path
5. run compile. expected - it should use the already compiled classes, and not compile from scratch. actual - it compiles from scratch.

This happens on 1.1.6, but when I used sbt 1.0.4 - the incremental compilation worked as expected.

**Comment by espenhw** [comment] 2018-08-31 12:57
I've run into the same issue; turns out that something Docker does to the container filesystem (probably compression, that would make sense) truncates file mtimes to second resolution (instead of millisecond).  If you're on Java 8 passing `-Dsbt.io.jdktimestamps=true` to SBT is a workaround, but that won't work for JDK 10 at least.

**Comment by espenhw** [comment] 2018-08-31 13:07
As a workaround on newer JDKs, you can do something like this:
```
  Seq(Compile, Test).map { c =>
    def needsTimestampTruncation: Boolean = somehowDetectDocker

    (c / previousCompile) := {
      val realPreviousResult = (c / previousCompile).value
      if (!needsTimestampTruncation) {
        realPreviousResult
      } else {
        import java.util.concurrent.TimeUnit._
        import sbt.internal.inc.{Analysis, LastModified, Stamps}
        import scala.collection.JavaConverters._
        import xsbti.compile.CompileAnalysis
        import xsbti.compile.analysis._

        def truncateMtime(s: Stamp): Stamp = s match {
          case mtime: LastModified =>
            val truncated = SECONDS.toMillis(MILLISECONDS.toSeconds(mtime.value))
            new LastModified(truncated)
          case other => other
        }

        def truncate(stamps: Stamps): Stamps = {
          Stamps(
            stamps.getAllProductStamps.asScala.toMap.mapValues(truncateMtime),
            stamps.getAllSourceStamps.asScala.toMap.mapValues(truncateMtime),
            stamps.getAllBinaryStamps.asScala.toMap.mapValues(truncateMtime)
          )
        }

        realPreviousResult.withAnalysis(realPreviousResult.analysis().asScala.map { case a: Analysis =>
          a.copy(stamps = truncate(a.stamps)): CompileAnalysis
        }.asJava)
      }
    }
  }
```

For a suitable definition of `somehowDetectDocker` (we use a special system property set by the thing that triggers the build)

**Comment by jvican** [comment] 2018-08-31 13:10
Good catch @espenhw. Note that what you're doing should not be done by default to all the stamps, as different incremental compilations that happen on the same second would not recompile incrementally correctly.

**Comment by espenhw** [comment] 2018-08-31 13:37
Indeed; there's also a weird interaction where invoking `sbt test:compile package` in the Dockerfile ends up compiling the production code twice, so the workaround is not perfect! (As a workaround for the bug in the workaround, we invoke `test:compile` and `package` on separate RUN lines.)

**Comment by pulasthibandara** [comment] 2019-01-10 23:04
Was struggling with this for few days. Here's a related Stackoverflow Q/A
https://stackoverflow.com/questions/54068316/how-to-re-use-compiled-sources-in-different-machines/54138157#54138157

**Comment by eed3si9n** [comment] 2019-02-17 20:31
We added millisecond-precision in https://github.com/sbt/io/pull/92 because we have observed incremental compilation issues under testing environment where changes are made in quick succession.

If Docker and/or ZIP file is losing precision, we might want to allow users to somehow round off the timestamp as @espenhw has done.  

## ZIP

From [Wikipedia](https://en.wikipedia.org/wiki/Zip_(file_format)#Structure)

> The FAT filesystem of DOS has a timestamp resolution of only two seconds; ZIP file records mimic this. As a result, the built-in timestamp resolution of files in a ZIP archive is only two seconds, though extra fields can be used to store more precise timestamps.


/cc @cunei @eatkins

**Comment by nafg** [comment] 2019-02-22 19:12
I believe the docker issue is https://github.com/osxfuse/osxfuse/issues/346

**Comment by eed3si9n** [comment] 2019-02-22 19:44
[Docker Desktop for Mac: File system sharing (osxfs)](https://docs.docker.com/docker-for-mac/osxfs/) says:

> `osxfs` does not use OSXFUSE. `osxfs` does not run under, inside, or between macOS userspace processes and the macOS kernel.

**Comment by edrevo** [comment] 2019-03-29 11:59
@eed3si9n, I see there's a `help wanted` tag in this issue, but there's no clear course of action on how to solve this.

Would a PR to https://github.com/sbt/io/ that forces second-level resolution when in Docker be the correct solution?

**Comment by eed3si9n** [comment] 2019-05-02 15:51
@edrevo I think doing some research to find out the root cause would be helpful.
Also providing options via sbt setting or JVM property to force second-level resolution might be a good workaround if in fact we have regressed in sbt 1.1.0.

**Comment by Daenyth** [comment] 2019-07-05 17:44
Could this be a cause of recompiles on circleci? https://discuss.circleci.com/t/sbt-recompiles-everything-between-workflow-steps/29162/5

**Comment by varunkvv** [comment] 2019-07-05 19:49
@Daenyth - yep - this is the cause of the recompilation on circle on versions 1.1.0 and above. At least this is what I'm seeing on my builds. And for some reason, the workaround mentioned here (https://github.com/sbt/sbt/issues/4168#issuecomment-417655678) did not work reliably for me on circle. For a while, we used the older sbt version on circle (1.0.4), and newer ones on our dev env as another workaround.

**Comment by Daenyth** [comment] 2019-07-08 14:09
I can confirm that the workaround also doesn't work for me on circle

**Comment by wuservices** [comment] 2019-09-10 18:51
Just to share another use case, I have a similar issue with millisecond resolution timestamps, but the issue is mainly that I'm shipping compiled artifacts between build agents (in my case, with TeamCity, but the problem is generic). Since tar files only have second resolution, the same issue happens.

@espenhw thanks for the workaround! For some reason I couldn't get `Dsbt.io.jdktimestamps=true` to work even on JDK 8, but your code-based workaround is great. I've been struggling to figure out the syntax and best way to reuse this across projects in my proper / main multi-project build as well as my meta build.

My issues are probably just due to my unfamiliarity with sbt biting me, but any tips would be really helpful! I could post on SO, but this might be helpful to others coming across this too.

**Issue with multi-project build**
What's the best way to reuse the code across projects? I came up something that seems decent by moving the code to `project/Utils.scala`, but it can't share code with the meta build (see below). I wasn't sure if I could define this more succinctly too.

In `build.sbt`:
```
import Utils._
lazy val commonSettings = Seq(
  // Can I do these both at once?
  previousCompile in Compile ~= previousCompileWithTruncatedTimestamps,
  previousCompile in Test ~= previousCompileWithTruncatedTimestamps
)
```

**Issue with reuse in meta build**
I have `project/Dependencies.scala`, so it seems like I need to define this config within `project/build.sbt` for `project/*.scala` files to use the second-precision. However, then I have the same code within the main `build.sbt`. I could extract the code into `project/Utils.scala`, but then I can't use it from `project/build.sbt` I think, and if I move it into a deeper `project/project/Utils.scala`, then I think that file wouldn't be using the rules...

**Comment by AndriusFromLTU** [comment] 2019-12-20 11:21
The workaround doesn't work on Bitbucket Pipelines as well :(

**Comment by arashi01** [comment] 2019-12-20 12:48
Using sbt-aether-deploy plugin works as a workaround on BitBucket

**Comment by AndriusFromLTU** [comment] 2019-12-22 14:18
After downgrading sbt to 1.0.4 and doing some custom file management I managed to make it work. 
If anyone interested, a working prototype is here: https://bitbucket.org/myDisconnect/sbt-ci-test/.
Thank you for the suggestion @varunkvv  :)

**Comment by matil019** [comment] 2020-02-08 05:07
Another quick, shell-based workaround is to manually tar with the POSIX format (`-H posix`), which stores timestamps in nanoseconds:

```Dockerfile
RUN sbt compile && \
    find -name target -exec tar -zcf targets.tar.gz -H posix {} + && \
    find -name target -exec rm -r {} +
RUN tar -xf targets.tar.gz && \
    sbt compile # <- no recompilation!
```

It seems to work well with Dockerfile, and though I haven't tested, in theory it should also work with "list of commands" in yaml configuration files.

**Comment by yhpark** [comment] 2020-03-20 08:25
If you like @matil019 's workaround and have lots of leaf dockerfiles with few base images, I wrote a simple sbt wrapper which you can replace sbt with in the base image. Assuming there's a `sbt compile` step in most of the leaf dockerfiles (okay if there isn't), we can compress the target files on `sbt compile` and decompress the gzip file on other steps. This way we can contain the workaround code within the base image without polluting other dockerfiles.

```sh
#!/bin/bash
# workaround for https://github.com/sbt/sbt/issues/4168
# `sbt-org` being the original sbt binary

if [[ "$1" == "compile" ]]; then
    echo "[sbt cache invalidation fix] will compress the compiled target dirs into targets.tar.gz"
    sbt-org "$@" && \
    find -name target -exec tar -zcf targets.tar.gz -H posix {} + && \
    find -name target -exec rm -r {} +
else
  tar -xf targets.tar.gz 2>/dev/null && \
    echo "[sbt cache invalidation fix] found and unpacked targets.tar.gz"
  sbt-org "$@"
fi
```

image build example:
 
```
> sbt compile (docker step)
[sbt cache invalidation fix] will compress the compiled target dirs into targets.tar.gz
[info] Loading project definition from /app/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to testt (in build file:/app/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Compiling 1 Scala source to /app/target/scala-2.13/classes ...
[success] Total time: 4 s, completed Mar 20, 2020 7:18:52 AM
> sbt test (docker step)
[sbt cache invalidation fix] found and unpacked targets.tar.gz
[info] Loading project definition from /app/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to testt (in build file:/app/)
[info] Compiling 1 Scala source to /app/target/scala-2.13/test-classes ...
[info] HelloSpec:
[info] The Hello object
[info] - should say hello
[info] Run completed in 434 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 6 s, completed Mar 20, 2020 7:19:10 AM
```

**Comment by neilchaudhuri** [comment] 2020-03-29 20:20
@yhpark If it isn't sensitive or too much trouble, could you publish your Dockerfile?

**Comment by eed3si9n** [comment] 2020-10-21 16:34
This should be fixed now since I've switched to using time-wrapped content hashing in https://github.com/sbt/zinc/pull/712 and https://github.com/sbt/sbt/pull/5417.

**Closed as completed by eed3si9n** 2020-10-21 16:34 UTC
Labels: area/incremental_compiler, help wanted

**Comment by yanns** [comment] 2021-12-20 11:05
Some updates:
when I run `sbt Test/compile` several times for example with cache saving / restore in between, the incremental compilation runs well.

But if I run `sbt Docker/stage` after a cache restore, then all classes are compiled again.
The next `sbt Docker/stage` after a cache restore triggers the whole compilation again.

Something to check on https://www.scala-sbt.org/sbt-native-packager/?

**Comment by yanns** [comment] 2022-02-07 21:28
Update as I found the root cause, and it might be useful for others.
I run `sbt -Dfatal-warnings=true Test/compile`, where `fatal-warnings` is used to tell scalac to treat warnings as errors.
After that, `sbt Test/compile` will compile everything again, as the flags are different.
So I "just" have to make sure that the sbt is being launched with the same parameters on all steps.
