### ISSUE TITLE
Build errors get "stuck" in Metals  (SBT 1.7.0-M2 as BSP server)

### ISSUE THREAD

**Issue by asflierl** [sbt/sbt#6896] opened 2022-05-13 16:40 UTC
continuing from my comments on #6847 @tanishiking 

## steps

1. clone https://github.com/asflierl/sbt-bsp-errors-minimal-repro.git
2. in the project root directory, start VSCode (e.g. `code .`) [assuming here that VSCode has the Metals plug-in version 0.11.5 installed]
3. after Metals starts, it will ask to import the project. select "not now"
4. perform the "Metals: switch build server" action and select "SBT" (this will generate `project/metals.sbt` etc. and start SBT in the background)
5. wait until everything downloads and compiles
6. introduce a small compilation error in `src/main/scala/Main.scala`, e.g. type "asd" as the last line
7. the compilation error shows up correctly in the problems view
8. undo the change you made in 6.

## problem

even after everything compiles fine again, the compilation error is still there in the problems view and will not disappear until another error is introduced somewhere else (which then in turn gets "stuck" in the problems view)

## expectation

the compile error should disappear after everything compiles fine again

## notes
I've also tried this with Scala 2.13.8 and the same thing happens.
When I switch back to SBT 1.6.2, everything works as expected.
In case it makes a difference, I ran all this with JDK 17.

**Comment by tgodzik** [comment] 2022-05-27 08:17
Looks like maybe sbt is not sending a successful compilation message to metals :thinking:

**Comment by tanishiking** [comment] 2022-05-27 09:29
@asflierl Thank you for reporting! I could reproduce the problem.
I'll investigate the root cause, but if I couldn't before the next release, it would be better to revert my change 👍

**Comment by eed3si9n** [comment] 2022-06-26 18:32
Fixed by @kpodsiad in https://github.com/sbt/sbt/pull/6929

**Closed as completed by eed3si9n** 2022-06-26 18:32 UTC

**Comment by asflierl** [comment] 2022-06-27 09:52
Thank you so much @kpodsiad for fixing this and @tanishiking for implementing it in the first place! This is improving my day-to-day development experience a lot.
