### ISSUE TITLE
[1.3.0-RC5] "scripted" task tab completion throws ArithmeticException

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#5013] opened 2019-08-31 08:29 UTC
## steps

sbt version: 1.3.0-RC5

`build.sbt`

```scala
val foo = project.enablePlugins(SbtPlugin)
```

`project/build.properties`

```
sbt.version=1.3.0-RC5
```

`foo/src/sbt-test/x/y/test`

```
> compile
```

`scripted x/<TAB KEY>` in sbt shell

## problem

```
 > scripted x/java.lang.ArithmeticException: / by zero
	at sbt.ScriptedPlugin$.pagedFilenames$1(ScriptedPlugin.scala:146)
	at sbt.ScriptedPlugin$.$anonfun$scriptedParser$10(ScriptedPlugin.scala:161)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at sbt.internal.util.complete.Parser$Value.map(Parser.scala:167)
	at sbt.internal.util.complete.MapParser.resultEmpty$lzycompute(Parser.scala:766)
	at sbt.internal.util.complete.MapParser.resultEmpty(Parser.scala:766)
	at sbt.internal.util.complete.HomParser.resultEmpty$lzycompute(Parser.scala:704)
	at sbt.internal.util.complete.HomParser.resultEmpty(Parser.scala:704)
	at sbt.internal.util.complete.MapParser.resultEmpty$lzycompute(Parser.scala:766)
	at sbt.internal.util.complete.MapParser.resultEmpty(Parser.scala:766)
	at sbt.internal.util.complete.Repeat.resultEmpty$lzycompute(Parser.scala:970)
	at sbt.internal.util.complete.Repeat.resultEmpty(Parser.scala:966)
	at sbt.internal.util.complete.MapParser.resultEmpty$lzycompute(Parser.scala:766)
	at sbt.internal.util.complete.MapParser.resultEmpty(Parser.scala:766)
	at sbt.internal.util.complete.ParserSeq.$anonfun$resultEmpty$6(Parser.scala:722)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.immutable.List.map(List.scala:298)
	at sbt.internal.util.complete.ParserSeq.resultEmpty$lzycompute(Parser.scala:722)
	at sbt.internal.util.complete.ParserSeq.resultEmpty(Parser.scala:721)
	at sbt.internal.util.complete.MapParser.resultEmpty$lzycompute(Parser.scala:766)
	at sbt.internal.util.complete.MapParser.resultEmpty(Parser.scala:766)
	at sbt.internal.util.complete.MatchedString.resultEmpty(Parser.scala:796)
	at sbt.internal.util.complete.And.resultEmpty$lzycompute(Parser.scala:824)
	at sbt.internal.util.complete.And.resultEmpty(Parser.scala:824)
	at sbt.internal.util.complete.HomParser.resultEmpty$lzycompute(Parser.scala:704)
	at sbt.internal.util.complete.HomParser.resultEmpty(Parser.scala:704)
	at sbt.internal.util.complete.MapParser.resultEmpty$lzycompute(Parser.scala:766)
	at sbt.internal.util.complete.MapParser.resultEmpty(Parser.scala:766)
	at sbt.internal.util.complete.And.resultEmpty$lzycompute(Parser.scala:824)
	at sbt.internal.util.complete.And.resultEmpty(Parser.scala:824)
	at sbt.internal.util.complete.SeqParser.resultEmpty$lzycompute(Parser.scala:687)
	at sbt.internal.util.complete.SeqParser.resultEmpty(Parser.scala:687)
	at sbt.internal.util.complete.BindParser.$anonfun$completions$3(Parser.scala:745)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$2(Completions.scala:28)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:244)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:321)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:244)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$1(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:42)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:42)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:20)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:42)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:42)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$1(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:42)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:42)
	at sbt.internal.util.complete.JLineCompletion$.convertCompletions(JLineCompletion.scala:75)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$parserAsCompletor$1(JLineCompletion.scala:72)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$parserAsCompletor$1$adapted(JLineCompletion.scala:72)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$customCompletor$2(JLineCompletion.scala:101)
	at sbt.internal.util.complete.JLineCompletion$.complete(JLineCompletion.scala:122)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$customCompletor$1(JLineCompletion.scala:101)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$customCompletor$1$adapted(JLineCompletion.scala:100)
	at sbt.internal.util.complete.JLineCompletion$CustomHandler.complete(JLineCompletion.scala:47)
	at jline.console.ConsoleReader.complete(ConsoleReader.java:3317)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2653)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
	at sbt.internal.util.JLine.readLineDirectRaw(LineReader.scala:65)
	at sbt.internal.util.JLine.$anonfun$readLineDirect$2(LineReader.scala:56)
	at sbt.internal.util.Signals0.withHandler(Signal.scala:89)
	at sbt.internal.util.Signals$.withHandler(Signal.scala:18)
	at sbt.internal.util.JLine.readLineDirect(LineReader.scala:56)
	at sbt.internal.util.JLine.readLineWithHistory(LineReader.scala:48)
	at sbt.internal.util.JLine.unsynchronizedReadLine(LineReader.scala:41)
	at sbt.internal.util.JLine.$anonfun$readLine$1(LineReader.scala:32)
	at sbt.internal.util.JLine$.$anonfun$withJLine$1(LineReader.scala:163)
	at sbt.internal.util.JLine$.withTerminal(LineReader.scala:128)
	at sbt.internal.util.JLine$.withJLine(LineReader.scala:160)
	at sbt.internal.util.JLine.readLine(LineReader.scala:32)
	at sbt.internal.ConsoleChannel$$anon$1.run(ConsoleChannel.scala:28)

Exception occurred while determining completions.
```

![scripted-ArithmeticException](https://user-images.githubusercontent.com/389787/64061342-740e0980-cc14-11e9-89be-4b7c5739a069.gif)

## expectation

Don't throw Exception

## notes

https://github.com/sbt/sbt/blob/v1.3.0-RC5/main/src/main/scala/sbt/ScriptedPlugin.scala#L146

**Comment by eed3si9n** [comment] 2019-08-31 18:52
@xuwei-k Does it happen with 1.2.8? If so we can move it to 1.3.1.

**Comment by xuwei-k** [comment] 2019-08-31 22:55
Does not happen with sbt 1.2.8 😢

**Comment by eatkins** [comment] 2019-08-31 23:43
The issue is sort of present in 1.2.8, but not with completions:
```
sbt:sbt-source-format> scripted sbt-source-format/*0of0
[error] java.lang.ArithmeticException: / by zero
[error]         at sbt.ScriptedPlugin$.pagedFilenames$1(ScriptedPlugin.scala:143)
[error]         at sbt.ScriptedPlugin$.$anonfun$scriptedParser$10(ScriptedPlugin.scala:158)
[error]         at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
[error]         at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
[error]         at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
[error]         at sbt.internal.util.complete.Parser$Value.map(Parser.scala:167)
[error]         at sbt.internal.util.complete.MapParser.resultEmpty$lzycompute(Parser.scala:754)
[error]         at sbt.internal.util.complete.MapParser.resultEmpty(Parser.scala:754)
[error]         at sbt.internal.util.complete.HomParser.resultEmpty$lzycompute(Parser.scala:692)
[error]         at sbt.internal.util.complete.HomParser.resultEmpty(Parser.scala:692)
[error]         at sbt.internal.util.complete.MapParser.resultEmpty$lzycompute(Parser.scala:754)
[error]         at sbt.internal.util.complete.MapParser.resultEmpty(Parser.scala:754)
[error]         at sbt.internal.util.complete.Repeat.resultEmpty$lzycompute(Parser.scala:958)
[error]         at sbt.internal.util.complete.Repeat.resultEmpty(Parser.scala:954)
[error]         at sbt.internal.util.complete.MapParser.resultEmpty$lzycompute(Parser.scala:754)
[error]         at sbt.internal.util.complete.MapParser.resultEmpty(Parser.scala:754)
[error]         at sbt.internal.util.complete.ParserSeq.$anonfun$resultEmpty$6(Parser.scala:710)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
[error]         at scala.collection.immutable.List.foreach(List.scala:388)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:233)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
[error]         at scala.collection.immutable.List.map(List.scala:294)
[error]         at sbt.internal.util.complete.ParserSeq.resultEmpty$lzycompute(Parser.scala:710)
[error]         at sbt.internal.util.complete.ParserSeq.resultEmpty(Parser.scala:709)
[error]         at sbt.internal.util.complete.MapParser.resultEmpty$lzycompute(Parser.scala:754)
[error]         at sbt.internal.util.complete.MapParser.resultEmpty(Parser.scala:754)
[error]         at sbt.internal.util.complete.ParserMain.loop$1(Parser.scala:478)
[error]         at sbt.internal.util.complete.ParserMain.result(Parser.scala:485)
[error]         at sbt.internal.util.complete.ParserMain.result$(Parser.scala:471)
[error]         at sbt.internal.util.complete.Parser$.result(Parser.scala:138)
[error]         at sbt.internal.util.complete.ParserMain.parse(Parser.scala:434)
[error]         at sbt.internal.util.complete.ParserMain.parse$(Parser.scala:433)
[error]         at sbt.internal.util.complete.DefaultParsers$.parse(Parsers.scala:312)
[error]         at sbt.Command$.process(Command.scala:180)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error]         at sbt.State$$anon$1.process(State.scala:250)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:139)
[error]         at sbt.MainLoop$.run(MainLoop.scala:132)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error]         at sbt.StandardMain$.runManaged(Main.scala:138)
[error]         at sbt.xMain.run(Main.scala:89)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error]         at xsbt.boot.Boot$.main(Boot.scala:18)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.ArithmeticException: / by zero
[error] Use 'last' for the full log.
```

**Comment by eatkins** [comment] 2019-09-01 00:23
Both #5014 and #5015 independently fix this issue.

**Comment by eed3si9n** [comment] 2019-09-04 03:56
Fixed in https://github.com/sbt/sbt/pull/5014

**Closed as completed by eed3si9n** 2019-09-04 03:56 UTC
