### ISSUE TITLE
Doesn't create src/[main | test]/scala directories

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#112] opened 2011-07-19 23:12 UTC
I thought that running 'sbt' with no arguments would create these directories by default. Is this a bug or a feature request?

Thanks!

**Comment by harrah** [comment] 2011-07-20 00:45
Duplicate of #56.

**Comment by ghost** [comment] 2011-07-20 00:46
My bad, Thanks!

**Closed as completed by harrah** 2011-07-20 00:45 UTC
Labels: Duplicate
