### ISSUE TITLE
Regression: Saving a file while compiling does not trigger recompile

### ISSUE THREAD

**Issue by fdietze** [sbt/sbt#4888] opened 2019-07-20 18:25 UTC
## steps
sbt version: *1.3.0-RC3*

## problem
Using `~compile`, file watching does not trigger recompilation for changes saved during compilation.

## expectation
Recompilation should be triggered again after the current compilation step and only stop when the latest changes are compiled. - Like it was in sbt `1.2.8`.

**Comment by eatkins** [comment] 2019-07-20 19:25
@fdietze does it not trigger or does it not recompile? I'm struggling to reproduce a lack of trigger when I save a file during compilation. I do, however, find that sometimes the build triggers when a source is modified during compilation but no recompilation is performed. That is due to an issue in zinc: https://github.com/sbt/zinc/issues/683.

Did the file contents actually change or was the file just saved or touched? The new watch subsystem ignores changes to files that haven't changed since the last run. You can revert to the old behavior with `ThisBuild / watchForceTriggerOnAnyChange := true`.

It also would be helpful if you ran with debug logging on and reported back. You might see some messages that look like "Dropping event for unmodified path..." or "Discarding entry for recently update path...".

**Comment by fdietze** [comment] 2019-07-24 05:21
Hmm, I was not able to reproduce it on a JVM project:
Having a `println("a")` in a big file. Then I changed it to `println("b")`, saved and immediately afer that changed it to `println("c")` and saved again. The compilation triggered twice for both saves, which is correct.

My guess is that is has something to do with my scalajs stack. I will dig deeper when I have more time...

**Comment by SethTisue** [comment] 2023-08-12 22:55
I suggest we close this, as it's been open for a long time and we don't have confirmation that it's reproducible — nor has anyone else stepped forward to say they're informally observing it.

We could always reopen the ticket if someone steps forward with a confirmed reproduction on current sbt.

**Closed as not planned** 2023-08-13 13:51 UTC
