### ISSUE TITLE
JAR entry sbt/sbt.autoplugins not found

### ISSUE THREAD

**Issue by 4lex1v** [sbt/sbt#1864] opened 2015-02-19 06:39 UTC
I have the following project structure:

``` scala
<root>/
  plugins/
    webapp/
  project/
    plugins.sbt
  webapp/
    webapp.sbt
```

`plugins/webapp` is an autoplugin which i wrote to use in my `webapp` project, it's not published, so i'm using `publishLocal` to publish it locally. So when i do some changes in the plugin project, the `reload` my project's session i get this error:

```
[error] java.io.FileNotFoundException: JAR entry sbt/sbt.autoplugins not found in /Users/aleksandrivanov/.ivy2/local/io.scaldo/webapp-plugin/scala_2.10/sbt_0.13/0.0.1/jars/webapp-plugin.jar
```

Though if i close the session (with `exit`) then start the sbt again, no error occurs.

**Comment by ritschwumm** [comment] 2015-02-19 20:29
could this be related to #892?

**Comment by eed3si9n** [comment] 2015-02-24 06:42
Yea. I'd say it's a duplicate of #892.

**Closed as completed by eed3si9n** 2015-02-24 06:42 UTC
Labels: Duplicate
