### ISSUE TITLE
Upgrade To Latest Version of Protobuf

### ISSUE THREAD

**Issue by mikail-khan** [sbt/sbt#5001] opened 2019-08-29 08:22 UTC
See [this](https://github.com/protocolbuffers/protobuf/issues/6512) issue.

**Comment by eed3si9n** [comment] 2019-08-29 12:49
@co-category This is a duplicate of https://github.com/sbt/zinc/issues/459, which has been fixed in 1.3.x. Please try 1.3.0-RC4.

**Closed as completed by eed3si9n** 2019-08-29 12:49 UTC

**Comment by mikail-khan** [comment] 2019-08-29 12:51
Can't upgrade to sbt version >= 1.0 where I work so it would be good to backport the fix if you can to pre-1.0 versions if possible.
