### ISSUE TITLE
Publish Local SNAPSHOT Configuration Not Found

### ISSUE THREAD

**Issue by darkfrog26** [sbt/sbt#4835] opened 2019-06-24 17:09 UTC
## steps
sbt version: *1.2.8*

## problem
When I publish YouI (https://github.com/outr/youi) locally and then try to use it from another project I've started getting this:
io.youi#youi-core_2.12;0.11.8-SNAPSHOT: configuration not found in io.youi#youi-core_2.12;0.11.8-SNAPSHOT: 'master'. It was required from io.youi#youi-stream_2.12;0.11.8-SNAPSHOT compile

**Comment by darkfrog26** [comment] 2019-06-24 17:13
Actually, I just confirmed this is even happening when I `publishLocal` with non-snapshots

**Comment by eed3si9n** [comment] 2019-06-24 17:21
Thanks for the report. This is a duplicate of #2874.

**Closed as completed by eed3si9n** 2019-06-24 17:21 UTC
