### ISSUE TITLE
sbt-1.3.0-M2 breaks code that relies on URLClassLoader

### ISSUE THREAD

**Issue by xerial** [sbt/sbt#4575] opened 2019-03-24 05:33 UTC
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

- Checkout airfame https://github.com/wvlet/airframe
- Run ` sbt -Dsbt.version=1.3.0-M2 logJVM/testOnly *ResourceTest`

## problem
- Some application needs to find files inside a jar file. To do so, we need to use the public method `URLClassLoader.findResourceURLs(path) : Enumeration[URL]`. ClassLoader has the same name method, but it's defined as protected, so we cannot use the base ClassLoader.
- Before sbt-1.3.0-M2, if we trace parent class loaders, we usually can find at least one URLClassLoader that can access resources inside jar files. 
    - Actually LayeredClassLoader, which is extending URLClassLoader, is found as a parent class loader, but it seems this class loader cannot find resources inside jar files.

- Upgrading airframe to use sbt-1.3.0-M2 breaks the build https://github.com/wvlet/airframe/pull/457
   - This is because no URLClassLoader that can find resources inside jar files can be found in this code: https://github.com/wvlet/airframe/blob/28a70c3fdc7a209eabf357548bdf7737c80e7b52/airframe-log/jvm/src/main/scala/wvlet/log/io/Resource.scala#L81-L90

## expectation
- sbt class loader should provide a URLClassLoader to get local resource URls.

## notes

sbt version: 1.3.0-M2

**Comment by xerial** [comment] 2019-03-24 05:37
Actually LayeredClassLoader, which is extending URLClassLoader, is found in a parent, but it seems this class loader cannot find resources inside jar files.

**Comment by eatkins** [comment] 2019-03-24 16:28
Thanks for the report @xerial. I will add this to my queue. There weren't many tests that loaded resources so that is something of a blindspot that needs to be addressed.

**Comment by eatkins** [comment] 2019-04-01 02:43
@xerial I do plan to fix the regression but I am curious if there is another way to solve this problem in airframe. Depending on the implementation details of class loading is inherently unreliable.

**Comment by xerial** [comment] 2019-04-01 06:04
@eatkins Actually simply loading class files of scala.io package is failing in sbt-1.3.0-M2. I think it should be supported by any class loaders in Scala because Scala standard libraries is always there for Scala applications.

I think this is sbt-specific issue since sbt itself is also using Scala.

**Comment by xerial** [comment] 2019-04-01 06:25
I'm wondering, does it affect only Scala libraries? How about resources in other dependent jars? What if sbt and user application share same jars (e.g., jawn or circe json parser, etc.) 

Fixing airframe is ok because reading Scala libraries is just an example of reading resources in airframe. But reading resources from jar files are quite standard techniques for web applications.

So at least I would like to make sure the new sbt can read resources from jar files in the application dependencies.

**Comment by eatkins** [comment] 2019-04-01 14:10
I’m not arguing that this shouldn’t be fixed. I am just saying that having to pattern match to find a URLClassLoader strikes me as an anti-pattern. Presumably in many if not most cases the classpath is known to the application. The required resource could then be loaded with a custom url class loader for the url corresponding to the relevant jar. It is difficult to make every use case work especially given that sbt is so widely used and in ways that are largely untested. It seemed to me that on some level airframe was relying on an implementation detail. Classloading in sbt is, frankly, a mess and the less that builds can rely on the existing implementation details, the more resilient they will be to future updates. That being said, you’re right that this is a regression that should be fixed. I appreciate the additional context/thoughts you’ve provided.

**Comment by xerial** [comment] 2019-04-01 17:44
@eatkins This issue is not specific to the airframe. Airframe just happened to have a test case to read resources in an external jar file (scala.io) 

- **Reading resources inside jar files** using a URLClassLoader is a **must have** feature. For example, if a web application embeds static contents (html pages, CSS files) inside some jar file in the dependency, the list of such resources should be accessible for the obvious reason. URLClassLoader is the de-facto standard to read such resources.
- Testing the capability of reading resources inside _jar files_ is usually forgotten, because if we have such resources as regular files that can be found from the current classpath, almost all class loader can read them.

**Comment by xerial** [comment] 2019-04-01 18:06
Here is a list of example projects that relies on URLClassLoader:
- Play! https://github.com/playframework/playframework/blob/45061d3f5d57001ef5b6eb995ed1b8507b551a12/dev-mode/run-support/src/main/java/play/runsupport/classloader/DelegatingClassLoader.java#L50-L60
- As you suggested, there is an approach that is not relying on URLClassLoader. akka-osgi: https://github.com/akka/akka/blob/02dc90ff6dbd76ef958dd568265fb33c2b4f1da1/akka-osgi/src/main/scala/akka/osgi/BundleDelegatingClassLoader.scala#L67
    - But OSGi is managing the list of resource files in advance, so that we can use a regular `ClassLoader.getResource(name)` by specifying a resource file path inside jar explicitly.
    - It is the same that this also needs an access to resources inside jar files.

**Comment by eatkins** [comment] 2019-04-01 18:11
Agreed with your points. The play! use case is different because they are specifically providing a URLClassLoader. I was just pointing out that runtime pattern matching to extract a URLClassLoader is unsafe. `ClassLoader.findResource` should work correctly.

**Comment by xerial** [comment] 2019-04-01 18:17
Another example: Google's Guava is also using URLClassLoader to get a list of resource URLs:
https://github.com/google/guava/blob/6d7f6556b0db2d177e3aa4cebbfbcfdb4170745f/guava/src/com/google/common/reflect/ClassPath.java#L463

**Comment by xerial** [comment] 2019-04-01 18:18
@eatkins Yes. If we do know the resource name, ClassLoader.findResource works. If we don't know the resource names, it's not easy to get a list of resources that can be found from a classloader if we cannot use URLClassLoader.

**Comment by xerial** [comment] 2019-04-01 18:31
Not only me, Google also has been using this resource listing technique based on URLClassLoader for a long time since around 2010.  An early example I can remember was GWT (Google Web Toolkit) to read web resources using URLClassLoader. 

If there is a proper way to read resources, we will use it. So far, however, using URLClassLoader has been the only way even though this approach is fundamentally unreliable as you said, but it's been working well except for LayeredClassLoader.

**Comment by eatkins** [comment] 2019-04-01 18:42
Ok, cool. I didn't fully understand the use case. My point is simply that there is nothing in the sbt spec that says that run or test provide any specific URLClassLoader implementation so you are relying on undefined behavior. As long as we can agree on that point (or agree to disagree), I think we can move on.

I'm not saying you're wrong. I am suggesting that if a URLClassLoader with specific semantics is required then it would be best practice to actually manage your classloaders manually and not rely on what sbt provides by default. Then you will not be impacted if sbt (or any other build tool) changes the implementation out from underneath you.

Again, I am planning to fix the current airframe build before sbt 1.3.0.

**Comment by eatkins** [comment] 2019-04-03 00:02
Should be fixed in #4601

```
ethanatkins@Ethans-MacBook-ProZ:~/work/oss/sbt/community/airframe$ sbt8 -Dsbt.supershell=never -Dsbt.version=1.3.0-M2 "logJVM/testOnly *ResourceTest"                                                                                                                                     
Getting org.scala-sbt sbt 1.3.0-M2  (this may take some time)...
:: retrieving :: org.scala-sbt#boot-app
        confs: [default]
        80 artifacts copied, 0 already retrieved (29549kB/218ms)
[info] Loading settings for project global-plugins from idea.sbt,global.sbt ...
[info] Loading global plugins from /Users/ethanatkins/.sbt/1.0/plugins
[info] Loading settings for project airframe-build from plugin.sbt ...
[info] Loading project definition from /Users/ethanatkins/work/oss/sbt/community/airframe/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project root from build.sbt ...
[info] Resolving key references (32254 settings) ...
[info] Set current project to airframe-root (in build file:/Users/ethanatkins/work/oss/sbt/community/airframe/)
[info] ResourceTest:
[info] Resource
[info] - should find files from the current class loader
[info] - should find resources from jar files *** FAILED ***
[info]   0 was not greater than 0 (ResourceTest.scala:41)
[info] - should find classes of specific types *** FAILED ***
[info]   0 was not greater than 0 (ResourceTest.scala:49)
[info] ResourceReader trait
[info] - should find files using the context class
[info] Run completed in 509 milliseconds.
[info] Total number of tests run: 4
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 2, failed 2, canceled 0, ignored 0, pending 0
[info] *** 2 TESTS FAILED ***
[error] Failed tests:
[error]         wvlet.log.io.ResourceTest
[error] (logJVM / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 3 s, completed Apr 2, 2019 5:00:51 PM
ethanatkins@Ethans-MacBook-ProZ:~/work/oss/sbt/community/airframe$ sbt8 -Dsbt.supershell=never -Dsbt.version=1.3.0-meta-0 "logJVM/testOnly *ResourceTest"                                                                                                                                 
Getting org.scala-sbt sbt 1.3.0-meta-0  (this may take some time)...
:: retrieving :: org.scala-sbt#boot-app
        confs: [default]
        80 artifacts copied, 0 already retrieved (29706kB/149ms)
[info] Loading settings for project global-plugins from idea.sbt,global.sbt ...
[info] Loading global plugins from /Users/ethanatkins/.sbt/1.0/plugins
[info] Loading settings for project airframe-build from plugin.sbt ...
[info] Loading project definition from /Users/ethanatkins/work/oss/sbt/community/airframe/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
/Users/ethanatkins/work/oss/sbt/community/airframe/build.sbt:251: warning: value watchSources in object Keys is deprecated (since 1.3.0): WatchSource has been replaced by Glob. To add file triggers to a task with key: Key, set `Key / watchTriggers := Seq[Glob](...)`.               
      watchSources += new sbt.internal.io.Source(
      ^
[info] Loading settings for project root from build.sbt ...
[info] Resolving key references (32319 settings) ...
[info] Set current project to airframe-root (in build file:/Users/ethanatkins/work/oss/sbt/community/airframe/)
[info] ResourceTest:
[info] Resource
[info] - should find files from the current class loader
[info] - should find resources from jar files
[info] - should find classes of specific types
[info] ResourceReader trait
[info] - should find files using the context class
[info] Run completed in 681 milliseconds.
[info] Total number of tests run: 4
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 4, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 4 s, completed Apr 2, 2019 5:01:39 PM
```

**Comment by xerial** [comment] 2019-04-03 01:21
@eatkins Awesome. Thanks! 
Then I can enjoy the other wonderful improvements at sbt-1.3.0!

**Comment by eatkins** [comment] 2019-04-03 02:49
Thank you! Sorry if I seemed obstinate before. It was great that you brought this issue up. I might not have solved it prior to release otherwise.

**Closed as completed** 2019-04-03 04:46 UTC
Labels: Regression
