### ISSUE TITLE
Debian SBT is not Signed

### ISSUE THREAD

**Issue by ellio246t** [sbt/sbt#6596] opened 2021-07-14 06:54 UTC
The install Scala Tools task in Azure DevOps stopped working last Friday.  Looks like the issue is the same as https://github.com/sbt/sbt/issues/4507.

Here's what my log file says:
2021-07-09T12:39:16.9171074Z sudo DEBIAN_FRONTEND=noninteractive apt-get update
2021-07-09T12:39:16.9171437Z ===================
2021-07-09T12:39:17.0271638Z Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
2021-07-09T12:39:17.0273113Z Hit:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease
2021-07-09T12:39:17.0274045Z Hit:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease
2021-07-09T12:39:17.0329542Z Hit:4 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease
2021-07-09T12:39:17.0713699Z Err:5 https://dl.bintray.com/sbt/debian  InRelease
2021-07-09T12:39:17.0714621Z   403  Forbidden [IP: 35.157.24.53 443]
2021-07-09T12:39:17.0787262Z Hit:6 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
2021-07-09T12:39:17.1729795Z Hit:7 http://security.ubuntu.com/ubuntu focal-security InRelease
2021-07-09T12:39:18.7422803Z Reading package lists...
2021-07-09T12:39:18.7615348Z E: Failed to fetch https://dl.bintray.com/sbt/debian/InRelease  403  Forbidden [IP: 35.157.24.53 443]
2021-07-09T12:39:18.7617016Z E: The repository 'https://dl.bintray.com/sbt/debian  InRelease' is not signed.
2021-07-09T12:39:18.7634938Z ===================
2021-07-09T12:39:18.7636092Z sudo DEBIAN_FRONTEND=noninteractive apt-get install sbt -y
2021-07-09T12:39:18.7636959Z ===================
2021-07-09T12:39:18.8304314Z Reading package lists...
2021-07-09T12:39:18.9896248Z Building dependency tree...
2021-07-09T12:39:18.9912572Z Reading state information...
2021-07-09T12:39:19.1205822Z E: Unable to locate package sbt
2021-07-09T12:39:19.1260499Z ##[debug]Exit code 100 received from tool '/usr/bin/bash'
2021-07-09T12:39:19.1271494Z ##[debug]STDIO streams have closed for tool '/usr/bin/bash'
2021-07-09T12:39:19.1325817Z ##[error]Bash exited with code 100
2021-07-09T12:39:19.1337278Z ##[debug]Processed: ##vso[task.issue type=error;]Bash exited with code 100
2021-07-09T12:39:19.1337986Z ##[debug]task result: Failed
2021-07-09T12:39:19.1341905Z ##[debug]Processed: ##vso[task.complete result=Failed;done=true;]
2021-07-09T12:39:19.1344268Z ##[section]Finishing: Install Scala Tools

**Comment by northernocean** [comment] 2021-07-14 12:25
Seeing this error in Ubuntu 20.04 running apt update:

E: Failed to fetch https://dl.bintray.com/sbt/debian/InRelease  403  Forbidden [IP: 34.211.43.146 443]
E: The repository 'https://dl.bintray.com/sbt/debian  InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by SethTisue** [comment] 2021-07-14 13:23
duplicate of #6582 and #6583 and #6584

**Closed as completed by SethTisue** 2021-07-14 13:23 UTC
