### ISSUE TITLE
regression: `sbt -error` doesn't suppress `[info]` messages during startup

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt#3928] opened 2018-02-07 18:36 UTC
sbt 0.13.17:

```
% sbt -error
> 
```

sbt 1.1.0:

```
% sbt -error
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/tisue/scala-fortify/project
[info] Loading settings from build.sbt ...
[info] Set current project to scala-fortify (in build file:/Users/tisue/scala-fortify/)
[info] sbt server started at local:///Users/tisue/.sbt/1.0/server/f255323a4802b19e47bd/sock
sbt:scala-fortify>
```

the original issue is #840

**Comment by eed3si9n** [comment] 2018-02-08 02:53
Duplicate of #3849

**Closed as completed by eed3si9n** 2018-02-08 02:53 UTC

**Comment by SethTisue** [comment] 2018-02-08 04:00
doh
