### ISSUE TITLE
crossSbtVersions and scalaVersion

### ISSUE THREAD

**Issue by mr-git** [sbt/sbt#3305] opened 2017-07-06 07:48 UTC
For our plugin, I have set in `build.sbt`
```
crossSbtVersions := Vector("0.13.15", "1.0.0-M6")
```
I expected that this will set `scalaVersion` correctly for each plugin cross-build ("2.10.x" for sbt 0.13 and "2.12.x" for sbt 1.0.0), but it tries to compile plugin with Scala 2.11.

I made a simple workaround, which I do not like:
```
scalaVersion := {
  if ((sbtVersion in pluginCrossBuild).value == "0.13.15") "2.10.6"
  else "2.12.2"
}
```

Is this a bug or expected behaviour?

**Comment by eed3si9n** [comment] 2017-07-06 09:19
I am assuming you are using 0.13.16-M1.
I think this is a bug.

**Comment by jvican** [comment] 2017-07-06 09:29
I think this is a known behaviour and every plugin cross building to different sbt versions special cases it. Wasn't there a ticket about this?

**Comment by dwijnand** [comment] 2017-07-06 09:38
Yep. Duplicate of #3205.

**Closed as completed by dwijnand** 2017-07-06 09:38 UTC

**Comment by mr-git** [comment] 2017-07-06 09:53
yes, I am using SBT `0.13.16-M1`.
I assume that it should be fairly easy to set Scala 2.10 for SBT 0.13.x case, like it sets Scala 2.12 in case of SBT 1.0.x - it is very well known limitation of plugin development.

**Comment by mr-git** [comment] 2017-07-06 09:54
Or migration documentation must provide code snippet for guidance:
```
scalaVersion := {
  if ((sbtVersion in pluginCrossBuild).value == "0.13.15") "2.10.6"
  else "2.12.2"
}
```

**Comment by dwijnand** [comment] 2017-07-06 10:13
I recommend:

```scala
scalaVersion := (CrossVersion partialVersion (sbtVersion in pluginCrossBuild).value match {
  case Some((0, 13)) => "2.10.6"
  case Some((1, _))  => "2.12.2"
  case _             => sys error s"Unhandled sbt version ${(sbtVersion in pluginCrossBuild).value}"
})
```

**Comment by mr-git** [comment] 2017-07-06 10:21
Thanks!
It would be good to have it in manual somewhere... Will that new auto-migration tool provide this automagically?

**Comment by dwijnand** [comment] 2017-07-06 10:33
I think those are _both_ good suggestions.

Could I interest you in contributing that change to the manual? The sources are at https://github.com/sbt/website.

And to request this as a feature of sbtfix, please open a ticket at https://github.com/scalacenter/sbtfix/issues.
