### ISSUE TITLE
"CreateFile() failed with error 123" on Windows 10

### ISSUE THREAD

**Issue by billsg** [sbt/sbt#5224] opened 2019-11-05 12:22 UTC
## steps
sbt version: 1.3.3
run compile command

## problem
Build error on Windows 10. 
java version "1.8.0_221"

## expectation
sbt build should be successful 

## Trace

```
[error] java.io.IOException: CreateFile() failed with error 123
[error]         at sbt.internal.io.WinMilli$.getHandle(Milli.scala:281)
[error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:290)
[error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:261)
[error]         at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:62)
[error]         at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:371)
[error]         at sbt.io.IO$.$anonfun$getModifiedTimeOrZero$1(IO.scala:1373)
[error]         at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
[error]         at sbt.internal.io.Retry$.liftedTree2$1(Retry.scala:38)
[error]         at sbt.internal.io.Retry$.impl$1(Retry.scala:38)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:52)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:24)
[error]         at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1373)
[error]         at sbt.nio.FileStamp$.lastModified(FileStamp.scala:87)
[error]         at sbt.nio.FileStamp$.apply(FileStamp.scala:66)
[error]         at sbt.nio.FileStamp$Cache.updateImpl(FileStamp.scala:308)
[error]         at sbt.nio.FileStamp$Cache.getOrElseUpdate(FileStamp.scala:275)
[error]         at sbt.internal.ExternalHooks$.$anonfun$default$3(ExternalHooks.scala:37)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at sbt.internal.ExternalHooks$.$anonfun$default$1(ExternalHooks.scala:35)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (objects / Compile / externalHooks) java.io.IOException: CreateFile() failed with error 123

[error] java.io.IOException: CreateFile() failed with error 123
[error]         at sbt.internal.io.WinMilli$.getHandle(Milli.scala:281)
[error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:290)
[error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:261)
[error]         at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:62)
[error]         at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:371)
[error]         at sbt.io.IO$.$anonfun$getModifiedTimeOrZero$1(IO.scala:1373)
[error]         at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
[error]         at sbt.internal.io.Retry$.liftedTree2$1(Retry.scala:38)
[error]         at sbt.internal.io.Retry$.impl$1(Retry.scala:38)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:52)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:24)
[error]         at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1373)
[error]         at sbt.nio.FileStamp$.lastModified(FileStamp.scala:87)
[error]         at sbt.nio.FileStamp$.apply(FileStamp.scala:66)
[error]         at sbt.nio.FileStamp$Cache.updateImpl(FileStamp.scala:308)
[error]         at sbt.nio.FileStamp$Cache.getOrElseUpdate(FileStamp.scala:275)
[error]         at sbt.Classpaths$.$anonfun$classpaths$22(Defaults.scala:2072)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
[error]         at scala.collection.immutable.List.flatMap(List.scala:355)
[error]         at sbt.Classpaths$.$anonfun$classpaths$21(Defaults.scala:2072)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (objects / Compile / dependencyClasspathFiles / outputFileStamps) java.io.IOException: CreateFile() failed with error 123
```

**Comment by eed3si9n** [comment] 2019-11-09 15:39
@billsg Thanks for the report. Currently the repro steps is likely insufficient to reproduce the issue. Does this happen with any project (including blank `build.sbt` file), or does it require something specific?

**Comment by amirhmd** [comment] 2019-12-18 19:06
yes its happening for me as well
`
akka > last akka-stream / Compile / externalHooks
[error] java.io.IOException: CreateFile() failed with error 123
[error]         at sbt.internal.io.WinMilli$.getHandle(Milli.scala:281)
[error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:290)
[error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:261)
[error]         at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:62)
[error]         at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:371)
[error]         at sbt.io.IO$.$anonfun$getModifiedTimeOrZero$1(IO.scala:1373)
[error]         at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
[error]         at sbt.internal.io.Retry$.liftedTree2$1(Retry.scala:38)
[error]         at sbt.internal.io.Retry$.impl$1(Retry.scala:38)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:52)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:24)
[error]         at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1373)
[error]         at sbt.nio.FileStamp$.lastModified(FileStamp.scala:87)
[error]         at sbt.nio.FileStamp$.apply(FileStamp.scala:66)
[error]         at sbt.nio.FileStamp$Cache.updateImpl(FileStamp.scala:308)
[error]         at sbt.nio.FileStamp$Cache.getOrElseUpdate(FileStamp.scala:275)
[error]         at sbt.internal.ExternalHooks$.$anonfun$default$3(ExternalHooks.scala:37)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at sbt.internal.ExternalHooks$.$anonfun$default$1(ExternalHooks.scala:35)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]         at java.lang.Thread.run(Unknown Source)
[error] (akka-stream / Compile / externalHooks) java.io.IOException: CreateFile() failed with error 123

`

**Comment by amirhmd** [comment] 2019-12-18 19:07
`akka > last akka-stream / Compile / externalHooks
[error] java.io.IOException: CreateFile() failed with error 123
[error]         at sbt.internal.io.WinMilli$.getHandle(Milli.scala:281)
[error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:290)
[error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:261)
[error]         at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:62)
[error]         at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:371)
[error]         at sbt.io.IO$.$anonfun$getModifiedTimeOrZero$1(IO.scala:1373)
[error]         at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
[error]         at sbt.internal.io.Retry$.liftedTree2$1(Retry.scala:38)
[error]         at sbt.internal.io.Retry$.impl$1(Retry.scala:38)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:52)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:24)
[error]         at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1373)
[error]         at sbt.nio.FileStamp$.lastModified(FileStamp.scala:87)
[error]         at sbt.nio.FileStamp$.apply(FileStamp.scala:66)
[error]         at sbt.nio.FileStamp$Cache.updateImpl(FileStamp.scala:308)
[error]         at sbt.nio.FileStamp$Cache.getOrElseUpdate(FileStamp.scala:275)
[error]         at sbt.internal.ExternalHooks$.$anonfun$default$3(ExternalHooks.scala:37)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at sbt.internal.ExternalHooks$.$anonfun$default$1(ExternalHooks.scala:35)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]         at java.lang.Thread.run(Unknown Source)
[error] (akka-stream / Compile / externalHooks) java.io.IOException: CreateFile() failed with error 123
`

**Comment by amirhmd** [comment] 2019-12-18 19:19
sbt 1.3.4
java 1.8.202

**Comment by mghildiy** [comment] 2020-01-18 17:23
I too face this issue when I run 'sbt compile' in akka project.

java version "1.8.0_221"
sbt 1.3.4

**Comment by ielkhalloufi** [comment] 2020-01-18 17:51
The same here:

Windows 10
SBT 1.3.6
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)

**Comment by eed3si9n** [comment] 2020-01-19 00:18
A quick workaround might be to run sbt with `-Dsbt.io.jdktimestamps=true`.

**Comment by eed3si9n** [comment] 2020-01-19 00:23
error 123 is apparently [`ERROR_INVALID_NAME`](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-):

> The filename, directory name, or volume label syntax is incorrect.

**Comment by eed3si9n** [comment] 2020-01-19 00:28
Could someone share the full path of the working directory that caused this issue?

**Comment by eed3si9n** [comment] 2020-01-19 01:18
@eatkins wrote on https://github.com/sbt/io/pull/273

> The fix for long path names on windows,
099aa4f3ced649b48a9cf6595fbdb5524b69cfa5, had the unintended side effect
of causing IO.getModifiedTimeOrZero to throw uncaught IOExceptions when
the path name was not normalized. Specifically, it would throw if the
path was empty or if it had relative components. To fix this, we try to
get the modified time but if the file is not found, we normalize the
path and make it absolute and retry.

I guess I need to backport the PR to 1.3.x.

**Comment by mghildiy** [comment] 2020-01-19 04:05
> Could someone share the full path of the working directory that caused this issue?

For me, its like this:
C:\work\projects\akka\akka-official

**Comment by eed3si9n** [comment] 2020-01-19 18:32
@mghildiy Thanks. The path looks perfectly normal assuming none of those are NTFS junctions. Do you specify Coursier directory to be somewhere weird?

Also could you try setting `sbt.version=1.4.0-bin-20200117T202001`? That would confirm that the PR would actually fix this problem.

**Comment by mghildiy** [comment] 2020-01-20 05:22
It worked with sbt.version=1.4.0-bin-20200117T202001.

**Comment by ielkhalloufi** [comment] 2020-01-20 10:19
@eed3si9n 
This worked also for me: sbt.version=1.4.0-bin-20200117T202001

**Comment by eed3si9n** [comment] 2020-02-04 01:04
This should be fixed in sbt 1.3.8.

**Closed as completed by eed3si9n** 2020-02-04 01:04 UTC
Labels: area/windows

**Comment by batterseapower** [comment] 2020-06-09 15:24
Hmm - I too saw this issue with 1.3.4 but it persisted after I upgraded to 1.3.10. The `-Dsbt.io.jdktimestamps=true` workaround does fix it. I'm on Windows 10. Traceback:

````
[error] java.io.IOException: CreateFile() failed with error 123
[error]         at sbt.internal.io.WinMilli$.getHandle(Milli.scala:281)
[error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:290)
[error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:261)
[error]         at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:62)
[error]         at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:371)
[error]         at sbt.io.IO$.$anonfun$getModifiedTimeOrZero$1(IO.scala:1373)
[error]         at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
[error]         at sbt.internal.io.Retry$.liftedTree2$1(Retry.scala:38)
[error]         at sbt.internal.io.Retry$.impl$1(Retry.scala:38)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:52)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:24)
[error]         at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1373)
[error]         at sbt.nio.FileStamp$.lastModified(FileStamp.scala:87)
[error]         at sbt.nio.FileStamp$.apply(FileStamp.scala:66)
[error]         at sbt.nio.FileStamp$Cache.updateImpl(FileStamp.scala:308)
[error]         at sbt.nio.FileStamp$Cache.getOrElseUpdate(FileStamp.scala:275)
[error]         at sbt.internal.ExternalHooks$.$anonfun$default$3(ExternalHooks.scala:37)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at sbt.internal.ExternalHooks$.$anonfun$default$1(ExternalHooks.scala:35)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
````

The working directory name is perfectly normal (`D:\aqua-runner`).

**Comment by batterseapower** [comment] 2020-06-09 16:55
I think my issue above is caused by the uninstall/reinstall not working quite right - I checked Process Monitor and sbt is still loading the 1.3.4 JARs somehow. Please disregard.
