### ISSUE TITLE
Order of settings evaluation is surprising and not intuitive

### ISSUE THREAD

**Issue by pfn** [sbt/sbt#2697] opened 2016-08-12 16:46 UTC
Given a  `build.sbt` like the following

```
val p = project.settings(name := "foo")
name in p := "bar"
```

I would expect `p/name` to show `bar`, it shows `foo`

If I later add `z-build.sbt` like so:

```
val p = ProjectRef(file("."), "p")
name in p := "baz"
```

I would expect `p/name` to show `baz`, but it still shows `foo`

```
[pfnguyen@galactica s] $ sbt p/name
[info] Loading global plugins from C:\Users\pfnguyen\.sbt\0.13\plugins
[info] Set current project to s (in build file:/C:/Users/pfnguyen/src/s/)
[info] foo
```

Generally, I would expect settings declarations that come after the initial project declaration to take precedence, especially when it's split across files. In this contrived example, it's "why would you ever do that", but in my actual use-cases, I often have a generated sbt file which I want to later make changes to. When making those changes, I do not want to change the generated sbt file, but an auxiliary file, like `z-build.sbt` to ensure correct ordering.

Also, this is very applicable to plugin settings, e.g. if one were to do

```
val p = project.settings(somePluginSettings) // sbt-android still requires this format because autoplugins is underengineered  ;-)
anyAbovePluginSetting := ... // will get ignored if it was set by somePluginSettings
```

**Comment by eed3si9n** [comment] 2016-08-12 17:01
Duplicate of (or related to) #2232

**Comment by clhodapp** [comment] 2017-01-02 08:15
Count me in as having hit this too. The current behavior makes it really hard to override things in the builds of source dependencies (I've not yet found a workaround).

**Comment by eed3si9n** [comment] 2017-10-06 17:16
I think the steps created by @dwijnand on Gitter is a variant of this:

## steps

foo/build.sbt

```scala
dependsOn(RootProject(file("../bar")))
scalaVersion in Global := "foo wins"
```

bar/build.sbt

```scala
scalaVersion in Global := "bar wins"
```

## problem

```
> show scalaVersion
[info] bar wins
```

## expectation of mine

I think DSL constructs (subproject definitions, `def`, `val`, bare settings, bare `dependsOn` etc) should be individually sorted first by file names alphabetically, and then dependencies.
And because `foo` comes after `bar` alphabetically, foo should win.

**Comment by eed3si9n** [comment] 2020-02-19 15:49
Note to self:

- https://github.com/sbt/sbt/blob/v1.3.8/main/src/main/scala/sbt/internal/EvaluateConfigurations.scala
- https://github.com/sbt/sbt/blob/v1.3.8/main/src/main/scala/sbt/internal/Load.scala

All things `memoSettings` are suspect.

**Comment by dwijnand** [comment] 2020-02-19 15:58
> I think the steps created by @dwijnand on Gitter is a variant of this:

Actually I think that variant is #3850, as it's about introducing other builds to the build configuration.  And I don't think it should do an alphabetic thing at all: the foo build is importing the bar build, so foo's settings should override bar's settings.

This one (#2697) and #2232 instead seem to be the same, and should probably specify and do an alphabetic thing.

**Closed as completed** 2020-02-26 21:25 UTC
Labels: Needs discussion/On Hold, area/build_dsl
