### ISSUE TITLE
sbt.bat not working with new

### ISSUE THREAD

**Issue by roti** [sbt/sbt#5221] opened 2019-10-31 17:48 UTC
## steps
sbt version: 1.3.3

## problem
`sbt new` doesn't seem to work. Here's the output:
```
D:\projects>sbt new scala/scala-seed.g8
c) continue
q) quit
?      if /I "" == "c" (
```

## notes
I traced it back to a typo in sbt.bat.
The problem area:
```
if not defined sbt_args_sbt_create if not defined sbt_args_print_version if not defined sbt_args_print_sbt_version if not defined sbt_args_print_sbt_script_version if not exist build.sbt (
  if not exist project\ (
    if not defined sbt_new (
      echo [warn] Neither build.sbt nor a 'project' directory in the current directory: %CD%
      setlocal
:confirm
      echo c^) continue
      echo q^) quit

      set /P reply=?^
      if /I "!reply!" == "c" (
        goto confirm_end
      ) else if /I "!reply!" == "q" (
        exit /B 1
      )

      goto confirm
:confirm_end
      endlocal
    )
  )
)
```

The problem is caused by an extra `^` character.
Current: `set /P reply=?^`
Correct: `set /P reply=?`

**Comment by roti** [comment] 2019-10-31 17:49
I wanted to make a pull request, but couldn't find `sbt.bat` in the repo. :)

**Comment by eed3si9n** [comment] 2019-10-31 18:47
@roti This is a duplicate of #5188, and it will be fixed in the next release.
`sbt.bat` lives in https://github.com/sbt/sbt-launcher-package/blob/master/src/universal/bin/sbt.bat for now, but we've always wanted to move it to sbt/sbt eventually.

**Closed as completed by eed3si9n** 2019-10-31 18:47 UTC
