### ISSUE TITLE
consecutive sbt runs resolve dependencies differently

### ISSUE THREAD

**Issue by redbaron** [sbt/sbt#4643] opened 2019-05-02 16:25 UTC
## steps

```
sbt evicted && sbt evicted
```

## problem

first run resolves dependencies differently from all subsequent runs:

First run:
```
[info]     * javax.cache:cache-api:1.1.0 is selected over 1.0.0
[info]         +- com.github.ben-manes.caffeine:jcache:2.6.2         (depends on 1.1.0)
[info]         +- com.typesafe.play:play-ahc-ws_2.12:2.7.1 ()        (depends on 1.0.0)
[info]         +- com.typesafe.play:play-caffeine-cache_2.12:2.7.1 () (depends on 1.0.0)
```

Second run:
```
[info]     * javax.cache:cache-api:1.0.0 is selected over 1.1.0
[info]         +- com.typesafe.play:play-ahc-ws_2.12:2.7.1 ()        (depends on 1.0.0)
[info]         +- com.typesafe.play:play-caffeine-cache_2.12:2.7.1 () (depends on 1.0.0)
[info]         +- com.github.ben-manes.caffeine:jcache:2.6.2         (depends on 1.1.0)
```

## expectation

dependency resolution is stable

## notes

sbt version: 1.2.8

`sbt  evicted evicted` shows the same difference

**Comment by eed3si9n** [comment] 2019-05-02 17:44
@redbaron Thanks for the report. Do you have a project available that would reproduce this issue? I can guess from the description but if would be nice if there's one already.

**Comment by redbaron** [comment] 2019-05-02 20:46
Hi! Thanks for the quick response. I am not sbt savvy, this ticket is a result of painstaking debugging, so I thought I ll just leave it here what I already have in case it is something already known or would be obvious from minimal info I gave.


I might have time to create minimal stripped down version of build.sbt to see if can be reproduced on your side, project is not open source sadly :(

It is also very reliably reproducible, so you if there are any flags/commands I can use to help you understand what it might be, I am more than happy to run them and submit logs here.

**Comment by eed3si9n** [comment] 2019-05-02 21:34
If you depended on `avax.cache:cache-api:1.1.0` directly, would the flip flopping go away?

**Comment by eed3si9n** [comment] 2019-08-10 06:50
I am going to preemptively close this issue since sbt 1.3.0-RC3 uses Coursier internally, and hopefully it's now fixed. Let us know if that's not the case.

**Closed as completed by eed3si9n** 2019-08-10 06:50 UTC
Labels: area/library_management
