### ISSUE TITLE
Arrow keys do not work on Windows without  -Dinput.encoding=Cp1252

### ISSUE THREAD

**Issue by richdougherty** [sbt/sbt#871] opened 2013-09-11 05:16 UTC
In Play we had some problems with sbt 0.13's command history on windows. This is because we set the `-Dfile.encoding=UTF-8` system property which interfered with JLine. 

```
>set JAVA_OPTS=-Dfile.encoding=UTF-8
>sbt
[info] Set current project to project (in build file:/C:/p/ansi/ansi2/project/)
> ∩┐╜
```

The fix required reading a bit of JLine 2 source code, but was pretty easy: add another property `-Dinput.encoding=Cp1252`.

Here's the Play issue: https://github.com/playframework/playframework/pull/1620

@jsuereth suggested that this fix might not work properly in all countries.

**Comment by eed3si9n** [comment] 2014-12-01 09:48
@Atry commented on 19d75ae2f9f0959e1f230d8d834dd39f827a5d83 that this is a JLine issue jline/jline2#100 that's fixed in the latest 2.12.

**Comment by richdougherty** [comment] 2014-12-01 22:42
Play has a [workaround](https://github.com/playframework/playframework/pull/1620/files), but it seems like it would be worth upgrading sbt to JLine 2.12 to pick up this fix.

**Comment by szeiger** [comment] 2016-01-10 12:21
Is there any progress on this in sbt? 0.13.9 still has the same problem.

**Comment by dwijnand** [comment] 2016-01-10 20:48
@szeiger We've updated JLine to 2.13 (#2173).

Can you check perhaps a nightly of 0.13.10? 

See https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt-launch/

**Comment by nartamonov** [comment] 2016-11-21 19:41
Still facing the same problem in 0.13.13.1.

**Comment by muxanick** [comment] 2017-09-17 20:03
Any progress on this issue? still doesn't work for me (I use utf-8 encoding)
sbt 1.0.1

**Comment by eed3si9n** [comment] 2017-09-17 21:01
I thought updating to the latest JLine 2 would fix it, but if it's happening to 1.0.1 we'd need to something more.
Does this happen to both cmd and Cygwin?

**Comment by muxanick** [comment] 2017-09-17 21:46
@eed3si9n I haven't tried cygwin (never used it before), I've tried `cmd` and `powershell`

**Comment by eed3si9n** [comment] 2017-09-21 07:10
Would you consider using Cygwin for sbt? That would be a horrible workaround, but hey the arrow key might start working again.

**Comment by muxanick** [comment] 2017-09-22 22:08
@eed3si9n I've tried to work in Cygwin for a day, that's not a solution at all, too slow, too much memory, to heavy for everyday work. And it requires of re-writing of whole my infrastructure of scripts.
Can you please point me to the code I can look into to fix that issue?

**Comment by eed3si9n** [comment] 2017-09-22 23:09
@muxanick I don't know for sure what's causing the problem, but a good start might be the following:

- https://github.com/sbt/sbt/blob/v1.0.2/internal/util-complete/src/main/scala/sbt/internal/util/LineReader.scala#L22-L31
- https://github.com/sbt/sbt-zero-thirteen/blob/v0.13.16/util/complete/src/main/scala/sbt/LineReader.scala#L16

Another thing you could try is write JLine 2 application in your environment, and find if the problem is coming from JLine or sbt.

**Comment by muxanick** [comment] 2017-09-24 17:11
@eed3si9n thanks!

**Comment by SethTisue** [comment] 2023-02-09 01:29
perhaps this is one we should just close unless someone speaks up and says it's still reproducible, as the whole JLine situation has moved on a lot since 2017

**Comment by eed3si9n** [comment] 2023-02-15 14:40
Closings this for now.

**Closed as completed by eed3si9n** 2023-02-15 14:40 UTC
Labels: documentation
