### ISSUE TITLE
Can't type in sbt 1.4.2 shell with supershell disabled

### ISSUE THREAD

**Issue by japgolly** [sbt/sbt#6055] opened 2020-11-03 23:20 UTC
## steps

1. Start sbt 1.4.2 in Linux
2. Try to type anything

## problem

It doesn't respond. Keys that I press don't appear; eg I can't type in "compile". ctrl-d doesn't exit. Only ctrl-c works.

## notes

Not a problem with 1.4.1

**Comment by eatkins** [comment] 2020-11-04 03:52
Thanks for the report. I cannot reproduce on my ubuntu vm. Could you provide some more details about os/jvm version/shell that you're running?

**Comment by japgolly** [comment] 2020-11-04 05:02
Yes! I'm using Arch Linux and gnome-terminal. Here are some additional details.

```
> uname -a                    
Linux golly-desktop 5.8.14-arch1-1 #1 SMP PREEMPT Wed, 07 Oct 2020 23:59:46 +0000 x86_64 GNU/Linux

> echo $TERM
gnome-256color

> echo $SHELL
/usr/bin/zsh

> java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)
```

**Comment by eatkins** [comment] 2020-11-04 15:44
I hate to say it, but I have no idea how I can debug this short of installing an arch linux vm and that's a lot of labor for me. It's unusual for this kind of thing to have different behavior between linux distros. Would you be willing to git bisect sbt to find what commit broke your console? I'm guessing you know how to use git bisect, but here are full instructions anyway:
1. clone sbt
2. cd to the project directory
3. `git bisect good v1.4.1`
4. `git bisect bad v1.4.2`
5. `sbt ~publishLocalBin`
6. go to the project that isn't working and run `rm -r ~/.sbt/boot/scala-2.12.*/org.scala-sbt/sbt/1.*SNAPSHOT; sbt -Dsbt.version=1.4.1-SNAPSHOT` (we switched the default version to 1.4.2-SNAPSHOT between 1.4.1 and 1.4.2 but the first bisect step should be 1.4.1-SNAPSHOT)
7. check if the console input works and go back to the sbt directory and run `git bisect good` if it did, `git bisect bad` if it didn't
8. go to 6 until the process identifies the first commit that broke console on your machine

There aren't that many commits between 1.4.1 and 1.4.2 so this process shouldn't take that long. If I had to make a guess, I'd say 82d6a050de44943f03825786294987bd0a2a0311 seems the most likely to have broken the console input so you also could try that commit and the one preceding it to possibly skip bisecting.

**Comment by eatkins** [comment] 2020-11-04 18:45
Another thing that would be helpful is the thread dump of the sbt process that isn't responding to input, i.e. the output of `jstack $SBT_PID`. In particular, I'm curious if you see an entry for a thread with the name `sbt-console-input-reader` which should look something like:
```
"sbt-console-input-reader" #46 prio=5 os_prio=31 cpu=1.08ms elapsed=18.50s tid=0x00007f84f192e800 nid=0xc603 runnable  [0x000070001575b000]                                                                                                                                     
   java.lang.Thread.State: RUNNABLE                                                                                                     
        at java.io.FileInputStream.readBytes(java.base@11.0.7/Native Method)                                                                                                                                                                                                    
        at java.io.FileInputStream.read(java.base@11.0.7/FileInputStream.java:279)                                                      
        at java.io.BufferedInputStream.fill(java.base@11.0.7/BufferedInputStream.java:252)                                                                                                                                                                                      
        at java.io.BufferedInputStream.read(java.base@11.0.7/BufferedInputStream.java:271)                                              
        - locked <0x00000007c0188658> (a java.io.BufferedInputStream)                                                                   
        at sbt.internal.util.Terminal$WriteableInputStream.impl$1(Terminal.scala:491)                                                                                                                                                                                           
        at sbt.internal.util.Terminal$WriteableInputStream.$anonfun$runnable$1(Terminal.scala:496)                                      
        at sbt.internal.util.Terminal$WriteableInputStream$$Lambda$447/0x00000008005ad440.run(Unknown Source)                                                                                                                                                                   
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.7/Executors.java:515)                                     
        at java.util.concurrent.FutureTask.run(java.base@11.0.7/FutureTask.java:264)                       
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.7/ThreadPoolExecutor.java:1128)                                                                                                                                                                     
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.7/ThreadPoolExecutor.java:628)                             
        at java.lang.Thread.run(java.base@11.0.7/Thread.java:834)  
```
If that thread is not running, then I wouldn't expect input to work.

**Comment by smarter** [comment] 2020-11-04 23:04
I'm seeing the same thing on Ubuntu 20.10 (tried multiple shells, multiple terminals, multiple JVM versions and it didn't make any difference), **however the problem only happens when starting sbt with ` -Dsbt.supershell=false`**

> Would you be willing to git bisect sbt to find what commit broke your console?

No sorry, sbt should really publish nightly binaries.

> Another thing that would be helpful is the thread dump of the sbt process that isn't responding to input, i.e. the output of jstack $SBT_PID

Full jstack: [jstack.log](https://github.com/sbt/sbt/files/5490911/jstack.log)

**Comment by eatkins** [comment] 2020-11-04 23:05
> No sorry, sbt should really publish nightly binaries.

@smarter I did not ask you personally and I really do not appreciate the tone that you often bring to issue discussions.

**Comment by eatkins** [comment] 2020-11-04 23:08
But thanks for the clue about `-Dsbt.supershell=false`. Now I can reproduce.

**Comment by smarter** [comment] 2020-11-04 23:09
You're welcome. Sorry for my comment, not attempting to be snarky, just personally distressed by the lack of nightlies (I spend a lot of my time worrying about and tracking regressions with sbt).

**Comment by eatkins** [comment] 2020-11-04 23:19
sbt is primarily maintained by just @eed3si9n and me right now. I don't know why nightlies don't work anymore but I believe that in the past they have been built using lightbend infrastructure and neither of us have any affiliation with lightbend.

Also, regarding `-Dsbt.supershell=false`, you might want to give supershell another try in 1.4.x. There were a lot of problems with it in 1.3.x that have been resolved. I won't claim it's perfect, but I think 1.4.x represents significant improvement. Of course the console should still work regardless of whether or not supershell is enabled or disabled but I can imagine why you may have gotten frustrated in the past and gotten in the habit of disabling it (or aliased sbt in your shell).

**Comment by griggt** [comment] 2020-11-04 23:27
Same symptoms here on Debian 10, also with supershell disabled.  First bad commit is 7894938

**Comment by smarter** [comment] 2020-11-04 23:34
> I believe that in the past they have been built using lightbend infrastructure and neither of us have any affiliation with lightbend.

FWIW, in Dotty we publish our nightlies directly to maven in the same way we publish releases and that has worked pretty well for us.

> you might want to give supershell another try in 1.4.x.

Since you're asking me directly, I hope you won't mind a frank answer: I don't think supershell provides a great user experience, I think sbt is already too verbose, making it easy to miss valuable information in the noise, supershell on top of that:
- reduces the amount of output from sbt I can see at the same time
- displays text that blinks in and out, which I find distracting most of the time (although I could see it being useful in some situations)
- means that my prompt doesn't always appear at the bottom of the screen, but some amount of lines above that, which I find disorientating.

Of course that's just my opinion, and I haven't heard anyone else complain about it so maybe I'm just particularly grumpy about changes :).

**Comment by eatkins** [comment] 2020-11-04 23:39
@smarter totally fair about supershell. I agree about the verbosity of sbt in general (as I commented here https://github.com/sbt/sbt/issues/5976#issuecomment-709390486) although I do find supershell useful personally. You had just previously raised an issue about supershell blowing away output in the `run` task and I thought it was possible that was why you disabled it.
@griggt thanks for the pointer to the broken commit

**Comment by griggt** [comment] 2020-11-05 00:03
Also reported yesterday on gitter: [November 3, 2020 2:19 PM](https://gitter.im/sbt/sbt?at=5fa1d76bd5a5a635f29c4f69) on macOS.

**Comment by eatkins** [comment] 2020-11-05 00:12
This should be fixed in #6051 by https://github.com/sbt/sbt/pull/6051/commits/8ff0afe8e698a8025269700d14c63d34e5dccd24 specifically

**Comment by japgolly** [comment] 2020-11-05 00:14
Ahhhh my apologies! I didn't think to look at my env. Like reported above,
I've got this:

SBT_OPTS=-Dsbt.supershell=never

**Comment by eed3si9n** [comment] 2020-11-05 03:07
I've created a new issue about nightlies - https://github.com/sbt/sbt/issues/6062

**Comment by crispywalrus** [comment] 2020-11-05 15:51
It's not just `sbt.supershell`, I see the same behavior for `sbt.color` and `sbt.ci`. If any of those are set the console stops accepting input. FWIW I'm on MacOS 10.15.7 using amazon corretto 8.0.272, amazon corretto 11.0.9, or openjdk 8.0.271.

**Comment by eatkins** [comment] 2020-11-05 18:04
@crispywalrus with color, it's the same underlying issue and is fixed by #6051. Tab completions also didn't really work very well with -Dsbt.color=false and that is fixed by #6068. Running an interactive session with -Dsbt.ci=true is not something I considered but that is fixed in #6067.

**Comment by eed3si9n** [comment] 2020-11-15 20:03
I'm closing this since #6051 / #6067 are merged.

**Closed as completed by eed3si9n** 2020-11-15 20:03 UTC

**Comment by japgolly** [comment] 2020-11-15 22:37
That's great. And thanks for your hard work! I imagine this would've been pretty fiddly to get right on all platforms.

**Comment by olafurpg** [comment] 2020-11-16 07:59
I can confirm that console input is working as expected in 1.4.3. I was hitting on the same issue in 1.4.2 with supershell disabled. The latest sbt versions are really nice, I really appreciate all the thought and work that has gone into improving sbt lately 🙏
