### ISSUE TITLE
Failed to fetch https://dl.bintray.com/sbt/debian/Packages  403  Forbidden

### ISSUE THREAD

**Issue by castroulloaaaron** [sbt/sbt#6449] opened 2021-04-12 20:08 UTC
## steps

Running command: apt-get update --allow-insecure-repositories

## problem

Failed to fetch https://dl.bintray.com/sbt/debian/Packages  403  Forbidden

## expectation

Libraries can be downloaded and installed

## notes

Looks like the repo has some issues:

Reading package lists...

95 | W: The repository 'https://dl.bintray.com/sbt/debian  Release' does not have a Release file.
96 | E: Failed to fetch https://dl.bintray.com/sbt/debian/Packages  403  Forbidden [IP: 52.40.49.72 443]

Getting it on the aws codebuild aws/codebuild/standard:4.0 image

**Comment by kittsville** [comment] 2021-04-12 20:28
This is duplicate of #6445

**Closed as completed** 2021-04-13 17:11 UTC
Labels: area/linux

**Comment by yt1969143065** [comment] 2022-09-01 04:00
echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
sudo apt-get update
sudo apt-get install sbt
