### ISSUE TITLE
sbt fails to install when following 1.0 instructions

### ISSUE THREAD

**Issue by janekdb** [sbt/sbt#3047] opened 2017-03-27 17:09 UTC
(See the guidelines for contributing, linked above)

## steps

Follow instructions to install SBT on http://www.scala-sbt.org/1.0/docs/Installing-sbt-on-Linux.html

## problem

`Unable to locate package sbt`

## expectation

SBT would be installed

## notes

This is the full transcript,

```
deb https://dl.bintray.com/sbt/debian-experimental /
Executing: /tmp/tmp.Ju8tLcsJDF/gpg.1.sh --keyserver
hkp://keyserver.ubuntu.com:80
--recv
642AC823
gpg: requesting key 642AC823 from hkp server keyserver.ubuntu.com
gpg: key 642AC823: public key "sbt build tool <scalasbt@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:2 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu xenial InRelease                                   
Hit:3 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease                                       
Hit:4 http://gb.archive.ubuntu.com/ubuntu xenial InRelease                                                
Get:5 http://gb.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]         
Get:6 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [100 kB]
Get:7 http://gb.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]    
Ign:8 https://dl.bintray.com/sbt/debian-experimental  InRelease                 
Get:9 http://security.ubuntu.com/ubuntu xenial-security/universe i386 Packages [90.2 kB]
Get:10 http://gb.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [498 kB]
Get:11 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [53.2 kB]
Ign:12 https://dl.bintray.com/sbt/debian-experimental  Release                                 
Ign:13 https://dl.bintray.com/sbt/debian-experimental  Packages             
Ign:14 https://dl.bintray.com/sbt/debian-experimental  Translation-en_GB
Ign:15 https://dl.bintray.com/sbt/debian-experimental  Translation-en
Ign:13 https://dl.bintray.com/sbt/debian-experimental  Packages
Ign:14 https://dl.bintray.com/sbt/debian-experimental  Translation-en_GB
Get:16 http://gb.archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages [488 kB]
Ign:15 https://dl.bintray.com/sbt/debian-experimental  Translation-en
Ign:13 https://dl.bintray.com/sbt/debian-experimental  Packages
Ign:14 https://dl.bintray.com/sbt/debian-experimental  Translation-en_GB
Ign:15 https://dl.bintray.com/sbt/debian-experimental  Translation-en
Ign:13 https://dl.bintray.com/sbt/debian-experimental  Packages
Get:17 http://gb.archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [200 kB]
Ign:14 https://dl.bintray.com/sbt/debian-experimental  Translation-en_GB
Ign:15 https://dl.bintray.com/sbt/debian-experimental  Translation-en
Ign:13 https://dl.bintray.com/sbt/debian-experimental  Packages
Get:18 http://gb.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [445 kB]
Ign:14 https://dl.bintray.com/sbt/debian-experimental  Translation-en_GB
Ign:15 https://dl.bintray.com/sbt/debian-experimental  Translation-en
Err:13 https://dl.bintray.com/sbt/debian-experimental  Packages
  404  Not Found
Ign:14 https://dl.bintray.com/sbt/debian-experimental  Translation-en_GB
Ign:15 https://dl.bintray.com/sbt/debian-experimental  Translation-en
Get:19 http://gb.archive.ubuntu.com/ubuntu xenial-updates/universe i386 Packages [434 kB]
Get:20 http://gb.archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [171 kB]
Fetched 2,787 kB in 2s (1,305 kB/s)                            
Reading package lists... Done
W: The repository 'https://dl.bintray.com/sbt/debian-experimental  Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://dl.bintray.com/sbt/debian-experimental/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package sbt
```

**Comment by dwijnand** [comment] 2017-03-27 19:05
We've never released (AFAIK) the deb (or any native package) for 1.0. So I guess you could say the root cause is the 1.0 docs are misleading.

https://github.com/sbt/website/issues/320

We hope to have more 1.0 news soon, but for now I'll close this issue.

**Closed as completed by dwijnand** 2017-03-27 19:05 UTC

**Comment by janekdb** [comment] 2017-03-27 19:24
Okay, cool. I'll use the normal installation technique. Thought I'd found a new way!
