### ISSUE TITLE
[sbt 1.0.0-M6] update caching is still not working

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3226] opened 2017-05-29 00:24 UTC
## steps

```scala
lazy val p1 = project
  .settings(
  )

lazy val p2 = project
  .dependsOn(p1 % "compile;test->test")
  .settings(
    libraryDependencies += zinc,
  )
```

1. compile
2. compile

## problem

I am seeing the following output:

```
> compile
[info] Updating {file:/xxx/}p2...
[warn] Choosing local for org.scala-sbt#zinc_2.12;1.0.0-X16-SNAPSHOT
[warn] Choosing local for org.scala-sbt#zinc-core_2.12;1.0.0-X16-SNAPSHOT
[warn] Choosing local for org.scala-sbt#zinc-apiinfo_2.12;1.0.0-X16-SNAPSHOT
[warn] Choosing local for org.scala-sbt#compiler-interface;1.0.0-X16-SNAPSHOT
[warn] Choosing local for org.scala-sbt#zinc-classfile_2.12;1.0.0-X16-SNAPSHOT
[warn] Choosing local for org.scala-sbt#zinc-classpath_2.12;1.0.0-X16-SNAPSHOT
[warn] Choosing local for org.scala-sbt#zinc-persist_2.12;1.0.0-X16-SNAPSHOT
[warn] Choosing local for org.scala-sbt#zinc-compile-core_2.12;1.0.0-X16-SNAPSHOT
[warn] Choosing local for org.scala-sbt#zinc-ivy-integration_2.12;1.0.0-X16-SNAPSHOT
[info] Done updating.
```

This indicates that the `update` is getting triggered even though the dependency graph has *not* changed.

## expectation

Works like sbt 0.13. Transitive call to `update` task via `compile` the second time should *not* trigger actual resolution (used to be called `doWork`, now called `def resolve`), thus the log should be much less noisier.

Basically it should be:

```
> compile
[success] Total time: 1 s, completed May 28, 2017 8:19:48 PM
> compile
[success] Total time: 0 s, completed May 28, 2017 8:19:49 PM
```

## notes

Original output on sbt:

```
> compile
[info] Updating {file:/xxx/sbt/}sbtRoot...
[info] Updating {file:/xxx/sbt/}testAgentProj...
[info] Updating {file:/xxx/sbt/}bundledLauncherProj...
[info] Updating {file:/xxx/sbt/}coreMacrosProj...
[info] Updating {file:/xxx/sbt/}taskProj...
[info] Updating {file:/xxx/sbt/}protocolProj...
[info] Updating {file:/xxx/sbt/}runProj...
[info] Done updating.
[warn] Choosing local for org.scala-sbt#zinc-classpath_2.12;1.0.0-X16-SNAPSHOT
[warn] Choosing local for org.scala-sbt#compiler-interface;1.0.0-X16-SNAPSHOT
[info] Done updating.
[info] Done updating.
[info] Done updating.
```

**Comment by eed3si9n** [comment] 2017-05-29 05:55
Without fixing this sbt 1.0.0-M5 takes up too much time to do simple `compile` on multi-project builds.

**Comment by jvican** [comment] 2017-05-29 06:15
Can you verify this https://github.com/sbt/librarymanagement/pull/109 fixes it?

**Comment by eed3si9n** [comment] 2017-05-29 06:50
@jvican Will do tomorrow. For now I'm working around using:

```
set skip in update in ThisBuild := true
```

**Comment by eed3si9n** [comment] 2017-05-29 19:02
sbt/librarymanagement#109 didn't seem to fix it.

I've put in this println:

```scala
      println("-------------------------------------------")
      println(s"""upToDate(inChanged = $inChanged, out = ...)
                 |  !force // ${!force}
                 |  && !depsUpdated // ${!depsUpdated}
                 |  && out.allFiles.forall(f => fileUptodate(f, out.stamps)) // ${out.allFiles.forall(f => fileUptodate(f, out.stamps)) }
                 |  && fileUptodate(out.cachedDescriptor, out.stamps)) // ${fileUptodate(out.cachedDescriptor, out.stamps)}
                 |  = $result
                 |""".stripMargin)
```

The output is:

```scala
-------------------------------------------
upToDate(inChanged = false, out = ...)
  !force // true
  && !depsUpdated // false
  && out.allFiles.forall(f => fileUptodate(f, out.stamps)) // true
  && fileUptodate(out.cachedDescriptor, out.stamps)) // true
  = false
```

**Comment by eed3si9n** [comment] 2017-05-29 20:46
Thawed `UpdateReport` needs to be marked as cached. I'll send a PR with the fix.

**Comment by dwijnand** [comment] 2017-07-11 15:27
@eed3si9n Do you have a minimised reproduction? I can't reproduce..

```
> compile
[info] Total time: 0 s, completed 11-Jul-2017 16:26:59
> compile
[info] Total time: 0 s, completed 11-Jul-2017 16:27:00
> p1/compile
[info] Total time: 0 s, completed 11-Jul-2017 16:27:02
> show libraryDependencies
[info] p2/*:libraryDependencies
[info] 	List(org.scala-lang:scala-library:2.12.2, org.scala-sbt:zinc:1.0.0-X16-SNAPSHOT)
[info] p1/*:libraryDependencies
[info] 	List(org.scala-lang:scala-library:2.12.2)
[info] t-2017-07-11-1459/*:libraryDependencies
[info] 	List(org.scala-lang:scala-library:2.12.2)
```

**Comment by eed3si9n** [comment] 2017-07-11 16:21
I can't reproduce it either. Maybe I was getting confused between beta1 and beta2 for some of the modules.

**Comment by dwijnand** [comment] 2017-07-11 20:54
Cool.

**Comment by eed3si9n** [comment] 2017-07-11 20:55
So is https://github.com/sbt/zinc/issues/353 related?

**Comment by jvican** [comment] 2017-07-11 21:23
I think so. I reproduced this issue with Zinc's build.

**Comment by dwijnand** [comment] 2017-07-11 23:02
I'll try and minimise from zinc's build.

**Comment by jvican** [comment] 2017-07-12 09:01
@dwijnand To minimise, run `compile` twice in whichever project, and you'll see `update` kick in always. I've run the command in the `zincPersist` module to confirm this is the case.

**Comment by eed3si9n** [comment] 2017-07-14 04:11
Wrote a plugin to debug this problem - https://gist.github.com/eed3si9n/2dbe452982625fb82a4de74f293344e0

At least for me the problem is really intermittent. It doesn't happen for a while, and then it happens several times in a row.

```
> zincPersist/checkUpdateCache
ModuleSettings doesn't match.
stored = InlineConfiguration(false, Some(IvyScala(2.12.2, 2.12, Vector(), true, false, false, org.scala-lang, Vector(scala-library, scala-compiler, scala-reflect, scala-actors, scalap))), org.scala-sbt:zinc-persist_2.12:1.0.0-X19-SNAPSHOT, ModuleInfo(zinc Persist, Incremental compiler of Scala, Some(https://github.com/sbt/zinc), None, Vector((BSD New,https://github.com/sbt/sbt/blob/0.13/LICENSE)), org.scala-sbt, Some(https://github.com/sbt/zinc), Some(ScmInfo(https://github.com/sbt/zinc, git@github.com:sbt/zinc.git, None)), Vector(Developer(harrah, Mark Harrah, @harrah, https://github.com/harrah), Developer(eed3si9n, Eugene Yokota, @eed3si9n, https://github.com/eed3si9n), Developer(jsuereth, Josh Suereth, @jsuereth, https://github.com/jsuereth), Developer(dwijnand, Dale Wijnand, @dwijnand, https://github.com/dwijnand), Developer(gkossakowski, Grzegorz Kossakowski, @gkossakowski, https://github.com/gkossakowski), Developer(Duhemm, Martin Duhem, @Duhemm, https://github.com/Duhemm))), Vector(org.scala-lang:scala-compiler:2.12.2:scala-tool->default,optional(default), org.scala-lang:scala-library:2.12.2:scala-tool->default,optional(default), org.scala-sbt:zinc-core_2.12:1.0.0-X19-SNAPSHOT, org.scala-sbt:zinc-core_2.12:1.0.0-X19-SNAPSHOT:test->test, org.scala-lang:scala-library:2.12.2, com.geirsson:scalafmt-core_2.11:0.6.8:scalafmt, com.lucidchart:scalafmt-impl:1.3-0.6:scalafmt, org.scalacheck:scalacheck_2.12:1.13.4:test, org.scalatest:scalatest_2.12:3.0.1:test, junit:junit:4.11:test, org.scala-sbt:util-testing_2.12:1.0.0-M26:test, org.scala-sbt:sbinary_2.12:0.4.4), Set(), Vector(), , Vector(compile, runtime, test, provided, optional, compile-internal, runtime-internal, test-internal, plugin, pom, scala-tool, scalafmt), Some(compile), ConflictManager(latest-revision, *, *))
in     = InlineConfiguration(false, Some(IvyScala(2.12.2, 2.12, Vector(), true, false, false, org.scala-lang, Vector(scala-library, scala-compiler, scala-reflect, scala-actors, scalap))), org.scala-sbt:zinc-persist_2.12:1.0.0-X19-SNAPSHOT, ModuleInfo(zinc Persist, Incremental compiler of Scala, Some(https://github.com/sbt/zinc), None, Vector((BSD New,https://github.com/sbt/sbt/blob/0.13/LICENSE)), org.scala-sbt, Some(https://github.com/sbt/zinc), Some(ScmInfo(https://github.com/sbt/zinc, git@github.com:sbt/zinc.git, None)), Vector(Developer(harrah, Mark Harrah, @harrah, https://github.com/harrah), Developer(eed3si9n, Eugene Yokota, @eed3si9n, https://github.com/eed3si9n), Developer(jsuereth, Josh Suereth, @jsuereth, https://github.com/jsuereth), Developer(dwijnand, Dale Wijnand, @dwijnand, https://github.com/dwijnand), Developer(gkossakowski, Grzegorz Kossakowski, @gkossakowski, https://github.com/gkossakowski), Developer(Duhemm, Martin Duhem, @Duhemm, https://github.com/Duhemm))), Vector(org.scala-lang:scala-compiler:2.12.2:scala-tool->default,optional(default), org.scala-lang:scala-library:2.12.2:scala-tool->default,optional(default), org.scala-sbt:zinc-core_2.12:1.0.0-X19-SNAPSHOT, org.scala-sbt:zinc-core_2.12:1.0.0-X19-SNAPSHOT:test->test, org.scala-lang:scala-library:2.12.2, com.geirsson:scalafmt-core_2.11:0.6.8:scalafmt, com.lucidchart:scalafmt-impl:1.3-0.6:scalafmt, org.scalacheck:scalacheck_2.12:1.13.4:test, org.scalatest:scalatest_2.12:3.0.1:test, junit:junit:4.11:test, org.scala-sbt:util-testing_2.12:1.0.0-M26:test, org.scala-sbt:sbinary_2.12:0.4.4), Set(), Vector(), , Vector(compile, runtime, test, provided, optional, compile-internal, runtime-internal, test-internal, plugin, pom, scala-tool, scalafmt), Some(compile), ConflictManager(latest-revision, *, *))
moduleInfo doesn't match.
stored = ModuleInfo(zinc Persist, Incremental compiler of Scala, Some(https://github.com/sbt/zinc), None, Vector((BSD New,https://github.com/sbt/sbt/blob/0.13/LICENSE)), org.scala-sbt, Some(https://github.com/sbt/zinc), Some(ScmInfo(https://github.com/sbt/zinc, git@github.com:sbt/zinc.git, None)), Vector(Developer(harrah, Mark Harrah, @harrah, https://github.com/harrah), Developer(eed3si9n, Eugene Yokota, @eed3si9n, https://github.com/eed3si9n), Developer(jsuereth, Josh Suereth, @jsuereth, https://github.com/jsuereth), Developer(dwijnand, Dale Wijnand, @dwijnand, https://github.com/dwijnand), Developer(gkossakowski, Grzegorz Kossakowski, @gkossakowski, https://github.com/gkossakowski), Developer(Duhemm, Martin Duhem, @Duhemm, https://github.com/Duhemm)))
in     = ModuleInfo(zinc Persist, Incremental compiler of Scala, Some(https://github.com/sbt/zinc), None, Vector((BSD New,https://github.com/sbt/sbt/blob/0.13/LICENSE)), org.scala-sbt, Some(https://github.com/sbt/zinc), Some(ScmInfo(https://github.com/sbt/zinc, git@github.com:sbt/zinc.git, None)), Vector(Developer(harrah, Mark Harrah, @harrah, https://github.com/harrah), Developer(eed3si9n, Eugene Yokota, @eed3si9n, https://github.com/eed3si9n), Developer(jsuereth, Josh Suereth, @jsuereth, https://github.com/jsuereth), Developer(dwijnand, Dale Wijnand, @dwijnand, https://github.com/dwijnand), Developer(gkossakowski, Grzegorz Kossakowski, @gkossakowski, https://github.com/gkossakowski), Developer(Duhemm, Martin Duhem, @Duhemm, https://github.com/Duhemm)))
HList equiv error
[error] (zincPersist/*:checkUpdateCache) Update cache is invalidated: InlineIvyConfiguration(Some(xsbt.boot.Locks$@52068a2e), /Users/eed3si9n/work/sbt-modules/zinc/internal/zinc-persist, sbt.internal.util.ManagedLogger@136ab928, sbt.librarymanagement.UpdateOptions@8335369b, IvyPaths(/Users/eed3si9n/work/sbt-modules/zinc/internal/zinc-persist, Some(/Users/eed3si9n/.ivy2)), Vector(Raw(ProjectResolver(inter-project, mapped: org.scala-sbt#compiler-bridge_2.12;1.0.0-X19-SNAPSHOT, org.scala-sbt#compiler-interface;1.0.0-X19-SNAPSHOT, org.scala-sbt#zinc-classfile_2.12;1.0.0-X19-SNAPSHOT, org.scala-sbt#zinc-classpath_2.12;1.0.0-X19-SNAPSHOT, org.scala-sbt#zinc-apiinfo_2.12;1.0.0-X19-SNAPSHOT, org.scala-sbt#zinc-core_2.12;1.0.0-X19-SNAPSHOT)), FileRepository(local, Patterns(ivyPatterns=Vector(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)(/[branch])/[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)(/[branch])/[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), FileConfiguration(true, None)), public: https://repo1.maven.org/maven2/, FileRepository(local-preloaded-ivy, Patterns(ivyPatterns=Vector(/Users/eed3si9n/.sbt/preloaded/[organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(/Users/eed3si9n/.sbt/preloaded/[organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), FileConfiguration(true, None)), local-preloaded: file:////Users/eed3si9n/.sbt/preloaded/, bintray-sbt-maven-releases: https://dl.bintray.com/sbt/maven-releases/, URLRepository(typesafe-ivy-releases, Patterns(ivyPatterns=Vector(https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)(/[branch])/[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)(/[branch])/[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false)), sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots, bintray-sbt-maven-releases: https://dl.bintray.com/sbt/maven-releases/, URLRepository(bintray-sbt-ivy-snapshots, Patterns(ivyPatterns=Vector(https://dl.bintray.com/sbt/ivy-snapshots/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)(/[branch])/[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(https://dl.bintray.com/sbt/ivy-snapshots/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)(/[branch])/[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false))), Vector(cache:publish-m2-local: /Users/eed3si9n/.m2/repository, Raw(Bintray-Maven-Publish-sbt-maven-releases-zinc)), Vector(), Vector(sha1, md5), false, Some(/Users/eed3si9n/work/sbt-modules/zinc/internal/zinc-persist/target/scala-2.12/resolution-cache)), InlineConfiguration(false, Some(IvyScala(2.12.2, 2.12, Vector(), true, false, false, org.scala-lang, Vector(scala-library, scala-compiler, scala-reflect, scala-actors, scalap))), org.scala-sbt:zinc-persist_2.12:1.0.0-X19-SNAPSHOT, ModuleInfo(zinc Persist, Incremental compiler of Scala, Some(https://github.com/sbt/zinc), None, Vector((BSD New,https://github.com/sbt/sbt/blob/0.13/LICENSE)), org.scala-sbt, Some(https://github.com/sbt/zinc), Some(ScmInfo(https://github.com/sbt/zinc, git@github.com:sbt/zinc.git, None)), Vector(Developer(harrah, Mark Harrah, @harrah, https://github.com/harrah), Developer(eed3si9n, Eugene Yokota, @eed3si9n, https://github.com/eed3si9n), Developer(jsuereth, Josh Suereth, @jsuereth, https://github.com/jsuereth), Developer(dwijnand, Dale Wijnand, @dwijnand, https://github.com/dwijnand), Developer(gkossakowski, Grzegorz Kossakowski, @gkossakowski, https://github.com/gkossakowski), Developer(Duhemm, Martin Duhem, @Duhemm, https://github.com/Duhemm))), Vector(org.scala-lang:scala-compiler:2.12.2:scala-tool->default,optional(default), org.scala-lang:scala-library:2.12.2:scala-tool->default,optional(default), org.scala-sbt:zinc-core_2.12:1.0.0-X19-SNAPSHOT, org.scala-sbt:zinc-core_2.12:1.0.0-X19-SNAPSHOT:test->test, org.scala-lang:scala-library:2.12.2, com.geirsson:scalafmt-core_2.11:0.6.8:scalafmt, com.lucidchart:scalafmt-impl:1.3-0.6:scalafmt, org.scalacheck:scalacheck_2.12:1.13.4:test, org.scalatest:scalatest_2.12:3.0.1:test, junit:junit:4.11:test, org.scala-sbt:util-testing_2.12:1.0.0-M26:test, org.scala-sbt:sbinary_2.12:0.4.4), Set(), Vector(), , Vector(compile, runtime, test, provided, optional, compile-internal, runtime-internal, test-internal, plugin, pom, scala-tool, scalafmt), Some(compile), ConflictManager(latest-revision, *, *)), UpdateConfiguration(None, false, Default, ArtifactTypeFilter(Set(source, javadocs, docs, doc, src, sources, javadoc), true), false, false)
[error] Total time: 0 s, completed Jul 13, 2017 11:52:47 PM
```

Still haven't found the exact root cause, but I think the fact that we are internally using `Equiv` is bad, and we should switch to typeclass-based hasher and persist the hash.

**Comment by dwijnand** [comment] 2017-07-14 10:33
Neat! Thanks.

**Comment by dwijnand** [comment] 2017-07-17 09:52
Fixed with https://github.com/sbt/util/pull/93.

**Closed as completed by dwijnand** 2017-07-17 09:52 UTC
Labels: Regression
