### ISSUE TITLE
SBT launcher fails to download dependencies from repo.scala-sbt.org

### ISSUE THREAD

**Issue by fancywriter** [sbt/sbt#5551] opened 2020-05-12 11:07 UTC
When I am trying to simply run `sbt` it fails to download (tried latest 1.3.10 version) needed dependencies, simply hangs on line
```
[info] [launcher] getting org.scala-sbt sbt 1.3.10  (this may take some time)...
```
Seems that it can't download some dependencies from repo.scala-sbt.org.
```
wget https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/google/protobuf/protobuf-parent/3.7.0/protobuf-parent-3.7.0.jar
--2020-05-12 11:58:44--  https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/google/protobuf/protobuf-parent/3.7.0/protobuf-parent-3.7.0.jar
Resolving repo.scala-sbt.org (repo.scala-sbt.org)... 3.224.199.251, 54.85.165.101, 52.1.64.47
Connecting to repo.scala-sbt.org (repo.scala-sbt.org)|3.224.199.251|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://jenkins.scala-sbt.org/sbt-snapshots/com/google/protobuf/protobuf-parent/3.7.0/protobuf-parent-3.7.0.jar [following]
--2020-05-12 11:58:44--  https://jenkins.scala-sbt.org/sbt-snapshots/com/google/protobuf/protobuf-parent/3.7.0/protobuf-parent-3.7.0.jar
Resolving jenkins.scala-sbt.org (jenkins.scala-sbt.org)... 128.179.67.43
Connecting to jenkins.scala-sbt.org (jenkins.scala-sbt.org)|128.179.67.43|:443... failed: Operation timed out.
Retrying.
```

Are there any mirrors I can use and how to specify them for launcher?

**Comment by hxtpoe** [comment] 2020-05-12 12:06
I'm having similar issue. 

On https://gitter.im/sbt/sbt @raboof suggested a dirty workaround to add ```127.0.0.1 jenkins.scala-sbt.org``` to /etc/hosts

**Comment by raboof** [comment] 2020-05-12 12:30
That workaround should not be needed anymore - we applied a workaround at our side so things should work for everyone again, but you might see "You probably access the destination server through a proxy server that is not well configured." and "Host jenkins.scala-sbt.org not found" warnings.

We're still working on fixing the issue properly, after that these warnings should go away again.

**Comment by raboof** [comment] 2020-05-12 12:39
> We're still working on fixing the issue properly, after that these warnings should go away again.

The warnings should now be gone again, too. Thanks for bearing with us!

**Comment by fancywriter** [comment] 2020-05-12 12:46
@hxtpoe @raboof I also applied another workaround with replacing `sbt.boot.properties` file, though it is a kind of overkill, what would be enough to simply replace one or two repo variables...

**Comment by raboof** [comment] 2020-05-12 12:48
> replacing `sbt.boot.properties` file

That's also a possibility indeed, and more elegant than my /etc/hosts cannon. Neither should be needed anymore, though.

**Comment by raboof** [comment] 2020-05-13 08:46
I think we can close this issue, #5458 covers the root cause.

**Closed as completed** 2020-05-13 10:17 UTC
Labels: area/proxy
