### ISSUE TITLE
Munit - test filtering doesn't work when ScalaTest is present in the same project

### ISSUE THREAD

**Issue by VlachJosef** [sbt/sbt#6412] opened 2021-03-22 22:56 UTC
## steps

Having this `build.sbt`

```scala
lazy val root = project
  .in(file("."))
  .settings(
    name := "Munit + ScalaTest",
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % "3.2.2"  % Test,
      "org.scalameta" %% "munit"     % "0.7.22" % Test
      )
  )
```

And test file `src/test/scala/example/Spec.scala`
```scala
package example

import munit.FunSuite

class Spec extends FunSuite {
  test("hello") {
    assertEquals(1, 1)
  }
}
```

## problem

When trying to run munit spec with test [filtering](https://scalameta.org/munit/docs/filtering.html)

```
root/testOnly example.Spec -- "--tests=hello"
```

ScalaTest's Runner is throwing and `IllegalArgumentException` and test is never run.

```
[error] (Test / testOnly) java.lang.IllegalArgumentException: Argument unrecognized by ScalaTest's Runner: --tests=hello
```

## expectation

ScalaTest's Runner shouldn't throw an exception and Munit Runner should be able to run the test.

## note

Tested in `1.4.9` and `1.5.0-RC2`

**Comment by eed3si9n** [comment] 2021-03-24 04:00
@VlachJosef Thanks for the report!

I wonder how we're creating the runners to ask for the list of test suites.. Here's `testOnly`'s implementation where it grabs the user-supplied argument as "options":

https://github.com/sbt/sbt/blob/3e125fa040d64dfb3b2a3bdd59f5e62c7bd08ffb/main/src/main/scala/sbt/Defaults.scala#L1404-L1410

Eventually these are fed to `createTestRunners` I think:

https://github.com/sbt/sbt/blob/3e125fa040d64dfb3b2a3bdd59f5e62c7bd08ffb/main/src/main/scala/sbt/Defaults.scala#L1430-L1443

So to find out if we have MUnit or ScalaTest test suites, we need to create test runners for them, and currently the way it works is that we pass the arguments to create the test runners, I think. So in one sense, everything is working as designed / intended. Maybe you could ask ScalaTest to delay the evaluation of argument parsing?

**Comment by eed3si9n** [comment] 2021-03-28 20:40
Fixed in https://github.com/sbt/sbt/pull/6418

**Closed as completed by eed3si9n** 2021-03-28 20:40 UTC
Labels: area/test_framework
