### ISSUE TITLE
Update doesn't seem to respect cross-versions, tries to resolve snapshot

### ISSUE THREAD

**Issue by travisbrown** [sbt/sbt#4181] opened 2018-06-02 23:03 UTC
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps

Have the following `build.sbt`:
```scala
val root = project.in(file(".")).aggregate(a, b)

lazy val a = project.in(file("a")).settings(
  scalaVersion := "2.12.6",
  crossScalaVersions := Seq("2.11.12", "2.12.6")
)

lazy val b = project.in(file("b")).settings(
  scalaVersion := "2.12.6",
  crossScalaVersions := Seq("2.12.6")
).dependsOn(a)
```
And a `project/build.properties` using a 1.x version (I've tried 1.1.6 and 1.0.5).
## problem
Running `sbt update` with `++2.11.12` blows up:
```
update-repro sbt ++2.11.12 update
[info] Loading settings from gpg.sbt ...
[info] Loading global plugins from /Users/travisbrown/.sbt/1.0/plugins
[info] Loading project definition from /Users/travisbrown/tmp/update-repro/project
[info] Loading settings from build.sbt ...
[info] Set current project to root (in build file:/Users/travisbrown/tmp/update-repro/)
[info] Setting Scala version to 2.11.12 on 1 projects.
[info] Excluded 2 projects, run ++ 2.11.12 -v for more details.
[info] Reapplying settings...
[info] Set current project to root (in build file:/Users/travisbrown/tmp/update-repro/)
[info] Updating a...
[info] Updating ...
[info] Done updating.
[info] Updating b...
[info] Done updating.
[warn] 	module not found: a#a_2.12;0.1.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/travisbrown/.ivy2/local/a/a_2.12/0.1.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/a/a_2.12/0.1.0-SNAPSHOT/a_2.12-0.1.0-SNAPSHOT.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/travisbrown/.sbt/preloaded/a/a_2.12/0.1.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/travisbrown/.sbt/preloaded/a/a_2.12/0.1.0-SNAPSHOT/a_2.12-0.1.0-SNAPSHOT.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: a#a_2.12;0.1.0-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		a:a_2.12:0.1.0-SNAPSHOT
[warn] 		  +- b:b_2.12:0.1.0-SNAPSHOT
[error] sbt.librarymanagement.ResolveException: unresolved dependency: a#a_2.12;0.1.0-SNAPSHOT: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
...
[error] (b / update) sbt.librarymanagement.ResolveException: unresolved dependency: a#a_2.12;0.1.0-SNAPSHOT: not found
[error] Total time: 2 s, completed Jun 2, 2018 3:57:46 PM
```
## expectation

`update` shouldn't try to resolve a snapshot and should just work.

## notes

When I asked about this [on Gitter](https://gitter.im/sbt/sbt?at=5b125680edd06f7d1502d545), @dwijnand said it looked like a bug. I did a quick search and wasn't able to find it, but there are 749 open issues so ¯\_(ツ)_/¯.

sbt version: 1.1.6, 1.0.5.

**Comment by eed3si9n** [comment] 2018-06-14 08:34
@travisbrown Thanks for the report! I think we've all ran into something similar where part of the subproject is in one scalaVersion, and the other subproject depending on it still thinks its in 2.12.6, so it blows up. The fact that it's reported now is good, because I already have a proposal for something like this. Check out https://discuss.lightbend.com/t/spatial-representation-of-cross-building/1277/2

Using projectMatrix, we should be able to address this because `aJVM2_11` and `aJVM2_12` would just be different subprojects.

**Comment by xerial** [comment] 2018-06-15 05:02
@eed3si9n I had the same issue when cross building projects for multiple Scala versions: An example build failure: https://travis-ci.org/wvlet/airframe/jobs/392496005

~This problem disappeared after downgrading from sbt 1.1.6 to 1.1.5.~
It seems its is not specific to sbt 1.1.6 because the same error happens sporadically even if I use sbt 1.1.5. But it happens only when I building projects with Scala 2.13.0-M3, 2.11.11, Scala.js, etc. + sbt 1.1.x
https://travis-ci.org/wvlet/airframe/builds/392561721

**Comment by eed3si9n** [comment] 2018-08-15 16:13
I think this is a duplicate of https://github.com/sbt/sbt/issues/3465

The workaround is:

```scala
val root = project.in(file("."))
  .aggregate(a, b)
  .settings(crossScalaVersions := List()) // add this line
```

**Closed as completed by eed3si9n** 2018-08-15 16:13 UTC
Labels: area/library_management, area/cross_building
