### ISSUE TITLE
I tried to install sbt on high sierra, 

### ISSUE THREAD

**Issue by BassirouRabo** [sbt/sbt#3856] opened 2018-01-06 17:08 UTC
## steps
I have installed the build tool using : "brew install sbt" , after that i tried to run the sbt on "./.brew/Cellar/sbt/1.1.0/bin/sbt

## problem

```
java.io.IOException: Operation not supported
	at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:90)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1115)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:88)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at xsbt.boot.Launch.locked(Launch.scala:238)
	at xsbt.boot.Launch.app(Launch.scala:147)
	at xsbt.boot.Launch.app(Launch.scala:145)
	at xsbt.boot.Launch$.run(Launch.scala:102)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.io.IOException: Operation not supported
```

## notes

sbt version: *1.1*

**Comment by eed3si9n** [comment] 2018-01-06 22:22
I can't reproduce this problem on my machine.
What do you see when you type `java -version`?

 ```
$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by BassirouRabo** [comment] 2018-01-06 22:36
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

**Comment by eed3si9n** [comment] 2018-01-07 02:54
Are you working on a shared drive? https://bugs.openjdk.java.net/browse/JDK-8193594

**Comment by akauppi** [comment] 2018-01-28 18:39
I'm noticing two things:

- Your HomeBrew is installed to a non-standard location (`~/.brew`). That should be okay, but most installations are to the default `/usr/local`.
- You are launching the inner `sbt` command, instead of the wrapper that's normally used. e.g. for me:

```
$ which sbt
/usr/local/bin/sbt
$ more /usr/local/bin/sbt 
#!/bin/sh
if [ -f "$HOME/.sbtconfig" ]; then
  echo "Use of ~/.sbtconfig is deprecated, please migrate global settings to /usr/local/etc/sbtopts" >&2
  . "$HOME/.sbtconfig"
fi
exec "/usr/local/Cellar/sbt/1.1.0/libexec/bin/sbt" "$@"
```

What does your `which sbt` say? 

Try launching `./.brew/bin/sbt`.

In addition, it's good to run "brew doctor" from time to time, to see that HomeBrew itself if feeling okay.

**Comment by BassirouRabo** [comment] 2018-01-28 18:45
./brew/bin/sbt is just a link to (sbt -> ../Cellar/sbt/1.1.0/bin/sbt)
When i run it i got he same error

**Comment by BassirouRabo** [comment] 2018-01-28 19:22
how can we relink sbt to /usr/local

**Comment by akauppi** [comment] 2018-01-29 12:14
Oh, you are right.

>how can we relink sbt to /usr/local

It would mean re-installing HomeBrew. It's not as bad as it sounds; I do that often.

Before that, I would advice to:

- `brew update; brew upgrade`
- `brew doctor`
- `brew uninstall sbt; brew install sbt`

You can also do `brew cleanup`, but that should simply remove unused packages.

**Comment by dwijnand** [comment] 2018-02-06 14:53
Duplicate of #2222.

**Closed as completed by dwijnand** 2018-02-06 14:53 UTC
Labels: needs info
