### ISSUE TITLE
SBT 1.4.1 prints Compilation failed in shell, that is unnecessary and too verbose

### ISSUE THREAD

**Issue by zzvara** [sbt/sbt#6002] opened 2020-10-21 08:59 UTC
## steps

`sbt ~test:compile` for example

## problem

Even if there is only one compilation error, SBT prints unnecessary stacktrace of the compiler as follows:

```
[error] Compilation failed
[error]         at xsbt.CachedCompiler0.handleErrors(CompilerBridge.scala:183)
[error]         at xsbt.CachedCompiler0.run(CompilerBridge.scala:172)
[error]         at xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
[error]         at xsbt.CompilerBridge.run(CompilerBridge.scala:39)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:92)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.sca
la:185)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:240)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.sca
la:175)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingComp
iler.scala:156)
[error]         at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:232)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:1
56)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:203)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompil
erImpl.scala:571)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(Increment
alCompilerImpl.scala:571)
[error]         at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
[error]         at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
[error]         at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:459)
[error]         at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error]         at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error]         at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
[error]         at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
[error]         at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
[error]         at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
[error]         at sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scal
a:571)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalC
ompilerImpl.scala:489)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerIm
pl.scala:332)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl
.scala:419)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2139)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2099)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:40)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:23)
[error]         at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2096)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scal
a:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (core / Compile / compileIncremental) Compilation failed
[error] Total time: 12 s, completed Oct 21, 2020 10:55:31 AM

```

## expectation

It should be turned off by default.

**Comment by eatkins** [comment] 2020-10-21 14:47
I don't personally love this behavior but when you run `sbt ~test:compile`, you are running sbt in batch mode rather than as an interactive shell. In batch mode, sbt will always print the full stacktrace of any errors. The reason for this default is that in batch mode, there is no opportunity to print the full stacktrace using the last command. I would still probably not print the full stacktrace by default even in batch mode, but it has been that way for a long time and changing it would probably affect others who rely on that behavior.

One workaround if you are using sbt 1.4.x is `sbt --client ~test:compile` or `sbtn ~test:compile` if you've installed sbtn. Another workaround is to run just `sbt` and then run `> ~test:compile` in the shell prompt.

**Comment by zzvara** [comment] 2020-10-21 17:32
@eatkins SBT never behaved like this before.

Using `sbt --client ~test:compile`, the output is the following:

```
J[0J[[0J0[0JJ[0J0[0J[0J[[0J0[0JJ[0JJ[0J[0J[[0J0[0JJ[0Jg[0J[0J[[0J
[0JJ[0J[0J[0J[[0J0[0JJ[0J[0J[0J[[0J0[0JJ[0J[[0J[0J[[0J0
0JJ[0J0[0J[0J[[0J0[0JJ[0JJ[0J[0J[[0J0[0JJ[0Ju[0J[0J[[0J0[0JJ[0J[0
[0J[[0J0[0JJ[0J[[0J[0J[[0J0[0J[[0J0[0JJ[0J[0J[0J[[0J0[0
J[0J[[0J[0J[[0J0[0JJ[0J0[0J[0J[[0J0[0JJ[0JJ[0J[0J[[0J0[0JJ[0J[[0J
0J[[0J0[0JJ[0J[0J[0J[[0J0[0JJ[00J0[0JJ[0Jm[0J[0J[[0J0[0
J[0J[0J[0J[[0J0[0JJ[0J[[0J0[0JJ[0J[[0J[0J[[0J0[0JJ[0J[0J[0J
[0J0[0JJ[0J[[0J[0J[[0J0[0JJ0[0J[0J
[0J0[0JJ[0JJ[0J[0J[[0J0[0JJ[0JJ[0J[0J[[0J0[0JJ[0J[0J[0J[[0J0[0JJ[
[0J[0J[[0J0[0JJ[0J[0J[0J
[0J[0J[[0J0[0JJ[0J[0J[0J[[0J0[0JJ[0J[[0J[0J[[0J0[0JJ[0J0[0J[0J[[0
0[0JJ[0JJ[0J[0J[[0J0[0J0J[0J[0J[[0J0[0JJ[0J[[
J[0J[[0J0[0JJ[0J0[0J[0J[[0J0[0JJ[0JJ[0J[0J[[0J0[0JJ[0J[[0J[0J[[0J
[0JJ[0J[0J[0J[[0J0[0JJ[0J[[0J[0J[[0J0[0JJ[0J0[0J[0J[[0J0[0JJ[0JJ[
J[0J[[0J0[0JJ[0J0[[0J[[0J0[0JJ[0J[[0J[0J[[0J0[0JJ[0J0[0J
0J[[0J0[0JJ[0JJ[0J[0J[[0J0[0JJ[J[0J[0J[[0J0[0JJ[0J0[0J
0J[[0J0[0JJ[0J[0J[0J[[0J0[0JJ[0J[[0J[0J[[0J0[0JJ[0J0[0J[0J[[0J0[0
J[0JJ[0J[0J[[0J0[0JJ[0Jm[0J[0J[[0J0[0JJ[0J[0J[0J[[0J0[0JJ[0J[[0J[
J[[
```

**Comment by eatkins** [comment] 2020-10-21 18:17
I was mistaken about the stacktrace behavior in 1.3.x vs 1.4.x. When I run run `sbt compile` (note there is no `~` in the command) in a project with a compilation error in sbt 1.3.13, only the compilation error is shown, not the full stack trace. In 1.4.0 and 1.4.1, the stacktrace is shown after the compilation error.

@zzvara I can't reproduce the output that you reported with `sbt --client`. Have you upgraded the launcher script to 1.4.1 (as opposed to just updating the project/build.properties)? What os and shell are you using?

@eed3si9n I removed the area/watch tag because the underlying issue is not actually related to watch but is a problem with the error output when sbt is started in batch mode.

**Comment by zzvara** [comment] 2020-10-21 18:30
@eatkins I upgraded SBT using Scoop on Windows 10 (regularly updated). I noticed the strange output `[0J0[0JJ` behavior in both IntelliJ terminal and PowerShell. I can't get any useful output when using `sbt --client`.

Batch incremental development became harder since to get an actual useful output, one has to scroll up a lot. @eatkins do you think that the compilation error's stack trace should be removed?

**Comment by eatkins** [comment] 2020-10-21 18:36
Oh, `sbt --client` seems to have problems with windows. There should be a platform specific installation of `sbtn` in the scoop bin folder that will probably work better.

I do agree that the compilation error stack traces should be removed since they weren't present before and they are not useful at all.

**Comment by zzvara** [comment] 2020-10-21 19:02
@eatkins actually, I'm getting the same `[0J0[0JJ` output with SBT 1.4.1 using `sbt --client ~test:compile` in WSL. Maybe worths a separate issue?

Good to hear, hopefully, this output will get fixed next patch release.

**Comment by eatkins** [comment] 2020-10-21 19:07
Yes, a separate issue for that would be good. Is the output ok if you run `$HOME\scoop\apps\sbt\1.4.1\bin\sbtn-x86_64-pc-win32.exe` (assuming your scoop install is in the default loation)? That would be useful information for the ticket.

**Comment by eatkins** [comment] 2020-10-21 19:58
Should be fixed by https://github.com/sbt/zinc/pull/935

**Comment by eatkins** [comment] 2020-10-22 02:44
It looks like there is already an issue about the `sbt --client` output: https://github.com/sbt/sbt/issues/5928

**Closed as completed by eatkins** 2020-10-22 02:44 UTC
