### ISSUE TITLE
publishM2 does not overwrite existing snapshots

### ISSUE THREAD

**Issue by johanandren** [sbt/sbt#1966] opened 2015-04-10 13:37 UTC
### Steps
1. Create an empty project, set name, organization and a snapshot version, 
2. fire up sbt 0.13.8 and perform publishM2
3. wait for a minute
4. publishM2 again - watch the merry publish output which states that everything went fine
5. look at the artifacts in your local maven repo (will be the ones first published)
### Problems

I have just traced publishM2 into `sbt.ConvertResolver.put()` which accepts an overwrite boolean, which is sent in correctly, but then on [ConvertResolver.scala:256](https://github.com/sbt/sbt/blob/0.13/ivy/src/main/scala/sbt/ConvertResolver.scala#L256) `FileUtil.copy(source, file, progress)` which in turn calls another copy method which takes an overwrite flag and uses a hardcoded false.

**Comment by dwijnand** [comment] 2015-04-10 14:23
Duplicate of #1960

**Closed as completed** 2015-04-10 14:30 UTC
