### ISSUE TITLE
sbt evicted should account for maven dependency version ranges

### ISSUE THREAD

**Issue by alexklibisz** [sbt/sbt#7495] opened 2024-02-14 23:11 UTC
Some java libraries specify a dependency on a range of versions using typical ex/inclusive range notation, e.g., `[1.2.3,1.4.0)`

These docs seem to describe it: https://www.mojohaus.org/versions/versions-maven-plugin/examples/resolve-ranges.html

When we depend on libraries that do this, we can end up with spurious errors like this:

```
[error]         * io.grpc:grpc-core:1.54.2 (strict?) is selected over [1.54.2]
[error]             +- com.lightbend.akka.grpc:akka-grpc-runtime_2.13:2.3.4 (depends on 1.54.2)
[error]             +- io.grpc:grpc-netty-shaded:1.54.2                   (depends on [1.54.2])
```

akka-grpc-runtime depends on `1.54.2`. grpc-netty-shaded depends on `[1.54.2]`. I don't know why they denoted the dependency with range brackets, but they did.

It would be great if SBT could account for this and determine that it's not actually an eviction.

**Comment by eed3si9n** [comment] 2024-02-15 02:14
This sounds more like a Coursier reporting issue? Could you report it to courier as well plz?

**Comment by SethTisue** [comment] 2024-02-15 19:52
Is it a duplicate of #5261?

**Comment by alexklibisz** [comment] 2024-02-17 05:48
Yep, looks like a duplicate of that one. Feel free to close and keep tracking there.

**Closed as duplicate** 2024-02-17 16:13 UTC
