### ISSUE TITLE
Cannot handle ${packaging.type} variable

### ISSUE THREAD

**Issue by Iacob** [sbt/sbt#3618] opened 2017-10-06 17:22 UTC
## steps

Add following line to build.sbt

```scala
libraryDependencies += "org.glassfish.jersey.core" % "jersey-server" % "2.26"
```

## problem

When building the project, sbt throwing the following error message and quit:

```
Error:Error while importing SBT project:
[warn] 	[FAILED     ] javax.ws.rs#javax.ws.rs-api;2.1!javax.ws.rs-api.${packaging.type}:  (0ms)
```

## expectation

`${packaging.type}` should be correctly handled, the correct value is "jar".

## notes

using sbt 1.0.2

**Comment by eed3si9n** [comment] 2017-10-07 00:12
<s>
Here's a workaround that you can add to `build.sbt`:

```scala
val workaround = {
  sys.props += "packaging.type" -> "jar"
  ()
}
```

I found this on https://github.com/ronmamo/reflections/issues/169
</s>

**Edit**: See an improved workaround https://github.com/sbt/sbt/issues/3618#issuecomment-424924293

**Comment by Iacob** [comment] 2017-10-07 07:13
Thank you very much, that's solved my problem.

**Comment by xmariachi** [comment] 2018-04-26 14:57
This workaround works strangely for me: first time does not, second time works. This is very ugly - especially for a Docker installation I'm preparing. 

I apply the workaround proposed here.

My dependency line: 

    "javax.ws.rs" % "javax.ws.rs-api" % "2.1"

I begin with non-existent   ~/.ivy2/cache/javax.ws.rs/javax.ws.rs-api directory. 

First time I run it, I still get the error:

    $ sbt assembly 
    ... 
    sbt.librarymanagement.ResolveException: download failed: javax.ws.rs#javax.ws.rs-api;2.1!javax.ws.rs-api.${packaging.type}

So it fails, but it creates some files in the corresponding directory: 
 
    $ ls   ~/.ivy2/cache/javax.ws.rs/javax.ws.rs-api/
    ivy-2.1.xml
    ivy-2.1.xml.original
    ivydata-2.1.properties

And, the next run of sbt assembly, it goes through, downloading the files into jars dir inside the above directory: 

    $ ls   ~/.ivy2/cache/javax.ws.rs/javax.ws.rs-api/jars
    javax.ws.rs-api-2.1.jar

The same happens with sbt package (just in case it has to do with assembly plugin). 
Any hints or ideas?

**Comment by ablx** [comment] 2018-07-03 15:01
This still happens in sbt 1.1.0 - any version available where this is fixed?

**Comment by ablx** [comment] 2018-08-15 07:57
@eed3si9n this bug is not fixed (see comment from @xmariachi )
Can you please reopen it?

**Comment by dougjanzen** [comment] 2018-08-15 16:41
Adding an explicit dependency on javax.ws.rs-api like this worked for me:

libraryDependencies += "javax.ws.rs" % "javax.ws.rs-api" % "2.1" artifacts( Artifact("javax.ws.rs-api", "jar", "jar"))

I tried the workaround mentioned earlier that sets sys.props and also found that it worked sometimes but not always.

**Comment by ablx** [comment] 2018-08-15 17:18
Thanks @dougjanzen 
I "fixed" it by calling `sbt compile` twice in gitlab-ci, however I'd prefer a working version :-)

**Comment by chrisalbright** [comment] 2018-09-20 20:23
Getting this when adding `libraryDependencies += "org.apache.kafka" %% "kafka-streams-scala" % "2.0.0" withSources()` to my project.

Workaround from above works for me - but definitely sucks.

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: javax.ws.rs#javax.ws.rs-api;2.1!javax.ws.rs-api.${packaging.type}
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[error] sbt.librarymanagement.ResolveException: download failed: javax.ws.rs#javax.ws.rs-api;2.1!javax.ws.rs-api.${packaging.type}
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2550)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (update) sbt.librarymanagement.ResolveException: download failed: javax.ws.rs#javax.ws.rs-api;2.1!javax.ws.rs-api.${packaging.type}
```

**Comment by mrt181** [comment] 2018-09-25 13:56
I have the same error with sbt 1.2.3 when depending on kafka-streams

**Comment by eed3si9n** [comment] 2018-09-27 01:20
I wonder if there's some evaluation ordering issue.

Could you try

```scala
libraryDependencies += {
  sys.props += "packaging.type" -> "jar"
  "org.apache.kafka" %% "kafka-streams-scala" % "2.0.0" withSources() 
}
```

**Comment by eed3si9n** [comment] 2018-09-27 01:28
The other workaround might be to make an ad-hoc AutoPlugin.


### project/PackagingTypePlugin.scala

```scala
import sbt._

object PackagingTypePlugin extends AutoPlugin {
  override val buildSettings = {
    sys.props += "packaging.type" -> "jar"
    Nil
  }
}
```

The above works for me.

**Comment by hsc-afk** [comment] 2018-09-29 02:43
@eed3si9n 
> import sbt._ object PackagingTypePlugin extends AutoPlugin { override val buildSettings = { sys.props += "packaging.type" -> "jar" Nil } }


/code/build.sbt:3: error: illegal start of simple expression
object PackagingTypePlugin extends AutoPlugin {
^
[error] Error parsing expression.  Ensure that there are no blank lines within a setting.

**Comment by eed3si9n** [comment] 2018-09-29 06:17
@l0n3r4n83r You need to create it at `project/PackagingTypePlugin.scala`, not `build.sbt`.

**Comment by vitojeng** [comment] 2018-10-23 14:43
> ### project/PackagingTypePlugin.scala
> ```scala
> import sbt._
> 
> object PackagingTypePlugin extends AutoPlugin {
>   override val buildSettings = {
>     sys.props += "packaging.type" -> "jar"
>     Nil
>   }
> }
> ```
> 
> The above works for me.

@eed3si9n This work for me, too. Thanks!

**Comment by eed3si9n** [comment] 2018-10-23 15:08
ok. I am closing this issue then.

**Comment by mtekp** [comment] 2018-11-19 07:43
> val workaround = { sys.props += "packaging.type" -> "jar" () }

This worked for me. The improved workaround did not work aroud.

**Comment by jonaf** [comment] 2018-12-03 17:57
FWIW, the problem exists in sbt 0.13.x and none of the proposed workarounds fix it (except for compiling twice). I had to upgrade to sbt 1.x (1.2.7 in my case) in order for the problem to be resolved, which works without *any* of the provided workarounds. I suspect since the original issue was encountered in sbt 1.0.2, that somewhere between 1.0.3 and 1.2.7 the issue itself was fixed, though I don't see any direct reference to this issue from any version of sbt released since 1.0.2. In any case, for others who may find themselves running up against this in the future, the problem cannot be worked around in sbt 0.13.x. Don't waste your time, just go ahead and upgrade. If you must upgrade to a version earlier than 1.2.7 for some reason, then one or more of the above workarounds may work, but by 1.2.7, the issue appears to have been resolved (I did not test any intermediate versions).

**Comment by Hashtagin** [comment] 2018-12-19 14:37
Having strange behavior. Having project with the project/PackagingTypePlugin.scala workaround working fine in windows. But when trying to compile it into a docker container using debian, problem raise again. I check the autoplugin, and it's loaded correctly. I tried 2 manners to install sbt ( by download 1.2.7 package and by using apt-get install), and nothing more happens.

This is my dockerfile

`
FROM openjdk:11.0.1-slim
RUN apt-get update && apt-get install -y curl zip
RUN cd ~ && curl -L https://piccolo.link/sbt-1.2.7.zip --output ~/sbt-1.2.7.zip
RUN unzip ~/sbt-1.2.7.zip -d / && ls -al /sbt && export PATH=/sbt/bin:$PATH && rm ~/sbt-1.2.7.zip
RUN /sbt/bin/sbt "exit"
RUN mkdir -p /ftp && cd /ftp ## && rm -Rvf project/target target project/project
WORKDIR /ftp
COPY . /ftp
RUN /sbt/bin/sbt publish
`
and these libraries used : 
`

libraryDependencies ++= {
  Seq(
    "com.github.nscala-time" %% "nscala-time" % "2.14.0",
    "org.scala-lang" % "scala-xml" % "2.11.0-M4",
    "com.typesafe.scala-logging"   %% "scala-logging-slf4j" % "2.1.2",
    "org.apache.kafka" % "connect-api" % kafkaVersion % "provided",
    "org.scalatest" %% "scalatest" % "3.0.1" % "test"
  )
}
`
Do you have any idea of what to check in order to understand the problem ?
TY

**Comment by ennru** [comment] 2018-12-20 10:38
The workaround [above](https://github.com/sbt/sbt/issues/3618#issuecomment-424924293) makes Travis consistently fail on the first try for us in [Alpakka Kafka](https://github.com/akka/alpakka-kafka).
Re-triggering the build step resolves that.

Same error as earlier.
```
[info] Done compiling.
[error] sbt.librarymanagement.ResolveException: download failed: javax.ws.rs#javax.ws.rs-api;2.1!javax.ws.rs-api.${packaging.type}
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
```

**Comment by Hashtagin** [comment] 2019-01-03 09:23
> The workaround [above](https://github.com/sbt/sbt/issues/3618#issuecomment-424924293) makes Travis consistently fail on the first try for us in [Alpakka Kafka](https://github.com/akka/alpakka-kafka).
> Re-triggering the build step resolves that.
> 
> Same error as earlier.
> 
> ```
> [info] Done compiling.
> [error] sbt.librarymanagement.ResolveException: download failed: javax.ws.rs#javax.ws.rs-api;2.1!javax.ws.rs-api.${packaging.type}
> [error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
> ```

@ennru 
Thanks you, running second time works great.

**Comment by halfninja** [comment] 2019-01-07 15:58
I think this needs to be reopened because neither workaround works with an unpopulated Ivy cache - `rm -rf ~/.ivy2/cache/javax.ws.rs/ && ./sbt update` will fail every time, and if you're doing CI against a cluster of build agents with different Ivy caches it's not practical to keep rerunning the build.

I don't think either workaround form works better or worse than the other, it's just people running before or after the Ivy cache has been populated.

**Comment by erikvanoosten** [comment] 2019-01-10 15:51
Another work around: switch to the new maven location of `javax.ws.rs-api` which is `jakarta.ws.rs/jakarta.ws.rs-api`, these poms use a regular packaging type.

**Comment by erikvanoosten** [comment] 2019-01-10 15:54
Its not clear to me how to apply the workaround for dependencies of sbt plugins. Can any one shed a light on that?

Things I tried:
• put mentioned `PackagingTypePlugin` in `~/project/project`
• put a line with `val workaround = { sys.props += "packaging.type" -> "jar" }` at the top of `~/project/plugins.sbt`
• exclude the javax.ws.rs dependency from the plugin's pom
• the same for each transient dependency that depends on javax.ws.rs

**Comment by erikvanoosten** [comment] 2019-01-11 10:10
I have settled for downloading the javax.ws.rs' pom and put it in ~/.m2/repository with a little shell script.

**Comment by lavrov** [comment] 2019-01-15 12:03
> I think this needs to be reopened because neither workaround works with an unpopulated Ivy cache - `rm -rf ~/.ivy2/cache/javax.ws.rs/ && ./sbt update` will fail every time, and if you're doing CI against a cluster of build agents with different Ivy caches it's not practical to keep rerunning the build.
> 
> I don't think either workaround form works better or worse than the other, it's just people running before or after the Ivy cache has been populated.

I can confirm that. We use the workaround in our CI pipelines and it fails if ivy cache is empty.

**Comment by halfninja** [comment] 2019-01-15 19:54
@erikvanoosten you can exclude a transitive dependency from another dependency with `exclude()`, then add the replacement yourself.

```
libraryDependencies ++= Seq(
  "org.apache.tika" % "tika-parsers" % "1.20" exclude("javax.ws.rs", "javax.ws.rs-api"),
  "jakarta.ws.rs" % "jakarta.ws.rs-api" % "2.1.4"
)
```

Alternatively, if like in my case you have multiple libraries pulling in `javax.ws.rs-api` and you don't have the time or patience to sift through them all, you can apply the exclusion to every dependency:

```
libraryDependencies ++= Seq(
  "org.apache.jclouds.api" % "filesystem" % "2.1.1",
  "org.apache.tika" % "tika-parsers" % "1.20",
  "jakarta.ws.rs" % "jakarta.ws.rs-api" % "2.1.4"
).map(_ exclude("javax.ws.rs", "javax.ws.rs-api"))
```

The [dependency graph plugin](https://github.com/jrudolph/sbt-dependency-graph) is useful for working out what's pulling it in.

**Comment by edmondop** [comment] 2019-01-17 14:23
@lavrov what sort of workaround do you have for your CI?

**Comment by erikvanoosten** [comment] 2019-01-17 18:12
@halfninja Thanks! Unfortunately it doesn't help. Coursier insists on downloading the jakarta.ws.rs pom (and only the pom), even though it is not needed.

This is the workaround we use in our CI (bash) script:

    if [ ! -f ~/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.pom ]; then
      mkdir -p ~/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1
      curl -k http://central.maven.org/maven2/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.pom > ~/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.pom
    fi

Don't forget to update the link so that it points to your local maven proxy.

**Comment by lavrov** [comment] 2019-01-18 13:26
> @lavrov what sort of workaround do you have for your CI?

@edmondo1984 
`-Dpackaging.type=jar` in `.sbtopts`

**Comment by tpanagos** [comment] 2019-02-08 19:39
> libraryDependencies ++= Seq(
>   "org.apache.jclouds.api" % "filesystem" % "2.1.1",
>   "org.apache.tika" % "tika-parsers" % "1.20",
>   "jakarta.ws.rs" % "jakarta.ws.rs-api" % "2.1.4"
> ).map(_ exclude("javax.ws.rs", "javax.ws.rs-api"))

I tried all the above. Putting this (or something like it) into my build.sbt file is the only work-around that fixed the problem BOTH my local build (OSX) and on CircleCI (Linux).

**Comment by GratefulTony** [comment] 2019-04-18 21:41
> > @lavrov what sort of workaround do you have for your CI?
> 
> @edmondo1984
> `-Dpackaging.type=jar` in `.sbtopts`

this worked for my ci build in aws. I passed the option directly to sbt in my build script.

**Comment by levinson** [comment] 2019-06-07 23:20
As a workaround exclude the busted dependency:
```
    excludeDependencies ++= Seq(
      // workaround for https://github.com/sbt/sbt/issues/3618
      // include "jakarta.ws.rs" % "jakarta.ws.rs-api" instead
      ExclusionRule("javax.ws.rs", "javax.ws.rs-api"),
    )
```

... and add a working alternative:
```
libraryDependencies += "jakarta.ws.rs" % "jakarta.ws.rs-api" % "2.1.5"
```

**Comment by MartensYM** [comment] 2019-06-24 13:30
> 
> 
> As a workaround exclude the busted dependency:
> 
> ```
>     excludeDependencies ++= Seq(
>       // workaround for https://github.com/sbt/sbt/issues/3618
>       // include "jakarta.ws.rs" % "jakarta.ws.rs-api" instead
>       ExclusionRule("javax.ws.rs", "javax.ws.rs-api"),
>     )
> ```
> 
> ... and add a working alternative:
> 
> ```
> libraryDependencies += "jakarta.ws.rs" % "jakarta.ws.rs-api" % "2.1.5"
> ```

This worked for me, thanks!

**Comment by ches** [comment] 2019-07-02 18:14
It sounds like upstream Ivy _might_ have [fixed this in a proper way][1] in Ivy 2.5.0-rc1. sbt's Ivy fork appears woefully far behind that, and it's not likely to be a trivial backport 😞 

[1]: https://issues.apache.org/jira/browse/IVY-1577

**Comment by anilkumarmyla** [comment] 2019-07-05 21:50
sbt 1.3.x switches from ivy to coursier for dependency management, so expect this to be resolved in 1.3.x series

**Comment by VillenaDeveloper** [comment] 2019-09-06 14:06
> As a workaround exclude the busted dependency:
> 
> ```
>     excludeDependencies ++= Seq(
>       // workaround for https://github.com/sbt/sbt/issues/3618
>       // include "jakarta.ws.rs" % "jakarta.ws.rs-api" instead
>       ExclusionRule("javax.ws.rs", "javax.ws.rs-api"),
>     )
> ```
> 
> ... and add a working alternative:
> 
> ```
> libraryDependencies += "jakarta.ws.rs" % "jakarta.ws.rs-api" % "2.1.5"
> ```

Thanks for this. Good workaround.

**Comment by anilkumarmyla** [comment] 2019-09-06 18:33
This is fixed in sbt-1.3.0 unless you've opted out of coursier

**Comment by eed3si9n** [comment] 2019-09-06 18:52
Confirmed using sbt 1.3.0:

```
sbt:foo> update
[info] Updating
https://repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.26/jersey-server-2.26.pom
  100.0% [##########] 10.8 KiB (24.4 KiB / s)
https://repo1.maven.org/maven2/org/glassfish/jersey/project/2.26/project-2.26.pom
  100.0% [##########] 83.8 KiB (829.2 KiB / s)
https://repo1.maven.org/maven2/org/glassfish/hk2/hk2-bom/2.5.0-b42/hk2-bom-2.5.0-b42.pom
  100.0% [##########] 16.0 KiB (380.2 KiB / s)
https://repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.26/jersey-client-2.26.pom
  100.0% [##########] 7.2 KiB (164.3 KiB / s)
https://repo1.maven.org/maven2/org/glassfish/jersey/media/jersey-media-jaxb/2.26/jersey-media-jaxb-2.26.pom
  100.0% [##########] 6.6 KiB (106.4 KiB / s)
https://repo1.maven.org/maven2/org/glassfish/hk2/external/javax.inject/2.5.0-b42/javax.inject-2.5.0-b42.pom
  100.0% [##########] 6.3 KiB (78.3 KiB / s)
https://repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-common/2.26/jersey-common-2.26.pom
  100.0% [##########] 9.6 KiB (115.6 KiB / s)
https://repo1.maven.org/maven2/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.pom
  100.0% [##########] 29.5 KiB (297.9 KiB / s)
https://repo1.maven.org/maven2/org/glassfish/hk2/external/2.5.0-b42/external-2.5.0-b42.pom
  100.0% [##########] 2.8 KiB (64.5 KiB / s)
https://repo1.maven.org/maven2/org/glassfish/jersey/media/project/2.26/project-2.26.pom
  100.0% [##########] 3.2 KiB (69.5 KiB / s)
https://repo1.maven.org/maven2/org/glassfish/hk2/hk2-parent/2.5.0-b42/hk2-parent-2.5.0-b42.pom
  100.0% [##########] 41.4 KiB (845.5 KiB / s)
[info] Resolved  dependencies
[info] Fetching artifacts of
https://repo1.maven.org/maven2/org/glassfish/hk2/external/javax.inject/2.5.0-b42/javax.inject-2.5.0-b42.jar
  100.0% [##########] 5.8 KiB (52.4 KiB / s)
https://repo1.maven.org/maven2/org/glassfish/jersey/media/jersey-media-jaxb/2.26/jersey-media-jaxb-2.26.jar
  100.0% [##########] 70.2 KiB (444.2 KiB / s)
https://repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.26/jersey-client-2.26.jar
  100.0% [##########] 177.2 KiB (575.5 KiB / s)
https://repo1.maven.org/maven2/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar
  100.0% [##########] 124.5 KiB (210.0 KiB / s)
https://repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.26/jersey-server-2.26.jar
  100.0% [##########] 898.6 KiB (946.9 KiB / s)
https://repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-common/2.26/jersey-common-2.26.jar
  100.0% [##########] 1.1 MiB (856.9 KiB / s)
[info] Fetched artifacts of
[success] Total time: 2 s, completed Sep 6, 2019 2:51:52 PM
```

**Closed as completed by eed3si9n** 2019-09-06 18:52 UTC
Labels: area/library_management, area/maven_integration

**Comment by howardrotterdam** [comment] 2019-12-05 15:18
> This is fixed in sbt-1.3.0 unless you've opted out of coursier

But Coursier has random failure problem when used in a corporate intranet with authenticated artifactory server, so we have to stick to Ivy.  So I vote on https://github.com/sbt/sbt/issues/3618#issuecomment-455545444 to be best simple work around.

**Comment by anilkumarmyla** [comment] 2019-12-06 07:15
@howardrotterdam open source software works best when you report bugs/issues to the software in question. Did you file an issue on coursier for the same?

**Comment by minnieshi** [comment] 2020-09-11 09:39
I use sbt 1.3.8, it has the same problem.

**Comment by mkharytonau** [comment] 2020-10-02 13:06
Faced the same issue with sbt 1.3.13, removing sbt-coursier plugin solved this.
