### ISSUE TITLE
Publishing don't work with 0.13.2-M3

### ISSUE THREAD

**Issue by aloiscochard** [sbt/sbt#1186] opened 2014-03-17 11:59 UTC
If you remove that commit from this branch:
https://github.com/drjuma/drscala/commit/964fa8adef3a5920c368dfa12cfb04faa7a81df2

SBT does not publish the artifact (but return no error)... I had to downgrade... but with 0.13.1 the command `last` don't work.

Do you guys actually have some form of regression testing?

Such regression in critical part like publishing and exception report is somewhat embarrassing.

**Comment by jsuereth** [comment] 2014-03-17 12:02
This is a duplicate, fixed in master.

**Comment by jsuereth** [comment] 2014-03-17 12:44
Duplicate of #1156

Turns out our tests for publishing weren't catching this particular regression.  There was a specific mechanism of defining builds which caused it and our ivy tests do not use it.

If you wish to contribute more tests to the regression suite, please do.  This type of bug is a blocker for a release.  If you can try the nightly, and let us know of things are working, please do.

**Closed as completed** 2014-03-17 12:44 UTC

**Comment by aloiscochard** [comment] 2014-03-17 17:23
Good to hear there is actually tests for that.
I gave the nightly a try and it work fine (I should have try before reporting...).

But when it comes to tests... I'm afraid I'll never spent time writing SBT tests on my spare time, I'm happy to isolate and report bugs though... 

But even during work hours writing tests is such a torment, that there is no such I spent my free time on it :-)

**Comment by jsuereth** [comment] 2014-03-17 17:27
Our tests are just mininal sbt projects.  Those are more than fine.

Sorry the issue hit you.  Given the significant features in 0.13.2 I'm
worried about squashing all regressions that may have popped up.

There's a few codepaths that aren't hit in our regression suite that I
missed.  If see more, please report.
