### ISSUE TITLE
"The compiler bridge sources ... could not be could not be retrieved"

### ISSUE THREAD

**Issue by mrt181** [sbt/sbt#6072] opened 2020-11-06 15:05 UTC
## steps

start sbt (using https://github.com/coursier/sbt-extras in WSL on windows 10)
```sbt
> ⋯ > mrt181 > bookstore > | master > 6700603 > ./sbt                                                                                                                                                                                            
[info] welcome to sbt 1.4.2 (Ubuntu Java 11.0.9)
[info] loading settings for project orderbookstore-build from plugins.sbt ...
[info] loading project definition from /mnt/c/Users/mrt181/bookstore/project
[info] loading settings for project root from build.sbt ...
[info] set current project to orderbook-store (in build file:/mnt/c/Users/mrt181/bookstore/)
[warn] sbt server could not start because there's another instance of sbt running on this build.
[warn] Running multiple instances is unsupported
sbt:orderbook-store> compile
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] compiling 134 Scala sources to /mnt/c/Users/mrt181/bookstore/target/scala-2.13/classes ...
[info] Attempting to fetch org.scala-sbt:compiler-bridge_2.13:1.4.2.
[info] Updating
[info] Resolved  dependencies
[error] ## Exception when compiling 134 sources to /mnt/c/Users/mrt181/bookstore/target/scala-2.13/classes
[error] sbt.internal.inc.InvalidComponent: The compiler bridge sources CoursierModuleDescriptor(ModuleDescriptorConfiguration(false, None, org.scala-sbt.temp:temp-module-52f238aede5a1d8d7a484c2bec27a144810e2ac0:1.4.2:compile, ModuleInfo(temp-module-52f238aede5a1d8d7a484c$
bec27a144810e2ac0, , None, None, Vector(), , None, None, Vector()), Vector(org.scala-sbt:compiler-bridge_2.13:1.4.2:compile), Vector(), Vector(), , Vector(compile, runtime, test, provided, optional), Some(compile), ConflictManager(latest-revision, *, *)),CoursierConfigur$
tion(Some(sbt.internal.util.ManagedLogger@220dfb2c), Vector(FileRepository(local, Patterns(ivyPatterns=Vector(///home/mrt181/.ivy2//local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), ar$
ifactPatterns=Vector(///home/mrt181/.ivy2//local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), FileConfigu$
ation(true, None)), cache:Maven2 Local: /home/mrt181/.m2/repository, URLRepository(ivy-nexus2, Patterns(ivyPatterns=Vector(http://repo.own.com:8080/nexus/content/groups/ivy/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-$
classifier]).[ext]), artifactPatterns=Vector(http://repo.own.com:8080/nexus/content/groups/ivy/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipCo$
sistencyCheck=false), true), URLRepository(ivy-nexus2-public, Patterns(ivyPatterns=Vector(http://repo.own.com:8080/nexus/content/groups/public/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactP$
tterns=Vector(http://repo.own.com:8080/nexus/content/groups/public/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), true)$
 URLRepository(ivy-nexus2-internal, Patterns(ivyPatterns=Vector(http://repo.own.com:8080/nexus/content/repositories/internal/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(htt$
://repo.own.com:8080/nexus/content/repositories/internal/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), true), URLRepos$
tory(ivy-nexus2-snapshots, Patterns(ivyPatterns=Vector(http://repo.own.com:8080/nexus/content/repositories/snapshots/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(http://repo$
own.com:8080/nexus/content/repositories/snapshots/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), true), maven-nexus2-pu$
lic: http://repo.own.com:8080/nexus/content/groups/public/, maven-nexus2-internal: http://repo.own.com:8080/nexus/content/repositories/internal/, maven-nexus2-snapshots: http://repo.own.com:8080/nexus/content/repositories/snapshots/), 6, 100, Some(org.scala-lang), Some(2$
12.12), Vector(/home/mrt181/.sbt/boot/scala-2.12.12/lib/jansi.jar, /home/mrt181/.sbt/boot/scala-2.12.12/lib/jline.jar, /home/mrt181/.sbt/boot/scala-2.12.12/lib/scala-compiler.jar, /home/mrt181/.sbt/boot/scala-2.12.12/lib/scala-library.jar, /home/mrt181/.sbt/boot/sca$
a-2.12.12/lib/scala-reflect.jar, /home/mrt181/.sbt/boot/scala-2.12.12/lib/scala-xml_2.12.jar), Vector(), Vector(), Vector(), true, false, Vector(), Vector(), Some(org.scala-lang), Some(2.13.3), Vector(), Vector(DirectCredentials(repo.own.com, SRV_OWN_BUILD, ****, S$
me(Sonatype Nexus Repository Manager), true, true, false)), None, Some(/home/mrt181/.cache/coursier/v1), Some(/home/mrt181/.ivy2), None, None, Vector(), Vector(), Vector((ModuleMatchers(Set(), Set(), true),Relaxed)), true, 0, Some(24 hours), Vector(Some(SHA-1), None), $
ector(LocalUpdateChanging, LocalOnly, Update), false, false, false)) could not be retrieved.
[error]
[error]         Note: Unresolved dependencies path:
[error] sbt.internal.inc.ZincLMHelper$.update(ZincComponentCompiler.scala:318)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3(ZincComponentCompiler.scala:274)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3$adapted(ZincComponentCompiler.scala:267)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:490)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:500)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$2(ZincComponentCompiler.scala:267)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.util.BufferedLogger.bufferQuietly(BufferedLogger.scala:159)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1(ZincComponentCompiler.scala:267)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1$adapted(ZincComponentCompiler.scala:264)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:490)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:500)
[error] sbt.internal.inc.ZincComponentCompiler.compileAndInstall(ZincComponentCompiler.scala:264)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compiledBridgeJar$1(ZincComponentCompiler.scala:232)
[error] sbt.internal.inc.IfMissing$Define.run(IfMissing.scala:19)
[error] sbt.internal.inc.ZincComponentManager.createAndCache$1(ZincComponentManager.scala:49)
[error] sbt.internal.inc.ZincComponentManager.$anonfun$files$3(ZincComponentManager.scala:60)
[error] sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:42)
[error] sbt.internal.inc.ZincComponentManager.$anonfun$files$2(ZincComponentManager.scala:60)
[error] sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:89)
[error] xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] xsbt.boot.Using$.withResource(Using.scala:10)
[error] xsbt.boot.Using$.apply(Using.scala:9)
[error] xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] xsbt.boot.Locks$.apply(Locks.scala:28)
[error] sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:89)
[error] sbt.internal.inc.ZincComponentManager.$anonfun$lockSecondaryCache$1(ZincComponentManager.scala:86)
[error] scala.Option.map(Option.scala:230)
[error] sbt.internal.inc.ZincComponentManager.lockSecondaryCache(ZincComponentManager.scala:86)
[error] sbt.internal.inc.ZincComponentManager.fromSecondary$1(ZincComponentManager.scala:58)
[error] sbt.internal.inc.ZincComponentManager.$anonfun$files$6(ZincComponentManager.scala:64)
[error] sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:42)
[error] sbt.internal.inc.ZincComponentManager.$anonfun$files$5(ZincComponentManager.scala:64)
[error] sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:89)
[error] xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] xsbt.boot.Using$.withResource(Using.scala:10)
[error] xsbt.boot.Using$.apply(Using.scala:9)
[error] xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] xsbt.boot.Locks$.apply(Locks.scala:28)
[error] sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:89)
[error] sbt.internal.inc.ZincComponentManager.lockLocalCache(ZincComponentManager.scala:82)
[error] sbt.internal.inc.ZincComponentManager.files(ZincComponentManager.scala:64)
[error] sbt.internal.inc.ZincComponentManager.file(ZincComponentManager.scala:70)
[error] sbt.internal.inc.ZincComponentCompiler.compiledBridgeJar(ZincComponentCompiler.scala:232)
[error] sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.compiledBridge(ZincComponentCompiler.scala:76)
[error] sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.fetchCompiledBridge(ZincComponentCompiler.scala:82)
[error] sbt.internal.inc.AnalyzingCompiler.getLoader(AnalyzingCompiler.scala:342)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:88)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:232)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:573)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:573)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:459)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:573)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:491)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2176)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2133)
[error] sbt.internal.io.Retry$.apply(Retry.scala:40)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2129)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] java.base/java.lang.Thread.run(Thread.java:834)
[error]
[error] stack trace is suppressed; run last Compile / compileIncremental for the full output
```

## problem

Something related to dependency resolution with couriser does not work

## expectation

normal compilation without any error like with sbt `1.3.13`

## notes
I added `,allowInsecureProtocol` to each remote entry in my repositories file and `.withAllowInsecureProtocol(true)` to my publish url when tryin out `1.4.2`.
I get the same error with `1.4.1`

**Comment by eed3si9n** [comment] 2020-11-08 17:06
Looks like the key error is here where it's failing to retrieve the compiler bridge sources.

```
[error] ## Exception when compiling 134 sources to /mnt/c/Users/mrt181/bookstore/target/scala-2.13/classes
[error] sbt.internal.inc.InvalidComponent: The compiler bridge sources CoursierModuleDescriptor(ModuleDescriptorConfiguration(false, None, org.scala-sbt.temp:temp-module-52f238aede5a1d8d7a484c2bec27a144810e2ac0:1.4.2:compile, ModuleInfo(temp-module-52f238aede5a1d8d7a484c$
bec27a144810e2ac0, , None, None, Vector(), , None, None, Vector()), Vector(org.scala-sbt:compiler-bridge_2.13:1.4.2:compile), Vector(), Vector(), , Vector(compile, runtime, test, provided, optional), Some(compile), ConflictManager(latest-revision, *, *)),CoursierConfigur$
tion(Some(sbt.internal.util.ManagedLogger@220dfb2c), Vector(FileRepository(local, Patterns(ivyPatterns=Vector(///home/mrt181/.ivy2//local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), ar$
ifactPatterns=Vector(///home/mrt181/.ivy2//local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), FileConfigu$
ation(true, None)), cache:Maven2 Local: /home/mrt181/.m2/repository, URLRepository(ivy-nexus2, Patterns(ivyPatterns=Vector(http://repo.own.com:8080/nexus/content/groups/ivy/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-$
classifier]).[ext]), artifactPatterns=Vector(http://repo.own.com:8080/nexus/content/groups/ivy/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipCo$
sistencyCheck=false), true), URLRepository(ivy-nexus2-public, Patterns(ivyPatterns=Vector(http://repo.own.com:8080/nexus/content/groups/public/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactP$
tterns=Vector(http://repo.own.com:8080/nexus/content/groups/public/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), true)$
 URLRepository(ivy-nexus2-internal, Patterns(ivyPatterns=Vector(http://repo.own.com:8080/nexus/content/repositories/internal/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(htt$
://repo.own.com:8080/nexus/content/repositories/internal/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), true), URLRepos$
tory(ivy-nexus2-snapshots, Patterns(ivyPatterns=Vector(http://repo.own.com:8080/nexus/content/repositories/snapshots/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(http://repo$
own.com:8080/nexus/content/repositories/snapshots/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), true), maven-nexus2-pu$
lic: http://repo.own.com:8080/nexus/content/groups/public/, maven-nexus2-internal: http://repo.own.com:8080/nexus/content/repositories/internal/, maven-nexus2-snapshots: http://repo.own.com:8080/nexus/content/repositories/snapshots/), 6, 100, Some(org.scala-lang), Some(2$
12.12), Vector(/home/mrt181/.sbt/boot/scala-2.12.12/lib/jansi.jar, /home/mrt181/.sbt/boot/scala-2.12.12/lib/jline.jar, /home/mrt181/.sbt/boot/scala-2.12.12/lib/scala-compiler.jar, /home/mrt181/.sbt/boot/scala-2.12.12/lib/scala-library.jar, /home/mrt181/.sbt/boot/sca$
a-2.12.12/lib/scala-reflect.jar, /home/mrt181/.sbt/boot/scala-2.12.12/lib/scala-xml_2.12.jar), Vector(), Vector(), Vector(), true, false, Vector(), Vector(), Some(org.scala-lang), Some(2.13.3), Vector(), Vector(DirectCredentials(repo.own.com, SRV_OWN_BUILD, ****, S$
me(Sonatype Nexus Repository Manager), true, true, false)), None, Some(/home/mrt181/.cache/coursier/v1), Some(/home/mrt181/.ivy2), None, None, Vector(), Vector(), Vector((ModuleMatchers(Set(), Set(), true),Relaxed)), true, 0, Some(24 hours), Vector(Some(SHA-1), None), $
ector(LocalUpdateChanging, LocalOnly, Update), false, false, false)) could not be retrieved.
```

At this point, I'm not sure if there's much we can do on this issue. There are too many things going on and it's hard to tell what's happening.

For instance, does this happen with simple 1 file Hello World project, or does it require the "bookstore" project?
Does it work from Windows 10 console without WSL? Is https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.13/1.4.2/compiler-bridge_2.13-1.4.2-sources.jar equivalent reachable via http://repo.own.com:8080?

**Comment by eed3si9n** [comment] 2020-11-08 17:31
There's a report saying publishing with HTTP doesn't work https://github.com/sbt/sbt/issues/6038, so I wonder if this issue is also hitting similar issue.

**Comment by nemoo** [comment] 2020-12-30 10:45
I get a similar/same error with a play framework app.

1)
ubuntu using sbt 1.4.4 :

 sbt ~run:
...
	Note: Unresolved dependencies path:]
	at play.sbt.run.PlayReload$.$anonfun$taskFailureHandler$1(PlayReload.scala:42)
	at scala.Option.map(Option.scala:230)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:35)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:28)
	at play.sbt.run.PlayReload$.$anonfun$compile$3(PlayReload.scala:63)
	at scala.util.Either$LeftProjection.map(Either.scala:573)
	at play.sbt.run.PlayReload$.compile(PlayReload.scala:63)
	at play.sbt.run.PlayRun$.$anonfun$playRunTask$4(PlayRun.scala:78)
	at play.runsupport.Reloader.$anonfun$reload$1(Reloader.scala:496)
	at play.runsupport.Reloader$$anon$1.run(Reloader.scala:57)
Caused by: sbt.internal.inc.InvalidComponent: The compiler bridge sources CoursierModuleDescriptor(ModuleDescriptorConfiguration(false, None, org.scala-sbt.temp:temp-module-52f238aede5a1d8d7a484c2bec27a144810e2ac0:1.4.3:compile, ModuleInfo(temp-module-52f238aede5a1d8d7a484c2bec27a144810e2ac0, , None, None, Vector(), , None, None, Vector()), Vector(org.scala-sbt:compiler-bridge_2.13:1.4.3:compile), Vector(), Vector(), , Vector(compile, runtime, test, provided, optional), Some(compile), ConflictManager(latest-revision, *, *)),CoursierConfiguration(Some(sbt.internal.util.ManagedLogger@3925ea2a), Vector(Raw(ProjectResolver(inter-project, mapped: org.scala-sbt#global-plugins;0.0)), public: https://repo1.maven.org/maven2/, FileRepository(local, Patterns(ivyPatterns=Vector(///home/myuser/.ivy2//local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(///home/myuser/.ivy2//local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), FileConfiguration(true, None)), URLRepository(my-ivy-proxy, Patterns(ivyPatterns=Vector(https://bin.company.com/artifactory/sbt/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(https://bin.company.com/artifactory/sbt/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), false), my-maven-proxy: https://bin.company.com/artifactory/sbt/, URLRepository(sbt-plugin-releases, Patterns(ivyPatterns=Vector(https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), false), URLRepository(typesafe-alt-ivy-releases, Patterns(ivyPatterns=Vector(https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), false)), 6, 100, Some(org.scala-lang), Some(2.12.12), Vector(/home/myuser/.sbt/boot/scala-2.12.12/lib/scala-library.jar, /home/myuser/.sbt/boot/scala-2.12.12/lib/jline.jar, /home/myuser/.sbt/boot/scala-2.12.12/lib/scala-reflect.jar, /home/myuser/.sbt/boot/scala-2.12.12/lib/scala-compiler.jar, /home/myuser/.sbt/boot/scala-2.12.12/lib/jansi.jar, /home/myuser/.sbt/boot/scala-2.12.12/lib/scala-xml_2.12.jar), Vector(), Vector(), Vector(), true, false, Vector(), Vector(), Some(org.scala-lang), Some(2.13.4), Vector(), Vector(), None, Some(/home/myuser/.cache/coursier/v1), Some(/home/myuser/.ivy2), None, None, Vector(), Vector(), Vector((ModuleMatchers(Set(), Set(), true),Relaxed)), true, 0, Some(24 hours), Vector(Some(SHA-1), None), Vector(LocalUpdateChanging, LocalOnly, Update), false, false, false)) could not be retrieved.

2)
ubuntu using sbt 1.3.13:
the build works fine.

3)
windows using sbt 1.4.4 :
the build works fine.

So that makes me think of some proxy configuration problem? It is a pity that we do not have a more detailed error message.

**Comment by eed3si9n** [comment] 2021-05-02 17:10
Closing this since I'm guessing it's caused by unofficial launcher.

**Closed as completed by eed3si9n** 2021-05-02 17:10 UTC
Labels: needs info, Regression, area/windows, area/linux
