### ISSUE TITLE
Keyboard input is supressed when creating a new project using sbt new

### ISSUE THREAD

**Issue by rodrigovedovato** [sbt/sbt#5095] opened 2019-09-18 15:22 UTC
## Steps
- sbt version: 1.3.0
- Ubuntu 18.04.3

1. Create a new project using `sbt new`, e.g. `sbt new scala/scala-seed.g8`
2. When it prompts for the project name, type anything (e.g. sample)

## Problem

Keyboard input is supressed, but the project is created with the name you just typed

## Expectation

I should be able to see what I'm typing

## Notes

![ezgif com-gif-maker](https://user-images.githubusercontent.com/2046725/65161896-c15cea00-da0e-11e9-9fda-55f29dd5ee21.gif)

**Comment by eed3si9n** [comment] 2019-09-18 15:44
@rodrigovedovato Thanks for the report! (Love the screencaps)
This looks like a duplicate of #5063 so I am closing this.

**Closed as completed by eed3si9n** 2019-09-18 15:44 UTC
