### ISSUE TITLE
Why sbt 0.10.x or 0.11.x doesn't provide project structure skeleton setups like 0.7.x?

### ISSUE THREAD

**Issue by fujohnwang** [sbt/sbt#205] opened 2011-09-26 14:08 UTC
please see here 
http://www.quora.com/Why-sbt-0-10-x-or-0-11-x-doesnt-provide-project-structure-skeleton-setups-like-0-7-x?__snids__=25909251

**Comment by harrah** [comment] 2011-09-26 22:56
Duplicate of #56.  Please use the mailing list for questions.

**Closed as completed by harrah** 2011-09-26 22:56 UTC
Labels: not-a-🐛
