### ISSUE TITLE
Ability to cancel a long running task

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [sbt/sbt#2190] opened 2015-09-01 07:15 UTC
Sometimes I task takes too long or it has been invoked with the wrong parameters.

If I try to cancel it with Ctrl+C under Linux, the taks is cancelled, but SBT is also killed.  Restarting SBT implies spending an additional minute in startup time.

How can I abort a long running process and keep SBT alive?

**Comment by eed3si9n** [comment] 2015-09-01 10:17
Duplicate of #228

**Closed as completed by eed3si9n** 2015-09-01 10:17 UTC
