### ISSUE TITLE
Address already in use: JVM_Bind

### ISSUE THREAD

**Issue by Enalmada** [sbt/sbt#3707] opened 2017-11-02 17:17 UTC
After upgrading to 1.0.2, I see this error occasionally at the end of starting sbt.
> [error] server failed to start on 127.0.0.1:4697. java.net.BindException: Address already in use: JVM_Bind

Seems like it usually happens when I have just stopped then restarted sbt so I assume something is still running for a moment even though it appears sbt has exited.  Is this a bug or expected behavior?

Full log for context:
> C:\Users\Adam\code\gell\gell>sbt
> [info] Loading settings from plugins.sbt ...
> [info] Loading project definition from C:\Users\Adam\code\gell\gell\project
> [info] Loading settings from build.sbt ...
> error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.27/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
> [info] Set current project to gell (in build file:/C:/Users/Adam/code/gell/gell/)
> [info] Set current project to gell (in build file:/C:/Users/Adam/code/gell/gell/)
> [error] server failed to start on 127.0.0.1:4697. java.net.BindException: Address already in use: JVM_Bind
> [gell] $

**Comment by laughedelic** [comment] 2017-11-03 12:31
Related: https://github.com/sbt/sbt/issues/3437

**Comment by dwijnand** [comment] 2017-12-19 08:45
Sounds duplicate of #3176.

**Closed as completed by dwijnand** 2017-12-19 08:45 UTC
Labels: Duplicate

**Comment by Enalmada** [comment] 2017-12-19 22:58
This might be a dupe of #3176 but I will just point out an important difference here.  #3176 is clearly about forced exit not cleaning something up: sbt, kill sbt (ie quit sbt without exit), sbt.

In this ticket, I am getting the error after a proper exit from shell.  My use case is that I start up sbt, do a "dependencyUpdates" command, increment my 3rd party component versions in build.sbt, exit sbt properly, and restart sbt.

Now that I think about it...I am totally guessing here...but I have Intelij open to update my build.sbt dependencies and it actually might be doing something internally on file save with sbt to fetch the new versions after I update my build.sbt file so when I restart my sbt on the console, there is actually some sbt process legitimately running?

**Comment by dwijnand** [comment] 2017-12-20 07:14
Yes, I kind of cheated by calling this a duplicate even though (as you rightly point out) the use cases are a bit different. The reason I did this is because the general area is influx currently, see for instance the hours-recent https://github.com/sbt/sbt/pull/3828 PR. I think when the dust settles all these similar issues can be closed.
