### ISSUE TITLE
ClassCastException when autoplugins are involved

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#1770] opened 2014-12-11 19:29 UTC
I tried to upgrade sbt-idea to sbt-pgp 1.0.0 but I ran into:

```
java.lang.ClassCastException
    at java.lang.Class.cast(Class.java:3047)
    at sbt.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:20)
    at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
    at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
    at scala.collection.immutable.Stream.map(Stream.scala:376)
    at sbt.ModuleUtilities$.getCheckedObjects(ModuleUtilities.scala:23)
    at sbt.PluginDiscovery$.loadModules(PluginDiscovery.scala:129)
    at sbt.PluginDiscovery$.binarySourceModules(PluginDiscovery.scala:123)
    at sbt.PluginDiscovery$.discover$1(PluginDiscovery.scala:28)
    at sbt.PluginDiscovery$.discoverAll(PluginDiscovery.scala:37)
    at sbt.Load$.loadPlugins(Load.scala:833)
    at sbt.Load$.loadPluginDefinition(Load.scala:790)
    at sbt.Load$.buildPlugins(Load.scala:785)
    at sbt.Load$.plugins(Load.scala:773)
    at sbt.Load$.loadUnit(Load.scala:431)
```

You can reproduce the failure by checking out https://github.com/gkossakowski/sbt-idea/tree/upgrade-sbt-and-plugins

This has been discovered while trying to fix scala/community-builds#83

**Comment by gkossakowski** [comment] 2014-12-11 19:29
Any workarounds would be highly appreciated.

**Comment by jsuereth** [comment] 2014-12-12 00:29
Global user plugin vs. Local.  Your global user directory has a stale version which is hijacking the claspath.

We had a community fix around this issue, but it's a known thing with global plugins.

**Comment by gkossakowski** [comment] 2014-12-12 11:54
Thanks for the hint. That was it!

I'll leave it open in case you guys would like to investigate improving the error message. Adding names of types involved in the cast would be a good start.

**Comment by joescii** [comment] 2015-04-13 14:46
I just hit this problem and likewise resolved it by commenting-out my global `sbt-pgp`.  I'm blaming the jerk that wrote that particular free plugin.

**Comment by jsuereth** [comment] 2015-04-13 14:56
@joescii yeah, that dude is pretty annoying.   Also, unintended consequences of upgrades.... yay.  Didn't mean to break everyone.

**Comment by jrudolph** [comment] 2015-09-05 07:33
I got a similar problem when building a new version of sbt-revolver and spent a few hours debugging what's going on.

In my case the problem was not related to a conflict between locally or globally defined plugins, but the `ClassCastException` would occur in a completely clean environment as well.

The problem is that when you convert a plugin from a `Plugin` to a `AutoPlugin` you may still end up publishing an old `sbt/sbt.plugins` file which wrongly specifies your new and fresh `AutoPlugin` to be just a `Plugin` which leads to the above error message.

I cannot comment on whether previous occurrences of this problem mentioned in this ticket are related to this problem but it may very well be.

The bug here is that whatever generates the `sbt/sbt.plugins` and `sbt/sbt.autoplugins` files does not make sure to cleanup old files which do not represent the actual status of the project any more.

A further annoyance is that the exception thrown from `discover` does not include the reason for the problem: it includes the information that a plugin was expected to be a `Plugin` but not why, i.e. because it was specified in `sbt/sbt.plugins`.

**Comment by eed3si9n** [comment] 2015-09-05 07:34
@jrudolph Thanks for the detective work!

**Comment by eed3si9n** [comment] 2018-09-01 00:49
I am going to close this since it's likely no longer relevant.

**Closed as completed by eed3si9n** 2018-09-01 00:49 UTC
