### ISSUE TITLE
value value is not a member of sbt.TaskKey

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [sbt/sbt#4020] opened 2018-03-16 07:52 UTC
## steps

I modified my `buid.sbt` and added new taskdefs.
If necessary, I can provide privately all my `build.sbt`.

## problem

This works:
```
val testsSikuli = taskKey[Map[String, Array[String]]]("Tests disponibles de Sikuli")
testsSikuli := {
   .....
}

val testsSikuli2 = taskKey[Iterable[String]]("")
testsSikuli2 := testsSikuli.value.values.flatten
```

But if I add brackets it doesn't:
```
val testsSikuli2 = taskKey[Iterable[String]]("")
testsSikuli2 := { testsSikuli.value.values.flatten }
```

In this way it works again:
```
val testsSikuli2 = taskKey[Iterable[String]]("")
testsSikuli2 := { 
   testsSikuli.value.values.flatten 
}
```

Error:
```
value value is not a member of sbt.TaskKey
```

## expectation

I used a lot SBT and I know it is legal to use `.value` on a TaskDef

## notes

sbt version: 0.13.16

**Comment by dwijnand** [comment] 2018-03-16 15:29
I can't reproduce this with sbt 0.13.16 or sbt 1.1.1.

now `value` isn't technically a member of TaskKey, it's only available on TaskKey via an implicit conversion, but I have no idea how that failed for you.. any ideas?

I'm going to close this because (1) I can't reproduce it, and (2) the idea that whitespaces changes anything along this line is crazy... but we can reopen it if needed.

**Closed as completed by dwijnand** 2018-03-16 15:29 UTC

**Comment by DavidPerezIngeniero** [comment] 2018-03-19 07:43
As I've found a workaround, I'm not worried by this bug.

**Comment by frosforever** [comment] 2018-04-27 13:52
FWIW I ran into this issue when I had a `build.sbt` in the project root and then another `build.sbt` in a module directory. Calling `.value` on a `TaskKey` in the module `build.sbt` would error out. I fixed it by importing `sbt._` in the module `build.sbt`. This was using `0.13.16`

**Comment by dwijnand** [comment] 2018-04-27 14:04
Can you provide a minimal-but-complete reproduction of the issue?
