### ISSUE TITLE
No tab completion when running `sbt console` in one go

### ISSUE THREAD

**Issue by Sciss** [sbt/sbt#3841] opened 2017-12-27 14:57 UTC
(See the guidelines for contributing, linked above)

## steps

Run `sbt console` for a project. (Note that I use [sbt-extras](https://github.com/paulp/sbt-extras) and do not have sbt installed, so it may be related to that?). Type `Indexe` and press <kbd>Tab</kbd> key.

## problem

A tab character is inserted instead of invoking the tab-completion.

## expectation

It should complete to `IndexedSeq` instead of adding a tab character.

## notes

The problem does not occur if I launch `sbt` first, and then enter into the `console`.

sbt version: 1.0.4
terminal/OS: Bash on Debian Stretch
Java: openjdk version "1.8.0_151"

**Comment by paulp** [comment] 2017-12-31 05:28
No, I just checked and it's the same with the "official" runner, so not specific to sbt-extras.

**Comment by paulp** [comment] 2017-12-31 05:31
It looks like the sbt server is only started if you run sbt with no args, then go into the console. Does anyone know offhand why the code path for "sbt console" differs from that of "sbt" followed by "console", and/or where it is that should be responsible for starting the server which presumably supplies the completions?

**Comment by eed3si9n** [comment] 2017-12-31 06:21
Running "sbt console" runs sbt in a batch mode that executes `console` task. `console` task calls Scala REPL, which handles input, tab completion using JLine, and output on its own (we haven't virtualized that for server yet).

Running "sbt" runs `shell` task, which accepts user input from both the terminal and the network (server).

The problem is due to JLine initialization or restoration timing, which I think is reported as https://github.com/sbt/sbt/issues/3453, so this issue might be a variant of that (tab just is not sent to JLine). I thought this was fixed by https://github.com/sbt/sbt/pull/3507, but maybe not in all cases?

**Comment by eed3si9n** [comment] 2017-12-31 06:29
Here's another issue that looks more related https://github.com/sbt/sbt/issues/3661.

Jason has a workaround in there:

> Running `jline.TerminalFactory.get.init` in the borked REPL seems to unbork it.

So maybe if you run "sbt" as part of `shell` JLine gets initialized, but if you run "sbt console" it never gets initialized?

```scala
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_144).
Type in expressions for evaluation. Or try :help.

sc      ndexe


scala> jline.TerminalFactory.get.init
jline.TerminalFactory.get.init

scala> Index[tab]
IndexOutOfBoundsException   IndexedSeq
```

**Comment by paulp** [comment] 2017-12-31 07:10
@eed3si9n Yes, `jline.TerminalFactory.get.init` unborks it, thanks a lot.

**Comment by paulp** [comment] 2017-12-31 07:14
@eed3si9n Though, at the price of leaving echo disabled when I quit the repl, sigh.

**Comment by simlei** [comment] 2018-01-06 21:28
@paulp @eed3si9n Please keep this thread updated if there is news on that; for me, too, the abovementioned fix is working just up to the point that my terminal basically stops working after exiting the REPL.
Awesome feature though, this project console, and thank you for posting the fix in the first place!

**Comment by paulp** [comment] 2018-01-06 21:31
Presumably the call to init discards a shutdown hook which formerly restored echo. For now you can do it manually with stty echo or maybe stty sane.

**Comment by eed3si9n** [comment] 2018-01-06 21:44
```scala
scala> jline.TerminalFactory.get.restore

scala> Ind


scala> :q
:q
```

Yea. Everything you init needs to be cleanup afterwards. Call `restore`, confirm that your tab no longer works again, and `:q`.

**Comment by simlei** [comment] 2018-01-06 23:50
Nice. If this is tackled in the future, I just want to put on the record that `consoleProject` is affected the same way as `console` (the reason I'm here)

**Comment by paulp** [comment] 2018-01-07 00:29
Is there an easy user-level wrapper strategy console sessions? E.g. there would be something along the lines of (in sbt) 
```scala
def consoleSession(): Unit = {
  initConsole
  try runConsoleUntilExit() finally cleanupConsole()
}
```
Where `initConsole` and `cleanupConsole` hook into keys I can influence somewhere in `~/.sbt`. I feel like this sort of thing is done for some subset of useful tasks in a number of ways, and the thought of researching it makes me immediately want to give up, so for a change I will try asking.
 
Edit: I should point out that, not being completely in the dark, I am aware of `initialCommands`, which maybe suffices for half of this. Except that in my experience you can't rely on anything in initialCommands in your personal sbt files actually being run, because most people will set the project's commands with `initialCommands := ...` instead of `initialCommands += ...`.

**Comment by paulp** [comment] 2018-01-07 01:14
I guess the initialCommands in user.sbt are run after the ones in the build's sbt, at least in 1.1.0, at least so it seems from here, because I can use `:=` in the build.sbt and `+=` in the user sbt and everything gets there. Though this means I can't get out in front of the build's initialCommands with my global wrapper, not that it matters here.

It is odd that

- sbt 0.12 looks in ~/.sbt/0.12
- sbt 0.13 looks in ~/.sbt/0.13
- sbt 1.0 looks in ~/.sbt/1.0
- sbt 1.1 still looks in ~/.sbt/1.0

**Comment by eed3si9n** [comment] 2018-01-07 01:15
If you don't mind using some other name, then

```scala
addCommandAlias("consoleSession", ";initConsole;console;cleanupConsole")
```

If we want to take over existing key, something like this could work

```scala
    console in Compile := (console in Compile)
      .dependsOn(Def.task { jline.TerminalFactory.get.init })
      .andFinally( jline.TerminalFactory.get.restore )
      .value
```

See also http://www.scala-sbt.org/1.x/docs/Howto-Sequencing.html

**Comment by paulp** [comment] 2018-01-07 01:17
If I wanted the wrapper to run on all the consoles and consoleProjects in Test and Compile, is there any way to avoid injecting the same splodge of code for each?

**Comment by paulp** [comment] 2018-01-07 01:23
I confirm that placing into `~/.sbt/1.0/user.sbt` the incantation
```scala
console in Compile := (console in Compile)
      .dependsOn(Def task jline.TerminalFactory.get.init)
      .andFinally(jline.TerminalFactory.get.restore)
      .value
```
provides `sbt console` with working tab completion and the resumption of echo upon exit for those projects I have since sampled.

Thanks @eed3si9n !

**Comment by eed3si9n** [comment] 2018-01-07 02:49
I think you do need to inject those for each, but you can do this:

```scala
jlineWorkarounds
def jlineWorkarounds = Def.settings(
  Seq(
    console        in Compile,
    console        in Test,
    consoleProject in Compile,
    consoleProject in Test,
  ) map { key =>
    key := key
             .dependsOn(Def.task { jline.TerminalFactory.get.init })
             .andFinally(jline.TerminalFactory.get.restore)
             .value
  }: _*)
```

Note that this injection would work only for the root project, so you might end up with an AutoPlugin if you want subproject handling as well.

**Comment by simlei** [comment] 2018-01-07 09:10
@eed3si9n @paulp wow, lots of thanks for the tinkering & workarounds. consoleProject massively improves my current project and this workaround was important to show it to people and not give the impression of hacked-together stuff ;))

I tried it also with ``initialCommands in console`` but did not get very far as I wasn't able to find a shutdown hook for the terminal.

**Comment by dwijnand** [comment] 2018-01-08 11:24
@paulp

> It is odd that
> 
> sbt 0.12 looks in ~/.sbt/0.12
> sbt 0.13 looks in ~/.sbt/0.13
> sbt 1.0 looks in ~/.sbt/1.0
> sbt 1.1 still looks in ~/.sbt/1.0

1.0 is the binary API for the whole 1.x series. In retrospect I should've made it "1.x" (and properly dealt with the existing `(Int, Int)` type signature) instead of "1.0". My bad.

**Closed as completed** 2018-01-31 16:30 UTC
