### ISSUE TITLE
Installer modifies path variable on windows using default instead of actual installation path

### ISSUE THREAD

**Issue by aholland** [sbt/sbt#2421] opened 2016-01-26 08:38 UTC
Download MSI and install, specifying a directory other than C:\Program Files (x86)\sbt\bin

After installation, the system path has had "C:\Program Files (x86)\sbt\bin" added to it, instead of the actual installation path.

**Comment by dwijnand** [comment] 2016-08-22 12:20
Duplicate of https://github.com/sbt/sbt-launcher-package/issues/28

**Closed as completed by dwijnand** 2016-08-22 12:20 UTC
Labels: Duplicate
