### ISSUE TITLE
Running test in non forked mode doesn't release static objects

### ISSUE THREAD

**Issue by lab3** [sbt/sbt#1688] opened 2014-10-22 00:06 UTC
1. Start sbt in interactive mode.
2. Run test
3. Static objects in the app are created and never released when the test finishes
4. Run test
5. Static objects in the app are created and never released when the test finishes

At this point you have 2 copies of all statics alive in sbt's jvm.

**Comment by MasseGuillaume** [comment] 2014-10-22 00:29
by static objects do you mean:

``` scala
object That {
 val a = largeAmountOfMemory
}
```

**Comment by lab3** [comment] 2014-10-22 01:06
That is exactly what I mean.

**Comment by jsuereth** [comment] 2014-10-24 15:59
Sbt caches the classloaders used for tests.   The memory won't be cleaned until the classloader is evicted, which may not be immediately, given how GC is indeterminent.

ALSO there is an issue in Java where classloaders aren't cleaned appropriately due to finalizers.  As a workaround, you should be able to force System.runFinalization and System.gc after test.  We don't' do this by default, because the slowdown is massive, however if you're keeping huge memory chunks in static blocks, I'd recommend this.

**Comment by SethTisue** [comment] 2015-04-02 20:54
There is no confirmed bug in sbt here, so I'd suggest simply closing the ticket.

**Comment by SethTisue** [comment] 2015-04-17 03:11
you say classloaders, @eed3si9n says #1223!

**Closed as completed** 2019-10-03 04:20 UTC
Labels: Needs Reproduction Test Case
