### ISSUE TITLE
Ctrl-C aborts sbt as a whole not the currently executed task

### ISSUE THREAD

**Issue by jm-g** [sbt/sbt#593] opened 2012-11-06 16:35 UTC
It would be great to have some way to abort task while they are running without leaving sbt, e.g. a compile task. When I press Ctrl-C I am always back in the bash. That is on OS X.

**Comment by harrah** [comment] 2012-11-09 14:44
Duplicate of #228.

**Closed as completed by harrah** 2012-11-09 14:44 UTC
Labels: Duplicate
