### ISSUE TITLE
Provide useful information, when $HOME ist not writeable

### ISSUE THREAD

**Issue by thisismana** [sbt/sbt#3028] opened 2017-03-17 11:39 UTC
## steps
We where trying to move our sbt build into a "dockerized" environment using a standard apline java image with only bash added:

```
#!/bin/bash

wget https://dl.bintray.com/sbt/native-packages/sbt/0.13.13/sbt-0.13.13.tgz
tar -xzf sbt-0.13.13.tgz --strip-components=1

cat << EOF > Dockerfile
FROM java:8-jdk-alpine
RUN apk add --no-cache bash
EOF

docker build -t alpine_bash .

docker run --interactive --tty \
        --rm --volume `pwd`:/opt/sbt_sample \
        --user 1234 \
        alpine_bash /opt/sbt_sample/bin/sbt
```

## problem
This happened when sbt was trying to create the sbt lock file but failed because `$HOME` was not writeable.
The exception did mention what actually failed:

```
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at xsbt.boot.Locks$.apply0(Locks.scala:34)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at xsbt.boot.Launch.locked(Launch.scala:238)
	at xsbt.boot.Launch.app(Launch.scala:147)
	at xsbt.boot.Launch.app(Launch.scala:145)
	at xsbt.boot.Launch$.run(Launch.scala:102)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.io.IOException: No such file or directory
```

## expectation

Checking pre-conditions as `$HOME`/`SBT_HOME` is writeable and present a useful error message.

**Comment by dwijnand** [comment] 2017-03-17 11:47
Duplicate of #2498, imo.

**Closed as completed by dwijnand** 2017-03-17 11:47 UTC
