### ISSUE TITLE
Transitive dependencies with classifier are not pulled

### ISSUE THREAD

**Issue by pdalpra** [sbt/sbt#5325] opened 2019-12-19 15:22 UTC
## steps
sbt version:1.3.5

* Clone https://github.com/pdalpra/coursier-test
* Go to the `netty-epoll-direct` folder
* Run `sbt ';update;show fullClasspath;publishLocal'` => Notice that the classpath does include `netty-transport-native-epoll-4.1.44.Final-linux-x86_64.jar`
* Go to the `netty-epoll-transitive` folder
* Run `sbt ';update;show fullClasspath` => Notice that that all dependency (including transitive ones) are there, except `netty-transport-native-epoll-4.1.44.Final-linux-x86_64.jar`, which has been replaced by `netty-transport-native-epoll-4.1.44.Final.jar` (no classifier)

## problem

sbt with coursier ignores the classifiers from transitive dependencies. This works with Ivy.
I have tried to tweak `transitiveClassifiers` to include the classifier, without success.

## expectation

sbt with coursier should honor the classifiers even on transitive dependencies.

**Comment by eed3si9n** [comment] 2019-12-19 17:25
I am guessing this is a duplicate of https://github.com/sbt/sbt/issues/5136.

**Comment by slandelle** [comment] 2019-12-19 17:41
Maybe.
Then, issue #5136 was copied on coursier as coursier/coursier#1386 which was closed as fixed, with commit shipped in coursier [2.0.0-RC5: Take Ivy dependencies artifacts into account](https://github.com/coursier/coursier/commits/v2.0.0-RC5). 

Yet, sbt 1.3.5 uses [2.0.0-RC5-2](https://github.com/sbt/sbt/blob/v1.3.5/project/Dependencies.scala#L115) and it still doesn't work.

**Comment by alexarchambault** [comment] 2019-12-19 22:06
That seems to originate from the classifier missing in some of the locally published metadata.

`~/.ivy2/local/coursier.test/netty-epoll-direct_2.12/0.1.0-SNAPSHOT/ivys/ivy.xml` misses the `linux-x86_64` classifier in its dependency towards `io.netty:netty-transport-native-epoll`:
```xml
    <dependency org="io.netty" name="netty-transport-native-epoll" rev="4.1.44.Final" conf="compile->default(compile)"> </dependency>
```

`~/.ivy2/local/coursier.test/netty-epoll-direct_2.12/0.1.0-SNAPSHOT/poms/netty-epoll-direct_2.12.pom` has it OTOH:
```xml
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-epoll</artifactId>
            <version>4.1.44.Final</version>
            <classifier>linux-x86_64</classifier>
        </dependency>
```
(so I'd expect anything published to Maven repositories to be fine).

**Comment by alexarchambault** [comment] 2019-12-19 22:49
Seems that `ivy.xml` file is now generated by [this (sbt) code](https://github.com/sbt/sbt/blob/develop/main/src/main/scala/sbt/internal/librarymanagement/IvyXml.scala).

The `dependency` in the `ivy.xml` should look like
```xml
    <dependency org="io.netty" name="netty-transport-native-epoll" rev="4.1.44.Final" conf="compile->default(compile)">
      <artifact classifier="linux-x86_64"></artifact>
    </dependency>
```
(don't know if other attributes are required in `artifact`… coursier is fine with that ^ )

**Comment by slandelle** [comment] 2019-12-20 08:03
@alexarchambault @eed3si9n Indeed, it looks like the problem is with the generated `ivy.xml`.
However, does it make sense that the issue is with sbt only as the problem goes away when disabling coursier?

Using sbt 1.3.5.

default:

```xml
<dependency org="io.netty" name="netty-transport-native-epoll" rev="4.1.44.Final" conf="compile->default(compile)"> </dependency>
```

with `ThisBuild / Keys.useCoursier := false`:

```xml
<dependency org="io.netty" name="netty-transport-native-epoll" rev="4.1.44.Final" conf="compile->default(compile)">
	<artifact name="netty-transport-native-epoll" type="jar" ext="jar" conf="*" e:classifier="linux-x86_64"/>
</dependency>
```

**Comment by alexarchambault** [comment] 2019-12-20 11:47
> However, does it make sense that the issue is with sbt only as the problem goes away when disabling coursier?

Yes, I think the code above that generates `ivy.xml` either doesn't run, or the file it writes is then overridden by Ivy itself. That code was added specifically for coursier support (this used to be handled by the coursier sbt plugin).

**Comment by mkurz** [comment] 2020-01-25 22:51
This just bit me too when building a local snapshot of the Play Framework, which also depends on [`netty-transport-native-epoll`](https://github.com/playframework/playframework/blob/40a9f4a74705153e12a93f3154094f3e62dc0ef3/project/Dependencies.scala#L154) with the `linux-x86_64` artifact. I can confirm it works when disabling coursier with `ThisBuild / Keys.useCoursier := false`.

**Comment by LeonardMeyer** [comment] 2020-02-18 16:52
Same problem here with 1.3.8. Is there a status on this or should we just disable Coursier ?

**Comment by slandelle** [comment] 2020-03-26 22:06
I would be willing to work on this and contribute a fix but I don't really know where to look. Any pointer would be very welcome! Also, instructions on how to build sbt-coursier would be very much appreciated (I guess the bug is in there but I couldn't manage to figure out how to build).

**Comment by 987Nabil** [comment] 2020-08-18 09:01
Hey! I would also be willing to help to fi this. I tried to take a look, but I got lost in the sources. Any hint would be nice.

**Comment by slandelle** [comment] 2021-04-19 09:50
@pdalpra It looks like you've dropped the reproducer project :(

**Comment by pdalpra** [comment] 2021-04-19 09:57
Ah indeed, sorry for that, completely forgot that it was for that issue...
I could not find a local copy for it, altough it’s not too hard to rebuild a reproducer.

**Comment by slandelle** [comment] 2021-04-19 09:59
Yes, will do. Thanks anyway :)

**Comment by guilgaly** [comment] 2021-04-19 13:38
> Yes, I think the code above that generates `ivy.xml` either doesn't run, or the file it writes is then overridden by Ivy itself. That code was added specifically for coursier support (this used to be handled by the coursier sbt plugin).

I opened the pull request #6456 which modifies that piece of code to add the classifier (if there is one) to the `ivy.xml` file, and it does seem to work. The code simply only generated the `dependency` element, and the `exclude` elements if there are exclusions, but not the `artifact` element for the classifier.

**Closed as completed** 2021-04-19 14:13 UTC
Labels: area/library_management
