### ISSUE TITLE
warning for multiple/no main class in module

### ISSUE THREAD

**Issue by wwagner4** [sbt/sbt#1889] opened 2015-02-28 11:49 UTC
For me this should not be a warning. I think it is normal to have no- or multiple main classes in a module.

```
[warn] No main class detected
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
```

I like to have my builds 'warningfree'

**Comment by eed3si9n** [comment] 2015-02-28 23:58
Duplicate of #1766.
Could you test sbt 0.13.8-M6 and see if it still happens?

**Closed as completed by eed3si9n** 2015-02-28 23:58 UTC
Labels: Duplicate

**Comment by nbrahms** [comment] 2015-05-22 18:53
Can we reopen this?

#1766 only fixed the "No main class detected" warning, not "Multiple main classes". 

I just rolled back to 0.13.7 so I don't have to see this.
