### ISSUE TITLE
`sbt new` does not clean up temporary `target` directory

### ISSUE THREAD

**Issue by note** [sbt/sbt#3888] opened 2018-01-16 16:37 UTC
## steps

```
sbt new scala/hello-world.g8
```

## problem

Creation works as expected but the command left `target` directory as leftover:

```

sbt new scala/hello-world.g8
```

## expectation

`sbt` should create just a folder with new project and should not left any temporary directories.

Pure `g8` does not leave leftovers: (checked for version `0.10.0`).

```
g8 scala/hello-world.g8
```

## notes

sbt version: *1.1.0*

I did a little research regarding that ticket. In https://github.com/sbt/sbt-giter8-resolver quite outdated version of `giter8` is used and since I see some cleanup code in current version of `giter8` and additionally pure `g8` does not left anything it may seem like update may work by itself. Unfortunately that's not the point (tried it quickly but with no positive result).

**Comment by dwijnand** [comment] 2018-01-16 16:40
Duplicate of #2835.

**Closed as completed by dwijnand** 2018-01-16 16:40 UTC
