### ISSUE TITLE
[1.3.0-RC2] Empty classpath / classloader issues in test

### ISSUE THREAD

**Issue by neko-kai** [sbt/sbt#4796] opened 2019-06-11 00:51 UTC
## steps
sbt version: *1.3.0-RC2*

## problem

When running tests in in-process JVM, classpath seems to be empty.  `ClassLoaderLayeringStrategy.Flat` does not restore the classpath visibility. `NoClassDefError` also arises when `scala-reflect` is used shutdown hook. More details at https://github.com/7mind/izumi/issues/545 (or below)

## expectation

Expected same behavior as 1.3.0-RC1

## notes

Original ticket copypasted below:

Certain classpath-based tests started failing after upgrade from 1.3.0-RC1 to 1.3.0-RC2.
These tests seem to  pass with `fork in Test := true`, **BUT NOT** with `classLoaderLayeringStrategy in Test := ClassLoaderLayeringStrategy.Flat`
Specifically:

[LoaderTest.scala](https://github.com/7mind/izumi/blob/a94f0de424d994e0585e6b27129370e311a019c1/idealingua-v1/idealingua-v1-transpilers/.jvm/src/test/scala/com/github/pshirshov/izumi/idealingua/LoaderTest.scala#L20) (no fastparse found on classpath):

```
[info] FS enumerator
[info] - should be able to find files in jars *** FAILED *** (40 milliseconds)
[info]   Map() had size 0 instead of expected size 1 (LoaderTest.scala:24)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:530)
[info]   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:529)
[info]   at org.scalatest.WordSpec.newAssertionFailedException(WordSpec.scala:1881)
[info]   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:503)
[info]   at com.github.pshirshov.izumi.idealingua.LoaderTest.$anonfun$new$4(LoaderTest.scala:24)
```

[CompilerTest.scala](https://github.com/7mind/izumi/blob/a94f0de424d994e0585e6b27129370e311a019c1/idealingua-v1/idealingua-v1-transpilers/.jvm/src/test/scala/com/github/pshirshov/izumi/idealingua/CompilerTest.scala#L15) - the classpath passed down to `scalac` is assembled from the current classpath, but on new sbt RC it's barren, jdk8 and no libraries:

```
-classpath /Users/kai/.sbt/boot/scala-2.12.8/lib/scala-reflect.jar:/Users/kai/.sbt/boot/scala-2.12.8/lib/scala-library.jar:/Users/kai/.sbt/boot/scala-2.12.8/lib/scala-library.jar:/Users/kai/.sbt/boot/scala-2.12.8/org.scala-sbt/sbt/1.3.0-RC2/test-interface-1.0.jar:/usr/local/Cellar/sbt/1.1.6/libexec/bin/sbt-launch.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/System/Library/Java/Extensions/MRJToolkit.jar:/usr/local/Cellar/sbt/1.1.6/libexec/bin/sbt-launch.jar
```

`scala-reflect` misbehaves also, `TypeTag` creation fails in shutdown hook after running `test` Task and exiting sbt:

```
[info] shutting down server
Exception in thread "termination-hook-memoizer" java.lang.NoClassDefFoundError: com/github/pshirshov/izumi/distage/testkit/services/ExternalResourceProvider$Singleton$$typecreator1$3
        at com.github.pshirshov.izumi.distage.testkit.services.ExternalResourceProvider$Singleton$.$anonfun$stop$1(ExternalResourceProvider.scala:150)
        at com.github.pshirshov.izumi.distage.testkit.services.ExternalResourceProvider$Singleton$.$anonfun$stop$1$adapted(ExternalResourceProvider.scala:131)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at com.github.pshirshov.izumi.distage.testkit.services.ExternalResourceProvider$Singleton$.stop(ExternalResourceProvider.scala:131)
        at com.github.pshirshov.izumi.distage.testkit.services.ExternalResourceProvider$Singleton$.$anonfun$shutdownHook$1(ExternalResourceProvider.scala:105)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.github.pshirshov.izumi.distage.testkit.services.ExternalResourceProvider$Singleton$$typecreator1$3
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 8 more
```

**Comment by eatkins** [comment] 2019-06-11 01:15
Duplicate of #4794.

**Comment by eatkins** [comment] 2019-06-11 01:17
Actually, it’s not strictly the same so reopening for now. Shutdown hooks have never been expected to work when using an in process jvm. However I am not sure of the cause of the other issues.

**Comment by pshirshov** [comment] 2019-06-11 11:32
@eatkins 
> Shutdown hooks have never been expected to work when using an in process jvm.

I understand that they are flawed. But they worked and they are the only option we have in fact.

So, we have a heavy integration test suite which relies on memoization. At the end of build process we need to perform cleanups (drop database schemas, shutdown services, etc).

Shutdown hook is the only solution we have. Dirty but it does the job (at least it worked for more than ten years).

We have no global knowledge of our test suites - scalatest and other test frameworks don't provide us enough data and don't provide us a single point of entry/exit. So there is no way around the issue - I would be happy to redesign the code but I can't unless I build my own test framework.

Could you please reconsider these breaking changes? Or, maybe, provide your own "shutdown hook" which should be executed once `test` finishes (it may be defined somewhere in aggregating project for example)? Or, maybe, sbt-level `before all`/`after all` hooks on project level and aggregating project level?..

**Comment by eatkins** [comment] 2019-06-11 16:33
set -Dsbt.classloader.close=false

**Comment by eed3si9n** [comment] 2019-06-11 20:45
Maybe related discussion here - https://github.com/sbt/sbt/issues/2056

**Comment by eatkins** [comment] 2019-06-11 21:40
I am sympathetic to the issues that you're experiencing, but I think that the entry/exit point for test and run is a better solution than trying to support shutdown hooks by default. That is more of an sbt 1.4.0 feature request though.

That being said, I'm not sure that I fully understand your issue. Are you trying to persist the memoized state across multiple evaluations, i.e. if the user runs `test;test` the same memoized state is used in both runs? Or do you set up a new memoized state for each run and clean them all up when sbt exits? What do you do if sbt crashes and the shutdown hooks are never run? We need to fully understand the use case in order to consider appropriate solutions.

Let me clarify further my explanation for why the changes were made that impact shutdown hooks. The changes were not made to inconvenience people who relied on shutdown hooks, but rather to reduce the memory and resource utilization of sbt to make it more stable for most users. We were aware that this would impact some users who cannot avoid the use of shutdown hooks for whatever reason. That is why we added the system property `sbt.classloader.close`. Moreover, forking tests and run has always been the recommended solution if shutdown hooks are required. This continues to work with sbt 1.3.0 and no system property is necessary to use forking.

Shutdown hooks are only run _at most_ once per jvm session. If the jvm is terminated forcefully, they do not run at all. Because they are stored globally at the jvm level, every hook that is registered effectively leaks a classloader. From the perspective of sbt, this is a resource leak that can, and will, cause projects to run out of memory because the classloader of the hook cannot be garbage collected.

There is the problem of libraries that use ShutdownHooks. Some libraries, like akka, have a mechanism for cleaning up their shutdown hooks (when an ActorSystem is closed, all of its registered shutdown hooks are run and removed from the global jvm registry). Other libraries do not support removing the shutdown hooks they register. This creates a problem for sbt. Either we leak memory with each run which eventually causes sbt to crash or we can close the classloaders after test and run. This fixes a file descriptor resource leak, though it does not fix the memory leak. It does, however, create a noisy failure that forces the user to decide what they want to do:

1) ignore the memory and resource leaks by setting `-Dsbt.classloader.close=false`.
2) ignore the error messages in the logs
3) fork tests

In your case, it seems that you've decided that given the complexity of your build, ignoring the leaks is appropriate. As a result of the initial errors, however, you've raised a valuable feature request/revived the discussion of https://github.com/sbt/sbt/issues/2056 that can be used to improve sbt in the future. I wish that your build worked out of the box with no errors or warnings, but your build has relied on undefined behavior that we have explicitly warned against in the documentation since at least 2012.

**Comment by pshirshov** [comment] 2019-06-12 01:20
We persist state across multiple runs. It's, obviously, a leak, but it serves the purpose.

I do understand all the problems with shutdown hooks - but I have no choice. I need memoization - it gives us like x100 speedup and I need cleanups.

Forking is an option, but again - it slows things down :(

Okay, I will stick with this new property or forking, though seems like I would have to write my own test framework with global knowledge allowing me to plan full graph of my test suite :(

**Comment by xerial** [comment] 2019-06-12 05:51
@eatkins 
>  Some libraries, like akka, have a mechanism for cleaning up their shutdown hooks (when an ActorSystem is closed, all of its registered shutdown hooks are run and removed from the global jvm registry)

That is good to know. My issue around #4794 can be solved with this approach. Thanks!

**Comment by eatkins** [comment] 2019-09-20 18:25
We changed the behavior of this feature in sbt 1.3.1/1.3.2. ClassLoaders can now be re-opened after close (which still happens after run or test completes) but sbt will emit a warning if that happens. You can disable the warning by setting the key `allowZombieClassLoaders := true`.

**Closed as completed by eatkins** 2019-09-20 18:25 UTC

**Comment by xerial** [comment] 2019-09-20 18:36
@eatkins Thanks. What I learned so far is as follows:
- If we register a custom log handler to java.util.logging, the handler will belong to a zombie :) and NoClassDefException will be thrown. We need to clean up custom log handlers.
- JVM shutdown hooks need to be properly removed before exiting test or run tasks. 

After understanding these issues, applying such a clean-up process was not so difficult. The warning message in sbt 1.3.2 when an old ClassLoader is used will definitely help to have this understanding. Thanks for adding this workaround.

**Comment by eatkins** [comment] 2019-09-20 18:43
@xerial that's good to hear. In spite of the confusion and complaints generated by the initial rollout of this feature, the hope is that it will help users identify resource leaks so that long lived sbt sessions will be more stable. Unfortunately we were just a little too aggressive in trying to enforce hygiene, causing frustration and confusion for users, so we had to relax our approach.

**Comment by xerial** [comment] 2019-09-20 19:09
@eatkins Yeah. It was a hard lesson but actually worked as you initially expected to find resource leaks. In my case, I found too many shutdown hooks were registered in my code.
