### ISSUE TITLE
1.4.3 Regression with tasks that return a function

### ISSUE THREAD

**Issue by julienrf** [sbt/sbt#6126] opened 2020-11-19 19:51 UTC
## steps

~~~ scala
// build.sbt
scalaVersion := "2.13.4"

val foo = taskKey[Unit]("")

foo := {
  val f = fTask.value
  streams.value.log.info(s"Invoking $f")
  f(0)
}

lazy val fTask: Def.Initialize[Task[Int => Int]] = Def.task {
  val log = streams.value.log
  x => {
    log.info(s"Evaluating f($x)")
    42
  }
}
~~~

## problem

sbt 1.4.3 does not evaluate the body of the function returned by `fTask`.

~~~
[info] Invoking $af8b69c2d2334066fdb0$$$Lambda$4487/0x0000000841335840@62df7a9a
[success] Total time: 0 s, completed Nov 19, 2020, 8:38:09 PM
~~~

## expectation

sbt 1.3.13 evaluates the body of the function.

~~~
[info] Invoking $c9429efa43a66453fa09$$$Lambda$4865/0x000000084167b840@50dbb213
[info] Evaluating f(0)
[success] Total time: 0 s, completed Nov 19, 2020, 8:39:16 PM
~~~

Note that it prints “Evaluating f(0)”, which was not the case with sbt 1.4.3.

## steps (variant 1)

I’ve noticed that if the function returned by my task is not a constant, then the output is different:

~~~ scala
// build.sbt
scalaVersion := "2.13.4"

val foo = taskKey[Unit]("")

foo := {
  val f = fTask.value
  streams.value.log.info(s"Invoking $f")
  f(0)
}

lazy val fTask: Def.Initialize[Task[Int => Int]] = Def.task {
  val log = streams.value.log
  x => {
    log.info(s"Evaluating f($x)")
    x + 1 // We now return the expression x + 1 instead of the constant 42
  }
}
~~~

Then both sbt 1.3 and 1.4 return the same (expected) output:

~~~
[info] Invoking $b1ce599c8650c7faaf35$$$Lambda$5101/0x0000000841566040@3d42583f
[info] Evaluating f(0)
[success] Total time: 0 s, completed Nov 19, 2020, 8:41:41 PM
~~~

## steps (variant 2)

Here is another variant where we print the result of the function returned by the task:

~~~ scala
// build.sbt
scalaVersion := "2.13.4"

val foo = taskKey[Unit]("")

foo := {
  val f = fTask.value
  streams.value.log.info(s"Invoking $f")
  streams.value.log.info(f(0).toString) // We now print the result
}

lazy val fTask: Def.Initialize[Task[Int => Int]] = Def.task {
  val log = streams.value.log
  x => {
    log.info(s"Evaluating f($x)")
    x + 1
  }
}
~~~

## problem

sbt 1.4.3 evaluates the function 4 times.

~~~
[info] Invoking $b1ce599c8650c7faaf35$$$Lambda$5130/0x0000000841569840@3bbae7a4
[info] Evaluating f(0)
[info] 1
[info] Evaluating f(0)
[info] Evaluating f(0)
[info] Evaluating f(0)
[success] Total time: 0 s, completed Nov 19, 2020, 8:45:37 PM
~~~

## expectation

sbt 1.3.13 evaluates the function once.

~~~
[info] Invoking $985fb3f3cf4f59b15e5b$$$Lambda$3893/0x0000000841367840@67d15a71
[info] Evaluating f(0)
[info] 1
[success] Total time: 0 s, completed Nov 19, 2020, 8:44:22 PM
~~~

## questions

- is there a better way to achieve what I want? I really want to define a task that returns me a function that I can apply on various inputs.
- is there a way to achieve what `taskDyn` was supposed to do, but without using operations that use macros? I’ve tried using `flatMap` but ended up with “Illegal dynamic dependencies” issues everywhere.

**Comment by eed3si9n** [comment] 2020-11-19 20:08
```scala
lazy val fTask: Def.Initialize[Task[Int => Int]] = Def.task {
  val log = streams.value.log
  x => {
    log.info(s"Evaluating f($x)")
    42
  }
}
```

I don't expect this to work because `Task[_]` is an Effect monad, and streams logger is an ephemeral thing that would exist only during the period when the task is on Java's thread scheduler. By the time `foo` has access to the function, I'm not sure if we can say what happens to those loggers. Otherwise, returning a pure function should be ok, I think.

**Comment by julienrf** [comment] 2020-11-19 20:26
OK. It used to work but I’m happy to find an alternative. I don’t need `log` but I need to write files (so I need to perform side-effects).

**Comment by eatkins** [comment] 2020-11-19 21:52
These are two independent issues.

I think that the first regression occurred due to the combination of b62ddaa4e982031ef56ea14599b0c3b3ceabe027, a44aee9ac and 3a1463bb7dfa2163c69715151329f2cee93ff2e6. If I revert those three commits, the problem goes away.

The second occurred in 2e9805b9d01c6345214c14264c61692d9c21651c. I think the bug is that log.info takes a thunk and the thunk is being evaluated by all of the multi loggers instead of just once for all of the loggers.

**Comment by eatkins** [comment] 2020-11-19 23:00
#6128 fixes the variant 2 issue.

**Comment by julienrf** [comment] 2020-11-20 07:44
Thank you so much @eatkins for the investigation!

I would still be interested to know if there is a macro-free API we can use to avoid these pitfalls. I guess this should be possible, since macro calls just desugar to calls to the public API?

**Comment by eed3si9n** [comment] 2020-11-20 14:36
> I would still be interested to know if there is a macro-free API we can use to avoid these pitfalls. I guess this should be possible, since macro calls just desugar to calls to the public API?

As far as I know, there's no clean macro-free API any more. It would likely look like a tuple syntax from sbt 0.12 combined with `<<=` operator to rewire keys since `:=` that deals with pure value is a macro too.

Idiomatic sbt way of doing things (I think) would be to map both inputs and the function as tasks:

```scala
import Dependencies._

ThisBuild / scalaVersion     := "2.13.4"
ThisBuild / version          := "0.1.0-SNAPSHOT"
ThisBuild / organization     := "com.example"
ThisBuild / organizationName := "example"

val foo = taskKey[Int]("")
val bar = taskKey[Int]("")

lazy val root = (project in file("."))
  .settings(
    bar := 1,
    foo := {
      if (bar.value % 2 == 0) addOne(bar).value
      else subOne(bar).value
    }
  )

def addOne(key: TaskKey[Int]) = Def.task { key.value + 1 }
def subOne(key: TaskKey[Int]) = Def.task { key.value - 1 }
```

**Comment by eed3si9n** [comment] 2020-11-20 14:49
> I think that the first regression occurred due to the combination of b62ddaa, a44aee9 and 3a1463b. If I revert those three commits, the problem goes away.

I'm happy to revert those.

**Comment by eed3si9n** [comment] 2020-11-22 23:03
Hopefully fixed in https://github.com/sbt/sbt/pull/6158.

**Closed as completed by eed3si9n** 2020-11-22 23:03 UTC
