### ISSUE TITLE
IO.scala doesnt handle relative file paths on windows correctly

### ISSUE THREAD

**Issue by benhutchison** [sbt/sbt#111] opened 2011-07-19 21:11 UTC
I found that this line from a SBT configuration (on Windows):

"lazy val tagtree = RootProject(file("../TagTree"))"

blows up with this exception:

java.net.URISyntaxException: Illegal character in path at index 2: ..\TagTree
        at java.net.URI$Parser.fail(Unknown Source)
        at java.net.URI$Parser.checkChars(Unknown Source)
        at java.net.URI$Parser.parseHierarchical(Unknown Source)
        at java.net.URI$Parser.parse(Unknown Source)
        at java.net.URI.<init>(Unknown Source)
        at sbt.IO$.toURI(IO.scala:620)
        at sbt.RootProject$.apply(Reference.scala:32)
        at HeroscapeMk2$.tagtree(Build.scala:4)

The problems seems to be at IO.scala:620:

"def toURI(f: File): URI  =  if(f.isAbsolute) f.toURI else new URI(f.getPath)"

Unfortunately, on Windows, File.getPath() uses backslashes which are illegal in URIs:

scala> new java.io.File("../TagTree")
res0: java.io.File = ..\TagTree

scala> res0.getPath()
res1: java.lang.String = ..\TagTree

**Comment by harrah** [comment] 2011-07-20 00:42
Valid and correctly diagnosed, but a duplicate of #105 and (supposedly) fixed in 0.10.1.

**Closed as completed by harrah** 2011-07-20 00:42 UTC
Labels: Duplicate
