### ISSUE TITLE
sbtn: navigating through previously launched commands doesn't work

### ISSUE THREAD

**Issue by guizmaii** [sbt/sbt#6813] opened 2022-02-03 02:19 UTC
## steps

1. Set the `SBT_NATIVE_CLIENT=true` in your terminal
2. launch sbt
3. Hit the :arrow_up: button in the sbt shell

## problem

Usually, without `SBT_NATIVE_CLIENT`,   Hitting the :arrow_up: button shows the previous command I launched and so I can go through all the previous commands I launched to relaunch them

With `SBT_NATIVE_CLIENT`, it only shows random characters: `[A[A[A[B[B[B[B[A[A[A`

## notes

OS: macOS
sbt version: 1.6.2

**Comment by eed3si9n** [comment] 2022-02-10 13:42
@guizmaii Thanks for the report. Could you tell us which terminal program you use? Terminal vs iTerm vs terminal embedded into VS Code etc. Does switching the terminal program make any difference?

**Comment by guizmaii** [comment] 2022-02-11 08:28
iTerm2 up-to-date with zsh.

Using the macOS "normal" terminal, still with zsh, doesn't fix the issue.

macOS Monterey 12.2

**Comment by Friendseeker** [comment] 2024-11-19 05:34
I cannot reproduce the issue. I use `sbt --client` on my M1 MacBook Pro daily with `zsh` and never encountered such issue. Tab completion & arrow history just works. (and I use latest sbt version, as of date 1.10.5).

Without further information I shall close the issue for now. Maybe some random PRs over the 2 years fixed the issue.

**Closed as not planned by Friendseeker** 2024-11-19 05:34 UTC
