### ISSUE TITLE
[1.3.0-RC4] Error when launching sbt on AdoptOpenJDK OpenJ9

### ISSUE THREAD

**Issue by hugo-vrijswijk** [sbt/sbt#4985] opened 2019-08-24 09:40 UTC
## steps
sbt version: *1.3.0-RC4*

Start sbt using AdoptOpenJDK J9 on Linux

## problem

When starting sbt 1.3.0-RC4 on Ubuntu or WSL (Debian) with AdoptOpenJDK J9, a stacktrace is printed almost right away: https://gist.github.com/hugo-vrijswijk/c49fbbdc613a088efb7819a02957c36f

3 files are also written to disk:

https://gist.github.com/hugo-vrijswijk/e284188579cf729ce80389792f79e4d9

And a binary file with the name `Snap.20190824.112919.24863.0003.trc` I could upload somewhere else if needed.

## expectation

Sbt starts normally.

## notes
WSL: 
- Java versions: AdoptOpenJDK J9 8.0.222 or 11.0.4
- Used latest `sbt-extras` script
- Distro: Debian 10
- Windows version 1903

Ubuntu:
- Java version: AdoptOpenJDK J9 11.0.4
- Used latest `sbt-extras` script
- Distro: Ubuntu 18.0.4

Works fine when in the following cases:
- OpenJDK 11 WSL
- AdoptOpenJDK 11 HotSpot on WSL
- AdoptOpenJDK OpenJ9 11 on Windows.

**Comment by eed3si9n** [comment] 2019-08-25 03:08
Did sbt 1.2.8 work?

**Comment by hugo-vrijswijk** [comment] 2019-08-25 06:54
Yes. 1.2.8 and 1.3.0-RC3 work

**Comment by eatkins** [comment] 2019-08-27 03:20
This is reproducible on osx using `adopt-openj9@1.11.0-4`. It does not crash if I downgrade the launcher to 1.1.2 or if I set `sbt.version` to `1.3.0-RC2`. It does crash with the 1.1.2 launcher with 1.3.0-RC3 and 1.3.0-RC4.

**Comment by eed3si9n** [comment] 2019-08-27 12:42
@eatkins That is useful information. I guess the my use of Console has triggered this regression?

**Comment by eatkins** [comment] 2019-08-27 15:31
I'm not sure about that. I think the switch to Console.err happened in 1.1.1. It didn't look like much changed besides wording of error messages but I didn't investigate thoroughly.

**Comment by eed3si9n** [comment] 2019-08-27 18:22
Yea. It's one commit - https://github.com/sbt/launcher/pull/73/commits/3861e8a1ea01317985095669252b89a589b6ee8d

I don't how that is triggering a JIT to error. I'm closing this since I don't think there's much we can do on our side. I guess a workaround might be to use launcher 1.1.1 for those people who want to use AdoptOpenJDK J9 8.0.222 or 11.0.4.

**Closed as completed by eed3si9n** 2019-08-27 18:22 UTC

**Comment by eed3si9n** [comment] 2019-08-27 22:17
@eatkins fixed the issue. Let's see how the next one goes.

**Comment by hugo-vrijswijk** [comment] 2019-09-01 08:03
I can confirm I am no longer running into the issue. Thanks a lot!!

**Comment by eed3si9n** [comment] 2019-09-03 18:39
@hugo-vrijswijk FYI I reported this upstream - https://github.com/eclipse/openj9/issues/6940
