### ISSUE TITLE
modify repository running error

### ISSUE THREAD

**Issue by duansheli** [sbt/sbt#5279] opened 2019-12-09 16:09 UTC
## steps
sbt version: *1.3.4*
windows 10 

modify sbt-launch.jar!/sbt/sbt.boot.properties
change Repositories Section to this
```
[repositories]
local
nexus-aliyun:https://maven.aliyun.com/nexus/content/groups/public
```

git bash run command
```
sbt --debug 
```

then error msg
```
[addSbt] arg = '-debug'
[process_args] java_version = '11'
[sbt_options] declare -a sbt_options=()
[addMemory] arg = '1024'
[addJava] arg = '-Xms1024m'
[addJava] arg = '-Xmx1024m'
[addJava] arg = '-Xss4M'
[addJava] arg = '-XX:ReservedCodeCacheSize=128m'
[copyRt] java9_rt = 'C:\Users\mnd\.sbt\0.13\java9-rt-ext-amazon_com_inc__11_0_5/rt.jar'
[addJava] arg = '-Dscala.ext.dirs=C:\Users\mnd\.sbt\0.13\java9-rt-ext-amazon_com_inc__11_0_5'
[addJava] arg = '-Djline.terminal=jline.UnixTerminal'
[addJava] arg = '-Dsbt.cygwin=true'
# Executing command line:
java
-Dfile.encoding=UTF-8
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-Dscala.ext.dirs=C:\Users\mnd\.sbt\0.13\java9-rt-ext-amazon_com_inc__11_0_5
-Djline.terminal=jline.UnixTerminal
-Dsbt.cygwin=true
-jar
P:\sprogram\sbt-1.3.4\bin\sbt-launch.jar
-debug

[info] [launcher] getting org.scala-sbt sbt 1.3.4  (this may take some time)...

:: problems summary ::
:::: WARNINGS
        problem while downloading module descriptor: https://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/sbt/1.3.4/sbt-1.3.4.pom: The HTTP response code for https://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/sbt/1.3.4/sbt-1.3.4.pom did not indicate a success. See log for more detail. (57ms)

                module not found: org.scala-sbt#sbt;1.3.4

        ==== local: tried

          C:\Users\mnd\.ivy2\local\org.scala-sbt\sbt\1.3.4\ivys\ivy.xml

          -- artifact org.scala-sbt#sbt;1.3.4!sbt.jar:

          C:\Users\mnd\.ivy2\local\org.scala-sbt\sbt\1.3.4\jars\sbt.jar

        ==== nexus-aliyun: tried

          https://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/sbt/1.3.4/sbt-1.3.4.pom

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: org.scala-sbt#sbt;1.3.4: not found

                ::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[error] [launcher] unresolved dependency: org.scala-sbt#sbt;1.3.4: not found
[error] [launcher] error during sbt launcher: error retrieving required libraries
  (see C:\Users\mnd\.sbt\boot\update.log for complete log)
[error] [launcher] could not retrieve sbt 1.3.4
```

## problem

use wget can get file
```
wget https://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/sbt/1.3.4/sbt-1.3.4.pom
wget https://maven.aliyun.com/nexus/content/groups/public/org/fusesource/jansi/jansi/1.11/jansi-1.11.pom
```
`sbt --debug `     ==>>  read `sbt-1.3.4.pom` error
`sbt --debug -version` ==>> read `jansi-1.11.pom`  error

in china our internet has great-wall  
init sbt project tooks so long times  
but got a error  
make people go nuts

## expectation

repository with `maven.aliyun.com` run correct

## notes
run command in `cmd.exe`  got info
` ` ` 
。。。
ROBOCOPY     ::     Windows 的可靠文件复制
list files dirs
。。。
` ` `

**Comment by eed3si9n** [comment] 2019-12-12 18:17
@duansheli Thanks for the report.

Have you tried using installs from https://www.scala-sbt.org/download.html? That should contain most of the JARs already and uses Robocopy to move that into a local repo.

**Comment by duansheli** [comment] 2019-12-19 13:40
seems link has a redirect 
@eed3si9n 
```
https://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/sbt/1.3.4/sbt-1.3.4.pom
http://archiva-maven-storage-prod.oss-cn-beijing.aliyuncs.com/repository/central/org/scala-sbt/sbt/1.3.4/sbt-1.3.4.pom?Expires=1576764983&OSSAccessKeyId=LTAIfU51SusnnfCC&Signature=s2o9ih9VvhMsje4CskxlApD2%2B6s%3D
```

**Comment by angelorobo** [comment] 2020-02-19 23:28
@duansheli Have you found a solution yet? We also have the same issue.

**Comment by eed3si9n** [comment] 2020-02-20 05:46
This might be a duplicate of https://github.com/sbt/sbt/issues/5059.
There's a workaround posted there.

**Closed as completed by eed3si9n** 2020-02-20 05:46 UTC
Labels: area/proxy, area/launcher
