### ISSUE TITLE
Recompiles even if there is no changes

### ISSUE THREAD

**Issue by joan38** [sbt/sbt#3501] opened 2017-09-06 14:13 UTC
## steps

```
mkdir -p test/project
cd test
echo "sbt.version=1.0.1" > project/build.properties
echo "addSbtPlugin(\"com.eed3si9n\" % \"sbt-buildinfo\" % \"0.7.0\")" > project/plugins.sbt
echo "enablePlugins(BuildInfoPlugin)" > build.sbt
mkdir -p src/main/scala
echo "object Test {}" > src/main/scala/Test.scala
sbt ~test:compile
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from /Users/joangoyeau/.sbt/1.0/plugins
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/joangoyeau/Code/test/project
[info] Loading settings from build.sbt ...
[info] Set current project to test (in build file:/Users/joangoyeau/Code/test/)
[info] Compiling 2 Scala sources to /Users/joangoyeau/Code/test/target/scala-2.12/classes ...
[info] Done compiling.
[success] Total time: 5 s, completed 08-Sep-2017 14:26:50
1. Waiting for source changes... (press enter to interrupt)
[info] Compiling 2 Scala sources to /Users/joangoyeau/Code/test/target/scala-2.12/classes ...
[info] Done compiling.
[success] Total time: 1 s, completed 08-Sep-2017 14:26:57
2. Waiting for source changes... (press enter to interrupt)
[info] Compiling 2 Scala sources to /Users/joangoyeau/Code/test/target/scala-2.12/classes ...
[info] Done compiling.
[success] Total time: 1 s, completed 08-Sep-2017 14:27:06
3. Waiting for source changes... (press enter to interrupt)
[info] Compiling 2 Scala sources to /Users/joangoyeau/Code/test/target/scala-2.12/classes ...
[info] Done compiling.
[success] Total time: 1 s, completed 08-Sep-2017 14:27:16
4. Waiting for source changes... (press enter to interrupt)
[success] Total time: 0 s, completed 08-Sep-2017 14:27:16
5. Waiting for source changes... (press enter to interrupt)
[info] Compiling 2 Scala sources to /Users/joangoyeau/Code/test/target/scala-2.12/classes ...
[info] Done compiling.
[success] Total time: 1 s, completed 08-Sep-2017 14:27:26
6. Waiting for source changes... (press enter to interrupt)
```

## problem

It recompiles even if there is no changes.

## expectation

Should recompile only if there is changes?

## notes

sbt version: 1.0.1

**Comment by joan38** [comment] 2017-09-07 10:34
Seems to happen with sbt-buildinfo enabled or whenever there is something generating sources

**Comment by dwijnand** [comment] 2017-09-08 12:09
@joan38 Could you provide a minimised reproduction of the problem, please?

**Comment by joan38** [comment] 2017-09-08 13:29
Hi @dwijnand, sorry I didn't give that before.
I updated with the issue with the reproduction steps.

**Comment by joan38** [comment] 2017-09-11 12:47
Should we label that as Bug and remove the Needs Reproduction Test Case?

**Comment by dwijnand** [comment] 2017-09-21 13:31
https://github.com/sbt/sbt/issues/3565 shows a variant using source generators.

**Comment by tpolecat** [comment] 2017-09-21 17:10
Yep @dwijnand it looks like the same thing. My little buildinfo equivalent gives you runtime access to the compilation time, which is useless enough that I'm happy to turn it off if there's no easy fix on your end.

**Comment by dwijnand** [comment] 2017-10-09 15:42
Minimised:

```scala
sourceGenerators in Compile += Def.task {
  val f = (sourceManaged in Compile).value / "f.scala"
  IO.write(f, "")
  Seq(f)
}.taskValue
```

**Comment by dwijnand** [comment] 2017-10-09 15:43
It's possible that sbt-buildinfo might need to modify its behaviour too. To that end I've also minimised its code to this minimisation:

```scala
sourceGenerators in Compile += Def.task {
  val outFile = (sourceManaged in Compile).value / "sbt-buildinfo" / s"BuildInfo.scala"

  val cacheDir = streams.value.cacheDirectory
  val tempFile = cacheDir / "sbt-buildinfo" / s"BuildInfo.scala"

  val cachedCopyFile =
    Tracked.inputChanged(cacheDir / "sbtbuildinfo-inputs") { (inChanged, _: HashFileInfo) =>
      if (inChanged || !outFile.exists) {
        IO.copyFile(tempFile, outFile, preserveLastModified = true)
      }
    }

  // 1. make the file under cache/sbtbuildinfo.
  // 2. compare its SHA1 against cache/sbtbuildinfo-inputs
  IO.write(tempFile, "")
  cachedCopyFile(FileInfo.hash(tempFile))
  Seq(outFile)
}.taskValue
```

**Comment by dwijnand** [comment] 2017-10-24 10:07
Keeping this open to track it needs a new version of io to be fixed in sbt 1.0.3.

**Closed as completed** 2017-10-24 19:36 UTC
Labels: Regression, area/watch

**Comment by dwijnand** [comment] 2017-10-26 06:44
Closed with https://github.com/sbt/sbt/pull/3634.

**Comment by joan38** [comment] 2017-10-31 17:18
@dwijnand It seems that with SBT 1.0.3 we've been too strong. Now it doesn't pick up changes.

Steps to reproduce:
```
git clone https://github.com/joan38/kubernetes-client
cd kubernetes-client
sbt ~compile
```

Should I open a new issue?

**Comment by eed3si9n** [comment] 2017-10-31 17:22
Someone reported https://github.com/sbt/sbt/issues/3695

**Comment by joan38** [comment] 2017-10-31 17:26
Great, thanks @eed3si9n
