### ISSUE TITLE
1.4.4: `sbt new` should not create a target directory in the working directory

### ISSUE THREAD

**Issue by drewboardman** [sbt/sbt#6281] opened 2021-01-23 15:16 UTC
This is a duplicate of 

https://github.com/sbt/sbt/issues/4339

This happens on 1.4.4.

**Comment by eed3si9n** [comment] 2021-04-06 21:48
Duplicate of https://github.com/sbt/sbt/issues/2835

**Closed as completed by eed3si9n** 2021-04-06 21:48 UTC
