### ISSUE TITLE
Impossible to recover broken SBT session from a thin client

### ISSUE THREAD

**Issue by keynmol** [sbt/sbt#7172] opened 2023-03-09 12:06 UTC
## steps

(the gif describes it better)

1. Have a simple build.sbt like this:

```scala
Global / onChangedBuildSource := ReloadOnSourceChanges

scalaVersion := "3.2.2"
```

2. Start SBT server in the background (as is done by Metals, for example)
3. connect to it from sbtn
4. Modify the `build.sbt` file and a change that breaks it

## problem

Thin client can no longer run any commands, cannot be shutdown, cannot reload the build

## expectation

Some way to recover the session, reload it? 
The only way you can do it is if you have the initial SBT session that started the server open in your terminal but when using SBT as build server you don't have that.

## notes

![2023-03-09 12 01 14](https://user-images.githubusercontent.com/1052965/224018214-065d6d2c-97ca-425f-9f99-3680ef9c10d4.gif)

**Comment by adpi2** [comment] 2023-03-09 14:59
This is a duplicate of https://github.com/sbt/sbt/issues/6840

**Closed as completed by adpi2** 2023-03-09 14:59 UTC
