### ISSUE TITLE
Can't download deb file (https://dl.bintray.com/sbt/debian/sbt-0.13.17.deb). Forbidden 403

### ISSUE THREAD

**Issue by dk8996** [sbt/sbt#6712] opened 2021-11-15 14:02 UTC
## steps

1) Try downloading the file via this url (https://dl.bintray.com/sbt/debian/sbt-0.13.17.deb)

## problem

Can't download deb file (https://dl.bintray.com/sbt/debian/sbt-0.13.17.deb). Forbidden, 403 error.

**Comment by eed3si9n** [comment] 2021-11-15 14:26
duplicate of #6582

**Closed as completed** 2021-11-15 14:27 UTC
Labels: Duplicate, area/linux
