### ISSUE TITLE
Error to run sbt on M1

### ISSUE THREAD

**Issue by cunhazera** [sbt/sbt#6702] opened 2021-11-03 04:01 UTC
## steps

Run `sbt run` (v1.5.5) command in a Play Framework project with Scala 2.12.13

## problem

Can't run `sbt run` in a Mac M1

## expectation

The command should start the application

## notes

```
[error] java.lang.UnsatisfiedLinkError: /Users/user/Library/Caches/JNA/temp/jna685230223668778388.tmp: dlopen(/Users/user/Library/Caches/JNA/temp/jna685230223668778388.tmp, 0x0001): tried: '/Users/user/Library/Caches/JNA/temp/jna685230223668778388.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/jna685230223668778388.tmp' (no such file)
[error] 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
[error] 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
[error] 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
[error] 	at java.lang.Runtime.load0(Runtime.java:811)
[error] 	at java.lang.System.load(System.java:1088)
[error] 	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
[error] 	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988
[error] 	at com.sun.jna.Native.<clinit>(Native.java:195)
[error] 	at io.methvin.watchservice.jna.CarbonAPI.<clinit>(CarbonAPI.java:20)
[error] 	at io.methvin.watchservice.jna.CFStringRef.toCFString(CFStringRef.java:23)
[error] 	at io.methvin.watchservice.MacOSXListeningWatchService.register(MacOSXListeningWatchService.java:128)
[error] 	at io.methvin.watchservice.WatchablePath.register(WatchablePath.java:50)
[error] 	at io.methvin.watcher.DirectoryWatcher.register(DirectoryWatcher.java:341)
[error] 	at io.methvin.watcher.DirectoryWatcher.registerAll(DirectoryWatcher.java:315)
[error] 	at io.methvin.watcher.DirectoryWatcher.<init>(DirectoryWatcher.java:176)
[error] 	at io.methvin.watcher.DirectoryWatcher$Builder.build(DirectoryWatcher.java:117)
[error] 	at play.dev.filewatch.DefaultFileWatchService.watch(DefaultFileWatchService.scala:38)
[error] 	at play.dev.filewatch.FileWatchService$$anon$1.watch(FileWatchService.scala:87)
[error] 	at play.runsupport.Reloader.<init>(Reloader.scala:443)
[error] 	at play.runsupport.Reloader$.reloader$lzycompute$1(Reloader.scala:283)
[error] 	at play.runsupport.Reloader$.play$runsupport$Reloader$$reloader$1(Reloader.scala:275)
[error] 	at play.runsupport.Reloader$.startDevMode(Reloader.scala:306)
[error] 	at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:98)
[error] 	at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:81)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:105)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) java.lang.UnsatisfiedLinkError: /Users/user/Library/Caches/JNA/temp/jna685230223668778388.tmp: dlopen(/Users/user/Library/Caches/JNA/temp/jna685230223668778388.tmp, 0x0001): tried: '/Users/user/Library/Caches/JNA/temp/jna685230223668778388.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/jna685230223668778388.tmp' (no such file)
[error] Total time: 1 s, completed Nov 3, 2021 12:56:56 AM

**Comment by cunhazera** [comment] 2021-11-03 12:13
If I add `PlayKeys.fileWatchService := play.dev.filewatch.FileWatchService.jdk7(play.sbt.run.toLoggerProxy(sLog.value))` to my `build.sbt` I get this error:

```
--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[error] java.lang.NoSuchMethodError: scala.tools.nsc.Settings.bootclasspath()Lscala/tools/nsc/settings/AbsSettings$AbsSetting;
[error] 	at play.twirl.compiler.TwirlCompiler$TemplateAsFunctionCompiler$CompilerInstance.compiler$lzycompute(TwirlCompiler.scala:503)
[error] 	at play.twirl.compiler.TwirlCompiler$TemplateAsFunctionCompiler$CompilerInstance.compiler(TwirlCompiler.scala:481)
[error] 	at play.twirl.compiler.TwirlCompiler$TemplateAsFunctionCompiler$PresentationCompiler$.<init>(TwirlCompiler.scala:549)
[error] 	at play.twirl.compiler.TwirlCompiler$TemplateAsFunctionCompiler$PresentationCompiler$.<clinit>(TwirlCompiler.scala)
[error] 	at play.twirl.compiler.TwirlCompiler$TemplateAsFunctionCompiler$.getFunctionMapping(TwirlCompiler.scala:425)
[error] 	at play.twirl.compiler.TwirlCompiler$.generateCode(TwirlCompiler.scala:326)
[error] 	at play.twirl.compiler.TwirlCompiler$.generateFinalTemplate(TwirlCompiler.scala:377)
[error] 	at play.twirl.compiler.TwirlCompiler$.parseAndGenerateCode(TwirlCompiler.scala:208)
[error] 	at play.twirl.compiler.TwirlCompiler$.compile(TwirlCompiler.scala:176)
[error] 	at play.twirl.sbt.TemplateCompiler$.$anonfun$compile$2(TemplateCompiler.scala:42)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
[error] 	at play.twirl.sbt.TemplateCompiler$.compile(TemplateCompiler.scala:39)
[error] 	at play.twirl.sbt.SbtTwirl$.$anonfun$compileTemplatesTask$1(SbtTwirl.scala:108)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / twirlCompileTemplates) java.lang.NoSuchMethodError: scala.tools.nsc.Settings.bootclasspath()Lscala/tools/nsc/settings/AbsSettings$AbsSetting;
[error] a.a.ActorSystemImpl - Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:97)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:506)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:376)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:606)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:485)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:764)
```

**Comment by SethTisue** [comment] 2021-11-03 14:01
looks like a duplicate of #6162?

**Comment by eed3si9n** [comment] 2021-11-04 08:27
I don't exactly remember the issue number but it's due Play's own watcher using newer JNA. Plz try sbt 1.6.0-M1.

**Closed as completed** 2021-11-04 08:27 UTC
Labels: area/arm_mac

**Comment by cunhazera** [comment] 2021-11-04 17:07
I followed what said @catap in #6162
Installing sbt using macports and updating JNA to the latest version is working 🎉

**Comment by channingwalton** [comment] 2021-11-17 17:23
@cunhazera would you mind describing what you did, I can't see it how to fix it from the thread :/

**Comment by cunhazera** [comment] 2021-11-17 17:58
@channingwalton [install macports](https://www.macports.org/install.php) then run `sudo port install sbt`
Assuming that you are using a M1 Mac and you installed the Azul Zulu JDK, you will need to replace two files: `jna-platform-x.x.x.jar` and `jna-x.x.x.jar`, both are located in `.sbt/boot/scala-x.xx.x/org.scala-sbt/sbt/`. You can download JNA [here](https://github.com/java-native-access/jna#jna).

**Comment by catap** [comment] 2021-11-17 18:17
@cunhazera you don't need to replace anything on macports :) just run `sudo port install openjdk8-zulu sbt` to install Zulu JDK and sbt via macports. After it is finished you'll have:
```
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Zulu 8.58.0.13-CA-macos-aarch64) (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Zulu 8.58.0.13-CA-macos-aarch64) (build 25.312-b07, mixed mode)
```
and working sbt.

If you would like to use another JDK, for example 11 => just use port `openjdk11-zulu`

**Comment by cunhazera** [comment] 2021-11-17 18:27
@catap alright, got it. As I did not install my Java using macports I had to do it.

**Comment by channingwalton** [comment] 2021-11-17 19:05
Thanks all, I've been using brew, installed on a new Mac. I'll try the Zulu JDK to see if that helps.

**Comment by channingwalton** [comment] 2021-11-17 19:10
And that worked! Thanks everyone.

**Comment by channingwalton** [comment] 2021-11-17 21:06
Ah sorry I made an error. Just using the Zulu JDK didn't work, I needed to replace the jna jars. Now it works!

**Comment by catap** [comment] 2021-11-17 21:09
@channingwalton FYI my way doesn't require to replace anything, it just work.

**Comment by channingwalton** [comment] 2021-11-17 21:11
@catap yes that's interesting. The only difference is I'm using brew as far as I can tell.

**Comment by catap** [comment] 2021-11-17 21:11
@channingwalton I spent a lot of time to port zulu JDK to macports, and I'm a man who supports sbt inside macports ;)

**Comment by channingwalton** [comment] 2021-11-17 21:13
I notice that by default the jna version that ends up in the sbt dir is 5.5.0, maybe that's the difference?

**Comment by catap** [comment] 2021-11-17 21:15
@channingwalton personally I'm moved away from brew back to macports when they switched JDK 8 to the last one. I realised that it was a night mare.

Also I was one of the first who bought M1 and macports was the only way to install something ;)

**Comment by channingwalton** [comment] 2021-11-17 21:17
@catap hmm, maybe its time I used macports again …

**Comment by cunhazera** [comment] 2021-11-17 21:28
> I notice that by default the jna version that ends up in the sbt dir is 5.5.0, maybe that's the difference?

try using the latest version of JNA, or uninstall you Java and install again using macports

**Comment by channingwalton** [comment] 2021-11-18 09:15
BTW putting brew and macports aside, if I download set manually I get the same issue so surely this is an SBT issue?

**Comment by channingwalton** [comment] 2022-01-14 11:19
Using sbt 1.6.1 resolved this for me

**Comment by vonbarnekowa** [comment] 2023-06-13 16:26
I'm using the specified Java version and replaced the JNA libs but it isn't working... Any tips ?

```
openjdk version "1.8.0_345"
OpenJDK Runtime Environment (Zulu 8.64.0.19-CA-macos-aarch64) (build 1.8.0_345-b01)
OpenJDK 64-Bit Server VM (Zulu 8.64.0.19-CA-macos-aarch64) (build 25.345-b01, mixed mode)
```

**Comment by catap** [comment] 2023-06-13 16:56
@vonbarnekowa this issue was fixed for years now. Which SBT version have you tried to use? Can you update it?

**Comment by eed3si9n** [comment] 2023-06-13 17:30
We use GitHub issue mostly to track bugs and tasks on sbt development. If you need help, please check this out - https://www.scala-sbt.org/support.html
