### ISSUE TITLE
[1.4.3] `sbt new` should not create a target and a project directory in the working directory 

### ISSUE THREAD

**Issue by KaoCC** [sbt/sbt#6156] opened 2020-11-22 20:17 UTC
## steps

sbt version 1.4.3 
run the following commands:
`sbt new akka/akka-quickstart-scala.g8`  or 
`sbt new scala/scala-seed.g8`

## problem

These will create `target` and `project` folders in the current directory.

## expectation

These directory should not be generated.

**Comment by eed3si9n** [comment] 2020-11-22 20:22
Thanks for the report. I think this is a duplicate of https://github.com/sbt/sbt/issues/5190

**Closed as completed by eed3si9n** 2020-11-22 20:22 UTC
