### ISSUE TITLE
Consider scoping the scala version only in ThisBuild or in Global

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3353] opened 2017-07-21 17:36 UTC
## problem
`scalaVersion` is scoped for every build. This often causes problems when people want to set their scala versions globally, because they are overriden by the sbt defaults.

## expectation
When people override the scala version in `Global` or in `ThisBuild`, sbt should pick up the scala versions from there since sbt does not scope sbt version to every project.

## notes
I am not sure this is technically possible. But I think it's an interesting effort that will make sbt more intuitive. @olafurpg has complained several times that this is the current behaviour.

sbt version: 0.13.x and 1.x.

**Comment by eed3si9n** [comment] 2017-07-21 18:11
Isn't this already the case?

```scala
root> inspect sbtVersion
[info] Setting: java.lang.String = 0.13.16-M1
[info] Description:
[info] 	Provides the version of sbt.  This setting should be not be modified.
[info] Provided by:
[info] 	*/*:sbtVersion
[info] Defined at:
[info] 	(sbt.Defaults) Defaults.scala:137
[info] Delegates:
[info] 	*:sbtVersion
[info] 	{.}/*:sbtVersion
[info] 	*/*:sbtVersion
[info] Related:
[info] 	*/*:sbtVersion
[info] 	*/*:pluginCrossBuild::sbtVersion
```

**Comment by jvican** [comment] 2017-07-21 21:02
I meant `scalaVersion`, but yeah, it's already scoped in `Global`. The issue is another one, where I think sbt could improve the experience. I will open a ticket soon. I'm closing this one.

**Comment by dwijnand** [comment] 2017-07-25 14:28
This issue is valid. `scalaVersion` is defined at project scope: [Defaults.scala](https://github.com/sbt/sbt/blob/v0.13.16-RC1/main/src/main/scala/sbt/Defaults.scala#L247) / [JvmPlugin.scala](https://github.com/sbt/sbt/blob/v0.13.16-RC1/main/src/main/scala/sbt/plugins/JvmPlugin.scala#L30). This is particularly troublesome as it impacts `crossScalaVersions` which _derives_ from `scalaVersion`: https://github.com/sbt/sbt/blob/v0.13.16-RC1/main/src/main/scala/sbt/Defaults.scala#L278.

Here's an example where @jvican had to deal with the interaction here in bintry: https://github.com/sbt/bintry/pull/29.

I'm currently having trouble with this in the scalajson build.

**Comment by jvican** [comment] 2017-07-25 14:32
Yay! Thanks for the catch @dwijnand. I had the feeling this was not an hallucination...

**Comment by jvican** [comment] 2017-07-25 14:34
Guys, in general, we should agree on what's the best and recommended way to have default values for our keys. I think that `ThisBuild` is almost always preferable. Is there any downside of doing it there?
  
We should also recommend plugin authors to scope stuff in `ThisBuild`, especially default implementations for keys. Not doing so ends up being a burden for their users, who expect scope delegation to work.

**Comment by dwijnand** [comment] 2017-07-25 14:38
Anything that is global to the entire sbt engine, such as the default version for a key you're introducing, should be defined (defaulted) `in Global`.

Anything that is not project-specific in your build, such as your organization, `in ThisBuild`.

We should document this.

It's possible that things are the way things are in JvmPlugin because of https://github.com/sbt/sbt/issues/2899.

**Comment by jvican** [comment] 2017-07-25 14:42
> Anything that is global to the entire sbt engine, such as the default version for a key you're introducing, should be defined (defaulted) in Global.
  
Isn't scoping in `Global` going to break the builds of source dependencies by overriding values that should not be overridden?
  
In my experience, people do not want to use `Global`, they generally want `ThisBuild` and I find it a safer alternative under my previous hypothesis that doing otherwise can generate undefined errors in builds with source dependencies. I think source dependencies are important, and we should give them more focus in 1.x.
  
It is going to be my recommended way to build software with sbt, and I'll write a blog post about it. It is certainly very useful for sbt plugins, among others.

**Comment by dwijnand** [comment] 2017-07-25 14:51
Due to the mechanics of `derive` and what we do with it in Defaults (namely define `scalaVersion`, `scalaBinaryVersion` and, specifically, `crossScalaVersions`) this is a regression in sbt 0.13.16-M1.

## steps

Given this build:

```scala
val t = project in file(".")
aggregateProjects(foo, bar)

      scalaVersion in ThisBuild := "2.11.11"
crossScalaVersions in ThisBuild := Seq("2.10.6", "2.11.11", "2.12.2")

val foo = project
val bar = project
```

## problem

In sbt 0.13.16-M1 or sbt 0.13.16-RC1:

```
> show crossScalaVersions
[info] foo/*:crossScalaVersions
[info] 	List(2.11.11)
[info] bar/*:crossScalaVersions
[info] 	List(2.11.11)
[info] t/*:crossScalaVersions
[info] 	List(2.11.11)
```

## expectation

How it used to work, such as in sbt 0.13.15:

```
> show crossScalaVersions
[info] foo/*:crossScalaVersions
[info] 	List(2.10.6, 2.11.11, 2.12.2)
[info] bar/*:crossScalaVersions
[info] 	List(2.10.6, 2.11.11, 2.12.2)
[info] t/*:crossScalaVersions
[info] 	List(2.10.6, 2.11.11, 2.12.2)
```

## notes

The commit that folded sbt-cross-building into sbt introduced the project-scoped `scalaVersion` setting: https://github.com/sbt/sbt/commit/ff017eb475fbf18b8066125596bcd1a8cd8fb3ff#diff-6373e7f7122325e753b75fe1cc76ff5fR247

**Comment by jvican** [comment] 2017-07-25 15:12
It would be lovely to have scripted tests that check the scopes of these things. This way, we won't have regressions on such important keys from now on.

**Comment by eed3si9n** [comment] 2017-07-25 15:34
This is a feature interaction between sbt version cross building and Scala version cross building.

Normally I try not to mess with existing globally-scoped keys, and I was aware that people often define `scalaVersion in ThisBuild`, so I did define a forwarder:

```diff
+    scalaVersion := {
+      val scalaV = scalaVersion.value
+      val sv = (sbtBinaryVersion in pluginCrossBuild).value
+      if (sbtPlugin.value) scalaVersionFromSbtBinaryVersion(sv)
+      else scalaV
+    },
```

I think I just need to do something similar with `crossScalaVersions`.

Note that recently merged https://github.com/sbt/sbt/pull/3356 re-injects `scalaVersion` at project-level on `^^`. This might allow us to remove project-level `scalaVersion` initialization in Defaults, but I considering `^ compile` etc `crossScalaVersions` forwarding still might be needed.

**Closed as completed** 2017-07-26 07:48 UTC
Labels: Regression
