### ISSUE TITLE
sbt new should not create target and project directories in the working directory with sbt version 1.4.5

### ISSUE THREAD

**Issue by logicpluscode** [sbt/sbt#6249] opened 2021-01-13 07:20 UTC
## steps

run 
`sbt new scala/hello-world.g8`

## problem

this creates ./target/ and ./project directories

## expectation

./target and ./project directories shouldn't be created

installed sbt version : 1.4.5

**Comment by eed3si9n** [comment] 2021-04-06 21:46
Duplicate of https://github.com/sbt/sbt/issues/2835

**Closed as completed by eed3si9n** 2021-04-06 21:46 UTC
