### ISSUE TITLE
Intellij Fails to Import Scala Play Project When Upgrading to 1.3.7

### ISSUE THREAD

**Issue by mikail-khan** [sbt/sbt#5409] opened 2020-01-31 15:02 UTC
## steps
sbt version: 1.3.7

## problem
When upgrading to 1.3.7, Intellij fails to import the Scala Play project (see attached screenshot of issue)

![Screenshot_2020-01-31_14-59-29](https://user-images.githubusercontent.com/13503259/73549498-995ca900-443a-11ea-9dbc-900a34b05dae.png)

## expectation
Scala Play project should import without issue

## notes
The only way I can get Intellij to import this project is to downgrade to 1.3.6 and then change it back to 1.3.7

**Comment by eed3si9n** [comment] 2020-01-31 19:01
@mikail-khan Thanks for the report.
This looks like a duplicate of https://github.com/sbt/sbt/issues/5374

**Closed as completed by eed3si9n** 2020-01-31 19:01 UTC
Labels: area/library_management, Regression, area/ide
