### ISSUE TITLE
How to use sbt behind a proxy / firewall that blocks downloading jars?

### ISSUE THREAD

**Issue by zoosky** [sbt/sbt#2679] opened 2016-07-20 12:11 UTC
## steps

Install Linux sbt-launcher.jar

start sbt
## problem

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
download failed: org.scala-sbt#main;0.13.12!main.jar
download failed: org.scala-sbt#actions;0.13.12!actions.jar
download failed: org.scala-sbt#io;0.13.12!io.jar
download failed: org.scala-sbt#completion;0.13.12!completion.jar
download failed: org.scala-sbt#collections;0.13.12!collections.jar
download failed: org.scala-sbt#api;0.13.12!api.jar
download failed: org.scala-sbt#incremental-compiler;0.13.12!incremental-compiler.jar
download failed: org.scala-sbt#compile;0.13.12!compile.jar
download failed: org.scala-sbt#ivy;0.13.12!ivy.jar
download failed: org.scala-sbt#main-settings;0.13.12!main-settings.jar
download failed: org.scala-sbt#command;0.13.12!command.jar
download failed: org.scala-sbt#compiler-interface;0.13.12!compiler-interface.jar
Error during sbt execution: Error retrieving required libraries
  (see /home/aem/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.12
## notes

I tried to deploy a used .ivy2 cache with all the needed resolutions but that produces the same error.

**Comment by evhen14** [comment] 2016-07-21 06:27
I don't think it is a proxy issue. There are no just folders on the repo web-site. For example: https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/ it should contain io or collections folder

**Comment by evhen14** [comment] 2016-07-21 07:52
I had just the same problem and after some research I found out that in my case the issue is not with firewall or proxy but with the way java9 started to treat jar files. For more info go here: http://blog.codefx.org/java/dev/how-java-9-and-project-jigsaw-may-break-your-code/#New-URL-Schema-For-Runtime-Image-Content

As a result  I downgraded to java8 and it works great. Hope it will be helpful. 

PS: It's quite interesting that my installation of Ubuntu 16.04 decided to install java9 as it's not out yet

**Comment by zoosky** [comment] 2016-07-21 20:52
In my case I use JDK 1.8.0. 

The problem might stem from bintray jars /CDN using self signed certificates.

**Comment by eed3si9n** [comment] 2016-07-21 21:13
The sbt issue tracker is not a support system. Please see [how can I get help?](http://www.scala-sbt.org/community.html#how-can-I-get-help)
Unless there's something we can reproduce or if you can identify some action we can take, this case will sit indefinitely, so I suggest we close it.

**Comment by eed3si9n** [comment] 2016-07-21 21:15
See also http://www.scala-sbt.org/0.13/docs/Proxy-Repositories.html for hitting something other than the Internet.

**Comment by zoosky** [comment] 2016-07-22 16:02
@eed3si9n thanks for the poiners. I used sbt in the described environment successfully over the last 2 years. Sometime in the last 3 months things changed.. I'll try to provide some logs.

**Comment by zoosky** [comment] 2016-07-28 11:53
Here is the sbt update.log

**Edit:** moved the long log to https://gist.github.com/eed3si9n/3bfbffb1737625ec25e5fae688fe311e

**Comment by zoosky** [comment] 2016-07-28 12:33
The Issue might stem from an invalid Typesafe Certificate:

`typesafe-ivy-releases: downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.12/jars/main.jar
to /home/aem/.ivy2/cache/org.scala-sbt/main/jars/main-0.13.12.jar.part
WARN: [FAILED ] org.scala-sbt#main;0.13.12!main.jar: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target (1397ms)`

When you load the URL in Chrome https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.12/jars/main.jar the browser complains about an invalid certificate.

![Uploading typesafe.png…]()

**Comment by zoosky** [comment] 2016-08-01 07:02
Sorry for accidentally closing this issue and pasting long log entries.  GitHub did not let me attach files to this issue.

**Comment by eed3si9n** [comment] 2016-08-01 07:27
@zoosky Please use https://gist.github.com/ next time.

**Comment by zoosky** [comment] 2016-08-02 14:16
The Jar URL is located at repo.typesafe.com, from were a 302 redirect leads to  https://dl.bintray.com/typesafe/ivy-releases/

Using wget I get the following error. Java seems to behave in a similar way.

```
aem@vmcnga30t12:~> wget  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.12/jars/compile.jar
--2016-08-02 16:11:52--  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.12/jars/compile.jar
Resolving proxy.example.com (proxy.example.com)... 193.5.217.60
Connecting to proxy.example.com (proxy.example.com)|193.5.217.60|:8080... connected.
Proxy request sent, awaiting response... 302 Moved Temporarily
Location: https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.12/jars/compile.jar [following]
--2016-08-02 16:11:53--  https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.12/jars/compile.jar
Connecting to proxy.example.com (proxy.example.com)|193.5.217.60|:8080... connected.
Proxy request sent, awaiting response... 302
Location: https://akamai.bintray.com/28/28f4982f5a94dd11440b2f24e9c8bd1f39800b1a4470d782f78b82fbe44cf788?__gda__=exp=1470147833~hmac=af07cb59797ef577e16e6cde0dd3bb3cfcf804a9624456483fd67ec2db53139e&response-content-disposition=attachment%3Bfilename%3D%22compile.jar%22&response-content-type=application%2Fjava-archive [following]
--2016-08-02 16:11:53--  https://akamai.bintray.com/28/28f4982f5a94dd11440b2f24e9c8bd1f39800b1a4470d782f78b82fbe44cf788?__gda__=exp=1470147833~hmac=af07cb59797ef577e16e6cde0dd3bb3cfcf804a9624456483fd67ec2db53139e&response-content-disposition=attachment%3Bfilename%3D%22compile.jar%22&response-content-type=application%2Fjava-archive
Connecting to proxy.example.com (proxy.example.com)|193.5.217.60|:8080... connected.
ERROR: cannot verify akamai.bintray.com's certificate, issued by â/CN=akamai.bintray.comâ:
  Self-signed certificate encountered.
To connect to akamai.bintray.com insecurely, use `--no-check-certificate'.
```

**Comment by dwijnand** [comment] 2016-08-02 15:04
Strange, here's it working for me :-/

```
16:03:34 $ wget https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.12/jars/compile.jar
--2016-08-02 16:03:37--  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.12/jars/compile.jar
Resolving repo.typesafe.com... 52.203.61.63, 54.165.237.90
Connecting to repo.typesafe.com|52.203.61.63|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.12/jars/compile.jar [following]
--2016-08-02 16:03:37--  https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.12/jars/compile.jar
Resolving dl.bintray.com... 5.153.35.248, 159.122.18.156
Connecting to dl.bintray.com|5.153.35.248|:443... connected.
HTTP request sent, awaiting response... 302
Location: https://akamai.bintray.com/28/28f4982f5a94dd11440b2f24e9c8bd1f39800b1a4470d782f78b82fbe44cf788?__gda__=exp=1470150938~hmac=df323a250d369c1cab388896574c56ec1b981046d5c80b17d975906667a3fd16&response-content-disposition=attachment%3Bfilename%3D%22compile.jar%22&response-content-type=application%2Fjava-archive [following]
--2016-08-02 16:03:38--  https://akamai.bintray.com/28/28f4982f5a94dd11440b2f24e9c8bd1f39800b1a4470d782f78b82fbe44cf788?__gda__=exp=1470150938~hmac=df323a250d369c1cab388896574c56ec1b981046d5c80b17d975906667a3fd16&response-content-disposition=attachment%3Bfilename%3D%22compile.jar%22&response-content-type=application%2Fjava-archive
Resolving akamai.bintray.com... 23.195.73.64
Connecting to akamai.bintray.com|23.195.73.64|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 249920 (244K) [application/java-archive]
Saving to: ‘compile.jar’

compile.jar                                         100%[================================================================================================================>] 244.06K  --.-KB/s    in 0.03s

2016-08-02 16:03:38 (8.54 MB/s) - ‘compile.jar’ saved [249920/249920]
```

**Comment by eed3si9n** [comment] 2016-08-27 04:45
Works for me:

```
$ wget https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.12/jars/compile.jar
--2016-08-27 00:44:02--  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.12/jars/compile.jar
Resolving repo.typesafe.com... 52.203.61.63, 54.165.237.90
Connecting to repo.typesafe.com|52.203.61.63|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.12/jars/compile.jar [following]
--2016-08-27 00:44:04--  https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.12/jars/compile.jar
Resolving dl.bintray.com... 75.126.118.188, 108.168.243.150
Connecting to dl.bintray.com|75.126.118.188|:443... connected.
HTTP request sent, awaiting response... 302
Location: https://akamai.bintray.com/28/28f4982f5a94dd11440b2f24e9c8bd1f39800b1a4470d782f78b82fbe44cf788?__gda__=exp=1472273767~hmac=01e64ed21fcd70c1fd1675e6f1eac94da40b7fd1666ab0e9d7e7c386a07f88b4&response-content-disposition=attachment%3Bfilename%3D%22compile.jar%22&response-content-type=application%2Fjava-archive&requestInfo=U2FsdGVkX186ZkU8034EOvC5ld5YsppE6C27vHpcZ5Gjn70RQG50dZvKD7wgk3djBR2lx56OGxaSLTnGbVVH4OHeqa9xvxfYwc8fxtfwaPieacEbOFOuYiamvOUSOi1IWIuGtYR8Uy7LYD4qlIzP9w [following]
--2016-08-27 00:44:07--  https://akamai.bintray.com/28/28f4982f5a94dd11440b2f24e9c8bd1f39800b1a4470d782f78b82fbe44cf788?__gda__=exp=1472273767~hmac=01e64ed21fcd70c1fd1675e6f1eac94da40b7fd1666ab0e9d7e7c386a07f88b4&response-content-disposition=attachment%3Bfilename%3D%22compile.jar%22&response-content-type=application%2Fjava-archive&requestInfo=U2FsdGVkX186ZkU8034EOvC5ld5YsppE6C27vHpcZ5Gjn70RQG50dZvKD7wgk3djBR2lx56OGxaSLTnGbVVH4OHeqa9xvxfYwc8fxtfwaPieacEbOFOuYiamvOUSOi1IWIuGtYR8Uy7LYD4qlIzP9w
Resolving akamai.bintray.com... 23.32.185.87
Connecting to akamai.bintray.com|23.32.185.87|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 249920 (244K) [application/java-archive]
Saving to: 'compile.jar'

compile.jar                                     100%[========================================================================================================>] 244.06K  1.26MB/s   in 0.2s

2016-08-27 00:44:10 (1.26 MB/s) - 'compile.jar' saved [249920/249920]
```

**Comment by rahulait** [comment] 2016-11-04 01:04
Same issue for me. If I put my machine on public ip-address and open all ports, then installation works fine. Else, it keeps on failing. Though, I can download the jar files manually as mentioned in the comment above this.

**Comment by rahulait** [comment] 2016-11-04 01:22
Works after following the steps mentioned by francisdb on this issue: https://github.com/sbt/sbt/issues/2536#issuecomment-205491495

For me, the problem seemed to be latest version of java. Switching to 1.8 worked fine without any issues.

**Closed as completed** 2018-05-05 09:51 UTC
Labels: area/proxy
