### ISSUE TITLE
Cannot resolve dependency (but Activator can)

### ISSUE THREAD

**Issue by jkutner** [sbt/sbt#2054] opened 2015-06-13 01:01 UTC
Running `sbt stage` against this application has a different result than `activator stage`:
https://github.com/gifman009/Licenta

More information in this thread:
https://groups.google.com/forum/#!topic/play-framework/RLSPwvOqBIE

```
$ sbt stage
...
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
[warn] :: UNRESOLVED DEPENDENCIES ::
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
[warn] :: com.typesafe.sbtrc#client-2-11;0.3.1: not found
[warn] :: com.typesafe.sbtrc#actor-client-2-11;0.3.1: not found
[warn] ::::::::::::::::::::::::::::::::::::::::::::::

$ activator stage
...
[info] downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbtrc/actor-client-2-11/0.3.1/jars/actor-client-2-11.jar ...
[info]     [SUCCESSFUL ] com.typesafe.sbtrc#actor-client-2-11;0.3.1!actor-client-2-11.jar (36444ms)
[info] downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbtrc/client-2-11/0.3.1/jars/client-2-11.jar
[info]     [SUCCESSFUL ] com.typesafe.sbtrc#client-2-11;0.3.1!client-2-11.jar (196692ms)
...
[info] Done packaging.
[success] Total time: 1028 s, completed Jun 11, 2015 4:57:22 PM
```

If I remove "sbt-fork-run-plugin" from that project, then it resolves the sbtrc dependencies. 
https://github.com/gifman009/Licenta/blob/master/project/play-fork-run.sbt

I'm not sure if this is an Activator or SBT bug.

**Comment by eed3si9n** [comment] 2015-06-23 05:35
Using a fresh Ivy cache, I was able to reproduce this 

```
[computer-database-scala] $ update
....

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbtrc#client-2-11;0.3.1: not found
[warn]  :: com.typesafe.sbtrc#actor-client-2-11;0.3.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      com.typesafe.sbtrc:client-2-11:0.3.1
[warn]        +- com.typesafe.play:fork-run-protocol_2.11:2.3.9 ((play.sbt.forkrun.PlayForkRun) PlayForkRun.scala#L49)
[warn]        +- com.typesafe.play:fork-run_2.11:2.3.9 ((play.sbt.forkrun.PlayForkRun) PlayForkRun.scala#L49)
[warn]        +- computer-database-scala:computer-database-scala_2.11:0.0.1-SNAPSHOT
[warn]      com.typesafe.sbtrc:actor-client-2-11:0.3.1
[warn]        +- com.typesafe.play:fork-run_2.11:2.3.9 ((play.sbt.forkrun.PlayForkRun) PlayForkRun.scala#L49)
[warn]        +- computer-database-scala:computer-database-scala_2.11:0.0.1-SNAPSHOT
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe.sbtrc#client-2-11;0.3.1: not found
[error] unresolved dependency: com.typesafe.sbtrc#actor-client-2-11;0.3.1: not found
[error] Total time: 31 s, completed Jun 23, 2015 1:25:12 AM
[computer-database-scala] $ show fullResolvers
[info] ArrayBuffer(Raw(ProjectResolver(inter-project, mapped: )), FileRepository(local,FileConfiguration(true,None),Patterns(ivyPatterns=List(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=List(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false)), public: https://repo1.maven.org/maven2/, Typesafe Releases Repository: https://repo.typesafe.com/typesafe/releases/)
[success] Total time: 0 s, completed Jun 23, 2015 1:26:26 AM
[computer-database-scala] $ exit
```

Maybe this is a Play (`PlayForkRun`) problem.

**Comment by jkutner** [comment] 2015-07-14 13:47
I found that adding the following to the `build.sbt` resolves the dependency:

```
resolvers += Resolver.url("Typesafe Ivy releases", url("https://repo.typesafe.com/typesafe/ivy-releases"))(Resolver.ivyStylePatterns)
```

I'm not sure why the `ivyStylePatterns` is required. The problem is that when the build runs with the plugin, it needs the extra resolve. I don't think it's possible to add the resolver from the plugin though.

I believe this is the same issue discussed here:
http://stackoverflow.com/questions/30248497/is-it-possible-to-add-a-resolver-to-an-sbt-projects-build-via-an-autoplugin

So this may turn from a bug to feature request.

**Comment by vromancas** [comment] 2015-11-20 00:02
Removing the **project/sbt-ui.sbt** file and the **fork in run := true** entry from the build.sbt file fixed the problem for me

**Comment by worrel** [comment] 2016-07-31 16:18
As I see it, these artifacts are not named correctly.  They should be named `actor-client_2.11` e.g. like the fork-run_2.11 dep.  Presumably that's why the ivyStylePattern thing is needed.  Anyone know why these artifacts have a different naming scheme?

**Comment by zalito12** [comment] 2017-03-30 20:46
Following @vromancas idea, removing `project/sbt-ui.sbt` and `project/play-fork-run.sbt` did the trick for me. I found this problem when clone a project that was created with activator in other windows machine, now working in both. Thanks.

**Comment by silentsudo** [comment] 2018-03-04 04:28
this solved build issues for me, 
Removing: project/sbt-ui.sbt file and the fork in run := true  entry from the build.sbt file  and project/play-fork-run.sbt

**Comment by eed3si9n** [comment] 2018-08-17 04:18
Closing this since it's likely no longer relevant.

**Closed as completed by eed3si9n** 2018-08-17 04:18 UTC
