### ISSUE TITLE
SHA1 mismatch with dependency

### ISSUE THREAD

**Issue by tsuckow** [sbt/sbt#580] opened 2012-10-16 03:30 UTC
### steps
- `git clone git://github.com/eboto/scalaguice-sha-bug.git`
- `cd scalaguice-sha-bug`
- `./sbt update`
## problems

SBT fails to download dependencies located in a Jenkins instance on OpenShift (behind a reverse proxy)
## notes

This result is a SHA1 mismatch
expected=029e25a1fabca555561858d026c63d53588cb01a computed=cded8e55f194026e8fe860ed979993d44ee8ccb9

The computed sha changes occasionally. If I snipe the .part file being downloaded to it appears to contain the desired JAR but includes some HTTP headers in the middle.

```
HTTP/1.1 200 OK^M
Server: Winstone Servlet Engine v0.9.10^M
Last-Modified: Sun, 07 Oct 2012 19:52:06 GMT^M
Expires: Sun, 07 Oct 2012 19:52:06 GMT^M
Accept-Ranges: bytes^M
Content-Type: application/java-archive^M
Content-Length: 59435^M
Connection: Keep-Alive^M
Date: Tue, 16 Oct 2012 03:12:38 GMT^M
X-Powered-By: Servlet/2.5 (Winstone/0.9.10)^
```

Downloading the JAR by any other means results in a JAR with the expected SHA1. Including Gradle.

**Comment by eboto** [comment] 2012-10-18 19:34
I'm the original logger of the issue @tsuckow just referenced. It's worth noting that [importing Salat seems to demonstrate the same issue](https://groups.google.com/forum/?fromgroups=#!topic/simple-build-tool/mxtQI-EPBjI). 

Any idea what could be going on?

**Comment by eboto** [comment] 2012-11-01 21:46
Is this the right issue tracker? Does the project have another main issue tracker?

**Comment by eed3si9n** [comment] 2012-11-02 02:25
@eboto [faq](http://www.scala-sbt.org/release/docs/faq) states that only the confirmed issue should be reported to issue tracker:

> Please use the issue tracker to report confirmed bugs. Do not use it to ask questions. If you are uncertain whether something is a bug, please ask on the mailing list first.

Hopefully we can get some response on the ML thread from the developers soon.

**Comment by eed3si9n** [comment] 2012-11-02 02:52
Using the repro project I was able to reproduce the error on both 0.12.0 and 0.12.1. Here's the output:

```
Getting org.scala-sbt sbt 0.12.1 ...
:: retrieving :: org.scala-sbt#boot-app
    confs: [default]
    40 artifacts copied, 0 already retrieved (8336kB/1461ms)
[info] Loading project definition from /Users/eed3si9n/work/quick-demo/scalaguice-sha-bug/project
[info] Updating {file:/Users/eed3si9n/work/quick-demo/scalaguice-sha-bug/project/}default-cb83d9...
[info] Resolving org.scala-sbt#precompiled-2_10_0-m7;0.12.1 ...
[info] Done updating.
[info] Set current project to default-5d1780 (in build file:/Users/eed3si9n/work/quick-demo/scalaguice-sha-bug/)
[info] Updating {file:/Users/eed3si9n/work/quick-demo/scalaguice-sha-bug/}default-5d1780...
[info] Resolving com.google.code.findbugs#jsr305;1.3.9 ...
[info] downloading https://jenkins-codingwell.rhcloud.com/job/Scala-Guice/lastSuccessfulBuild/artifact/repo/uk/me/lings/scala-guice_2.9.2/3.0.1-SNAPSHOT/scala-guice_2.9.2-3.0.1-SNAPSHOT.jar ...
[warn]  [FAILED     ] uk.me.lings#scala-guice_2.9.2;3.0.1-SNAPSHOT!scala-guice_2.9.2.jar: invalid sha1: expected=029e25a1fabca555561858d026c63d53588cb01a computed=7f1d1d050e1404740ec8b0cc167868194e96621e (10457ms)
[warn]  [FAILED     ] uk.me.lings#scala-guice_2.9.2;3.0.1-SNAPSHOT!scala-guice_2.9.2.jar: invalid sha1: expected=029e25a1fabca555561858d026c63d53588cb01a computed=7f1d1d050e1404740ec8b0cc167868194e96621e (10457ms)
[warn] ==== scalaGuiceResolvers: tried
[warn]   https://jenkins-codingwell.rhcloud.com/job/Scala-Guice/lastSuccessfulBuild/artifact/repo/uk/me/lings/scala-guice_2.9.2/3.0.1-SNAPSHOT/scala-guice_2.9.2-3.0.1-SNAPSHOT.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: uk.me.lings#scala-guice_2.9.2;3.0.1-SNAPSHOT!scala-guice_2.9.2.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: download failed: uk.me.lings#scala-guice_2.9.2;3.0.1-SNAPSHOT!scala-guice_2.9.2.jar
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:214)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:121)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:102)
    at sbt.IvySbt.liftedTree1$1(Ivy.scala:49)
    at sbt.IvySbt.action$1(Ivy.scala:49)
    at sbt.IvySbt$$anon$3.call(Ivy.scala:58)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:75)
    at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:79)
    at xsbt.boot.Using$.withResource(Using.scala:11)
    at xsbt.boot.Using$.apply(Using.scala:10)
    at xsbt.boot.Locks$GlobalLock.liftedTree1$1(Locks.scala:51)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:51)
    at xsbt.boot.Locks$.apply0(Locks.scala:30)
    at xsbt.boot.Locks$.apply(Locks.scala:27)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:58)
    at sbt.IvySbt.withIvy(Ivy.scala:99)
    at sbt.IvySbt.withIvy(Ivy.scala:95)
    at sbt.IvySbt$Module.withModule(Ivy.scala:114)
    at sbt.IvyActions$.update(IvyActions.scala:121)
    at sbt.Classpaths$$anonfun$work$1$1.apply(Defaults.scala:951)
    at sbt.Classpaths$$anonfun$work$1$1.apply(Defaults.scala:949)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$54.apply(Defaults.scala:972)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$54.apply(Defaults.scala:970)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:974)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:969)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:977)
    at sbt.Classpaths$$anonfun$45.apply(Defaults.scala:856)
    at sbt.Classpaths$$anonfun$45.apply(Defaults.scala:853)
    at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
    at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
    at sbt.std.Transform$$anon$5.work(System.scala:71)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:238)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
[error] (*:update) sbt.ResolveException: download failed: uk.me.lings#scala-guice_2.9.2;3.0.1-SNAPSHOT!scala-guice_2.9.2.jar
[error] Total time: 20 s, completed Nov 1, 2012 10:37:06 PM
```

The computed SHA1 changes between the runs, which is weird.

**Comment by eed3si9n** [comment] 2014-04-01 19:03
At least for salat, the problem was coming from Typesafe's repo:

> I noticed that in both salat's case and in scala-guice's case the build is pulling from a SNAPSHOT dependency.
> I also noticed that salat-util_2.9.1-1.9.2-SNAPSHOT.jar.sha1 is returning 404:
> http://repo.typesafe.com/typesafe/snapshots/com/novus/salat-util_2.9.1/1.9.2-SNAPSHOT/salat-util_2.9.1-1.9.2-SNAPSHOT.jar.sha1

We need to check if this still a sbt issue.

**Comment by eed3si9n** [comment] 2018-01-03 20:08
I am going to close this for now. Let me know if the problem is still there on the latest sbt 1.

**Closed as completed by eed3si9n** 2018-01-03 20:08 UTC
Labels: needs info
