### ISSUE TITLE
SNAPSHOT dependency with classifiers not updated

### ISSUE THREAD

**Issue by wedens** [sbt/sbt#1676] opened 2014-10-15 05:41 UTC
Ref #641

sbt version: 0.13.5
1. old version of dependency in local ivy cache
2. publish updated dependency to nexus repository
3. sbt update
4. cache still contains old version

Dependency declared like:

```
libraryDependencies += "org.test" %% "dep" % "0.1-SNAPSHOT" classifier "assembly" intransitive()
```

from `sbt last`:

```
[info] Resolving org.test#dep_2.11;0.1-SNAPSHOT ...
[debug] sbt-chain: Checking cache for: dependency: org.test#dep_2.11;0.1-SNAPSHOT {compile=[default(compile)]}
[debug] don't use cache for org.test#dep_2.11;0.1-SNAPSHOT: changing=true
[debug] don't use cache for org.test#dep_2.11;0.1-SNAPSHOT: changing=true
[debug]                 tried /home/user/.ivy2/local/org.test/dep_2.11/0.1-SNAPSHOT/ivys/ivy.xml
[debug]         local: no ivy file found for org.test#dep_2.11;0.1-SNAPSHOT
[debug] don't use cache for org.test#dep_2.11;0.1-SNAPSHOT: changing=true
[debug]         maven-metadata not available: /home/user/.m2/repository/org/test/dep_2.11/0.1-SNAPSHOT/maven-metadata.xml
[debug]                 tried file:/home/user/.m2/repository/org/test/dep_2.11/0.1-SNAPSHOT/dep_2.11-0.1-SNAPSHOT.pom
[debug]         Maven2 Local: no ivy file found for org.test#dep_2.11;0.1-SNAPSHOT
[debug] don't use cache for org.test#dep_2.11;0.1-SNAPSHOT: changing=true
[debug]                 tried http://nexus.domain.lan/nexus/content/groups/public/org/test/dep_2.11/0.1-SNAPSHOT/dep_2.11-0.1-SNAPSHOT.pom
[debug]         test-proxy: found md file for org.test#dep_2.11;0.1-SNAPSHOT
[debug]                 => http://nexus.domain.lan/nexus/content/groups/public/org/test/dep_2.11/0.1-SNAPSHOT/dep_2.11-0.1-SNAPSHOT.pom (0.1-SNAPSHOT)
[debug]         default-cache: revision in cache (not updated): org.test#dep_2.11;0.1-SNAPSHOT
[debug]         found org.test#dep_2.11;0.1-SNAPSHOT in sbt-chain

[NOT REQUIRED] org.test#dep_2.11;0.1-SNAPSHOT!dep_2.11.jar
```

**Comment by eed3si9n** [comment] 2014-10-15 07:43
Could you try sbt 0.13.6? There's been fix on SNAPSHOT handling.

**Comment by wedens** [comment] 2014-10-15 08:28
same problem :disappointed:

**Comment by eed3si9n** [comment] 2014-10-15 08:45
Do you see the same behavior without `classifier "assembly"`?

**Comment by wedens** [comment] 2014-10-15 08:51
No. I validated it again and problem appears only with classifier.

**Comment by eric-leblouch** [comment] 2014-12-17 09:09
Reproduced the issue with sbt 0.13.7. Only for dependencies SNAPSHOT with a classifier.

**Comment by kahliburke** [comment] 2015-01-13 01:54
This one is a big problem for groups like mine which use Play 2.3 and have multi module applications. Play 2.3 introduced an asset jar that is produced by creating an artifact with the "assets" classifier.

We have sbt projects that depend on a base project and its assets, so I include those in the sub project with:

```
libraryDependencies ++= Seq(
  "org" % "base" % "version-SNAPSHOT",
  "org" % "base" % "version-SNAPSHOT" classifier("assets")
)
```

When we publish new versions of the base to nexus and then rebuild the sub project, only the main jar is downloaded to the ivy cache, the assets jar is never updated once it's in the ivy cache.

This seems to have nothing to do with the updateOptions cached resolution flag introduced in 0.13.7. This behavior seems to exist in 0.13.5 as well, I couldn't go back before that without more major changes to the project build so I didn't check.

The only workaround I have come up with for now is to use something like sbt-dirty-money to delete the file from the ivy cache before update.

```
import sbtdirtymoney.Plugin._
lazy val clearCachedAssetsJar = taskKey[Unit]("Delete the assets from ivy cache")
project.settings(
    clearCachedAssetsJar := {
      cleanCache.toTask(s""" "org" % "base"""").value
    }
    update <<= update dependsOn clearCachedAssetsJar
```

Thanks for your attention on it, I looked at the code but I'm not sure where I could jump in to fix it, given the fact that there are several issues with SNAPSHOT and classifier resolution, combined with the cachedResolution settings. Do you have any update on if this is likely to be fixed soon?

**Comment by jsuereth** [comment] 2015-02-26 17:30
Can you try this in sbt 0.13.8-M6 and add the maven plugin -> https://github.com/sbt/sbt/blob/0.13/notes/0.13.8.markdown#maven-resolver-plugin

I think we may have fixed some of the crucial -SNAPSHOT issues by using Aether.

**Comment by kahliburke** [comment] 2015-02-27 20:35
I tried this and it's not working upon my first attempt. I am trying to figure out if it's a problem on my end.  I'm getting failures with checksums and downloading artifacts against our nexus server. However everything is working properly (with the exception of this bug) when using ivy. I am getting warnings like the following (I have replaced some strings with xxx for privacy):

```
WARN org.eclipse.aether.internal.impl.WarnChecksumPolicy - Could not validate integrity of download     
from http://xxxx/content/groups/xxxx.pom: Checksum validation failed, expected 
3eb838c6a6d84e9004586eb5eacf33560a613f7f but is     
da39a3ee5e6b4b0d3255bfef95601890afd80709
```

Then I also get errors downloading artifacts.

```
[error] Failed to resolve artifacts from xxx, Could not find artifact 
xxxx:yyy:jar:4.0.0-20150202.185028-129 in xxxx (http://xxxx/content/groups/xxxxx)
```

I simply made the changes to use sbt 0.13.8-M6 (in build.properties) and added addMavenResolverPlugin to plugins.sbt.

This checksum (da39a3ee5e6b4b0d3255bfef95601890afd80709) refers to an empty file, so I'm trying to figure out why this is happening, if it's something weird with our nexus server or a bug in the way SBT with aether plugin is communicating with it. But I'm posting this here in case you've run into anything similar. Thanks, I will update if I figure out the issue here.

**Comment by LukaszMarchewka** [comment] 2015-06-09 18:21
0.13.8 still have the same problem: snapshot with classifier. I have used artefactory instead of nexus.

**Comment by eed3si9n** [comment] 2015-06-24 03:36
Are the artifacts pushed to the same repository via `publish`? 
Or are `publishLocal` and `publish` being mixed? If so that's #1514

**Comment by wedens** [comment] 2015-06-24 03:39
I was publishing via `publish`

**Comment by eed3si9n** [comment] 2015-06-24 03:42
@wedens Does b1aa263b7f281496960e1bcf3534406e068277e5 capture this issue? I am having hard time reproducing the issue via scripted.

**Comment by wedens** [comment] 2015-06-24 03:52
@eed3si9n yes, I think so

**Comment by eed3si9n** [comment] 2015-06-24 04:00
@wedens the test doesn't fail on my machine:

```
sbtRoot> scripted dependency-management/snapshot-classifier-resolution
....
About to run tests: 
 * dependency-management/snapshot-classifier-resolution

Running dependency-management / snapshot-classifier-resolution
[success] Total time: 64 s, completed Jun 23, 2015 11:54:52 PM
```

**Comment by quelgar** [comment] 2015-07-08 23:59
For what it's worth, I'm also seeing this.
- sbt 0.13.8
- Play assets JAR
- Published via `publish` to a local Maven repository on an Artifactory server

**Comment by dwijnand** [comment] 2015-08-17 18:57
Having worked on #1750 it looks like this ticket could subsumes that..

**Comment by ryano144** [comment] 2015-11-05 21:00
Is this still in scope for the 0.13.10 release?

**Comment by eed3si9n** [comment] 2015-12-03 22:59
Closing as duplicate of #1750, which is fixed in 0.13.

**Comment by dwijnand** [comment] 2015-12-04 04:37
I don't think it is, the fix for #1750 is docs/srcs specific.. unfortunately

**Comment by nik-kashi** [comment] 2016-04-20 09:03
This problem still exists in latest version
`sbt.version=0.13.11`

and in my build.sbt :

```
libraryDependencies ++= Seq(
...
"com.rh.cores" % "treasury" % treasuryVer changing(),
  "com.rh.cores" % "treasury" % treasuryVer % Test classifier "tests" changing(),
...
```

but after executing `sbt update` only main dependencies updated and "tests" classified  dependencies does not update.
I should remove them manually from .ivy2 folder

**Note that the version is snapshot**

**Comment by kostaskougios** [comment] 2016-05-18 13:28
I've as well got this issue on 0.13.11. The xxx-SNAPSHOT-tests.jar is not updated unless I manually delete it from .ivy2/cache

**Comment by sometao** [comment] 2017-07-13 14:28
have same problem.

sbt 0.13.15
"org.nd4j" % "nd4j-native" % "0.8.1-SNAPSHOT" classifier "" classifier "windows-x86_64"

**Comment by mverbist** [comment] 2018-09-04 12:10
apparently still an issue in 
sbt 1.1.6

`% "1.0.0-SNAPSHOT" % Test classifier "tests"`

**Comment by athempel** [comment] 2019-05-01 15:18
I can confirm this is still an issue in sbt 1.2.8.

The problem appears to be at https://github.com/sbt/ivy/blob/cb9cc189e9f3af519f9f102e6c5d446488ff6832/src/java/org/apache/ivy/core/cache/DefaultRepositoryCacheManager.java#L1385

If cached metadata is found to be out-of-date, an attempt is made to delete an unclassified artifact from the cache, but classified artifacts are left.

**Comment by athempel** [comment] 2019-05-01 15:45
Here's the upstream issue:

https://issues.apache.org/jira/browse/IVY-1221?jql=project%20%3D%20IVY%20AND%20text%20~%20%22snapshot%20cache%20classifier%22

**Comment by eed3si9n** [comment] 2019-09-26 03:19
I am going to preemptively close this as hopefully-fixed-in-Coursier.
Please let us know if this not the case.

**Closed as completed by eed3si9n** 2019-09-26 03:19 UTC
Labels: Needs Reproduction Test Case, area/library_management
