### ISSUE TITLE
super shell starts blinking after reload?

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5547] opened 2020-05-10 23:09 UTC
## steps

1. run some long-running task
2. reload
3. run some long-running task again

## problem

super shell starts blinking

[![asciicast](https://asciinema.org/a/L54jMB12g12M8u5HvCfqyVVC6.svg)](https://asciinema.org/a/L54jMB12g12M8u5HvCfqyVVC6)

## expectation

no blinking.

## notes

potentially related https://github.com/sbt/sbt/pull/5531

**Comment by eatkins** [comment] 2020-05-10 23:34
I am almost certain I have a fix for this on a wip branch. IIRC, the problem is that multiple progress threads can be started and they interfere which each other, causing the blinking. My guess in this case is that the original progress thread wasn’t killed after the ctrl+c. Part of the fix is to rework TaskProgress to automatically stop the thread if there are no tasks. I think I also made further changes elsewhere to try and ensure there was only ever at most one progress thread running.

**Closed as completed** 2020-07-02 22:27 UTC
Labels: area/shell
