### ISSUE TITLE
`sbt fullClasspath > out.txt` adds invisible symbols to output 

### ISSUE THREAD

**Issue by danielleontiev** [sbt/sbt#6232] opened 2020-12-27 02:25 UTC
## steps

Setup Scala CI using this https://github.com/danielleontiev/sbt-invisible-symbol/blob/master/.github/workflows/scala.yml configuration for GitHub Actions or this https://github.com/danielleontiev/sbt-invisible-symbol/blob/master/gitlab-ci.yml configuration for GitLab CI

## problem

File "out.txt" contains invisible symbol:

[image](https://imgur.com/a/j89VuyF)

You could check "out.txt" here https://github.com/danielleontiev/sbt-invisible-symbol/runs/1612704297
Click on "artifacts" and download the archive

## expectation

File "out.txt" should contain only classpath

## notes

This behavior is reproducible only in CI for some reason. I've tried to reproduce it locally on Ubuntu 20.04, Arch Linux and on MacOS, but with no luck

**Comment by reminia** [comment] 2023-11-17 16:52
Meet the same issue. 
Trying to run a sbt command in github workflow, an invisible symbol is appended to the command output.
Not sure it's due to sbt or github ci env.

The command I try to run:
sbt  'show version' | tail -n 1

Due to the invisible symbol, there's no any output. It takes me a lot of time to debug issue.
Not sure why the behavior is not consistent in github ci and local shell.

**Comment by SethTisue** [comment] 2023-11-18 00:46
does using `export fullClasspath` instead help?

does `--no-colors` help?

**Comment by reminia** [comment] 2023-11-18 16:06
@SethTisue  it works with -no-colors, see my [job](https://github.com/reminia/json2struct/actions/runs/6914920179/job/18813280090).
Amazing! It took me quite a while to debug.

**Comment by eed3si9n** [comment] 2023-11-18 20:34
Closing this issue. Thanks Seth!

**Closed as not planned** 2023-11-18 20:35 UTC

**Comment by danielleontiev** [comment] 2023-11-19 20:28
Probably, `sbt` should detect if its output is redirected to a file and disable color by itself. Otherwise it's a very subtle issue to troubleshoot. It's what `git`, `ls` and many others do using [`isatty`](https://man7.org/linux/man-pages/man3/isatty.3.html) call

**Comment by eed3si9n** [comment] 2023-11-20 08:12
Yea, to be fair there was an issue along the same line https://github.com/sbt/sbt/issues/4284 and I did try to fix it as https://github.com/sbt/util/pull/184 back in 2018, or at least attempted to fix it. As far as I know, if you redirect the output to `> out.txt` it should by default print out without ANSI color.

```
sbt "show Compile/compile" > out.txt
....
[warn] To keep the same meaning in 2.12 and 2.13, un-import MergeStrategy by adding `MergeStrategy => _` to the import list.
[warn] import sbtassembly.AssemblyPlugin.autoImport.{ Assembly => _, _ }
[warn]        ^
[warn] one warning found
[info] done compiling
[info] Analysis: 19 Scala sources, 37 classes, 20 binary dependencies
```

**Comment by danielleontiev** [comment] 2023-11-20 10:15
Yes, it works as intended on my local machine, but in CI it keeps color codes.

Here I've updated my example in new branch: https://github.com/danielleontiev/sbt-invisible-symbol/blob/november-2023/.github/workflows/scala.yml#L18

It produces `out.txt`: https://github.com/danielleontiev/sbt-invisible-symbol/suites/18335739744/artifacts/1060970990

Which contains ANSI color codes:

```
[0m[[0m[0minfo[0m] [0m[0mwelcome to sbt 1.9.7 (Eclipse Adoptium Java 11.0.21)[0m
[0m[[0m[0minfo[0m] [0m[0mloading project definition from /home/runner/work/sbt-invisible-symbol/sbt-invisible-symbol/project[0m
[0m[[0m[0minfo[0m] [0m[0mloading settings for project sbt-invisible-symbol from build.sbt ...[0m
[0m[[0m[0minfo[0m] [0m[0mset current project to test (in build file:/home/runner/work/sbt-invisible-symbol/sbt-invisible-symbol/)[0m
[0m[[0m[0minfo[0m] [0m[0mAnalysis: [0m
[0m[[0m[32msuccess[0m] [0m[0mTotal time: 0 s, completed Nov 20, 2023, 9:57:48 AM[0m
[0J

```

**Comment by SethTisue** [comment] 2023-11-21 16:06
> it works as intended on my local machine, but in CI it keeps color codes

For this to progress, someone would need to analyze the underlying cause for the difference.

**Comment by danielleontiev** [comment] 2023-11-21 23:27
I've tried the following code:

```scala
object Main extends App {
  val hasConsole = Option(java.lang.System.console).isDefined
  val isDumb = Some("dumb") == sys.env.get("TERM")
  val isDumbTerminal = isDumb || System.getProperty("jline.terminal", "") == "none"
  val isCI = System.getProperty("sbt.ci", "") == "true" || sys.env.contains("BUILD_NUMBER") || sys.env.contains("CI")
  val isEmacs = sys.env.contains("INSIDE_EMACS")

  println("hasConsole: " + hasConsole)
  println("isDumb: " + isDumb)
  println("isDumbTerminal: " + isDumbTerminal)
  println("isCI: " + isCI)
  println("isEmacs: " + isEmacs)
  println()
  println(
    "useColor: " + ((hasConsole && !isDumbTerminal) || isCI || isEmacs)
  )
}
```

trying to mimick this
https://github.com/sbt/sbt/blob/213e933be673588fe2e19d500dc8810049856ecb/internal/util-logging/src/main/scala/sbt/internal/util/Terminal.scala#L362

and running with

```sh
sbt run > out.txt
```

both in Github Actions and locally.

In CI it shows `isCI: true` because of
https://github.com/sbt/sbt/blob/213e933be673588fe2e19d500dc8810049856ecb/internal/util-logging/src/main/scala/sbt/internal/util/Terminal.scala#L218-L219
GitHub Actions indeed set `CI` environment variable to `true`.

If I am not mistaken this condition seems to fool the `sbt` into turning the colors on. At least running

```sh
CI=true sbt "show Compile/compile" > out.txt
```

also adds ANSI colors to output file

**Comment by SethTisue** [comment] 2023-11-22 03:54
Ah, so, working as designed, as per https://github.com/sbt/sbt/pull/5777

Not clear what the best or “right“ design is here. The explanation on that PR is murky to me. But many CI environments are capable of displaying colored logs, so I can see some logic behind enabling colors by default in that context, even though the output isn't a terminal.
