### ISSUE TITLE
[0.13.13] test class autocompletion broken

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt#2822] opened 2016-11-03 09:42 UTC
## steps

sbt 0.13.12
```
clean
test:compile
testOnly [tab]
Display all 126 possibilities? (y or n)
--                                                                        ApplicationSpec                                                          IntegrationSpec
foo.bar.MySpec
...                                                
```

sbt 0.13.13
```
clean
test:compile
testOnly [tab]
--
```

We are using specs2 on a multi-module project

**Comment by eed3si9n** [comment] 2016-11-03 15:16
Thanks for reporting this.

**Comment by francisdb** [comment] 2016-11-24 11:37
can this be marked as a bug / regression?

**Comment by koertkuipers** [comment] 2016-11-29 02:38
i just ran into this with scalatest as well

**Comment by mriehl** [comment] 2016-12-27 08:34
Hi, any way to help solve this issue? SBT 0.13.13 is so good, but this issue is holding it back (the time I gained on compile is lost on copy pasting test paths into the SBT shell).

I noticed that when upgrading SBT the completion still works for the old tests (until a `clean`) so I reckon the completion is not broken, it's the "generate stuff that is used by the completion" part that doesn't seem to work anymore. I can do a PR if it's not a systemic issue, especially if someone points me to the way autocompletion is handled in SBT :)

**Comment by dwijnand** [comment] 2016-12-27 08:40
@mriehl you could start by seeing if this is still broken in 0.13.14-SNAPSHOT (ie. a local build of latest sbt).

I wouldn't be surprised if this were already fixed by @eed3si9n's fix of build level key completion.

**Comment by mriehl** [comment] 2016-12-27 08:40
@dwijnand Nice, I'm off to trying that out ASAP. Thank you!

**Comment by mriehl** [comment] 2016-12-27 12:20
I'm afraid I'm unable to get 0.13.14-SNAPSHOT to work, after a `publishLocal` of sbt with javac 1.6.x (bails out otherwise) running the launcher jar from `launch/target` on another project nets me a resolution error for `org.scala-sbt#compiler-interface;0.13.14-SNAPSHOT!compiler-interface.jar(src)` :/

**Comment by xuwei-k** [comment] 2017-01-06 06:02
https://github.com/xuwei-k/sbt-jol/commit/7dc2e10925f5662a054b45d58264b8748f7ba9eb#diff-4e3c125922202e6220ef0a1510208da4R39
maybe same issue ?

**Comment by dwijnand** [comment] 2017-01-06 08:02
@xuwei-k no that's #1444

**Comment by dwijnand** [comment] 2017-01-12 14:52
I expect this to be broken for the same root cause as #1444: the `:=`/`.value` syntax broke [definedTestNames](https://github.com/sbt/sbt/blob/v0.13.13/main/src/main/scala/sbt/Defaults.scala#L430).

**Comment by dwijnand** [comment] 2017-01-13 15:01
Fixed in https://github.com/sbt/sbt/pull/2908 (pending merge)

**Closed as completed** 2017-01-13 18:58 UTC
Labels: Regression

**Comment by analytically** [comment] 2017-01-30 13:19
0.13.14-SNAPSHOT doesn't work for me
