### ISSUE TITLE
AutoPlugin additionalProjects

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2645] opened 2016-06-17 21:55 UTC
As transition path from `sbt.Build`, consider defining the following method to AutoPlugin:

``` scala
def additionalProjects: List[Project]
```
## expectation

When an auto plugin is enabled, it adds `additionalProjects` to the build.
## notes

I'm not 100% sure if this feature is feasible. By the time auto plugins are enabled per subprojects, Load should know the list of subprojects already.

**Comment by dwijnand** [comment] 2016-08-14 18:56
@eed3si9n is this a duplicate of #2532?

**Comment by dwijnand** [comment] 2016-08-18 22:57
I'm going to close this as duplicate of #2532, let me know what I'm missing if I'm wrong.

**Closed as completed by dwijnand** 2016-08-18 22:57 UTC
Labels: Enhancement
