### ISSUE TITLE
Reinstallation if SBT doesn't work

### ISSUE THREAD

**Issue by mukesh14j** [sbt/sbt#3462] opened 2017-08-18 16:30 UTC
(See the guidelines for contributing, linked above)

## steps
1) Install the SBT in windows 7.
2) uninstall and install again SBT
3) set the path of SBT in path variable
4) now open the command prompt and type sbt

## problem
It gives an error 
Error during SBT execution:Label <!DOCTYPE html> us not in section

## expectation

Should run successfully without any error

## notes
Both times the installation path are different and environment variables also have been updated

sbt version: 0.13.0

**Comment by dwijnand** [comment] 2017-08-18 16:51
Duplicate of #3463

**Closed as completed by dwijnand** 2017-08-18 16:51 UTC
