### ISSUE TITLE
thrashing (hangs in "Reapplying settings...") on `~ + testQuick`

### ISSUE THREAD

**Issue by wookietreiber** [sbt/sbt#1962] opened 2015-04-09 09:57 UTC
I am using `~ + testQuick` and sbt starts to hang / get stuck with the last output being `Reapplying settings...`. Here's the threaddump (visualvm, hope this helps):

```
2015-04-09 11:40:23
Full thread dump OpenJDK 64-Bit Server VM (24.75-b04 mixed mode):

"RMI TCP Accept-0" daemon prio=10 tid=0x00007f08ac266800 nid=0x5516 runnable [0x00007f08efcfb000]
   java.lang.Thread.State: RUNNABLE
    at java.net.PlainSocketImpl.socketAccept(Native Method)
    at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
    at java.net.ServerSocket.implAccept(ServerSocket.java:530)
    at java.net.ServerSocket.accept(ServerSocket.java:498)
    at sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(LocalRMIServerSocketFactory.java:52)
    at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:399)
    at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:371)
    at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
    - None

"Attach Listener" daemon prio=10 tid=0x00007f08d0002000 nid=0x5514 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
    - None

"AWT-XAWT" daemon prio=10 tid=0x00007f087c0cc800 nid=0x519a runnable [0x00007f089664c000]
   java.lang.Thread.State: RUNNABLE
    at sun.awt.X11.XToolkit.waitForEvents(Native Method)
    at sun.awt.X11.XToolkit.run(XToolkit.java:541)
    at sun.awt.X11.XToolkit.run(XToolkit.java:505)
    at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
    - None

"Java2D Disposer" daemon prio=10 tid=0x00007f087c0b0000 nid=0x5199 in Object.wait() [0x00007f08ec1d9000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    - waiting on <0x00000000a1ea8998> (a java.lang.ref.ReferenceQueue$Lock)
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
    - locked <0x00000000a1ea8998> (a java.lang.ref.ReferenceQueue$Lock)
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
    at sun.java2d.Disposer.run(Disposer.java:145)
    at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
    - None

"Service Thread" daemon prio=10 tid=0x00007f0904174000 nid=0x510f runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
    - None

"C2 CompilerThread1" daemon prio=10 tid=0x00007f0904171800 nid=0x510e waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
    - None

"C2 CompilerThread0" daemon prio=10 tid=0x00007f090416e800 nid=0x510d waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
    - None

"Signal Dispatcher" daemon prio=10 tid=0x00007f090416c800 nid=0x510c runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
    - None

"Finalizer" daemon prio=10 tid=0x00007f0904141800 nid=0x510b in Object.wait() [0x00007f08fb0ef000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    - waiting on <0x00000000a05dc058> (a java.lang.ref.ReferenceQueue$Lock)
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
    - locked <0x00000000a05dc058> (a java.lang.ref.ReferenceQueue$Lock)
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
    at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

   Locked ownable synchronizers:
    - None

"Reference Handler" daemon prio=10 tid=0x00007f090413f800 nid=0x510a in Object.wait() [0x00007f08fb1f0000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    - waiting on <0x00000000a05dbcd0> (a java.lang.ref.Reference$Lock)
    at java.lang.Object.wait(Object.java:503)
    at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)
    - locked <0x00000000a05dbcd0> (a java.lang.ref.Reference$Lock)

   Locked ownable synchronizers:
    - None

"main" prio=10 tid=0x00007f0904008800 nid=0x5104 runnable [0x00007f090b1b2000]
   java.lang.Thread.State: RUNNABLE
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
    at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:176)
    at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
    at scala.collection.SeqLike$class.$colon$plus(SeqLike.scala:529)
    at scala.collection.AbstractSeq.$colon$plus(Seq.scala:40)
    at sbt.Init$class.append(Settings.scala:168)
    at sbt.Def$.append(Def.scala:10)
    at sbt.Init$$anonfun$add$1.apply(Settings.scala:165)
    at sbt.Init$$anonfun$add$1.apply(Settings.scala:165)
    at sbt.IMap$IMap0.mapValue(PMap.scala:52)
    at sbt.IMap$IMap0.mapValue(PMap.scala:46)
    at sbt.Init$class.add(Settings.scala:165)
    at sbt.Def$.add(Def.scala:10)
    at sbt.Init$$anonfun$grouped$1.apply(Settings.scala:162)
    at sbt.Init$$anonfun$grouped$1.apply(Settings.scala:162)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
    at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
    at sbt.Init$class.grouped(Settings.scala:162)
    at sbt.Def$.grouped(Def.scala:10)
    at sbt.Init$class.compiled(Settings.scala:136)
    at sbt.Def$.compiled(Def.scala:10)
    at sbt.Init$class.make(Settings.scala:144)
    at sbt.Def$.make(Def.scala:10)
    at sbt.Project$.makeSettings(Project.scala:350)
    at sbt.Load$.reapply(Load.scala:187)
    at sbt.BuiltinCommands$.reapply(Main.scala:233)
    at sbt.Cross$$anonfun$switchVersion$2.apply(Cross.scala:77)
    at sbt.Cross$$anonfun$switchVersion$2.apply(Cross.scala:34)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    at sbt.Command$.process(Command.scala:92)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.State$$anon$1.process(State.scala:184)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.MainLoop$.next(MainLoop.scala:98)
    at sbt.MainLoop$.run(MainLoop.scala:91)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
    at sbt.Using.apply(Using.scala:24)
    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
    at sbt.MainLoop$.runLogged(MainLoop.scala:24)
    at sbt.StandardMain$.runManaged(Main.scala:53)
    at sbt.xMain.run(Main.scala:28)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
    at xsbt.boot.Launch$.run(Launch.scala:109)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)

   Locked ownable synchronizers:
    - None

"VM Thread" prio=10 tid=0x00007f090413b000 nid=0x5109 runnable 

"GC task thread#0 (ParallelGC)" prio=10 tid=0x00007f090401e000 nid=0x5105 runnable 

"GC task thread#1 (ParallelGC)" prio=10 tid=0x00007f0904020000 nid=0x5106 runnable 

"GC task thread#2 (ParallelGC)" prio=10 tid=0x00007f0904022000 nid=0x5107 runnable 

"GC task thread#3 (ParallelGC)" prio=10 tid=0x00007f0904023800 nid=0x5108 runnable 

"VM Periodic Task Thread" prio=10 tid=0x00007f090417e800 nid=0x5110 waiting on condition 

JNI global references: 448
```

At one point, one of the threads is running at 100% CPU, while some others are on low CPU, busy wait, I guess. Strike that: now I have four sbt threads running at almost 100% (I have four cores).

This is reproducible, although it needs a few runs, i.e. add a space in the editor and save, add another space and save, etc. until at some point it will get stuck.

Let me know if you need anything else.

**Comment by wookietreiber** [comment] 2015-04-09 10:02
To help you reproduce: I cut [a new branch on my project](https://github.com/wookietreiber/scala-chart/tree/sbt-issue-1962).

I also have a bit of config in `~/.sbt`. I don't know, if that matters. Let me know if you need it or if I should try myself to reproduce with a clean global config.

**Comment by eed3si9n** [comment] 2015-04-09 21:10
Thanks for the repro project. I was able to reproduce the issue with my own sbt.

The following is my speculative notes. Since the Finalizer thread is in `WAITING` state, I wonder if it's related to #1223 that @cunei discovered. In there he says:
- Each time sbt invokes the Scala compiler, by creating a new classloader, the classloader is not released.
- if finalization is not run promptly, the classloader cannot be freed, and its permgen cannot be released.

Combining continuous (`~`) with cross building (`+`) is especially potent because if that's what's going on, we are heaping classloader on top of another continuously.

**Comment by wookietreiber** [comment] 2015-04-09 21:39
Would forking help as a workaround?

**Comment by eed3si9n** [comment] 2015-04-09 21:44
The workaround probably is to not do `+` when you are doing continuous.

**Comment by dwijnand** [comment] 2015-04-09 21:57
Looks from #1223 another option you might want to try (if it's a viable option for you) is to run sbt with Java 8.

**Comment by godenji** [comment] 2015-06-04 21:02
Getting the same _with_ Java 8 when `+ publish`ing

**Comment by joescii** [comment] 2015-08-10 01:35
I upgraded (lift-ng)[https://github.com/joescii/lift-ng] from 0.13.5 to 0.13.8 and hit this problem when doing my cross-build/publish.  I'm running 1.7.0_45.  It's easily reproducible by running `sbt "< publish.txt"` in the project.  Edit `publish.txt` to have `alias pub=publishLocal` if you need my project as another point of reference.

**Comment by JohnReedLOL** [comment] 2016-04-18 06:19
I am having this exact same problem. sbt 13.9. 

```
> + publish
[info] Setting version to 2.10.4
[info] Reapplying settings...
```

^ 30 second lag ^

**Comment by barnardb** [comment] 2016-05-02 12:33
I have been having this problem for a while now, currently with sbt 0.13.11.

I have a build that had `crossScalaVersions in Global := Seq("2.10.6", "2.11.8")`, which I would run with something like `sbt +clean +test +doc +package`, and the later "Reapplying settings" would take much longer than the earlier ones.

I recently changed to `crossScalaVersions in Global := Seq("2.10.6", "2.11.8", "2.12.0-M4")`, which another 4 setting reapplication steps, which now invariably hangs on a "Reapplying settings" step for unreasonably long periods of time and has to be killed. It seems that each time the settings are reapplied there is more work to do than the previous time, as if old setting objects from previous reapplications that are no longer being used are being updated—or something.

I am currently working around this by cleaning outside of sbt and doing `sbt +test:compile +test +package reload +doc`. Note the `reload` in there, which seems to reset the problematic state and enable setting reapplication for `+doc` to happen in a reasonable period of time.

**Comment by jkleckner** [comment] 2017-03-13 01:20
FWIW, we are seeing progressive slowdowns in Jenkins build steps with crossScalaVersions.  That build system is still using spinning disks so I wonder if this is somewhat masked by using SSD disks.

**Comment by eed3si9n** [comment] 2019-10-02 02:50
sbt 1.3.x has new watch so closing this.

**Closed as completed by eed3si9n** 2019-10-02 02:50 UTC
Labels: area/watch
