### ISSUE TITLE
SNAPSHOT dependency not updated

### ISSUE THREAD

**Issue by notmandatory** [sbt/sbt#1061] opened 2014-01-05 00:00 UTC
I'm using play 2.2.1 with sbt 0.13.0 with a SNAPSHOT dependency from my local ~/.m2 updating to my ~/.ivy2/cache. My SNAPSHOT dependency does not get updated in the ~/.ivy2/cache, even after a clean and update. I tried adding changing() to my SNAPSHOT dependency config in build.sbt but that did not help. Only if I manually delete my SNAPSHOT package from `/.ivy2/cache does it then get updated. 

This is the same problem as in closed issue #335

**Comment by dansanduleac** [comment] 2014-01-16 09:31
Can you clarify a bit, where is the snapshot dependency? Does your play 2.2.1 depend on a snapshot dependency, or do you depend on something like "play-2.2.1-SNAPSHOT"?
I think `update` only works on the current project and its direct dependencies. Not sure if this is applicable to your case, but as for projects that your project `dependsOn` (so classpath deps on other internal or external projects), they do _not_ seem to get updated at all unless 1) their source code changes or 2) their deps have been changed in the cache.

**Comment by notmandatory** [comment] 2014-01-17 23:01
Hi, the application I'm building depends on release version of play 2.2.1 and has a dependency on a locally built bitcoinj-0.11-SNAPSHOT installed to my ~/.m2 directory (and cached to my ~/.ivy2/cache directory).   If I re-build (and maven install) my bitcoinj-0.11-SNAPSHOT I was expecting an sbt update on my project with a direct dependency on bitcoinj-0.11-SNAPSHOT would also get the new changed version in my .ivy2/cache.

**Comment by dansanduleac** [comment] 2014-01-20 17:32
If the dependency on `bitcoinj-0.11-SNAPSHOT` is a direct dependency of your app, `update` should definitely pick it up.. A log of the update command might be useful. Could you run `update` on your project (_not_ after a clean) when the problem would manifest itself, then type `last-grep bitcoinj` and show us the output of this latter command?

**Comment by jsuereth** [comment] 2014-02-11 19:30
I think this was a known bug in sbt 0.13.0 but should be fixed in sbt 0.13.1.  @harrah may recall if there are any additional incantations, but please update to sbt 0.13.1 and see if that fixes the issue.

Thanks!

**Comment by tsandall** [comment] 2014-04-22 12:59
@dansanduleac @jsuereth 

I am seeing similar behaviour in my project. I have reproduced it in a sample project. Here is the output from sbt update and last-grep with 0.13.2: https://gist.github.com/tsandall/57387a4affc5be0c6b2f

**Comment by jsuereth** [comment] 2014-04-22 14:20
hmm, the `[NOT REQUIRED]` bit looks bad...

**Comment by tsandall** [comment] 2014-04-22 14:34
@jsuereth looks bad as in user error or looks bad as in need to investigate sbt/ivy?

**Comment by jsuereth** [comment] 2014-04-22 14:36
if that build is all you have, it's something in sbt/ivy.

The real issue appears to be it can't resolve the -SNAPSHOT from your github repo.  You can solve that as well, but the fact that Ivy thinks the artifact is optional _is_ an issue.

**Comment by tsandall** [comment] 2014-04-22 14:40
I've updated the gist w/ output _after_ removing the ~/.ivy2/cache/org.tsandall directory.

**Comment by jsuereth** [comment] 2014-04-22 14:45
So, like I said, your repository actually isn't working correctly (I know I can't hit it locally):

https://gist.github.com/tsandall/57387a4affc5be0c6b2f#file-sbt-update-and-sbt-last-grep-after-rm-fr-ivy-cache-L23-L27

I'm not really sure WHY it's succeeding though, because it should be failing.  I'll investigate more when I have some time.

**Comment by tsandall** [comment] 2014-04-22 14:48
FWIW this repo was generated by using 'sbt publish' with publishTo set to a local directory (file:///...)

**Comment by tsandall** [comment] 2014-04-22 16:30
@jsuereth I added the sbt-aether-deploy plugin to my sample project. The aether-deploy command generates the maven-metadata.xml file. I'm still seeing similar behaviour. 
https://gist.github.com/tsandall/3a18bdc9c00c9e591065.

This line is a bit odd, no?
https://gist.github.com/tsandall/3a18bdc9c00c9e591065#file-gistfile1-txt-L45

**Comment by eed3si9n** [comment] 2014-04-22 17:27
My theory is that sbt/Ivy remembers the last place it grabbed the SNAPSHOT from, and it doesn't look at other resolvers, so it appears to not check the latest. This is why I use sbt-dirty-money to wipe out the cache selectively. If someone can confirm the behavior, we'd have repro steps.

**Comment by UriShohet** [comment] 2015-06-23 07:06
@eed3si9n I'm pretty sure I can confirm this behavior - I have a Maven project mydep-0.1-SNAPSHOT. SBT retrieves the updated version only after it's published to Artifactory repository (mvn deploy). When I do mvn clean install to the local ~/.m2 repo - sbt update does nothing. Deleting ~/.ivy2/cache/ and mvn clean install again also doesn't help - sbt update retrieves the latest version from the Artifactory, which is older than in ~/.m2/

**Comment by sundaramohanm** [comment] 2017-04-13 01:35
Any update on this bug? i am also seeing something similar when i delete transitive dependency from ~/.ivy2/cache and do update it is not downloading again.

Ex:  Pkg_A (my direct dependency) depends on Pkg_B, Pkg_C
when i delete Pkg_C and do sbt update i expect Pkg_C to be downloaded but it is not getting downloaded

**Comment by eed3si9n** [comment] 2019-08-09 19:41
I am closing this due to inactivity, but if this is still relevant let us know with more details (reproduction steps etc).

**Closed as completed by eed3si9n** 2019-08-09 19:41 UTC
Labels: needs info, area/library_management, area/maven_integration
