### ISSUE TITLE
sbt -client -no-colors still prints colors 

### ISSUE THREAD

**Issue by alexklibisz** [sbt/sbt#7138] opened 2023-01-26 04:14 UTC
## steps

1. Create a new Scala/SBT project in IntelliJ. SBT version 1.8.2, Scala version 2.13.10. Using SBT 1.6.2 launcher on MacOS.
2. Run `sbt -no-color version`. The output is printed with no colors, as expected.
3. Run `sbt -client -no-color version`. The output includes colors -- not expected.
4. Run `sbt -client --no-color version`. Still has colors.

## problem

The `sbt -client -no-color version` command includes colors.

## expectation

The `sbt -client -no-color version` command should not include colors.

## notes

Here's a screenshot of the commands above

<img width="997" alt="image" src="https://user-images.githubusercontent.com/8015228/214757235-a1deea27-9ae9-401a-ba70-3ad6744b7bda.png">

**Comment by SethTisue** [comment] 2023-01-26 04:35
duplicate of #6468?

**Comment by alexklibisz** [comment] 2023-01-26 15:32
Ah, yeah, that seems like a more general version of this issue. Feel free to close.

**Closed as not planned** 2023-01-26 16:11 UTC
Labels: Duplicate
