### ISSUE TITLE
setting keys do not always appear as completion suggestions

### ISSUE THREAD

**Issue by tpolecat** [sbt/sbt#6715] opened 2021-11-16 20:53 UTC
## steps

- Clone the minimal repository [here](https://github.com/tpolecat/sbt-repro) and run `sbt`.
- Observe that `mimaVersionCheckExtraVersions` (provided by the [mima-version-check plugin](https://github.com/ChristopherDavenport/sbt-mima-version-check)) is a valid key.
- Observe that `mima<tab>` shows completions for MiMa keys, but not for keys provided by mima-version-check.

![image](https://user-images.githubusercontent.com/1200131/142063218-98d40667-13fd-446b-8075-a6b4ffff1dac.png)

## problem

Tab completion does not suggest keys provided by mima-version-check, but _does_ suggest keys provided by MiMa (which is pulled in as a transitive dependency).

## expectation

All available keys should be visible through tab completion.

## notes

It's possible that this is a duplicate. I didn't see anything that seemed to be exactly the same but I don't understand sbt very well.

**Comment by SethTisue** [comment] 2021-11-16 21:02
I wonder if the mima-version-check plugin is somehow doing something wrong.

**Comment by eed3si9n** [comment] 2021-11-16 23:09
sbt-mima-version-check is doing something correct, which is using Global scope to provide the default value:

https://github.com/ChristopherDavenport/sbt-mima-version-check/blob/7fd9b88723f9490b81507eb4be30f323b58787df/core/src/main/scala/io/chrisdavenport/sbtmimaversioncheck/MimaVersionCheck.scala#L61-L65

```scala
  override def globalSettings: Seq[Def.Setting[_]] = List(
    mimaVersionCheckExtraVersions := Set(),
    mimaVersionCheckExcludedVersions := Set(),
    mimaVersionCheckSnapshotUsesLatestReleasedVersion := false,
  )
```

This is one of the advices in Plugin Best Practice guide as well (https://www.scala-sbt.org/1.x/docs/Plugins-Best-Practices.html#Provide+default+values+in).

My guess is that the tab completion is currently not displaying those keys in global scope (because technically it's not in the subproject?). I think displaying the globally available keys in tab completion makes sense given there are no other weirdness introduced by doing so.

**Comment by eed3si9n** [comment] 2021-11-16 23:20
> It's possible that this is a duplicate.

This is indeed a duplicate of #1373 I think.

Looks like @Duhemm and I worked on `ThisBuild` scoped key completion in #2469 and #2855 in 2016.

**Comment by eed3si9n** [comment] 2021-11-16 23:52
Here's my PR for this - https://github.com/sbt/sbt/pull/6716

**Closed as completed** 2021-11-17 00:51 UTC
Labels: area/shell

**Comment by tpolecat** [comment] 2021-11-17 01:11
Wow that's service! Thank you!
