### ISSUE TITLE
SBT won't autocomplet on keys defined in globalSettings of an AutoPlugin

### ISSUE THREAD

**Issue by joan38** [sbt/sbt#2341] opened 2015-12-30 10:52 UTC
```
object BlaBlaPlugin extends AutoPlugin {

  object autoImport {
    lazy val blabla = taskKey[Unit]("")
  }
  import autoImport._

  override lazy val globalSettings = Seq(
    blabla := println("Hello")
  )
}
```

Gives:

```
> bla
{invalid input}
> blabla
Hello
[success] Total time: 0 s, completed 22-Dec-2015 00:33:21
```

Why wouldn't the autocompletion work?

Thanks

**Comment by eed3si9n** [comment] 2019-09-26 03:24
Closing this a duplicate of https://github.com/sbt/sbt/issues/1373

**Closed as completed by eed3si9n** 2019-09-26 03:24 UTC
Labels: area/shell
