### ISSUE TITLE
Clean leaves input and output stream files

### ISSUE THREAD

**Issue by nalbertfr** [sbt/sbt#2885] opened 2016-12-29 11:18 UTC
## Env (unclear if influences trouble)
- java_version = '1.8.0_112'
- scala-2.12.1
- sbt 0.13.12-1 from @bintray--sbt-rpm

## steps
```
# optional # sbt compile # or any sbt command like run...
sbt clean
```

Any sbt command produces stream input and output files within target dirs

## problem
Clean leaves target directories with some stream input and output files within (both within "root project" target dir and "project" subprojects)

## expectation
Clean is expected to delete target dirs deleted

**Comment by dwijnand** [comment] 2016-12-29 12:04
Duplicate of #896.

**Closed as completed by dwijnand** 2016-12-29 12:04 UTC

**Comment by nalbertfr** [comment] 2016-12-29 13:28
Still don't agree. 
I'm with delitescere.

At least, does anyone know of a plugin doing what we're looking for? 
This would be a "final solution" to controversy, allowing 
- "core sbt" to keep its behaviour and 
- people looking fo real clean operation to have it, within sbt
