### ISSUE TITLE
Scala sources are recompiled every time on JDK 9, sbt 0.13.16

### ISSUE THREAD

**Issue by sjrd** [sbt/sbt#3631] opened 2017-10-11 09:24 UTC
## steps

`project/build.properties`
```
sbt.version=0.13.16
```
`project/Extra.scala`
```scala
package build

object Extra {
  val FooVersion = "1.0"
}
```
`build.sbt`
```scala
import build.Extra

lazy val foo = project.
  settings(
    version := Extra.FooVersion
  )
```
`foo/src/main/test/SimpleTest.scala`
```scala
package test

object SimpleTest {
  def main(args: Array[String]): Unit =
    println("Test")
}
```

**On JDK 9**:
```
sbt-test$ sbt
[info] Loading global plugins from /localhome/doeraene/.sbt/0.13/plugins
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by sbt.ivyint.ErrorMessageAuthenticator$ (file:/home/doeraene/.sbt/boot/scala-2.10.6/org.scala-sbt/sbt/0.13.16/ivy-0.13.16.jar) to field java.net.Authenticator.theAuthenticator
WARNING: Please consider reporting this to the maintainers of sbt.ivyint.ErrorMessageAuthenticator$
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] Loading project definition from /localhome/doeraene/projects/sbt-test/project
[info] Updating {file:/localhome/doeraene/projects/sbt-test/project/}sbt-test-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /localhome/doeraene/projects/sbt-test/project/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to sbt-test (in build file:/localhome/doeraene/projects/sbt-test/)
>


sbt-test$ sbt
[info] Loading global plugins from /localhome/doeraene/.sbt/0.13/plugins
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by sbt.ivyint.ErrorMessageAuthenticator$ (file:/home/doeraene/.sbt/boot/scala-2.10.6/org.scala-sbt/sbt/0.13.16/ivy-0.13.16.jar) to field java.net.Authenticator.theAuthenticator
WARNING: Please consider reporting this to the maintainers of sbt.ivyint.ErrorMessageAuthenticator$
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] Loading project definition from /localhome/doeraene/projects/sbt-test/project
[info] Compiling 1 Scala source to /localhome/doeraene/projects/sbt-test/project/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to sbt-test (in build file:/localhome/doeraene/projects/sbt-test/)
>
> foo/run
[info] Updating {file:/localhome/doeraene/projects/sbt-test/}foo...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /localhome/doeraene/projects/sbt-test/foo/target/scala-2.10/classes...
[info] Running test.SimpleTest 
Test
[success] Total time: 1 s, completed Oct 11, 2017, 11:19:02 AM
> foo/run
[info] Compiling 1 Scala source to /localhome/doeraene/projects/sbt-test/foo/target/scala-2.10/classes...
[info] Running test.SimpleTest 
Test
[success] Total time: 0 s, completed Oct 11, 2017, 11:19:05 AM
> foo/run
[info] Compiling 1 Scala source to /localhome/doeraene/projects/sbt-test/foo/target/scala-2.10/classes...
[info] Running test.SimpleTest 
Test
[success] Total time: 0 s, completed Oct 11, 2017, 11:19:07 AM
>

doeraene@lamppc18:~/projects/sbt-test$
```

## problem

* `project/Extra.scala` is recompiled every time we launch sbt (also happens on `reload`)
* `SimpleTest.scala` is recompiled every time we run `foo` (or just `foo/compile`)

## expectation

I expect incremental compilation to correctly do its job.

## notes

sbt version: 0.13.16
sbt launcher version: either 0.13.16 or 1.0.2

The issue cannot be reproduced with sbt 1.0.2 in `build.properties`. Also, on JDK 8 there is no issue.

**Comment by ritschwumm** [comment] 2017-10-15 13:45
any idea why this happens?

**Comment by smarter** [comment] 2017-10-31 19:14
Duplicate of https://github.com/sbt/sbt/issues/3142 where I provided some more info.

**Comment by dwijnand** [comment] 2017-11-02 13:52
Duplicate of #3142 (as @smarter said).

**Closed as completed by dwijnand** 2017-11-02 13:52 UTC
