### ISSUE TITLE
`+` does not work for commands that take arguments in sbt 1.x

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3539] opened 2017-09-15 21:48 UTC
## problem
In sbt 0.13.x:
```scala
sbt @ root > +show compiler/scalaVersion
[info] Setting version to 2.12.3
[info] Reapplying settings...
[info] *** Welcome to the sbt build definition for Scala! ***
[info] Check README.md for more information.
[info] 2.12.3
[info] Setting version to 2.12.3
[info] Reapplying settings...
[info] *** Welcome to the sbt build definition for Scala! ***
[info] Check README.md for more information.
```
  
In sbt 1.0.x:
```scala
sbt:zinc Root> +show compilerBridge/scalaVersion
[info] Setting Scala version to 2.10.6 on 5 projects.
[info] Excluded 13 projects, run ++ 2.10.6 -v for more details.
[info] Reapplying settings...
[info] Set current project to zinc Root (in build file:/data/rw/code/scala/zinc/)
[error] Expected configuration
[error] Expected ':' (if selecting a configuration)
[error] Expected key
[error] Not a valid key: show (similar: showTiming, sLog, ps)
[error] compilerInterface/show compilerBridge/scalaVersion
[error]                       ^
```

## expectation
I would expect my command to work in 1.x.

sbt version: 1.0.0

**Comment by eed3si9n** [comment] 2017-09-15 22:00
Duplicate of https://github.com/sbt/sbt/issues/2776.
It should be fixed in sbt 1.0.1.

**Closed as completed by eed3si9n** 2017-09-15 22:00 UTC
