### ISSUE TITLE
Publishing to Sonatype Nexus repository doesn't work in sbt-1.0.0-x

### ISSUE THREAD

**Issue by xerial** [sbt/sbt#3331] opened 2017-07-17 20:41 UTC
## steps
- Checkout https://github.com/xerial/sbt-publish-test
- Modify the organziation value to your own one
- Set credential in `$(HOME)/.sbt/1.0/sonatype.sbt` https://github.com/xerial/sbt-sonatype/tree/support-1.0.0-M2#homesbtsbt-versionsonatypesbt
-- Or write the credential configuration in build.sbt
- Run publish

## problem
It seems Sonatype credential configuration is not effective, and `publish` fails with an authentication failure:
```
sbt:publish-example> publish
[info] Wrote /Users/leo/work/tmp/publish-example/target/scala-2.12/publish-example_2.12-0.1-SNAPSHOT.pom

[error] java.io.IOException: Access to URL https://oss.sonatype.org/content/repositories/snapshots/org/xerial/sbt/publish-example_2.12/0.1-SNAPSHOT/publish-example_2.12-0.1-SNAPSHOT.pom was refused by the server: Unauthorized

[error] 	at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:79)

[error] (*:publish) java.io.IOException: Access to URL https://oss.sonatype.org/content/repositories/snapshots/org/xerial/sbt/publish-example_2.12/0.1-SNAPSHOT/publish-example_2.12-0.1-SNAPSHOT.pom was refused by the server: Unauthorized

[error] Total time: 1 s, completed Jul 17, 2017 1:50:43 PM
```

## expectation
The same configuration works if I use sbt 0.13.x. This is a blocker for releasing https://github.com/xerial/sbt-sonatype for sbt-1.0.0-RC2.  

## notes

sbt version: 1.0.0-RC2

I found the configuration in ~/.sbt/1.0/*.sbt is loaded (for example, the other key set in this file can be seen in sbt console) but it seems the credential is not used when running `publish` command.

**Comment by dwijnand** [comment] 2017-07-20 11:05
I think @marsxu1984 is running into the same issue (when trying to publish to an Artifactory repo). He reports that the same issue occurs in 1.0.0-M6, while 1.0.0-M5 works.

Start of the conversation: https://gitter.im/sbt/sbt?at=597082dabf7e6af22cf81123.

**Comment by jvican** [comment] 2017-07-20 12:20
My guess is that this is due to Gigahorse.

**Comment by eed3si9n** [comment] 2017-07-22 22:04
I was able to reproduce it myself using an old scopt build (https://github.com/eed3si9n/scopt/tree/wip/350).
sbt/sbt dogfoods, but we use sbt-bintray so we haven't tested the publishing with authentication.

```scala
sbt:scopt> publishSigned
[info] Wrote /Users/eed3si9n/work/scopt/target/scala-2.11/scopt_2.11-3.5.0-SNAPSHOT.pom

[error] java.io.IOException: Access to URL https://oss.sonatype.org/content/repositories/snapshots/com/github/scopt/scopt_2.11/3.5.0-SNAPSHOT/scopt_2.11-3.5.0-SNAPSHOT-sources.jar.asc was refused by the server: Unauthorized

[error] 	at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:79)

[error] (*:publishSigned) java.io.IOException: Access to URL https://oss.sonatype.org/content/repositories/snapshots/com/github/scopt/scopt_2.11/3.5.0-SNAPSHOT/scopt_2.11-3.5.0-SNAPSHOT-sources.jar.asc was refused by the server: Unauthorized
```

**Comment by xerial** [comment] 2017-07-22 22:24
There are some pains in using Bintray (because its repository can be down for several hours). We also need to use private repositories (e.g., Artifactory as @marsxu1984 reported). 

I'd appreciate if this bug can be fixed. (I've tried to check the corresponding code but sbt has many components, and it was difficult for me to identify the cause)

**Comment by eed3si9n** [comment] 2017-07-22 22:25
Yes. We can't ship another RC until we fix this bug.

**Comment by eed3si9n** [comment] 2017-07-24 19:41
Fixed in https://github.com/sbt/librarymanagement/pull/141. This will be in next RC.

**Closed as completed by eed3si9n** 2017-07-24 19:41 UTC
Labels: area/library_management, Regression
