### ISSUE TITLE
[0.13.10] useJCenter doesn't work

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2464] opened 2016-02-20 04:58 UTC
originally reported by @seratch - https://twitter.com/seratch_ja/status/700878251669893121
## steps
1. Remove some artifact from Ivy cache
2. Use sbt 0.13.10
## problem

Still using JCenter.
## expectation

Not using JCenter.
## notes

When the resolver has been changed in the metabuild sbt 0.13.10 inherits them into the build resolvers.
Typically one has some level of resolver modification installed as a global setting, so you end up pulling in JCenter into the build level resolver.

**Comment by seratch** [comment] 2016-02-20 05:05
Sorry for the tweet in Japanese. 
See also: 
sbt 0.13.10 still uses jcenter primarily when using older sbt-launch.jar
https://gist.github.com/seratch/e2f082162d695505aaba

**Comment by dwijnand** [comment] 2016-02-20 17:23
This might be of note: https://github.com/sbt/sbt/pull/2335/files#r53553807

**Comment by dwijnand** [comment] 2016-02-20 18:45
I've included a fix for the above in #2466

**Comment by eed3si9n** [comment] 2016-02-22 02:12
@seratch Do you mind testing 0.13.11 when you get a chance? It's now available with the fix.

**Comment by seratch** [comment] 2016-02-22 02:55
@eed3si9n Thanks for the incredibly quick fix. I just tried 0.13.11.
https://gist.github.com/seratch/e2f082162d695505aaba#file-sbt-0-13-11-stdout
sbt-launcher 0.13.9 still accesses jcenter when downloading sbt 0.13.11 libs. Is this an intended behavior? If so, everything looks fine. 0.13.11 never uses jcenter when resolving libraryDependencies.

**Comment by eed3si9n** [comment] 2016-02-22 05:27
@seratch 

> sbt-launcher 0.13.9 still accesses jcenter when downloading sbt 0.13.11 libs.

That is an expected behavior since the sbt 0.13.11 JARs are downloaded by the launcher.

> If so, everything looks fine. 0.13.11 never uses jcenter when resolving libraryDependencies.

Thanks for the confirmation!

**Closed as completed** 2016-02-26 22:02 UTC
Labels: area/library_management
