### ISSUE TITLE
Failure to install SBT - Linux Mint

### ISSUE THREAD

**Issue by dhope-lab** [sbt/sbt#6600] opened 2021-07-17 17:21 UTC
SBT has been failing on my Linux Mint distro.

Trying to update the distro yields this error message - 

'E: The repository 'https://dl.bintray.com/sbt/debian  InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.'

Even trying to update through the distros software center yields a 'Failure to download package files'.

How can this be remedied?

Thanks.

**Comment by SethTisue** [comment] 2021-07-17 20:13
duplicate of #6582 and #6583 and #6584 and #6596 (!!)

**Closed as completed by SethTisue** 2021-07-17 20:13 UTC
