### ISSUE TITLE
Parallelize and cache download of Artifacts

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2982] opened 2017-03-02 15:02 UTC
In light of Coursier, we should revisit the idea of parallelizing and caching download of Artifacts.

**Comment by xuwei-k** [comment] 2017-03-15 03:18
https://github.com/sbt/sbt/issues/590

**Comment by dwijnand** [comment] 2017-03-15 10:43
You're right @xuwei-k. Duplicate of #590. I've labelled that one like this one was labelled.

**Closed as completed by dwijnand** 2017-03-15 10:43 UTC
Labels: Enhancement, help wanted, area/library_management
