### ISSUE TITLE
excessive GC & `OutOfMemory` error with SBT1.4.1

### ISSUE THREAD

**Issue by bertlebee** [sbt/sbt#6032] opened 2020-10-27 05:17 UTC
## steps

currently using sbt 1.4.1 & AdoptOpenJDK Java 11.0.8

export SBT_OPTS="-Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
(I've tried -Xmx20G with similar results)

clone https://github.com/zio/zio.git

open project in SBT and run `clean` then `prepare` a couple of times.

this should be enough to start showing GC warnings (maybe even as early as `prepare`)
there are examples of this throughout zio CI builds e.g. check the end of the `lint code` step here
https://app.circleci.com/pipelines/github/zio/zio/9297/workflows/c7b95261-3137-49c2-a6ee-2d8f1e74305d/jobs/95003

## problem

since upgrading to 1.4.x I've been having problems with excessive GC and most recently an OOM crash while working on ZIO

## expectation

SBT should be able to handle building a reasonable size project without spending excessive time in GC

## notes

here's the log from when I got the OOM error:

```scala
sbt:core-tests> prepare
[info] compiling 1 Scala source to /home/rob/IdeaProjects/zio/core-tests/jvm/target/scala-2.12/test-classes ...
[info] Running scalafix on 59 Scala sources
[warn] 14.536 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
[success] Total time: 42 s, completed Oct 27, 2020, 3:13:38 PM
[info] Formatting 1 Scala sources...
[success] Total time: 1 s, completed Oct 27, 2020, 3:13:40 PM
sbt:core-tests> prepare
[info] compiling 1 Scala source to /home/rob/IdeaProjects/zio/core-tests/jvm/target/scala-2.12/test-classes ...
[info] Running scalafix on 59 Scala sources
[warn] 9.528 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
[warn] 5.071 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
[warn] 5.164 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
[warn] 8.151 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
[warn] 9.97 seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/10/27 15:21:45 - please wait.
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/10/27 15:21:45 - please wait.
JVMDUMP032I JVM requested Heap dump using '/home/rob/IdeaProjects/zio/heapdump.20201027.152145.13868.0002.phd' in response to an event
JVMDUMP010I Heap dump written to /home/rob/IdeaProjects/zio/heapdump.20201027.152145.13868.0002.phd
JVMDUMP032I JVM requested System dump using '/home/rob/IdeaProjects/zio/core.20201027.152145.13868.0001.dmp' in response to an event
JVMPORT048E Failed to create system dump because a non-regular file "/home/rob/IdeaProjects/zio/core" exists with the same name as the expected system dump file
JVMDUMP012E Error in System dump: /home/rob/IdeaProjects/zio/core.20201027.152145.13868.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/rob/IdeaProjects/zio/javacore.20201027.152145.13868.0003.txt' in response to an event
JVMDUMP010I Java dump written to /home/rob/IdeaProjects/zio/javacore.20201027.152145.13868.0003.txt
JVMDUMP032I JVM requested Snap dump using '/home/rob/IdeaProjects/zio/Snap.20201027.152145.13868.0005.trc' in response to an event
JVMDUMP010I Snap dump written to /home/rob/IdeaProjects/zio/Snap.20201027.152145.13868.0005.trc
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
JVMDUMP032I JVM requested Heap dump using '/home/rob/IdeaProjects/zio/heapdump.20201027.152145.13868.0004.phd' in response to an event
JVMDUMP010I Heap dump written to /home/rob/IdeaProjects/zio/heapdump.20201027.152145.13868.0004.phd
JVMDUMP032I JVM requested Java dump using '/home/rob/IdeaProjects/zio/javacore.20201027.152145.13868.0006.txt' in response to an event
JVMDUMP010I Java dump written to /home/rob/IdeaProjects/zio/javacore.20201027.152145.13868.0006.txt
JVMDUMP032I JVM requested Snap dump using '/home/rob/IdeaProjects/zio/Snap.20201027.152145.13868.0007.trc' in response to an event
JVMDUMP010I Snap dump written to /home/rob/IdeaProjects/zio/Snap.20201027.152145.13868.0007.trc
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
Exception in thread "MemoryMXBean notification dispatcher" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.lang.Long.valueOf(Long.java:1180)
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/10/27 15:22:46 - please wait.
JVMDUMP032I JVM requested Heap dump using '/home/rob/IdeaProjects/zio/heapdump.20201027.152246.13868.0008.phd' in response to an event
JVMDUMP010I Heap dump written to /home/rob/IdeaProjects/zio/heapdump.20201027.152246.13868.0008.phd
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/10/27 15:23:04 - please wait.
        at JVMDUMP032I JVM requested Heap dump using '/home/rob/IdeaProjects/zio/heapdump.20201027.152304.13868.0009.phd' in response to an event
JVMDUMP010I Heap dump written to /home/rob/IdeaProjects/zio/heapdump.20201027.152304.13868.0009.phd
JVMDUMP032I JVM requested Java dump using '/home/rob/IdeaProjects/zio/javacore.20201027.152246.13868.0010.txt' in response to an event
JVMDUMP010I Java dump written to /home/rob/IdeaProjects/zio/javacore.20201027.152246.13868.0010.txt
JVMDUMP032I JVM requested Snap dump using '/home/rob/IdeaProjects/zio/Snap.20201027.152246.13868.0012.trc' in response to an event
JVMDUMP010I Snap dump written to /home/rob/IdeaProjects/zio/Snap.20201027.152246.13868.0012.trc
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
JVMDUMP032I JVM requested Java dump using '/home/rob/IdeaProjects/zio/javacore.20201027.152304.13868.0011.txt' in response to an event
JVMDUMP010I Java dump written to /home/rob/IdeaProjects/zio/javacore.20201027.152304.13868.0011.txt
JVMDUMP032I JVM requested Snap dump using '/home/rob/IdeaProjects/zio/Snap.20201027.152304.13868.0013.trc' in response to an event
java.management/com.ibm.java.lang.management.internal.MemoryUsageUtil.toCompositeData(MemoryUsageUtil.javaJVMDUMP010I Snap dump written to /home/rob/IdeaProjects/zio/Snap.20201027.152304.13868.0013.trc
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
:126)
        at java.management/com.ibm.java.lang.management.internal.MemoryUsageUtil.toTabularData(Exception in thread "NioPathWatcher-loop-thread-2" MemoryUsageUtil.java:155)java.lang.OutOfMemoryErrorException in thread "MemoryMXBean notification dispatcher" 
: 
java.lang.OutOfMemoryError: Exception in thread "classloader-cache-cleanup-0"   at Java heap spacejava.base
/java.lang.OutOfMemoryError: Exception in thread "NioPathWatcher-loop-thread-4" Java heap spacejava.lang.OutOfMemoryErrorsun.nio.fs.UnixPath    at ?
: .Java heap spacegetName
(
UnixPath.java:347)
        at      at ?java.base
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:309)
        at sbt.Execute.next$1(Execute.scala:117)
        at sbt.Execute.processAll(Execute.scala:127)
        at sbt.Execute.runKeep(Execute.scala:95)
        at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:472)
        at sbt.EvaluateTask$.run$1(EvaluateTask.scala:471)
        at sbt.EvaluateTask$.runTask(EvaluateTask.scala:494)
        at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:101)
        at sbt.internal.Aggregation$$$Lambda$4873/0000000000000000.apply(Unknown Source)
        at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:388)
        at sbt.internal.Aggregation$.timedRun(Aggregation.scala:99)
        at sbt.internal.Aggregation$.runTasks(Aggregation.scala:113)
        at sbt.internal.Aggregation$.$anonfun$applyDynamicTasks$4(Aggregation.scala:181)
        at sbt.internal.Aggregation$$$Lambda$11260/000000003B42BEF0.apply(Unknown Source)
        at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
        at sbt.Command$$$Lambda$802/0000000000000000.apply(Unknown Source)
        at sbt.internal.Act$.$anonfun$actParser0$4(Act.scala:436)
        at sbt.internal.Act$$$Lambda$4863/0000000000000000.apply(Unknown Source)
        at sbt.Command$.process(Command.scala:189)
        at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
        at sbt.MainLoop$$$Lambda$840/0000000038DEC3E0.apply(Unknown Source)
        at scala.Option.getOrElse(Option.scala:189)
        at sbt.MainLoop$.process$1(MainLoop.scala:245)
        at sbt.MainLoop$.processCommand(MainLoop.scala:269)
        at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:162)
        at sbt.MainLoop$$$Lambda$757/0000000038DBA820.apply(Unknown Source)
        at sbt.State$StateOpsImpl$.runCmd$1(State.scala:286)
        at sbt.State$StateOpsImpl$.process$extension(State.scala:322)
        at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:162)
        at sbt.MainLoop$$$Lambda$753/0000000038DBA1F0.apply(Unknown Source)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
        at sbt.MainLoop$.next(MainLoop.scala:162)
        at sbt.MainLoop$.run(MainLoop.scala:143)
        at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:118)
        at sbt.MainLoop$$$Lambda$651/0000000000000000.apply(Unknown Source)
        at sbt.io.Using.apply(Using.scala:27)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:111)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
        at sbt.MainLoop$.runLogged(MainLoop.scala:41)
        at sbt.StandardMain$.runManaged(Main.scala:188)
        at sbt.xMain$.$anonfun$run$6(Main.scala:100)
        at sbt.xMain$$$Lambda$202/0000000038BD3BB0.apply(Unknown Source)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withIn(Console.scala:230)
        at sbt.internal.util.Terminal$.withIn(Terminal.scala:542)
        at sbt.internal.util.Terminal$.$anonfun$withStreams$2(Terminal.scala:337)
        at sbt.internal.util.Terminal$$$Lambda$306/0000000038CA17E0.apply(Unknown Source)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withOut(Console.scala:167)
        at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:532)
        at sbt.internal.util.Terminal$$$Lambda$309/0000000038CA1DE0.apply(Unknown Source)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withErr(Console.scala:196)
        at sbt.internal.util.Terminal$.withOut(Terminal.scala:532)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:337)
        at sbt.xMain$.run(Main.scala:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
        at xsbt.boot.Launch$.run(Launch.scala:111)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
        at xsbt.boot.Launch$.launch(Launch.scala:119)
        at xsbt.boot.Launch$.apply(Launch.scala:20)
        at xsbt.boot.Boot$.runImpl(Boot.scala:56)
        at xsbt.boot.Boot$.main(Boot.scala:18)
        at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.OutOfMemoryError: Java heap space
```

**Comment by bertlebee** [comment] 2020-10-27 05:26
new record I think:
[warn] **94.313** seconds of the last 10 seconds were spent in garbage collection. You may want to increase the project heap size using `-Xmx` or try a different gc algorithm, e.g. `-XX:+UseG1GC`, for better performance.
[info] Running scalafix on 47 Scala sources

**Comment by eatkins** [comment] 2020-10-27 17:14
Thanks for the report! I don't think this is an sbt bug though. The scalafix plugin has a memory leak/uses excessive memory. I reproduced the issue and took a heap dump:
<img width="994" alt="Screen Shot 2020-10-27 at 10 12 52 AM" src="https://user-images.githubusercontent.com/2658825/97337150-23f0fe00-183d-11eb-9868-54ef0a5a49be.png">

I previously opened an issue with scalafix: https://github.com/scalacenter/scalafix/issues/1229

**Comment by eatkins** [comment] 2020-10-27 17:15
Closing this because it's not fixable on the sbt side.

**Closed as completed by eatkins** 2020-10-27 17:15 UTC

**Comment by bertlebee** [comment] 2020-10-27 18:23
@eatkins thanks for taking a look - I'll follow the scalafix issue.

**Comment by stanislav-chetvertkov** [comment] 2021-03-30 06:45
Was recently having a similar issue, in my case it was related to 'slickless' in db table definitions - the implicit search got stuck because there was no entity matching the hlist
