### ISSUE TITLE
possible memory leak (has easy workaround - just restart)

### ISSUE THREAD

**Issue by mr-git** [sbt/sbt#7074] opened 2022-11-11 09:56 UTC
## steps

Keep SBT session active for many days/weeks for project, which gets actively developed and keeps running SBT commands.

## problem

After a while, JDK or SBT becomes slower and starts to report warnings like:
```
[warn] In the last 10 seconds, 8.084 (81.0%) were spent in GC. [Heap: 0.00GB free of 1.00GB, max 1.00GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.
```

## expectation

There is no need for regular restarts of SBT session

## notes

The same warning message has been observed on both: SBT session kept open in terminal AND in IDEA's SBT shell.
SBT version: 1.7.3
JDK version: 18.0.1.1
OS version: macOS Ventura 13.0

**Comment by adpi2** [comment] 2022-11-11 11:37
Thanks for opening this issue. Can you give more information on how to reproduce this memory leak?

Ideally you can share a repository. Otherwise you can give us details about the number of sub-projects, their Scala versions, the main library dependencies.

**Comment by mr-git** [comment] 2022-11-11 13:14
In my case it was on my main company project during active development, I kept IDEA open for at least a week, regular development, rebuilds with `compile` and unit-tests with `test`, some branch switches etc, sometimes `clean; compile`.

Using following plugins (and few in-house ones, which use `sbt-native-packager` and `laika`, but only as wrappers):
```
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.0.0")
addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.1.1")
addSbtPlugin("com.github.mwz" % "sbt-sonar" % "2.2.0")
```

Project uses Scala 2.13.8, but it looks that SBT keeps something in caches.
Maybe some of our plugins is leaking data, though they mostly provide only settings or tasks, not caching anything.

I do not have "clean" project without other plugins, which I would keep open and running constantly.

**Comment by eed3si9n** [comment] 2022-11-11 16:42
We have a documentation for this here
https://www.scala-sbt.org/1.x/docs/Troubleshoot-Memory-Issues.html#Troubleshoot+memory+issues

One thing to note about sbt is that when `test` task is called, the application to be tested are loaded into the same JVM of sbt, effectively emulating JVM call as a function call. This has the benefit of warmed up JVM (bytecode ready to run your code) as you make changes. The downside is that you might need to do some resource management, if you or your library relied on JVM-shutdown-as-cleanup.

A common example is Akka's ActorSystem. In example codes (like https://github.com/akka/akka-quickstart-scala.g8/blob/0f451283ce9fd3fb7fb5905b7dd8c6a8b05eea17/src/main/g8/src/main/scala/%24package%24/AkkaQuickstart.scala#L70-L78), we don't always see ActorSystem shutdown. This is ok for hello world example, but if you have a more complicated system that create a bunch of actors, over time these things can leak. Similar memory leak can likely happen with any other effect system. In general using `object` can lead to subtle memory leaks. If this is what's happening, one solution is to shutdown these things and drain out the `object`s. Another thing to try is:

```scala
Test / fork := true
```

That would spawn a fresh JVM upon test. It would add a few seconds of pause each time you run the test. You could try using that first to see if test is the cause.

**Comment by mr-git** [comment] 2022-11-11 20:06
Thank you for links and explanation!
Usually workaround is not a big hustle, thus I do not mind, if we close this issue.

**Comment by SethTisue** [comment] 2023-02-09 22:52
Closing since it's possible that in some cases some bug in sbt is at fault, we don't have specific evidence of that here.

**Closed as not planned** 2023-02-09 22:51 UTC
