### ISSUE TITLE
[1.3.0-RC1] FSEvents error

### ISSUE THREAD

**Issue by cquiroz** [sbt/sbt#4699] opened 2019-05-17 12:32 UTC
- [*] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
Run in triggered mode for a while (at least some 20 reloads), e.g.
~project/compile

## problem
Triggered mode stops working and I get a large amount of messages like
`2019-05-17 08:11 java[63537] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)`

Further file changes don't trigger a recompilation

## expectation
Triggered mode working

## notes
This is happening on OSX Mojave, version 10.14.4
As noted above I only see this after a while, and surprisingly restarting sbt after it does not solve the problem I keep getting the same error message and no triggered mode. Restarting the shell doesn't help either

The problem only goes away when restarting the editor. In my case Atom

sbt version: 1.3.0-RC1

**Comment by eed3si9n** [comment] 2019-05-17 12:57
@cquiroz Thanks for the report!

> The problem only goes away when restarting the editor. In my case Atom

Are you using any plugins with Atom that might be launching sbt in the background?

**Comment by cquiroz** [comment] 2019-05-17 12:58
Yeah metals is installed and running with Atom

**Comment by eed3si9n** [comment] 2019-05-22 13:39
Does that mean you're running two instances of sbt on a single working directory?
One by you and the other by Atom and/or metals? If so can you reproduce them using just one instance of sbt?

**Comment by cquiroz** [comment] 2019-05-22 15:38
I haven't seen it again. It could be that atom was running 1.2.8 while I did the reboot with 1.3.0-RC1 an sbt. It is hard to tell

I'll keep observing but if it doesn't appear again it maybe better to close it as non reproducible

**Comment by eed3si9n** [comment] 2019-05-30 05:31
I am going to close this for now since likely other watcher code is involved.

**Closed as completed by eed3si9n** 2019-05-30 05:31 UTC
Labels: area/watch
