### ISSUE TITLE
sbtn "project foobar" compile / Expected project ID Error

### ISSUE THREAD

**Issue by JR-Utily** [sbt/sbt#6295] opened 2021-02-05 18:56 UTC
Hello,
In my team, we have a big git mono repo with one build.sbt at its root. 
So we are used to compile specific project by calling
`sbt "project foobar" compile`

We are trying to use the new --client feature to speed up the compilation time, but when we execute
`sbt --client "project foobar" compile` 
it goes in error, as if it was looking for project "foobar compile"
```
[info] entering *experimental* thin client - BEEP WHIRR
[info] terminate the server with `shutdown`
> project foobar compile
[error] Expected project ID
[error] project foobar compile
[error]               ^

```
It does the same if I call directly sbtn

**Comment by griggt** [comment] 2021-02-05 19:17
Have you tried `sbt --client "foobar/compile"` or `sbt --client "project foobar; compile"`?

**Comment by JR-Utily** [comment] 2021-02-05 19:20
`sbt --client "project foobar; compile"` works indeed ! 
Thanks for the workaround ! ;)
(but still, it means that adding --client is not transparent to an existing, working, script)

**Comment by eed3si9n** [comment] 2021-02-06 18:24
I think this is a duplicate of https://github.com/sbt/sbt/issues/5969, and as far as I know, it's by design.
I think sbtn is meant to replace sbt shell, not the batch mode, so what you should pass in as argument is a single line you'd pass to the shell.

**Closed as completed by eed3si9n** 2021-02-06 18:24 UTC
Labels: area/sbtn
