### ISSUE TITLE
SBT errors out with sbt-bloop

### ISSUE THREAD

**Issue by AnirudhVyas** [sbt/sbt#7434] opened 2023-11-14 20:37 UTC
## steps

__sbt version:__ 1.9.6

__build sbt:__

```scala
import Dependencies._
import sbt._

ThisBuild / organization := "blahblah"
ThisBuild / organizationName := "uberblah"
ThisBuild / useCoursier := false
ThisBuild / version := "0.0.1-SNAPSHOT"
val artifactory = "https://some_legit_url/legit_context_root/blah"

lazy val commonSettings = Seq(
  Test / parallelExecution := false,
  scalafmtOnCompile := true,
  libraryDependencies += akkaWSCommons,
  libraryDependencies += akkaHttp,
  libraryDependencies ++= akkaTyped(CrossVersion.partialVersion(scalaBinaryVersion.value)),
  libraryDependencies ++= awsLibs,
  libraryDependencies += json4s(CrossVersion.partialVersion(scalaBinaryVersion.value)),
  libraryDependencies += jcabi,
  libraryDependencies += logback,
  libraryDependencies += mysqlConnector,
  libraryDependencies += postgres,
  libraryDependencies += queryCommons,
  libraryDependencies += retry,
  libraryDependencies ++= spark(CrossVersion.partialVersion(scalaBinaryVersion.value)),
  libraryDependencies += sparkCommons,
  libraryDependencies += scalaLogging,
  libraryDependencies += someReader,
  libraryDependencies ++= akkaTest(CrossVersion.partialVersion(scalaBinaryVersion.value)),
  libraryDependencies ++= hadoopTestLibraries(CrossVersion.partialVersion(scalaBinaryVersion.value)).map(_ % Test),
  libraryDependencies += scalaTest % Test,
  dependencyOverrides ++= jackson(CrossVersion.partialVersion(scalaBinaryVersion.value)),
  credentials += Credentials(Path.userHome / ".sbt" / ".credentials"),
  credentials += Credentials(Path.userHome / ".ivy2" / ".credentials")
)

scalacOptions ++= Seq("-deprecation", "-feature", "-Ywarn-unused", "-Yrangepos")
enablePlugins(JavaServerAppPackaging)
addCompilerPlugin(scalafixSemanticdb)
Compile / run / mainClass := Some("blahblah.SubmitMain.scala")
Compile / doc / scalacOptions ++= Seq(
  "-no-link-warnings" // Suppresses problems with Scaladoc @throws links
)
Universal / maintainer := "abc-admin"
Universal / topLevelDirectory := Some(packageName.value)
Universal / packageName := name.value

lazy val publishSettings = Seq(
  publishTo := {
    if (isSnapshot.value)
      Some("snapshots".at(artifactory + "/abc-unit;build.timestamp=" + new java.util.Date().getTime))
    else
      Some("releases".at(artifactory + "/abc-release"))
  }
)

lazy val root = (project in file("."))
  .settings(
    ThisBuild / scalaVersion := scala_212,
    name := tarName(CrossVersion.partialVersion(scalaBinaryVersion.value)),
    publish / skip := true,
    commonSettings,
    coverageMinimum := 33.00,
    coverageFailOnMinimum := true
  )

def tarName(scalaVersion: Option[(Long, Long)]): String =
  scalaVersion.collect { case (2, 11) => "blah" }.getOrElse("double-blah")

assembly / assemblyMergeStrategy := {
  case PathList("META-INF", _ @_*) => MergeStrategy.discard
  case "reference.conf"            => MergeStrategy.concat
  case _                           => MergeStrategy.first
}


```

__Scala version:__  2.12.18

## problem

when running sbt clean assembly I get this trace:
```scala
[error] Couldn't run bloopGenerate. Cause: Incomplete(node=Some(Task(_)), tpe=Error, msg=None, causes=List(Incomplete(node=Some(Task(_)), tpe=Error, msg=None, causes=List(Incomplete(node=Some(Task(_)), tpe=Error, msg=None, causes=List(Incomplete(node=Some(Task((tags: Map(Tag(update) -> 1, Tag(network) -> 1), taskDefinitionKey: ScopedKey(Scope(Select(ProjectRef(file:/Users/anirudh.vyas/scala/portal-submit/project/,portal-submit-build)), Zero, Zero, Zero),updateSbtClassifiers)))), tpe=Error, msg=None, causes=List(), directCause=Some(java.lang.IllegalArgumentException: Cannot add dependency 'ch.epfl.scala#sbt-bloop;1.5.11' to configuration 'default' of module default#portal-submit-build$sbt;0.1.0-SNAPSHOT because this configuration doesn't exist!))), directCause=None)), directCause=None)), directCause=None)
[error] java.lang.IllegalArgumentException: Cannot add dependency 'ch.epfl.scala#sbt-bloop;1.5.11' to configuration 'default' of module default#portal-submit-build$sbt;0.1.0-SNAPSHOT because this configuration doesn't exist!
[error] 	at org.apache.ivy.core.module.descriptor.DefaultDependencyDescriptor.addDependencyConfiguration(DefaultDependencyDescriptor.java:567)
[error] 	at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser$AbstractParser.parseDepsConfs(AbstractModuleDescriptorParser.java:157)
[error] 	at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser$AbstractParser.parseDepsConfs(AbstractModuleDescriptorParser.java:128)
[error] 	at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser$AbstractParser.parseDepsConfs(AbstractModuleDescriptorParser.java:118)
[error] 	at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser$AbstractParser.parseDepsConfs(AbstractModuleDescriptorParser.java:113)
[error] 	at sbt.internal.librarymanagement.CustomXmlParser$CustomParser.parseDepsConfs(CustomXmlParser.scala:36)
[error] 	at sbt.internal.librarymanagement.IvySbt$.convertDependency(Ivy.scala:971)
[error] 	at sbt.internal.librarymanagement.IvySbt$.$anonfun$addDependencies$1(Ivy.scala:906)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.internal.librarymanagement.IvySbt$.addDependencies(Ivy.scala:905)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.configureInline(Ivy.scala:317)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.x$7$lzycompute(Ivy.scala:281)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.x$7(Ivy.scala:278)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.moduleDescriptor0$lzycompute(Ivy.scala:278)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.moduleDescriptor0(Ivy.scala:278)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:267)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:212)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:72)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$1.call(Ivy.scala:82)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:113)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:91)
[error] 	at xsbt.boot.Locks$GlobalLock.$anonfun$withFileLock$1(Locks.scala:119)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:12)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.withFileLock(Locks.scala:119)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:71)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:59)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:47)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:36)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:82)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:206)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:203)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:266)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:194)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:22)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.transitiveScratch(LibraryManagement.scala:189)
[error] 	at sbt.Classpaths$.$anonfun$sbtClassifiersTasks$16(Defaults.scala:3556)
[error] 	at sbt.internal.LibraryManagement$$anon$2.call(LibraryManagement.scala:355)
[error] 	at sbt.internal.LibraryManagement$$anon$2.call(LibraryManagement.scala:347)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:113)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:91)
[error] 	at xsbt.boot.Locks$GlobalLock.$anonfun$withFileLock$1(Locks.scala:119)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:12)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.withFileLock(Locks.scala:119)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:71)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:59)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:47)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:36)
[error] 	at sbt.internal.LibraryManagement$.withExcludes(LibraryManagement.scala:347)
[error] 	at sbt.Classpaths$.withExcludes(Defaults.scala:3682)
[error] 	at sbt.Classpaths$.$anonfun$sbtClassifiersTasks$13(Defaults.scala:3543)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (updateSbtClassif
## expectation

Expectation: build should have completed.

## notes
I use java 17

**Comment by eed3si9n** [comment] 2023-11-15 04:09
This looks like a duplicate of https://github.com/sbt/sbt/issues/5263. See https://github.com/sbt/sbt/issues/5263#issuecomment-626462593 for the workaround.

**Closed as not planned by eed3si9n** 2023-11-15 04:09 UTC
