### ISSUE TITLE
cross building support and scripted test plugin compatibility

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#3245] opened 2017-06-03 08:41 UTC
#### build.sbt

```scala
crossSbtVersions := Vector("0.13.15", "1.0.0-M6")
ScriptedPlugin.scriptedSettings
sbtPlugin := true
organization := "com.example"
name := "foo"
```

#### project/build.properties 

```
sbt.version=0.13.16-M1
```

#### project/scripted.sbt 

```scala
libraryDependencies += "org.scala-sbt" % "scripted-plugin" % sbtVersion.value
```

#### src/sbt-test/foo/bar/test

```
> compile
```

execute `sbt ^scripted`

## problem

```
java.lang.NoSuchMethodException: sbt.test.ScriptedTests$.run(java.io.File, boolean, [Ljava.lang.String;, java.io.File, [Ljava.lang.String;)
	at java.lang.Class.getMethod(Class.java:1786)
	at sbt.ScriptedPlugin$$anonfun$scriptedRunTask$1.apply(ScriptedPlugin.scala:39)
	at sbt.ScriptedPlugin$$anonfun$scriptedRunTask$1.apply(ScriptedPlugin.scala:38)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:scriptedRun) java.lang.NoSuchMethodException: sbt.test.ScriptedTests$.run(java.io.File, boolean, [Ljava.lang.String;, java.io.File, [Ljava.lang.String;)
[error] Total time: 0 s, completed Jun 3, 2017 5:23:08 PM
```

## notes

There is no problem with `sbtVersion in pluginCrossBuild := "1.0.0-M5"`. 
I believe this problem caused by https://github.com/sbt/sbt/pull/3151 /cc @jvican

- restore the old method `run(java.io.File, boolean, [Ljava.lang.String;, java.io.File, [Ljava.lang.String;)` in sbt 1.0.x ?
- fix sbt 0.13.x scripted test? (call new method if `sbtVersion in pluginCrossBuild := "1.0.0-M6"` )
- or am I missing my build settings?  Is there existing solutions?  if so, please provide more migration guide 🙏

**Comment by jvican** [comment] 2017-06-03 09:35
Hmmm, I see. Great catch. I think we may want to restore the old method, though it's not elegant. Otherwise we will need people to upgrade their sbt versions and lose time figuring out why it fails.

**Comment by xuwei-k** [comment] 2017-06-04 15:11
workaround

```scala
ScriptedPlugin.scripted := {
  val args = ScriptedPlugin.asInstanceOf[{
    def scriptedParser(f: File): complete.Parser[Seq[String]]
  }].scriptedParser(sbtTestDirectory.value).parsed
  val prereq: Unit = scriptedDependencies.value
  try {
    if((sbtVersion in pluginCrossBuild).value == "1.0.0-M6") {
      ScriptedPlugin.scriptedTests.value.asInstanceOf[{
        def run(
          x1: File,
          x2: Boolean,
          x3: Array[String],
          x4: File,
          x5: Array[String],
          x6: java.util.List[File]
        ): Unit
      }].run(
        sbtTestDirectory.value,
        scriptedBufferLog.value,
        args.toArray,
        sbtLauncher.value,
        scriptedLaunchOpts.value.toArray,
        new java.util.ArrayList()
      )
    } else {
      ScriptedPlugin.scriptedTests.value.asInstanceOf[{
        def run(
          x1: File,
          x2: Boolean,
          x3: Array[String],
          x4: File,
          x5: Array[String]
        ): Unit
      }].run(
        sbtTestDirectory.value,
        scriptedBufferLog.value,
        args.toArray,
        sbtLauncher.value,
        scriptedLaunchOpts.value.toArray
      )
    }
  } catch { case e: java.lang.reflect.InvocationTargetException => throw e.getCause }
}
```

**Comment by jvican** [comment] 2017-06-13 22:00
@xuwei-k Here's my proposed solution: https://github.com/sbt/sbt/pull/3268/files. I think it's the cleanest.
  
To all the people affected by this: I suggest that you redefine what scripted means for your build until this is merged and released. I would like to ship this change in a binary compatible sbt 1.0.0-M6-2 (and that has to be confirmed by @eed3si9n). I'll keep you in the loop.

**Comment by eed3si9n** [comment] 2017-06-13 22:24
I don't know if releasing 1.0.0-M6-2 is actually going to solve this. Currently I'm using 0.13.16-M1 to cross build against 0.13 and 1.0.0-M6. _It_ knows the compatible binary versions for all sbt versions to determine the linking sbt modules and the suffix, not 1.0.0-M6.

I think what we need to do is actually publish 0.13.16-M2 with the fix.

**Closed as completed** 2017-06-14 10:12 UTC

**Comment by jvican** [comment] 2017-06-14 10:16
The reason I;ve proposed to release `1.0.0-M6-2` is because I'd like to have the last two more important bug fixes available for M6 (the test log cleanup and this one).
  
If we do that, we not only help plugins that want to cross-compile but also users that want to use sbt 1.0.0 and are used to the coloring of sbt tests. I think it's worth it...
