### ISSUE TITLE
active.json should be removed on sbt shell exit

### ISSUE THREAD

**Issue by olafurpg** [sbt/sbt#3862] opened 2018-01-08 23:18 UTC
## steps
```
$ sbt 
...
[info] sbt server started at local:///Users/ollie/.sbt/1.0/server/bee8812eca596a7b260c/sock
sbt:test-workspace-sbt-1-1>exit
$ cat project/target/active.json
{"uri":"local:///Users/ollie/.sbt/1.0/server/bee8812eca596a7b260c/sock"}
```

## problem

The `active.json` file still exists after exiting the sbt shell. The existence of the file should indicate that sbt server is listening on that socket but the server has exited and is no longer listening. This makes it harder for clients to know if sbt server is actually listening on that socket, the only way to find out is to try and connect and check for "Connection refused".

## expectation

I expected the active.json file to be removed on sbt shell exit. This would simplify the life of clients integrating with sbt server.

## notes

sbt version: 1.1.0

**Comment by eed3si9n** [comment] 2018-01-12 19:45
Yes. The intent was to remove the file.

**Comment by mrveera** [comment] 2018-03-19 10:20
@eed3si9n  Would you mind If I create PR for this?

**Comment by eed3si9n** [comment] 2018-03-19 10:20
Plz do. I put help wanted for this reason :)

**Comment by eed3si9n** [comment] 2018-03-19 10:24
Places to look into:
https://github.com/sbt/sbt/blob/v1.1.1/main/src/main/scala/sbt/Main.scala#L108-L117

```scala
  def runManaged(s: State): xsbti.MainResult = {
    val previous = TrapExit.installManager()
    try {
      try {
        try {
          MainLoop.runLogged(s)
        } finally exchange.shutdown
      } finally DefaultBackgroundJobService.backgroundJobService.shutdown()
    } finally TrapExit.uninstallManager(previous)
  }
```

That calls exchange.shutdown, which should eventually call server shutdown as well https://github.com/sbt/sbt/blob/v1.1.1/main-command/src/main/scala/sbt/internal/server/Server.scala#L124-L133

```scala
      override def shutdown(): Unit = {
        log.info("shutting down server")
        if (portfile.exists) {
          IO.delete(portfile)
        }
        if (tokenfile.exists) {
          IO.delete(tokenfile)
        }
        running.set(false)
      }
```

**Comment by mrveera** [comment] 2018-03-19 10:50
Hey @eed3si9n,
 I need small clarity Its already resolved in sbt-version 1.1.1
Do you want me to work on 1.1.0?

**Comment by eed3si9n** [comment] 2018-03-19 10:53
If it already works with 1.1.1, then we can just close this issue.

**Comment by eed3si9n** [comment] 2018-03-19 10:56
@olafurpg I can't reproduce this either, so I am going to close this for now.

**Comment by mrveera** [comment] 2018-03-19 10:58
@eed3si9n  I hope you checked it before closing.

**Comment by eed3si9n** [comment] 2018-03-19 10:59
I tried on my machine using a hello world project.

**Comment by mrveera** [comment] 2018-03-19 11:01
Cool @eed3si9n  The same I was tested.

**Comment by mrveera** [comment] 2018-03-19 11:02
Do you have any other things
 that I can Fix quickly?

**Comment by eed3si9n** [comment] 2018-03-19 11:06
I can't promise "quickly" but something like https://github.com/sbt/sbt/issues/3849 might be contained.

**Comment by dwijnand** [comment] 2018-03-19 11:15
this isn't fixed. using sbt/sbt's build (HEAD 933668076):

```bash
$ sbt
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
[info] Loading settings from idea.sbt,global-plugins.sbt ...
[info] Loading global plugins from /Users/dnw/.dotfiles/.sbt/1.0/plugins
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /d/sbt/project
[info] Loading settings from build.sbt ...
[info] Resolving key references (15599 settings) ...
[info] Set current project to sbtRoot (in build file:/d/sbt/)
[info] sbt server started at local:///Users/dnw/.sbt/1.0/server/9bea40e9748dc34f2c46/sock
> compile
[info] Updating bundledLauncherProj...
[info] Updating ...
^C
11:13:41 ! ll project/target/
project/target/
├── [drwxr-xr-x dnw      staff     256 Mar 16 17:38]  config-classes/
├── [drwxr-xr-x dnw      staff      96 Jan 24 14:04]  scala-2.12/
├── [drwxr-xr-x dnw      staff     160 Jan 24 14:04]  streams/
└── [-rw-r--r-- dnw      staff      70 Mar 19 11:13]  active.json

3 directories, 1 file

11:13:46 $ more project/build.properties
sbt.version=1.1.1
```

**Comment by eed3si9n** [comment] 2018-03-19 11:16
Ólaf's step said "exit" not shoot the computer with handgun.

**Comment by mrveera** [comment] 2018-03-19 11:19
Dear @eed3si9n, the @dwijnand comment makes sense for me.
Even user closed in the middle of execution we should shutdown server and remove active.json file

**Comment by eed3si9n** [comment] 2018-03-19 11:20
We do already have exit hook if you want to look into this further.

**Comment by mrveera** [comment] 2018-03-19 11:37
Yeah @eed3si9n, It has a hook to exit  but what about handling ^C

**Comment by dwijnand** [comment] 2018-03-19 11:43
> Ólaf's step said "exit" not shoot the computer with handgun.

can you reproduce with exit on 1.1.0?

**Comment by eed3si9n** [comment] 2018-03-19 11:44
> can you reproduce with exit on 1.1.0?

No, it worked for me.

**Comment by dwijnand** [comment] 2018-03-19 11:46
same for me.

**Comment by olafurpg** [comment] 2018-03-19 12:10
The reproduction steps in the ticket include `exit` but it would be nice if ^C was also handled. This is not a blocker issue however, as a client to sbt server a workaround is to catch errors when establishing a connection.

**Comment by olafurpg** [comment] 2018-03-19 12:11
It goes without saying that a client should handle errors when establishing the connection regardless if this ticket is fixed or not.

**Comment by dwijnand** [comment] 2018-06-12 13:10
Reviewing this I was really confused at the time. :smile:

Let's call this one resolved - I've opened https://github.com/sbt/sbt/issues/4191 about the file being removed on JVM shutdown.

**Closed as completed by dwijnand** 2018-06-12 13:10 UTC
Labels: help wanted, area/server

**Comment by markusa380** [comment] 2020-11-02 11:17
I'm seeing this issue again on my system when using SBT 1.4.2 with Metals - the `active.json` isn't being removed causing a restart of SBT not attempting to start a build server - but only if I connected to it using Metals. If I don't connect it seems to be removed normally.

@dwijnand

**Comment by eatkins** [comment] 2020-11-02 16:36
@markusa380 my guess is that metals, or something else, is creating a new server instance. The presence of the `active.json` file should not in itself prevent sbt from starting a server. When there is an `active.json` file, the sbt instance attempts to make a client connection to the socket described in the file. It should only be when successfully makes a client connection that sbt aborts creating a server and logs a warning about multiple instances. Otherwise it is supposed to delete the `active.json` file and try to start a new server. Can you verify that there is actually no other sbt server running when you see this behavior?
