### ISSUE TITLE
Config traversal - unexpected behaviour - reloaded

### ISSUE THREAD

**Issue by frgomes** [sbt/sbt#2247] opened 2015-10-19 15:21 UTC
This issue is pretty similar to https://github.com/sbt/sbt/issues/1932, but much simpler.

Sources: http://github.com/frgomes/sbt-issue-2247

It was expected that:
1. alias _r1_ would execute Application1 (executed by configuration _RunnerR1_) and
2. alias _r2_ would execute Application2 (executed by configuration _RunnerR2_)

But both run only Application2

```
sbt-issue-2247/
├── build.sbt
├── build.sbt.HACKED
├── ModuleA
│   └── src
│       └── main
│           └── scala
│               ├── Application1.scala
│               └── Application2.scala
└── project
    └── build.properties
```

NOTE: `build.sbt.HACKED` provides a way to circumvent this issue.
## build.sbt

``` scala
import sbt._
import Keys._

lazy val buildSettings: Seq[Setting[_]] = Defaults.defaultSettings
lazy val forkRunOptions: Seq[Setting[_]] = Seq(fork := true)

addCommandAlias("r1",       "ModuleA/RunnerR1:run")
addCommandAlias("r2",       "ModuleA/RunnerR2:run")

lazy val RunnerR1 = sbt.config("RunnerR1").extend(Compile)
lazy val RunnerR2 = sbt.config("RunnerR2").extend(Compile)

lazy val root =
  project
    .in(file("."))
    .settings(buildSettings:_*)
    .aggregate(ModuleA)

lazy val ModuleA =
  project
    .in(file("ModuleA"))
    .settings(buildSettings:_*)
    .configs(RunnerR1,RunnerR2)
    .settings(inConfig(RunnerR1)(
      forkRunOptions ++
        Seq(
          mainClass in Compile :=  Option("sbt.tests.issueX.Application1"))):_*)
    .settings(inConfig(RunnerR2)(
      forkRunOptions ++
        Seq(
          mainClass in Compile :=  Option("sbt.tests.issueX.Application2"))):_*)
```
## REPL

``` shell
$ sbt
[info] Loading global plugins from /home/richard/.sbt/0.13/plugins
[info] Loading project definition from /home/richard/workspace/sbt-issue-X/project
[info] Updating {file:/home/richard/workspace/sbt-issue-X/project/}sbt-issue-x-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to root (in build file:/home/richard/workspace/sbt-issue-X/)
> compile
[info] Updating {file:/home/richard/workspace/sbt-issue-X/}root...
[info] Updating {file:/home/richard/workspace/sbt-issue-X/}ModuleA...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Resolving org.scala-lang#scala-compiler;2.10.5 ...
[info] Compiling 2 Scala sources to /home/richard/workspace/sbt-issue-X/ModuleA/target/scala-2.10/classes...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[success] Total time: 1 s, completed 19-Oct-2015 16:18:15
> r1
[info] Running sbt.tests.issueX.Application2 
This is Application2
[success] Total time: 0 s, completed 19-Oct-2015 16:18:18
> r2
[info] Running sbt.tests.issueX.Application2 
This is Application2
[success] Total time: 0 s, completed 19-Oct-2015 16:18:20
```

**Comment by jsuereth** [comment] 2015-10-19 15:35
This is, unfortunately, expected.

Why?

Your configuration is copying the `mainClass` setting into a new configuration.  HOWEVER, you are not copying the _tasks_ into this configurations.  SO when you type:

`r2` (or `ModuleA/RunnerR1:run`) what happens is it uses the configuration inheritance to find the right tasks.  There is no task in the new configuration.   We wind up finding `ModuleA/compile:run`, which we use.

The "workaround" is to actually dupicate the `run` task in your configuration (the details for doing that escape me).

I'm not sure whether to mark this "WontFix" or "Enhancement".  There's an experimental thing we have in place to actually make this work as you'd like (`Def.derived`), but it turns out to have its own set of warts and rough edges.  I'm not sure we have a good way to "solve" the problem (hence a possible wontfix, with better docs being our only answer for now).

cc> @eed3si9n + @dwijnand for thoughts on this one.

**Comment by frgomes** [comment] 2015-10-20 16:17
NOTE: `build.sbt.HACKED` provides a way to circumvent this issue.
see: https://github.com/frgomes/sbt-issue-2247/blob/master/build.sbt.HACKED

**Comment by frgomes** [comment] 2015-10-20 18:43
On StackOverflow:
http://stackoverflow.com/questions/33243981/how-can-i-override-tasks-run-and-runmain-in-sbt-to-use-my-own-forkopti/33244341#33244341

**Comment by eed3si9n** [comment] 2019-09-19 21:05
Closing this as a duplicate of https://github.com/sbt/sbt/issues/2899.
It's a won't fix for sbt 1.x, but the change required to fix this is surprisingly small based on what I saw on @dwijnand's laptop.

**Closed as completed by eed3si9n** 2019-09-19 21:05 UTC
Labels: Needs discussion/On Hold

**Comment by dwijnand** [comment] 2019-09-20 06:49
> the change required to fix this is surprisingly small based on what I saw on @dwijnand's laptop.

Unsurprisingly incomplete too, though...

Need to either continue to extend the repro model to the model in sbt, or try to modify sbt's model proper.  Anyways, my repro model is at https://github.com/dwijnand/usbt/blob/master/usbt.scala.
