### ISSUE TITLE
The "console" tasks should be mentioned by "sbt help"

### ISSUE THREAD

**Issue by x3ro** [sbt/sbt#482] opened 2012-06-14 15:56 UTC
I added a reference on the wiki FAQ page, as I couldn't think of a better place to put it. But I guess "help" should mention it.

**Comment by harrah** [comment] 2012-06-28 14:15
Essentially a duplicate of #277.  See the output of 'help' in 0.12.0 (currently RC3), which lists the 'tasks' command more prominently.

**Closed as completed by harrah** 2012-06-28 14:15 UTC
Labels: Duplicate
