### ISSUE TITLE
SBT creating unnecessary empty directories

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt#1914] opened 2015-03-12 08:04 UTC
When I compile my Play project, it creates directories like `target/scala-2.10/twirl/test` as empty directories. This is annoying because these empty directories get pulled into Eclipse and make it harder to find the meaningful directories. Can we avoid creating these directories until we know there's going to content in them?

**Comment by pauldraper** [comment] 2015-03-13 08:08
+1

**Comment by eed3si9n** [comment] 2015-03-15 09:40
That directory seems to be part of managed source directory for the Test configuration.

```
reactive-stocks> test:managedSourceDirectories
[info] List(reactive-stocks/target/scala-2.11/src_managed/test, reactive-stocks/target/scala-2.11/twirl/test)
```

It seems the directory is added to the list by sbt-twirl. I don't know if the plugin creates an empty directory or not (I don't think sbt is creating it), but even if it did I feel like it's a reasonable thing to generate a directory if it's part of `managedSourceDirectories in Test`. typesafehub/sbteclipse#82 says that Eclipse's classpath should match that of your build. 

I'm going to close this for now, but feel free to reopen it if you can reproduce this issue without having plugins involved.

**Closed as completed by eed3si9n** 2015-03-15 09:40 UTC
Labels: Needs Reproduction Test Case

**Comment by benmccann** [comment] 2015-03-17 16:34
We found the issue and it's in sbteclipse. I should have done a better job verifying it was in sbt before filing this issue. Thanks for looking at this issue though

**Comment by benmccann** [comment] 2015-03-19 03:45
Fix checked in here: https://github.com/typesafehub/sbteclipse/commit/ac825d5453d837a86675ec047dbedebd2470e0cd
