### ISSUE TITLE
SBT 1.0.2 fails to fetch dependencies from maven.twttr.com

### ISSUE THREAD

**Issue by ckozak** [sbt/sbt#3670] opened 2017-10-25 22:41 UTC
Some of the libraries from maven.twttr.com can't be downloaded if they are not already in local cache

## steps
- delete `~/.sbt` and `~/.ivy2` folders
- `build.sbt`
```
resolvers ++= Seq(
  "twitterrepo" at "http://maven.twttr.com"
)

libraryDependencies += "com.twitter.common.zookeeper" % "server-set" % "1.0.103"
```

- try to run `sbt update`

## problem
sbt can't download the library
```
[warn] problem while downloading module descriptor: http://maven.twttr.com/com/twitter/common/zookeeper/server-set/1.0.103/server-set-1.0.103.pom: null (36ms)
[warn] 	module not found: com.twitter.common.zookeeper#server-set;1.0.103
[warn] ==== local: tried
[warn]   /Users/constantine.kozak/.ivy2/local/com.twitter.common.zookeeper/server-set//1.0.103/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/twitter/common/zookeeper/server-set/1.0.103/server-set-1.0.103.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/constantine.kozak/.sbt/preloaded/com.twitter.common.zookeeper/server-set/1.0.103/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/constantine.kozak/.sbt/preloaded/com/twitter/common/zookeeper/server-set/1.0.103/server-set-1.0.103.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/twitter/common/zookeeper/server-set/1.0.103/server-set-1.0.103.pom
[warn] ==== Typesafe Releases: tried
[warn]   https://repo.typesafe.com/typesafe/maven-releases/com/twitter/common/zookeeper/server-set/1.0.103/server-set-1.0.103.pom
[warn] ==== bintray/websudos: tried
[warn]   http://dl.bintray.com/websudos/oss-releases/com/twitter/common/zookeeper/server-set/1.0.103/server-set-1.0.103.pom
[warn] ==== twitterrepo: tried
[warn]   http://maven.twttr.com/com/twitter/common/zookeeper/server-set/1.0.103/server-set-1.0.103.pom
[warn] ==== Maven2 Local: tried
[warn]   file:/Users/constantine.kozak/.m2/repository/com/twitter/common/zookeeper/server-set/1.0.103/server-set-1.0.103.pom
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.11/scala-compiler-2.11.11.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.11/scala-library-2.11.11.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.11/scala-reflect-2.11.11.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.twitter.common.zookeeper#server-set;1.0.103: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.twitter.common.zookeeper:server-set:1.0.103 (/Users/constantine.kozak/Development/DepTest/build.sbt#L15-16)
[warn] 		  +- default:deptest_2.11:0.1
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.twitter.common.zookeeper#server-set;1.0.103: not found
```

But `http://maven.twttr.com/com/twitter/common/zookeeper/server-set/1.0.103/server-set-1.0.103.pom` path is valid and the library can be downloaded in previous versions of SBT

## expectation
dependencies are downloaded without any issues

## notes

sbt version: 1.0.2, 1.0.3

it looks like a regression, works fine with sbt 1.0.1

**Comment by alexarchambault** [comment] 2017-10-27 13:57
FYI, this seems to work fine when [sbt-coursier](http://get-coursier.io) is enabled.

**Comment by ckozak** [comment] 2017-10-31 21:31
still broken on 1.0.3

**Comment by ckozak** [comment] 2017-10-31 21:32
@alexarchambault it's logical that it would work with sbt-coursier because the issue is likely in library resolving code. But our project doesn't compile with coursier and I wasn't able to reproduce that yet in an isolated case

**Comment by eed3si9n** [comment] 2017-10-31 21:38
Here's a workaround for 1.0.3 (or any 1.0.x):

```scala
updateOptions := updateOptions.value.withGigahorse(false)
```

**Comment by eed3si9n** [comment] 2017-10-31 21:38
Potentially related to https://github.com/sbt/sbt/issues/3519

**Comment by alexarchambault** [comment] 2017-10-31 22:01
> But our project doesn't compile with coursier and I wasn't able to reproduce that yet in an isolated case

@ckozak Yeah, I'm interested in knowing more. Some issues with Java 9, and sbt >= 1.0.2, were fixed in the latest 1.0.0-RC13, if ever that's related to the errors you're seeing.

**Comment by ckozak** [comment] 2017-10-31 22:17
@eed3si9n can confirm, your workaround works

**Comment by dragisak** [comment] 2017-11-27 17:48
This is still broken in 1.0.4

**Comment by absynthe** [comment] 2018-01-30 10:08
For me changing from "http://maven.twttr.com" to "https://maven.twttr.com" worked.

**Comment by jimschubert** [comment] 2018-05-23 14:10
I believe `http://maven.twttr.com` should be HTTPS `https://maven.twttr.com`. Maybe the issue is that `withGigahorse` isn't following redirects.

**Comment by eed3si9n** [comment] 2019-08-09 20:53
This works in sbt 1.3.0-RC3 that uses Coursier internally.

**Closed as completed by eed3si9n** 2019-08-09 20:53 UTC
Labels: area/library_management
