### ISSUE TITLE
[1.3.0-RC1] java.nio.file.InvalidPathException on Windows when class names have non-Ascii characters 

### ISSUE THREAD

**Issue by plokhotnyuk** [sbt/sbt#4717] opened 2019-05-23 07:00 UTC
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

1. Clone the following repo: https://github.com/plokhotnyuk/jsoniter-scala
2. Set `1.3.0-RC1` in `project/build.properties`
3. Run tests: `sbt clean test`

## problem

[error] (jsoniter-scala-macros / Test / compileIncremental) java.nio.file.InvalidPathException: Illegal char <?> at index 144: C:\projects\jsoniter-scala\jsoniter-scala-macros\target\scala-2.12\test-classes\com\github\plokhotnyuk\jsoniter_scala\macros\JsonCodecMakerSpec$?$1.class

## expectation

No compilation errors

## notes

Full build log: https://ci.appveyor.com/project/plokhotnyuk/jsoniter-scala/builds/24602003
Full stacktrace:
```
[error] java.nio.file.InvalidPathException: Illegal char <?> at index 144: C:\projects\jsoniter-scala\jsoniter-scala-macros\target\scala-2.12\test-classes\com\github\plokhotnyuk\jsoniter_scala\macros\JsonCodecMakerSpec$?$1.class
[error] 	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
[error] 	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
[error] 	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
[error] 	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
[error] 	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
[error] 	at java.nio.file.Paths.get(Paths.java:84)
[error] 	at com.swoval.files.SimpleFileTreeView$Lister.impl(SimpleFileTreeView.java:168)
[error] 	at com.swoval.files.SimpleFileTreeView$Lister.fillResults(SimpleFileTreeView.java:140)
[error] 	at com.swoval.files.SimpleFileTreeView$Lister.impl(SimpleFileTreeView.java:161)
[error] 	at com.swoval.files.SimpleFileTreeView$Lister.fillResults(SimpleFileTreeView.java:140)
[error] 	at com.swoval.files.SimpleFileTreeView$Lister.impl(SimpleFileTreeView.java:161)
[error] 	at com.swoval.files.SimpleFileTreeView$Lister.fillResults(SimpleFileTreeView.java:140)
[error] 	at com.swoval.files.SimpleFileTreeView$Lister.impl(SimpleFileTreeView.java:161)
[error] 	at com.swoval.files.SimpleFileTreeView$Lister.fillResults(SimpleFileTreeView.java:140)
[error] 	at com.swoval.files.SimpleFileTreeView$Lister.impl(SimpleFileTreeView.java:161)
[error] 	at com.swoval.files.SimpleFileTreeView$Lister.fillResults(SimpleFileTreeView.java:140)
[error] 	at com.swoval.files.SimpleFileTreeView$Lister.impl(SimpleFileTreeView.java:161)
[error] 	at com.swoval.files.SimpleFileTreeView$Lister.fillResults(SimpleFileTreeView.java:140)
[error] 	at com.swoval.files.SimpleFileTreeView.list(SimpleFileTreeView.java:50)
[error] 	at sbt.io.DescendantOrSelfPathFinder$.default(Path.scala:666)
[error] 	at sbt.io.DescendantOrSelfPathFinder$$anonfun$$lessinit$greater$1.apply(Path.scala:649)
[error] 	at sbt.io.DescendantOrSelfPathFinder$$anonfun$$lessinit$greater$1.apply(Path.scala:649)
[error] 	at sbt.io.DescendantOrSelfPathFinder.$anonfun$addTo$1(Path.scala:653)
[error] 	at sbt.io.DescendantOrSelfPathFinder.$anonfun$addTo$1$adapted(Path.scala:651)
[error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error] 	at sbt.io.DescendantOrSelfPathFinder.addTo(Path.scala:651)
[error] 	at sbt.io.PathFinderImpl.get(Path.scala:604)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$9(AnalyzingJavaCompiler.scala:138)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:742)
[error] 	at scala.collection.immutable.Map$Map1.foreach(Map.scala:128)
[error] 	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:741)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:136)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$5(MixedAnalyzingCompiler.scala:134)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:100)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1655)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1628)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:270)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:279)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:270)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by eed3si9n** [comment] 2019-05-23 12:55
@plokhotnyuk Thanks for the report with repro steps!
This looks like a duplicate of https://github.com/sbt/sbt/issues/4690, so I am going to close this but I might borrow the title etc.

**Closed as completed by eed3si9n** 2019-05-23 12:55 UTC
