### ISSUE TITLE
Warning on transitive macro recompilation

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2614] opened 2016-05-13 13:33 UTC
## steps
1. Transitive macro definition causes recompilation by default.
## problem

This can end up invalidating a lot of code.
## expectation

Print warning message during compilation, so people are aware of why suddenly incremental compiler is recompiling everything.

**Comment by dwijnand** [comment] 2016-07-07 17:37
This isn't in the default branch (1.0.x), but it is in 0.13.12, which is what the issue is targeting. So I'm going to close it given #2637 was merged, and it's in 0.13.12-RC1.

**Closed as completed by dwijnand** 2016-07-07 17:37 UTC

**Comment by eed3si9n** [comment] 2016-07-07 17:38
Don't we have to forward port?

**Comment by dwijnand** [comment] 2016-07-07 17:41
Yes. Added to #2352. Good shout.
