### ISSUE TITLE
doc task failing on package objects.

### ISSUE THREAD

**Issue by anikifoss** [sbt/sbt#269] opened 2011-11-17 06:41 UTC
Doc task is failing with the following error:

[error] error while loading package, Missing dependency 'class pkg.subpkg.package', required by ./target/broken/scala-2.9.1/classes/pkg/subpkg/package.class

This happens only if the project is compiled first, then doc is called. If the target directory is removed, and then doc is called, then the task will succeed.

The stragest thing is that the doc task is picking up on compilation units from other projects. In effect, when publishing large project, it's pretty much guranteed that there will be some package objects somewhere in the target dir, causing doc task to fail.

Stranger yet, adding a dummy dependency to a failing project via dependsOn(dummyProject) fixes the issue. Of course, this depenency becomes an ivy depenency and gets published, so it's not a viable workaround.

I will attempt to add a sample project as an attachment to the ticket. If it does not work, please contact me via email to get a copy of the sample project that replicates the bug (it's been reduced to a couple of files).

**Comment by anikifoss** [comment] 2011-11-17 06:49
There seems to be no way to add attachments. You can setup the project as described below or email me to get a zip. The project setup is as follows:

project
--Build.scala
src
--pkg
----package.scala

Build.scala contains:

import sbt._
import Keys._

object Simplex3d extends Build {

  val buildSettings = Defaults.defaultSettings ++ Seq (
    scalaSource in Compile <<= baseDirectory(_ / "src")
  )

  lazy val dummyProjectToFixSbt = Project(
    id = "dummy-project",
    base = file("."),
    settings = buildSettings ++ Seq (
      target := new File("target/dummy-project"),
      excludeFilter := "*"
    )
  )

  lazy val working = Project(
    id = "working",
    base = file("."),
    settings = buildSettings ++ Seq (
      target := new File("target/working")
    )
  ) dependsOn(Simplex3d.dummyProjectToFixSbt)

  lazy val broken = Project(
    id = "broken",
    base = file("."),
    settings = buildSettings ++ Seq (
      target := new File("target/broken")
    )
  )
}

package.scala contains:

package pkg

package object subpkg {
  final val foo = "Foo"
}

To replicate a basic error:
1) Remove target dir before attempting to replicate.
2) sbt -> project broken -> compile -> doc

To replicate an error involving classes from another project in an unrelated directory:
1) Remove target dir before attempting to replicate.
2) sbt -> project working -> compile -> doc
3) project broken -> doc

The only viable workaround I could find:
1) Remove target dir.
2) sbt -> project broken -> doc

**Comment by indrajitr** [comment] 2011-11-17 10:46
@harrah is this related to #82, #85 ?

**Comment by anikifoss** [comment] 2011-11-17 13:55
This is not related to #82. This problem seems to be the same as #85.

**Comment by harrah** [comment] 2011-11-17 14:45
closing as duplicate of #82 and #85 (they are the same underlying issue)

**Comment by anikifoss** [comment] 2011-11-17 19:09
If build tools are responsible for reducing complexity behind the build process, shouldn't this include working around known bugs in the underlying system?

I have gathered that the problem is on scalac side, and it has been fixed in Scala's trunk, but the release date is unknown. In the meantime (and it has been almost half a year since this issue was raised) you pretty much throw your users under the bus, even though the workaround on your side is trivial. This is very discouraging.

**Comment by indrajitr** [comment] 2011-11-18 10:20
Okay, this is actually recreatable in 0.11-2-SNAPSHOT, so it really exists.

Contrary to what JIRA says, [SI-4782](https://issues.scala-lang.org/browse/SI-4782), has actually been fixed in Scala 2.9.1 which is what SBT is using now (see [Release Notes](http://www.scala-lang.org/node/10780)). I haven't yet seen the compiler code in Scala to see what it does with the `-cp` arguments, but the current workaround of adding an empty string doesn't address the problem.

So what about a more 'sledgehammer'-ish workaround of appending a dummy file to the `-cp` when it is empty? Say, something like:

``` scala
val classpathOption = Seq("-classpath", if(cpWithCompiler.isEmpty) file("some_random_in_tmp").getAbsolutePath else absString(cpWithCompiler) )
```

**Comment by indrajitr** [comment] 2011-11-18 10:31
Sample project showing the problem. https://github.com/indrajitr/broken-classpath

**Comment by harrah** [comment] 2011-11-19 01:31
Heh, the release notes are actually contradictory.  In the fixed ticket section, it includes the bug, but the changeset is not listed.  I'm inclined to believe it isn't actually in 2.9.1.

**Comment by indrajitr** [comment] 2011-11-19 09:04
Well, looking at the [SVN tree for 2.9.1.final](http://lampsvn.epfl.ch/trac/scala/browser/scala/tags/R_2_9_1_final/src/compiler/scala/tools/nsc/settings/MutableSettings.scala#L52), I am inclined to believe the other way round :) But we shouldn't be going through this conversation in an ideal world. Release notes (at least for stable releases) are permanent document and they should be accurate.

**Comment by retronym** [comment] 2011-11-19 09:21
The dummy classpath entry doesn't need to correspond to an actual file or folder. I've just used "dummy".

**Comment by indrajitr** [comment] 2011-11-19 09:33
Acknowledged the file doesn't need to exist -- going through `Random` just reduces the possibility of conflicting with some real file name "dummy" or something.

**Closed as completed** 2011-11-19 11:28 UTC
Labels: Duplicate
