### ISSUE TITLE
Windows MSI installer for version 0.13.9 actually installs version 0.13.8

### ISSUE THREAD

**Issue by larspars** [sbt/sbt#2316] opened 2015-12-15 08:27 UTC
I noticed that the installer sbt-0.13.9.msi actually installs version 0.13.8.

After installing:

```
C:\Program Files (x86)\sbt\bin>sbt --about
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] This is sbt 0.13.8
```

**Comment by eed3si9n** [comment] 2015-12-15 08:29
Duplicate of #2181

**Closed as completed by eed3si9n** 2015-12-15 08:29 UTC
