### ISSUE TITLE
Improve error message when publish credentials are not found

### ISSUE THREAD

**Issue by jsuereth** [sbt/sbt#660] opened 2013-02-01 14:49 UTC
It should be _obvious_ that credentials were not found and what they would need to be.  Even if publishing somewhere that requires no credentials (which I think is a rarer case).

Currently, the error is nested in a mess of ivy output.  Would be ideal to highlight this sucker and bring it out if possible.  May require a good bit of work, but it's the most common error I see with regards to publishing:  malformed credentials.

**Comment by hseeberger** [comment] 2013-02-01 14:49
+1

**Comment by jsuereth** [comment] 2013-06-17 01:32
A note to myself (when I have a chance to fix this) i that you can find the authentication realm by doing a HEAD request on a repository:

```
 (master *=) ➜ curl --head https://api.bintray.com/content/jsuereth/sbt-plugins/
HTTP/1.1 401 Unauthorized
Server: nginx
Date: Mon, 17 Jun 2013 01:31:21 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 1025
Connection: keep-alive
Set-Cookie: rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Sun, 16-Jun-2013 01:31:21 GMT; Secure
WWW-Authenticate: Basic realm="Bintray API Realm"
```

With the bottom line being the important one...

**Comment by harrah** [comment] 2013-07-12 21:57
Related to and possibly a duplicate of #429.

**Comment by harrah** [comment] 2013-09-30 13:13
Closing as a duplicate of #429.

**Closed as completed by harrah** 2013-09-30 13:13 UTC
Labels: Duplicate
