### ISSUE TITLE
SBT on Network File System

### ISSUE THREAD

**Issue by BassirouRabo** [sbt/sbt#3925] opened 2018-02-06 22:25 UTC
I installed SBT on NFS, but got an error

## steps
brew update
brew install sbt
Location : .brew/Cellar/sbt/1.1.0/

## problem
java.io.IOException: Operation not supported
	at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:90)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1115)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:88)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at xsbt.boot.Launch.locked(Launch.scala:238)
	at xsbt.boot.Launch.app(Launch.scala:147)
	at xsbt.boot.Launch.app(Launch.scala:145)
	at xsbt.boot.Launch$.run(Launch.scala:102)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.io.IOException: Operation not supported
## expectation

sbt version: *1.1.0*

**Comment by SethTisue** [comment] 2018-02-07 02:51
surely a duplicate of #2222?

**Comment by BassirouRabo** [comment] 2018-02-07 07:40
My question, what is the solution to fix it

**Comment by dwijnand** [comment] 2018-02-07 08:47
Let's discuss in #2222.

**Closed as completed** 2018-02-07 08:47 UTC
