### ISSUE TITLE
Windows installer sets Path environment variable incorrectly

### ISSUE THREAD

**Issue by distinctdan** [sbt/sbt#2665] opened 2016-07-08 20:01 UTC
The windows installer set the sbt path incorrectly. It added a double backslash somewhere, I think it was like `C:\Program Files (x86)\\sbt\bin`, which of course caused it to point to the wrong place. After I removed the double backslash, it appeared to be working fine. I'm running Windows 10.

**Comment by dwijnand** [comment] 2016-08-17 21:15
Duplicate of https://github.com/sbt/sbt-launcher-package/issues/76

**Closed as completed by dwijnand** 2016-08-17 21:15 UTC

**Comment by eed3si9n** [comment] 2016-08-23 05:56
@distinctdan Dale (@dwijnand) fixed the bug so I published a new installer for Windows for 0.13.12. Could you try using it, and see if it fixes the issue for you?
http://www.scala-sbt.org/download.html

**Comment by distinctdan** [comment] 2016-08-23 14:35
Yup, it now sets the path correctly. Thanks!

**Comment by dwijnand** [comment] 2016-08-23 14:59
Awesome. Thanks for the quick turnaround @distinctdan.
