### ISSUE TITLE
SBT 1.0.1+ fails on loading resources

### ISSUE THREAD

**Issue by jdrphillips** [sbt/sbt#3963] opened 2018-02-21 13:47 UTC
Scala code to list resources which works in sbt 0.13.x and SBT 1.0.0 fails in SBT 1.0.1 and 1.1.1

## steps
- Clone this project https://github.com/jdrphillips/sbt-testing
- Run `sbt "run /subfolder"`

Direct link to the code being run: https://github.com/jdrphillips/sbt-testing/blob/master/src/main/scala/foo/Testing.scala

To see a working version using sbt 0.13.17, checkout the branch `1317` on the same project and complete the same steps. To see SBT 1.0.0, checkout branch `100`. The code being run does not change between branches.

The code fails on branches `111` (SBT 1.1.1) and `101` (SBT 1.0.1)

## problem

When trying to load resources in SBT 1.0.1+ using `getClass.getResource`, the path generated is something like:

- `file:/tmp/sbt_2a66a2c6/job-1/target/84311835/sbt-testing_2.12-0.1-SNAPSHOT.jar!/subfolder`

when it should be something like:

- `~/sbt-testing/target/scala-2.12/classes/subfolder`

This change has the effect of being unable to list files in a resource directory. `java.io.File` cannot find the first path.

## expectation

The scala code which runs on the `1317` branch should also run on the `111` and `101` branches (sbt versions `1.1.1` and `1.0.1` respectively).

## notes

scala version `2.12.4`

sbt version: `1.1.1`, `1.0.1`

Confirmed behaviour on Ubuntu and Mac.

**Comment by eed3si9n** [comment] 2018-02-28 08:10
This is likely a regression around `bgRun`.

**Comment by Obarros** [comment] 2018-03-05 22:44
@eed3si9n, @jdrphillips anyone looking into this? 

Seems like a nice first issue to try to help.

**Comment by eed3si9n** [comment] 2018-03-05 22:46
@Obarros Since no one has claimed it here, I'd guess not.

**Comment by Obarros** [comment] 2018-03-05 23:03
@eed3si9n, Thanks, I can try to implement this fix and submit a PR if this is not a priority for the SBT team, but I'd need some guidance on where and how this could be implemented.

**Comment by eed3si9n** [comment] 2018-03-05 23:08
@Obarros Awesome. 
A good starting point if looking at the PR that added bgRun - https://github.com/sbt/sbt/pull/2936/files
and I guess https://github.com/sbt/sbt/blob/v1.1.1/run/src/main/scala/sbt/Run.scala.
If you have any other questions feel free to ask here or gitter sbt/sbt-contrib

**Comment by jdrphillips** [comment] 2018-03-06 08:35
Would love to help @Obarros but I can't guarantee the time I'd need to spend on it as a complete newbie to SBT. If a fix surfaces for it I'll definitely read it

**Comment by tmiyamon** [comment] 2018-03-16 06:35
The cause of this problem seems changing the way to run of sbt between 0.x and 1.x.
sbt 0.x run with build directory but 1.x run with built jar.
The built jar include resources properly so if you can read them as stream.
I think listing resources in jar need to extract jar itself.

**Comment by eed3si9n** [comment] 2018-03-16 06:39
So I guess it works as well as it can as `bgRun`. I am going to close this as design.

**Closed as completed by eed3si9n** 2018-03-16 06:39 UTC
Labels: help wanted, good first issue, area/run

**Comment by sungiant** [comment] 2018-07-15 19:06
If this is as-designed and not a regression, what is the expected workflow for users when it comes to loading resources?

I've just run into the same problem myself.  I would absolutely expect the above code to work in sbt 1.+

**Comment by joroKr21** [comment] 2018-09-28 12:58
That makes walking a directory of files more complicated. Normally I wouldn't care about this in `run`, but this also happens in `jmh:run` when using sbt-jmh.

**Comment by konradmalik** [comment] 2018-11-18 14:52
Can someone explain why is this marked as closed but the problem still presists in SBT 1.2.6?
Whenever I use `getClass.getResource` in my code I cannot use `sbt run` because it'll fail to find the files, this makes `sbt run` basically unusable.
I couldn't even find any workarounds to this. Suggestions?

**Comment by tuzhucheng** [comment] 2019-04-02 05:33
I cannot agree with @konradmalik more. This is still a problem and should be addressed.

Whenever I use `runMain` `sbt` cannot find the resource using `getClass.getResource`.

**Comment by mtsokol** [comment] 2019-04-02 21:34
Hi. I have also encountered same issue lately with `sbt 1.2.8`. 

Here I reproduced this issue as I got it:
https://github.com/mat646/sbt-resource-bug
Pretty the same as origin poster.

**Comment by mtsokol** [comment] 2019-04-06 10:03
@joroKr21 @konradmalik @tuzhucheng Hi once again! 
Few days ago I've written a question on stackoverflow about this issue. Today Mario Galic gave comprehensive answer which seamlessly solved my issue:
https://stackoverflow.com/questions/55493096/listing-files-from-resource-directory-in-sbt-1-2-8
Answer covers either sbt tuning or simply jar handling.

**Comment by warrenronsiek** [comment] 2019-11-19 11:11
Ran into the same issue when trying to programmatically load configs. You have to use the standard `getResource` when running tests, etc. but when executing a jar you have to use `getResourceAsStream`. E.g.: 

```
  private val file = new File(getClass.getResource("/" + configName).getPath)
  val config: Config = if (!file.exists) {
    val jarFile = new File(getClass.getProtectionDomain.getCodeSource.getLocation.getPath)
    val jar = new JarFile(jarFile)
    val configs = jar.entries().asScala
      .filter(!_.isDirectory)
      .filter(entry => entry.getName.contains(configName))
      .map(entry => entry.toString).toList
    try {
      val cfg_input = getClass.getResourceAsStream("/" + configs.head)
      val cfg = scala.io.Source.fromInputStream(cfg_input).mkString
      ConfigFactory.parseString(cfg)
    } catch {
      case ex: NullPointerException => throw new Error("couldn't get the config")
    }
  } else {
    ConfigFactory.parseFile(file)
  }
```
(code adapted from the helpful link posted by @mtsokol)

IMO, this is a bug. I would expect a `getResource` function to work regardless of whether or not its been compiled. Not sure why this considered closed.

**Comment by spydon** [comment] 2020-03-25 16:00
This is still an issue, and should be reopened.
You can add the following to your `build.sbt` as a temporary solution:
`run := Defaults.runTask(fullClasspath in Runtime, mainClass in run in Compile, runner in run).evaluated`
