### ISSUE TITLE
False positive in DSL checker for setting keys

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#3299] opened 2017-06-29 14:31 UTC
## steps

```scala
val foo = taskKey[Unit]("")
val bar = settingKey[Int]("")

bar := 1
foo := (if (true) bar.value)
```

## problem

```
/s/t-2017-06-29.1446/build.sbt:5: error: The evaluation of `bar` happens always inside a regular task.

Problem: `bar` is inside the if expression of a regular task.
  Regular tasks always evaluate task inside the bodies of if expressions.

Solution:
  1. If you only want to evaluate it when the if predicate is true or false, use a dynamic task.
  2. Otherwise, make the static evaluation explicit by evaluating `bar` outside the if expression.

foo := (if (true) bar.value)
                  ^
[error] Type error in expression
```

## expectation

`bar` is a `SettingKey` so there's no evaluation or side-effecting.

## notes

sbt version: 1.0.0-M6

**Comment by eed3si9n** [comment] 2017-07-24 19:43
Fixed in https://github.com/sbt/sbt/pull/3351. This will be part of next RC.

**Comment by xuwei-k** [comment] 2017-08-10 16:59
another example (sbt 1.0.0 final)

```scala
val foo = taskKey[Unit]("")
val bar = settingKey[Int]("")

bar := 1
foo := {
  List(42).map { x =>
    if (true) bar.value
  }
}
```

```
build.sbt:7: error: The evaluation of `bar` happens always inside a regular task.

Problem: `bar` is inside the if expression of a regular task.
  Regular tasks always evaluate task inside the bodies of if expressions.

Solution:
  1. If you only want to evaluate it when the if predicate is true or false, use a dynamic task.
  2. Otherwise, make the static evaluation explicit by evaluating `bar` outside the if expression.

    if (true) bar.value
              ^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

**Comment by jvican** [comment] 2017-08-10 17:07
I'm looking into this.

**Comment by jvican** [comment] 2017-08-10 18:34
@xuwei-k I cannot reproduce locally. I'm trying with https://github.com/sbt/sbt/pull/3421.

**Comment by jvican** [comment] 2017-08-10 18:39
CI cannot reproduce either. Compilation succeeds, meaning that no error is displayed. https://travis-ci.org/sbt/sbt/jobs/263208933 Close if this is an error on your end.

**Comment by xuwei-k** [comment] 2017-08-10 20:45
- https://github.com/xuwei-k/sbt-3299/commit/8327f796392a6e73859392ae27d7b451af7c8da3
- https://travis-ci.org/xuwei-k/sbt-3299/builds/263253265#L395

**Comment by jvican** [comment] 2017-08-10 20:52
Must be an error publishing. I've even cherry-picked my commit on the published v1.0.0 tag and cannot reproduce.

**Comment by jrudolph** [comment] 2017-08-14 16:36
This still happens with 1.0.0:

```
> sbt -Dsbt.version=1.0.0
[warn] No sbt.version set in project/build.properties, base directory: /tmp/broken-lint/blubber
[info] Set current project to blubber (in build file:/tmp/broken-lint/blubber/)
[info] sbt server started at 127.0.0.1:5117
sbt:blubber> set Def.task { if (true) scalaVersion.value }
<set>:1: error: The evaluation of `scalaVersion` happens always inside a regular task.

Problem: `scalaVersion` is inside the if expression of a regular task.
  Regular tasks always evaluate task inside the bodies of if expressions.

Solution:
  1. If you only want to evaluate it when the if predicate is true or false, use a dynamic task.
  2. Otherwise, make the static evaluation explicit by evaluating `scalaVersion` outside the if expression.

Def.task { if (true) scalaVersion.value }
                     ^
[error] Type error in expression
sbt:blubber> 
```

**Comment by jrudolph** [comment] 2017-08-15 11:53
A cursory try to locate the issue turned out that `qual.sym.info` is of type `=> SettingKey` in the false positive case which is not `<:< SettingKey[_]`. So far, I couldn't reproduce it in the test file, maybe it's somehow related to where the key is defined exactly or it has something to do with separate compilation.

**Comment by Duhemm** [comment] 2017-08-15 12:07
Thanks for the repro @jrudolph, I'll look into that soon.

**Closed as completed** 2017-09-13 15:08 UTC

**Comment by sjrd** [comment] 2017-09-13 15:10
Is there a fix in the 0.13.x series as well?

**Comment by dwijnand** [comment] 2017-09-13 15:22
There's no DSL checker in 0.13 (unless I'm losing my mind).

**Comment by sjrd** [comment] 2017-09-13 15:26
Ah! Good point! I got confused with something else, I guess :P
