### ISSUE TITLE
1.4.0-RC2: Not seeing log to STOUT of a running application

### ISSUE THREAD

**Issue by GuntherW** [sbt/sbt#5897] opened 2020-09-25 04:53 UTC
## steps

When I start a http4s application in sbt console via "reStart", I can't see any stout output.
With sbt 1.3.13, the output was visible.
It is reproducable with this tiny http4s application:
https://github.com/GuntherW/Http4sTapirWithAuth
Just clone it, start sbt and run `reStart` in sbt shell.
Retry with sbt 1.3.13 and see the difference.

## problem

I don't the any logs from http4s app in my sbt console, which are targeted to stout

## expectation

I expect the same behaviour, as  sbt 1.3.13

**Comment by eatkins** [comment] 2020-09-25 05:19
Thanks for the report! I can reproduce and the root cause is clear. There was an assumption that tasks would not be printing output after the sbt process had returned to the shell which is obviously wrong for reStart. I should have a fix soon.

**Comment by eed3si9n** [comment] 2020-10-02 01:34
This was fixed in https://github.com/sbt/sbt/pull/5898

**Closed as completed by eed3si9n** 2020-10-02 01:34 UTC
