### ISSUE TITLE
Display warning when invoked in batch mode

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2987] opened 2017-03-03 11:04 UTC
## steps

Someone runs `$ sbt compile` from the terminal.

## expectation

Display 

```
Executing "compile" in batch mode. Note running "sbt" and executing "compile" from the shell repeatedly is going to compile much faster. (Think 2x)
```

## notes

It's been pointed out many times that batch mode is 1.3x ~ 2x slower because of Scalac JIT (and from sbt 0.13.13 classloader caching)
https://twitter.com/eed3si9n/status/837585213563801600

**Comment by dwijnand** [comment] 2017-03-03 11:06
Duplicate of https://github.com/sbt/website/issues/319#issuecomment-277733591, but I'm happy to track this here now.

**Closed as completed** 2017-03-09 09:31 UTC
Labels: Enhancement, help wanted

**Comment by koertkuipers** [comment] 2017-04-26 19:17
i find this feature annoying.

if i run "sbt clean test publish" then i know what i am doing, and i do now want me accidentally hitting an extra [ENTER] to put me in interactive mode. 

i is especially bad when the sbt call is part of a larger script. i have various bash scripts that automatically build multiple projects, and now they sometimes manage to enter interactive mode at times (i am guessing because i hit enter by accident while inspecting terminal output?)

is there a way to disable this? thanks

**Comment by eed3si9n** [comment] 2017-04-26 19:22
@koertkuipers There's a discussion going on in https://github.com/sbt/sbt/issues/3091 on how to improve the implementation. Could you repost your comment there please?

**Comment by koertkuipers** [comment] 2017-04-26 19:23
@eed3si9n okay i will repost there. thanks
