### ISSUE TITLE
dl.bintray.com/sbt returns 403

### ISSUE THREAD

**Issue by juli1** [sbt/sbt#6583] opened 2021-07-06 02:55 UTC
## steps

Trying to download sbt from HTTP://dl.bintray.com/sbt/debian

## problem

I am getting a 403

```
E: Failed to fetch http://dl.bintray.com/sbt/debian/InRelease  403  Forbidden [IP: 52.34.7.22 80]
```

## expectation

The URL should normally work without issue.

**Comment by SethTisue** [comment] 2021-07-06 03:44
duplicate of https://github.com/sbt/sbt/issues/6582 ?

**Comment by eed3si9n** [comment] 2021-07-06 04:08
I don't know why there is a sudden surge of people who are failing to install sbt on Linux without reading the documentation. Are you following some classes or blog post or just coincidence?

**Closed as completed** 2021-07-06 04:11 UTC

**Comment by SethTisue** [comment] 2021-07-06 14:54
@eed3si9n Bintray shut down on July 4. I suspect that people have existing scripts that suddenly stopped working as a result; I doubt it's actual first-time users hitting this.

**Comment by eed3si9n** [comment] 2021-07-06 14:58
> Bintray shut down on July 4.

I see. So I guess Bintray extended grace period for some packaging, but that ended over the weekend?

**Comment by SethTisue** [comment] 2021-07-06 15:26
Yes, as per https://status.bintray.com

**Comment by tovine** [comment] 2021-07-25 14:47
> 
> 
> I don't know why there is a sudden surge of people who are failing to install sbt on Linux without reading the documentation. Are you following some classes or blog post or just coincidence?

In my case it was an old install on Debian that I hadn't touched in about 4 years that started throwing errors on automated updates, I guess that's the same for a lot of other users as well.
Now that I found this issue I'll update my setup. 🙂
