### ISSUE TITLE
Test scope dependencies silently evict Compile/Runtime dependencies

### ISSUE THREAD

**Issue by avdv** [sbt/sbt#5291] opened 2019-12-11 09:00 UTC
## steps
sbt version: `1.3.4`

## problem

After upgrading our project from SBT 1.2.8 to 1.3.4 we were seeing an `UnsupportedOperationException` in production. Details here: https://github.com/featureflow/featureflow-java-sdk/issues/4

This was apparently caused by the okhttp 3.2.0 artifact being evicted by version 3.11.0.

But the `evicted` output gives no clue as to why:
```
[info]  * com.squareup.okhttp3:okhttp:3.11.0 is selected over 3.2.0
[info]      +- io.featureflow:featureflow-java-sdk:1.0.3          (depends on 3.2.0)
```

Looking a bit deeper, I found that there was a single library that transitively depends on okhttp 3.11.0:

```
* com.typesafe.play:play-test:2.7.3:test
  ...
  + org.fluentlenium:fluentlenium-core:3.7.1
    + org.seleniumhq.selenium:selenium-remote-driver:3.141.59
      ...
      + com.squareup.okhttp3:okhttp:3.11.0
    + org.seleniumhq.selenium:selenium-support:3.141.59
      ...
      + com.squareup.okhttp3:okhttp:3.11.0
  + org.seleniumhq.selenium:selenium-firefox-driver:3.141.59
      + com.squareup.okhttp3:okhttp:3.11.0
```

But, as you can see, this one is scoped to `Test`.

## expectation

okhttp version 3.2.0 should be used during runtime / compilation.

**Comment by avdv** [comment] 2019-12-11 09:04
BTW, after setting `useCoursier := false`, the problem is gone.

**Comment by eed3si9n** [comment] 2019-12-11 15:35
@avdv This is a known regression of Coursier - https://github.com/coursier/coursier/issues/1382

**Comment by avdv** [comment] 2019-12-11 15:40
> @avdv This is a known regression of Coursier - [coursier/coursier#1382](https://github.com/coursier/coursier/issues/1382)

Thank you @eed3si9n -- and sorry for the duplicate. Sometimes its a bit hard to choose the right culprit, given all the (sub)projects of sbt, sbt-coursier and whatnot. :wink:

**Comment by eed3si9n** [comment] 2019-12-11 15:43
Your report is totally fair since it is an sbt problem from your point of view. I just wanted to let you know that the suffering is real, and there are others experiencing this :)

**Comment by dwijnand** [comment] 2020-05-20 11:25
Coursier 2.0.0-RC6-17.

**Comment by eed3si9n** [comment] 2020-08-01 21:36
Latest Coursier was merged with scripted passing on our side - https://github.com/sbt/sbt/pull/5575

**Closed as completed by eed3si9n** 2020-08-01 21:36 UTC
Labels: area/library_management, Regression, Merged Upstream
