### ISSUE TITLE
Crossbuilds are broken because of issues with dependency resolver

### ISSUE THREAD

**Issue by pshirshov** [sbt/sbt#4320] opened 2018-08-13 23:20 UTC
I have a demo project which has one shared library targeting two scala versions and two other projects depending on that library and targeting one scala version each.

This project fails to build. Exclusions work but sbt tries to resolve shared artifact with wrong scala version from external resolver which is definitely wrong.

The repo: https://github.com/pshirshov/sbt-assymmetric-crossbuild-bug-demo

How to reproduce: just run `+ test:compile` in sbt shell 

The output on my machine:

```
sbt:root> + test:compile
[info] Setting Scala version to 2.11.12 on 3 projects.
[info] Excluded 1 projects, run ++ 2.11.12 -v for more details.
[info] Reapplying settings...
[info] Set current project to root (in build file:/Users/liyon/work/sbttest/)
[info] Updating shared-lib...
[info] Updating ...
[info] Done updating.
[info] Done updating.
[info] Updating modern-app...
[info] Updating legacy-app...
[info] Done updating.
[warn] 	module not found: shared-lib#shared-lib_2.12;0.1.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/liyon/.ivy2/local/shared-lib/shared-lib_2.12/0.1.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/shared-lib/shared-lib_2.12/0.1.0-SNAPSHOT/shared-lib_2.12-0.1.0-SNAPSHOT.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/liyon/.sbt/preloaded/shared-lib/shared-lib_2.12/0.1.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/liyon/.sbt/preloaded/shared-lib/shared-lib_2.12/0.1.0-SNAPSHOT/shared-lib_2.12-0.1.0-SNAPSHOT.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: shared-lib#shared-lib_2.12;0.1.0-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		shared-lib:shared-lib_2.12:0.1.0-SNAPSHOT
[warn] 		  +- modern-app:modern-app_2.12:0.1.0-SNAPSHOT
[error] sbt.librarymanagement.ResolveException: unresolved dependency: shared-lib#shared-lib_2.12;0.1.0-SNAPSHOT: not found
```

Related: https://github.com/coursier/coursier/issues/893

Tested on `1.2.1` and `1.2.0`

**Comment by eed3si9n** [comment] 2018-08-15 16:20
Duplicate of https://github.com/sbt/sbt/issues/3465

The workaround is:

```scala
lazy val root = (project in file("."))
  .aggregate(`shared-lib`, `legacy-app`, `modern-app`)
  .settings(crossScalaVersions := List())
```

**Closed as completed by eed3si9n** 2018-08-15 16:20 UTC
Labels: area/cross_building
