### ISSUE TITLE
Path setting error on Windows when sbt being installed

### ISSUE THREAD

**Issue by zhou-jg** [sbt/sbt#2684] opened 2016-07-26 01:25 UTC
(See the guidelines for contributing, linked above)
## steps

I download the sbt-1.0.0-M4.msi from [https://dl.bintray.com/sbt/native-packages/sbt/1.0.0-M4/sbt-1.0.0-M4.msi] and installed it on my Window 7 system.
## problem

When I type "sbt ...." in an console window to execute the command, an error message occurs, which says sbt is not a inner command, i.e., the system cannot find the command.
## expectation

The system should know where to find the command since I installed it correctly without any fault.
## notes

I have found the command path set in my system environment is "....\sbt\\bin", but the correct one should be "....\sbt\bin", we only need just one "\" for the last path segment.

**Comment by dwijnand** [comment] 2016-08-22 12:12
Yep, this is duplicate of https://github.com/sbt/sbt-launcher-package/issues/76, which has a fix on the way.

**Closed as completed by dwijnand** 2016-08-22 12:12 UTC
Labels: Duplicate
