### ISSUE TITLE
Cannot see anything on screen when setting up the project

### ISSUE THREAD

**Issue by mikail-khan** [sbt/sbt#5281] opened 2019-12-10 08:50 UTC
When I invoke, 

```
sbt new playframework/play-scala-seed.g8
```

and I get prompted for entering the project name, organisation name etc, I don't see the characters I type on the screen. This used to work before but not now. It's might be due to my terminal setup rather than the plugin. Any help would be appreciated:

![image](https://user-images.githubusercontent.com/13503259/70466877-0b101a80-1abc-11ea-9f2f-53c5a33d6247.png)

This is the terminal I am using:

![image](https://user-images.githubusercontent.com/13503259/70513864-5bbe5c80-1b2a-11ea-9ecb-6670155c5308.png)

This is the only ENV variable I am setting:

export TERM="xterm-256color"

sbt version:

sbt version in this project: 1.3.3
sbt script version: 1.3.3

**Comment by eed3si9n** [comment] 2019-12-10 14:59
Thanks for the report. I think this is a duplicate of https://github.com/sbt/sbt/issues/5063

**Closed as completed by eed3si9n** 2019-12-10 14:59 UTC

**Comment by mikail-khan** [comment] 2019-12-10 15:12
Yeah I think it is. The workaround in #5063 works for me as well.

```scala
sbt --supershell=false new playframework/play-scala-seed.g8
```
