### ISSUE TITLE
windows error

### ISSUE THREAD

**Issue by jw-devops-n** [sbt/sbt#6791] opened 2022-01-17 08:35 UTC
## steps

 sbt data-redis-dump/docker:publishLocal
sbt: 1.6.1 
## problem

[success] All package validations passed
[error] java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///D:/Soft/Coursier/Cache/https/repo1.maven.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
[error]         at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
[error]         at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
[error]         at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
[error]         at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
[error]         at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
[error]         at java.nio.file.Paths.get(Paths.java:84)
[error]         at sbt.internal.inc.MappedVirtualFile$.toPath(MappedVirtualFile.scala:36)
[error]         at sbt.internal.inc.MappedFileConverter.toPath(MappedVirtualFile.scala:53)
[error]         at sbt.Sync$.$anonfun$convertFromVirtual$1(Sync.scala:175)
[error]         at sbt.internal.util.Relation$.$anonfun$switch$1(Relation.scala:58)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error]         at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:400)
[error]         at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
[error]         at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at sbt.internal.util.Relation$.switch(Relation.scala:56)
[error]         at sbt.Sync$.convertFromVirtual(Sync.scala:175)
[error]         at sbt.Sync$.readInfoWrapped(Sync.scala:168)
[error]         at sbt.Sync$.$anonfun$sync$1(Sync.scala:67)
[error]         at com.typesafe.sbt.packager.Stager$.stageFiles(Stager.scala:28)
[error]         at com.typesafe.sbt.packager.Stager$.stage(Stager.scala:42)
[error]         at com.typesafe.sbt.packager.docker.DockerPlugin$.$anonfun$projectSettings$56(DockerPlugin.scala:292)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (viid-data-redis-dump / Docker / stage) java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///D:/Soft/Coursier/Cache/https/repo1.maven.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
[error] Total time: 12 s, completed 2022-1-17 16:01:50
## expectation

success

**Comment by jw-devops-n** [comment] 2022-01-17 08:37
I tried 1.6.0 and got the same result

**Comment by jw-devops-n** [comment] 2022-01-17 08:37
1.5.8 is ok

**Comment by SethTisue** [comment] 2022-01-17 18:23
looks like a duplicate of #6774

**Comment by eed3si9n** [comment] 2022-01-17 21:34
Thanks Seth. I agree it's a duplicate.

**Closed as completed by eed3si9n** 2022-01-17 21:34 UTC

**Comment by OlegYch** [comment] 2022-02-03 15:34
@2690522020 clean seems to fix it
