### ISSUE TITLE
Using console more than once breaks JLine

### ISSUE THREAD

**Issue by tpolecat** [sbt/sbt#4109] opened 2018-04-20 17:32 UTC
## steps

Construct this minimal project, enter the console twice.

```
foo$ tree
.
├── build.sbt
└── project
    └── build.properties

1 directory, 2 files

foo$ cat build.sbt 
scalaVersion := "2.12.5"

foo$ cat project/build.properties 
sbt.version=1.1.4

foo$ sbt
[info] Loading global plugins from /Users/rnorris/.sbt/1.0/plugins
[info] Loading project definition from /private/tmp/foo/project
[info] Updating ProjectRef(uri("file:/private/tmp/foo/project/"), "foo-build")...
[info] Done updating.
[info] Loading settings from build.sbt ...
[info] Set current project to foo (in build file:/private/tmp/foo/)
[info] sbt server started at local:///Users/rnorris/.sbt/1.0/server/b2c7b08bb0a88ab6cd9f/sock
sbt:foo> console
[info] Updating ...
[info] Done updating.
[info] Starting scala interpreter...
Welcome to Scala 2.12.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_144).
Type in expressions for evaluation. Or try :help.

scala> 1
res0: Int = 1

scala> 
[success] Total time: 6 s, completed Apr 20, 2018 10:21:43 AM
sbt:foo> console
[info] Starting scala interpreter...
Welcome to Scala 2.12.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_144).
Type in expressions for evaluation. Or try :help.

scala> ^[[A // pressed up arrow
1 // pressed up arrow
res0: Int = 1

scala> ^D
[success] Total time: 7 s, completed Apr 20, 2018 10:21:52 AM
sbt:foo> [info] shutting down server
```

## problem

Console control keys don't work.

## expectation

They should!

## notes

sbt version: 1.1.4

I'm on a Mac using Terminal.app

Tested with the homebrew launcher and sbt-extras, same results.

**Comment by tpolecat** [comment] 2018-04-20 18:14
A workaround is

```scala
initialCommands := "jline.TerminalFactory.get.init"
```

As observed by @retronym [here](https://github.com/sbt/sbt/issues/3661#issuecomment-338897918).

**Comment by sarahgerweck** [comment] 2018-04-20 21:49
Thanks for workaround: also running into this.

**Comment by milessabin** [comment] 2018-04-21 12:16
I also see this on linux, konsole.

**Comment by xuwei-k** [comment] 2018-04-23 14:34
Maybe regression in <del> https://github.com/sbt/sbt/issues/4109 </del> #4082 

sbt 1.1.3 works

**Comment by eed3si9n** [comment] 2018-04-23 15:14
Thanks for the reproduction steps.
It seems like a duplicate of https://github.com/sbt/sbt/issues/3482, which I intended to fix in 1.1.4 with https://github.com/sbt/sbt/pull/4082, but apparently I managed to break it in cases where it wasn't previously broken.

**Comment by eed3si9n** [comment] 2018-04-23 15:17
I am going to close this to consolidate to #3482.

**Closed as completed by eed3si9n** 2018-04-23 15:17 UTC

**Comment by dwijnand** [comment] 2018-04-24 08:45
(Side note: instead of re-opening and re-targeting issues that were part of a release, new issues (like this one) should be used in my opinion. Issues are free and can link to prior discussions and older tickets in shipped releases.)

**Comment by eed3si9n** [comment] 2018-04-25 21:05
https://github.com/sbt/sbt/pull/4123
