### ISSUE TITLE
[1.3.0] Fail to start on AdoptOpenJDK JDK 12.0.2 2019-07-16

### ISSUE THREAD

**Issue by apflieger** [sbt/sbt#5011] opened 2019-08-30 14:57 UTC
## steps
sbt version: 1.3.0-RC5
macOS Mojave 10.14.6
```
java -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode)
```
## problem
SBT fails on startup : 

```
java.lang.UnsatisfiedLinkError: /private/var/folders/ph/_5v_199j02b3f30m8lxztk9m0000gn/T/jna-1919929507/jna7459118449433163038.tmp: dlopen(/private/var/folders/ph/_5v_199j02b3f30m8lxztk9m0000gn/T/jna-1919929507/jna7459118449433163038.tmp, 1): no suitable image found.  Did find:
	/private/var/folders/ph/_5v_199j02b3f30m8lxztk9m0000gn/T/jna-1919929507/jna7459118449433163038.tmp: code signature in (/private/var/folders/ph/_5v_199j02b3f30m8lxztk9m0000gn/T/jna-1919929507/jna7459118449433163038.tmp) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.base/java.lang.Runtime.load0(Runtime.java:765)
	at java.base/java.lang.System.load(System.java:1866)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at sbt.internal.io.MilliPosixBase.<init>(Milli.scala:87)
	at sbt.internal.io.PosixMilli.<init>(Milli.scala:103)
	at sbt.internal.io.PosixMilliLong.<init>(Milli.scala:116)
	at sbt.internal.io.MacMilli$.<init>(Milli.scala:240)
	at sbt.internal.io.MacMilli$.<clinit>(Milli.scala)
	at sbt.internal.io.Milli$.<init>(Milli.scala:354)
	at sbt.internal.io.Milli$.<clinit>(Milli.scala)
	at sbt.io.IO$.$anonfun$getModifiedTimeOrZero$1(IO.scala:1373)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at sbt.internal.io.Retry$.liftedTree2$1(Retry.scala:38)
	at sbt.internal.io.Retry$.impl$1(Retry.scala:38)
	at sbt.internal.io.Retry$.apply(Retry.scala:52)
	at sbt.internal.io.Retry$.apply(Retry.scala:24)
	at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1373)
	at sbt.internal.classpath.ClassLoaderCache$Key$$anonfun$$lessinit$greater$3.apply(ClassLoaderCache.scala:55)
	at sbt.internal.classpath.ClassLoaderCache$Key$$anonfun$$lessinit$greater$3.apply(ClassLoaderCache.scala:55)
	at scala.collection.immutable.List.map(List.scala:286)
	at sbt.internal.classpath.ClassLoaderCache$Key.<init>(ClassLoaderCache.scala:55)
	at sbt.internal.classpath.ClassLoaderCache.cachedCustomClassloader(ClassLoaderCache.scala:178)
	at sbt.State$StateOpsImpl$.initializeClassLoaderCache$extension(State.scala:358)
	at sbt.StandardMain$.initialState(Main.scala:179)
	at sbt.xMain$.run(Main.scala:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:46)
	at sbt.xMain.run(Main.scala:39)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
```

## notes

I don't understand the error. Does it come from the fast that sbt doesn't use scala 1.3.0 internally?

**Comment by eed3si9n** [comment] 2019-08-30 17:02
> java.lang.UnsatisfiedLinkError: /private/var/folders/ph/_5v_199j02b3f30m8lxztk9m0000gn/T/jna-1919929507/jna7459118449433163038.tmp: dlopen(/private/var/folders/ph/_5v_199j02b3f30m8lxztk9m0000gn/T/jna-1919929507/jna7459118449433163038.tmp, 1): no suitable image found.  Did find:
	/private/var/folders/ph/_5v_199j02b3f30m8lxztk9m0000gn/T/jna-1919929507/jna7459118449433163038.tmp: code signature in (/private/var/folders/ph/_5v_199j02b3f30m8lxztk9m0000gn/T/jna-1919929507/jna7459118449433163038.tmp) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

Could you try `-Dsbt.io.jdktimestamps=true` plz?

**Comment by eatkins** [comment] 2019-08-30 22:10
This looks like osx applying https://en.wikipedia.org/wiki/Gatekeeper_(macOS). I have never seen this before on my system. What version of sbt is installed on your system and how was it installed, e.g. homebrow?

**Comment by kevin-lee** [comment] 2019-08-31 01:53
I have the same problem but with sbt 1.2.8 and the latest Java 11 from AdoptOpenJDK. I didn't happen before I upgraded but I don't remember exactly which version I was using before.

macOS: `10.14.6`
sbt: `1.2.8`

```
$ java -version

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```

Error log:
```
[error] java.lang.UnsatisfiedLinkError: /private/var/folders/rw/t170r9s92tzd4y8s7_n2bgjr0000gn/T/jna-424296939/jna3457531304875252559.tmp: dlopen(/private/var/folders/rw/t170r9s92tzd4y8s7_n2bgjr0000gn/T/jna-424296939/jna3457531304875252559.tmp, 1): no suitable image found.  Did find:
[error]   /private/var/folders/rw/t170r9s92tzd4y8s7_n2bgjr0000gn/T/jna-424296939/jna3457531304875252559.tmp: code signature in (/private/var/folders/rw/t170r9s92tzd4y8s7_n2bgjr0000gn/T/jna-424296939/jna3457531304875252559.tmp) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
[error]   at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
[error]   at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
[error]   at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
[error]   at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
[error]   at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
[error]   at java.base/java.lang.Runtime.load0(Runtime.java:767)
[error]   at java.base/java.lang.System.load(System.java:1831)
[error]   at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
[error]   at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
[error]   at com.sun.jna.Native.<clinit>(Native.java:190)
[error]   at sbt.internal.io.MilliPosixBase.<init>(Milli.scala:91)
[error]   at sbt.internal.io.PosixMilli.<init>(Milli.scala:106)
[error]   at sbt.internal.io.PosixMilliLong.<init>(Milli.scala:119)
[error]   at sbt.internal.io.MacMilli$.<init>(Milli.scala:253)
[error]   at sbt.internal.io.MacMilli$.<clinit>(Milli.scala)
[error]   at sbt.internal.io.Milli$.<init>(Milli.scala:358)
[error]   at sbt.internal.io.Milli$.<clinit>(Milli.scala)
[error]   at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1329)
[error]   at sbt.librarymanagement.RichUpdateReport.$anonfun$recomputeStamps$1(RichUpdateReport.scala:22)
[error]   at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
[error]   at scala.collection.Iterator.foreach(Iterator.scala:937)
[error]   at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error]   at scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error]   at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]   at scala.collection.TraversableLike.map(TraversableLike.scala:233)
[error]   at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
[error]   at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error]   at sbt.librarymanagement.RichUpdateReport.recomputeStamps(RichUpdateReport.scala:15)
[error]   at sbt.internal.librarymanagement.IvyRetrieve$.updateReport(IvyRetrieve.scala:233)
[error]   at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:337)
[error]   at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error]   at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error]   at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]   at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]   at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]   at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]   at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]   at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]   at xsbt.boot.Using$.withResource(Using.scala:10)
[error]   at xsbt.boot.Using$.apply(Using.scala:9)
[error]   at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]   at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]   at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]   at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]   at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]   at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]   at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]   at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error]   at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error]   at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]   at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]   at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error]   at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error]   at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]   at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error]   at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]   at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error]   at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error]   at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]   at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error]   at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2561)
[error]   at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]   at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]   at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]   at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]   at sbt.Execute.work(Execute.scala:278)
[error]   at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]   at java.base/java.lang.Thread.run(Thread.java:834)
[error] (update) java.lang.UnsatisfiedLinkError: /private/var/folders/rw/t170r9s92tzd4y8s7_n2bgjr0000gn/T/jna-424296939/jna3457531304875252559.tmp: dlopen(/private/var/folders/rw/t170r9s92tzd4y8s7_n2bgjr0000gn/T/jna-424296939/jna3457531304875252559.tmp, 1): no suitable image found.  Did find:
[error]   /private/var/folders/rw/t170r9s92tzd4y8s7_n2bgjr0000gn/T/jna-424296939/jna3457531304875252559.tmp: code signature in (/private/var/folders/rw/t170r9s92tzd4y8s7_n2bgjr0000gn/T/jna-424296939/jna3457531304875252559.tmp) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```

**Comment by kevin-lee** [comment] 2019-08-31 01:55
>
> Could you try `-Dsbt.io.jdktimestamps=true` plz?

@eed3si9n Thanks Eugene, I tried and I can now use sbt with the following extra non-error log.

```
Exception in thread "sbt-socket-server" java.lang.UnsatisfiedLinkError: /private/var/folders/rw/t170r9s92tzd4y8s7_n2bgjr0000gn/T/jna-424296939/jna7576157866496668457.tmp: dlopen(/private/var/folders/rw/t170r9s92tzd4y8s7_n2bgjr0000gn/T/jna-424296939/jna7576157866496668457.tmp, 1): no suitable image found.  Did find:
  /private/var/folders/rw/t170r9s92tzd4y8s7_n2bgjr0000gn/T/jna-424296939/jna7576157866496668457.tmp: code signature in (/private/var/folders/rw/t170r9s92tzd4y8s7_n2bgjr0000gn/T/jna-424296939/jna7576157866496668457.tmp) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
  at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
  at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
  at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
  at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
  at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
  at java.base/java.lang.Runtime.load0(Runtime.java:767)
  at java.base/java.lang.System.load(System.java:1831)
  at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
  at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
  at com.sun.jna.Native.<clinit>(Native.java:190)
  at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
  at com.sun.jna.Structure.<clinit>(Structure.java:2130)
  at sbt.internal.server.Server$$anon$2$$anon$1.$anonfun$run$1(Server.scala:65)
  at scala.util.Try$.apply(Try.scala:209)
  at sbt.internal.server.Server$$anon$2$$anon$1.run(Server.scala:60)
[warn] sbt server could not start in 10
```

**Comment by eatkins** [comment] 2019-08-31 02:06
@Kevin-Lee I have the same question about how sbt was installed on your system. This looks like a security error. I cannot reproduce on my 10.14.6 system so I'm trying to figure out what is different about your setup.

**Comment by kevin-lee** [comment] 2019-08-31 02:26
@eatkins sbt? using homebrew but I did not just install it. I've been using the same version of sbt for several months.

It started happening after I had upgraded my Java (AdoptOpenJDK11) to the latest. 
If I switch Java from 11 to 8, it works.

Are you using the same version of Java as mine?
```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```

Both sbt and AdoptOpenJDK were installed using homebrew.

**Comment by eatkins** [comment] 2019-08-31 02:32
Yes, I use https://github.com/shyiko/jabba for cross jdk testing. This seems more like an issue with jna and jdk11. The only thing I can think is that maybe there is something about where your jdk is installed that is triggering the extra security checks. With jabba, it's installed in my home directory which is completely unprotected.

**Comment by kevin-lee** [comment] 2019-08-31 03:01
@eatkins Ah...got it. Let me try a non-brew version. 

Thank you! 👍

**Comment by kevin-lee** [comment] 2019-08-31 03:11
@eatkins I downloaded AdoptOpenJDK11 package from the official AdoptOpenJDK website and installed it. It works without the issue. 
So I think this is an issue to be reported to `homebrew-openjdk`.

**Comment by apflieger** [comment] 2019-08-31 07:58
I use `sbt-launch.jar` to install and run sbt.
My AdoptOpenJDK was installed using homebrew.

**Comment by apflieger** [comment] 2019-09-01 16:42
I installed the JDK with the AdotOpenJDK installer but the installation path is the same by default. I still get the error. 
I tried to let Gatekeeper run the jdk but it didn't work. I'm not sure how to do that. I finally tried a `sudo spctl --master-disable` but the error is still there

**Comment by apflieger** [comment] 2019-09-02 09:13
Alright, I installed OpenJDK instead, from there http://jdk.java.net/12/. This one works.

```
java -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)
```

**Comment by eed3si9n** [comment] 2019-09-02 17:56
Since code formatting is hiding this, I am going to use quote markdown to highlight the key part of the error message:

> java.lang.UnsatisfiedLinkError: /private/var/folders/ph/_5v_199j02b3f30m8lxztk9m0000gn/T/jna-1919929507/jna7459118449433163038.tmp: dlopen(/private/var/folders/ph/_5v_199j02b3f30m8lxztk9m0000gn/T/jna-1919929507/jna7459118449433163038.tmp, 1): no suitable image found.  Did find:
	/private/var/folders/ph/_5v_199j02b3f30m8lxztk9m0000gn/T/jna-1919929507/jna7459118449433163038.tmp: code signature in (/private/var/folders/ph/_5v_199j02b3f30m8lxztk9m0000gn/T/jna-1919929507/jna7459118449433163038.tmp) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

**Comment by eed3si9n** [comment] 2019-09-02 18:31
Looks like this is a known issue on AdoptOpenJDK (https://github.com/AdoptOpenJDK/openjdk-build/issues/1211 / https://github.com/AdoptOpenJDK/openjdk-build/issues/1206) specific to some variant of 2019-07-16 releases (11.0.4+? and 12.0.2+?). The issues are now marked as *fixed*, but I am not sure what the resolution steps are since AdoptOpenJDK could be installed in a various fashion.

The simplest likely would be to download directly from https://adoptopenjdk.net/ and use 11.0.4+11.4. Neither Jabba nor SDKMAN tracks the build metadata of 11.0.4.

**Comment by eed3si9n** [comment] 2019-09-02 18:32
In any case, I am closing this since it doesn't look like an sbt specific issue that we can take actions on.

**Closed as completed by eed3si9n** 2019-09-02 18:32 UTC
Labels: area/jdk_x

**Comment by jodom961** [comment] 2020-10-29 15:05
going to project structure --> selecting java 1.8 for SDK and project language level fixed it for me 

super strange, unrelated error though.
