### ISSUE TITLE
Large number of open files while running all tests in Akka project

### ISSUE THREAD

**Issue by bantonsson** [sbt/sbt#937] opened 2013-10-25 12:55 UTC
Hi,

I made a snapshot using lsof somewhere past the halfway mark during the Akka testsuite and this is what I found.
- 1862 open files
- 440 of them are jar files (that's our fault) :wink: 
- 598 of them with test output `.../out`
- 762 of them are `.../export` files
- The rest are some `.so` files and pipes

An example of the 17 `.../export` files for akka-actor:

```
akka-actor/target/streams/compile/dependencyClasspath/$global/export
akka-actor/target/streams/compile/exportedProducts/$global/export
akka-actor/target/streams/compile/externalDependencyClasspath/$global/export
akka-actor/target/streams/compile/internalDependencyClasspath/$global/export
akka-actor/target/streams/compile/managedClasspath/$global/export
akka-actor/target/streams/compile/unmanagedClasspath/$global/export
akka-actor/target/streams/compile/unmanagedJars/$global/export
akka-actor/target/streams/runtime/exportedProducts/$global/export
akka-actor/target/streams/runtime/unmanagedJars/$global/export
akka-actor/target/streams/test/dependencyClasspath/$global/export
akka-actor/target/streams/test/exportedProducts/$global/export
akka-actor/target/streams/test/externalDependencyClasspath/$global/export
akka-actor/target/streams/test/fullClasspath/$global/export
akka-actor/target/streams/test/internalDependencyClasspath/$global/export
akka-actor/target/streams/test/managedClasspath/$global/export
akka-actor/target/streams/test/unmanagedClasspath/$global/export
akka-actor/target/streams/test/unmanagedJars/$global/export
```

**Comment by retronym** [comment] 2013-11-03 23:12
@harrah  mentioned:

> so, as a workaround, I think you can do `testListeners in (Test,test) := Nil` .  That should disable writing the output to files.

**Comment by jroper** [comment] 2013-11-04 02:09
On Play, we fork most of our tests, but right now with SBT 0.13, SBT is hanging.  Here are the open files at the point that SBT is hanging:
- Total: 1328
- Jar files: 504 (of which 184 are sbt related)
- Export files: 497
- Out files: 295

SBT hangs because server.accept() call made in ForkTest.scala is throwing an exception, which is caused by this JDK bug:

https://bugs.openjdk.java.net/browse/JDK-8021820

And SBT is making no attempt to handle such errors.

So the real bug here for Play is the JDK bug, but I think it will be easier to get a fix into SBT to limit the number of open files than to get a release of JDK7 that fixes this.  So this issue is currently blocking the Play main build from upgrading to SBT 0.13, which is in turn blocking testing Play with JDK 8 since upgrading the Play build to SBT 0.13 is a prerequisite to that.

**Comment by jroper** [comment] 2013-11-04 02:20
We can work around this by building Play with JDK 6.  This work around won't last though because we want to build with JDK7 - you get pretty javadocs that way.

**Comment by retronym** [comment] 2013-11-04 07:53
Looks like the fix will be in the next JDK7 release, too: https://bugs.openjdk.java.net/browse/JDK-8023403

**Comment by bantonsson** [comment] 2013-11-04 08:00
@retronym So the `testListeners in (Test,test) := Nil` workaround effectively silence all test output. Maybe not a real workaround.

**Comment by bantonsson** [comment] 2013-11-04 08:32
So doing this instead seems to do the trick `testListeners in (Test, test) := Seq(TestLogger(streams.value.log, {_ => streams.value.log }, logBuffered.value))`

**Comment by harrah** [comment] 2013-11-04 19:27
These workarounds are a little risky but I think they should be ok.  They should reduce the contribution to total open files from the test-logging and export categories.  A full fix is a lot more work; hopefully this will suffice for a while.

**Comment by bantonsson** [comment] 2013-11-04 20:26
Thanks @harrah. The close `export` code is almost identical to the code I have locally, minus the cleanup. At least I'm not barking up the wrong tree.

**Comment by jroper** [comment] 2013-11-07 03:58
I've tested this with play, it solves the problem for us (at least until our build gets bigger and we exceed 1024 open files again...)

**Comment by jsuereth** [comment] 2014-04-17 01:26
Pushed to 0.13.6 as this most likely requires two fixes:
1. The GC fix should help clean classloader open files that hang around and help this out
2. We need to rework our logging system to limit the # of open files at any given time.  In fact, it'd be ideal if "taskstreams" closes the stream of a given task when the task is completed, or has some eviction strategy.

**Comment by jsuereth** [comment] 2014-07-18 13:27
So, we pushed back the logging fixes one more release, but I think we have a plan now.  Moving this to 0.13.7

**Comment by bloo** [comment] 2014-11-25 22:21
@jsuereth looks like this was removed from the 0.13.7 milestone - what should I expect re: a fix for this?

**Comment by bloo** [comment] 2014-11-25 23:11
:point_up: that answers that - thanks @eed3si9n

**Comment by eed3si9n** [comment] 2014-12-14 14:01
The part we can fix in shorter time is #1223.

**Comment by huntc** [comment] 2015-09-10 03:58
@eed3si9n FYI, we're experiencing this with 0.13.9:

> We need to rework our logging system to limit the # of open files at any given time. In fact, it'd be ideal if "taskstreams" closes the stream of a given task when the task is completed, or has some eviction strategy.

We see the issue manifest itself when using the sbt-native-packager where there are a lot of files to archive. We workaround the issue by removing some tasks, but it is an ugly hack.

**Comment by fchaillou** [comment] 2016-07-12 16:57
@eed3si9n I'm also expericing it with 0.13.11.
running `sbt test` hangs once in a while on my machine or jenkins in a large multi module project.

Any workaround for now ?
Thanks.

**Comment by eed3si9n** [comment] 2016-07-12 17:09
Workaround for now would be bump up the open file limits on the OS, and reduce the parallelism during testing or fork the tests - http://www.scala-sbt.org/0.13/docs/Parallel-Execution.html

**Comment by JohnPendlebury** [comment] 2017-12-08 14:51
Was there any further developments with this issue. I see it happening intermittently with sbt and sbt-native-packager. Versions don't appear to be relevant.

**Comment by eed3si9n** [comment] 2019-10-03 04:27
I am closing this due to inactivity, but if this is still relevant let us know.

**Closed as completed by eed3si9n** 2019-10-03 04:27 UTC
Labels: area/logging
