### ISSUE TITLE
sbt 1.0.3 not longer watches test classpath

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt#3687] opened 2017-10-28 19:27 UTC
## problem

macOS (have not tried other os)

with sbt `1.0.2` when using `~test:compile` and modifying a test the test is recompiled (same with `~testOnly xxx`)

with sbt `1.0.3` when using `~test:compile` and modifying a test nothing happens (does recompile when changing code in src/main)

could be related to the changes in #3527?

**Comment by francisdb** [comment] 2017-10-29 18:42
hmm, I seem to also see this for some non-test files.

**Comment by francisdb** [comment] 2017-10-30 08:40
@dwijnand let me know if you have a hard time reproducing this, then I can try to come up with a test project

**Comment by dwestheide** [comment] 2017-10-30 12:46
+1 – I am on macOS, and it seems that neither test sources nor main sources are watched, or at least, no triggered task execution is happening any more in SBT 1.0.3.

**Comment by ScalaWilliam** [comment] 2017-11-03 00:45
I had this problem on Linux too.

**Comment by ScalaWilliam** [comment] 2017-11-03 00:47
For me ~testQuick didn't work on Linux sometimes - changing a compile classpath source would not trigger any change.

**Comment by dwijnand** [comment] 2017-11-17 17:58
The upstream issue is https://github.com/sbt/io/issues/82.

**Comment by OlegYch** [comment] 2017-11-17 18:03
@dwijnand on windows and linux `PollingWatchService` is not really relevant..

**Comment by dwijnand** [comment] 2017-11-20 14:38
@OlegYch Yeah, there are multiple issues going on at once. But I think the regression tracked here has to do with the solution (shipping as of 1.0.3) being `PollingWatchService`-based, which is also broken..

**Comment by francisdb** [comment] 2017-11-29 08:24
I think this can be closed as it's a duplicate of #3695?

**Comment by dwijnand** [comment] 2017-11-29 08:42
The use cases are slightly different. Last I tried I couldn't reproduce #3695, but I could this one. Which, btw, I'm going to investigate more today, with the info in #3775 / sbt/io#86.

**Comment by francisdb** [comment] 2017-11-29 08:49
Ah, great to see you are getting tot he root cause of this 👍

**Comment by dwijnand** [comment] 2017-11-29 13:59
Real upstream is https://github.com/sbt/io/issues/86.

**Comment by OlegYch** [comment] 2017-12-01 13:19
modifications to files in dependent projects are also ignored, even if executing the command directly in that project like `~derp/compile`
btw it would be nice to add proper toString to classes like sbt.io.SimpleFileFilter and sbt.internal.io.Source, or all sbt classes for that matter, and make their properties public (or make them case classes?), otherwise inspecting much of sbt keys (watchSources in this case) is an exercise in frustration

**Comment by dwijnand** [comment] 2017-12-01 13:49
> btw it would be nice to add proper toString to classes like sbt.io.SimpleFileFilter and sbt.internal.io.Source, or all sbt classes for that matter, and make their properties public (or make them case classes?), otherwise inspecting much of sbt keys (watchSources in this case) is an exercise in frustration

Done: https://github.com/sbt/io/pull/77

**Comment by OlegYch** [comment] 2017-12-13 15:37
@eed3si9n does this fix the issue on windows (which afaik doesn't use pollingwatchservice) ?

**Comment by dwijnand** [comment] 2017-12-13 15:54
@OlegYch No, that must be another issue. One which I'm not sure has already been reported.

Also, the fix was merged in sbt/io's 1.0.x branch, which I just merged into the 1.1.x branch (https://github.com/sbt/io/pull/99), so that it can be in sbt 1.1.0-RC2. Re-opening so we know to re-release sbt/io for 1.1.0-RC2.

**Comment by eed3si9n** [comment] 2017-12-16 22:54
New io with the fix was merged in #3816

**Closed as completed by eed3si9n** 2017-12-16 22:54 UTC
Labels: Regression, Merged Upstream
