### ISSUE TITLE
-opt:l:inline breaks incremental compilation

### ISSUE THREAD

**Issue by eparejatobes** [sbt/sbt#4125] opened 2018-04-26 15:21 UTC
Given

``` scala
@inline def x = 2

// somewhere else
def z = x + 1 
```

changes in `x` above after a successful compilation will not propagate to `z`; if we make `def x = 3` then we will have `z == 3`, not `4`.

I'm aware of the [2.12 Release Notes](https://www.scala-lang.org/news/2.12.0/) stating that

> We recommend enabling inlining only in production builds, as sbt’s incremental compilation does not track dependencies introduced by inlining.

but IMHO mentioning it upfront doesn't make it less of a bug: either incremental compilation works correctly when inlining is enabled (which it should), or we are given a way of disabling it (as it was already asked for in #1282).

**Comment by dwijnand** [comment] 2018-04-26 16:00
Duplicate of https://github.com/sbt/zinc/issues/227?

Alternatively could you provide, please, a minimal-but-complete reproduction? For instance sbt version, scala version, scala options, the test, etc. Following our [ISSUE_TEMPLATE](https://github.com/sbt/sbt/blob/1.x/ISSUE_TEMPLATE.md), ideally 😀.

**Comment by eparejatobes** [comment] 2018-04-26 19:09
> Duplicate of sbt/zinc#227?

That one looks a particular side-effect of "does not track dependencies introduced by inlining" related with singleton types and final vals being always inlined by the type checker. This is something wider: you simply cannot trust the incremental compiler *at all* when using the 2.12 optimizer.

> Alternatively could you provide, please, a minimal-but-complete reproduction? (...)

There you go, not just that but a dedicated repo: 

- https://github.com/ohnosequences/sbt4125/blob/c3169097b485e742a721af4a58150ee9c8329dbb/README.md

**Comment by eparejatobes** [comment] 2018-05-02 11:42
*Copying here the relevant portion of the link above; see [ohnosequences/sbt4125](https://github.com/ohnosequences/sbt4125) for more*

## steps

Open a shell and 

``` bash
git checkout "x=1"
```

Now run `sbt` on a different shell and do `~test`. Once it runs for the first time,

``` bash
git checkout "x=2"
```

Take a look at the test passing, and the definitions of `x` and `y`.

## Problem

Incremental compilation when used together with the optimizer generates incorrect bytecode: modifications in methods/vals are not propagated to wherever they are being inlined.

## Expectation

The incremental compiler should not *ever* generate incorrect bytecode.

## Version

sbt `1.1.0` most likely previous ones too.

**Comment by eed3si9n** [comment] 2018-05-02 13:45
@eparejatobes Thanks for the report and reproduction.

**Comment by eed3si9n** [comment] 2018-05-02 13:55
I wasn't able to follow the instruction exactly:

```
$ git checkout "x=1"
error: pathspec 'x=1' did not match any file(s) known to git.
```

but I got the gist of what's going on from manually changing:

```scala
  @inline
  def x: Int = 1
```

to

```scala
  @inline
  def x: Int = 2
```

**Comment by eparejatobes** [comment] 2018-05-02 14:13
> I wasn't able to follow the instruction exactly: (...)

My fault, forgot to push the tags; it should work now.

> but I got the gist of what's going on (...)

yes, that's it. I can understand that fixing this would involve considerable work in zinc; I think then that there should be a way (however hackish) of disabling incremental compilation. Note that (as this example shows) I could perfectly publish bytecode wildly different from what the source should generate.

**Comment by eed3si9n** [comment] 2018-05-02 14:19
It can't be too difficult to invalidate everything whenever the flag is present, and show a warning saying "oh snap. you have inline flag on. we can't handle this."

**Comment by eed3si9n** [comment] 2018-05-02 14:31
I've reported also to https://github.com/sbt/zinc/issues/537

**Comment by hodga** [comment] 2018-05-15 12:33
im trying this one

**Closed as completed** 2023-12-18 22:57 UTC
Labels: area/incremental_compiler, help wanted, Blocked on Upstream
