### ISSUE TITLE
Display error message regarding Scala 2.12.4 not working with Zinc

### ISSUE THREAD

**Issue by jackkoenig** [sbt/sbt#6838] opened 2022-03-15 20:36 UTC
## steps

I have reproduced the bug with both sbt 1.6.2 and 1.6.0, but no problem with sbt 1.5.8.

To reproduce, just take any SBT project using SBT 1.6 and try to compile with Scala 2.12.4, eg.

```
sbt new scala/scala-seed.g8
# cd into directory and change Scala version to 2.12.4
sbt compile
```

Note that the issue does not show up with Scala versions 2.12.2, 2.12.3, nor 2.12.5.

## problem

You will see a stack trace like the following:
```
[error] java.lang.StackOverflowError
[error] scala.reflect.macros.Attachments.matchesTag(Attachments.scala:38)
[error] scala.reflect.macros.Attachments.$anonfun$get$1(Attachments.scala:42)
[error] scala.reflect.macros.Attachments.$anonfun$get$1$adapted(Attachments.scala:42)
[error] scala.collection.immutable.Set$Set1.find(Set.scala:104)
[error] scala.reflect.macros.Attachments.get(Attachments.scala:42)
[error] xsbt.Compat$OriginalTreeTraverser$Reflective$.traverseOriginal(Compat.scala:48)
[error] xsbt.Compat.processOriginalTreeAttachment(Compat.scala:25)
[error] xsbt.ExtractUsedNames$ExtractUsedNamesTraverser.handleClassicTreeNode(ExtractUsedNames.scala:294)
[error] xsbt.ExtractUsedNames$ExtractUsedNamesTraverser.traverse(ExtractUsedNames.scala:170)
[error] xsbt.ExtractUsedNames$ExtractUsedNamesTraverser.$anonfun$handleClassicTreeNode$3(ExtractUsedNames.scala:294)
[error] xsbt.ExtractUsedNames$ExtractUsedNamesTraverser.$anonfun$handleClassicTreeNode$3$adapted(ExtractUsedNames.scala:294)
[error] xsbt.Compat$OriginalTreeTraverser$Reflective$.traverseOriginal(Compat.scala:49)
[error] xsbt.Compat.processOriginalTreeAttachment(Compat.scala:25)
... repeating
```

## expectation

I would expect SBT to work, or if it doesn't support compiling with certain versions of Scala, it would be helpful if that were called out and a specific error message were given.

I understand this is an old version of Scala, I'm only hitting this in cross compiling a compiler plugin, but it would be ideal if this were fixed.

**Comment by SethTisue** [comment] 2022-03-15 20:51
duplicate of https://github.com/sbt/zinc/issues/1010

**Comment by eed3si9n** [comment] 2022-03-15 20:53
I think this is a known issue in Scalac https://github.com/sbt/zinc/issues/1010

Per @dwijnand in https://github.com/sbt/zinc/issues/1010#issuecomment-993388899:

> Here's my hypothesis: OriginalTreeAttachment was added in 2.12.3, something was changed in 2.12.4 which introduced some cycle, which was either removed or guarded against in 2.12.5+ as well as 2.13+. 2.12.4 is Oct 2017 and 2.12.5 is Mar 2018, so this seems pretty low priority to me. But apologies for introducing the bug!

In other words, we were aware of Scala 2.12.4 and Zinc not working together, so I pushed it out to 1.6.x and since it seems to not happen in the latest 2.12.x series, we don't plan to make any fixes in either Zinc or Scala 2.x. Displaying an error message might be a good idea.

**Comment by jackkoenig** [comment] 2022-03-16 16:55
Thanks for the information!

**Comment by eed3si9n** [comment] 2024-10-07 16:27
Closing this in favor of https://github.com/sbt/zinc/issues/1010

**Closed as not planned by eed3si9n** 2024-10-07 16:27 UTC
Labels: good first issue
