### ISSUE TITLE
On Windows, Coursier creates "./null/Coursier/cache/v1" directories as cache

### ISSUE THREAD

**Issue by FireFoxAhri** [sbt/sbt#5206] opened 2019-10-20 06:41 UTC
See also https://github.com/coursier/coursier/issues/1438

## steps
sbt version: 1.3.3

1. Use Windows.
2. Download the AdoptOpenJDK 8 232-b09 zip file (https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u232-b09/OpenJDK8U-jdk_x86-32_windows_hotspot_8u232b09.zip)
3. Launch sbt as follows:

```
sbt --java-home /cygdrive/c/Users/foo/Downloads/OpenJDK8U-jdk_x86-32_windows_hotspot_8u232b09/jdk8u232-b09/
```

## problem
Coursier location was wrongly set to the project location, with a null folder, not in the %LOCALAPPDATA%\Coursier\Cache\v1.

My system is newly reinstalled win10 1909. I think maybe it's the new windows10 issue & sbt didn't get the right %LOCALAPPDATA%.

![批注 2019-10-20 141902](https://user-images.githubusercontent.com/14964489/67155624-6ee05780-f345-11e9-939d-d9f16d8da7ae.png)

Both tested in the IDEA and PowerShell with downloaded sbt 1.3.3.

## expectation
Coursier located in %LOCALAPPDATA%\Coursier\Cache\v1

## notes
By setting the COURSIER_CACHE enviroment varible, the Coursier location works correctly.

**Comment by eed3si9n** [comment] 2019-10-21 14:48
@FireFoxAhri Thanks for the report!

**Comment by djneades** [comment] 2019-10-21 21:08
I am also seeing this problem with Sbt 1.3.3 under Windows 20H1 Insider Preview build 19002.1002.

**Comment by frozenspider** [comment] 2019-10-23 02:30
Just got it with sbt 1.3.3, Win8.1 and IDEA 2019.2.3

**Comment by OlegYch** [comment] 2019-11-01 14:53
this seems like a long standing problem, same behaviour with 1.1.4 and 1.2.8 launchers

**Comment by OlegYch** [comment] 2019-11-01 14:55
oh actually it doesn't depend on launcher version, just sbt version

**Comment by shyan1** [comment] 2019-11-09 02:23
I just follow the [sbt-1.3-Release-Notes](https://www.scala-sbt.org/1.x/docs/sbt-1.3-Release-Notes.html), and add the following code in `build.sbt` file to disable the Coursier and go back to Apache Ivy for library management
```
ThisBuild / useCoursier := false
```

Right now I found the 'null' folder very annoying.

**Comment by OlegYch** [comment] 2019-12-02 14:27
same with 1.3.4

**Comment by UkonnRa** [comment] 2019-12-03 12:23
same with Windows 10 and sbt 1.3.4. And it seems that it will download all dependecies twice and just ignore the original ones in `C:\Users\<user>\AppData\Local\Coursier`

**Comment by enesterenko** [comment] 2019-12-27 11:52
This issue persists in sbt 1.3.6, Windows 10

**Comment by almothafar** [comment] 2020-01-02 14:52
I got no issues at all with version 1.3.4 until 1.3.6 in macOS, but I'm getting it now when I switched back to Windows 10.

**Comment by eed3si9n** [comment] 2020-01-02 15:38
Could someone figure out if this is an sbt issue, IntelliJ issue, or Coursier issue?
In other words, does this happen without involving IntelliJ or without involving sbt?

**Comment by OlegYch** [comment] 2020-01-02 16:00
this certainly is not related to intellij, but seems to depend on java version:
"c:\Program Files\Java\jre1.8.0_231\bin\java.exe" -jar d:\Distrib\Coding\Java\scala\sbt\bin\sbt-launch.jar creates a 'null' folder
D:\Distrib\Coding\Java\jdk\jdk1.8.0_181x64\bin\java.exe -jar d:\Distrib\Coding\Java\scala\sbt\bin\sbt-launch.jar does not
perhaps it's running with jre vs jdk?

**Comment by OlegYch** [comment] 2020-01-02 16:10
d:\Distrib\Coding\Java\jdk\jdk1.8.0_231x64\bin\java.exe  -jar d:\Distrib\Coding\Java\scala\sbt\bin\sbt-launch.jar also creates a 'null' folder, so it looks like something has changed in minor java version
same with latest adoptopenjdk 8.0.232.09-hotspot

**Comment by OlegYch** [comment] 2020-01-02 16:39
even with ThisBuild / useCoursier := false in build and metabuild the null folder is created, although it remains empty

**Comment by almothafar** [comment] 2020-01-02 16:55
@eed3si9n  I think it is sbt or Coursier issue, I reported the issue was thinking it might be IntelliJ at first here https://youtrack.jetbrains.com/issue/SCL-16814 

But I tried today to launch sbt console outside the IDE in the terminal and the issue is happening, I ran `sbt clean update compile` and the folder got generated.

So I think it is sbt, also, I tried to use older version like sbt 1.2.6 and no issues with that inside IntelliJ.

**Comment by eed3si9n** [comment] 2020-01-02 17:00
If setting `COURSIER_CACHE` environement variable works around this it has to be something in Coursier code here https://github.com/coursier/coursier/blob/1cd0240823b2aeab63458116d0743af71f4062b8/modules/paths/src/main/java/coursier/paths/CoursierPaths.java. This also makes 

```scala
coursierDirectories0 = ProjectDirectories.from(null, null, "Coursier")
```

which calls out to https://github.com/soc/directories-jvm/blob/master/src/main/java/io/github/soc/directories/ProjectDirectories.java, which has Windows specific code like

```scala
      case WIN:
        String[] winDirs = getWinDirs("3EB685DB-65F9-4CF6-A03A-E3EF65729F3D", "F1B32785-6FBA-4FCF-9D55-7B8E7F157091");
        String appDataRoaming = winDirs[0] + '\\' + path;
        String appDataLocal   = winDirs[1] + '\\' + path;
        dataDir      = appDataRoaming + "\\data";
        dataLocalDir = appDataLocal   + "\\data";
        configDir    = appDataRoaming + "\\config";
        cacheDir     = appDataLocal   + "\\cache";
        break;
```

/cc @alexarchambault

**Comment by OlegYch** [comment] 2020-01-02 17:07
on a related note, i've seen someone claiming sbt hangs in that code trying to execute a powershell command (!)
i wonder if it would be better to just revert to using .coursier on windows @alexarchambault ?

**Comment by eed3si9n** [comment] 2020-01-02 17:46
I reported it upstream https://github.com/soc/directories-jvm/issues/26.

**Comment by eed3si9n** [comment] 2020-01-02 17:50
@OlegYch Here's the powershell command - https://github.com/soc/directories-jvm/blob/8849872b9b71a378e6356f69bcf58427cb681e2f/src/main/java/io/github/soc/directories/Util.java#L113-L145

**Comment by KeithGrant** [comment] 2020-01-05 16:48
This behavior started when I switched from Java 1.8.0_112 to 1.8.0_231. It stopped when I switched back to  1.8.0_112

**Comment by dwijnand** [comment] 2020-01-06 08:06
Fixed in upstream Coursier v2.0.0-RC5-5.

**Comment by dwijnand** [comment] 2020-01-06 08:07
(Oh, maybe "Merged Upstream" is the wrong label, reading the label description?  Leaving it for now.)

**Comment by almothafar** [comment] 2020-02-04 14:06
Just an update, since version 1.3.7 I got no issues, so I think this is solved?

**Comment by eed3si9n** [comment] 2020-02-04 14:18
Yes this has been fixed.

**Comment by aalubin** [comment] 2020-04-25 13:50
This still happens with 1.3.10

**Comment by OlegYch** [comment] 2020-04-25 13:54
@aalubin probably caused by outdated scalafix or scalafmt version

**Comment by liebichw** [comment] 2020-07-28 21:07
I can also reproduce it with SBT 1.3.13 (launcher and the version used in the project). OS is Windows 10, Java version is OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)

**Comment by almothafar** [comment] 2020-07-29 11:08
> I can also reproduce it with SBT 1.3.13 (launcher and the version used in the project). OS is Windows 10, Java version is OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)

There should be something wrong the issue is 100% gone since 1.3.8 (but with other issues), and I have no issues at all starting from 1.3.13.
If you use IntelliJ (they are using an older version) see my comment here: https://github.com/sbt/sbt/issues/5501#issuecomment-662996791

**Comment by liebichw** [comment] 2020-08-05 09:14
This issue also appears when starting SBT from the (Windows 10) command line.
It seems to be related to the SBT launcher - what is put into this directory are the downloads for SBT itself.
So maybe the launcher has a bug?
I recently upgraded to the SBT launcher 1.3.13. As I got problems with IDEA project file upgrades when I disabled coursier, I had to enable it - and the above problem shows up.

When I define the environment variables
`COURSIER_HOME=C:/Users/<Username>/AppData/Local/Coursier`
and
`C:/Users/<Username>/AppData/Local/Coursier/Cache/v1`
(forward slahses are really needed here), the problem seems to disappear - except for the SBT shell in idea, which just does not work at all then.

**Comment by VIKCT001** [comment] 2020-09-15 10:30
which path we need to set for COURSIER_HOME environment variable.
C:/Users/<Username>/AppData/Local/Coursier or C:/Users/<Username>/AppData/Local/Coursier/Cache/v1 ?

Also how do we get rid of null folder which is already created in project? can we delete that. Please suggest

**Comment by FireFoxAhri** [comment] 2020-12-30 01:39
It looks like this problem appears again in sbt 1.4.6. Both latest Oracle JDK 8 & 11 tested error. sbt 1.4.5 works fine. 
![QQ截图20201230093823](https://user-images.githubusercontent.com/14964489/103324519-c79b9c00-4a82-11eb-8c9f-da3f32d54e1a.png)

**Comment by alexarchambault** [comment] 2020-12-30 01:42
I didn't check on my Windows machine, but that might be because of https://github.com/dirs-dev/directories-jvm/pull/46 (which stops rejecting some `null`s).

**Comment by alexarchambault** [comment] 2021-01-04 10:18
FYI, I tried sbt 1.4.6 on a Windows machine, and got no `null` directories. It seemed to work fine.

**Comment by FireFoxAhri** [comment] 2021-01-04 10:22
> FYI, I tried sbt 1.4.6 on a Windows machine, and got no `null` directories. It seemed to work fine.

Did you use IDEA? I'm using IDEA and get null directories.

**Comment by alexarchambault** [comment] 2021-01-04 13:32
> Did you use IDEA? I'm using IDEA and get null directories.

@FireFoxAhri Can you reproduce it from the console? Like wipe `null`, run `sbt clean update`, and see if the `null` directory is back.

**Comment by FireFoxAhri** [comment] 2021-01-04 13:51
> > Did you use IDEA? I'm using IDEA and get null directories.
> 
> @FireFoxAhri Can you reproduce it from the console? Like wipe `null`, run `sbt clean update`, and see if the `null` directory is back.

I've tried IDEA sbt shell console  and null is back. PowerShell too.  @alexarchambault 
![QQ截图20210104214933](https://user-images.githubusercontent.com/14964489/103541738-d052fe80-4ed6-11eb-9601-b0cb75f9538f.png)

**Comment by philwalk** [comment] 2021-01-19 16:12
fwiw:  I was having this problem until I did the following:

```
mv null /tmp # remove null directory
touch null      # prevent it from being re-created
export COURSIER_CACHE COURSIER_HOME
```
Not sure which if any of these actions mattered, but I'm now past the problem.
command line sbt version: 1.4.5
project sbt version: 1.3.3

**Comment by ngtrio** [comment] 2021-01-21 03:43
windows 10:
1.4.5 -> fine
1.4.6 -> reproduced

**Comment by snlykf** [comment] 2021-02-01 13:44
Encountered this when upgrading to 1.4.7. Reverting back to 1.4.5 works.

**Comment by grindvoll** [comment] 2021-02-04 09:27
I just checked this with 1.4.7 on Windows 10 on a simple SBT project. The Coursier cache is placed in a local `null` folder. Reverting to 1.4.5 works fine.

**Comment by amicuwehkamp** [comment] 2021-02-08 07:21
The release notes for sbt 1.4.6 mention an update to Coursier 2.0.8, with changes that affect the cache directory in Windows: https://github.com/sbt/sbt/releases/tag/v1.4.6

**Comment by andrei-micu** [comment] 2021-02-08 07:29
The release notes for sbt 1.4.6 mention an update to Coursier 2.0.8, with changes that affect the cache directory in Windows: https://github.com/sbt/sbt/releases/tag/v1.4.6

**Comment by snlykf** [comment] 2021-02-08 15:38
Seems to be an issue with PowerShell: https://github.com/dirs-dev/directories-jvm/issues/47

**Comment by soc** [comment] 2021-03-21 02:59
@FireFoxAhri Could you retest after SBT releases a new version that includes the updated directories code?

**Comment by FireFoxAhri** [comment] 2021-03-21 03:05
> @FireFoxAhri Could you retest after SBT releases a new version that includes the updated directories code?

Of course. I'm waiting the new version.

**Comment by ScalaWilliam** [comment] 2021-03-21 14:22
It is still happening to me, even in 1.5.0-RC1.

**Comment by eed3si9n** [comment] 2021-03-22 00:56
I have a PR for this to short-circuit Couriser and use `LOCALAPPDATA` environment variable instead - https://github.com/sbt/sbt/pull/6408

**Closed as completed** 2021-03-22 03:59 UTC
Labels: area/windows

**Comment by astiob** [comment] 2022-06-20 22:57
I still got a `null` directory on Windows 11 (64-bit), in PowerShell, using Oracle’s Java 18.0.1.1, sbt launcher 1.6.2 installed via Coursier 2.1.0-M6-26 as recommended [on Scala’s website](https://www.scala-lang.org/download/), sbt 1.6.2 in project.

However, this happened only on the very first launch of sbt. The timestamps on the `null` directory and its subdirectories match the creation of `~/.sbt` and its contents. I ran sbt in two projects, but only the first one ended up containing `null`, and when I quit sbt, deleted the `null` directory and relaunched sbt, it kept working and did _not_ recreate the directory or redownload anything. For full disclosure, I did create `~/.sbt/repositories` (listing `maven-local`, `maven-central` and some custom repos but not `local`) after I first launched sbt and before I first launched it in the other project; but removing the `repositories` file and relaunching sbt still doesn’t recreate `null`.

Before I deleted it, the `null/Coursier/cache/v1/https/repo1.maven.org/maven2` directory contained:

```
com/eed3si9n
com/github
com/google
com/jcraft
com/lmax
com/squareup
com/swoval
com/typesafe
io/get-coursier
net/java
net/openhft
org/apache
org/checkerframework
org/fusesource
org/jline
org/reactivestreams
org/scala-lang
org/scala-sbt
org/slf4j
org/sonatype
```

**Comment by eed3si9n** [comment] 2022-06-21 05:03
@astiob As of https://github.com/sbt/sbt/pull/6408, sbt no longer uses the cache directory created by directories-jvm or Coursier. My guess is that if you had installed using the installer available from https://github.com/sbt/sbt/releases/tag/v1.6.2 or used [Chocolatey](https://chocolatey.org/install) to install sbt, `null/Coursier/cache/v1/` wouldn't have been created.

**Comment by joekrie** [comment] 2023-12-04 20:52
I just had a null folder created in the project's root while running sbt build with these versions:
coursier: 2.1.8
sbt: 1.6.1
jdk: Eclipse Adoptium Java 17.0.8.1

I resolved it by setting the environment variable COURSIER_CACHE to %LOCALAPPDATA%\Coursier\Cache\v1 (which according to https://github.com/coursier/coursier/blob/v2.1.8/doc/docs/cache.md?plain=1#L31 should be the default on Windows)
