### ISSUE TITLE
Misleading warnings for locked outdated dependency

### ISSUE THREAD

**Issue by martinring** [sbt/sbt#1015] opened 2013-11-29 09:14 UTC
when for some reason an outdated dependency is still locked and thus sbt fails to delete the artifact from the cache, it correctly displays an error message: 

```
[error] couldn't delete outdated artifact from cache: ...
```

but then follows a misleading warning, which frequently caused me to check the dependencies not knowing what the problem is:

```
[warn] module not found: ...
[warn] === repo1: tried
[warn]   http://...
[warn] === repo2: tried
[warn]   http://...
[warn] === repo3: tried
[warn]   http://...
[warn] === repo4: tried
[warn]   http://...
[warn]  :::::::::::::::::::::::::::::::::::::
[warn]  ::      UNRESOLVED DEPENDENCY      ::
[warn]  :::::::::::::::::::::::::::::::::::::
[warn]  :: name.of.the.group#artifact.id;version: not found
[warn]  :::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies ...
[warn]      <name of dependency>
[warn]
sbt.ResolveException: unresolved dependency ...
  <STACKTRACE>
   ...
```

The displayed warning message emphasizes the fact, that the dependency could not be found (which is not true), this and the fact, that on most screens the warning + stacktrace will fill the entire terminal makes it very easy to overlook the one-line error  message which states the actual problem.

I would suggest to suppress the entire warning message.

**Comment by eed3si9n** [comment] 2014-04-05 20:52
In general I agree we should produce better error message, but since we might have found the root cause of the problem (#1223), I'm going to close this case.

**Closed as completed by eed3si9n** 2014-04-05 20:52 UTC
Labels: Wontfix
