### ISSUE TITLE
Alot of OkHttp warnings after upgrading to 1.7.2

### ISSUE THREAD

**Issue by larochef** [sbt/sbt#7051] opened 2022-10-14 14:00 UTC
## steps

After upgrading to sbt 1.7.2, I have alot of the following logs that appear a few minutes after downloading dependencies:

```
WARNING: A connection to https://repo1.maven.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Oct 14, 2022 3:52:10 PM okhttp3.internal.platform.Platform log
```
I also see the same warnings with the URL of my nexus.

Sbt is still runnig at that point and continues working normally.

While this isn't blocking, it is still confusing to see these.

**Comment by eed3si9n** [comment] 2022-10-14 19:27
Thanks for the report. Could you provide reproduction steps so we can reproduce your problem on _our computers_? Do you use any plugins?

One thing to note about sbt 1.7.x is that it no longer depends on OkHttp since I've switched to using shaded Apache HTTP Async Client:

```
cs resolve -t org.scala-sbt:sbt:1.7.2
....
         ├─ org.scala-sbt:librarymanagement-core_2.12:1.7.1
         │  ├─ com.eed3si9n:gigahorse-apache-http_2.12:0.7.0
         │  │  ├─ com.eed3si9n:gigahorse-core_2.12:0.7.0
         │  │  │  ├─ com.typesafe:ssl-config-core_2.12:0.6.1
         │  │  │  │  ├─ com.typesafe:config:1.4.2
         │  │  │  │  └─ org.scala-lang:scala-library:2.12.15 -> 2.12.16
         │  │  │  ├─ org.reactivestreams:reactive-streams:1.0.3
         │  │  │  ├─ org.scala-lang:scala-library:2.12.15 -> 2.12.16
         │  │  │  └─ org.slf4j:slf4j-api:1.7.28
         │  │  ├─ com.eed3si9n:shaded-apache-httpasyncclient:0.7.0
         │  │  └─ org.scala-lang:scala-library:2.12.15 -> 2.12.16
```

**Comment by larochef** [comment] 2022-10-25 07:52
Ok, I will give a try at finding what configuration gives that. So far, on simple projects I don't see these.

**Comment by eed3si9n** [comment] 2022-10-29 07:24
Closing this for now.

**Closed as completed by eed3si9n** 2022-10-29 07:24 UTC
Labels: needs info
