### ISSUE TITLE
sbt crash during startup when using sbt-coursier plugin 

### ISSUE THREAD

**Issue by ayoub-benali** [sbt/sbt#5144] opened 2019-10-02 15:18 UTC
## steps
After upgrading from `1.2.8` to `1.3.2` sbt started crashing when `sbt-coursier` is enabled in project.

I have been using `"io.get-coursier" % "sbt-coursier" % "2.0.0-RC2-1"` but even upgrading to `v2.0.0-RC3-6` didn't help.
I suspect the issue is related to the introduction of coursier in sbt for library management in `1.3.X`

## problem
```
[error] java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
[error]         at coursier.sbtcoursier.ResolutionTasks$.$anonfun$resolutionsTask$3(ResolutionTasks.scala:42)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:289)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (coursierResolutions) java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;

```

## expectation
SBT should work fine with `sbt-coursier`

**Comment by eed3si9n** [comment] 2019-10-02 17:33
@ayoub-benali Thanks for the report! I think this is a duplicate of https://github.com/sbt/sbt/issues/5040. Feel free to add comments on that one to add more details.

**Closed as completed by eed3si9n** 2019-10-02 17:33 UTC
Labels: area/library_management
