### ISSUE TITLE
Test interface not on the classpath when using scalaHome

### ISSUE THREAD

**Issue by szeiger** [sbt/sbt#2748] opened 2016-09-19 14:25 UTC
When using a locally built Scala distribution via `scalaHome`, any attempt to run a test fails with `java.lang.ClassNotFoundException: org.scalatools.testing.Framework`. I was able to confirm this with sbt 0.13.7 and 0.13.12, using the `build/pack` output from ant in Scala 2.12.0-M5 and from sbt in Scala 2.12.0-RC1. Tests can be run when Scala is resolved in the usual way from a Maven repository.

This was originally filed as https://github.com/scala/scala-dev/issues/223 but seems to be an sbt problem rather than one with the new build. The assumptions from that ticket appear to be wrong though. The problem is not caused by building the Scala distribution with sbt or the lack of a `partest.properties` file. Even when building M5 with ant and manually launching partest to generate `partest.properties` I can still reproduce the problem.

**Comment by milessabin** [comment] 2016-09-19 14:55
Hmm ... I _was_ fairly confident that I had run tests successfully quite recently and that persuaded me it must be a regression in the Scala SBT build.

**Comment by dwijnand** [comment] 2016-09-19 14:59
This is because of insourcing ScalaCheck: https://github.com/scala/scala/pull/5244#issuecomment-233861230

And @milessabin has proposed a workaround in https://github.com/sbt/sbt/pull/2678

Quoting myself:

> Personally I would prefer this to be fixed in scala/scala. But (I think) I understand the situation, so I can be convinced to accept this.

My reasons are`scala-partest-extras.jar` shouldn't include scalacheck and I would prefer to not add another workaround in sbt, especially given that, as far as I understand, the insourcing of scalacheck is temporarily (tm).

Also not that if the workaround is accepted into sbt 0.13 (and then forward ported to 1.0), then it needs a release, and then you must upgrade the project(s) that you want to use `scalaHome` in.

**Comment by szeiger** [comment] 2016-09-19 15:03
How does ScalaCheck's presence alone cause this failure? Does sbt eagerly load all class files from partest-extras?

**Comment by milessabin** [comment] 2016-09-19 15:54
Blimey! I'd completely forgotten about that!

**Comment by szeiger** [comment] 2016-09-20 21:11
To expand my previous question: Why does sbt load _anything_ from partest-extras at all? The JAR is not part of library, compiler or reflect, and I can't think of any reason why sbt would care abouts its existence.

Furthermore: If a ClassNotFoundException gets thrown while sbt analyzes the JAR (for whatever reason), wouldn't it make more sense to log it as a warning and then continue?

**Comment by eed3si9n** [comment] 2016-09-20 21:19
Yes. Perhaps sbt overlearned from the scala-reflect split-up, but currently it treats every JAR files in Scala home as something useful unless it's mentioned in the blacklist: 
https://github.com/sbt/sbt/blob/0.13/util/classpath/src/main/scala/sbt/ScalaInstance.scala#L110

**Comment by eed3si9n** [comment] 2016-09-20 21:35
See #661:

> The whitelist in ScalaInstance needs to become a blacklist. Methods that provide the scala-library and scala-compiler jars need to be deprecated. Although they can return a sequence of files, this information is not available from a Scala home directory without hardcoding in sbt.

sbt/sbt@5b5577a1878dcdbce36f84514c3ea6c0d04389bb

**Comment by szeiger** [comment] 2016-09-21 12:27
Maybe we shouldn't put partest-extras into `pack` in the first place. It's there because ant put it there and it's needed for partest, so it kind of makes sense, but there shouldn't be any technical reason for it in the sbt build. We can reference it wherever it is located.

**Comment by eed3si9n** [comment] 2016-09-21 12:30
Another idea might be to reverse the course of #661 and white list again assuming Scala team won't modularize Scala compiler JARs at least for a while.

**Comment by SethTisue** [comment] 2016-09-21 18:06
> We can reference it wherever it is located

+1

**Comment by milessabin** [comment] 2016-09-22 07:41
Is there a consensus on the right way to fix this now? It'd be good to get a fix into an SBT release to help with testing prior to 2.12.0-RC2.

**Comment by szeiger** [comment] 2016-09-22 10:44
@milessabin There's a simple workaround: Delete `scala-partest-extras.jar` before using `build/pack` as a `scalaHome` in sbt.

I'll look into how difficult it would be to move this file to a better location without too many changes to the sbt build.

**Comment by milessabin** [comment] 2016-09-22 11:00
@szeiger that works in the very short term, but it seems we have several simple SBT-side fixes ... we just need to pick one :-)

**Comment by szeiger** [comment] 2016-09-22 11:05
@milessabin Moving the file out of build/pack will fix the problem permanently without requiring a new sbt version.

**Comment by milessabin** [comment] 2016-09-22 11:07
Fair enough ... so the consensus is to change the scala build rather than sbt?

**Comment by szeiger** [comment] 2016-09-22 11:11
There's still some room for improvement in sbt (like not failing catastrophically when such an exception occurs) but changing it in the Scala build looks like the simplest way to make it work again.

**Comment by dwijnand** [comment] 2016-09-27 22:08
Fixed in scala/scala https://github.com/scala/scala/pull/5414

**Closed as completed by dwijnand** 2016-09-27 22:08 UTC
