### ISSUE TITLE
Command parsing error reporting regression

### ISSUE THREAD

**Issue by jroper** [sbt/sbt#5442] opened 2020-02-18 01:43 UTC
If I create a new sbt project, just with a `build.properties` setting `sbt.version` to `1.3.8`, without creating a `build.sbt` file, and then I try to run an task or command in a sub project that doesn't exist, I get the following error:

```
sbt:sbt-test> s/compile
[error] Expected ';'
[error] s/compile
[error]          ^
```

Well, that doesn't describe what the error is, but let's indulge sbt briefly, and see if adding the expected semicolon in the expected location helps:

```
sbt:sbt-test> s/compile;
[error] Expected ';'
[error] s/compile
[error]          ^
```

Nope. I don't know when this regression was injected, but here's what happens when you do the same thing on sbt 1.0.2:

```
sbt:sbt-less> s/compile
[error] Expected ID character
[error] Not a valid command: s
[error] Expected 'show'
[error] Expected project ID
[error] Expected configuration
[error] Expected ':' (if selecting a configuration)
[error] Expected key
[error] Not a valid key: s
[error] s/compile
[error]  ^
```

Now at least it describes the error correctly (though it's still not a good user experience).

**Comment by eed3si9n** [comment] 2020-02-18 02:23
Thanks for the report. I think this is a duplicate of https://github.com/sbt/sbt/issues/5039.

**Closed as completed by eed3si9n** 2020-02-18 02:23 UTC
