### ISSUE TITLE
maven resolver plugin pulls excluded transitive dependencies

### ISSUE THREAD

**Issue by chasebradford** [sbt/sbt#2109] opened 2015-07-15 21:56 UTC
chase:lib1:1.0-SNAPSHOT

```
<dependencies>
</dependencies>
```

chase:lib2:1.0-SNAPSHOT:

```
<dependencies>
  <dependency>
    <groupId>chase</groupId>
    <artifactId>lib1</artifactId>
    <version>1.0-SNAPSHOT</version>
  </dependency>
</dependencies>
```

top:

```
<dependencies>
  <dependency>
    <groupId>chase</groupId>
    <artifactId>lib2</artifactId>
    <version>1.0-SNAPSHOT</version>
    <exclusions>
      <exclusion>
        <groupId>chase</groupId>
        <artifactId>lib1</artifactId>
      </exclusion>
    </exclusions>
  </dependency>
</dependencies>
```

My test SBT project depends on top.

```
// build.sbt
resolvers += "Local Maven Repository" at "file://" + Path.userHome.absolutePath + "/.m2/repository"

libraryDependencies += "chase" % "top" % "1.0-SNAPSHOT"
```

lib1 still resolves when I run `sbt update`, even though it's a transitive dependency and should be excluded.  I hacked the SbtArtifactDescriptorReader in the sbt-maven-resolver to `System.err.println(dependency.getArtifactId() + " EXCLUDES " + exclusion.getArtifactId());` and I can see that the exclusion rule is detected while processing top's dependencies.  For some reason it still shows up in the full dependency tree:

```
#[Jul 15 14:44:30][~/TestProject]
> sbt dependencyTree
[info] Loading project definition from /Users/cbradford/TestProject/project
[info] Set current project to testproject (in build file:/Users/cbradford/TestProject/)
[info] Updating {file:/Users/cbradford/TestProject/}testproject...
[info] Resolving chase#top;1.0-SNAPSHOT ...
lib2 EXCLUDES lib1
[info] Resolving chase#lib2;1.0-SNAPSHOT ...
[info] Resolving chase#lib1;1.0-SNAPSHOT ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] default:testproject_2.10:0.1-SNAPSHOT [S]
[info]   +-chase:top:1.0-SNAPSHOT
[info]     +-chase:lib2:1.0-SNAPSHOT
[info]       +-chase:lib1:1.0-SNAPSHOT
```

**Comment by chasebradford** [comment] 2015-07-15 22:15
A similar maven app that depends on only `chase:top:1.0-SNAPSHOT` has this tree, which is correct.

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ app ---
[INFO] chase:app:jar:1.0-SNAPSHOT
[INFO] +- chase:top:jar:1.0-SNAPSHOT:compile
[INFO] |  \- chase:lib2:jar:1.0-SNAPSHOT:compile
[INFO] \- junit:junit:jar:3.8.1:test
```

**Comment by jsuereth** [comment] 2015-07-21 20:47
Thanks for the report.  Looks like we're not filling something out in Ivy correctly....

**Comment by chasebradford** [comment] 2015-07-21 21:18
I didn't follow up on this after I kept digging.  I'm pretty sure this is the cause:
https://github.com/sbt/sbt/blob/0.13/sbt-maven-resolver/src/main/scala/sbt/mavenint/MavenRepositoryResolver.scala#L175

**Comment by jsuereth** [comment] 2015-07-22 01:17
Ha, good catch.  I need to learn to finish all my TODOs.

**Comment by jsuereth** [comment] 2015-07-22 01:44
Ok, think I have this fixed.  You wouldn't happen to have a reproducible test project?  I just need your full pom.xml file I can dump into an offline repository and check to make sure we aren't resolving the excluded transitives.

**Comment by chasebradford** [comment] 2015-07-22 02:48
I don't want to make a PR just to pass the data over, so I'm inlining it.  mvn install should work on all of these and the app, which depends on top, shouldn't depend on bottom.

Directories:

```
./app
./app/build.sbt
./app/pom.xml
./app/src
./app/src/main
./app/src/main/java
./bottom
./bottom/pom.xml
./bottom/src
./bottom/src/main
./bottom/src/main/java
./middle
./middle/pom.xml
./middle/src
./middle/src/main
./middle/src/main/java
./top
./top/pom.xml
./top/src
./top/src/main
./top/src/main/java
```

pom files

```
==> app/pom.xml <==
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>exclude.test</groupId>
  <artifactId>app</artifactId>
  <packaging>jar</packaging>
  <version>1.0.0</version>
  <name>app</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
      <groupId>exclude.test</groupId>
      <artifactId>top</artifactId>
      <version>1.0.0</version>
    </dependency>
  </dependencies>
</project>

==> bottom/pom.xml <==
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>exclude.test</groupId>
  <artifactId>bottom</artifactId>
  <packaging>jar</packaging>
  <version>1.0.0</version>
  <name>bottom</name>
  <url>http://maven.apache.org</url>
  <dependencies>
  </dependencies>
</project>

==> middle/pom.xml <==
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>exclude.test</groupId>
  <artifactId>middle</artifactId>
  <packaging>jar</packaging>
  <version>1.0.0</version>
  <name>middle</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
      <groupId>exclude.test</groupId>
      <artifactId>bottom</artifactId>
      <version>1.0.0</version>
    </dependency>
  </dependencies>
</project>

==> top/pom.xml <==
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>exclude.test</groupId>
  <artifactId>top</artifactId>
  <packaging>jar</packaging>
  <version>1.0.0</version>
  <name>top</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
      <groupId>exclude.test</groupId>
      <artifactId>middle</artifactId>
      <version>1.0.0</version>
      <exclusions>
        <exclusion>
          <groupId>exclude.test</groupId>
          <artifactId>middle</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
  </dependencies>
</project>
```

**Comment by jsuereth** [comment] 2015-07-23 20:06
OK< so I found out this is actually a fundamental issue in Ivy.  I've fixed the first-level exclusion for the aether plugin, but the transitive exclusion is failing for our Ivy tests AND the maven plugin....

**Comment by jsuereth** [comment] 2015-07-24 13:49
Ok, FYI, I founda bug in your maven poms.  You have TOP depending on middle AND excluding middle.  For some strange reason, Ivy allows this, but does not issue any warnings.  That was causing test failures and I thought indicative of a larger bug.  It appears though, that this is just a mechanism we should not support.   Transitives are now working correctly :)

**Comment by chasebradford** [comment] 2015-07-24 14:56
heh, whoops.  Sorry about that.  It was supposed to depend on middle and exclude bottom.

**Closed as completed** 2015-07-24 17:23 UTC
Labels: area/library_management, area/maven_integration
