### ISSUE TITLE
Multi-line prompts no longer work since 0.13.10

### ISSUE THREAD

**Issue by thirstycrow** [sbt/sbt#2636] opened 2016-06-07 03:26 UTC
A newline in the middle of the shell prompt does not work as expected, and it breaks the console color. For example:

```
> set shellPrompt := { state => Seq(scala.Console.BOLD, "myproject", scala.Console.RESET, "\n> ").mkString }
```

produces the following prompt:

```
^[[1mmyproject^[[0m^J>
```

A preceeding newline does not break console color, but still not work correctly:

```
> set shellPrompt := { state => Seq("\n", scala.Console.BOLD, "myproject", scala.Console.RESET, "> ").mkString }
^Jmyproject>
```

**Comment by eed3si9n** [comment] 2016-06-07 03:32
This is a duplicate of #2480, which has been fixed on 0.13, but hasn't been released.
Could you try a nightly build: `0.13.12-20160526-062513` and see if it works for you?

**Comment by thirstycrow** [comment] 2016-06-07 04:03
Thanks @eed3si9n , the nightly build works fine.

**Comment by eed3si9n** [comment] 2016-06-07 04:29
Awesome. Closing this issue then.

**Closed as completed by eed3si9n** 2016-06-07 04:29 UTC
Labels: Duplicate
