### ISSUE TITLE
Source file .history does not exist

### ISSUE THREAD

**Issue by Fristi** [sbt/sbt#2406] opened 2016-01-21 08:31 UTC
While running `sbt clean` I am getting this;

```
java.lang.IllegalArgumentException: requirement failed: Source file '<sbt-project>/.history' does not exist.
    at scala.Predef$.require(Predef.scala:233)
    at sbt.IO$.copyFile(IO.scala:583)
    at sbt.IO$.move(IO.scala:786)
    at sbt.IO$$anonfun$move$1.apply(IO.scala:772)
    at sbt.IO$$anonfun$move$1.apply(IO.scala:772)
    at scala.Function$$anonfun$tupled$1.apply(Function.scala:77)
    at scala.Function$$anonfun$tupled$1.apply(Function.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at sbt.IO$.move(IO.scala:772)
    at sbt.Defaults$$anonfun$doClean$1.apply(Defaults.scala:713)
    at sbt.Defaults$$anonfun$doClean$1.apply(Defaults.scala:710)
    at sbt.IO$.withTemporaryDirectory(IO.scala:291)
    at sbt.Defaults$.doClean(Defaults.scala:710)
    at sbt.Defaults$$anonfun$projectTasks$3.apply(Defaults.scala:301)
    at sbt.Defaults$$anonfun$projectTasks$3.apply(Defaults.scala:301)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

What could be causing this? 
- Using SBT 0.13.9
- Multi-module project
- sbt-coverage 1.3.5 is the only plugin

Root build.sbt

``` scala
scalaVersion in ThisBuild := "2.11.7"

akkaVersion in ThisBuild := "2.3.12"

specs2Version in ThisBuild := "2.4.17"

kamonVersion in ThisBuild := "0.5.1"

libraryDependencies in ThisBuild <++= (scalaVersion, specs2Version) { (scala_version, specs2_version) => Seq(
  "com.github.nscala-time"    %% "nscala-time"    % "1.8.0",
  "org.specs2"                %% "specs2"         % specs2_version % "test",
  "org.specs2"                %% "specs2-mock"    % specs2_version % "test"
  )
}

publishTo in ThisBuild := {
  if (isSnapshot.value)
    Some("Artifactory Realm" at "...")
  else
    Some("Artifactory Realm" at "...")
}

credentials in ThisBuild += Credentials(Path.userHome/".ivy2"/".credentials")

aggregate in update := false

scalacOptions in ThisBuild  := Seq("-encoding", "utf8",
  "-target:jvm-1.8",
  "-feature",
  "-language:implicitConversions",
  "-language:postfixOps",
  "-unchecked",
  "-deprecation",
  "-Xlog-reflective-calls"
)

updateOptions := updateOptions.value.withCachedResolution(true)

fork in ThisBuild := true
```

Each submodule has a build.sbt which describes it name and it's dependencies.

We have a BuildModules.scala which describes the modules and how they depend on each other;

``` scala
import sbt.Keys._
import sbt._

object BuildModules extends Build {
  val akkaVersion = SettingKey[String]("akkaVersion", "Akka version")
  val specs2Version = SettingKey[String]("specs2Version", "Specs2 version")
  val kamonVersion = SettingKey[String]("kamonVersion", "kamon version")

  def compAndTest(p: Project) = p % "test->test;compile->compile"

  def onlyTest(p: Project) = p % "test->test"

  lazy val root: Project = Project("root", file("."))
          .settings(
            publishLocal := {},
            publish := {}
          )
          .aggregate(
            projectA, projectB
          )

  lazy val projectA: Project = Project("projectA", file("projectA"), delegates = root :: Nil)

  lazy val projectB: Project = Project("projectB", file("projectB"), delegates = root :: Nil)
          .dependsOn(compAndTest(projectA))
}

```

**Comment by dwijnand** [comment] 2016-01-21 09:07
A race condition on the filesystem. The files to cleanup were evaluated at one point, but by the time it got to deleting them they were gone.

**Comment by Fristi** [comment] 2016-01-21 09:51
Any resolution for this problem? Or will this be fixed in a release?

**Comment by dwijnand** [comment] 2016-01-21 10:04
Any ideas what might also be deleting the file? Is it always `target/.history`?

**Comment by dwijnand** [comment] 2016-01-21 10:04
And no, there are no recent fixes for this issue.

**Comment by Fristi** [comment] 2016-01-21 13:06
I have no clue what might be deleting the `target/.history` file. I've found a similiar issue while googleing;

https://github.com/ucb-bar/chisel/issues/47

Adding; `parallelExecution in Global := false` in the root `build.sbt` seems to solve the issue

**Comment by dwijnand** [comment] 2016-01-21 13:43
I see. Possible duplicate of #1673 then.

**Comment by Fristi** [comment] 2016-01-21 21:10
Okido, thank you!

**Closed as completed** 2019-08-15 08:11 UTC
