### ISSUE TITLE
"No Scala version specified" in 0.13.5

### ISSUE THREAD

**Issue by austinsalonen** [sbt/sbt#1403] opened 2014-06-10 22:49 UTC
This might be an extension of #1388 

We go through an in-house Artifactory instance and everything must go through it (no exceptions, even for debugging).

We installed 0.13.5 on a Windows box and with custom repositories and .credential files, everything worked fine.

When we tried to run 0.13.5 on a Windows box with cygwin, we got the "No Scala version" error.  The ~/.sbt/boot directory looked like this: 

```
other  
sbt.boot.lock  
update.log.
```

When we downgraded to 0.13.0, everything worked.  ~/.sbt/boot looks like this:

```
scala-2.10.2
sbt.boot.lock
update.log
```

The process was similar with a RHL installation -- 0.13.5 did not work while 0.13.0 worked just fine with the same ~/.sbt/boot layouts.

The repositories file looks like this (scrubbed):

```
[repositories]
 local
 maven-proxy: http://local.url/artifactory/remote-repos/
 my-ivy-proxy-releases: http://local.url/artifactory/ivy-remote-repo/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```

Something that _might_ be related is that 0.13.5 on Linux/cygwin will not use the credentials specified (file or hard-coded).

**Comment by eed3si9n** [comment] 2014-06-11 10:41
For developers to work on this, we need a reliable way of reproducing this locally (or remotely).

> When we tried to run 0.13.5 on a Windows box with cygwin, we got the "No Scala version" error. 

I'd like to see more context around this when and where it's failing. Could you post the full log of what you see when you run `sbt --debug` to gist?

**Comment by austinsalonen** [comment] 2014-06-11 14:23
It fails pretty quick.

```
[user@host bin]$ sbt -debug
[process_args] java_version = '1.7.0_09-icedtea'
# Executing command line:
java
-Xms1024m
-Xmx1024m
-XX:ReservedCodeCacheSize=128m
-XX:MaxPermSize=256m
-jar
/scrubbed/bin/sbt-launch.jar

Error during sbt execution: No Scala version specified or detected
```

**Comment by ms-tg** [comment] 2014-07-11 17:29
Isn't this the same as #1117?

**Comment by jsuereth** [comment] 2014-08-08 16:32
Closing as duplicate of #1117

**Closed as completed by jsuereth** 2014-08-08 16:32 UTC
Labels: needs info
