### ISSUE TITLE
Dependency with classifier overrides the same dependency without (apparently)

### ISSUE THREAD

**Issue by lalloni** [sbt/sbt#345] opened 2012-01-26 23:25 UTC
Case 1:

```
libraryDependencies ++= Seq("org.neo4j.app" % "neo4j-server" % "1.6")
```

Gets me neo4j-server-1.6.jar.

Case 2:

```
libraryDependencies ++= Seq("org.neo4j.app" % "neo4j-server" % "1.6",  "org.neo4j.app" % "neo4j-server" % "1.6" classifier "static-web")
```

Just gets me neo4j-server-1.6-static-web.jar in my classpath. I want both, though. Is this the expected behavior?

Case 3 (workaround):

```
libraryDependencies ++= Seq( "org.neo4j.app" % "neo4j-server" % "1.6",  "org.neo4j.app" % "neo4j-server" % "1.6" classifier "" classifier "static-web")
```

Gets me both jars! :D

Just leaving the second module also works as I need.

**Comment by harrah** [comment] 2012-02-08 14:52
duplicate of #285

**Closed as completed by harrah** 2012-02-08 14:52 UTC
Labels: Duplicate

**Comment by lalloni** [comment] 2012-02-09 20:24
I'm not sure this is a duplicate of #285

The thing here is that for getting both jars (with & without a classifier) you have to put an empty string classifier:

```
libraryDependencies += "org.neo4j.app" % "neo4j-server" % "1.6" classifier "" classifier "static-web"
```

Is that the intended way of doing this?
