### ISSUE TITLE
Sbt plugins need native magikz used on run/test

### ISSUE THREAD

**Issue by jsuereth** [sbt/sbt#748] opened 2013-05-01 17:44 UTC
When running play in sbt and modifying the build:

```
jsuereth@jsuereth-work-i7:~/projects/snap/snap/dist/target/stage/play-test$ sbt
[info] Loading global plugins from /home/jsuereth/.sbt/plugins
[info] Updating {file:/home/jsuereth/.sbt/plugins/}default-d3d37a...
[info] Resolving org.scala-sbt#precompiled-2_10_1;0.12.3 ...
[info] Done updating.
[info] Loading project definition from /home/jsuereth/projects/snap/snap/dist/target/stage/play-test/project
[info] Set current project to reactive-stocks (in build file:/home/jsuereth/projects/snap/snap/dist/target/stage/play-test/)
[reactive-stocks] $ run

[info] Updating {file:/home/jsuereth/projects/snap/snap/dist/target/stage/play-test/}reactive-stocks...
[info] Done updating.                                                        
--- (Running the application from SBT, auto-reloading is enabled) ---

[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)
```

Now we hit CTRL-D, muck with the build (change the name setting), and then reload:

```
[reactive-stocks] $ reload
[info] Loading global plugins from /home/jsuereth/.sbt/plugins
[info] Loading project definition from /home/jsuereth/projects/snap/snap/dist/target/stage/play-test/project
[info] Set current project to reactive-stocks2 (in build file:/home/jsuereth/projects/snap/snap/dist/target/stage/play-test/)
[reactive-stocks2] $ run

[info] Updating {file:/home/jsuereth/projects/snap/snap/dist/target/stage/play-test/}reactive-stocks2...
[info] Done updating.                                                        

Cannot load the JNotify native library (Native Library /home/jsuereth/projects/snap/snap/dist/target/stage/play-test/target/native_libraries/64bits/libjnotify.so already loaded in another classloader)
Play will check file changes for each request, so expect degraded reloading performace.

--- (Running the application from SBT, auto-reloading is enabled) ---

[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)
```

Not sure you see, but the magical SO loading of JNotify (and most native-bindings in java) will fail after reload

```
Cannot load the JNotify native library (Native Library /home/jsuereth/projects/snap/snap/dist/target/stage/play-test/target/native_libraries/64bits/libjnotify.so already loaded in another classloader)
Play will check file changes for each request, so expect degraded reloading performace.
```

SO - it would be ideal if sbt plugins supported uses native bindings after reload.

**Comment by opyate** [comment] 2014-02-19 10:37
I've had this same issue whilst using an app based off http://typesafe.com/activator/template/play-yeoman

**Comment by dwijnand** [comment] 2015-08-03 19:10
The JNotify issue with Play seems to have gone, or at least I've not seen it recently or heard of it, but I guess the issue on paper.

I tried with play-yeoman, but it complained about grunt or Gruntfile or something, of which I know nothing.

Would be great to have a reproducible case for this.

**Comment by jkleckner** [comment] 2016-09-19 23:38
I just started hitting something like this right after upgrading my Mac to version 10.11.6.
Building has ground to a halt as dependencies seem to be validating each time and I see the jnotify error when leaving run mode.  sbtVersion 0.13.8 (also with 0.13.12) playVersion 2.3.9

```
$ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
```

Has anyone else started seeing this after applying the security update?
Here is a partial traceback with hitting control-D after the run prompt:

```
$ sbt -Dsbt.log.format=false 
[info] Loading global plugins from /Users/jim/.sbt/0.13/plugins
[info] Loading project definition from /Users/jim/dev/edison/project
[info] Set current project to edison (in build file:/Users/jim/dev/edison/)
[edison] $ run

[warn] Error loading JNotify watch service: no jnotify in java.library.path
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/jim/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/jim/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
--- (Running the application, auto-reloading is enabled) ---

[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)


java.lang.UnsatisfiedLinkError: no jnotify in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
        at java.lang.Runtime.loadLibrary0(Runtime.java:849)
        at java.lang.System.loadLibrary(System.java:1088)
        at net.contentobjects.jnotify.macosx.JNotify_macosx.<clinit>(Unknown Source)
        at net.contentobjects.jnotify.macosx.JNotifyAdapterMacOSX.<init>(Unknown Source)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:383)
        at net.contentobjects.jnotify.JNotify.<clinit>(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at play.runsupport.JNotifyPlayWatchService$JNotifyDelegate.ensureLoaded(PlayWatchService.scala:168)
...
```

**Comment by ralphcollett** [comment] 2016-10-21 13:12
Hi @jkleckner did you resolve your issue? I am seeing the same since upgrading to macOS Sierra (10.12)? Thank-you, Ralph

**Comment by ghost** [comment] 2016-11-10 19:18
Any updates on this?
I am seeing the same on macOS 10.12 and java 1.8.0.101

**Comment by alesbukovsky** [comment] 2016-11-15 13:31
I am also getting the same on MacOS 10.12.1 with Java 1.8.0_112, sbt 0.13.5 and Play 2.3.8. The same setup used to work fine, so I am suspecting the recent security OS update.

**Comment by jkleckner** [comment] 2016-11-15 14:09
@ralphcollett The problem did go away but it wasn't clear what of many things resolved it.  I updated  Xcode and command line tools with xcode-select.  Updated Jdk (both 7 and 8).

Note that an "sbt update" from a cleaned repo is still very slow for me which might be related to #2830

**Comment by M10han** [comment] 2018-02-20 23:45
Hi @jkleckner, @ralphcollett, @unkelly, @alesbukovsky I am seeing the same (java.lang.UnsatisfiedLinkError: no jnotify in java.library.path) error with Mac OS X 10.9.5, Play 2.3, activator 1.3, sbt 1.1.1, Java 1.8.0_161. Please help! Thank you.

**Comment by jkleckner** [comment] 2018-03-15 01:33
@M10han I'm not sure what to suggest.  I haven't seen this with OSX 10.12.6, Java 1.7.0_80-b15/1.8.0_162-b12, sbt 0.13.16, Play 2.3.10, Scala 2.11.8 and xcode-select version 2347.

**Comment by macmacbr** [comment] 2018-09-14 19:10
Seeing the same error with 
OSX 10.13.6
java 1.8.0_181
sbt 0.13.16
play 2.3.10
scala 2.11.11
xcode-select 2349

**Comment by SethTisue** [comment] 2023-07-19 22:45
does sbt even still use jnotify these days?

**Comment by eed3si9n** [comment] 2023-07-20 02:46
We use Ethan's https://github.com/swoval/swoval for file watch, but in theory the issue of loading native libraries `*.so`/`*.dll` files might still persist? https://github.com/sbt/sbt/discussions/6202 covers a list of native libraries that we use directly or indirectly. In any case, since we no longer use JNotify, I'll close this issue until we find out that this is still a problem.

**Closed as not planned** 2023-07-20 03:00 UTC
Labels: Enhancement
