### ISSUE TITLE
Transitive dependency causes wrong evictions

### ISSUE THREAD

**Issue by axos88** [sbt/sbt#2291] opened 2015-11-27 11:37 UTC
In the example below my build.sbt depends on the angular webjar 1.4.7. My other dependency depends on angular webjar version [1.3.0). However the newest version of said jar is 1.5.0-beta.2

Expected: angular jar version 1.4.7 to be used, as it satisfies both requirement
Actual: angular 1.4.7 evicted, and 1.5.0-beta.2 used instead, which does not satisfy my main build.sbt requirements (version 1.4.7)

```
organization := "vandra.hu"

name := "sbt-bug"

version := "0.0.1"

scalaVersion := "2.11.6"

scalacOptions := Seq("-unchecked", "-deprecation", "-encoding", "utf8", "-feature")

libraryDependencies ++= Seq(
   "org.webjars.bower" % "angular" % "1.4.7"
  ,"org.webjars.bower" % "angular-bootstrap" % "0.14.2"
)
```

pom.xml of angular-bootstrap:

```
(...)
        <dependency>
            <groupId>org.webjars.bower</groupId>
            <artifactId>angular</artifactId>
            <version>[1.3.0,)</version>
        </dependency>
```

Run results:

```
akovanm0:foo avandra$ sbt sbtVersion evicted
[info] Set current project to sbt-bug (in build file:/Users/avandra/projects/foo/)
[info] 0.13.6
[info] Updating {file:/Users/avandra/projects/foo/}foo...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * org.webjars.bower:angular:1.4.7 -> 1.5.0-beta.2 (caller: org.webjars.bower:angular-bootstrap:0.14.2, vandra.hu:sbt-bug_2.11:0.0.1)
[success] Total time: 1 s, completed Nov 27, 2015 12:39:19 PM
```

**Comment by axos88** [comment] 2015-11-27 11:39
Worked around with force() for now, but this should be fixed

**Comment by axos88** [comment] 2015-11-27 11:41
Just reproduced in 0.13.9 as well:

```
akovanm0:foo avandra$ sbt sbtVersion evicted
[info] Loading project definition from /Users/avandra/projects/foo/project
[info] Set current project to sbt-bug (in build file:/Users/avandra/projects/foo/)
[info] 0.13.9
[info] Updating {file:/Users/avandra/projects/foo/}foo...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * org.webjars.bower:angular:1.4.7 -> 1.5.0-beta.2 (caller: org.webjars.bower:angular-bootstrap:0.14.2, vandra.hu:sbt-bug_2.11:0.0.1)
[success] Total time: 1 s, completed Nov 2
```

**Comment by eed3si9n** [comment] 2015-12-01 06:32
- https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm
- http://ant.apache.org/ivy/history/latest-milestone/ivyfile/dependency.html

Not sure from reading the above links if the behavior is "wrong" or not.
The notion of version range is mixed up with dynamic revisions in Ivy, which sbt uses internally.
For example, the build user can specify `latest.integration`, and it will pull the latest version from the revolvers. Similarly, the build user can specify `1.0.+`, which will pick the latest that starts with "1.0". In this vein, it's not a stretch to interpret `[1.3.0,)` to be the latest that is greater than `1.3.0`.

In general, if you want more control of the versions, the way to go is using `dependencyOverrides`: http://www.scala-sbt.org/0.13/docs/Library-Management.html#Overriding+a+version

**Comment by axos88** [comment] 2015-12-03 08:02
@eed3si9n, it is fine to interpret [1.3.0,) to be greater than 1.3.0, but there is a direct dependency for "1.4.7" there, which is not being met when it evicts it in favour of "1.5.0-beta.2".

So my problem is not the way the [1.3.0,) works, but the way the specific version of "1.4.7" is replaced with "1.5.0-beta.2"

So build.sbt depens on library x, version 1.4.7, and library y.
library y depends on library x, version [1.3.0.).

Expected: library x version 1.4.7 to be used.

Actual library x, version 1.5.0-beta.2 used.

**Comment by eed3si9n** [comment] 2015-12-03 20:34
The calculation of dynamic revision likely happens prior to the conflict resolution between the nodes. So `[1.3.0,)` effectively is the same as writing `1.5.0-beta.2`. Between 1.5.0-beta.2 and 1.4.7, 1.5.0-beta.2 will win because of eviction. So if you want 1.4.7 to be used, the interpretation of `[1.3.0,)` cannot be "the latest (on the Internet) that is greater than `1.3.0`." Instead it needs to change to "the latest (within the current dependency graph) that is greater than `1.3.0`."

**Comment by axos88** [comment] 2015-12-04 04:45
That makes sense. Do you still think the current one is the intended and expected behaviour?

**Comment by axos88** [comment] 2015-12-04 04:46
IMHO I would never navigate outside the current dependency graph if a resolution can be found without eviction.

**Comment by axos88** [comment] 2015-12-04 04:47
Also it means that if there is one transitive dependency that does not have a direct version specified, but a minimal version, ALWAYS the latest one on the internet will be used, regardless of other libraries' needs.

**Comment by eed3si9n** [comment] 2015-12-04 05:19
> That makes sense. Do you still think the current one is the intended and expected behaviour?

It depends on what the expectations are. We humans have some assumptions of how `x >= 1.3` should be interpreted, but mathematically `x >= 1.3` simply is a restriction on `x` that says it's greater or equal to `1.3`. So, technically it's not wrong when `x` is the largest number on the internet or some other "common sense" number. Since that's how Ivy behaves, I'd have to say it's behaving as designed unless you can point to me some other specs from Ivy documentation. (That's why I linked to Ivy doc in my first response - http://ant.apache.org/ivy/history/latest-milestone/ivyfile/dependency.html)

**Comment by axos88** [comment] 2015-12-04 05:57
"[1.0,) matches all versions greater or equal to 1.0" [all versions, not the latest version]  - http://ant.apache.org/ivy/history/latest-milestone/ivyfile/dependency.html

I'm not sure why you are saying writing [1.3.0,) is the same as writing 1.5.0-beta.2.
The way I am interpreting the statement above is that all versions would be selected by that depepndency, which later on would be crossed with the other dependency statements and would yield a single element, ["1.4.7"], since that's the only version that is common.

Which is very similar to what you said, "the latest (within the current dependency graph) that is greater than 1.3.0."

Also if [1.3.0,) was the same as saying '1.5.0-beta.2', what would be the difference between "[1.3.0,)" and "latest.integration", considering that a version >=1.3.0 already is published (which is almost always the case, can't think of a real-life scenario where i'd create a dependency for a version that does not yet exist)?

**Comment by eed3si9n** [comment] 2017-01-04 21:42
Given that most people use the default Ivy conflict manager that picks the "latest", perhaps we could  provide an option to ignore the dynamic-ness of the dynamic revision when we translate POM, and everyone would be happy.

For example, if we treat Maven's `[1.3.0,)` as Ivy `1.3.0`, and your build.sbt brings in another Ivy `1.4.7`, it will pick up `1.4.7` as you expected.

**Comment by dstibbe** [comment] 2017-01-05 07:32
Then it would be working as expected, indeed :)

(although I do not see how this is 'ignoring the dynamic-ness')

**Comment by eed3si9n** [comment] 2019-08-09 19:57
Closing this to be folded into https://github.com/sbt/sbt/issues/2954.
Also 1.3.0 will use Coursier.

**Closed as completed by eed3si9n** 2019-08-09 19:57 UTC
Labels: area/library_management

**Comment by eed3si9n** [comment] 2019-08-09 21:34
I confirmed using sbt 1.3.0-RC3 that 1.4.7 gets picked.

```
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] * Attributed(/Users/eed3si9n/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.jar)
[info] * Attributed(/Users/eed3si9n/.coursier/cache/v1/https/repo1.maven.org/maven2/org/webjars/bower/angular/1.4.7/angular-1.4.7.jar)
[info] * Attributed(/Users/eed3si9n/.coursier/cache/v1/https/repo1.maven.org/maven2/org/webjars/bower/angular-bootstrap/0.14.2/angular-bootstrap-0.14.2.jar)
```
