### ISSUE TITLE
Activator UI not showing

### ISSUE THREAD

**Issue by kamaudan** [sbt/sbt#2288] opened 2015-11-25 19:21 UTC
When I run the activator UI, the only thing I see is logo,  I read that the problem has to do with sbt .ivy2 
How can I resolving versions conflict. I will be grateful for an answer.

**Comment by SethTisue** [comment] 2015-11-25 19:56
duplicate of https://github.com/typesafehub/activator/issues/1085

**Closed as completed** 2015-12-04 10:11 UTC
