### ISSUE TITLE
Scala 2.10 build failure when using sbt 0.13.12 or higher

### ISSUE THREAD

**Issue by seratch** [sbt/sbt#2790] opened 2016-10-19 02:31 UTC
## steps
- https://github.com/seratch/json4s/commit/0a57852174300955a88ad781f967ed1bd0dba82f
- `sbt ++2.10.6 compile`
- https://gist.github.com/seratch/feea260204db7800ff7538e54fff2874
## problem

The build succeeds when using sbt 0.13.11. But 0.13.12 and 0.13.13-RCs fail to compile as above. Compiling for Scala 2.11 and 2.12.0-RCs are fine.
## expectation

Can compile for Scala 2.10 as well.
## notes

I tried to reproduce the issue on Travis CI environment but somehow it didn't happen there.

https://travis-ci.org/seratch/json4s/builds/168771237

**Comment by eed3si9n** [comment] 2016-10-19 02:41
Regression via https://github.com/sbt/sbt/pull/2432?

**Comment by xuwei-k** [comment] 2016-10-19 03:01
```
sbt ++$TRAVIS_SCALA_VERSION test:compile
echo "sbt.version=0.13.12" > project/build.properties
sbt ++$TRAVIS_SCALA_VERSION test:compile # failure
sbt ++$TRAVIS_SCALA_VERSION clean test:compile  # success
```

https://github.com/xuwei-k/json4s/commit/b13006004e1d4fa1d16cd5e82ab274f54d2f3f56
https://travis-ci.org/xuwei-k/json4s/jobs/168809926

**Comment by dwijnand** [comment] 2016-10-19 08:12
So it's a transient error when upgrade sbt? If so then I'm not sure if there's much we can do to fix that..

**Comment by SethTisue** [comment] 2022-03-17 18:47
closing because of Dale's remarks, because sbt 0.13.x is now unmaintained, and because I'm not sure how much longer it makes sense for sbt/zinc to even support building 2.10 code

**Closed as completed by SethTisue** 2022-03-17 18:47 UTC
