### ISSUE TITLE
SBT download piccolo link return 500

### ISSUE THREAD

**Issue by willohuabunwathd** [sbt/sbt#5860] opened 2020-09-16 14:58 UTC
`curl -L --head https://piccolo.link/sbt-1.3.10.tgz`

HTTP/1.1 500 Internal Server Error
content-type: text/html; charset=UTF-8
x-powered-by: PHP/7.1.22
cache-control: no-cache, private
date: Wed, 16 Sep 2020 14:55:22 GMT

**Comment by melezov** [comment] 2020-09-18 14:36
OT, but I did come into possession of the xsbt.org domain a while ago.
(when SBT was still xsbt, legacy project here: https://github.com/melezov/xsbt.org)

If you guys want to use that I'll happily hand it over.
http://xsbt.org/

**Comment by eed3si9n** [comment] 2020-09-19 17:53
@willohuabunwathd Thanks for the report. Are you still experiencing this issue?
I can't reproduce it locally.

@melezov Thanks for the offer, but I think we're ok. If being able to change the domain name is an option we should use a subdomain of scala-sbt.org.

**Comment by mcintyre94** [comment] 2020-09-23 17:54
Seeing issues with piccolo.link in the last few hours both locally and in our CI.

Tried a few random links on the SBT download page and saw the same. 

```
curl -L --head https://piccolo.link/sbt-1.2.8.tgz
HTTP/1.1 500 Internal Server Error
content-type: text/html; charset=UTF-8
x-powered-by: PHP/7.1.22
cache-control: no-cache, private
date: Wed, 23 Sep 2020 17:52:11 GMT
```

When I hit it in my browser locally I sometimes get a generic 502 or 503, sometimes an error message "Whoops, looks like something went wrong."

**Comment by eed3si9n** [comment] 2020-09-23 18:44
I pinged @dwijnand and @SethTisue about this.

**Comment by bwmills** [comment] 2020-09-23 18:55
Fwiw, we are seeing this issue (using `wget` in a Dockerfile):

```
--2020-09-23 18:08:37--  https://piccolo.link/sbt-1.2.8.tgz
Resolving piccolo.link (piccolo.link)... 169.55.161.7
Connecting to piccolo.link (piccolo.link)|169.55.161.7|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-09-23 18:09:09 ERROR 500: Internal Server Error.
```

in GCP in the **us-central1** region.

**Comment by willohuabunwathd** [comment] 2020-09-23 20:39
Sorry for the delay @eed3si9n but it seems the issue is intermittent..but it is definitely still happening. Below is the logs from Actions
![Screen Shot 2020-09-23 at 4 34 39 PM](https://user-images.githubusercontent.com/67963939/94066732-e111b580-fdba-11ea-994a-c1fdee8a0d3a.png)

**Comment by sjrd** [comment] 2020-09-24 07:21
This has become systematic in the past ~18 hours or so. It blocks every AppVeyor build using sbt I think (at least the one in lampepfl/dotty).

**Comment by ahuret** [comment] 2020-09-24 08:53
Hi, same issue our side. Has anyone a solution to workaround temporary ?

**Comment by Guillaume-iov42** [comment] 2020-09-24 08:56
The workaround we're using is to use the GitHub link instead.

Instead of `https://piccolo.link/sbt-<SBT_VERSION>.tgz`

Use `https://github.com/sbt/sbt/releases/download/v<SBT_VERSION>/sbt-<SBT_VERSION>.tgz`

Actually, I think it's probably more stable to use the GitHub link anyway. We'll probably make this workaround permanent in our build process.

**Comment by ahuret** [comment] 2020-09-24 08:57
It works, thanks !

**Comment by mcintyre94** [comment] 2020-09-24 09:05
On Debian there's also `https://dl.bintray.com/sbt/debian/sbt-SBT_VERSION>.deb` as a workaround

**Comment by eed3si9n** [comment] 2020-09-24 13:13
We'll try to switch over SDKMAN to use the GitHub Releases URL too.

**Comment by eed3si9n** [comment] 2020-09-24 19:12
SDKMAN is now switched over - https://github.com/sdkman/sdkman-db-migrations/pull/348

Locally at least piccolo link seems to be coming back up too:

```
$ curl -L --head https://piccolo.link/sbt-1.3.13.tgz
HTTP/1.1 301 Moved Permanently
content-type: text/html; charset=UTF-8
x-powered-by: PHP/7.1.22
cache-control: no-cache
date: Thu, 24 Sep 2020 19:11:28 GMT
location: https://sbt-downloads.cdnedge.bluemix.net/releases/v1.3.13/sbt-1.3.13.tgz
set-cookie: XSRF-TOKEN=eyJpdiI6Ik51QkxtZ0xcL0h4Y2pDdFdsNUttT2N3PT0iLCJ2YWx1ZSI6IncxT0diNjJQVG8yVFBJdUVIbktxVmMxTWtxcDI5enJQcFk1MG80Tnl4aTF1WmlGVGhLZFRyR2cyOHJud3JoSk5LeFBsRWFraFkxK2NDMXV1NlBcL05Wdz09IiwibWFjIjoiZDZlZTAxZjI2MDE4MGJlYzhiZDRiYjQ5YTU5OWNiOGRhMGUyNWEyM2ZhMGEwOTU3NGY4MDdmMzEyZDA5ZDFmMyJ9; expires=Thu, 24-Sep-2020 21:11:28 GMT; Max-Age=7200; path=/
set-cookie: laravel_session=eyJpdiI6Im10bGRHbk91b1I4N3pocTEzTUdyM1E9PSIsInZhbHVlIjoibzN4eFFRcGJoQVJRUWpnaUdiMXVIenNTZmVQNXF1OUVWYlR0aUxPbDBPbE9Yb3Z1SWU0N3Z5aHFNSEEzVzd4UU9RZUJSRXlxcG0rTVlKRU14MXlwRWc9PSIsIm1hYyI6IjUzZjg4M2MzNDJkNWJlODgwYmUwZDkwMjEzNDJiYWJlOTM3Yjc3YmNiNWNiMmIwNjI2NGJmZTYyODAxOWI2YjIifQ%3D%3D; expires=Thu, 24-Sep-2020 21:11:28 GMT; Max-Age=7200; path=/; HttpOnly
set-cookie: f7929d53dc4eac581de8f1dac5c92c3306a2bb93=eyJpdiI6Ik80TkZTTHVpNk9oWE52cWZvZGNkemc9PSIsInZhbHVlIjoiZFI2dHFxQUphZHg4dlJUS1pMTEpqXC9JcnFRWE1MVEZTSmV4eGtoZjE1N2djWnZKZnc0RnBMUkMwbmw2cEhrdnJSZElBTGRrdG1yYkYrdU1lK2ViMjljcE5GT0ZSRnZENkZIallGY1ZWZ2dRbzZ2Z2Y1OEkxcEJqbFdrMFVqeEdiSjVjOFZudzdmaWpWdEVPYkJNY3l6WlZaS0tSSVhaWjJueENJREl3Z25NSzRxYVdBRDBuMEtuWU15NUtSd1hzc01YUlFKWmdcL0FmOGkzK2RwZE5QSzk2S2hmOEIyMmk0WXlFZlhlZjBSd3RvRTR6TVMzckFzdzJPWm9LamJsQXQyRjdpa1A2OGZ4VVcydjY0SG9YcERFQk5PeDNYeFNmdEVmOFdUWGlBcFROdFBORnQ5RlJWckhCRXprN0tYd0prbERjWmt3TXQ2cjllTUtUXC9reXc3VlwvbGh4dmlCNktPbGNNWkZOc3ZTQkQ2RT0iLCJtYWMiOiIxZjgzZGVjOGRiYzU2Nzk0NzdhODM2OGMzMzI1NTQxZTExMjQ1NTVkN2MwN2Y0ZWE0ZmZjZGI2MDViYjhlYWNmIn0%3D; expires=Thu, 24-Sep-2020 21:11:28 GMT; Max-Age=7200; path=/; HttpOnly

HTTP/2 200
x-clv-request-id: 019f0ac1-b875-4d4b-8397-e46fd6714db4
server: Cleversafe/3.15.0.51
x-clv-s3-version: 2.5
accept-ranges: bytes
x-amz-request-id: 019f0ac1-b875-4d4b-8397-e46fd6714db4
etag: "41de26ec7fe046c601a85c1dbf326c66"
content-type: application/x-gzip
last-modified: Sat, 27 Jun 2020 22:20:17 GMT
content-length: 1227567
date: Thu, 24 Sep 2020 19:11:29 GMT
```

**Comment by marc0der** [comment] 2020-09-28 16:14
This is resolved so closing this issue. Thanks for helping @eed3si9n

**Closed as completed** 2020-09-28 18:22 UTC
Labels: area/proxy, area/dist

**Comment by eed3si9n** [comment] 2020-10-11 19:39
Maybe I spoke too soon about piccolo.link

```
$ curl -L --head https://piccolo.link/sbt-1.3.13.tgz
HTTP/1.1 500 Internal Server Error
content-type: text/html; charset=UTF-8
x-powered-by: PHP/7.1.22
cache-control: no-cache, private
date: Sun, 11 Oct 2020 19:21:58 GMT
```
