### ISSUE TITLE
after upgrading to 1.2.6: `A fatal error happened in `SameAPI`: different extra api hashes for no traits!`

### ISSUE THREAD

**Issue by mr-git** [sbt/sbt#4441] opened 2018-11-06 14:15 UTC
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

Have multi-module project
Change SBT version to 1.2.6

## problem

Change SBT version and compile project. Get exception like:

```
[error] ## Exception when compiling 5 sources to /Users/path/to/project/module/target/scala-2.12/classes
[error] A fatal error happened in `SameAPI`: different extra api hashes for no traits!
[error]   `package.ClassName`: 0
[error]   `package.ClassName`: -1773067415
[error]              
[error] scala.sys.package$.error(package.scala:26)
[error] sbt.internal.inc.IncrementalNameHashing.sameAPI(IncrementalNameHashing.scala:52)
[error] sbt.internal.inc.IncrementalCommon.sameClass(IncrementalCommon.scala:204)
[error] sbt.internal.inc.IncrementalCommon.$anonfun$changedIncremental$1(IncrementalCommon.scala:186)
[error] scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error] scala.collection.Iterator.foreach(Iterator.scala:937)
[error] scala.collection.Iterator.foreach$(Iterator.scala:937)
[error] scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error] scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:177)
[error] scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error] scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error] scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] sbt.internal.inc.IncrementalCommon.changedIncremental(IncrementalCommon.scala:185)
[error] sbt.internal.inc.IncrementalCommon.changedInitial(IncrementalCommon.scala:242)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:66)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1544)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1518)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] sbt.std.Transform$$anon$4.work(System.scala:67)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] sbt.Execute.work(Execute.scala:278)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] java.base/java.lang.Thread.run(Thread.java:844)
```

Tried to remove all `target` directories and then build project, SBT throw up very long stack trace, like:

```
[error] ## Exception when compiling 6 sources to /Users/path/to/project/module/target/scala-2.12/test-classes
[error] null
[error] scala.tools.nsc.typechecker.Contexts$Context.nextOuter(Contexts.scala:629)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:893)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:897)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:897)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:897)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:897)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:897)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:916)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:913)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:896)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitss(Contexts.scala:913)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1477)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:95)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:82)
[error] scala.tools.nsc.Global$$anon$1.inferImplicit(Global.scala:469)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicitFor(Implicits.scala:40)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicitFor$(Implicits.scala:39)
[error] scala.tools.nsc.Global$$anon$1.inferImplicitFor(Global.scala:469)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$applyImplicitArgs$2(Typers.scala:243)
[error] scala.tools.nsc.typechecker.Typers$Typer.applyImplicitArgs(Typers.scala:236)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:881)
[error] scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:471)
[error] scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1219)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5631)
[error] scala.reflect.macros.contexts.Typers.$anonfun$typecheck$4(Typers.scala:26)
[error] scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:693)
[error] scala.reflect.macros.contexts.Typers.$anonfun$typecheck$3(Typers.scala:26)
[error] scala.reflect.macros.contexts.Typers.$anonfun$typecheck$2(Typers.scala:26)
[error] scala.reflect.macros.contexts.Typers.doTypecheck$1(Typers.scala:25)
[error] scala.reflect.macros.contexts.Typers.$anonfun$typecheck$7(Typers.scala:38)
[error] scala.reflect.internal.Trees.wrappingIntoTerm(Trees.scala:1736)
[error] scala.reflect.internal.Trees.wrappingIntoTerm$(Trees.scala:1733)
[error] scala.reflect.internal.SymbolTable.wrappingIntoTerm(SymbolTable.scala:18)
[error] scala.reflect.macros.contexts.Typers.typecheck(Typers.scala:38)
[error] scala.reflect.macros.contexts.Typers.typecheck$(Typers.scala:20)
[error] scala.reflect.macros.contexts.Context.typecheck(Context.scala:6)
[error] scala.reflect.macros.contexts.Context.typecheck(Context.scala:6)
[error] io.circe.generic.util.macros.ExportMacros.exportDecoder(ExportMacros.scala:20)
[error] jdk.internal.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
[error] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.base/java.lang.reflect.Method.invoke(Method.java:564)
[error] scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.$anonfun$resolveJavaReflectionRuntime$4(JavaReflectionRuntimes.scala:34)
[error] scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime(Macros.scala:803)
[error] scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime$(Macros.scala:779)
[error] scala.tools.nsc.Global$$anon$1.macroExpandWithRuntime(Global.scala:469)
[error] scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:620)
[error] scala.tools.nsc.Global.withInfoLevel(Global.scala:219)
[error] scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:613)
[error] scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:600)
[error] scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:764)
[error] scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:762)
[error] scala.tools.nsc.Global$$anon$1.standardMacroExpand(Global.scala:469)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:432)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:429)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:401)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:429)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:429)
[error] scala.tools.nsc.Global$$anon$1.pluginsMacroExpand(Global.scala:469)
[error] scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:757)
[error] scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:757)
[error] scala.tools.nsc.Global$$anon$1.macroExpand(Global.scala:469)
[error] scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1163)
[error] scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1223)
[error] scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1196)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5631)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3280)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:471)
[error] scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgWithFormal$1(PatternTypers.scala:108)
[error] scala.tools.nsc.typechecker.PatternTypers$PatternTyper.$anonfun$typedArgsForFormals$4(PatternTypers.scala:122)
[error] scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgsForFormals(PatternTypers.scala:122)
[error] scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgsForFormals$(PatternTypers.scala:103)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedArgsForFormals(Typers.scala:184)
[error] scala.tools.nsc.typechecker.Typers$Typer.handleMonomorphicCall$1(Typers.scala:3619)
[error] scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3652)
[error] scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4767)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4776)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5571)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:881)
[error] scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:471)
[error] scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1219)
[error] scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1216)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit1(Implicits.scala:759)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit0(Implicits.scala:696)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch.scala$tools$nsc$typechecker$Implicits$ImplicitSearch$$typedImplicit(Implicits.scala:513)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.rankImplicits(Implicits.scala:1019)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.findBest(Implicits.scala:1050)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1107)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1503)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:95)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:82)
...
```

After next recompilation, project managed to get built.

## expectation

Upgrade of patch versions should be simple, but if there are some internal format incompatibilities, then SBT must inform user to discard previous compilation results.

## notes

There are several such places where SBT fails to compile.
The exception happens for case classes like:
```
    final case class ClassName(field: OtherCaseClass)

    object SetupResponse {
      implicit val ClassNameFormat: OFormat[ClassName] = Json.format
    }
```

sbt version: 1.2.6
jvm version: oracle 10.0.2
IDE: JetBrains IDEA Ultimate 2018.2

**Comment by eed3si9n** [comment] 2018-11-08 04:21
@mr-git Thanks for the report. I've run into this myself and it's quite annoying.
Maybe sbt can detect some version difference in Zinc state and wipe it out if it's inconsistent.

**Comment by smarter** [comment] 2018-11-13 21:16
@jvican it seems that there's more unforeseen issues with the API check you added in zinc. Any idea why ? What about just disabling the assertion ?

**Comment by jbaileyashe** [comment] 2018-11-15 18:53
I'm hitting this bug multiple times per day. It started happening when I added a `RootProject` to my existing SBT project (in order for two libraries to share some common code). Not reliably reproducible :( - however, I can always fix it by removing the `target` directories for both projects. (`rm -rf target`).

Using SBT 1.2.6, Typelevel Scala Compiler `2.12.4-bin-typelevel-4`, running on Windows 10 64-bit.

**Comment by jvican** [comment] 2018-11-17 10:16
@smarter I don't know what sbt is doing here, but the fact that these errors constantly show up hints that there's an underlying cause for it outside of zinc. Disabling the assertion is a brute-force measure, https://github.com/sbt/zinc/pull/606 should fix this, but it's not available in 2.12.6 to the best of my knowledge.

**Comment by smarter** [comment] 2018-11-17 10:49
>  but it's not available in 2.12.6 to the best of my knowledge.

Do you mean 1.2.6 ? Because it is.

**Comment by eed3si9n** [comment] 2018-11-18 05:15
AFAIK https://github.com/sbt/zinc/commits/v1.2.4 contains sbt/zinc#606, and sbt 1.2.6 was released to include that. If the end result is we would overcompile in Zinc by invalidating some files, that's better than the current error that requires `clean` or `git clean`.

**Comment by limansky** [comment] 2018-11-23 15:02
I have the same issue. The last not affected sbt version is 1.2.3.

**Comment by tpolecat** [comment] 2018-11-26 07:53
I'm seeing this as well. Works in 1.2.3, fails in 1.2.4/5/6.

**Comment by eed3si9n** [comment] 2018-11-26 16:11
Given the mounting evidence, let's remove the assertion for now.
If someone can come up with minimized steps, that would be helpful, but can come later.

**Comment by limansky** [comment] 2018-11-26 16:32
@eed3si9n If there are any steps to collect logs or other required debugging information feel free to provide it.

**Comment by eed3si9n** [comment] 2018-11-26 16:51
@limansky Typing `debug` into sbt shell would display debug level logs, so that could be a starter once you get into a bad state.

**Comment by jbaileyashe** [comment] 2018-11-26 18:57
@limansky  I think the `last` command (when the bad compilation happens) might also be useful, as it shows the debug output on demand. (If you find that `debug` produces too much output.) From the docs: https://www.scala-sbt.org/1.0/docs/Howto-

**Comment by eed3si9n** [comment] 2018-11-27 21:19
For those who are having issues with sbt 1.2.6, are you switching between older version of sbt (because of branch) without running `clean`, or this error happens while staying on sbt 1.2.6 the whole time?

If switching of sbt versions are involved, then I can workaround that in sbt, but if it's latter it suggests some unknown logical error in Zinc.

**Comment by jbaileyashe** [comment] 2018-11-27 21:21
I'm staying on the same version of SBT.

**Comment by tpolecat** [comment] 2018-11-27 21:29
I changed 1.2.3 to 1.2.6, probably without cleaning, and this started happening, after which cleaning didn't help. Once I got into this situation the only way out was to restart sbt. Probably not helpful, sorry.

**Comment by eed3si9n** [comment] 2018-11-27 21:42
All observations are helpful, even if they provide partial info of the whole picture.

**Comment by jbaileyashe** [comment] 2018-11-27 21:47
I did change from SBT 1.2.1 to 1.2.6 (around Nov 15). Unlikely I ran `clean`.

**Comment by limansky** [comment] 2018-11-27 21:48
@eed3si9n it seems like it happens no matter if I run `clean` or not.

**Comment by eed3si9n** [comment] 2018-11-27 21:50
For ppl who are switching sbt versions, I think it would be good to try running `git clean -fdx` to wipe out all `target` including `project/target`.

**Comment by eatkins** [comment] 2018-11-27 21:50
I'm think I've seen this in projects that have never been upgraded (I cloned an existing project and always ran with sbt version > 1.2.5), but I can't say for sure. And, yes, my solution is always `rm -r **/target`.

**Comment by tpolecat** [comment] 2018-11-27 21:56
It happens with any version > 1.2.3 by the way.

I'll try with `git clean -xdf` and see if the problem comes back. I * think* I tried that but I may have dreamed it.

**Comment by limansky** [comment] 2018-11-28 10:30
I've just checked in clean repo (`git clone myrepo myrepo-test`) and the issue is gone.

Next steps:
1. Revert to 1.2.3, `clean`, `compile`:  everything is file.
2. back to 1.2.6, `compile`: [error] A fatal error happened in `SameAPI`: different extra api hashes for no traits!
3. `clean`,  `compile`: same errors.
4. `git clean -fxd`, `compile`: compile without errors.

**Comment by eed3si9n** [comment] 2018-11-30 14:36
Fixed in https://github.com/sbt/zinc/pull/620

**Closed as completed by eed3si9n** 2018-11-30 14:36 UTC
Labels: area/incremental_compiler, Blocked on Upstream

**Comment by limansky** [comment] 2018-12-04 16:52
@eed3si9n I've just tested. Everything works fine with 1.2.7. Thanks!

**Comment by eed3si9n** [comment] 2018-12-04 18:04
Awesome.
