### ISSUE TITLE
externalDependencyClasspath depending on managedClasspath in Runtime

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt#3578] opened 2017-09-25 15:39 UTC
## steps

Use an sbt-plugin such as sbt-web, and have the following included in your `build.sbt`

```sbt
managedClasspath in Runtime += (packageBin in Assets).value
```

You can clone https://github.com/vmunier/akka-http-with-scalajs-example if you want a live example

Finally load the project in Intellij

## problem

When using Intellij which resolves dependencies via sbt, Intellij runs the `externalDependencyClasspath` task to resolve the dependencies it needs. It appears that this task depends on `managedClasspath in Runtime`. Since plugins such as sbt-web compile Scala.js artifacts to `managedClasspath in Runtime`, this causes Intellij to do a scala-js `fullOptJs` when loading dependencies for such a project, taking easily 20+ minutes and sometimes causing Intellij to freeze

## expectation

Need to clarify if `externalDependencyClasspath` should actually depend on `managedClasspath in Runtime`. According to @sjrd, `managedClasspath in Compile` should be enough to get the dependencies needed for the project. If `externalDependencyClasspath` depending on `managedClasspath in Runtime` is correct, then scala-js/sbt-web needs to re-evaluate how it uses sbt?

## notes

Related ticket is https://github.com/sbt/sbt-web/issues/154
Also scala-js (ticket is closed) https://github.com/scala-js/scala-js/issues/3145

Also on Intellij bug tracker as https://youtrack.jetbrains.com/issue/SCL-12594

sbt version: 0.13.x

**Comment by mdedetrich** [comment] 2017-09-25 15:46
Pinging @jastice

**Comment by dwijnand** [comment] 2017-09-25 15:49
> If `externalDependencyClasspath` depending on `managedClasspath in Runtime` is correct, then scala-js/sbt-web needs to re-evaluate how it uses sbt?

I wonder perhaps `externalDependencyClasspath` depending on `managedClasspath in Runtime` _is_ correct, and IntelliJ should use `managedClasspath in Compile` instead of `externalDependencyClasspath`?

**Comment by jastice** [comment] 2017-09-25 15:54
One issue is that the IntelliJ import evaluates `externalDependencyClasspath` in *all* configurations to get all the artifacts used by the project. Do you think `Runtime` should be specifically excluded? I would have to look into the consequences of that.

**Comment by dwijnand** [comment] 2017-09-25 15:56
For typechecking reasons you only need what's in compile scope. On the other hand it might be handy to have the other runtime dependencies loaded in your IDE too.. For instance slf4j in compile scope and logback in runtime scope - you might want access to the sources of logback.

**Comment by jastice** [comment] 2017-09-25 16:03
There's also the custom scopes such as `it`. But I might try excluding runtime and see how it goes in the Nightlies.

Do you see an alternative to the configuration of making the classpath depend on the build? That doesn't seem right in the first place.

**Comment by mdedetrich** [comment] 2017-09-25 17:05
This is actually interesting, because actually you sometimes do want `managedClasspath in Runtime`, i.e. the slf4j/logback is a very good example of this. Other examples are things like Servlet Java API (or anything where you code against a default interface at compile time but provide an implementation at runtime).

I have a sneaking suspicion that there should be a separate config for compiling assets that are provided at runtime rather than jar's (i.e. dependencies) which are provided at runtime. `managedClasspath in Runtime += (packageBin in Assets).value` is saying that "this is the result of a compiled scala.js + other assets". Putting the "other assets" as a runtime dependency makes sense (i.e. `.css` files) however a compile `.js` binary doesn't make any sense (on the other hand, the `.jar` dependency files resulting from scala.js libraries does make sense).

Maybe we need something like a `managedCompiledClasspath` which is just specific for things like Scalajs builds but not for things like Scala-js library dependencies (denoted by `%%%`) or assets like `.css`/`.html` and `.js` files provided by things like webjars. Basically separating out assets which are provided via dependencies vs assets which need to be compiled (such as a Scala-js `fullOptJs` or even the result of compiles from things like `sbt-less`)

@wsargent Thoughts?

**Comment by eed3si9n** [comment] 2017-09-25 17:22
I am not familiar with how sbt-web and asset pipeline work exactly, but what is the intention of putting `(packageBin in Assets).value` into `managedClasspath in Runtime` here?

> I have a sneaking suspicion that there should be a separate config for compiling assets that are provided at runtime rather than jar's (i.e. dependencies) which are provided at runtime. 

Isn't that called resources? Would there be a problem if `managedResources in Runtime` was used?

**Comment by mdedetrich** [comment] 2017-09-25 18:10
> I am not familiar with how sbt-web and asset pipeline works exactly, but what is the intention of putting (packageBin in Assets).value into managedClasspath in Runtime here?

> Isn't that called resources? Would there be a problem if managedResources in Runtime was used?

Probably would be best to ask here https://github.com/sbt/sbt-web/issues/154

**Comment by richdougherty** [comment] 2017-09-25 19:20
> what is the intention of putting (packageBin in Assets).value into managedClasspath in Runtime here?

> Isn't that called resources? Would there be a problem if managedResources in Runtime was used?

I'm not 100% sure, but sbt-web may package up its resources (CSS, JavaScript, etc) into a [WebJar](https://www.webjars.org/), and this WebJar should then be added to the classpath so that its contents can be found when the web server runs.

**Comment by eed3si9n** [comment] 2017-09-25 21:11
## is there actually a problem with sbt, sbt-web, or Scala.js?

To clarify the situation, it's [akka-http-with-scalajs-example](https://github.com/vmunier/akka-http-with-scalajs-example) that added the following line:

```scala
managedClasspath in Runtime += (packageBin in Assets).value
```

The readme says "The assets (js files, sourcemaps, etc.) are added to the classpath during development thanks to the following lines," so isn't what's happening exactly what the author of akka-http-with-scalajs-example intended? If we don't want that to happen, I think we should try removing the line from `build.sbt`.

Note that sbt-web also uses `resourceManaged in Assets`.

## externalDependencyClasspath

`externalDependencyClasspath` is a task key available for `Compile`, `Runtime`, and `Test` etc.
`Test` extends `Runtime`, which extends `Compile`, so if IntelliJ wants to grab `externalDependencyClasspath` for `Test`, then it will also pull in `Runtime`. Here, I don't think it's unreasonable for IntelliJ to grab `externalDependencyClasspath` for `Test` etc.
It could probably skip `Runtime`, only because no one writes source for that configuration.

**Comment by mdedetrich** [comment] 2017-09-26 00:37
@eed3si9n Thanks a lot for the help, going to make an issue with akka-http-with-scalajs-example. It is also however mentioned on sbt-web, see https://github.com/sbt/sbt-web/blob/master/README.md#packaging-and-publishing

**Comment by mdedetrich** [comment] 2017-09-26 00:43
@eed3si9n Quoting from sbt-web, here is there reasoning

> Assets are automatically packaged and published along with project classes at the following path inside the jar: META-INF/resources/webjars/module/version/. This means that assets can be shared as external library dependencies. Simply publish the project and use as a library dependency. The assets will be extracted and available under lib/module/ in the same way as other webjar dependencies or internal dependencies.

> To package all assets for production there is a packageBin in Assets task, web-assets:package in the sbt shell. This packages the result of the asset pipeline. An optional path prefix can be specified with the packagePrefix in Assets setting. For example, to have assets packaged under a public directory, as used for Play Framework distributions:

On second thoughts, akka-http-with-scalajs-example is just doing what sbt-web said in their README.md. Have to get sbt-web to clarify (agin) why they are using `managedClasspath in Runtime += (packageBin in Assets).value`

**Comment by eed3si9n** [comment] 2017-09-26 00:47
To be part of `packageBin` you just need to join the `products`. `products` are made up of classpath + resources.

To be part of compilation classpath, you need to join some of the classpathes like `externalDependencyClasspath`. Since you don't need png file and text files for your normal compilation, they shouldn't be part of the classpath. And same goes for compiled `*.js` files, no?

**Comment by mdedetrich** [comment] 2017-09-26 00:59
> To be part of packageBin you just needs to join the products. products are made up of classpath + resources.

> To be part of compilation classpath, you need to join some of the classpathes like externalDependencyClasspath. Since you don't need png file and text files for your normal compilation, they shouldn't be part of the classpath. And same goes for compiled *.js files, no?

Yeah agreed, wouldn't something like

```sbt
packageBin in Universal := (packageBin in Universal dependsOn(packageBin in Assets)).value
```

Make more sense? This way you would only trigger a full optimized build when you do a proper binary package.

Another  alternative is to override the `deliver` and `deliverLocal` so that the optimized assets happens before any publishing (which should also work when you do `packageBin in Universal`), i.e.

```sbt
deliver := (deliver dependsOn(packageBin in Assets)).value,
deliverLocal := (deliverLocal dependsOn(packageBin in Assets)).value,
```

@wsargent @jroper Doesn't this make more sense? I mean @eed3si9n  is right, by doing `managedClasspath in Runtime += (packageBin in Assets).value` you are basically saying that "you need these compiled assets as dependencies to compile your project" which isn't really true

**Comment by eed3si9n** [comment] 2017-09-26 01:09
If it needs to be in `packageBin in Compile`, then my first guess is that it should be part of `managedResources in Runtime` as I first wrote.

I also just saw https://github.com/sbt/sbt-web#packaging-and-publishing on sbt-web README.

**Comment by mdedetrich** [comment] 2017-09-26 01:12
Ah yes, you are right. Okay will see what the sbt-web guys are saying. I am going to try this out on my projects to see if there are any issues.

**Comment by jroper** [comment] 2017-09-26 02:39
@mdedetrich If you add:

```
managedClasspath in Runtime += (packageBin in Assets).value
```

To your build, then what you are saying is "I need this jar file on my classpath in order to run my project". Is that true?

I think it's fine for IntelliJ to execute something that eventually executes `managedClasspath in Runtime` to discover dependencies, afterall, it's not a build tool, it isn't just compiling/typechecking your code, it's an IDE which means it runs/debugs your code as well, you can pick any file with a main method in your project and IntelliJ will run it, to do that it needs the runtime classpath, so IntelliJ is probably doing the right thing here.

So back to whether you need your assets binary on your classpath. If you run/debug your projects main class from IntelliJ, will your project successfully run if your assets jar is not on the classpath? Or, will your tests successfully run if the jar is not on the classpath? If not, then technically you need it in `managedClasspath in Runtime`, and there's not a lot that you can do about that, Scala.js is slow, IntelliJ needs Scala.js to run to correctly work out your classpath. I'm not sure why it's so slow, it may be that Scala.js isn't doing incremental compiles, in which case that's a problem in Scala.js that needs to be fixed.

But maybe you never will use IntelliJ to run your project, or run your tests, or maybe you don't need the jar present on your classpath when you run your project or tests. In which case, you can not add it to `managedClasspath in Runtime`, and technically your import to IntelliJ is broken, but that doesn't matter because you don't use IntelliJ to run it.. But maybe you run your project from sbt, using `run`, and you need it present there. If that's the case, then you could try adding it to `fullClasspath in Runtime` (although it might be `fullClasspath in Compile`, not sure which is used). `fullClasspath` is what sbts `run` task uses. Not sure if that's going to work with sbt native packager or other similar plugins.

@eed3si9n `managedResources in Runtime` won't help here - the problem is computing the resources takes too long, whether it's part of a separate artifact, or part of the managed resources, makes no difference. FYI, sbt-web aims to try and keep the assets pipeline/dependencies etc completely separate from the concept of a classpath, until the last minute - since those things are completely separate, they're not classpath resources, they are assets that are served by a webserver. When deployed, the assets artifact could be extracted directly to the filesystem, where the web server serves it from, using efficient native system calls, etc. In some cases, like in Play, the web server serves assets from the classpath, in these cases, we add the assets artifact to the classpath at the last minute in the build process. But this is only optional - you can tell Play not to put them on the classpath, and instead you just take the produced artifact and deploy the assets inside it to a CDN for example. In contrast, if we mixed them up with classpath resources by adding them directly to `managedResources`, how would you differentiate them from each other, gather them from multiple projects etc, and deploy them to a CDN? They'd be mixed up with your configuration files and other valid classpath resources, it'd be a messy and hacky process.

**Comment by jroper** [comment] 2017-09-26 03:21
Another possible solution to this is:

```scala
managedClasspath in Runtime += (artifactPath in packageBin in Assets).value
```

What this will do is add the artifact to the classpath without actually packaging it (and therefore without executing scala.js etc). This should solve the issue with importing to IntelliJ, allowing IntelliJ to run the project with the correct classpath assuming that the artifact has actually been built prior to running it. It will however introduce issues with running from sbt, you might need to do:

```scala
fullClasspath in Runtime := (fullClasspath in Runtime).dependsOn(packageBin in Assets).value
```

To ensure that the assets are actually packaged, and not just on the classpath, before running the project. This might also be needed for things like sbt native packager and sbt assembly, but again, not 100% on what tasks they use.

**Comment by mdedetrich** [comment] 2017-09-26 03:22
> So back to whether you need your assets binary on your classpath. If you run/debug your projects main class from IntelliJ, will your project successfully run if your assets jar is not on the classpath? Or, will your tests successfully run if the jar is not on the classpath?

> If not, then technically you need it in managedClasspath in Runtime, and there's not a lot that you can do about that, Scala.js is slow, IntelliJ needs Scala.js to run to correctly work out your classpath. 

Actually you technically sought of don't. Scala-js has `fastOptJs` and `fullOptJs`. `fastOptJs` is much faster (hence its name) and it can be used to debug/run any code that is produced by Scala.js. In fact, `fastOptJs` is what you should use for debugging/running `.js` code produced by Scala.js. `fullOptJs` should only be ever used for the final package or for things like CDN.

> To your build, then what you are saying is "I need this jar file on my classpath in order to run my project". Is that true?

> I think it's fine for IntelliJ to execute something that eventually executes managedClasspath in Runtime to discover dependencies, afterall, it's not a build tool, it isn't just compiling/typechecking your code, it's an IDE which means it runs/debugs your code as well, you can pick any file with a main method in your project and IntelliJ will run it, to do that it needs the runtime classpath, so IntelliJ is probably doing the right thing here.

Thanks for clarifying. Sure I can understand the technical reasons why this may be "correct", unfortunately its creating a big usability issue as it means that Intellij can't load such projects properly. Also afaik (although I may be wrong here), even if you use `managedClasspath in Runtime += (packageBin in Assets).value`, this doesn't cause other assets (such as sbt-less) to compile all the time when you upload/import `build.sbt`. For Scala.js though, basically any time you change your `build.sbt` (or even just import the project) it will do this `fullOptJs`. `fullOptJs` won't even contain any info in the produce `.js` file to allow debugging/introspection because it all gets optimized out.

> I'm not sure why it's so slow, it may be that Scala.js isn't doing incremental compiles, in which case that's a problem in Scala.js that needs to be fixed.

@jroper  Its slow because it causes Scala.js to do a `fullOptJs` which is a fully optimized Scala.js build, this alone can take 20 minutes to even up to an hour depending on the complexity of the project. Note that this isn't specific to Scala.js, most languages that target Javascript has some sought of full optimize build (usually using Google Closure Compiler) and this is incredibly expensive since it does full program optimization amongst other things. This really can't be avoided, a `fullOptJs` will always take this long

**Comment by mdedetrich** [comment] 2017-09-26 03:25
> To ensure that the assets are actually packaged, and not just on the classpath, before running the project. This might also be needed for things like sbt native packager and sbt assembly, but again, not 100% on what tasks they use.

sbt-native-packager uses `pacakgeBin in Universal` to produce the full artifact.

**Comment by jroper** [comment] 2017-09-26 03:42
I've just had a look at [sbt-web-scalajs](https://github.com/vmunier/sbt-web-scalajs), and I see what the underlying problem is here. It's looking at what command has been run on the CLI to establish whether to run the fast or full JS command. Doing this is really working against the tool, sbt tasks should be idempotent, invoke it once, invoke it 100 times, doesn't matter the context, it should always return the same result if the files its processing haven't changed. This is a fundamental assumption of sbt, and when you break that assumption, such as the way sbt-web-scalajs does, then things start to break in ways that are really difficult to fix.

Fixing this would probably be quite involved, I'm not that experienced with scala.js to know exactly how it works, but what you'd probably need to do is have it configured to run the fast process initially as a source generator, then produce a directory that all assets are copied to correctly prefixed that can be added to your development classpath (this is something that sbt-web could provide, but I don't think it currently does provide, however, Play framework provides exactly this in its development mode, and that directory is isolated and not included in the final production artifact). Then, you'd add a pipeline stage that does the full build, possibly dropping the dev compiled assets from the pipeline if they are no longer applicable. This would be the idiomatic sbt way of doing things that would work well with other tooling.

**Comment by jroper** [comment] 2017-09-26 03:50
By the way, the example project you're using already has published a work around to your problem right at the bottom of its README:

https://github.com/vmunier/akka-http-with-scalajs-example#classpath-during-development

> Note that packageBin in Assets also executes any tasks appended to pipelineStages, e.g. gzip. You may want to avoid executing tasks under pipelineStages during development, because it could take long to execute.
>
> In that case, in order to still have access to the assets under WebKeys.packagePrefix in Assets during development, you can use the following code instead:
>
> ```scala 
> lazy val server = (project in file("server")).settings(
> ...
> WebKeys.packagePrefix in Assets := "public/",
> WebKeys.exportedMappings in Assets ++= (for ((file, path) <- (mappings in Assets).value)
>   yield file -> ((WebKeys.packagePrefix in Assets).value + path)),
>   ...
> )
> ```

I still don't think the way that sbt-web-scalajs works is good, but that should at least work around your issue.

**Comment by eed3si9n** [comment] 2017-09-26 05:01
Isn't the contract of `externalDependencyClasspath in Runtime`, you get the JAR file results from the `update` task in `Runtime`? Keys.scala says:

> The classpath consisting of library dependencies, both managed and unmanaged.

It's reasonable for IntelliJ to then ask for the key, thinking it will get necessary JARs to do whatever it needs to do, like code completion.

By injecting assets into `Runtime` (and thus its child such as `Test`), we are turning `externalDependencyClasspath` into:
- You can get list of JARs, or
- we are going to start compiling TypeScript using Node, Saas using Ruby, Scala.js etc.

When we say "we need assets during development", does it mean we need to generate these assets and put them into "public/"? If so, could that action be delayed until the user hits run/debug button on IntelliJ?

**Comment by mdedetrich** [comment] 2017-09-26 08:43
> I've just had a look at sbt-web-scalajs, and I see what the underlying problem is here. It's looking at what command has been run on the CLI to establish whether to run the fast or full JS command. Doing this is really working against the tool, sbt tasks should be idempotent, invoke it once, invoke it 100 times, doesn't matter the context, it should always return the same result if the files its processing haven't changed. This is a fundamental assumption of sbt, and when you break that assumption, such as the way sbt-web-scalajs does, then things start to break in ways that are really difficult to fix.

While this is a problem, its not the underlying issue. I will make a ticket at sbt-web-scalajs, but @eed3si9n is right. `externalDependencyClasspath in Runtime` is only for loading dependencies (in the context of Scala/Java/Intellij, this means downloading all the jar dependencies). Its not meant to be for compiling assets. Even if this is fixed in sbt-web-scalajs, Intellij will still have to do a `fullOptJs` the first time you load a project, and also every time you edit a `.scala` file for frontend/client code (which gets compiled by Scalajs). Putting assets into `managedClasspath in Runtime` doesn't make any sense, it is breaking the contract of what `managedClassPath` means.

There is one complication which @jroper mentioned earlier, and that is CDN (which is probably why we are doing `managedClasspath in Runtime += (packageBin in Assets).value` in the first place). I suspect that libraries which depend on sbt-web assume that you can get your CDN'ed assets when you hit "compile" in sbt, not when you actually run/test or sbt project. I think this can be resolved by just adding another task to sbt-web which compiles the assets specifically for CDN

How does this sound?

**Comment by jroper** [comment] 2017-09-27 00:14
> There is one complication which @jroper mentioned earlier, and that is CDN (which is probably why we are doing managedClasspath in Runtime += (packageBin in Assets).value in the first place). I suspect that libraries which depend on sbt-web assume that you can get your CDN'ed assets when you hit "compile" in sbt, not when you actually run/test or sbt project.

I'm not sure that there are any such assumptions.

There are three main reasons for adding the assets to the classpath:

* To ensure that they get included by tools such as sbt-native-packager and sbt-assembly
* To ensure that they get get included on the classpath when running the project
* To ensure that they get included on the classpath when running tests

Whichever point (or points) we add the assets to the classpath at, needs to address all three of those. It was a long time ago that we did all this (and there have been some subtle changes to the way sbt composes classpaths since then as well I think), I can't remember if this was thought about in too much depth, or if we just happened to find that adding it to `managedClasspath in Runtime` worked, and so went with that without working out if that was the most ideal place to add it.

So, if there's a better place to add it (perhaps `fullClasspath in Runtime`), then maybe we should switch to that.

@eed3si9n just to be clear, there is nothing in sbt-web that actually does this, it's just documented that if you want to add the assets to the classpath, this is how you do it, and the example project in question here does that.

**Comment by mdedetrich** [comment] 2017-10-04 09:32
@jroper @eed3si9n Just letting you know that `fullClasspath in Runtime += (packageBin in Assets).value` doesn't work. If you run the project than everything is compiled, but running `universal:packageBin` (which sbt-native-packager uses) doesn't compile the assets properly for the final `zip`.

On the other hand, `fullClasspath in Runtime += (packageBin in Assets).value` doesn't force Intellij to do a `fullOptJs` when you load the project, so its a step in the right direction. I think that `fullClasspath in Runtime += (packageBin in Assets).value` combined with something like

```sbt
deliver := (deliver dependsOn(packageBin in Assets)).value,
deliverLocal := (deliverLocal dependsOn(packageBin in Assets)).value,
```

and/or

```sbt
packageBin in Universal := (packageBin in Universal dependsOn(packageBin in Assets)).value
```

Seems to be the more correct option? (Note that I don't know if `deliver`/`deliverLocal`/`packageBin in Universal` are the right keys to override but what is missing when using `fullclassPath` is its missed by sbt-native-package/sbt-assembly).

What do you guys think? Also does anyone know what sbt-assembly requires so the assets get picked up in the final jar?

**Comment by eed3si9n** [comment] 2020-01-04 21:47
I am closing this issue since I am not sure if there's todo on sbt.

> Also does anyone know what sbt-assembly requires so the assets get picked up in the final jar?

Let's continue this over in https://github.com/sbt/sbt-assembly/issues/316.

**Closed as completed by eed3si9n** 2020-01-04 21:47 UTC
Labels: needs info

**Comment by mdedetrich** [comment] 2020-01-04 21:52
> I am closing this issue since I am not sure if there's todo on sbt.

If anything, the only thing that sbt could do in this situation is to provide a suggestion on how to solve this problem https://github.com/sbt/sbt/issues/3578#issuecomment-334101093 .

Not sure if this however has anything to do specifically with sbt-assembly since sbt-native-packager doesn't use sbt-assembly under the hood.

**Comment by eed3si9n** [comment] 2020-01-04 22:20
The membership into `Universal / packageBin` is called `Universal / mapping`. sbt-native-packager populates it by using `JavaAppPackaging` (or ["Java Application Archetype"](https://www.scala-sbt.org/sbt-native-packager/archetypes/java_app/index.html)).

https://github.com/sbt/sbt-native-packager/blob/v1.5.2/src/main/scala/com/typesafe/sbt/packager/archetypes/JavaAppPackaging.scala#L52-L64

```scala
    scriptClasspathOrdering += {
      val jar = (packageBin in Compile).value
      val id = projectID.value
      val art = (artifact in Compile in packageBin).value
      jar -> ("lib/" + makeJarName(id.organization, id.name, id.revision, art.name, art.classifier))
    },
    projectDependencyArtifacts := findProjectDependencyArtifacts.value,
    scriptClasspathOrdering ++= universalDepMappings(
      (dependencyClasspath in Runtime).value,
      projectDependencyArtifacts.value
    ),
    scriptClasspathOrdering := scriptClasspathOrdering.value.distinct,
    mappings in Universal ++= scriptClasspathOrdering.value,
```

If you need to stuff more files into the `Universal / mappings ++= List(...)` you can probably do that first from `build.sbt`, but it might be a good idea to define a custom archetype that extends `JavaAppPackaging` like [`JavaServerAppPackaging`](https://github.com/sbt/sbt-native-packager/blob/v1.5.2/src/main/scala/com/typesafe/sbt/packager/archetypes/JavaServerApplication.scala).
