### ISSUE TITLE
useCoursier := false in build.sbt won't work without adding it in project/plugins.sbt too

### ISSUE THREAD

**Issue by joan38** [sbt/sbt#4878] opened 2019-07-18 04:49 UTC
## steps
sbt version: 1.3.0-RC3

```
echo "useCoursier := false" > build.sbt
mkdir project
echo "sbt.version=1.3.0-RC3" > project/build.properties
echo "addSbtPlugin(\"ch.epfl.scala\" % \"sbt-scalafix\" % \"0.9.5\")" > project/plugins.sbt
sbt updateSbtClassifiers
```

## problem

The problem is if we do `useCoursier := false` in build.sbt we need to do it in project/plugins.sbt too.

**Comment by eatkins** [comment] 2019-07-18 20:15
I'm not really sure how to categorize this. The main build settings are not shared with the meta build. I agree that it is a pain point that useCoursier needs to be specified for both the main build and the meta build but I'm not sure that there is much that can be done about it. The workaround would be to run sbt with `-Dsbt.coursier=false` which will set `useCoursier := false` for both.

Just out of curiosity, what is broken for you with Coursier? Is there an outstanding issue for it?

**Comment by joan38** [comment] 2019-07-18 23:34
@eatkins This specific issue is minor to be fair, all I have to do is add `useCoursier := false ` everywhere as you said, which is ok.
My original issue is https://github.com/sbt/sbt/issues/4720

**Comment by eatkins** [comment] 2019-07-18 23:43
Got it. Thanks for the clarification.

**Comment by francisdb** [comment] 2019-09-06 08:02
I guess this is only needed if your plugins fail to resolve with coursier? like #4852
Then this can be closed as it `works as intended`

**Comment by eed3si9n** [comment] 2019-09-06 19:36
Closing this.

**Closed as completed by eed3si9n** 2019-09-06 19:36 UTC
