### ISSUE TITLE
regression: 0.12.0-RC1 won't launch if there are spaces in path to launcher

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt#488] opened 2012-06-17 21:42 UTC
0.11.3 didn't have this problem:

``` text
% mkdir "foo bar"
% cd "foo bar"
% curl -sSO http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.11.3/sbt-launch.jar
% java -jar sbt-launch.jar 
[info] Set current project to default-501d17 (in build file:/Users/tisue/foo%20bar/)
>
```

but 0.12.0-RC1 does:

``` text
% mkdir "foo bar"
% cd "foo bar"
% curl -sSO http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.12.0-RC1/sbt-launch.jar
% java -jar sbt-launch.jar 
[error] java.net.URISyntaxException: Illegal character in path at index 16: /Users/tisue/foo bar/
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

**Comment by harrah** [comment] 2012-06-17 22:16
The full stack trace would help, but I expect this is a duplicate of #478.

**Closed as completed by harrah** 2012-06-17 22:16 UTC
Labels: Duplicate

**Comment by SethTisue** [comment] 2012-06-17 23:10
oh, indeed, not sure how I missed that.
