### ISSUE TITLE
SBT not functional on Apple M1 silicon (arm64 arch)

### ISSUE THREAD

**Issue by timperrett** [sbt/sbt#6187] opened 2020-12-02 03:40 UTC
## steps

1. buy or obtain a mac with m1 silicon and big sur installed
2. install sbt extras boot script
3. `sbt -sbt-create` (or try to build an existing project)

## problem

When creating a new project:

```
λ sbt -sbt-create
Exception during JVMCI compiler initialization:
jdk.vm.ci.common.JVMCIError: no JVMCI compiler selected: default compiler is not found
	at jdk.vm.ci.hotspot.HotSpotJVMCICompilerConfig$DummyCompilerFactory.compileMethod(jdk.internal.vm.ci@13.0.5.1/HotSpotJVMCICompilerConfig.java:57)
	at jdk.vm.ci.hotspot.HotSpotJVMCICompilerConfig$DummyCompilerFactory.compileMethod(jdk.internal.vm.ci@13.0.5.1/HotSpotJVMCICompilerConfig.java:47)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(jdk.internal.vm.ci@13.0.5.1/HotSpotJVMCIRuntime.java:692)
```

When building an existing project (e.g. cats):

```
λ sbt
java.lang.UnsatisfiedLinkError: /Users/nighthawk/Library/Caches/JNA/temp/jna7516104507158212546.tmp: dlopen(/Users/nighthawk/Library/Caches/JNA/temp/jna7516104507158212546.tmp, 1): no suitable image found.  Did find:
  /Users/nighthawk/Library/Caches/JNA/temp/jna7516104507158212546.tmp: no matching architecture in universal wrapper
  /Users/nighthawk/Library/Caches/JNA/temp/jna7516104507158212546.tmp: no matching architecture in universal wrapper
  at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
  at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2452)
  at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2508)
  at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704)
  at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2637)
  at java.base/java.lang.Runtime.load0(Runtime.java:745)
  at java.base/java.lang.System.load(System.java:1873)
  at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
  at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
  at com.sun.jna.Native.<clinit>(Native.java:195)
  at org.scalasbt.ipcsocket.UnixDomainSocketLibrary.<clinit>(UnixDomainSocketLibrary.java:129)
  at org.scalasbt.ipcsocket.JNAUnixDomainSocketLibraryProvider.socket(UnixDomainSocketLibrary.java:165)
  at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:109)
  at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:87)
  at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:342)
  at sbt.internal.BootServerSocket.<init>(BootServerSocket.java:295)
  at sbt.xMain$.getSocketOrExit(Main.scala:120)
  at sbt.xMain$.run(Main.scala:75)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:567)
  at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
  at sbt.xMain.run(Main.scala:46)
  at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
  at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
  at xsbt.boot.Launch$.run(Launch.scala:111)
  at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
  at xsbt.boot.Launch$.launch(Launch.scala:120)
  at xsbt.boot.Launch$.apply(Launch.scala:20)
  at xsbt.boot.Boot$.runImpl(Boot.scala:56)
  at xsbt.boot.Boot$.main(Boot.scala:18)
  at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.UnsatisfiedLinkError: /Users/nighthawk/Library/Caches/JNA/temp/jna7516104507158212546.tmp: dlopen(/Users/nighthawk/Library/Caches/JNA/temp/jna7516104507158212546.tmp, 1): no suitable image found.  Did find:
[error] [launcher]  /Users/nighthawk/Library/Caches/JNA/temp/jna7516104507158212546.tmp: no matching architecture in universal wrapper
[error] [launcher]  /Users/nighthawk/Library/Caches/JNA/temp/jna7516104507158212546.tmp: no matching architecture in universal wrapper
```

## expectation

SBT should boot and function normally on macs with amd64 hardware. 

## notes

I'm running [Azul's build of AdoptOpenJdk](https://www.azul.com/downloads/zulu-community/?os=macos&architecture=arm-64-bit&package=jdk) - and it would appear that what's happening here is that when SBT tries to start the IPC subsystems for the build server, it bombs due to a problem within JNA due to not being compiled for the amd64 arch. I believe this is related to this issue upstream on JNA: https://github.com/java-native-access/jna/pull/1238

**Comment by eed3si9n** [comment] 2020-12-02 03:46
Hi Tim. This sound like a duplicate of https://github.com/sbt/sbt/issues/6162, which through heroic effort by @eatkins and @catap has been fixed.

You could try the nightly build and see if it works for you (This might require the official launcher that has https://repo.scala-sbt.org/scalasbt/maven-snapshots/ in the default resolvers):

```
sbt.version=1.5.0-bin-20201130T081423
```

**Comment by timperrett** [comment] 2020-12-02 03:47
@eed3si9n Hey old friend! Sorry for the duplicate - will close this and move any conversation over there; will try the snapshot 🙏

**Comment by catap** [comment] 2020-12-02 18:08
@timperrett keep in mind that the only native JVM for M1 right now is zule and you can enjoy my port that might be merged someday: https://github.com/macports/macports-ports/pull/9226

**Closed as completed** 2020-12-04 18:11 UTC
Labels: Duplicate

**Comment by dieu** [comment] 2020-12-10 16:55
@eed3si9n 1.5.0-bin-20201130T081423 is latest version?

I see errors in console, when metals try to connect to sbt server:

```
sbt:scalding> Exception in thread "sbt-networkchannel-0" java.lang.NoClassDefFoundError: Could not initialize class org.scalasbt.ipcsocket.UnixDomainSocketLibrary
	at org.scalasbt.ipcsocket.JNAUnixDomainSocketLibraryProvider.read(UnixDomainSocketLibrary.java:238)
	at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketInputStream.doRead(UnixDomainSocket.java:157)
	at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketInputStream.read(UnixDomainSocket.java:125)
	at sbt.internal.util.ReadJsonFromInputStream$.apply(ReadJsonFromInputStream.scala:49)
	at sbt.internal.server.NetworkChannel$$anon$3.run(NetworkChannel.scala:181)
Exception in thread "sbt-network-2-write-thread" java.lang.NoClassDefFoundError: Could not initialize class org.scalasbt.ipcsocket.UnixDomainSocketLibrary
	at org.scalasbt.ipcsocket.JNAUnixDomainSocketLibraryProvider.write(UnixDomainSocketLibrary.java:247)
	at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketOutputStream.doWrite(UnixDomainSocket.java:185)
	at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketOutputStream.write(UnixDomainSocket.java:176)
	at java.base/java.io.OutputStream.write(OutputStream.java:122)
	at sbt.internal.server.NetworkChannel.impl$1(NetworkChannel.scala:348)
	at sbt.internal.server.NetworkChannel.$anonfun$writeThread$1(NetworkChannel.scala:363)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
and
```
sbt:scalding> Exception in thread "sbt-network-1-write-thread" java.lang.NoClassDefFoundError: Could not initialize class org.scalasbt.ipcsocket.UnixDomainSocketLibrary
	at org.scalasbt.ipcsocket.JNAUnixDomainSocketLibraryProvider.write(UnixDomainSocketLibrary.java:247)
	at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketOutputStream.doWrite(UnixDomainSocket.java:185)
	at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketOutputStream.write(UnixDomainSocket.java:176)
	at java.base/java.io.OutputStream.write(OutputStream.java:122)
	at sbt.internal.server.NetworkChannel.impl$1(NetworkChannel.scala:348)
	at sbt.internal.server.NetworkChannel.$anonfun$writeThread$1(NetworkChannel.scala:363)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "sbt-networkchannel-0" java.lang.UnsatisfiedLinkError: /Users/apanasenko/Library/Caches/JNA/temp/jna10917766929720239658.tmp: dlopen(/Users/apanasenko/Library/Caches/JNA/temp/jna10917766929720239658.tmp, 1): no suitable image found.  Did find:
	/Users/apanasenko/Library/Caches/JNA/temp/jna10917766929720239658.tmp: no matching architecture in universal wrapper
	/Users/apanasenko/Library/Caches/JNA/temp/jna10917766929720239658.tmp: no matching architecture in universal wrapper
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at org.scalasbt.ipcsocket.UnixDomainSocketLibrary.<clinit>(UnixDomainSocketLibrary.java:129)
	at org.scalasbt.ipcsocket.JNAUnixDomainSocketLibraryProvider.read(UnixDomainSocketLibrary.java:238)
	at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketInputStream.doRead(UnixDomainSocket.java:157)
	at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketInputStream.read(UnixDomainSocket.java:125)
	at sbt.internal.util.ReadJsonFromInputStream$.apply(ReadJsonFromInputStream.scala:49)
	at sbt.internal.server.NetworkChannel$$anon$3.run(NetworkChannel.scala:181)
```

**Comment by catap** [comment] 2020-12-10 16:58
@eed3si9n I guess it is a good time to release 1.4.5 to fix this ;)

**Comment by eed3si9n** [comment] 2020-12-10 16:59
@dieu The latest nightly is `1.5.0-bin-20201210T081509`.

@catap Yea. I'll try to get to it this weekend.

**Comment by roohix** [comment] 2021-01-26 06:15
I have app on playframework 2.5.9 and sbt 0.3.6. can I develop on m1 ?
how about with roseta2 ?

**Comment by eed3si9n** [comment] 2021-01-26 14:33
@roohix We use GitHub issue mostly to track bugs and tasks on sbt development. If you have questions or need help, please check this out - https://www.scala-sbt.org/support.html
