### ISSUE TITLE
Updated snapshot versions not being downloaded

### ISSUE THREAD

**Issue by rgladwell** [sbt/sbt#2680] opened 2016-07-22 11:36 UTC
Updated snapshot versions do not appear to be downloaded/updated on a typical sbt command (i.e. `sbt compile`).
## steps
1. `sbt publish` snapshot dependency
2. `sbt compile` in a project consuming the same snapshot dependency.
3. Modify snapshot project
4. `sbt publish` snapshot dependency
5. `sbt compile` in a project consuming the same snapshot dependency.
## problem

`/.ivy2/cache` contains the first version of the snapshot initially downloaded in step 1. Fails to download subsequent modified snapshot dependencies.
## expectation

`/.ivy2/cache` should be updated with new version publish in step 4.
## notes

Snapshots are only updated if marked with `changing()` or an `sbt update` command.

Note, according to the official SBT documentation snapshot version should always be freshly downloaded:

http://www.scala-sbt.org/1.0/docs/Dependency-Management-Flow.html#Notes

This issue also appears to be intermittant: sometimes a snapshot dependency will randomly dowload an update on an `sbt compile`.

(Originally reported: https://github.com/frugalmechanic/fm-sbt-s3-resolver/issues/21)

**Comment by rgladwell** [comment] 2016-07-22 11:41
NB adding:

```
updateOptions := updateOptions.value.withLatestSnapshots(true)
```

To my `build.sbt` does not seem to resolve this issue.

**Comment by dwijnand** [comment] 2016-07-22 11:50
That page says:

> Directly running the update task (as opposed to a task that depends on it) will force resolution to run, whether or not configuration changed. This should be done in order to refresh remote SNAPSHOT dependencies.

I think this is expected behaviour. Think of the performance impact of always checking every snapshot dependency against every resolver.

Also, (I'm pretty sure) you're seeing dependencies be downloaded when a certain timespan has passed - I think it's 24 hours, so every 24h snapshots will be downloaded even with just `compile`.

**Comment by rgladwell** [comment] 2016-07-22 11:55
That section seems to contradict the note I linked to:

> There is no need to mark SNAPSHOT dependencies as changing() because sbt configures Ivy to know this already. 

If an `sbt update` was required to update SNAPSHOT dependencies then the same should be true for dependencies marked as `changing()`. However, dependencies marked as `changing()` always update outside of the `update` goal.

I also note the section you quote doesn't explicitly say the update task is _required_ to refresh  remote SNAPSHOT dependencies.

Is the 24 hour limit documented anywhere? If so, it seems odd as its wildly different to how other build systems handle SNAPSHOTS, like Maven.

**Comment by dwijnand** [comment] 2016-07-22 12:50
I think the current behaviour is what we want.

But I do see the discrepancy/contradiction/confusion, so I think we should improve the documentation here. Given what you've found, would you like to contribute to improve the documentation for this?

**Comment by rgladwell** [comment] 2016-07-22 13:39
It's disappointing that SBT handles SNAPSHOT versions in an unexpected and non-standard way. Are there any plans to change this to make this behaviour more usable and conventional in the future?

**Comment by dwijnand** [comment] 2016-07-22 13:42
What standard and/or convention are you referring to?

Also, why is using `update` or `changing()` not sufficiently usable for you?

**Comment by rgladwell** [comment] 2016-07-22 13:46
I think most developers would expect SNAPSHOT versions to be downloaded on each dependency resolution pass, matching the behaviour of Maven. I.e. if you would expect a task/goal to resolve dependencies it should also refresh SNAPSHOT dependencies.

Not doing so seems surprising and good usability is about satisfying user's expectations.

**Comment by dwijnand** [comment] 2016-07-22 13:52
No, Maven has a `-U` flag specifically to update snapshots.

Sbt has the `update` task, or you can use `changing()` on the dependency.

It's not feasible to do this every time, but perhaps you would like to contribute this as a feature to sbt.

**Comment by eed3si9n** [comment] 2016-07-22 16:42
> I think most developers would expect SNAPSHOT versions to be downloaded on each dependency resolution pass, matching the behaviour of Maven. I.e. if you would expect a task/goal to resolve dependencies it should also refresh SNAPSHOT dependencies.

As Dale wrote, that's not how Maven works.

I don't think we have TTL on the SNAPSHOTs. The `update` task is cached if the input doesn't change.

Suppose we implemented always-hit-the-Internet semantics for all SNAPSHOTs:
- The performance will be horrible for projects with 20 subprojects, because it will hit the Internet 20 times.
- You won't be able to code when the network goes down or when you're on the plane. (That's still iffy today, but it'll get worse)

I'm closing this for now.

**Closed as completed by eed3si9n** 2016-07-22 16:42 UTC
Labels: area/library_management
