### ISSUE TITLE
Incorrect classpath when artifacts differ only by classifier

### ISSUE THREAD

**Issue by mpeltonen** [sbt/sbt#419] opened 2012-04-05 21:47 UTC
Adding different classifiers of the same artifact as libraryDependencies, only the last one is included in external-dependency-classpath:

``` code
$ cat build.sbt 
libraryDependencies += "com.github.scala-incubator.io" %% "scala-io-core" % "0.3.0" 

libraryDependencies += "com.github.scala-incubator.io" %% "scala-io-core" % "0.3.0" classifier "test"
$ sbt11 'show external-dependency-classpath'
[info] Set current project to default-d0f036 (in build file:/private/tmp/)
[info] ArrayBuffer(Attributed(/Users/mpe/.sbt/boot/scala-2.9.1/lib/scala-library.jar), Attributed(/Users/mpe/.ivy2/cache/com.github.scala-incubator.io/scala-io-core_2.9.1/jars/scala-io-core_2.9.1-0.3.0-test.jar), Attributed(/Users/mpe/.ivy2/cache/com.github.jsuereth.scala-arm/scala-arm_2.9.1/jars/scala-arm_2.9.1-1.1.jar))
[success] Total time: 0 s, completed Apr 6, 2012 12:28:25 AM
$ 
```

In the above case, only 'scala-io-core_2.9.1-0.3.0-test.jar' ends up in classpath.

I can get both jars into classpath by moving 'test' classified artifact to 'test' configuration _and_ adding withSources() to non-classified one:

``` code
$ cat build.sbt 
libraryDependencies += "com.github.scala-incubator.io" %% "scala-io-core" % "0.3.0" withSources()

libraryDependencies += "com.github.scala-incubator.io" %% "scala-io-core" % "0.3.0" % "test" classifier "test"
$ sbt11 'show test:external-dependency-classpath'
[info] Set current project to default-d0f036 (in build file:/private/tmp/)
[info] ArrayBuffer(Attributed(/Users/mpe/.sbt/boot/scala-2.9.1/lib/scala-library.jar), Attributed(/Users/mpe/.ivy2/cache/com.github.scala-incubator.io/scala-io-core_2.9.1/jars/scala-io-core_2.9.1-0.3.0-test.jar), Attributed(/Users/mpe/.ivy2/cache/com.github.scala-incubator.io/scala-io-core_2.9.1/jars/scala-io-core_2.9.1-0.3.0.jar), Attributed(/Users/mpe/.ivy2/cache/com.github.jsuereth.scala-arm/scala-arm_2.9.1/jars/scala-arm_2.9.1-1.1.jar))
[success] Total time: 0 s, completed Apr 6, 2012 12:42:10 AM
$ 
```

**Comment by harrah** [comment] 2012-04-05 23:21
Duplicate of #285.  This is an Ivy quirk or bug or something.  The lack of a classifier has to be represented as an empty string.  If it can be shown that sbt can work around this, this can be reopened.

**Closed as completed by harrah** 2012-04-05 23:21 UTC
Labels: Duplicate

**Comment by mpeltonen** [comment] 2012-04-06 08:04
Thanks! I guessed that there might already be an issue about this one, but didn't find it by quick search.
