### ISSUE TITLE
Sbt won't install on Ubuntu

### ISSUE THREAD

**Issue by lucaster** [sbt/sbt#279] opened 2011-11-25 20:34 UTC
I followed the instructions at https://github.com/harrah/xsbt/wiki/Getting-Started-Setup

I tried the installation on a Windows machine, on which Maven isn't installed, and the installation went through.

I then followed the Unix installation instructions on a Ubuntu machine with Maven installed, but the installation fails, with the following error:

Getting net.java.dev.jna jna 3.2.3 ...

:: problems summary ::
:::: WARNINGS
        [NOT FOUND  ] net.java.dev.jna#jna;3.2.3!jna.jar (2ms)

```
==== Maven2 Local: tried

  file:///home/luca/.m2/repository/net/java/dev/jna/jna/3.2.3/jna-3.2.3.jar

    ::::::::::::::::::::::::::::::::::::::::::::::

    ::              FAILED DOWNLOADS            ::

    :: ^ see resolution messages for details  ^ ::

    ::::::::::::::::::::::::::::::::::::::::::::::

    :: net.java.dev.jna#jna;3.2.3!jna.jar

    ::::::::::::::::::::::::::::::::::::::::::::::
```

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
download failed: net.java.dev.jna#jna;3.2.3!jna.jar
Error during sbt execution: Error retrieving required libraries
  (see /home/luca/.sbt/boot/update.log for complete log)
Error: Could not retrieve JNA

**Comment by indrajitr** [comment] 2011-11-25 20:50
Okay, this is likely a duplicate of #217.

**Comment by lucaster** [comment] 2011-11-25 21:04
Ok, I cleared ~/.sbt, ~/.ivy2 and ~/.m2 and the the installation went through.

I will now restore the three directories, hoping that I won't have to clear them each time I have to run sbt though :/

What was the reason for the error by the way?

**Comment by fernandezpablo85** [comment] 2011-11-28 03:10
Shouldn't this be closed already?

**Closed as completed** 2011-11-28 06:18 UTC
Labels: Duplicate

**Comment by wspringer** [comment] 2012-11-08 07:57
I still have exactly this problem happening with fresh SBT installations (0.12.0) happening once in a while. Which is _incredibly_ annoying, since that's what our build servers do: they start with nothing but an SBT jar. BTW, if you just Google for this problem, you will find numerous people having this problem.
