### ISSUE TITLE
SERVER ERROR: GATEWAY_TIMEOUT url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.18/jars/compiler-ivy-integration.jar

### ISSUE THREAD

**Issue by dimisjim** [sbt/sbt#6461] opened 2021-04-21 09:43 UTC
## problem

A project that uses sbt `0.13.18` outputs this error while trying to `sbt assembly` the project

Full stack trace:
```
:: problems summary ::
:::: WARNINGS
		[FAILED     ] org.scala-sbt#compiler-ivy-integration;0.13.18!compiler-ivy-integration.jar: The HTTP response code for https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.18/jars/compiler-ivy-integration.jar did not indicate a success. See log for more detail. (736ms)

		[FAILED     ] org.scala-sbt#compiler-ivy-integration;0.13.18!compiler-ivy-integration.jar: The HTTP response code for https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.18/jars/compiler-ivy-integration.jar did not indicate a success. See log for more detail. (736ms)

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.18/jars/compiler-ivy-integration.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::              FAILED DOWNLOADS            ::

		:: ^ see resolution messages for details  ^ ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#compiler-ivy-integration;0.13.18!compiler-ivy-integration.jar

		::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
	SERVER ERROR: GATEWAY_TIMEOUT url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.18/jars/compiler-ivy-integration.jar


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
download failed: org.scala-sbt#compiler-ivy-integration;0.13.18!compiler-ivy-integration.jar
Error during sbt execution: Error retrieving required libraries
  (see /root/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.18
```

closely related to another issue reported earlier today: https://github.com/sbt/sbt/issues/6460

**Comment by dimisjim** [comment] 2021-04-21 10:23
related issue: https://github.com/sbt/sbt/issues/6460

**Comment by eed3si9n** [comment] 2021-04-28 16:53
I'm going to close this as likely duplicate of https://github.com/sbt/sbt/issues/6460

**Closed as completed by eed3si9n** 2021-04-28 16:53 UTC
