### ISSUE TITLE
(hive/*:update) java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = commons-codec#commons-codec;1.4

### ISSUE THREAD

**Issue by yuzhenling** [sbt/sbt#2265] opened 2015-11-10 02:02 UTC
Hello,

 I am using sbt to install spark 1.5.1, when I execute command 'sbt assembly', it will show error like below, I have already remove folder .ivy , .sbt and reinstall sbt , but the problem is remain, My OS is windows 7 , version 1.4 of commons-codec#commons-codec exists under .ivy/cache .....  Would you help to give some advice? Thanks in advance!

```
[warn] Merging 'org\objenesis\instantiator\sun\Sun13InstantiatorBase.class' with strategy 'first
[warn] Merging 'org\objenesis\instantiator\sun\Sun13SerializationInstantiator.class' with strate
first'
[warn] Merging 'org\objenesis\instantiator\sun\SunReflectionFactoryInstantiator.class' with stra
 'first'
[warn] Merging 'org\objenesis\instantiator\sun\SunReflectionFactorySerializationInstantiator.cla
with strategy 'first'
[warn] Merging 'org\objenesis\strategy\BaseInstantiatorStrategy.class' with strategy 'first'
[warn] Merging 'org\objenesis\strategy\InstantiatorStrategy.class' with strategy 'first'
[warn] Merging 'org\objenesis\strategy\SerializingInstantiatorStrategy.class' with strategy 'fir
[warn] Merging 'org\objenesis\strategy\StdInstantiatorStrategy.class' with strategy 'first'
[warn] Merging 'reference.conf' with strategy 'concat'
[warn] Merging 'rootdoc.txt' with strategy 'first'
[warn] Strategy 'concat' was applied to a file
[warn] Strategy 'discard' was applied to 3 files
[warn] Strategy 'first' was applied to 7145 files
[info] Assembly up to date: E:\Tools\spark-1.5.1\assembly\target\scala-2.10\spark-assembly-1.5.1
oop2.2.0.jar
java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyN
= commons-codec#commons-codec;1.4
        at org.apache.ivy.core.resolve.IvyNode.getArtifacts(IvyNode.java:809)
        at org.apache.ivy.core.resolve.IvyNode.getSelectedArtifacts(IvyNode.java:786)
        at org.apache.ivy.core.report.ResolveReport.setDependencies(ResolveReport.java:235)
        at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:235)
        at org.apache.ivy.Ivy.resolve(Ivy.java:517)
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:266)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:157)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:128)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:64)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.sca
8)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
        at sbt.IvySbt.withIvy(Ivy.scala:123)
        at sbt.IvySbt.withIvy(Ivy.scala:120)
        at sbt.IvySbt$Module.withModule(Ivy.scala:151)
        at sbt.IvyActions$.updateEither(IvyActions.scala:157)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1318)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1315)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1345)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1343)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1348)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1342)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1360)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1300)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1275)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
[error] (hive/*:update) java.lang.IllegalStateException: impossible to get artifacts when data h
ot been loaded. IvyNode = commons-codec#commons-codec;1.4
[error] Total time: 978 s, completed Nov 9, 2015 6:16:42 PM
```

**Comment by yuzhenling** [comment] 2015-11-10 02:40
I refer to https://github.com/holdenk/spark/commit/e3099425e5b99e62238f8bed269983c0f9891f32, and then add change into the hive/pom.xml ,but seems useless...

**Comment by eed3si9n** [comment] 2015-11-10 20:50
This seems like a duplicate of #2015

**Closed as completed by eed3si9n** 2015-11-10 20:50 UTC
Labels: Duplicate

**Comment by yuzhenling** [comment] 2015-11-12 06:31
I have downloaded spark1.5.0 for learning, everything is going well, Thanks.
