### ISSUE TITLE
sbt 1.0.2 ~compile loops forever with source generator

### ISSUE THREAD

**Issue by tpolecat** [sbt/sbt#3565] opened 2017-09-20 21:23 UTC
## steps

1. check out http://tpolecat.github.io/doobie/
2. sbt
3. project core
4. ~compile
6. wait. it will recompile every 10 seconds or so

## expectation

It shouldn't do that.

## notes

If I comment out the source generator [here](https://github.com/tpolecat/doobie/blob/series/0.5.x/build.sbt#L269-L287) it doesn't do this. Should I be doing this differently?

sbt version: *1.0.2*

**Comment by eed3si9n** [comment] 2017-09-21 07:06
Is it source code generation in general that causes this, or the fact that you have timestamp in there that's causing the loop?

/cc @Duhemm

**Comment by dwijnand** [comment] 2017-09-21 13:31
Duplicate of #3501 (imo)

**Closed as completed by dwijnand** 2017-09-21 13:31 UTC
Labels: area/watch

**Comment by dwijnand** [comment] 2017-10-09 15:33
Here's the link using a stable sha: https://github.com/tpolecat/doobie/blob/cda21f0ece72e3a63392477237a32c26bb4f127d/build.sbt#L269-L287

**Comment by dwijnand** [comment] 2017-10-09 15:39
To answer the question: it's source generators in general.

**Comment by tpolecat** [comment] 2017-10-09 16:49
Sorry I didn't provide a stable link. I later reverted to sbt 0.13 as you probably discovered. The 10-second delay was due to the file watcher bug, which I'm also tracking. Thanks!
