### ISSUE TITLE
Failure to download sbt 0.13.18

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#4827] opened 2019-06-21 09:09 UTC
## steps
sbt version: 1.3.0-RC2

* https://github.com/playframework/interplay/pull/79/files
* Run `validate`

## problem

```
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:sbt:0.13.18
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.18/sbt-0.13.18.pom
[error]   not found: /home/travis/.ivy2/local/org.scala-sbt/sbt/0.13.18/ivys/ivy.xml
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/sbt/0.13.18/sbt-0.13.18.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/sbt/0.13.18/ivys/ivy.xml
[error] Error downloading org.scala-sbt:scripted-plugin:0.13.18
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala-sbt/scripted-plugin/0.13.18/scripted-plugin-0.13.18.pom
[error]   not found: /home/travis/.ivy2/local/org.scala-sbt/scripted-plugin/0.13.18/ivys/ivy.xml
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/scripted-plugin/0.13.18/scripted-plugin-0.13.18.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/scripted-plugin/0.13.18/ivys/ivy.xml
[error] Error downloading org.scala-sbt:sbt-core-next;sbtVersion=0.13;scalaVersion=2.10:0.1.1
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala-sbt/sbt-core-next_2.10_0.13/0.1.1/sbt-core-next-0.1.1.pom
[error]   not found: /home/travis/.ivy2/local/org.scala-sbt/sbt-core-next/scala_2.10/sbt_0.13/0.1.1/ivys/ivy.xml
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/sbt-core-next_2.10_0.13/0.1.1/sbt-core-next-0.1.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/sbt-core-next/scala_2.10/sbt_0.13/0.1.1/ivys/ivy.xml
```

## expectation

Validation passes

**Comment by eed3si9n** [comment] 2019-06-21 20:36
A duplicate of https://github.com/sbt/sbt/issues/4698, I am guessing.
I was wondering if we can just call this one a breaking change with a workaround to add typesafe-ivy resolver if you want to cross build against 0.13.

**Comment by dwijnand** [comment] 2019-06-21 21:10
Presumably it's not Apache Ivy that's adding the Typesafe Ivy repo.  So what part of sbt is adding it and why doesn't it also add it to Coursier?

**Comment by eed3si9n** [comment] 2019-06-22 00:11
sbt 1.2.8 https://github.com/sbt/sbt/blob/v1.2.8/main/src/main/scala/sbt/Defaults.scala#L200-L203

```scala
      sbtResolver := {
        if (sbtVersion.value endsWith "-SNAPSHOT") Classpaths.sbtIvySnapshots
        else Classpaths.typesafeReleases
      },
```

sbt 1.3.0-RC2 https://github.com/sbt/sbt/blob/v1.3.0-RC2/main/src/main/scala/sbt/Defaults.scala#L219-L223

```scala
      sbtResolver := {
        val v = sbtVersion.value
        if (v.endsWith("-SNAPSHOT") || v.contains("-bin-")) Classpaths.sbtMavenSnapshots
        else Resolver.DefaultMavenRepository
      },
```

so the change of behavior was introduced in https://github.com/sbt/sbt/pull/4409 where I corrected `sbtResolver` to point at Maven Central, unrelated to Coursier. I guess I can point it back to typesafe-releases.

**Comment by eed3si9n** [comment] 2019-06-22 04:45
https://github.com/sbt/sbt/pull/4829

**Closed as completed** 2019-06-24 00:45 UTC
Labels: area/library_management, Regression
