### ISSUE TITLE
on 'sbt run', Thread.currentThread.getContextClassLoader cannot load scala.Int

### ISSUE THREAD

**Issue by raboof** [sbt/sbt#3736] opened 2017-11-13 16:40 UTC
## steps

Check out https://github.com/raboof/sbt-run-classloading and `sbt run`

## problem

An error is thrown trying to load the `scala.Int` class

## notes

This might be related to #3515, however there it is mentioned that it only fails for `URLClassLoader`s, while I get a `ClasspathFilter`:
```
ClasspathFilter(
  parent = URLClassLoader with NativeCopyLoader with RawResources
(
  urls = Vector(/tmp/sbt_db097681/job-6/target/d9ce6563/bug-facto
ryconfig_2.12-0.1-SNAPSHOT.jar, /tmp/sbt_db097681/target/7663f74e
/scala-library.jar),
  parent = java.net.URLClassLoader@5056dfcb,
  resourceMap = Set(app.class.path, boot.class.path),
  nativeTemp = /tmp/sbt_baa31d30
)
  root = sun.misc.Launcher$AppClassLoader@677327b6
  cp = Set(/tmp/sbt_db097681/job-6/target/d9ce6563/bug-factorycon
fig_2.12-0.1-SNAPSHOT.jar, /tmp/sbt_db097681/target/7663f74e/scal
a-library.jar)
)

```

**Comment by gmarti** [comment] 2017-12-04 13:31
i have same problem with sbt 0.13.6 scala 2.11.8 and akka-remote 2.5.4
If i start my project without akka-remote i don't have the scala.Int exception.

I try to make a short example

**Comment by franbh** [comment] 2017-12-07 15:02
I had this problem while starting a new project until I realized that I had forgotten to fork the JVM for the run task:
```fork in run := true```

Although this seems to be a SBT regression, the workaround is pretty simple.

BTW I'm using SBT 1.0.4, Scala 2.12.4, Akka 2.5.7.

**Comment by ktoso** [comment] 2017-12-13 13:08
Just making sure you've seen this @eed3si9n @dwijnand; 
It seems to stop us from moving quickstart examples to sbt 1.0 etc.
So the workaround with forking exists, but is a bit too weird for users (esp in our quickstarts, when things would stop working if not forked)

**Comment by ravwojdyla** [comment] 2017-12-20 05:25
Just for the reference, PTAL: https://github.com/sbt/zinc/pull/473

**Comment by eed3si9n** [comment] 2017-12-22 19:02
Zinc fix is now merged. Please try sbt 1.1.0-RC3.

**Closed as completed by eed3si9n** 2017-12-22 19:02 UTC
Labels: Regression

**Comment by raboof** [comment] 2018-05-30 16:14
(this issue *may* have returned in 1.1.5, at least something that looks a lot like it, but I'll first dig a bit further in https://github.com/akka/akka/issues/24098 before really blaming sbt :smile:  )
