### ISSUE TITLE
make `sbt new` work to create a simple build without requiring g8 template as arg

### ISSUE THREAD

**Issue by bjornregnell** [sbt/sbt#6574] opened 2021-07-01 10:23 UTC
## steps

```
$ sbt new
[info] welcome to sbt 1.5.4 (Ubuntu Java 11.0.11)
[info] loading settings for project global-plugins from gpg.sbt ...
[info] loading global plugins from /home/bjornr/.sbt/1.0/plugins
[info] set current project to new (in build file:/tmp/sbt_b525b66e/new/)
Template not found for: 
$
```

## problem

The error message is not helpful, esp not to a beginner.
## expectation
`sbt new` should Just Work (TM) and e.g. give me the simplest possible single-project `build.sbt` with the latest `scalaVersion` as a bare-bone setting on top level.

## notes
see also https://github.com/sbt/sbt/issues/6217

**Comment by bjornregnell** [comment] 2022-01-03 18:49
see also https://github.com/sbt/sbt/discussions/6772#discussioncomment-1901624

**Comment by SethTisue** [comment] 2022-01-04 01:51
I'd love to see a volunteer tackle this. Even if it were only to give a much better error message with guidance on what the user should do instead.

**Comment by eed3si9n** [comment] 2022-01-04 01:53
This also seems related or plain duplicate of https://github.com/sbt/sbt/issues/3949

**Comment by magnolia-k** [comment] 2022-10-06 15:42
If the argument is omitted, it may be a good idea to use scala-seed.g8 as the default value.

**Comment by adpi2** [comment] 2024-12-10 07:56
Now that we have the interactive menu (https://github.com/sbt/sbt/pull/7228), we probably don't want this anymore.

**Closed as not planned by adpi2** 2024-12-10 07:56 UTC
