### ISSUE TITLE
Unexpected access to /tmp and AccessDeniedException exception 

### ISSUE THREAD

**Issue by michalbogacz** [sbt/sbt#6979] opened 2022-07-20 06:23 UTC
## steps

Running sbt in restricted environment with limited access can result with unexpected exception

```
16:35:44  [info] [launcher] getting org.scala-sbt sbt 1.7.1  (this may take some time)...
16:35:50  [info] [launcher] getting Scala 2.12.16 (for sbt)...
16:35:50  java.nio.file.AccessDeniedException: /tmp/.sbt/sbt-socket8345419141087914081
16:35:50  	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
16:35:50  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
16:35:50  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
16:35:50  	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
16:35:50  	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
16:35:50  	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
16:35:50  	at java.base/java.nio.file.Files.createDirectories(Files.java:783)
16:35:50  	at sbt.internal.BootServerSocket.<init>(BootServerSocket.java:290)
16:35:50  	at sbt.xMain$.getSocketOrExit(Main.scala:145)
16:35:50  	at sbt.xMain$.bootServerSocket$lzycompute$1(Main.scala:77)
16:35:50  	at sbt.xMain$.bootServerSocket$1(Main.scala:77)
16:35:50  	at sbt.xMain$.withStreams$1(Main.scala:85)
16:35:50  	at sbt.xMain$.run(Main.scala:121)
16:35:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:35:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:35:50  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

## problem

I updated sbt from 1.6.1 to 1.7.1 on very restricted Jenkins without access to /tmp.
Then I started `sbt sbtVersion`

## expectation

I expected there will be no files access changes between 1.6.1 and 1.7.1 versions. 
If it's expected, it would be nice to add what path to set in https://www.scala-sbt.org/1.x/docs/Command-Line-Reference.html#Command+Line+Options to mitigate that issue.

## notes
I was able to fix it using `java.io.tmpdir` option, after I found https://github.com/sbt/ipcsocket/pull/23

**Comment by eed3si9n** [comment] 2022-07-20 22:04
> I expected there will be no files access changes between 1.6.1 and 1.7.1 versions.

This was documented in https://github.com/sbt/sbt/releases/tag/v1.7.0. We do make breaking changes in minor versions.

**Comment by NikkChern** [comment] 2022-08-08 12:02
@michalbogacz @eed3si9n Hello. Can you please provide value for "java.io.tmpdir"? I have tried to fix it, but I haven't find right option. Thank you
P.S. Also, I agree with @michalbogacz, it would be great to document this in SBT documentation (as mentioned in "expectation" section)

**Comment by michalbogacz** [comment] 2022-08-08 12:52
@NikkChern You can run sbt with property `-Djava.io.tmpdir=$HOME`. 
In my case, I have write access in $HOME path. But in your case it can be some other directory you have write access to.

**Comment by placydo** [comment] 2022-08-30 07:57
Thanks @michalbogacz, your solution fixed my issue too!

**Comment by francisdb** [comment] 2022-09-23 10:31
The sbt [docker images](https://github.com/sbt/docker-sbt) also have this problem when run as non-default user as /tmp/.sbt is owned by `sbtuser`.

We saw this when running a jenkins docker pipeline

```
pipeline {
    agent {
        docker { image 'sbtscala/scala-sbt:eclipse-temurin-17.0.4_1.7.1_3.2.0' }
    }
    ...
```

Which makes jenkins call

```
docker run -t -d -u 106:114  ...
```

**Comment by jsleight** [comment] 2023-10-06 19:12
I also encountered this.  I'm pretty sure it is caused by #6887.  So you should set the `XDG_RUNTIME_DIR` env variable to control where the socket gets created.  I just set `XDG_RUNTIME_DIR = $(HOME)` to fix error.

**Comment by eed3si9n** [comment] 2023-10-06 21:22
To support libraries that work with native libraries, we need a place to extract `*.so`/`*.dll` kind of files. Current implementation looks like this:

https://github.com/sbt/sbt/blob/bf8e92be743bca3d1e3c200e191134fe55e840a9/main/src/main/scala/sbt/internal/SysProp.scala#L247-L262

Yea, maybe the advice should be to set `XDG_RUNTIME_DIR` environment variable to a directory of choosing given that we would like to walk towards using XDG more instead of spewing files in various subdirectories under `$HOME`. So for now, I'm going to close this as won't fix.

**Closed as not planned by eed3si9n** 2023-10-06 21:22 UTC
