### ISSUE TITLE
Name hashing heap explosion with shapeless master

### ISSUE THREAD

**Issue by milessabin** [sbt/sbt#1640] opened 2014-10-03 11:11 UTC
Building shapeless master with SBT 0.13.6 results in an OutOfMemoryError with default 2G heap (configured via .jvmopts) and continued to fail with the heap limit increased to 3 and 4G.

Reverting to 0.13.5 or disabling name hashing (with `incOptions := incOptions.value.withNameHashing(false)`) allows the build to complete successfully in 2G.

**Comment by gkossakowski** [comment] 2014-10-03 12:59
Thanks for the report!  This looks like duplicate of #1610 but with advantage of publicly available project where OOM happens. I'll have a quick look now.

**Comment by gkossakowski** [comment] 2014-10-03 13:31
The problem is with macro expansion handling. The `ExtractUsedNames.handleMacroExpansion` appears to go into an infinite loop and leaks memory at the same time.

**Comment by gkossakowski** [comment] 2014-10-03 13:33
//cc @Duhemm who worked on improved macro handling recently.

**Comment by Duhemm** [comment] 2014-10-03 13:53
My first guess is that the set containing the list of original trees (trees before expansion, `inspectedOriginalTrees`) introduced in #1544 ends up consuming all the memory... What would be a better solution to the problem of cyclic structures in macro originals ?

**Comment by gkossakowski** [comment] 2014-10-03 13:59
I think the solution in #1544 was fine but we might have missed some small detail. @Duhemm, can you reproduce the problem on your machine?

**Comment by Duhemm** [comment] 2014-10-03 14:17
Actually I've not been able to reproduce the OOM on milessabin/shapeless. Are there other instructions than `compile`-ing the project with sbt 0.13.6 to reproduce it ?

You're right, I've been looking a little too fast at your message (I'm helping the students with their software engineering class at the moment) and you said it was located in `ExtractUsedNames.handleMacroExpansion`.

Do you think the `filter` in https://github.com/sbt/sbt/blob/0.13/compile/interface/src/main/scala/xsbt/ExtractUsedNames.scala#L64 is responsible for this problem ?

**Comment by gkossakowski** [comment] 2014-10-03 14:31
No, it should work out of the box. Are you sure you have the latest (master) shapeless checked out? I used 5ec04acd101367cbf3aba0b1a08973192b0e1de8 commit from shapeless. Apply

``` patch
diff --git a/project/build.properties b/project/build.properties
index be6c454..64abd37 100644
--- a/project/build.properties
+++ b/project/build.properties
@@ -1 +1 @@
-sbt.version=0.13.5
+sbt.version=0.13.6
```

then start sbt, type `compile`, wait for a while and observe sbt blowing up with OOME. Let me know if you can reproduce it.

**Comment by gkossakowski** [comment] 2014-10-03 14:40
Ah, I see now that #1544 was about extracting dependencies and here we are dealing with extraction of used names. I don't think the problem is with `filter`. Let me offer my wild guess. I think we are hitting unbounded recursion again. That is, we are walking the same tree nodes over and over again. However, instead of seeing StackOverflowException we see OOME because at each recursive call to `handleMacroExpansion` we add names to [`namesBuffer`](https://github.com/sbt/sbt/blob/0.13/compile/interface/src/main/scala/xsbt/ExtractUsedNames.scala#L51). We exhaust the heap memory before stack memory is exhausted.

I think if you just replicated your fix from #1544 and applied it to `ExtractUsedNames.scala` you would fix this problem.

**Comment by Duhemm** [comment] 2014-10-03 14:47
I had not remarked that name hashing was disabled, sorry. I can reproduce it now.

I'll take a look at this while on the train this evening, I'll keep you updated !

Thank you for the investigation :mag: !

**Comment by milessabin** [comment] 2014-10-03 17:51
Aside from this being an issue when compiling shapeless itself, I guess this is also going to be an issue for projects with a binary dependency on shapeless and using 0.13.6?

**Comment by gkossakowski** [comment] 2014-10-04 09:29
@milessabin, it depends on which macro is causing the problem. If it's a macro that is publicly exposed then most likely dependent projects will hit this issue too.

**Closed as completed** 2014-10-04 09:30 UTC
Labels: area/incremental_compiler

**Comment by milessabin** [comment] 2014-10-04 09:50
I think that's most likely the case. A release of shapeless 2.1.0 is going to happen within the next couple of weeks ... are you able to get a bug fix SBT release out in that timeframe? Otherwise I'm going to have to warn shapeless users to stick with 0.13.5 or set `incOptions := incOptions.value.withNameHashing(false)`.

**Comment by jsuereth** [comment] 2014-10-04 11:07
We should be able to make that happen.  We were going to issue an milestone release asap to check some of the ivy fixes before hitting rc.

**Comment by milessabin** [comment] 2014-10-04 11:11
Awesome :-)
