### ISSUE TITLE
1.3.4/1.3.5 regression: cannot bootstrap properly anymore

### ISSUE THREAD

**Issue by pshirshov** [sbt/sbt#5323] opened 2019-12-19 14:10 UTC
Hi,

I'm building docker images with sbt using this repo: `https://dl.bintray.com/sbt/debian`
Once I've upgraded to 1.3.5 I've noticed that sbt fails to execute any actions start on first invokation:

```
❯ docker run --rm -ti septimalmind/izumi-env:latest
root@79ff36785a09:/work# sbt -Dsbt.override.build.repos=true -Dsbt.log.noformat=true -verbose +clean
[process_args] java_version = '11'
[sbt_options] declare -a sbt_options=()
[copyRt] java9_rt = '/root/.sbt/0.13/java9-rt-ext-private_build_11_0_5/rt.jar'
Copying runtime jar.
# Executing command line:
java
-Dfile.encoding=UTF-8
-Dsbt.override.build.repos=true
-Dsbt.log.noformat=true
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-jar
/usr/share/sbt/bin/java9-rt-export.jar
/root/.sbt/0.13/java9-rt-ext-private_build_11_0_5/rt.jar

root@79ff36785a09:/work# sbt -Dsbt.override.build.repos=true -Dsbt.log.noformat=true -verbose +clean
[process_args] java_version = '11'
[sbt_options] declare -a sbt_options=()
[copyRt] java9_rt = '/root/.sbt/0.13/java9-rt-ext-private_build_11_0_5/rt.jar'
# Executing command line:
java
-Dfile.encoding=UTF-8
-Dsbt.override.build.repos=true
-Dsbt.log.noformat=true
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-Dscala.ext.dirs=/root/.sbt/0.13/java9-rt-ext-private_build_11_0_5
-jar
/usr/share/sbt/bin/sbt-launch.jar
+clean

[info] [launcher] getting org.scala-sbt sbt 1.3.5  (this may take some time)...
```

Look at commandline parameters of the first invokation: no args have been passed and it just exited after bootstrap!

```
root@8e5c68c4d7ad:/work# dpkg -s sbt
Package: sbt
Status: install ok installed
Priority: optional
Section: java
Installed-Size: 1403
Maintainer: Eugene Yokota <eugene.yokota@lightbend.com>
Architecture: all
Source: sbt
Version: 1.3.5
Depends: bash (>= 3.2)
Recommends: git
Description: sbt, the interactive build tool
 This script provides a native way to run sbt,
  a build tool for Scala and more.
```

UPD: I've rechecked, latest working version is 1.3.3

**Comment by eed3si9n** [comment] 2019-12-19 18:08
I think this is a duplicate of https://github.com/sbt/sbt/issues/5270

**Comment by pshirshov** [comment] 2019-12-19 20:47
Yup, seems like it is.  Though I doubt it is related to Ubuntu or a particular JDK version, especially considering the fact that it was working for literally years until 1.3.4 release. I didn't change anything in my setup apart of sbt version.

**Comment by eed3si9n** [comment] 2019-12-20 14:29
Yea. I don't fault Ubuntu/Debian here, but I wasn't able to reproduce it using Alpine image, so I am guessing there's some interaction between something in sbt and Ubuntu/Debian.

**Closed as completed by eed3si9n** 2019-12-20 14:29 UTC
