### ISSUE TITLE
NullPointerException while compiling

### ISSUE THREAD

**Issue by joan38** [sbt/sbt#3502] opened 2017-09-06 14:47 UTC
## steps and problem

```
> ~test:compile
...
[error] Error occurred obtaining files to watch.  Terminating continuous execution...
[error] java.lang.NullPointerException
[error] 	at sun.nio.fs.UnixPath.toUnixPath(UnixPath.java:198)
[error] 	at sun.nio.fs.UnixPath.resolve(UnixPath.java:397)
[error] 	at sun.nio.fs.UnixPath.resolve(UnixPath.java:43)
[error] 	at sbt.internal.io.SourceModificationWatch$.expandEvent(SourceModificationWatch.scala:70)
[error] 	at sbt.internal.io.SourceModificationWatch$.$anonfun$watch$1(SourceModificationWatch.scala:28)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error] 	at scala.collection.immutable.List.map(List.scala:295)
[error] 	at sbt.internal.io.SourceModificationWatch$.watch(SourceModificationWatch.scala:28)
[error] 	at sbt.Watched$.liftedTree1$1(Watched.scala:101)
[error] 	at sbt.Watched$.executeContinuously(Watched.scala:99)
[error] 	at sbt.BasicCommands$.$anonfun$continuous$2(BasicCommands.scala:215)
[error] 	at sbt.CommandUtil$.withAttribute(CommandUtil.scala:42)
[error] 	at sbt.BasicCommands$.$anonfun$continuous$1(BasicCommands.scala:213)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:125)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:228)
[error] 	at sbt.State$$anon$1.process(State.scala:234)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:98)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:104)
[error] 	at sbt.xMain.run(Main.scala:71)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NullPointerException
[error] Use 'last' for the full log.
```

## notes

sbt version: 1.0.1

**Comment by dwijnand** [comment] 2017-09-08 12:06
@joan38 Could you provide a minimised reproduction of the problem, please?

**Comment by rintcius** [comment] 2017-09-26 10:54
I hit the same problem after we upgraded to `sbt 1.0.2`. It may be a resource leak, triggered only for big projects (or after a long time of watching files), so may not be so easy to minimise this problem. 
You could try to reproduce by:

* cloning `https://github.com/quasar-analytics/quasar` 
* `./sbt` 
* in `sbt` console: `~ ;compile ;test:compile` (I ran into the NPE after I needed to recompile a lot of files, so it may make sense to just see what happens when running it in a clean env)

BTW **after** this exception - after retrying `~ ;compile ;test:compile` without stopping sbt - I got stacktraces like these which are probably more insightful (also my browser crashed, but surprisingly other apps kept running fine):

```
[error] Could not create file ..../target/streams/test/$global/$global/discoveredMainClasses/datajava.io.IOException: Too many open files
[error] 	at sbt.internal.io.ErrorHandling$.translate(ErrorHandling.scala:11)
[error] 	at sbt.io.IO$.touch(IO.scala:194)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.make(Streams.scala:171)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.getOutput(Streams.scala:138)
[error] 	at sbt.SessionVar$.$anonfun$persist$1(SessionVar.scala:30)
[error] 	at sbt.SessionVar$.$anonfun$persist$1$adapted(SessionVar.scala:30)
[error] 	at sbt.std.Streams.use(Streams.scala:99)
[error] 	at sbt.std.Streams.use$(Streams.scala:96)
[error] 	at sbt.std.Streams$$anon$3.use(Streams.scala:128)
[error] 	at sbt.SessionVar$.persist(SessionVar.scala:30)
[error] 	at sbt.SessionVar$.persistAndSet(SessionVar.scala:25)
[error] 	at sbt.Project$RichTaskSessionVar.$anonfun$storeAs$2(Project.scala:803)
[error] 	at sbt.SessionVar$.$anonfun$transform$2(SessionVar.scala:43)
[error] 	at scala.Function$.$anonfun$chain$2(Function.scala:24)
[error] 	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:56)
[error] 	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:64)
[error] 	at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:48)
[error] 	at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
[error] 	at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
[error] 	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error] 	at scala.Function$.$anonfun$chain$1(Function.scala:24)
[error] 	at sbt.EvaluateTask$.applyResults(EvaluateTask.scala:414)
[error] 	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:385)
[error] 	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:382)
[error] 	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:401)
[error] 	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:96)
[error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:327)
[error] 	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:94)
[error] 	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:107)
[error] 	at sbt.internal.Aggregation$.$anonfun$applyTasks$1(Aggregation.scala:64)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error] 	at sbt.internal.Aggregation$.$anonfun$evaluatingParser$11(Aggregation.scala:216)
[error] 	at sbt.internal.Act$.$anonfun$actParser0$3(Act.scala:310)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:227)
[error] 	at sbt.State$$anon$1.process(State.scala:233)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:98)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:104)
[error] 	at sbt.xMain.run(Main.scala:71)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.io.IOException: Too many open files
[error] 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
[error] 	at java.io.File.createNewFile(File.java:1012)
[error] 	at sbt.io.IO$.$anonfun$touch$3(IO.scala:194)
[error] 	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
[error] 	at sbt.internal.io.ErrorHandling$.translate(ErrorHandling.scala:10)
[error] 	at sbt.io.IO$.touch(IO.scala:194)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.make(Streams.scala:171)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.getOutput(Streams.scala:138)
[error] 	at sbt.SessionVar$.$anonfun$persist$1(SessionVar.scala:30)
[error] 	at sbt.SessionVar$.$anonfun$persist$1$adapted(SessionVar.scala:30)
[error] 	at sbt.std.Streams.use(Streams.scala:99)
[error] 	at sbt.std.Streams.use$(Streams.scala:96)
[error] 	at sbt.std.Streams$$anon$3.use(Streams.scala:128)
[error] 	at sbt.SessionVar$.persist(SessionVar.scala:30)
[error] 	at sbt.SessionVar$.persistAndSet(SessionVar.scala:25)
[error] 	at sbt.Project$RichTaskSessionVar.$anonfun$storeAs$2(Project.scala:803)
[error] 	at sbt.SessionVar$.$anonfun$transform$2(SessionVar.scala:43)
[error] 	at scala.Function$.$anonfun$chain$2(Function.scala:24)
[error] 	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:56)
[error] 	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:64)
[error] 	at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:48)
[error] 	at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
[error] 	at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
[error] 	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error] 	at scala.Function$.$anonfun$chain$1(Function.scala:24)
[error] 	at sbt.EvaluateTask$.applyResults(EvaluateTask.scala:414)
[error] 	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:385)
[error] 	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:382)
[error] 	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:401)
[error] 	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:96)
[error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:327)
[error] 	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:94)
[error] 	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:107)
[error] 	at sbt.internal.Aggregation$.$anonfun$applyTasks$1(Aggregation.scala:64)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error] 	at sbt.internal.Aggregation$.$anonfun$evaluatingParser$11(Aggregation.scala:216)
[error] 	at sbt.internal.Act$.$anonfun$actParser0$3(Act.scala:310)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:227)
[error] 	at sbt.State$$anon$1.process(State.scala:233)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:98)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:104)
[error] 	at sbt.xMain.run(Main.scala:71)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)

```

**Comment by djspiewak** [comment] 2017-09-26 15:26
@dwijnand Is it possible this is being caused by SBT attempting to get file monitor handles on every source file in the project?  Quasar is a particularly large project, and I wouldn't be surprised if it were pushing some of the limits in that regard.

**Comment by djspiewak** [comment] 2017-09-26 15:51
A bit of internal testing has confirmed that this bug was introduced with SBT 1.0.1.  It is not present on SBT 1.0.0.

**Comment by dwijnand** [comment] 2017-09-26 15:53
I don't have anything to disprove that possibility. Maybe @Duhemm, who changed the file watching in sbt 1, could answer better than me (if he has any spare cycles).

WRT 1.0.1, https://github.com/sbt/sbt/pull/3438 and https://github.com/sbt/sbt/pull/3439 are two PRs that we shipped in sbt 1.0.1 to do with source watching.

**Comment by djspiewak** [comment] 2017-09-26 15:59
Looks like quasar has `sourcesInBase` set to `true` (relevant to [this line](https://github.com/sbt/sbt/pull/3439/files#diff-6373e7f7122325e753b75fe1cc76ff5fR320)), which is interesting because I don't believe we've actually configured that setting, so I'm guessing that SBT is just defaulting it.  If I understand things correctly, this means that SBT 1.0.[1,2] is now doubling up on watching all project sources?

**Comment by djspiewak** [comment] 2017-09-26 22:20
As a sidebar, it's possible to generate this failure even without using `~`.  Or at least, you can get it out of things that are not using file monitors after having previously used `~`.

**Comment by jrudolph** [comment] 2017-10-30 10:46
Happened for me on the first run of the sbt 1.0 akka-http build.

**Comment by DylanArnold** [comment] 2017-11-08 21:35
I just got the same `NullPointerException` and original stacktrace when running `~compile` with `1.0.2` on a large codebase. I've compiled for a couple of days without getting this error.

**Comment by eed3si9n** [comment] 2019-09-30 21:20
watch has been reimplemented in sbt 1.3.x, so I am closing this preemptively.

**Closed as completed by eed3si9n** 2019-09-30 21:20 UTC
Labels: Needs Reproduction Test Case, area/watch
