### ISSUE TITLE
Latest zinc + sbt setting "-Ypickle-write" when pipelining is off

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#5730] opened 2020-08-08 03:15 UTC
## steps

* publish zinc 1.4.0-SNAPSHOT from origin/develop
* set zinc version to 1.4.0-SNAPSHOT in sbt project/Dependencies.scala
* publish sbt 1.4.0-SNAPSHOT
* clone https://github.com/ikryvorotenko/sbt-junit-sample
* run `sbt -Dsbt.version=1.4.0-SNAPSHOT clean;compile` in the above project (which uses scala 2.12.7)

## problem
```
[info] welcome to sbt 1.4.0-SNAPSHOT (Azul Systems, Inc. Java 1.8.0_252)                                                                
[info] loading project definition from sbt-junit-sample/project                               
[info] loading settings for project root from build.sbt ...         
[info] set current project to Scala Seed Project (in build file:sbt-junit-sample/)            
[success] Total time: 0 s, completed Aug 7, 2020 8:11:24 PM         
[info] Compiling 1 Scala source to sbt-junit-sample/target/scala-2.12/classes ...             
[error] bad option: '-Ypickle-write'                                
[error] Compilation failed  
```
## expectation
-Ypickle-write not be set
## notes
I ran `show Compile / scalacOptions` and they were empty. I also ran `show Compile / incOptions` and `pipelining: false` was set. Looking briefly at the zinc code, it seemed as though if pipelining was off, then zinc wouldn't append `-Ypickle-write` so I'm not sure if the issue is in sbt or zinc.

**Comment by eed3si9n** [comment] 2020-08-08 04:38
It's a sort of duplicate of "Let the build tools configure -Ypickle-write flag" - https://github.com/sbt/zinc/pull/862

A bit of a history on this is:
1. In https://github.com/sbt/zinc/pull/821 @dwijnand added -Ypickle-write flag whenever early output is specified.
2. 12 days ago @eed3si9n removed flag adding code entirely in https://github.com/sbt/zinc/pull/855 and self-merged.
3. In sbt/sbt pipelining support https://github.com/sbt/sbt/pull/5703, Eugene started configuring early output regardless of `ThisBuild / usePipelining` value.
4. Dale reverted flag removal commit in https://github.com/sbt/zinc/pull/860.
5. Eugene resent flag removal in https://github.com/sbt/zinc/pull/862 to give the scalacOptions flag control back to the build users.

Currently the situation is a bit in flux, but hopefully we will settle on one solution or the other and this would eventually be fixed, I think.

**Comment by eed3si9n** [comment] 2020-10-02 01:49
I think this can be closed now.

**Closed as completed by eed3si9n** 2020-10-02 01:49 UTC
