### ISSUE TITLE
Removing override breaks compilation

### ISSUE THREAD

**Issue by NeQuissimus** [sbt/sbt#3579] opened 2017-09-25 18:21 UTC
I have a ScalaTest suite trait that is customized to include a few traits.
In some of my tests, I override `beforeAll`, in others I do not.
I just removed a `beforeAll` implementation from a test suite and noticed a strange error.

Luckily, I have been able to minimize the bug quite a bit.

**build.sbt**
```scala
import sbt._
import sbt.Keys._

scalaVersion in ThisBuild := "2.12.3"

libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.1" % Test
```

**project/build.properties**

```
sbt.version=1.0.2
```

**src/test/scala/Suite.scala**

```scala
import org.scalatest._

trait TestSuite extends WordSpec with BeforeAndAfterAll {
  override def beforeAll: Unit = { super.beforeAll(); println("bar") }
}
```

**src/test/scala/SbtBug.scala**

```scala
import org.scalatest._

class SbtBugSpec extends TestSuite {
 override def beforeAll: Unit = { super.beforeAll(); println("foo") } // Comment this line in and out

  "This Spec" should {
    "just run" in {
      println("gogogo")
    }
  }
}
```

In `SbtBugSpec` there is the line with `beforeAll`.

- Run `sbt test`, everything is fine
- Toggle comment on `beforeAll` line
- Run `sbt test`, error as below
- Run `sbt clean test`, works fine

A few things I noticed:

- The bug only occurs when the `TestSuite` trait and the implementing `SbtBugSpec` are in separate files
- Toggling the comment works both way: "Comment out, build, add back, build" will fail as much as "Add override, build, comment out, build"

**Here is the error:**

<details>
<summary>Click to expand</summary>
<pre>
[error] java.lang.AssertionError: assertion failed: Modified names for SbtBugSpec is empty
[error]         at scala.Predef$.assert(Predef.scala:219)
[error]         at sbt.internal.inc.NamesChange.<init>(Changes.scala:54)
[error]         at sbt.internal.inc.IncrementalNameHashing.sameAPI(IncrementalNameHashing.scala:46)
[error]         at sbt.internal.inc.IncrementalCommon.sameClass(IncrementalCommon.scala:205)
[error]         at sbt.internal.inc.IncrementalCommon.$anonfun$changedIncremental$1(IncrementalCommon.scala:187)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error]         at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error]         at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error]         at sbt.internal.inc.IncrementalCommon.changedIncremental(IncrementalCommon.scala:186)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:76)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error]         at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error]         at sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error]         at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:70)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1403)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1385)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:266)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (test:compileIncremental) java.lang.AssertionError: assertion failed: Modified names for SbtBugSpec is empty
[error] Total time: 3 s, completed 25-Sep-2017 2:14:38 PM
</pre>
</details>

**Comment by dwijnand** [comment] 2017-09-26 13:10
Hey @NeQuissimus, thanks for the great minimisation. Unless I'm mistaken, I think this is a duplicate of https://github.com/sbt/zinc/issues/292, so I'm closing this in favour of that, notifying that issue of your minimisation.

**Closed as completed by dwijnand** 2017-09-26 13:10 UTC

**Comment by NeQuissimus** [comment] 2017-09-26 13:17
Oh, yes, looks like it. I had not searched across repos :) Will watch for progress there.
