### ISSUE TITLE
Exception after upgrade to Play 2.2.6

### ISSUE THREAD

**Issue by richdougherty** [sbt/sbt#1739] opened 2014-11-20 00:26 UTC
An error has been reported on the mailing list. @jsuereth asked me to report it here.

https://groups.google.com/d/msg/play-framework/7uNX_ImTW08/y82aICqggaIJ

These are the changes in Play 2.2.6. There shouldn't be anything sbt related.

https://github.com/playframework/playframework/compare/2.2.5...2.2.6

**Comment by mslinn** [comment] 2014-11-20 00:30
Last did not give a longer stack trace. This is all I could get.

```
java.lang.UnsupportedOperationException: Position.start on class scala.reflect.internal.util.OffsetPosition
    at scala.reflect.internal.util.Position.start(Position.scala:114)
    at sbt.internals.parser.SbtParser.sbt$internals$parser$SbtParser$$convertStatement$1(SbtParser.scala:142)
    at sbt.internals.parser.SbtParser$$anonfun$4.apply(SbtParser.scala:147)
    at sbt.internals.parser.SbtParser$$anonfun$4.apply(SbtParser.scala:147)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
    at sbt.internals.parser.SbtParser.splitExpressions(SbtParser.scala:147)
    at sbt.internals.parser.SbtParser.<init>(SbtParser.scala:60)
    at sbt.EvaluateConfigurations$.splitExpressions(EvaluateConfigurations.scala:227)
    at sbt.EvaluateConfigurations$.parseConfiguration(EvaluateConfigurations.scala:69)
    at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:107)
    at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:710)
    at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:715)
    at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:714)
    at scala.Option.getOrElse(Option.scala:120)
    at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:714)
    at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:721)
    at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:721)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at sbt.Load$.loadFiles$1(Load.scala:721)
    at sbt.Load$.discoverProjects(Load.scala:732)
    at sbt.Load$.discover$1(Load.scala:545)
    at sbt.Load$.loadTransitive(Load.scala:574)
    at sbt.Load$.loadProjects$1(Load.scala:442)
    at sbt.Load$.loadUnit(Load.scala:446)
    at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
    at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
    at sbt.BuildLoader.apply(BuildLoader.scala:140)
    at sbt.Load$.loadAll(Load.scala:334)
    at sbt.Load$.loadURI(Load.scala:289)
    at sbt.Load$.load(Load.scala:285)
    at sbt.Load$.load(Load.scala:276)
    at sbt.Load$.apply(Load.scala:130)
    at sbt.GlobalPlugin$.build(GlobalPlugin.scala:33)
    at sbt.GlobalPlugin$.load(GlobalPlugin.scala:39)
    at sbt.Load$.loadGlobal(Load.scala:88)
    at sbt.Load$.defaultWithGlobal(Load.scala:63)
    at sbt.Load$.defaultLoad(Load.scala:34)
    at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    at sbt.Command$.process(Command.scala:92)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.State$$anon$1.process(State.scala:184)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.MainLoop$.next(MainLoop.scala:98)
    at sbt.MainLoop$.run(MainLoop.scala:91)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
    at sbt.Using.apply(Using.scala:24)
    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
    at sbt.MainLoop$.runLogged(MainLoop.scala:24)
    at sbt.StandardMain$.runManaged(Main.scala:53)
    at sbt.xMain.run(Main.scala:28)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
    at xsbt.boot.Launch$.run(Launch.scala:57)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
    at xsbt.boot.Launch$.launch(Launch.scala:65)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Boot$.runImpl(Boot.scala:32)
    at xsbt.boot.Boot$.main(Boot.scala:21)
    at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.UnsupportedOperationException: Position.start on class scala.reflect.internal.util.OffsetPosition
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

**Comment by retronym** [comment] 2014-11-20 00:39
Could you please provide the `.sbt` files in the project and home directory? One of these is tripping up the new `.sbt` file parser in SBT introduced in #1606. See also #1666

**Comment by retronym** [comment] 2014-11-20 00:41
Something like https://github.com/retronym/xsbt/compare/ticket/1739 should fix this, but it will be important to get a test case to validate this.

**Comment by mslinn** [comment] 2014-11-20 00:54
Jason, I sent files to your gmail account.

Thanks,

Mike

**Comment by retronym** [comment] 2014-11-20 01:07
As a workaround, you can pass `-Dsbt.parser.simple=true` to your play/SBT command line. This will revert to the old `.sbt` parser that splits based on `\n\n`.

**Comment by retronym** [comment] 2014-11-20 01:54
I was not able to reproduce the problem. I tried `sbt 0.13.{6,7-M3,7}`. Only the latter two tags contain the `SbtParser` class that is the home of the bug.

@mslinn Could you please try to whittle down your `.sbt` files line-by-line so as to find out which part is to blame? This will really help us to write a test case for this bug.

**Comment by mslinn** [comment] 2014-11-20 02:12
I'm working towards a deadline, it is a long march. I don't expect to be able to do this for some time.

Sorry, Mike

**Comment by mslinn** [comment] 2014-11-20 03:03
Probably not surprising, but switching back to SBT 0.11.6 made the problem go away

**Comment by retronym** [comment] 2014-11-20 03:37
Good luck on the march!

Does the suggested workaround help?

I can't imagine it would take more ten minutes to remove the lines of your build definition one by one, to see when you transition from "java.lang.UnsupportedOperationException" to _either_ a successful load of the project or some other error in the build. The latter would indicate that it got past parsing.

So if you need a break from marching, we'd really appreciate that.

**Comment by retronym** [comment] 2014-11-20 03:38
> Probably not surprising, but switching back to SBT 0.11.6 made the problem go away

The project you sent me privately contained a build.properties that was set to SBT 0.11.6. That confused my a little. Are you certain you sent me the right project?

**Comment by mslinn** [comment] 2014-11-20 22:46
I made a new project on the same machine. `build.sbt` is empty. `~/.sbt` has been renamed

```
$ ls -alF
total 12
drwxr--r-x  3 mslinn mslinn 4096 Nov 20 14:39 ./
drwxrw-r-x 13 mslinn mslinn 4096 Nov 20 14:26 ../
-rw-rw-r--  1 mslinn mslinn    0 Nov 20 14:39 build.sbt
drwxrw-r-x  3 mslinn mslinn 4096 Nov 20 14:38 project/

$ ls -alF project/
total 20
drwxrw-r-x 3 mslinn mslinn 4096 Nov 20 14:38 ./
drwxr--r-x 3 mslinn mslinn 4096 Nov 20 14:39 ../
-rw-rw-r-- 1 mslinn mslinn   19 Nov 20 14:32 build.properties
-rw-rw-r-- 1 mslinn mslinn   59 Nov 20 14:34 plugins.sbt

$ cat project/build.properties 
sbt.version=0.13.7

$ cat project/plugins.sbt 
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.2.6")
```

There are no other files in the project. This still causes the same stack dump as before:

```
/opt/play-2.2.6/play update
```

Perhaps an environment variable is the problem, or another package installed on the system (XUbuntu 14.10)?

**Comment by retronym** [comment] 2014-11-21 01:07
> Perhaps an environment variable is the problem, 

I can see the problem now. The `play` script in version 2.2.6 forces SBT 0.13.7 to using Scala 2.10.3 internally, rather the supported version, 2.10.4.

I was running `sbt` directly, which did not suffer from this problem.

A workaround is to use:

```
SBT_SCALA_VERSION=2.10.4 ~/usr/play-2.2.6/play update
```

It seems the new `SbtParser` relies on a bug fix in Scala 2.10.4.

@richdougherty I'm going to close this issue and let you find a solution on the `play` side. You can either bump to 2.10.4, or, if there is some other reason that doesn't work in Play, add `-Dsbt.parser.simple=true` to the Java command line of the SBT process.

**Closed as completed by retronym** 2014-11-21 01:07 UTC

**Comment by mslinn** [comment] 2014-11-21 01:11
Both workarounds work.

Now I can brag about having written the smallest possible Play 2.2.6 app :)
Whoohoo!

**Comment by retronym** [comment] 2014-11-21 01:16
:smile:

**Comment by richdougherty** [comment] 2014-11-21 01:50
FYI Play 2.2.6 ships with sbt 0.13.0. It's good to know there's a workaround if users use a higher version of sbt.

**Comment by infomofo** [comment] 2015-06-01 16:14
They just released Play 2.4.0. I'm upgrading from Play 2.3.8. 

Part of the upgrade guide says to update sbt. In upgrading from 0.13.5 to 0.13.8 I started encountering this same stack trace.  It is not happening on my development box but it is happening on my integration test environment (CircleCI).  I am using scalaVersion  2.11.6.

During the "play update" step of the build it will attempt to download a lot of dependencies and eventually gives this stack trace.

```
[SUCCESSFUL ] org.scala-sbt#apply-macro;0.13.8!apply-macro.jar (327ms)
:: retrieving :: org.scala-sbt#boot-app
    confs: [default]
    52 artifacts copied, 0 already retrieved (17674kB/98ms)
java.lang.UnsupportedOperationException: Position.start on class scala.reflect.internal.util.OffsetPosition
    at scala.reflect.internal.util.Position.start(Position.scala:114)
    at sbt.internals.parser.SbtParser.sbt$internals$parser$SbtParser$$convertStatement$1(SbtParser.scala:148)
    at sbt.internals.parser.SbtParser$$anonfun$4.apply(SbtParser.scala:153)
    at sbt.internals.parser.SbtParser$$anonfun$4.apply(SbtParser.scala:153)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
    at sbt.internals.parser.SbtParser.splitExpressions(SbtParser.scala:153)
    at sbt.internals.parser.SbtParser.<init>(SbtParser.scala:58)
    at sbt.EvaluateConfigurations$.splitExpressions(EvaluateConfigurations.scala:226)
    at sbt.EvaluateConfigurations$.parseConfiguration(EvaluateConfigurations.scala:69)
    at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:106)
    at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:712)
    at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:717)
    at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:716)
    at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
    at scala.collection.AbstractMap.getOrElse(Map.scala:58)
    at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:716)
    at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:723)
    at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:723)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at sbt.Load$.loadFiles$1(Load.scala:723)
    at sbt.Load$.discoverProjects(Load.scala:734)
    at sbt.Load$.discover$1(Load.scala:545)
    at sbt.Load$.loadTransitive(Load.scala:574)
    at sbt.Load$.loadProjects$1(Load.scala:442)
    at sbt.Load$.loadUnit(Load.scala:446)
    at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
    at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
    at sbt.BuildLoader.apply(BuildLoader.scala:140)
    at sbt.Load$.loadAll(Load.scala:334)
    at sbt.Load$.loadURI(Load.scala:289)
    at sbt.Load$.load(Load.scala:285)
    at sbt.Load$.load(Load.scala:276)
    at sbt.Load$.apply(Load.scala:130)
    at sbt.Load$.buildPluginDefinition(Load.scala:821)
    at sbt.Load$.buildPlugins(Load.scala:787)
    at sbt.Load$.plugins(Load.scala:775)
    at sbt.Load$.loadUnit(Load.scala:431)
    at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
    at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
    at sbt.BuildLoader.apply(BuildLoader.scala:140)
    at sbt.Load$.loadAll(Load.scala:334)
    at sbt.Load$.loadURI(Load.scala:289)
    at sbt.Load$.load(Load.scala:285)
    at sbt.Load$.load(Load.scala:276)
    at sbt.Load$.apply(Load.scala:130)
    at sbt.Load$.defaultLoad(Load.scala:36)
    at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    at sbt.Command$.process(Command.scala:92)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.State$$anon$1.process(State.scala:184)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.MainLoop$.next(MainLoop.scala:98)
    at sbt.MainLoop$.run(MainLoop.scala:91)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
    at sbt.Using.apply(Using.scala:24)
    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
    at sbt.MainLoop$.runLogged(MainLoop.scala:24)
    at sbt.StandardMain$.runManaged(Main.scala:53)
    at sbt.xMain.run(Main.scala:28)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
    at xsbt.boot.Launch$.run(Launch.scala:57)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
    at xsbt.boot.Launch$.launch(Launch.scala:65)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Boot$.runImpl(Boot.scala:32)
    at xsbt.boot.Boot$.main(Boot.scala:21)
    at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.UnsupportedOperationException: Position.start on class scala.reflect.internal.util.OffsetPosition
[error] Use 'last' for the full log.
```

**Comment by ckaeslin** [comment] 2015-06-02 22:56
I was facing the same problem on circle ci. I solved it by overriding dependencies and test by using sbt instead of the default circle ci commands.

```
machine:
  java:
    version: oraclejdk8
dependencies:
  pre:
    - wget -q https://dl.bintray.com/sbt/debian/sbt-0.13.8.deb
    - sudo dpkg -i sbt-0.13.8.deb
  override:
    - sbt compile
cache_directories:
    - "~/.ivy2"
    - "~/.sbt"

test:
  override:
    - sbt test
```

**Comment by the21st** [comment] 2015-06-17 13:58
@ckaeslin thanks, that helped a lot! I have been having the same issues in Circle CI. Just a minor thing: you are missing the two-space indentation before `cache_directories:`

**Comment by DavidPerezIngeniero** [comment] 2015-06-30 07:11
I observing exactly this bug in a SBT app that doesn't use Play, but SBT 0.13.8.

In many Ubuntu and Mac machines it works ok, but in a Fedora machine it crashes.

I'm using the SBT launcher.

**Comment by DavidPerezIngeniero** [comment] 2015-06-30 07:39
Solution: rename `~/.sbt` directory.

**Comment by DavidPerezIngeniero** [comment] 2015-06-30 07:43
It looks like that `yum install sbt` is harmful.

**Comment by matanox** [comment] 2015-10-09 10:36
I am getting what appears to be the same error, when compiling the 0.13.9 branch of sbt itself. I can't blame anything as it only happens when my compiler plugin is wired in, but what might be your advice?

The line of code in my plugin, which triggers it, is `val start  = symbol.pos.start`

Can you please advice?

```
[error] uncaught exception during compilation: java.lang.UnsupportedOperationException
java.lang.UnsupportedOperationException: Position.start on class scala.reflect.internal.util.OffsetPosition
    at scala.reflect.internal.util.Position.start(Position.scala:114)
    at extractor.plugin.SourceExtract$.apply(SourceExtract.scala:85)
    at extractor.plugin.Nodes$.apply(Model.scala:24)
    at extractor.plugin.TraversalExtraction$ExtractionTraversal$1.traverse(TraversalExtraction.scala:146)
    at extractor.plugin.TraversalExtraction$ExtractionTraversal$1$$anonfun$traverse$7.apply(TraversalExtraction.scala:181)
    at extractor.plugin.TraversalExtraction$ExtractionTraversal$1$$anonfun$traverse$7.apply(TraversalExtraction.scala:181)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at extractor.plugin.TraversalExtraction$ExtractionTraversal$1.traverse(TraversalExtraction.scala:181)
    at extractor.plugin.TraversalExtraction$ExtractionTraversal$1.traverse(TraversalExtraction.scala:72)
    at scala.reflect.internal.Trees$$anonfun$itraverse$2.apply$mcV$sp(Trees.scala:1107)
    at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2849)
    at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1106)
    at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2825)
    at extractor.plugin.TraversalExtraction$ExtractionTraversal$1.traverse(TraversalExtraction.scala:184)
    at extractor.plugin.TraversalExtraction$ExtractionTraversal$1.traverse(TraversalExtraction.scala:72)
    at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2829)
    at scala.reflect.internal.Trees$$anonfun$itraverse$1.apply$mcV$sp(Trees.scala:1103)
    at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2849)
    at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1102)
    at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2825)
    at extractor.plugin.TraversalExtraction$ExtractionTraversal$1.traverse(TraversalExtraction.scala:184)
    at extractor.plugin.TraversalExtraction$.apply(TraversalExtraction.scala:191)
    at extractor.plugin.TraversalExtractionWriter$.apply(TraversalExtraction.scala:17)
    at extractor.plugin.PluginPhase$$anon$1$$anonfun$run$1.apply(PluginPhase.scala:35)
    at extractor.plugin.PluginPhase$$anon$1$$anonfun$run$1.apply(PluginPhase.scala:32)
    at scala.collection.immutable.Stream.foreach(Stream.scala:547)
    at extractor.plugin.PluginPhase$$anon$1.run(PluginPhase.scala:32)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
    at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
    at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:51)
    at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
    at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
    at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:75)
    at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:50)
    at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:65)
    at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
    at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
    at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
    at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
    at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
    at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
    at sbt.inc.Incremental$.compile(Incremental.scala:61)
    at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
    at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
    at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
    at sbt.Compiler$.compile(Compiler.scala:128)
    at sbt.Compiler$.compile(Compiler.scala:114)
    at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:829)
    at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:820)
    at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:818)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (testingProj/compile:compileIncremental) java.lang.UnsupportedOperationException: Position.start on class scala.reflect.internal.util.OffsetPosition
```

I use sbt 0.13.9 to build itself as seen in the `sbt about` output below, a little puzzling but somehow that branch seems to come with version 0.13.9 specified in its `build.properties` file, so I could only guess this is the way it is supposed to be.

```
> about
[info] This is sbt 0.13.9
[info] The current project is {file:......./test-projects/sbt/}sbtRoot 1.0.0-SNAPSHOT
[info] The current project is built against Scala 2.10.5
[info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, sbt.plugins.JUnitXmlReportPlugin, com.typesafe.sbteclipse.plugin.EclipsePlugin, com.hanhuy.sbt.keypath.KeyPathPlugin, canve.sbt.ExtractorSbtPlugin, com.typesafe.sbt.JavaVersionCheckPlugin, sbtdoge.DogePlugin, bintray.BintrayPlugin, StatusPlugin, NightlyPlugin, SbtLauncherPlugin, org.sbtidea.SbtIdeaPlugin, com.typesafe.sbt.SbtSite, com.typesafe.sbt.SbtGhPages, com.typesafe.sbt.SbtGit, com.typesafe.sbt.SbtScalariform
[info] sbt, sbt plugins, and build definitions are using Scala 2.10.5
```

```
$ java -version
java version "1.8.0_60"
```

```
$javac -version
javac 1.7.0_80
```

As much as it matters I get the same error compiling the `1.0.x` branch of sbt.

Many thanks!!
