### ISSUE TITLE
Corrupt Ivy Cache Works Online

### ISSUE THREAD

**Issue by jamesward** [sbt/sbt#733] opened 2013-04-18 00:56 UTC
Using this project as an example: https://github.com/jamesward/play-as-a-toolkit

I am connected to the internet and I run: `sbt clean compile`

Everything works fine.

Then I disconnect from the internet and run: `sbt clean compile`

The build fails with `UNRESOLVED DEPENDENCIES`:

```
jamesw@T430s:~/projects/play-as-a-toolkit(master)$ sbt clean compile
[info] Loading project definition from /home/jamesw/projects/play-as-a-toolkit/project
[info] Set current project to play-as-a-toolkit (in build file:/home/jamesw/projects/play-as-a-toolkit/)
[success] Total time: 0 s, completed Apr 17, 2013 6:51:21 PM
[info] Updating {file:/home/jamesw/projects/play-as-a-toolkit/}default-2d6dca...
[info] Resolving org.scala-lang#scala-library;2.10.1 ...
[info] Resolving play#play_2.10;2.1.1 ...
[info] Resolving play#sbt-link;2.1.1 ...
[info] Resolving org.javassist#javassist;3.16.1-GA ...
[info] Resolving play#play-exceptions;2.1.1 ...
[info] Resolving play#templates_2.10;2.1.1 ...
[info] Resolving com.github.scala-incubator.io#scala-io-file_2.10;0.4.2 ...
[info] Resolving com.github.scala-incubator.io#scala-io-core_2.10;0.4.2 ...
[info] Resolving com.jsuereth#scala-arm_2.10;1.3 ...
[info] Resolving play#play-iteratees_2.10;2.1.1 ...
[info] Resolving org.scala-stm#scala-stm_2.10.0;0.6 ...
[info] Resolving com.typesafe#config;1.0.0 ...
[info] Resolving io.netty#netty;3.6.3.Final ...
[info] Resolving org.slf4j#slf4j-api;1.6.6 ...
[info] Resolving org.slf4j#jul-to-slf4j;1.6.6 ...
[info] Resolving org.slf4j#jcl-over-slf4j;1.6.6 ...
[info] Resolving ch.qos.logback#logback-core;1.0.7 ...
[info] Resolving ch.qos.logback#logback-classic;1.0.7 ...
[info] Resolving com.typesafe.akka#akka-actor_2.10;2.1.0 ...
[info] Resolving com.typesafe.akka#akka-slf4j_2.10;2.1.0 ...
[info] Resolving joda-time#joda-time;2.1 ...
[warn] Host repo.typesafe.com not found. url=http://repo.typesafe.com/typesafe/releases/joda-time/joda-time/2.1/joda-time-2.1.pom
[info] You probably access the destination server through a proxy server that is not well configured.
[warn] Host repo1.maven.org not found. url=http://repo1.maven.org/maven2/joda-time/joda-time/2.1/joda-time-2.1.pom
[info] You probably access the destination server through a proxy server that is not well configured.
[warn]  module not found: joda-time#joda-time;2.1
[warn] ==== local: tried
[warn]   /home/jamesw/.ivy2/local/joda-time/joda-time/2.1/ivys/ivy.xml
[warn] ==== Typesafe Repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/joda-time/joda-time/2.1/joda-time-2.1.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/joda-time/joda-time/2.1/joda-time-2.1.pom
[info] Resolving org.joda#joda-convert;1.2 ...
[info] Resolving org.apache.commons#commons-lang3;3.1 ...
[info] Resolving com.ning#async-http-client;1.7.6 ...
[info] Resolving oauth.signpost#signpost-core;1.2.1.2 ...
[info] Resolving commons-codec#commons-codec;1.3 ...
[info] Resolving oauth.signpost#signpost-commonshttp4;1.2.1.2 ...
[info] Resolving org.apache.httpcomponents#httpcore;4.0.1 ...
[info] Resolving org.apache.httpcomponents#httpclient;4.0.1 ...
[info] Resolving commons-logging#commons-logging;1.1.1 ...
[warn] Host repo.typesafe.com not found. url=http://repo.typesafe.com/typesafe/releases/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
[info] You probably access the destination server through a proxy server that is not well configured.
[warn] Host repo1.maven.org not found. url=http://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
[info] You probably access the destination server through a proxy server that is not well configured.
[warn]  module not found: commons-logging#commons-logging;1.1.1
[warn] ==== local: tried
[warn]   /home/jamesw/.ivy2/local/commons-logging/commons-logging/1.1.1/ivys/ivy.xml
[warn] ==== Typesafe Repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
[info] Resolving org.codehaus.jackson#jackson-core-asl;1.9.10 ...
[info] Resolving org.codehaus.jackson#jackson-mapper-asl;1.9.10 ...
[info] Resolving net.sf.ehcache#ehcache-core;2.6.0 ...
[info] Resolving javax.transaction#jta;1.1 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.0 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: joda-time#joda-time;2.1: not found
[warn]  :: commons-logging#commons-logging;1.1.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[error] {file:/home/jamesw/projects/play-as-a-toolkit/}default-2d6dca/*:update: sbt.ResolveException: unresolved dependency: joda-time#joda-time;2.1: not found
[error] unresolved dependency: commons-logging#commons-logging;1.1.1: not found
[error] Total time: 2 s, completed Apr 17, 2013 6:51:23 PM
```

If a build works online and then the only thing that changes is I go offline, the build should still work.

**Comment by harrah** [comment] 2013-04-19 17:29
Could not reproduce in initial attempt with 0.12.3.

**Comment by jamesward** [comment] 2013-04-19 19:04
Let me clear my ivy cache and try again.

**Comment by jamesward** [comment] 2013-04-19 19:10
Cleared my ivy cache and it worked this time.  Usually when I have ivy issues in SBT clearing the cache fixes the problem.  But why does the cache get screwed up?  Reproducing that issue is gonna be tough.

**Comment by jamesward** [comment] 2013-04-19 19:10
And why would a corrupt ivy cache work online but not offline?

**Comment by jamesward** [comment] 2013-04-19 19:26
Here is the `ivy-2.1.xml` from the ivy cache that didn't work offline:

```
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0">
        <info organisation="joda-time"
                module="joda-time"
                revision="2.1"
                status="release"
                publication="20130208022336"
                default="true"
        />
        <configurations>
                <conf name="default" visibility="public"/>
        </configurations>
        <publications>
                <artifact name="joda-time" type="jar" ext="jar" conf="default"/>
        </publications>
</ivy-module>
```

Here is the `ivy-2.1.xml` from the ivy cache that does work offline:

```
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0" xmlns:m="http://ant.apache.org/ivy/maven">
    <info organisation="joda-time"
        module="joda-time"
        revision="2.1"
        status="release"
        publication="20120222092242"
    >
        <license name="Apache 2" url="http://www.apache.org/licenses/LICENSE-2.0.txt" />
        <description homepage="http://joda-time.sourceforge.net">
        Date and time library to replace JDK date handling
        </description>
        <m:properties__project.build.sourceEncoding>UTF-8</m:properties__project.build.sourceEncoding>
        <m:maven.plugins>org.apache.maven.plugins__maven-clean-plugin__2.4.1|org.apache.maven.plugins__maven-compiler-plugin__2.3.2|null__maven-antrun-plugin__1.7|org.apache.maven.plugins__maven-surefire-plugin__2.12|org.apache.maven.plugins__maven-jar-plugin__2.4|org.apache.maven.plugins__maven-javadoc-plugin__2.8.1|org.apache.maven.plugins__maven-source-plugin__2.1.2|org.apache.maven.plugins__maven-site-plugin__2.3|org.apache.maven.plugins__maven-repository-plugin__2.3.1|org.apache.maven.plugins__maven-assembly-plugin__2.3|org.codehaus.mojo__clirr-maven-plugin__2.3</m:maven.plugins>
    </info>
    <configurations>
        <conf name="default" visibility="public" description="runtime dependencies and master artifact can be used with this conf" extends="runtime,master"/>
        <conf name="master" visibility="public" description="contains only the artifact published by this module itself, with no transitive dependencies"/>
        <conf name="compile" visibility="public" description="this is the default scope, used if none is specified. Compile dependencies are available in all classpaths."/>
        <conf name="provided" visibility="public" description="this is much like compile, but indicates you expect the JDK or a container to provide it. It is only available on the compilation classpath, and is not transitive."/>
        <conf name="runtime" visibility="public" description="this scope indicates that the dependency is not required for compilation, but is for execution. It is in the runtime and test classpaths, but not the compile classpath." extends="compile"/>
        <conf name="test" visibility="private" description="this scope indicates that the dependency is not required for normal use of the application, and is only available for the test compilation and execution phases." extends="runtime"/>
        <conf name="system" visibility="public" description="this scope is similar to provided except that you have to provide the JAR which contains it explicitly. The artifact is always available and is not looked up in a repository."/>
        <conf name="sources" visibility="public" description="this configuration contains the source artifact of this module, if any."/>
        <conf name="javadoc" visibility="public" description="this configuration contains the javadoc artifact of this module, if any."/>
        <conf name="optional" visibility="public" description="contains all optional dependencies"/>
    </configurations>
    <publications>
        <artifact name="joda-time" type="jar" ext="jar" conf="master"/>
    </publications>
    <dependencies>
        <dependency org="org.joda" name="joda-convert" rev="1.2" force="true" conf="optional->compile(*),master(*)"/>
        <dependency org="junit" name="junit" rev="3.8.2" force="true" conf="test->runtime(*),master(*)"/>
    </dependencies>
</ivy-module>
```

Not sure why they are different.

**Comment by jamesward** [comment] 2013-04-19 19:30
And here is the `ivydata-2.1.properties` from the broken cache:

```
#ivy cached data file for joda-time#joda-time;2.1
#Thu Apr 18 13:59:54 MDT 2013
artifact\:ivy\#ivy\#xml\#926029232.location=http\://repo.typesafe.com/typesafe/releases/joda-time/joda-time/2.1/joda-time-2.1.pom
artifact\:joda-time\#jar\#jar\#-392003469.exists=true
artifact\:joda-time\#pom.original\#pom\#1260559193.location=http\://repo.typesafe.com/typesafe/releases/joda-time/joda-time/2.1/joda-time-2.1.pom
resolver=sbt-chain
artifact\:joda-time\#pom.original\#pom\#1260559193.exists=true
artifact\:joda-time\#pom.original\#pom\#1260559193.is-local=false
artifact\:joda-time\#jar\#jar\#-392003469.is-local=false
artifact\:joda-time\#doc\#jar\#-1588988920.is-local=false
artifact\:joda-time\#src\#jar\#1455075258.exists=true
artifact\:joda-time\#jar\#jar\#-392003469.location=http\://repo.typesafe.com/typesafe/releases/joda-time/joda-time/2.1/joda-time-2.1.jar
artifact\:joda-time\#doc\#jar\#-1588988920.location=http\://repo.typesafe.com/typesafe/releases/joda-time/joda-time/2.1/joda-time-2.1-javadoc.jar
artifact\:joda-time\#doc\#jar\#-1588988920.exists=true
artifact.resolver=sbt-chain
artifact\:joda-time\#src\#jar\#1455075258.is-local=false
artifact\:joda-time\#src\#jar\#1455075258.location=http\://repo.typesafe.com/typesafe/releases/joda-time/joda-time/2.1/joda-time-2.1-sources.jar
artifact\:ivy\#ivy\#xml\#926029232.exists=true
artifact\:ivy\#ivy\#xml\#926029232.is-local=false
```

And the one from the working cache:

```
#ivy cached data file for joda-time#joda-time;2.1
#Fri Apr 19 13:08:42 MDT 2013
artifact.resolver=public
artifact\:joda-time\#jar\#jar\#-392003469.is-local=false
artifact\:joda-time\#jar\#jar\#-392003469.location=http\://repo1.maven.org/maven2/joda-time/joda-time/2.1/joda-time-2.1.jar
artifact\:joda-time\#pom.original\#pom\#1260559193.location=http\://repo1.maven.org/maven2/joda-time/joda-time/2.1/joda-time-2.1.pom
artifact\:joda-time\#pom.original\#pom\#1260559193.is-local=false
artifact\:ivy\#ivy\#xml\#926029232.location=http\://repo1.maven.org/maven2/joda-time/joda-time/2.1/joda-time-2.1.pom
artifact\:ivy\#ivy\#xml\#926029232.is-local=false
resolver=public
```

**Comment by jsuereth** [comment] 2013-04-19 19:35
Looks like you grabbed a bad POM file from repo.typesafe.com before we
cleaned that up.... AND IVY REMEMBERED!

**Comment by jamesward** [comment] 2013-04-19 19:39
Cool.  Glad we got that fixed.  But why the inconsistent behavior between online & offline?

**Comment by jsuereth** [comment] 2013-04-19 19:42
Really good question, and one definitely worth investigating a little.  My guess is that ivy isn't good about clearing out bad data.  Mark would know more.

**Comment by harrah** [comment] 2013-04-22 13:58
Thanks @jsuereth, good catch.   That Ivy succeeds when online is surprising.  The outcome I expect from further investigation is to make online fail like offline.  I'll leave this open, but I do not think it is feasible to get Ivy to clear bad data because first you have to get it to recognize bad data.

**Comment by eed3si9n** [comment] 2014-04-01 18:50
Are we still gong to solve this?

**Comment by jsuereth** [comment] 2014-04-01 18:57
Good question.  I think we have a few larger fish in the cache world to fry first.

**Comment by eed3si9n** [comment] 2014-04-01 18:59
I'm closing this for now.

**Closed as completed by eed3si9n** 2014-04-01 18:59 UTC

**Comment by antonin42** [comment] 2016-08-18 19:14
+1
