### ISSUE TITLE
sbt console breaks xterm mapping for backspace

### ISSUE THREAD

**Issue by bandrei** [sbt/sbt#1681] opened 2014-10-18 20:51 UTC
operating system: arch
terminal: xterm

running sbt and then typing run in a project and closing sbt breaks the mapping for the backspace key. 
When pressing backspace `^H` shows on the console.

Could it be that it overrides `xterm*backarrowKeyIsErase: true` in Xdefaults or something?

**Comment by jsuereth** [comment] 2014-10-20 20:33
Jline is doing some interesting things with xterm.   You should check out everything that happens here, as sbt will call "Terminal.reset" on jline, which IIRC changes the echo characters, among other things.

**Comment by bandrei** [comment] 2014-11-12 00:00
Interesting, I'll try looking into it. It's Jline version 1 that's being used I assume?

**Comment by michelboaventura** [comment] 2015-04-10 01:42
This is still happening.

OS: Gentoo
terminal: xterm

If I run `stty -a` before and after sbt console I can see it changes erase from ^H to ^?. If I run manually a `stty erase ^H` the problem is fixed.

If I can give more info to fix this, please ask me.

**Comment by stewSquared** [comment] 2015-05-04 07:16
Gah. This is so annoying. My present solution is to add "stty erase ^H" To the end of /usr/bin/sbt, but this annoyingly crops up elsewhere.

**Comment by cruhland** [comment] 2015-07-27 22:03
I spent some time looking into this today as it has been bothering me for a while as well.

The issue was fixed in https://github.com/jline/jline2/pull/125, although that change caused some additional problems which were (hopefully) resolved by https://github.com/jline/jline2/commit/cababd8c7ae1a540b2e14c4bb1b695c5754c74ec.

I verified that the fix works by building SBT locally with its JLine dependency upgraded to the latest snapshot release, `2.13-SNAPSHOT`. So this should be fixable once JLine publishes a new versioned release, unless SBT is okay with using a snapshot?

**Comment by Lakret** [comment] 2015-10-13 00:48
Same problem here. Vagrant with Ubuntu on Windows and Ubuntu on AWS.

**Comment by dwickern** [comment] 2015-11-04 23:35
I'm having the same issue. There's a release of jline 2.13 now @cruhland

**Comment by cruhland** [comment] 2015-11-05 14:45
There was already a PR out for the fix! I've added a comment to it; hopefully we can get it merged soon.

**Closed as completed** 2018-06-18 05:04 UTC
Labels: help wanted
