### ISSUE TITLE
sbt new doesn't work on Windows: '"!_JAVACMD!"' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by chenjianxin** [sbt/sbt#5212] opened 2019-10-25 07:54 UTC
## steps
sbt version: 1.3.3

## problem
**sbt -Dsbt.version=1.3.3 new akka/akka-http-quickstart-scala.g8**
**sbt  new akka/akka-http-quickstart-scala.g8 "-Dsbt.version=1.3.3"**

[error] Expected ';'
[error] --sbt.version
[error]

c) continue
q) quit
?      if /I "" == "c" (c

The Java Development Kit (JDK) installation you have is not up to date.
sbt requires at least version !required_version!+, you have
version "!JAVA_VERSION!"

Please go to http://www.oracle.com/technetwork/java/javase/downloads/ and download
a valid JDK and install before running sbt.

Missing operator.
Missing operator.
'"!_JAVACMD!"' is not recognized as an internal or external command,
operable program or batch file.

OS: windows 10
Java version :
java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)

**Comment by eed3si9n** [comment] 2019-10-25 19:23
@chenjianxin This is a duplicate of https://github.com/sbt/sbt/issues/5188, and it will be fixed in the next release.

**Closed as completed by eed3si9n** 2019-10-25 19:23 UTC
