### ISSUE TITLE
javaOptions in test doesn't seem to work

### ISSUE THREAD

**Issue by ijuma** [sbt/sbt#1240] opened 2014-04-07 16:49 UTC
The forking documentation page[1] includes the following line:

`javaOptions in test += "-Xmx8G"`

This did not have the desired effect in our build. Changing it slightly made it work:

`javaOptions in Test += "-Xmx8G"`

It looks like either code or documentation need to be changed. There is another `in test` instance on that same page. Maybe that needs updating too?

[1] http://www.scala-sbt.org/0.13.1/docs/Detailed-Topics/Forking.html

**Comment by jsuereth** [comment] 2014-04-07 17:02
This is a duplicate of #975

**Comment by jsuereth** [comment] 2014-04-07 17:02
Also, thanks for pointing out the docs, we should get those updated.

**Closed as completed by jsuereth** 2014-04-07 17:02 UTC
