### ISSUE TITLE
Download artifacts in parallel

### ISSUE THREAD

**Issue by jroper** [sbt/sbt#590] opened 2012-10-30 06:45 UTC
It appears SBT doesn't download artifacts in parallel.  Consider the following
- Play framework has 3 repos by default
- In Australia, ping times times to maven/typesafe repos are 200ms (at least)
- If an artifact is not found in any repo (for example, when looking up source artifacts), that could total up to 6 round trips, or 1.2 seconds, just to ascertain that an artifact can't be found.
- Running play eclipsify from scratch, I can count on it taking about 10 minutes just to download everything, even with a 20mb/s internet connection, it's the round trip times that kill me.

Downloading in parallel would go a long way to help mitigate this.  Checking repositories for artifacts in parallel would help even more.

**Comment by vigdorchik** [comment] 2012-10-30 10:51
If only ivy was thread-safe...

**Comment by harrah** [comment] 2013-08-26 18:28
The best shot of this happening is probably https://github.com/adept-dm/adept.

**Comment by yanns** [comment] 2014-08-26 02:39
For info, the issue in ivy: https://issues.apache.org/jira/browse/IVY-1011

**Comment by jroper** [comment] 2014-12-30 02:30
An example of one user taking 2 hours just to download dependencies for the play-scala-intro Activator template:

https://groups.google.com/forum/#!topic/play-framework/lglJ6WDAftQ

**Comment by ghost** [comment] 2014-12-31 03:06
Our team is in India. It is very difficult to introduce scala into our organization as there is huge resistance because of this issue.

**Comment by richdougherty** [comment] 2015-05-26 03:02
Reported again: https://groups.google.com/d/msg/play-framework/Mk0AUcFHavM/4NiujRvoPaQJ

Shall we re-open this issue so that we can track the Ivy issue?

**Comment by richdougherty** [comment] 2015-05-26 03:10
I added a note on the Ivy ticket so they know about this issue.

**Comment by eed3si9n** [comment] 2015-05-26 04:58
Parallel download is possible without changing Ivy. (There was a branch @jsuereth created at some point) When we last looked at it we didn't see that much of improvement compared to the time sbt/ivy was taking resolving dependencies. But then again, we don't live in Australia or India. I can reopen this case and investigate this more.

**Comment by eed3si9n** [comment] 2015-05-26 04:59
https://github.com/sbt/sbt/tree/wip/ivy-parallel-artifact-download

**Comment by jroper** [comment] 2015-05-26 07:23
Does this just download the artifacts in parallel, or does it also download the artifact metadata (poms, ivy.xml) in parallel?  Downloading the artifact metadata in parallel would be a significant improvement, the thing that kills us the most is when you have many resolvers, and each one has to be tried before it finds the metadata.  For example, with a 250ms latency (standard trans pacific ping times), and an average of 4 resolvers to be tried, it will take an average of 1s per artifact to resolve.  In practice it takes longer, due to having to create new connections, ssl negotiations, etc.

**Comment by richdougherty** [comment] 2015-05-27 20:59
@eed3si9n, thanks for re-opening this ticket.

If you want to experience the joy of a non-US/non-European internet connection, there are plenty of tools out there to slow your network down. I've used [Charles](http://www.charlesproxy.com/) in the past and I just saw [Network Link Conditioner](http://apple.stackexchange.com/a/24078/121632) for Mac OS.

**Comment by richdougherty** [comment] 2015-05-27 21:05
Another idea: instead of trying all the resolvers in the same order for every artifact, would it be possible to remember that artifact X is usually on repo Y and then try repo Y first when a new version is needed? I think this would help speed things up a lot and reduce the amount of traffic to the repos.

**Comment by eed3si9n** [comment] 2015-05-28 06:18
@jroper No, that branch is about downloading artifacts.
To download the metadata in parallel, we likely need to mess with the resolver, which we already do as [SbtChainResolver](https://github.com/sbt/sbt/blob/v0.13.8/ivy/src/main/scala/sbt/ivyint/SbtChainResolver.scala).

@richdougherty I liked Charles so much that I used to call him Charlie. Also found an app named [Comcast](https://github.com/tylertreat/Comcast).

Looking at curl, SSL adds 300ms latency for me. Maybe the effect is even worse for your guys.

```
$ curl -w "tcp:%{time_connect}, ssl:%{time_appconnect}, start_transfer:%{time_starttransfer}, total:%{time_total}" -o /dev/null -s https://jcenter.bintray.com/org/scala-sbt/launcher-interface/1.0.0-M1/launcher-interface-1.0.0-M1.pom
tcp:0.077, ssl:0.365, start_transfer:0.451, total:0.451
```

**Comment by jsuereth** [comment] 2015-05-30 16:31
@jroper Another thing that could help is if we could get Ivy to expand the graph in parallel, when possible.   Checking multiple repositories in parallel may actually lead to more network hits, but it still is only partial parallelism, as we'll still only be checking for one dependency at a time, rather than doing a more thorough (and parallel) graph expansion.

**Comment by thorinii** [comment] 2015-06-18 00:48
With the command @eed3si9n posted (from Adelaide, Australia), I get:

```
tcp:0.336, ssl:0.782, start_transfer:1.066, total:1.066
```

**Comment by jroper** [comment] 2015-07-20 02:27
There are worse places than Australia to use sbt from - some people have satellite connections: https://github.com/playframework/playframework/issues/4866

**Comment by He-Pin** [comment] 2015-07-20 03:10
+1,in fact the play contains so many artifacts ,It will be a long time to download it.
a better thing would be support external downloader,like axel or aria2c.

**Comment by omervk** [comment] 2015-08-20 11:47
+1 to parallelizing the download of both dependencies and metadata.

**Comment by zafarella** [comment] 2016-01-26 19:37
++1 :)

**Comment by kralikba** [comment] 2016-01-28 15:30
+n :)
Could someone please post about the status of this issue?

**Comment by richdougherty** [comment] 2016-01-31 19:42
I think this is waiting on an upstream feature request in Ivy: https://issues.apache.org/jira/browse/IVY-1011. If you want this improvement in sbt then you may want to go to that Ivy issue and click "Vote for this issue". :)

**Comment by zafarella** [comment] 2016-02-04 05:53
some evidence that this is big issue https://github.com/jrudolph/sbt-optimizer

**Comment by guersam** [comment] 2016-02-05 07:23
Or migrate to https://github.com/alexarchambault/coursier ? (#2294)

**Comment by ghost** [comment] 2016-03-21 21:09
+1

**Comment by jvican** [comment] 2017-04-26 22:46
This has been implemented by the Scala Center here: https://github.com/sbt/librarymanagement/pull/90.

**Closed as completed** 2017-05-24 16:57 UTC
Labels: Enhancement, help wanted, area/library_management

**Comment by xiaopong** [comment] 2017-06-07 12:09
Any plan to resolve this issue? This has been there for years. If there's no way to get around the problem in ivy2 cache, is there any plan to move to a better cache repository? Or the plan is just to get stuck in this mess?

This is the most terrible thing in programming Scala. I'm in Shanghai China, with a big pipe Internet connection, and I've wasted so many hours that I can't believe we are still using this thing.

For example, doing a "sbt eclipse" on a Play starter example on a new computer took me 12 hours!!!!! I actually timed it and let it run for a whole day.

And I can't work on more than one project at the same time on the same computer, they got easily hung on the .sbt.ivy.lock and I have to still waste more time.

What I'd like to know is if there is a plan on this, or we, as developers, should just move to other workable solution.

**Comment by jvican** [comment] 2017-06-07 12:26
This feature is merged in sbt 1.0 @renzhi. So download should be much faster. Also, 12 hours is suspeciously slow. It would be good if you would share a reproducible build so that we can diagnose the problem further.

**Comment by hongxuchen** [comment] 2017-06-07 17:31
@renzhi that may result from the network issues in China; you might refer to https://github.com/Centaur/repox.

**Comment by xiaopong** [comment] 2017-06-08 03:17
@jvican Thanks for the heads up info. I would be happy to move to 1.0.x whenever the migration tools are ready (will find time to setup a new computer to experiment with it and not messing up with my current projects). I'm not sure how to reproduce it (suggestions would be much appreciated), it's just the resolving part that is extremely slow @HongxuChen.

For example, I clone the repox code, and do "sbt compile", and it just sits at here:

`xp @ λ ★ sbt compile
Getting org.scala-sbt sbt 0.13.13  (this may take some time)...
`
for 30 minutes, no network activity, no cpu activity, no disk activity. And in the meantime, I can't do anything else. If I try to work on some other project, I would get

`Waiting for lock on /home/xp/.sbt/boot/sbt.boot.lock to be available...`

And I can't do anything beside twiddling my thumbs. And this is the worst thing to have.

I cleared my ~/.sbt and ~/.ivy2 cache, and start from new, and I got exactly the same effect. And when it finally starts downloading, it's trickling down like a small mountain spring, at 2Kb/s or a bit higher, but most of the time, it just sits there doing nothing,  while maven can pump constantly at 2MB/s or 3MB/s (yeah, a capital B).

I don't know the internal of sbt (never had a chance to look into it), but what is even annoying is, why does it insist on downloading all the sbt 0.13.13 artifacts and all the artifacts of the older versions of scala, even if I set scalaVersion := "2.12.1". And it does it over and over again, every time you run sbt. But these have been downloaded so many times already.

I change -sbt-version to 0.13.15 in sbtopts, then it just skips the downloading of sbt artifacts, but it still gets stuck with others.

I have not used Scala in the last five years, just recently got back on a few Scala projects, and I'm almost getting bald by this sbt thing :)

Anyway, need to run to the railway station for now. Thanks all for your information and suggestion.

**Comment by hongxuchen** [comment] 2017-06-08 03:40
@renzhi I'm not quite familiar with repox and I'm not using it. However you can ask the author about the network issues. I suppose it's because some sbt repo centers are partially blocked (probably not central maven) in China.
sbt resolving is really slow IMO. But downloading older versions (e.g., bootstrap is 0.13.15 but project specifies 0.13.13) is reasonable, and it will download *once*.
