### ISSUE TITLE
Link broken for SBT launcher

### ISSUE THREAD

**Issue by asheshambasta** [sbt/sbt#2470] opened 2016-02-22 14:35 UTC
(See the guidelines for contributing, linked above)
## steps

when I do `sbt dist` inside a project, I see this warning

```
Detected sbt version 0.13.8
Cannot find sbt launcher 0.13.8
Please download: 
  From  http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
    To  /root/.sbt/.lib/0.13.8/sbt-launch.jar
```

So I follow by 

**`wget http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar`**
## problem

the link is incorrect (404 not found)
## expectation

The download should work.

**Comment by dwijnand** [comment] 2016-02-22 14:48
The problem is that http://typesafe.artifactoryonline.com was never meant to be the canonical URL, http://repo.typesafe.com was.

Therefore it should download from https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar.

Update you `sbt` launcher script and the problem will go away.

**Comment by eed3si9n** [comment] 2016-02-22 18:28
Are you using the unofficial sbt-extra launcher? The bug has been fixed by @dwijnand

**Closed as completed by eed3si9n** 2016-02-22 18:28 UTC
