### ISSUE TITLE
NullPointerException in compilation with Scala 2.11.11

### ISSUE THREAD

**Issue by alexandru** [sbt/sbt#3730] opened 2017-11-12 10:47 UTC
Tried upgrading to SBT 1.0.1:

- see this PR: https://github.com/monix/monix/pull/463
- see its failure on Travis: https://travis-ci.org/monix/monix/builds/300894949

Got a NPE that does not happen if I revert to SBT 0.13.16 or if I compile with Scala 2.12.4.
So this happens as a combination of SBT 1.0.1 with Scala 2.11.11

Note — not sure if relevant, but the `executionJVM` subproject that fails also contains Java code and thus this error might get triggered due to being a mixed project.

## Steps

```
git clone git@github.com:alexandru/monix.git

cd monix/
git checkout sbt-1.0

sbt "executionJVM/compile"
```

## Output

```
[error] ## Exception when compiling 156 sources to ./monix/monix-sbt/monix-execution/jvm/target/scala-2.11/classes
[error] java.lang.NullPointerException
[error] com.sun.tools.javac.main.Main.compile(Main.java:559)
[error] com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
[error] com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
[error] sbt.internal.inc.javac.LocalJavaCompiler.run(LocalJava.scala:152)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$11(AnalyzingJavaCompiler.scala:130)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:196)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:120)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:104)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:132)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:89)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:115)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:118)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:64)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:70)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1382)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1364)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] sbt.std.Transform$$anon$4.work(System.scala:64)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] sbt.Execute.work(Execute.scala:266)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] java.lang.Thread.run(Thread.java:745)
[error]            
[error] java.lang.RuntimeException: java.lang.NullPointerException
[error] 	at com.sun.tools.javac.main.Main.compile(Main.java:559)
[error] 	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
[error] 	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
[error] 	at sbt.internal.inc.javac.LocalJavaCompiler.run(LocalJava.scala:152)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$11(AnalyzingJavaCompiler.scala:130)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:196)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:120)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:104)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:132)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:89)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:115)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:118)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:64)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:70)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1382)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1364)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] Caused by: java.lang.NullPointerException
[error] 	at com.sun.tools.javac.util.DiagnosticSource.findLine(DiagnosticSource.java:163)
[error] 	at com.sun.tools.javac.util.DiagnosticSource.getLineNumber(DiagnosticSource.java:77)
[error] 	at com.sun.tools.javac.util.JCDiagnostic$SourcePosition.<init>(JCDiagnostic.java:379)
[error] 	at com.sun.tools.javac.util.JCDiagnostic.getLineNumber(JCDiagnostic.java:519)
[error] 	at com.sun.tools.javac.api.ClientCodeWrapper$DiagnosticSourceUnwrapper.getLineNumber(ClientCodeWrapper.java:637)
[error] 	at sbt.internal.inc.javac.DiagnosticsReporter$PositionImpl.<init>(DiagnosticsReporter.scala:85)
[error] 	at sbt.internal.inc.javac.DiagnosticsReporter.report(DiagnosticsReporter.scala:67)
[error] 	at com.sun.tools.javac.api.ClientCodeWrapper$WrappedDiagnosticListener.report(ClientCodeWrapper.java:593)
[error] 	at com.sun.tools.javac.util.Log.writeDiagnostic(Log.java:616)
[error] 	at com.sun.tools.javac.util.Log$DefaultDiagnosticHandler.report(Log.java:591)
[error] 	at com.sun.tools.javac.util.Log.report(Log.java:562)
[error] 	at com.sun.tools.javac.util.AbstractLog.mandatoryWarning(AbstractLog.java:189)
[error] 	at com.sun.tools.javac.comp.Check$8.report(Check.java:3182)
[error] 	at com.sun.tools.javac.code.DeferredLintHandler.report(DeferredLintHandler.java:80)
[error] 	at com.sun.tools.javac.comp.Check.checkSunAPI(Check.java:3177)
[error] 	at com.sun.tools.javac.comp.Attr.checkIdInternal(Attr.java:3636)
[error] 	at com.sun.tools.javac.comp.Attr.checkId(Attr.java:3490)
[error] 	at com.sun.tools.javac.comp.Attr.visitIdent(Attr.java:3233)
[error] 	at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2011)
[error] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
[error] 	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:638)
[error] 	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:631)
[error] 	at com.sun.tools.javac.comp.Attr.visitTypeCast(Attr.java:3100)
[error] 	at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[error] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
[error] 	at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:618)
[error] 	at com.sun.tools.javac.comp.Attr.visitVarDef(Attr.java:1075)
[error] 	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:852)
[error] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
[error] 	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
[error] 	at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4364)
[error] 	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4272)
[error] 	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4201)
[error] 	at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4176)
[error] 	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1248)
[error] 	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
[error] 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
[error] 	at com.sun.tools.javac.main.Main.compile(Main.java:523)
[error] 	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
[error] 	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
[error] 	at sbt.internal.inc.javac.LocalJavaCompiler.run(LocalJava.scala:152)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$11(AnalyzingJavaCompiler.scala:130)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:196)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:120)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:104)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:132)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:89)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:115)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:118)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:64)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:70)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1382)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1364)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (executionJVM/compile:compileIncremental) java.lang.NullPointerException
[error] Total time: 18 s, completed Nov 12, 2017 12:38:01 PM
```

**Comment by alexandru** [comment] 2017-11-12 11:16
As a follow up to my note on mixture of Java code, I tried `compileOrder := CompileOrder.JavaThenScala`, but it did not help.

**Comment by SethTisue** [comment] 2017-11-13 21:43
duplicate of #3623?

**Comment by alexandru** [comment] 2017-11-13 21:48
Possibly. In my experiments, this failure is pretty reproducible. I think it failed every time I tried.

**Comment by eed3si9n** [comment] 2017-11-17 08:23
Given the involvement of Java in the stacktrace, I'd say it's highly likely a duplicate of #3623.
If this is failing reliably, then Monix would be a great candidate for testing when we have the fix.

**Comment by alexandru** [comment] 2017-12-14 09:31
Just an FYI, but this still happens with version 1.0.3:

```
[error] java.lang.RuntimeException: java.lang.NullPointerException
[error] 	at com.sun.tools.javac.main.Main.compile(Main.java:559)
[error] 	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
[error] 	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
[error] 	at sbt.internal.inc.javac.LocalJavaCompiler.run(LocalJava.scala:152)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$11(AnalyzingJavaCompiler.scala:130)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:196)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:120)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:104)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:132)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:89)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:115)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:117)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:64)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:70)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1403)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1385)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.NullPointerException
[error] 	at com.sun.tools.javac.util.DiagnosticSource.findLine(DiagnosticSource.java:163)
[error] 	at com.sun.tools.javac.util.DiagnosticSource.getLineNumber(DiagnosticSource.java:77)
[error] 	at com.sun.tools.javac.util.JCDiagnostic$SourcePosition.<init>(JCDiagnostic.java:379)
[error] 	at com.sun.tools.javac.util.JCDiagnostic.getLineNumber(JCDiagnostic.java:519)
[error] 	at com.sun.tools.javac.api.ClientCodeWrapper$DiagnosticSourceUnwrapper.getLineNumber(ClientCodeWrapper.java:637)
[error] 	at sbt.internal.inc.javac.DiagnosticsReporter$PositionImpl.<init>(DiagnosticsReporter.scala:85)
[error] 	at sbt.internal.inc.javac.DiagnosticsReporter.report(DiagnosticsReporter.scala:67)
[error] 	at com.sun.tools.javac.api.ClientCodeWrapper$WrappedDiagnosticListener.report(ClientCodeWrapper.java:593)
[error] 	at com.sun.tools.javac.util.Log.writeDiagnostic(Log.java:616)
[error] 	at com.sun.tools.javac.util.Log$DefaultDiagnosticHandler.report(Log.java:591)
[error] 	at com.sun.tools.javac.util.Log.report(Log.java:562)
[error] 	at com.sun.tools.javac.util.AbstractLog.mandatoryWarning(AbstractLog.java:189)
[error] 	at com.sun.tools.javac.comp.Check$8.report(Check.java:3182)
[error] 	at com.sun.tools.javac.code.DeferredLintHandler.report(DeferredLintHandler.java:80)
[error] 	at com.sun.tools.javac.comp.Check.checkSunAPI(Check.java:3177)
[error] 	at com.sun.tools.javac.comp.Attr.checkIdInternal(Attr.java:3636)
[error] 	at com.sun.tools.javac.comp.Attr.checkId(Attr.java:3490)
[error] 	at com.sun.tools.javac.comp.Attr.visitIdent(Attr.java:3233)
[error] 	at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2011)
[error] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
[error] 	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:638)
[error] 	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:631)
[error] 	at com.sun.tools.javac.comp.Attr.visitTypeCast(Attr.java:3100)
[error] 	at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[error] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
[error] 	at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:618)
[error] 	at com.sun.tools.javac.comp.Attr.visitVarDef(Attr.java:1075)
[error] 	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:852)
[error] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
[error] 	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
[error] 	at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4364)
[error] 	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4272)
[error] 	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4201)
[error] 	at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4176)
[error] 	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1248)
[error] 	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
[error] 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
[error] 	at com.sun.tools.javac.main.Main.compile(Main.java:523)
[error] 	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
[error] 	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
[error] 	at sbt.internal.inc.javac.LocalJavaCompiler.run(LocalJava.scala:152)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$11(AnalyzingJavaCompiler.scala:130)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:196)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:120)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:104)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:132)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:89)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:115)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:117)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:64)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:70)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1403)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1385)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (executionJVM/compile:compileIncremental) java.lang.NullPointerException
[error] Total time: 96 s, completed Dec 14, 2017 11:28:53 AM
```

**Comment by eed3si9n** [comment] 2017-12-19 01:21
There's sbt 1.1.0-RC2 out with this fix, but we found other issues around RC-2 so we haven't widely announced it yet.

I just tested by running `clean` and `executionJVM/compile` 3 times in a row, and I'm not seeing NPE with 1.1.0-RC2.

**Closed as completed by eed3si9n** 2017-12-19 01:21 UTC
Labels: Duplicate

**Comment by alexandru** [comment] 2017-12-20 13:27
Thanks @eed3si9n
