### ISSUE TITLE
Sette opp issue her hvis den ikke kommer seg videre med compiling. startet 10:30

### ISSUE THREAD

**Issue by jQrgen** [sbt/sbt#2555] opened 2016-04-14 09:30 UTC
Hello

I'm a complete spark beginner, and im currently following [this tutorial](http://blog.prabeeshk.com/blog/2014/10/31/install-apache-spark-on-ubuntu-14-dot-04/) to set up spark locally on my machine. 
## steps

I run this command to build spark agains the hadoop file system i have already installed:
`hduser@jorgen-pc:~/spark-1.6.1$ build/sbt -Phadoop-2.6 assemly
`

This is the hadoop version i have installed:
`hduser@jorgen-pc:/home/jorgen$ hadoop version
Hadoop 2.6.0
Subversion https://git-wip-us.apache.org/repos/asf/hadoop.git -r e3496499ecb8d220fba99dc5ed4c99c8f9e33bb1
Compiled by jenkins on 2014-11-13T21:10Z
Compiled with protoc 2.5.0
From source with checksum 18e43357c8f927c0695f1e9522859d6a
This command was run using /usr/local/hadoop/share/hadoop/common/hadoop-common-2.6.0.jar
`
## problem

The commad above produces the following output and then the terminal stops logging. I let it stand there for one hour but

```
Using /usr/lib/jvm/java-7-openjdk-amd64 as default JAVA_HOME.
Note, this will be overridden by -java-home if it is set.
[info] Loading project definition from /home/hduser/spark-1.6.1/project/project
[info] Loading project definition from /home/hduser/.sbt/0.13/staging/ad8e8574a5bcb2d22d23/sbt-pom-reader/project
[warn] Multiple resolvers having different access mechanism configured with same name 'sbt-plugin-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * com.typesafe.sbt:sbt-git:0.6.1 -> 0.6.2
[warn]  * com.typesafe.sbt:sbt-site:0.7.0 -> 0.7.1
[warn] Run 'evicted' to see detailed eviction warnings
[info] Loading project definition from /home/hduser/spark-1.6.1/project
Waiting for lock on /home/hduser/.ivy2/.sbt.ivy.lock to be available...
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * org.apache.maven.wagon:wagon-provider-api:1.0-beta-6 -> 2.2
[warn] Run 'evicted' to see detailed eviction warnings
```
## expectation

I expected sbt to continue running and producing logs, but it has stopped further logging for an hour now all though it's still running.

**Comment by eed3si9n** [comment] 2016-04-14 21:16
I am guessing this is a duplicate of #2556

**Closed as completed by eed3si9n** 2016-04-14 21:16 UTC
