### ISSUE TITLE
Auto-scala-bin-compat source folder probably doesn't make sense in Play projects

### ISSUE THREAD

**Issue by victrcodes** [sbt/sbt#1957] opened 2015-04-07 11:04 UTC
Since the upgrade to sbt version 0.13.8 an empty folder "app-2.11" is appearing in the root of my Play 2.3.8 application when I work with it in dev ("run") mode.

**Comment by jsuereth** [comment] 2015-04-07 13:41
This is the default behavior in sbt now.  Perhaps we need play to disable it.  

Basically, there is a new, optional, directory in every project which is versioned by the scala you're using.  This allows you to do cross-building activities where the source differs between scala versions.

Given play's naming convention, this is probably pretty gross.   We'll look into either disabling for play, or having the default be smarter (cc @jroper)

**Comment by dwijnand** [comment] 2015-04-07 14:12
I agree, been seeing a bunch of comments about this change in 0.13.8.

IMO if you don't have multiple `crossScalaVersions` there's no need for both a `scala` and a `scala-2.11` source directory (or `app` and `app-2.11` in Play's case)

**Comment by jroper** [comment] 2015-04-07 23:56
We're aware that there are issues here with 0.13.8, and we will be looking at addressing them at least for Play 2.4, and maybe backporting to 2.3:

https://github.com/playframework/playframework/issues/4127

**Comment by eed3si9n** [comment] 2015-04-10 06:32
Note that OP of playframework/playframework#4127 (@mslinn) says:

> I hope that Play with SBT 0.13.8+ will continue to accept app-2.xx and test-2.xx directories and use them as per the new Cross-version support for Scala sources behavior. Play does not need to continuously create these directories if they do not exist, however.

`mkdirs` will no longer happen thanks to @jroper's playframework/playframework#4201.
A temporary workaround may be to set `crossPaths` to `false`. My vote is to close this issue. WDYT?

**Comment by zinking** [comment] 2015-08-04 15:52
I am using play2.4 @eed3si9n  and I am still seeing this issue. can you add a few more details regarding how to remove those ?

**Comment by dwijnand** [comment] 2015-08-04 17:06
@zinking Can you provide a reproducible case? Because I'm using Play 2.4 (2.4.2) and I'm _not_ seeing this issue anymore.

**Comment by mslinn** [comment] 2015-08-04 17:25
I see the extra directories in many/most projects. However, I don't consider this behavior to be a problem. Here is an example of a project that creates the directories: https://github.com/mslinn/play24Template

**Comment by dwijnand** [comment] 2015-08-04 18:00
@mslinn I tried play24Template and I'm not seeing it there either.. :-/

**Comment by mslinn** [comment] 2015-08-04 18:02
Hmm, maybe there is something in my ~/.sbt that is a factor

**Comment by zinking** [comment] 2015-08-05 14:01
@dwijnand not sure what kind of reproducible you want, I am using play 2.4, Java 1.8.52, scala 2.11.7 sbt 0.13.0, project is created using template play-scala.

**Comment by dwijnand** [comment] 2015-08-05 14:12
I tried what you say, I created a project using the `play-scala` activator template, changed the sbt version from 0.13.8 to 0.13.0 and it doesn't even load. (`value enablePlugins is not a member of sbt.Project`).

Also, from the [Play migration guide](https://www.playframework.com/documentation/2.4.x/Migration24), Play 2.4 requires sbt 0.13.8 anyways.

So I'm guessing you're seeing this as you're mixing Play 2.4 and sbt 0.13.0 somehow.

Do you have a step-by-step reproducible case of this issue using latest stable versions of sbt (0.13.8) and Play (2.4.2)?

For your reference, we have a guide on how to create a great bug report in [CONTRIBUTING](https://github.com/sbt/sbt/blob/0.13.8/CONTRIBUTING.md#what-to-report).

**Comment by muuki88** [comment] 2018-08-12 12:31
@eed3si9n I guess we can close this one.

**Closed as completed** 2018-08-12 13:18 UTC
Labels: Enhancement
