### ISSUE TITLE
Option to maintain execute permissions in IO.copy

### ISSUE THREAD

**Issue by jroper** [sbt/sbt#713] opened 2013-03-21 04:09 UTC
It would be great if there was an option to maintain execute permissions in IO.copy, using File.canExecute/File.setExecutable.

**Comment by pvlugter** [comment] 2013-03-21 04:32
I've implemented this in builds before and have also been meaning to suggest adding it to sbt. For example:

https://github.com/typesafehub/zinc/blob/master/project/Util.scala#L9-L34

**Comment by jroper** [comment] 2013-03-21 04:39
Yeah I've used something similar in my build.

**Comment by harrah** [comment] 2013-11-09 01:51
(Closing as a duplicate of the newer issue that had a contributed fix.)

**Closed as completed by harrah** 2013-11-09 01:51 UTC
Labels: Duplicate

**Comment by cos** [comment] 2014-09-15 12:35
What is the id of the new issue? Thanks!
