### ISSUE TITLE
java.lang.NoClassDefFoundError when starting sbt on macOS 10.13.6 (homebrew)

### ISSUE THREAD

**Issue by joewiz** [sbt/sbt#5275] opened 2019-12-08 20:58 UTC
## steps

- sbt version: 1.3.4
- macOS 10.13.6
- Java 1.8.0_232 (Zulu 8.42.0.23-CA-macosx) (build 1.8.0_232-b18)

1. Install sbt via `brew install sbt` as described at https://www.scala-sbt.org/download.html#macos
2. Type `sbt`

## problem

Invoking `sbt` or `sbt assembly` returns this error (here I'll paste in the full results of `sbt -v`:

```text
$ sbt -v
[process_args] java_version = '8'
[sbt_options] declare -a sbt_options=()
# Executing command line:
java
-Dfile.encoding=UTF-8
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-jar
/usr/local/Cellar/sbt/1.3.4/libexec/bin/sbt-launch.jar

java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/Appender
	at sbt.StandardMain$.initialGlobalLogging(Main.scala:146)
	at sbt.StandardMain$.initialState(Main.scala:175)
	at sbt.xMain$.run(Main.scala:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:45)
	at sbt.xMain.run(Main.scala:39)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:119)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.core.Appender
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 18 more
[error] [launcher] error during sbt launcher: java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/Appender
```

## expectation

On my other machine, running the current version of macOS (Catalina) and the same JDK, I've never had this problem.

## notes

I also tried downloading the release from https://github.com/sbt/sbt/releases and invoking it directly via `/Users/joe/Downloads/sbt/bin/sbt`, but the result was the same.

I'd be happy to provide more info, perform any tests that are needed, or try any workarounds that can be suggested.

**Comment by eatkins** [comment] 2019-12-08 21:31
I can't reproduce this on 10.14.16 with (Zulu 8.42.0.21-CA-macosx) (build 1.8.0_232-b18). Seems like it could be related to #5253.

> I'd be happy to provide more info, perform any tests that are needed, or try any workarounds that can be suggested.

In general debugging old mac os releases is going to be tough for us because we don't have the resources to maintain development machines for different versions. Does the issue occur on high sierra with a different jdk?

**Comment by eed3si9n** [comment] 2019-12-09 05:21
Could you wipe out `~/.sbt/boot/scala-2.12.10/org.scala-sbt/sbt/1.3.4` and try again?

**Comment by agyant** [comment] 2021-04-27 15:12
Hi @eed3si9n I am also seeing the same issue, I tried wiping out `~/.sbt/boot/scala-2.12.10/org.scala-sbt/sbt/1.3.8` but that didn't help either

**Comment by eed3si9n** [comment] 2021-04-27 16:36
Do you have a public build available that could reproduce this issue?
Also could you try using the current stable sbt 1.5.1?

**Comment by agyant** [comment] 2021-06-25 08:04
I am on 1.5.3. But still getting the same.

**Comment by eed3si9n** [comment] 2021-06-25 22:50
If you have `$HOME/.sbt/preloaded` directory, that might also be a good candidate to wipe out.

**Comment by agyant** [comment] 2021-06-28 07:42
I don't have that location locally

**Comment by zhengcan** [comment] 2022-01-04 13:36
I use sdkman to install latest sbt in a new macbook.
If I try to run sbt in a project, which declare to use sbt 1.3.x in `project/build.properties`, the sbt will throw the above exception.
If I remove build.properties file, the sbt works fine.

When I reinstall v1.3.13 sbt, and try to run it in an empty project, the sbt still throw above exception.

**Comment by zhengcan** [comment] 2022-01-05 13:37
I write a bash shell script to fix this issue. It works well.
```
#!/bin/bash

for api in `ls ~/.sbt/boot/scala-*/org.scala-sbt/sbt/*/log4j-api-*.jar`; do
  core=${api//log4j-api/log4j-core}
  if [[ ! -e $core ]]; then
    ver=${core//*\/log4j-core-/}
    ver=${ver//.jar/}
    file=https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/${ver}/log4j-core-${ver}.jar
    curl -Lfs -o $core $file
    echo "fixed $core"
  fi
done
```

**Comment by eed3si9n** [comment] 2022-01-05 17:14
@zhengcan Thanks. I'll close this issue then as sort of fixed with your workaround then.

**Closed as completed by eed3si9n** 2022-01-05 17:14 UTC
Labels: needs info
