### ISSUE TITLE
[sbt 1.0.0] NullPointerException from sbt.internal.util.StringTypeTag$.typeToString(StringTypeTag.scala:27)

### ISSUE THREAD

**Issue by robby-phd** [sbt/sbt#3445] opened 2017-08-15 03:19 UTC
## steps

1. ``git clone -b master --recursive https://github.com/sireum/v3`` (commit: [0aff5d3](https://github.com/sireum/v3/tree/0aff5d38d3706634faa7043da9e3a4d43fe63b9f))

2. patch: 

```patch
diff --git a/bin/prelude.sh b/bin/prelude.sh
index 332caa45..753a1bcf 100755
--- a/bin/prelude.sh
+++ b/bin/prelude.sh
@@ -29,7 +29,7 @@ for COMMAND in ${COMMANDS}; do
 done
 ZULU_VERSION=8.23.0.3-jdk8.0.144
 SCALA_VERSION=2.12.3
-SBT_VERSION=0.13.16
+SBT_VERSION=1.0.0
 NODE_VERSION=8.2.1
 Z3_VERSION=4.4.1
 if [ -z "${PLATFORM}" ]; then
diff --git a/build.sbt b/build.sbt
index 5b00f94b..ee83acbe 100644
--- a/build.sbt
+++ b/build.sbt
@@ -69,7 +69,6 @@ traceLevel in iveDistros := -1
 lazy val sireumSettings = Seq(
   organization := "org.sireum",
   version := sireumVersion,
-  incOptions := incOptions.value.withNameHashing(true),
   incOptions := incOptions.value.withLogRecompileOnMacro(false),
   scalaVersion := scalaVer,
   retrieveManaged := true,
diff --git a/project/build.properties b/project/build.properties
index 042ee620..333696cf 100644
--- a/project/build.properties
+++ b/project/build.properties
@@ -22,4 +22,4 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
-sbt.version=0.13.16
+sbt.version=1.0.0
```

3. run: ``v3/bin/sbt-launch.sh test``

## problem

```sbt
[error] java.lang.NullPointerException
[error] 	at sbt.internal.util.StringTypeTag$.typeToString(StringTypeTag.scala:27)
[error] 	at sbt.internal.util.StringTypeTag$.apply(StringTypeTag.scala:15)
[error] 	at sbt.internal.util.ManagedLogger.registerStringCodec(ManagedLogger.scala:39)
[error] 	at sbt.internal.util.ManagedLogger.<init>(ManagedLogger.scala:46)
[error] 	at sbt.util.LogExchange.logger(LogExchange.scala:32)
[error] 	at sbt.internal.LogManager$.defaultLogger(LogManager.scala:122)
[error] 	at sbt.internal.LogManager$DefaultLogManager.apply(LogManager.scala:99)
[error] 	at sbt.internal.LogManager$.$anonfun$construct$1(LogManager.scala:47)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:173)
[error] 	at sbt.std.TaskStreams.log(Streams.scala:88)
[error] 	at sbt.std.TaskStreams.log$(Streams.scala:88)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log$lzycompute(Streams.scala:137)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:137)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1393)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1375)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (runtime-runtime-js/test:compileIncremental) java.lang.NullPointerException
[error] Total time: 226 s, completed Aug 14, 2017 9:31:58 PM
```

## expectation

Successful build (like on [0.13.16](https://ci.appveyor.com/project/robby-phd/v3/build/1.0.248)).

## notes

sbt version: 1.0.0

**Comment by dwijnand** [comment] 2017-08-15 09:21
Duplicate of https://github.com/sbt/util/issues/119.

**Closed as completed by dwijnand** 2017-08-15 09:21 UTC
