### ISSUE TITLE
Apt key for Debian packages

### ISSUE THREAD

**Issue by fhackenberger** [sbt/sbt#1851] opened 2015-02-11 11:12 UTC
Could you please publish the GPG key you are using to sign the Debian packages, so we can import them when installing the packages. That's super important for a secure system, like it is now, there is no way I can verify that the sbt package is actually from you guys.

Thanks a lot!

**Comment by jsuereth** [comment] 2015-03-12 00:18
You're getting our key from bintray, correct?  I'll have to check what/who signs it.

In terms of consumption, do you want it as its own "deb" file or would you rather just have the raw .asc / .gpg ?

**Comment by czchen** [comment] 2015-08-12 01:33
@jsuereth 

The `https://dl.bintray.com` is now signed by key `99E82A75642AC823`, which I cannot know if it is authenticated or not. If the key is good, please update the DEB section in http://www.scala-sbt.org/0.13/tutorial/Installing-sbt-on-Linux.html.

The following is error message I got when `apt update`.

```
W: GPG error: https://dl.bintray.com  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 99E82A75642AC823
```

**Comment by eed3si9n** [comment] 2015-08-12 01:36
This is a duplicate of sbt/sbt-launcher-package#72. The new deb for 0.13.9 should be signed with `642AC823`.

```
$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
```

**Closed as completed by eed3si9n** 2015-08-12 01:36 UTC
Labels: documentation, Duplicate

**Comment by avelinob** [comment] 2019-03-15 08:22
Doesnt work behind a proxy
