### ISSUE TITLE
https://dl.bintray.com/sbt/debian/Release is not publicly accessible

### ISSUE THREAD

**Issue by nercisla** [sbt/sbt#6446] opened 2021-04-12 16:39 UTC
## steps

run `sudo apt update` on Ubuntu 18.04
the command fails with

```
Err:6 https://dl.bintray.com/sbt/debian  InRelease
  403  Forbidden
```

## problem

[https://dl.bintray.com/sbt/debian/Release](https://dl.bintray.com/sbt/debian/Release) is not publicly accessible

## expectation

[https://dl.bintray.com/sbt/debian/Release](https://dl.bintray.com/sbt/debian/Release) should be publicly accessible

**Comment by JayCork** [comment] 2021-04-12 16:45
```
[Container] 2021/04/12 16:09:27 Running command apt-get update
Err:11 https://dl.bintray.com/sbt/debian  InRelease
  403  Forbidden [IP: XX]
```

**Comment by obohrer** [comment] 2021-04-12 16:47
We are encountering this issue as well

**Comment by ajaykumarmandapati** [comment] 2021-04-12 16:48
This also happens for https://sbt.bintray.com/rpm/repodata/repomd.xml , we get `Forbidden!`

**Comment by teroxik** [comment] 2021-04-12 16:49
There is a brownout in place. Nothing what can be done by the maintainers except publishing to some other repository.

https://github.com/sbt/sbt/issues/6445

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

@eed3si9n is there any plan to push the packages to some other repositories as ultimately it will go away. The other libraries artifacts have a similar problem.

**Comment by eed3si9n** [comment] 2021-04-12 17:15
Closing this as duplicate of https://github.com/sbt/sbt/issues/6445

> is there any plan to push the packages to some other repositories as ultimately it will go away. The other libraries artifacts have a similar problem.

Yes. Please see https://github.com/sbt/sbt/issues/6294.

**Closed as completed by eed3si9n** 2021-04-12 17:15 UTC
Labels: area/linux
