### ISSUE TITLE
^C doesn't kill sbt anymore

### ISSUE THREAD

**Issue by tpolecat** [sbt/sbt#3708] opened 2017-11-02 23:43 UTC
I can't get out of sbt by hitting ^C anymore. If I do it during a compile it says `[warn] Canceling execution...` and then waits for compilation to finish, then throws an exception and drops me back at the prompt. The only way I know to bail out is to `^Z` and then locate the job and `kill -9` which is a lot of work relative to one keystroke. Is there a way to turn this off?

```
> test:compile
[info] Compiling 45 Scala sources to /Users/rnorris/Scala/gem/modules/core/jvm/target/scala-2.12/test-classes ...
[info] Compiling 1 Scala source to /Users/rnorris/Scala/gem/modules/json/target/scala-2.12/test-classes ...
...
^C
[warn] Canceling execution...
...         
^C
[warn] Canceling execution...
^C
[warn] Canceling execution...
...
^C
...
[error] 28 errors found
[error] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ExecutorCompletionService$QueueingFuture@62d6611a rejected from java.util.concurrent.ThreadPoolExecutor@6a29807f[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 3520]
[error] 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
[error] 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
[error] 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
[error] 	at java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:181)
[error] 	at sbt.CompletionService$.submit(CompletionService.scala:32)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.submitValid(ConcurrentRestrictions.scala:169)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.submit(ConcurrentRestrictions.scala:158)
[error] 	at sbt.Execute.submit(Execute.scala:257)
[error] 	at sbt.Execute.ready(Execute.scala:237)
[error] 	at sbt.Execute.notifyDone(Execute.scala:176)
[error] 	at sbt.Execute.$anonfun$retire$2(Execute.scala:147)
[error] 	at sbt.Execute.$anonfun$retire$2$adapted(Execute.scala:146)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at sbt.Execute.retire(Execute.scala:146)
[error] 	at sbt.Execute.$anonfun$work$2(Execute.scala:274)
[error] 	at sbt.Execute$$anon$1.process(Execute.scala:20)
[error] 	at sbt.Execute.next$1(Execute.scala:99)
[error] 	at sbt.Execute.processAll(Execute.scala:102)
[error] 	at sbt.Execute.runKeep(Execute.scala:79)
[error] 	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:383)
[error] 	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:382)
[error] 	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:401)
[error] 	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:96)
[error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:327)
[error] 	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:94)
[error] 	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:107)
[error] 	at sbt.internal.Aggregation$.$anonfun$applyTasks$1(Aggregation.scala:64)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error] 	at sbt.internal.Aggregation$.$anonfun$evaluatingParser$11(Aggregation.scala:216)
[error] 	at sbt.internal.Act$.$anonfun$actParser0$3(Act.scala:310)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:227)
[error] 	at sbt.State$$anon$1.process(State.scala:233)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:98)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:104)
[error] 	at sbt.xMain.run(Main.scala:71)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ExecutorCompletionService$QueueingFuture@62d6611a rejected from java.util.concurrent.ThreadPoolExecutor@6a29807f[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 3520]
[error] Use 'last' for the full log.
> 
```

## steps

As above.

## problem

It's annoying.

## expectation

sbt should respect ^C.

## notes

sbt version: 1.0

**Comment by laughedelic** [comment] 2017-11-03 12:28
Probably you have `cancellable in Global := true` in your global settings? How about `^D` to exit?

Another thing is that even when `^C` is supposed to cancel current task, but stay in the sbt shell, it doesn't really work..

**Comment by tpolecat** [comment] 2017-11-03 16:39
I do have `cancelable in Global := true` in order to ^C out of my running program back to the shell. Is there a way to scope it such that it only applies to `run`?

**Comment by eed3si9n** [comment] 2020-02-22 18:56
@azolotko said he can't reproduce this on 1.3.8 so I am closing this for now.

**Closed as completed by eed3si9n** 2020-02-22 18:56 UTC
