### ISSUE TITLE
classpathDependency erroneously looked for in Ivy/Maven when default scalaVersions don't match

### ISSUE THREAD

**Issue by ryan-williams** [sbt/sbt#3980] opened 2018-03-02 05:12 UTC
## steps
[As reported in gitter]():

### build.sbt
```scala
lazy val a = project.settings(
  scalaVersion := "2.11.12"
).dependsOn(
  b
)
lazy val b = project.settings(
  scalaVersion := "2.12.4",
  crossScalaVersions := Seq("2.11.12", "2.12.4")
)
```

Run:

```bash
sbt a/update
```

## problem
`a/update` fails like:

```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: b#b_2.11;0.1.0-SNAPSHOT: not found
[error]     at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error]     at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error]     at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
…
```

## expectation

`a` (scala `2.11.12`) gets a classpath-dependency on `b`'s scala-`2.11.12`-cross-build

## notes

For some reason, the differing default `scalaVersion` values (`2.11.12` in `a` vs `2.12.4` in `b`) causes `a` to not actually use `b` as a classpath-dep, but instead search for it in external repositories where it doesn't (and doesn't need to) exist.

sbt version: 1.1.1

**Comment by dwijnand** [comment] 2018-03-15 14:38
Duplicate of #1448

**Closed as completed by dwijnand** 2018-03-15 14:38 UTC
