### ISSUE TITLE
Link to CONTRIBUTING is broken

### ISSUE THREAD

**Issue by ignasi35** [sbt/sbt#4344] opened 2018-09-04 16:22 UTC
(this is a meta-issue)

- [ ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

^^^ the link above to `CONTRIBUTING` is broken for both the issue and the PR templates.

**Comment by eed3si9n** [comment] 2018-09-05 03:25
Duplicate of https://github.com/sbt/sbt/issues/4338

**Closed as completed by eed3si9n** 2018-09-05 03:25 UTC
