### ISSUE TITLE
Sbt-bintray not publishing due to wrong settings (possibly plugin is not enabled, which should be by default)

### ISSUE THREAD

**Issue by slouc** [sbt/sbt#2995] opened 2017-03-07 10:58 UTC
(See the guidelines for contributing, linked above)

## steps

I was trying to use [sbt-bintray](https://github.com/sbt/sbt-bintray) and I followed the instructions in the main readme:

- Added the following to project/plugins.sbt file: `addSbtPlugin("me.lessis" % "bintray-sbt" % "0.3.0")`
- Set up credentials correctly (username + API key)
- Added `bintrayOrganization := Some("my-organization")` to my sbt because I am publishing to an organization, not my standalone repo
- Ran `sbt publish` task

## problem

> [error] (*:bintrayEnsureBintrayPackageExists) was not able to find or create a package for spotcap in Repo(my-organization,maven) named my-project
> [error] (*:publish) error uploading to https://api.bintray.com/maven/my-organization/maven/maven/my-username/my-project_2.12/0.0.1/my-project_2.12-0.0.1.pom: {"message":"Repo 'maven' was not found"}

## expectation

Successfully publishing the project to bintray repo.

## notes

It's possible that `sbtPlugin.value` in the settings file was false (see [here](https://github.com/sbt/sbt-bintray/blob/456e57e91a8e94fdde6199279defb2df453a0c17/src/main/scala/BintrayPlugin.scala#L54-L62)), which caused the sbt to publish to non-existing "maven" repo. Manually adding `bintrayRepository`, `bintrayPackage` and `bintrayOrganization` to sbt resolved the issue.

Only other option I see is that `sbtPlugin.value` was true, but settings file was missing a certain key (I see that there is no standalone `bintrayOrganization` key in the settings file, only the one used for `bintrayRepo` key, so perhaps something like that could be the issue).

**Comment by dwijnand** [comment] 2017-03-07 11:02
Hey @slouc. Sorry I meant create an issue in sbt/sbt-bintray.

This is duplicate of https://github.com/sbt/sbt-bintray/issues/58, which has been fixed in https://github.com/sbt/sbt-bintray/pull/70, but requires a release..

**Closed as completed by dwijnand** 2017-03-07 11:02 UTC

**Comment by slouc** [comment] 2017-03-07 11:05
Yeah it was weird for me too to publish to sbt itself, but I thought that's what you wanted :) Anyways, everything is working now for me, I just wanted to communicate to you guys that something is off for the future users. If it's fixed but not yet released, then great.
