### ISSUE TITLE
Windows MSI installer: unrecognized app

### ISSUE THREAD

**Issue by unkarjedy** [sbt/sbt#6317] opened 2021-02-17 09:57 UTC
Just try to run installer from https://www.scala-sbt.org/download.html
Looks like the installers should be somehow signed / verified by Microsoft

![image](https://user-images.githubusercontent.com/3989292/108187466-8f7a1680-711f-11eb-81a8-15063c9c1d74.png)

**Comment by eed3si9n** [comment] 2021-02-19 01:15
I think this is a duplicate of https://github.com/sbt/sbt/issues/4309

**Closed as not planned by eed3si9n** 2021-02-19 01:15 UTC
