### ISSUE TITLE
Ivy2 cache preceeds ivy2 local

### ISSUE THREAD

**Issue by jorkzijlstra** [sbt/sbt#2687] opened 2016-08-01 12:44 UTC
## steps
- create an library and publish it
- update the library and use publishLocal
## problem

So you have 2 of the same snapshot version but with different code in your .ivy2 cache
On in .ivy2/cache and one in .ivye/local, where the one in .ivy/local is the latest snapshot version. 

SBT resolved the dependency to the .ivy2/cache (older) version instead of the new .ivy2/local version.
## expectation

That the .ivy2/local preceeds the .ivy2/cache
## notes

We sometimes publish our snapshot version to share between environments, but this doesn't mean development is one. We still want/ need to update the exact same version number locally before remotely.

**Comment by jorkzijlstra** [comment] 2016-08-01 12:55
IntelliJ resolves the local before the cache version, so the other way around.

**Comment by eed3si9n** [comment] 2016-08-01 13:52
I recommend against using SNAPSHOT version outside of local or temporary testing. That said, sbt at least 0.13.12 should try to pick the latest version given the right metadata. What's your version of sbt? What kind of repository are you publishing into? If it's a Maven repo, does it have `maven-metadata.xml`?

**Comment by jorkzijlstra** [comment] 2016-08-01 14:11
> I recommend against using SNAPSHOT version outside of local or temporary testing.

I agree, but unfortunately sometimes when developing with multiple developers and different environments it's necessary. 

I'm using sbt 0.13.12 and I'm publishing to a internal maven artifactory (JFrog) and that does have that maven-meradata.xml [maven-metadata.xml.zip](https://github.com/sbt/sbt/files/393941/maven-metadata.xml.zip)

As you can see in the metadata xml the remote version is from last week. The .ivy2/local version doesn't have any metadata but was published locally this week (today). Since the local version is from a later timestamp it should use this one and not the one from remote.

**Comment by eed3si9n** [comment] 2016-08-01 14:18
sbt caches the result of the `update` task using the description of the dependency graph. Have you run `clean` and then `update`?

**Comment by jorkzijlstra** [comment] 2016-08-01 14:29
Yes, off course (I should have mentioned it). I use clean and update very frequently. However clean and update doesn't effect the .ivy2 directory and in this case the description of the library remains the same between snapshot versions.

It only works after:
1- adding the dependency as an unmanaged jar and remove the library dependency
2- manually remove it from the .icy2/cache location but keeping the .ivy2/local

**Comment by dwijnand** [comment] 2016-09-02 08:53
I can confirm this bug.

**Comment by clhodapp** [comment] 2016-09-07 06:18
The behavior I've noted (which I at least sort of depend on) is that resolution is "sticky". Basically, the resolution steps seem to be:

Steps for a lookup where artifact is in local but not cache:
1. Try to look up artifact in cache (suppose it's not there)
2. Try to look up artifact in local
3. Find artifact in local
4. Store a "pointer" to local into the cache for this artifact
5. Use artifact from local

Steps for a lookup where artifact is not in local or cache:
1. Try to look up artifact in cache (suppose it's not there)
2. Try to look up artifact in local
3. Do not find artifact in local
4. Try to look up artifact online
5. Find artifact on maven central
6. Download artifact from maven central to the cache
7. Store a "pointer" to maven central into the cache
8. Use artifact from cache

Steps for a lookup of an artifact that was previously found:
1. Try to look up artifact in cache (find pointer and possibly artifact)
2. If artifact is "changing" (which includes being a snapshot), check the place the pointer points to for a new version
3. If there's a new version, update pointer and possibly download it (if it's not local)
4. Use the artifact

This behavior is actually kind of useful if you know that it's there, as it lets you, e.g., lock a downstream repo into either `publishLocal`ed or remote artifacts, depending on what you want. I will say that I think the use case of locking to `local` is more important than locking to remote artifacts, so a change to always prefer local wouldn't be the worst thing in the world. If you want to operate effectively under the current behavior, https://github.com/sbt/sbt-dirty-money is your friend.

**Comment by wsargent** [comment] 2017-02-03 05:43
I've been running into this with https://github.com/playframework/play-ws shaded files.

**Comment by er1c** [comment] 2017-06-09 22:50
@eed3si9n is there any way to explicitly set a setting to always prefer the `~/.ivy2/local` SNAPSHOT file over the one that can get updated from `~/.ivy2/cache` if the versions are the same?  There are instances where I'm playing on the same `SNAPSHOT` as someone else, and if the version doesn't get bumped, I then have to start playing games to make sure my local fork/publish of the snapshot overrides the maven-resolved file.  It seems like the logic should *always* be to prefer the local over the cache.

**Comment by gaydenko** [comment] 2017-07-18 12:24
Hi! Has anybody got any workaround during this year to prefer local over cache?

**Comment by er1c** [comment] 2017-07-18 12:49
@gaydenko I've been forced to rename my `-BRANCH-SNAPSHOT` versions to be extra sure.  If you find a better solution let me know :)  I also have https://github.com/scalacenter/sbt-release-early on my "to investigate" list.

**Comment by jkleckner** [comment] 2017-07-20 01:45
@gaydenko I find that if I do an otherwise unnecessary depth-first publishLocal it will cause the filesystem timestamps to be newer and your local will resolve first.  This works until someone, including you, pushes a snapshot upstream causing the cache to have a newer filesystem timestamp.  I have to say this is inferred not rigorously deduced.

**Comment by adisesha** [comment] 2017-11-01 10:54
Any update on this issue?

**Comment by pharmazone** [comment] 2017-11-07 09:42
+1

**Comment by ozmad** [comment] 2017-12-01 11:36
I just had the similar problem in sbt-1.0.
This is a simple workaround that works for me (might need slight syntax changes for other sbt versions but should work).

Add the following to build.sbt of the project (the dependency):

`publishLocal := {`
`	val cachePath =` `s"${ivyPaths.value.ivyHome.get.getCanonicalPath}/cache/${organization.value}/${name.value}"`
`	org.apache.commons.io.FileUtils.deleteDirectory(new File(cachePath))`
`	publishLocal.value`
`}`


The idea is just to delete cache when running "publishLocal" (you can also delete specific files with pure java...) all "to be published" artifacts can be found in `publishConfiguration.value.artifacts`, version and name are widely available.

Note that I'm not sure if publishing a newer artifact to the remote repository will be used over the one in local.

**Comment by jesinity** [comment] 2017-12-09 17:04
the point is when you have mixed projects, as we are because we're transitioning from maven to sbt you are in a real pain.

We have this workflow:

* we have a mixed sbt and maven project
* imagine last stable release, published in internal nexus with version `2.0.0`.
* I develop on my branch with next release `2.0.1-SNAPSHOT` . This release is never published to nexus: SNAPSHOT only exist in local envs. This version is used both in maven and sbt sub projects.
* I publish in ***maven*** local module **A**  version `2.0.1-SNAPSHOT` as next features are done.
* I have ***sbt*** module **B**, still of version  depending on module **A** . when I update it, it quite often resolves an old picture of module **A**, it's not able to find new snapshots.

What's the current workaround for this situation?

**Comment by nromeoarena** [comment] 2017-12-09 17:05
+1

**Comment by ozmad** [comment] 2017-12-09 19:40
@jesinity I would consider adding a task to build.sbt  "localDependenciesCleanup" that will clean the local maven repo. you should consider if it should be done on your build server too (might be problematic if more than one "build" is running at the same time)

**Comment by hindog** [comment] 2018-02-13 06:44
+1

**Comment by regis-leray** [comment] 2018-03-06 19:59
+1

**Comment by pshirshov** [comment] 2018-07-14 14:27
So, I have a project which is publishied to `sonatype-snapshots` by travis. 
At the same time I'm publishing it locally as a part of my development cycle.

It's very annoying that oftenly SBT prefers to use remote version instead of local, even if local timestamp is more recent than remote one.

**Comment by clhodapp** [comment] 2018-08-01 06:35
@pshirshov My experience is that the version it picks is actually controllable if you know how. See my comment above: https://github.com/sbt/sbt/issues/2687#issuecomment-245185840

**Comment by eed3si9n** [comment] 2019-08-09 20:11
I am closing this since 1.3.0 switches to Coursier.

**Closed as completed by eed3si9n** 2019-08-09 20:11 UTC
Labels: area/library_management
