### ISSUE TITLE
SBT 1.0.[23] NPE in sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.getURLInfo

### ISSUE THREAD

**Issue by NicolasRouquette** [sbt/sbt#3750] opened 2017-11-19 22:52 UTC
(See the guidelines for contributing, linked above)

## steps

Clone this repo: https://github.com/NicolasRouquette/sbt.gigahorse.npe

## problem

With SBT 1.0.[23], running `sbt update` will result in the NPE described in the README.md

This is odd that this NPE happens specifically with the supersafe plugin.

## expectation

No NPE.

## notes

@eed3si9n's [suggestion](https://github.com/sbt/sbt/issues/3519#issuecomment-328971177) works, i.e.,:

```
updateOptions := updateOptions.value.withGigahorse(false)
```

sbt version: 1.0.2 (there is no supersafe plugin for 1.0.3)

**Comment by cheeseng** [comment] 2017-11-20 03:45
Related: https://github.com/sbt/librarymanagement/issues/180

**Comment by eed3si9n** [comment] 2017-11-24 22:39
I tested it on my Mac, but I could not reproduce this.

```
sbt:p> update
[success] Total time: 4 s, completed Nov 24, 2017 5:32:53 PM
```

**Comment by bjonnh** [comment] 2018-01-28 01:32
This solved my problem of not being able to use banana-rdf in my project.
https://hastebin.com/ixiqixosan.nginx

**Comment by eed3si9n** [comment] 2019-09-25 01:43
Hopefully fixed by https://github.com/sbt/librarymanagement/pull/214

**Closed as completed by eed3si9n** 2019-09-25 01:43 UTC
