### ISSUE TITLE
Performance of Incremential Compilation 

### ISSUE THREAD

**Issue by vjovanov** [sbt/sbt#400] opened 2012-03-14 13:48 UTC
We have a large project consisting of several sub-projects (https://github.com/stanford-ppl/Delite/tree/optiml-alpha). The project is very heavy on the Scala compiler as it uses great number of implicit conversions and type system features. To give you a flavor it takes 200 seconds to compile 21 test case. The whole project compiles for 450 seconds.

The performance issue happens when we make a simple API change (adding one dummy method) in the base module of the project. SBT properly analyses the dependencies (it finds that about 70% of classes need to be re-compiled). 

The problem is that incremental compilation of those 70% of the classes takes longer than the full rebuild of the project. 

It could be that the large complexity of our project makes the dependency analysis very expensive.

**Comment by harrah** [comment] 2012-05-01 01:19
Duplicate of #322.

**Closed as completed by harrah** 2012-05-01 01:19 UTC
Labels: Duplicate
