### ISSUE TITLE
sbt 0.11.3: AttributeKey ID collisions of 'scripted-scalas'

### ISSUE THREAD

**Issue by omervk** [sbt/sbt#448] opened 2012-05-08 21:40 UTC
I'm using two plugins ([xsbt-web-plugin](git://github.com/siasia/xsbt-web-plugin) and [sbt-assembly](git://github.com/sbt/sbt-assembly)), both of which use the scripted-scalas module and both of which have been upgraded to use the new 0.11.3 scheme.
However, when I load the project I get this error:

`[info] Loading global plugins from /Users/omervk/.sbt/plugins
[debug] Running task... Cancelable: false, max worker threads: 8, check cycles: false
[debug] 
[debug] Initial source changes: 
[debug]     removed:Set()
[debug]     added: Set()
[debug]     modified: Set()
[debug] Removed products: Set()
[debug] Modified external sources: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug]     product: Set()
[debug]     binary dep: Set()
[debug]     external source: Set()
[debug] Initially invalidated: Set()
[debug] Copy resource mappings: 
[debug]     
[debug] Other repositories:
[debug] Default repositories:
[debug]     Raw(ProjectResolver(inter-project, mapped: ))
[debug]     URLRepository(typesafe-ivy-releases,sbt.Patterns@560508be)
[debug]     FileRepository(local,FileConfiguration(true,None),sbt.Patterns@304a0ac5)
[debug]     sbt-idea-repo: http://mpeltonen.github.com/maven/
[debug]     public: http://repo1.maven.org/maven2/
[debug] Using inline dependencies specified in Scala.
[debug] post 1.3 ivy file: using exact as default matcher
[info] Loading project definition from /Users/omervk/repro/project
[debug] Running task... Cancelable: false, max worker threads: 8, check cycles: false
[debug] 
[debug] Initial source changes: 
[debug]     removed:Set()
[debug]     added: Set()
[debug]     modified: Set()
[debug] Removed products: Set()
[debug] Modified external sources: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug]     product: Set()
[debug]     binary dep: Set()
[debug]     external source: Set()
[debug] Initially invalidated: Set()
[debug] Copy resource mappings: 
[debug]     
[info] Loading project definition from /Users/omervk/.sbt/staging/65e4501327cb11085ce0/project
[debug] Running task... Cancelable: false, max worker threads: 8, check cycles: false
[debug] 
[debug] Initial source changes: 
[debug]     removed:Set()
[debug]     added: Set()
[debug]     modified: Set()
[debug] Removed products: Set()
[debug] Modified external sources: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug]     product: Set()
[debug]     binary dep: Set()
[debug]     external source: Set()
[debug] Initially invalidated: Set()
[debug] Copy resource mappings: 
[debug]     
[info] Loading project definition from /Users/omervk/.sbt/staging/9e1f511682a010fc8b53/project/project
[debug] Running task... Cancelable: false, max worker threads: 8, check cycles: false
[debug] 
[debug] Initial source changes: 
[debug]     removed:Set()
[debug]     added: Set()
[debug]     modified: Set()
[debug] Removed products: Set()
[debug] Modified external sources: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug]     product: Set()
[debug]     binary dep: Set()
[debug]     external source: Set()
[debug] Initially invalidated: Set()
[debug] Copy resource mappings: 
[debug]     
[info] Loading project definition from /Users/omervk/.sbt/staging/9e1f511682a010fc8b53/project
[debug] Running task... Cancelable: false, max worker threads: 8, check cycles: false
[debug] 
[debug] Initial source changes: 
[debug]     removed:Set()
[debug]     added: Set()
[debug]     modified: Set()
[debug] Removed products: Set()
[debug] Modified external sources: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug]     product: Set()
[debug]     binary dep: Set()
[debug]     external source: Set()
[debug] Initially invalidated: Set()
[debug] Copy resource mappings: 
[debug]     
java.lang.RuntimeException: AttributeKey ID collisions detected for: 'scripted-scalas' (sbt.ScriptedPlugin$ScriptedScalas, sbt.ScriptedPlugin$ScriptedScalas)
    at scala.sys.package$.error(package.scala:27)
    at scala.Predef$.error(Predef.scala:66)
    at sbt.Index$.stringToKeyMap(Build.scala:190)
    at sbt.Load$.structureIndex(Load.scala:168)
    at sbt.Load$.apply(Load.scala:124)
    at sbt.Load$.defaultLoad(Load.scala:37)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:513)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:510)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:62)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:62)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:64)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:64)
    at sbt.Command$.process(Command.scala:92)
    at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(Main.scala:121)
    at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(Main.scala:121)
    at sbt.State$$anon$1.process(State.scala:154)
    at sbt.MainLoop$$anonfun$next$1.apply(Main.scala:121)
    at sbt.MainLoop$$anonfun$next$1.apply(Main.scala:121)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.MainLoop$.next(Main.scala:121)
    at sbt.MainLoop$.run(Main.scala:114)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(Main.scala:103)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(Main.scala:100)
    at sbt.Using.apply(Using.scala:25)
    at sbt.MainLoop$.runWithNewLog(Main.scala:100)
    at sbt.MainLoop$.runAndClearLast(Main.scala:83)
    at sbt.MainLoop$.runLoggedLoop(Main.scala:67)
    at sbt.MainLoop$.runLogged(Main.scala:60)
    at sbt.xMain.run(Main.scala:33)
    at xsbt.boot.Launch$.run(Launch.scala:54)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:43)
    at xsbt.boot.Launch$.launch(Launch.scala:68)
    at xsbt.boot.Launch$.apply(Launch.scala:14)
    at xsbt.boot.Boot$.runImpl(Boot.scala:25)
    at xsbt.boot.Boot$.main(Boot.scala:15)
    at xsbt.boot.Boot.main(Boot.scala)
[error] AttributeKey ID collisions detected for: 'scripted-scalas' (sbt.ScriptedPlugin$ScriptedScalas, sbt.ScriptedPlugin$ScriptedScalas)
`

I've cleaned up the .ivy2 folder and checked that both use the same version of scripted.

To reproduce this cleanly, create a directory, add a project folder and in that project create a PluginBuild.scala file containing:

```
package project

import sbt._

object MyPlugins extends Build {
    lazy val root = Project("root", file("."))
        .dependsOn(webPlugin, assemblyPlugin)

    lazy val webPlugin = uri("git://github.com/siasia/xsbt-web-plugin")
    lazy val assemblyPlugin = uri("git://github.com/sbt/sbt-assembly")
}
```

Then run sbt and you're done.

**Comment by holograph** [comment] 2012-05-09 00:46
Experienced much the same with a root project referencing (ProjectRef) two projects, each of which depending on xsbt-web-plugin, via repository-hosted binary. Given what I've read on attribute collisions, I believe this is a 0.11.3 regression.

**Comment by holograph** [comment] 2012-05-11 15:55
Hmm, no it isn't. I downgraded to 0.11.2 and am still geting the same error; since I'm no longer convinced this is the same issue as reported, I'll file a separate bug report.

**Comment by harrah** [comment] 2012-05-17 02:30
Duplicate of #329.

**Closed as completed by harrah** 2012-05-17 02:30 UTC
Labels: Duplicate
