### ISSUE TITLE
Update to ncurses causes sbt to throw an exception on startup

### ISSUE THREAD

**Issue by amuttsch** [sbt/sbt#3240] opened 2017-06-02 14:00 UTC
After upgrading `ncurses`, starting `sbt` shows the following error: 

```
amu ~ >sbt
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:580)
at java.lang.Integer.valueOf(Integer.java:766)
at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:233)
...
```

This is because of a recent update to `ncurses`: http://invisible-island.net/ncurses/NEWS.html#index-t20170506
```
    + modify tic/infocmp display of numeric values to use hexadecimal when
          they are "close" to a power of two, making the result more readable.
```

## steps

I'm using Arch Linux and have ncurses updated from `6.0+20170429-1` to `6.0+20170527-1`. Just run `sbt` after installing the newest version and the error will appear.

## problem

`sbt` uses `jline` for some terminal stuff. `jline` itself uses the `infocmp` utility provided by `ncurses` to determine terminal capabilities. It didn't expect a hex value and only parsed decimal values. This behaviour was already fixed: https://github.com/jline/jline2/commit/c1b1676de1803278289af0622ad202f1c7a526ec

`sbt` should update its `jline` dependency to include the fix.

## expectation

`sbt` should start without issues.

## notes
Using sbt version `0.13.15`.

Is it possible to force `sbt` to use a locally compiled version of `jline`?

Stackoverflow issue: https://stackoverflow.com/q/44317384/2014080
jline issue: https://github.com/jline/jline2/issues/281

**Comment by eed3si9n** [comment] 2017-06-02 14:09
You could try putting the following in `project/plugins.sbt`:

```
dependencyOverrides += "jline" % "jline" % "2.15-SNAPSHOT"
```

but I'm not sure if it would fix because the metabuild still needs to load.

**Comment by amuttsch** [comment] 2017-06-02 14:19
Thanks for the fast reply. Unfortunately, it still throws the exception. I will stay on ncurses version `6.0+20170429-1` for now until this issue is resolved :)

Edit: I forgot to mention the version: I'm using `0.13.15`.

**Comment by eatobin** [comment] 2017-06-02 14:57
Thank you @amuttsch for posting this and your reply on StackOverflow. I will watch for developments. Appreciated. :-)

**Comment by BardurArantsson** [comment] 2017-06-03 03:46
Yeah, I think we'll need a new release of jline. I took the liberty of submitting https://github.com/jline/jline3/issues/127

**Comment by BardurArantsson** [comment] 2017-06-03 03:48
Another potential workaround would be putting

```
-Djline.terminal=jline.UnsupportedTerminal
```

in the `_JAVA_OPTIONS` env var. That has some unpleasant side effects, though: You lose editing + up/down arrow + color + every single "Resolving ..." line will be printed to console. So only really usable if you're using sbt non-interactively.

**Comment by eed3si9n** [comment] 2017-06-04 05:27
- http://lists.gnu.org/archive/html/bug-ncurses/2017-06/msg00000.html
- http://lists.gnu.org/archive/html/bug-ncurses/2017-06/msg00001.html

**Comment by tmccombs** [comment] 2017-06-04 15:03
I also run into this problem with the scala REPL.

**Comment by grscheller** [comment] 2017-06-06 00:14
Until the jline fixes get push out, you can temporarily "fix" the problem by downgrading ncurses after a Pacman `update:
```
    $ sudo pacman -Syu
    $ cd /var/cache/pacman/pkg
    $ sudo pacman -U ncurses-6.0+20170429-1-x86_64.pkg.tar.xz
```

**Comment by captainju** [comment] 2017-06-06 08:41
I found using `export TERM=xterm-color` better than downgrading ncurses

**Comment by wsxarcher** [comment] 2017-06-06 09:01
jline-2.14.4 is out with the fix

**Comment by amuttsch** [comment] 2017-06-06 10:06
As well as [jline-3.3.1](https://github.com/jline/jline3/releases/tag/jline-3.3.1)

**Comment by SRGOM** [comment] 2017-06-12 08:08
I know this is probably not the best place to ask but am I the only one who updates arch once a month?

**Comment by Rogach** [comment] 2017-06-13 07:52
Are there any plans to release updated version with the fix any time soon?

`export TERM=xterm-color` fixes exceptions, but breaks some other stuff on my system.

(I can make the PR if needed)

**Comment by dwijnand** [comment] 2017-06-13 10:18
@Rogach A PR would be very helpful. Thank you.

**Comment by Rogach** [comment] 2017-06-13 10:23
@dwijnand Should I make 2 PRs - one for `0.13` branch, one for `1.0.x`?

**Comment by dwijnand** [comment] 2017-06-13 10:37
That would be even more lovely! Thank you.

**Comment by gaydenko** [comment] 2017-06-13 10:59
Is it possible to force old SBT projects (when SBT version is out of control) use new `jline` version on user's system base? (that is some magic in `~/.sbt`)

**Comment by vn971** [comment] 2017-06-16 12:45
It would be great to release a bug-fix version of SBT!

**Comment by dwijnand** [comment] 2017-06-16 13:13
I think well be releasing a 0.13.16-M2 or 0.13.16 shortly, which thanks to @Rogach would have fixed this issue.

**Closed as completed by dwijnand** 2017-06-16 13:13 UTC

**Comment by vn971** [comment] 2017-06-23 07:19
If anyone notices a release, please write. (I don't know how to subscribe to github-s milestone.)

**Comment by wookietreiber** [comment] 2017-06-23 07:25
@vn971 You can follow the releases with news feed: https://github.com/sbt/sbt/releases.atom

**Comment by vn971** [comment] 2017-06-23 07:31
@wookietreiber Thanks! (subscribed)

**Comment by tmccombs** [comment] 2017-08-27 03:14
I still get this when I run `console` in sbt 0.13.16. And characters I type aren't echoed back, which makes using the console pretty difficult.

**Comment by vn971** [comment] 2017-08-27 08:05
@tmccombs did you just change the version in build.properties, or did you also change the main binary that starts SBT? You have to both, unfortunately.

**Comment by tmccombs** [comment] 2017-08-28 04:42
My sbt binary is version 1.0.0

**Comment by vn971** [comment] 2017-08-28 06:14
@tmccombs any reproducable case? Like a repo that can be cloned to see the error?

**Comment by 2m** [comment] 2017-08-29 13:36
I started getting this error after I have changed my `$TERM` from `xterm` to `xterm-256color`.

**Comment by tmccombs** [comment] 2017-08-30 02:46
hmm, this does in fact appear to be related to the `TERM` environment variable.  I get the error if TERM is one of `xterm-256color`, `xterm-termite`, `screen-256color`,  or `rxvt-unicode-256color`, I don't get the error if TERM is `xterm`, `screen`, or `rxvt-unicode`, or even `nonsense`. 

I'm guessing it has something to do with the TERM being set to a terminal that supports 256 colors.

Also, I don't get the error when I run the scala interpreter outside of sbt.

**Comment by avdv** [comment] 2017-08-30 06:52
The problem is that Scala 2.11.x and <= 2.12.2 use the old jline version which is not yet fixed. Try to upgrade to 2.12.3...

**Comment by liquidarmour** [comment] 2017-09-18 12:51
@dwijnand 
I think this is still a problem. I'm seeing it on Linux and MacOS. To replicate do the following:
> sbt new liquidarmour/akka-http-docker.g8 (just use the defaults provided)
> cd akka-http-docker (the default project name)
> sbt test

The terminal no longer echoes the inputs.

I have sbt 1.0.1 installed and as you can see Scala 2.12.3 with sbt version for the project of 1.0.1.

**Comment by avdv** [comment] 2017-09-18 14:35
@liquidarmour I cannot reproduce your problem. Are you seeing any errors from JLine or anything else? Do you have any global plugins enabled?

**Comment by liquidarmour** [comment] 2017-09-18 15:34
@avdv I just checked. Intellij had put plugins in both 0.13 and 1.0 directories. I removed them and tried again. Still no luck.

Whatever I type does not appear. 

There are no errors in the build and no jline errors visible.

```
akka-http-docker> sbtVersion
[info] 1.0.1
akka-http-docker> version
[info] 0.1.0-SNAPSHOT
akka-http-docker> sbtBinaryVersion
[info] 1.0
akka-http-docker>
```

**Comment by liquidarmour** [comment] 2017-09-18 15:46
Sorry, should be more precise. The `idea.sbt` plugin was the only global plugin installed. With or without it the same behaviour ensues.

**Comment by djmcgill** [comment] 2017-09-19 09:58
Confirmed that I get the same issue with @liquidarmour 's template. After running `sbt test` the shell won't echo any more. No JLine errors.

**Comment by avdv** [comment] 2017-09-19 12:35
@liquidarmour, @djmcgill do you have any environment variables set? `TERM` maybe? which terminal emulator are you using? And which ncurses version?

I assume that this does not happen for other SBT tasks like `compile`, but only for `test`?

**Comment by liquidarmour** [comment] 2017-09-19 14:56
@avdv I have done some more testing and it appears the problem only occurs when the console exits without user interaction.

I do not have TERM set on any of my machines. 3 so far that have seen this problem.

The problem exists in all the terminals I have used on multiple OS. It happens in Linux in the standard Mint terminal and in Terminator. On MacOS it happens in the standard terminal and in iterm.

If I type `sbt test` or `sbt compile` the sbt process ends once the task is complete. The terminal is then not echoing.
If I enter the sbt repl, run any tasks I want including, test and compile, and then hit `ctrl-c` the terminal works properly. `sbt run` work as well, in that `ctrl-c` restores a good terminal.

So there is definitely a problem when the sbt process exits automatically, and not when the user forces an exit.

**Comment by avdv** [comment] 2017-09-20 09:32
Which sbt script are you using? The original or the one from sbt-extras ?

Could you run the sbt script with bash in verbose mode:
```
bash -v sbt
```
and post the output?

**Comment by liquidarmour** [comment] 2017-09-20 10:18
```
~/liquidarmour/akka-http-docker $ bash -v sbt
#!/bin/sh
if [ -f "$HOME/.sbtconfig" ]; then
  echo "Use of ~/.sbtconfig is deprecated, please migrate global settings to /usr/local/etc/sbtopts" >&2
  . "$HOME/.sbtconfig"
fi
exec "/usr/local/Cellar/sbt/1.0.1/libexec/bin/sbt" "$@"
[info] Loading global plugins from /Users/jameswilliams/.sbt/1.0/plugins
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/jameswilliams/liquidarmour/akka-http-docker/project
[info] Loading settings from build.sbt,version.sbt ...
[info] Set current project to akka-http-docker (in build file:/Users/jameswilliams/liquidarmour/akka-http-docker/)
[info] sbt server started at 127.0.0.1:5350
akka-http-docker> c~/liquidarmour/akka-http-docker $
~/liquidarmour/akka-http-docker $
~/liquidarmour/akka-http-docker $ bash -v sbt test
#!/bin/sh
if [ -f "$HOME/.sbtconfig" ]; then
  echo "Use of ~/.sbtconfig is deprecated, please migrate global settings to /usr/local/etc/sbtopts" >&2
  . "$HOME/.sbtconfig"
fi
exec "/usr/local/Cellar/sbt/1.0.1/libexec/bin/sbt" "$@"
[info] Loading global plugins from /Users/jameswilliams/.sbt/1.0/plugins
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/jameswilliams/liquidarmour/akka-http-docker/project
[info] Loading settings from build.sbt,version.sbt ...
[info] Set current project to akka-http-docker (in build file:/Users/jameswilliams/liquidarmour/akka-http-docker/)
[info] Formatting 2 Scala sources {file:/Users/jameswilliams/liquidarmour/akka-http-docker/}root(test) ...
[info] Formatting 2 Scala sources {file:/Users/jameswilliams/liquidarmour/akka-http-docker/}root(compile) ...
[info] Reformatted 2 Scala sources {file:/Users/jameswilliams/liquidarmour/akka-http-docker/}root(compile).
[info] Reformatted 2 Scala sources {file:/Users/jameswilliams/liquidarmour/akka-http-docker/}root(test).
[info] Compiling 1 Scala source to /Users/jameswilliams/liquidarmour/akka-http-docker/target/scala-2.12/classes ...
[info] Done compiling.
[info] Run completed in 49 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[success] Total time: 7 s, completed 20-Sep-2017 11:16:55
```
Note the first run release the terminal properly. The second does not.

**Comment by avdv** [comment] 2017-09-20 14:09
Oh, your sbt script is not a symlink to the sbt launcher script, so not much to see here. Could you do the same for the real script?
```
bash -v "/usr/local/Cellar/sbt/1.0.1/libexec/bin/sbt" test
```
I suspect that there will be a stty call which messes up the terminal after SBT has run...

**Comment by avdv** [comment] 2017-09-21 08:42
@liquidarmour @djmcgill SBT 1.0.2 is out, which seems to fix the bug you are seeing: https://github.com/sbt/sbt/pull/3507

**Comment by djmcgill** [comment] 2017-09-21 08:49
I'll update and report back @avdv

**Comment by liquidarmour** [comment] 2017-09-21 13:53
OK. Looks like we have made progress. 

Updating the sbt version in the project fixes the problem. The installed version of 1.0.1 works properly as long as the project has version 1.0.2

:-)

@avdv Thanks for your help.

**Comment by dwijnand** [comment] 2017-09-21 16:55
Nicely done @avdv.
