### ISSUE TITLE
jcenter is in the Linux resolvers, but not the windows one

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2253] opened 2015-10-25 00:04 UTC
I've just had some failures resolving some artefacts, only on Windows, because they are hosted on jcenter. https://ci.appveyor.com/project/fommil/ensime-server/build/1.0.223

It looks like jcenter is added via some property files rather than in code (am I right?), which might be ignored by the windows launcher.

**Comment by fommil** [comment] 2015-10-25 00:21
This is somewhat related to #2217

I'm actually quite surprised that you added jcenter to the default repository list. I wasn't aware of that, and I would really like you to consider making this opt-in.

As it stands, the workaround is to either:
1. hacky `fullResolvers -= Resolver.jcenterRepo,`
2. set up user-wide `.sbt/repositories`
3. set up project-level `repositories` file, passing properites via `sbt-extras` `.jvmopts`
4. maybe you want jcenter, in which case add it to resolvers so that you don't break things for your windows developers and downstream users

The most important point from this version of the ticket is that the repository list is different for Linux and Windows, so please make it consistent.

**Comment by eed3si9n** [comment] 2015-10-28 07:43
Thanks for the report. This is likely a duplicate of #2181 (I think I messed up the packaging of Windows installer somehow).

**Comment by fommil** [comment] 2015-10-28 07:49
BTW, we discovered this via our AppVeyor CI. Not sure what testing you have but it's worth looking into.

**Comment by eed3si9n** [comment] 2015-12-24 17:06
#2181 is now fixed.

**Closed as completed by eed3si9n** 2015-12-24 17:06 UTC
