### ISSUE TITLE
Binary releases are missing licenses

### ISSUE THREAD

**Issue by sbahling** [sbt/sbt#4280] opened 2018-07-23 08:13 UTC
The main LICENSE file of the source stipulates:

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

But I can't find the LICENSE within the binary archives released on github
(e.g. https://github.com/sbt/sbt/releases/tag/v1.1.6)

Also I guess the licenses under the licenses directory should also be included.

**Comment by eed3si9n** [comment] 2018-07-23 16:44
Duplicate of #1722. We should try to fix this in the next release.

**Closed as completed by eed3si9n** 2018-07-23 16:44 UTC
