### ISSUE TITLE
SBT Unaware of Java 9 Runtime

### ISSUE THREAD

**Issue by kolotyluk** [sbt/sbt#4104] opened 2018-04-18 17:46 UTC
(See the guidelines for contributing, linked above)

## steps

sbt clean

The Java Development Kit (JDK) installation you have is not up to date.
sbt requires at least version 6+, you have
version 0

Please go to http://www.oracle.com/technetwork/java/javase/downloads/ and download
a valid JDK and install before running sbt.

## problem

java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

## expectation

SBT should not report such an error when Java 9 is installed.

## notes

sbt version: 1.1.4

**Comment by jessicah** [comment] 2018-04-19 23:00
If this is on Windows, this is a problem with sbt.bat not supporting paths with spaces. The fix is to edit sbt.bat and wrap uses of %_JAVACMD% with double quotes.

**Comment by kolotyluk** [comment] 2018-04-20 23:57
Looking at the sbt.bat, it's is not clear that is the problem. It seems to be aware of Java 9, but is still broken. It's not clear if this has ever been tested. Here is the sbt.bat from my 1.1.4 release.


[sbt.zip](https://github.com/sbt/sbt/files/1933949/sbt.zip)

**Comment by jessicah** [comment] 2018-04-21 03:17
I had to fix locally with same version. I've also submitted pull request to
the installer repo. It's the version check line is only one missing double
quotes.

**Comment by dwijnand** [comment] 2018-04-23 05:49
> you have
> version 0

assuming the root cause here is the same, it's fixed in https://github.com/sbt/sbt-launcher-package/pull/228, by @jessicah! coming in sbt 1.1.5.

**Comment by dwijnand** [comment] 2018-05-15 09:47
1.1.5 is out!

**Closed as completed by dwijnand** 2018-05-15 09:47 UTC
Labels: Merged Upstream, area/runner-script
