### ISSUE TITLE
Windows sbt.bat verbose (-V) doesn't format -XX:ReservedCodeCacheSize=128m, --XX:MaxPermSize=256m on same line

### ISSUE THREAD

**Issue by er1c** [sbt/sbt#5176] opened 2019-10-10 14:38 UTC
## steps
sbt version: 1.3.3

## problem

When enabling verbose (`-V`) the -XX flags with an `=` argument are formatted on multiple lines.

```bash
[warn] four warnings found
example.test.SbtRunnerTest Executing command line:
"C:/Users/travis/.jabba/jdk/adopt@1.8.0-222\bin\java.exe"
-Dfile.encoding=UTF-8
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize
128m
-XX:MaxPermSize
256m
-cp "C:\Users\travis\build\sbt\sbt-launcher-package\target\universal\stage\bin\sbt-launch.jar" xsbt.boot.Boot
```

## expectation

```bash
[warn] four warnings found
example.test.SbtRunnerTest Executing command line:
"C:/Users/travis/.jabba/jdk/adopt@1.8.0-222\bin\java.exe"
-Dfile.encoding=UTF-8
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-XX:MaxPermSize=256m
-cp "C:\Users\travis\build\sbt\sbt-launcher-package\target\universal\stage\bin\sbt-launch.jar" xsbt.boot.Boot
```

## notes

This is the famous/infamous windows argument parsing bug (https://blogs.oracle.com/quinn/a-little-trick-with-windows-bat-scripts-argument-processing-and-equals-signs)

We have some special logic for `-D` variables that needs to be expanded to also include `-X`: https://github.com/sbt/sbt-launcher-package/blob/master/src/universal/bin/sbt.bat#L536-L544

**Comment by eed3si9n** [comment] 2019-10-11 13:56
The formatting `-V` is a cosmetic nice to have, so I wouldn't call this a bug.
I spent too much time working on that and there's no silver bullet that can handle both quoting around file paths and `=`, so I would say whatever we have is ok. I am not sure if we can add special handling for `-X` since not all parameters would have `=`.

**Comment by er1c** [comment] 2019-10-11 14:00
Should be easy to add, just need to check for either `-D` *or* `-X`.  It loosely aligns with the `-S-X` and `-J-X` functionality: https://github.com/sbt/sbt/issues/5179 - since they would likely have the same cosmetic issue.

**Comment by eed3si9n** [comment] 2019-10-11 14:05
If you just admit all `-X` for equaling, then wouldn't you end up with

```
-Xms1024m=-Xmx1024m
```

? Part of the problem is that `=` is already parsed away at that point.

**Comment by er1c** [comment] 2019-10-11 14:24
It will have to be solved as part of the `:args_loop` for the other ticket.

Might need to add an argument when calling `:echolist` to indicate if it is an "options" list since we know (I think?) that all `SBT_OPTS` or `JAVA_OPTS` must start with a hyphen, otherwise if the next arg doesn't start with a hyphen, then it should be treated as a value for the previous argument.  The assumption here is that all `-X` arguments would always use the `=` if they have a value argument.  The bit of googling I've done seems to support this, but I guess there is some additional research there that has to be done to convince myself that's safe to assume.

**Comment by eed3si9n** [comment] 2019-10-11 16:40
Also I don't think this needs to be part of 1.3.4.

**Comment by michaelh0911** [comment] 2019-11-07 15:31
I had make a patch of sbt.bat of release 1.3.3.

It can handle -D and -XX with an = argument. I also fix the problem that only the first option of SBT_OPTS and JAVA_OPTS got processed.

Please see attached file which is sbt.bat
[sbt.txt](https://github.com/sbt/sbt/files/3820338/sbt.txt)

**Comment by er1c** [comment] 2019-11-07 16:08
@michaelh0911 do you want to make a pull request?  https://github.com/sbt/sbt-launcher-package/blob/master/src/universal/bin/sbt.bat

**Comment by michaelh0911** [comment] 2019-11-08 02:42
> 
> 
> @michaelh0911 do you want to make a pull request? https://github.com/sbt/sbt-launcher-package/blob/master/src/universal/bin/sbt.bat

Just did it
https://github.com/sbt/sbt-launcher-package/pull/306

**Comment by SethTisue** [comment] 2023-04-28 18:49
https://github.com/sbt/sbt-launcher-package/pull/306 was merged. can this be closed now?

**Closed as completed** 2023-04-29 05:45 UTC
Labels: area/runner-script, area/windows
