### ISSUE TITLE
Terminal reset required after `sbt about` (or any other command)

### ISSUE THREAD

**Issue by jeffrey-aguilera** [sbt/sbt#3528] opened 2017-09-14 19:21 UTC
(See the guidelines for contributing, linked above)

## steps

Using `sbt` 1.0.1, run `sbt about`

## problem

On macOS, the terminal echo is lost, requiring a `reset`.

## expectation

On any OS, the terminal echo is properly restored, requiring no operation.

## notes

sbt version: *1.0.0*

This is an adoption blocker.

**Comment by eed3si9n** [comment] 2017-09-14 19:44
Duplicate of https://github.com/sbt/sbt/issues/3453.
We'll hopefully issue hotfix release soon.

**Closed as completed by eed3si9n** 2017-09-14 19:44 UTC
