### ISSUE TITLE
jcenter is unreliable

### ISSUE THREAD

**Issue by MasseGuillaume** [sbt/sbt#2217] opened 2015-09-21 20:51 UTC
missing jar:
https://travis-ci.org/slamdata/quasar/builds/81045851
https://travis-ci.org/slamdata/quasar/builds/81093558
https://travis-ci.org/slamdata/quasar/builds/81097293

500 errors:
https://travis-ci.org/slamdata/quasar/builds/81462446

currently it's the first resolver

```
> show fullResolvers
ArrayBuffer(
  Raw(ProjectResolver(inter-project, mapped: )),   
  FileRepository(local,FileConfiguration(true,None),Patterns(ivyPatterns=List(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=List(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false)),
  jcenter: https://jcenter.bintray.com/,
  public: https://repo1.maven.org/maven2/,
  sonatype-releases: https://oss.sonatype.org/content/repositories/releases,
  sonatype-releases: https://oss.sonatype.org/content/repositories/releases,
  sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots,
  JBoss repository: https://repository.jboss.org/nexus/content/repositories/,
  Scalaz Bintray Repo: http://dl.bintray.com/scalaz/releases,
  bintray/non: http://dl.bintray.com/non/maven
)
```

**Comment by jedesah** [comment] 2015-09-21 20:54
:+1: Is there a particular reason why JCenter was added as the first resolver? If not, it might make sense to relegate them to lower priority in order to avoid flakiness issues with sbt builds.

**Comment by eed3si9n** [comment] 2015-09-21 22:14
In #1938 @jsuereth  says:

> - Bintray is now looked in first for all artifacts, as it's generally faster.

Maybe we should compare general availability of the two services as well as performances for typical builds in resolving and downloading all JARs from scratch. (latency and bandwidth)

**Comment by MasseGuillaume** [comment] 2015-09-22 16:11
from Bintray support: 

> org/http4s/http4s-blazeclient_2.11/0.8.6/ is missing the jar file.
> 
> it's here on maven central http://search.maven.org/remotecontent?filepath=org/http4s/http4s-client_2.11/0.8.3/http4s-client_2.11-0.8.3.jar
> 
> but missing on jcenter https://jcenter.bintray.com/org/http4s/http4s-blazeclient_2.11/0.8.6/
> 
> same for 0.8.5
> see https://github.com/http4s/http4s/issues/415#issuecomment-141606616
> 
> > Hi Guillaume,
> > 
> > Thank you for reporting this.
> > When a certain version of a package that exists on jcenter by the Bintray users is requested from jcenter, we resolve the files from other remote repositories and cache it under the jcenter package.
> > In this case, you can see that jcenter is serving the artifacts: http://jcenter.bintray.com/org/http4s/http4s-blazeclient_2.10/0.8.6/http4s-blazeclient_2.10-0.8.6.jar.
> > Which means that it was resolved from a remote repository and will be cached in jcenter.
> > 
> > Please let us know if you stumble upon a file that is supposed to be in jcenter but is not available for download.
> > 
> > Regards,
> > Itamar
> > JFrog Support
> > that's not the same artifact this is compiled for scala 2.10
> 
> the artifact I wanted was 
> http://jcenter.bintray.com/org/http4s/http4s-blazeclient_2.11/0.8.6/http4s-blazeclient_2.11-0.8.6.jar
> 
> it failed to download multiple times
> https://travis-ci.org/slamdata/quasar/builds/81093558#L932
> https://travis-ci.org/slamdata/quasar/builds/81097293#L943
> https://travis-ci.org/slamdata/quasar/builds/81045851#L932
> 
> now it look like it's available
> 
> I have to disable jcenter as a resolver because it makes our builds fails.
> 
> > Hi Guillaume,
> > 
> > Thank you for the update.
> > This behaviour can be explained:
> > If the requested artifact is not in jcenter, Bintray will try to retrieve it from a remote repository which is hosted on an Artifactory instance. If this artifact can be found in Artifactory, it will be server immediately to the client and later will also be cached in jcenter. But if the file was not found in Artifactory, the response to the client will be a 404 not found, but Artifactory will still try to look it up in it's remote repositories, and cache it locally in Artifactory if found. So the next request for this artifact from jcenter should get the file.
> > 
> > Please let us know if this sounds right to you.

**Comment by MasseGuillaume** [comment] 2015-09-22 16:14
if the artifact is NotFound does it try the other resolvers ?

**Comment by jedesah** [comment] 2015-09-22 16:57
So if I understand correctly, they are saying our software sucks, if you encounter flakiness, just try again, it should work eventually?

**Comment by slandelle** [comment] 2015-09-25 16:36
Same problem here: [our build fails](https://travis-ci.org/gatling/gatling-highcharts/builds/78241658#L497) because jcenter fails to properly deliver the artifacts, while they are fine on maven central.

**Comment by jbaruch** [comment] 2015-09-25 23:14
Guys, I am with JFrog (the company behind JCenter) and I am really sorry for the troubles you encountered in the last days. We have been experiencing intermittent ddosing attacks during the 18-21 which may explain the high error rates, which since then should be resolved.

For the last report (by @slandelle) we cannot see anything suspicious in our log and if this still happens randomly we'd love to investigate and get if fixed as quickly as possible so any additional information you can provide (such as exact time and IP address) would be great.

**Comment by MasseGuillaume** [comment] 2015-09-26 00:11
@jbaruch the ddos is one issue

this behavior is another one

> > If the requested artifact is not in jcenter, Bintray will try to retrieve it from a remote repository which >> is hosted on an Artifactory instance. If this artifact can be found in Artifactory, it will be server 
> > immediately to the client and later will also be cached in jcenter. But if the file was not found in 
> > Artifactory, the response to the client will be a 404 not found, but Artifactory will still try to look it up 
> > in it's remote repositories, and cache it locally in Artifactory if found. So the next request for this 
> > artifact from jcenter should get the file.

For our builds to succed, any request to jcenter should return 200 right away. The pom was served but not the jar. Something is not right.

**Comment by jbaruch** [comment] 2015-09-26 07:40
You are correct, the answer from support is not accurate. Bintray always returns 200 for the file it can serve (or at least it should). We are investigating why you got 404, it definitely shouldn't happen (that's why they asked for more info).

**Comment by slandelle** [comment] 2015-09-26 09:54
@jbaruch I confirm my build is back. Thanks!

**Comment by jbaruch** [comment] 2015-09-27 04:51
Sorry again guys. Shit usually happens in batches, as you all know.

**Comment by jbaruch** [comment] 2015-09-27 22:52
Further investigation from our end (jfrog) shows that the reason for this issue is with SBT not following redirection responses (302..307) for HEAD requests. While GET requests are automatically followed by SBT, HEAD requests are not. We can see that SBT first sends a HEAD request, and when the resource is not in JCenter it does not follow the 302 response.
This looks like a bug to me, since while the spec does not mandate automatic request redirection, I'd expect redirection behavior to be consistent across HEAD and GET.
Does this make sense?

**Comment by dwijnand** [comment] 2015-09-28 05:59
@jbaruch Can you provide an example URL so we can try and reproduce it please?

**Comment by dwijnand** [comment] 2015-09-28 08:51
If this is a seriously blocker a workaround is:

``` scala
fullResolvers ~= {_.filterNot(_.name == "jcenter")}
```

Credit to @xuwei-k.

**Comment by MasseGuillaume** [comment] 2015-09-28 14:20
@dwijnand `fullResolvers -= "jcenter" at "https://jcenter.bintray.com/"`

**Comment by dwijnand** [comment] 2015-09-28 14:41
That's a handy operator to use :D

**Comment by dwijnand** [comment] 2015-09-28 19:14
@jbaruch an example URL would allow me to find a fix to this issue that keeps jCenter as the first resolver as opposed to taking it out.

**Comment by MasseGuillaume** [comment] 2015-09-28 19:25
https://jcenter.bintray.com/org/http4s/http4s-blazeclient_2.11/0.8.5/

the pom is available but not the jar

**Comment by dwijnand** [comment] 2015-09-28 19:32
Ok, so that's now available. But I capture the curl output:

```
$ curl -LI https://jcenter.bintray.com/org/http4s/http4s-blazeclient_2.11/0.8.5/http4s-blazeclient_2.11-0.8.5.jar
HTTP/1.1 302
Server: nginx
Date: Mon, 28 Sep 2015 19:30:38 GMT
Content-Type: application/octet-stream
Content-Length: 0
Connection: keep-alive
Location: http://repo.jfrog.org/artifactory/libs-release-bintray/org/http4s/http4s-blazeclient_2.11/0.8.5/http4s-blazeclient_2.11-0.8.5.jar?referrer

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Disposition: attachment; filename="http4s-blazeclient_2.11-0.8.5.jar"; filename*=UTF-8''http4s-blazeclient_2.11-0.8.5.jar
Content-Length: 85791
Content-Type: application/java-archive
Date: Mon, 28 Sep 2015 19:30:38 GMT
ETag: 8849746cb6f2494c56ea743afea10f11248ea0bb
Last-Modified: Thu, 27 Aug 2015 00:50:04 GMT
Server: nginx
X-Artifactory-Filename: http4s-blazeclient_2.11-0.8.5.jar
X-Artifactory-Id: repo.jfrog.org
X-Checksum-Md5: f592cd70704001dd849e96385b0010d5
X-Checksum-Sha1: 8849746cb6f2494c56ea743afea10f11248ea0bb
X-Node: nginx1c.prod-use1
Connection: keep-alive
```

**Comment by eed3si9n** [comment] 2015-09-28 19:45
@jbaruch Thanks for looking into this.

> Further investigation from our end (jfrog) shows that the reason for this issue is with SBT not following redirection responses (302..307) for HEAD requests. While GET requests are automatically followed by SBT, HEAD requests are not. We can see that SBT first sends a HEAD request, and when the resource is not in JCenter it does not follow the 302 response.

Both Typesafe Repo (https://repo.typesafe.com/) and sbt Plugin Repo (https://repo.scala-sbt.org/) are Nginx box that redirects to Bintray using 302. If what you're describing is the behavior of sbt (and its underlying Apache Ivy), wouldn't it break for Typesafe Repo artifacts as well? 

> ```
> Location: http://repo.jfrog.org/artifactory/libs-release-bintray/org/http4s/http4s-blazeclient_2.11/0.8.5/http4s-blazeclient_2.11-0.8.5.jar?referrer
> ```

Could the problem be caused by **https** redirecting to **http**?

**Comment by jbaruch** [comment] 2015-09-28 21:13
Thanks for the info. Let us look into it. Will be back soon with findings.

**Comment by jbaruch** [comment] 2015-09-29 20:03
Guys, @eed3si9n  was right, thanks for the triage. Found and fixed, should be OK now.

**Comment by eed3si9n** [comment] 2015-09-29 20:07
Thanks @jbaruch for the fix. Props to @dwijnand for running `curl` in time.

Anyone who had previous issues, plz try using JCenter again and report issues here.

**Comment by dwijnand** [comment] 2015-09-29 20:08
Was it the redirect?

**Comment by jbaruch** [comment] 2015-09-29 20:25
Yup, redirect.

**Comment by larsrh** [comment] 2015-10-01 19:08
Some more problems: JCenter appears to be serving broken artifacts occasionally. A couple of days ago, sbt successfully resolved an artifact only to find out that its checksum didn't match. JCenter support fixed this after a while. The artifact was correct on Sonatype and Maven Central the whole time.

**Comment by jbaruch** [comment] 2015-10-02 09:47
@larsrh Not sure I understood. You mention "appears to be serving broken artifacts occasionally" as something happening on a regular basis. Does it happen frequently? Or it was one-time indecent as you describe referring to a single artifact that was fixed by the support?

**Comment by larsrh** [comment] 2015-10-03 16:44
So far I have observed one reproducible case, where my Travis CI build failed. Bintray support fixed the problem on second attempt. I had another case locally on my machine which I fixed by removing the JCenter resolver; I can't reproduce it any longer. What strikes me as odd is that these mismatches haven't been caught on the server side.

**Comment by jbaruch** [comment] 2015-10-05 21:47
Can I assume it was one-time event then?

**Comment by eed3si9n** [comment] 2015-12-14 01:28
More issues of missing JAR on JCenter.

https://jcenter.bintray.com/com/typesafe/akka/akka-http-testkit-experimental_2.11/2.0-M2/

<img width="979" alt="https___jcenter_bintray_com_com_typesafe_akka_akka-http-testkit-experimental_2_11_2_0-m2_" src="https://cloud.githubusercontent.com/assets/184683/11770932/a235a428-a1d7-11e5-8cce-e8b54dea1396.png">

https://oss.sonatype.org/content/repositories/public/com/typesafe/akka/akka-http-testkit-experimental_2.11/2.0-M2/

<img width="933" alt="index_of__repositories_public_com_typesafe_akka_akka-http-testkit-experimental_2_11_2_0-m2" src="https://cloud.githubusercontent.com/assets/184683/11770913/63d68e72-a1d7-11e5-9442-c6c95dd69753.png">

I think we need to reverse the change made in 0.13.9, and hit Maven Central first, instead of using JCenter for common artifacts.

**Comment by slandelle** [comment] 2015-12-14 07:13
Same thing goes with latest Jackson:
- jar missing on jCenter: https://jcenter.bintray.com/com/fasterxml/jackson/core/jackson-databind/2.7.0-rc2/
- jar available on maven central: https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.7.0-rc2/

:+1: for reversing the change (that's [what I did in my build](https://github.com/gatling/gatling-build-plugin/commit/05b9c8547c9b381ec7ba1bfc00fc8777b562246c)).

**Comment by eed3si9n** [comment] 2015-12-17 07:50
For some period of time JCenter was returning 503.

```
$ curl -L -i https://jcenter.bintray.com/com/typesafe/play/play-netty-utils/2.4.2-bin-rp-15v09p03/play-netty-utils-2.4.2-bin-rp-15v09p03.pom
HTTP/1.1 302 
Server: nginx
Date: Thu, 17 Dec 2015 07:27:18 GMT
Content-Length: 0
Connection: keep-alive
Location: https://repo.jfrog.org/artifactory/libs-release-bintray/com/typesafe/play/play-netty-utils/2.4.2-bin-rp-15v09p03/play-netty-utils-2.4.2-bin-rp-15v09p03.pom?referrer

HTTP/1.1 503 Service Unavailable: Back-end server is at capacity
Content-Length: 0
Connection: keep-alive
```

**Closed as completed** 2016-02-26 22:02 UTC
Labels: area/library_management
