### ISSUE TITLE
[Bug]Serialization issue : four is enough, five is too much

### ISSUE THREAD

**Issue by Shastick** [sbt/sbt#513] opened 2012-08-03 10:14 UTC
Hello,

I've run in a strange issue with sbt : 
I'm serializing an object containing a set of other objects. (cf. the attached code). I can run this without any issue through Eclipse, but when I run it through sbt (tested on 0.11.3), the following thing happens :
- if the set contains only four elements, everything runs fine.
- when the set has more than four elements, I get the following exception :

```
java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashSet$SerializationProxy to field debug.Holder.steps of type scala.collection.immutable.Set in instance of debug.Holder
```

```
object SerialTest extends App {
    /**
     * Comment out one of the five elements and sbt will run this fine,
     * but will crash if 5 or more elements are present. 
     */

    val stepSet = Set(new Element("one"),
                    new Element("two"),
                    new Element("three"),
                    new Element("four"),
                    new Element("five")) 

    val hold = new Holder(stepSet)

    val baos = new ByteArrayOutputStream
    val oos = new ObjectOutputStream(baos)

    oos.writeObject(hold)

    val bytes = baos.toByteArray()

    val bais = new ByteArrayInputStream(bytes)
    val ois = new ObjectInputStream(bais)

    ois.readObject() match {
      case s: Holder => println(s.steps) 
    }

}

class Holder(val steps: Set[Element]) extends Serializable {

}

class Element(val v1: String) extends Serializable {

}
```

This code causes the exception, and simply commenting one of the Element's out makes it run without a problem,

**Comment by harrah** [comment] 2012-08-03 14:29
Duplicate of #136, #163

**Closed as completed by harrah** 2012-08-03 14:29 UTC
Labels: not-a-🐛, Duplicate

**Comment by Shastick** [comment] 2012-08-03 14:33
Aw I was exited about my first bug report, sorry for not checking if it had been reported before :-)
