### ISSUE TITLE
Consider removing *Compat from testFrameworks

### ISSUE THREAD

**Issue by ijuma** [sbt/sbt#66] opened 2011-06-21 21:41 UTC
For test:compile in a medium-sized project, YourKit reports that TestFramework.create takes 10% of the time.

In Defaults.scala:

```
testFrameworks in GlobalScope :== {
  import sbt.TestFrameworks._
  Seq(ScalaCheck, Specs2, Specs, ScalaTest, ScalaCheckCompat, ScalaTestCompat, SpecsCompat, JUnit)
},
```

Maybe we want to remove the *Compat ones?

**Comment by harrah** [comment] 2011-06-22 13:06
Since you can override this yourself in a project, do you notice an actual difference in execution time?

**Comment by ijuma** [comment] 2011-06-23 01:37
I added some instrumentation like so:

```
loadedTestFrameworks <<= (testFrameworks, streams, testLoader) map { (frameworks, s, loader) =>
  val startTime = System.nanoTime
  val m = frameworks.flatMap(f => f.create(loader, s.log).map( x => (f,x)).toIterable).toMap
  println("End " + ((System.nanoTime - startTime) / 1000000.0))
  m
}
```

Then I executed test:compile. The results without changing testFrameworks:

End 2.563492
End 17.53423
End 12.455988
End 10.95388
End 11.986022
End 23.721038
End 33.159863
End 67.568948
End 91.611512
End 15.454221
End 18.664711
End 34.610366
End 19.211399
End 31.851488
End 28.20278

So, 420ms are spent in that code.

I then added to my build file:

```
testFrameworks := Seq(TestFrameworks.ScalaCheck, TestFrameworks.Specs, TestFrameworks.ScalaTest)
```

The results became worse:

End 56.566838
End 9.037073
End 19.845867
End 12.671643
End 10.416767
End 69.985547
End 118.04907
End 119.324735
End 139.583516
End 12.107813
End 18.100182
End 42.082706
End 40.440119
End 27.66444
End 13.808065

710ms.

If I add testFrameworks := Seq() to the build file though, results get much better:

End 10.553686
End 0.009976
End 0.006517
End 0.008945
End 0.010753
End 0.010988
End 0.008612
End 0.011053
End 28.699278
End 0.013013
End 0.008921
End 0.007734
End 0.015344
End 0.007665
End 0.011637

I'm a bit surprised at how expensive classloading is in this case and I don't understand why the second set of results are worse than the first. Do you have an idea?

**Comment by harrah** [comment] 2011-06-23 03:07
Not sure since I can't reproduce it.  My times are in the single ms on a small project and the shorter Seq is faster, so I assume it varies with the test frameworks used and actual classpaths.  In any case, I wouldn't expect much work to be done for the Compat pieces because the framework's classes aren't on your classpath and therefore they will throw ClassNotFoundException (caught in create) and no actual class loading will occur for them.  I'm closing this because of this (I didn't think of it at first.), but we can reopen if necessary.

Because the common use case is running tests and not just compiling them (as far as I'm aware), the class loading is simply done sooner than it normally would be.  Also, the reason this gets run for a plain test:compile is to populate tab completion for test-only.  You can disable it with the following (fairly obscure) setting:

``` scala
seq( inConfig(Test)( Seq(definedTests <<= Defaults.detectTests) ) : _* )
```

(Basically, the default definition of definedTests has 'triggeredBy compile' and this omits that.  definedTests is the cause of loadedTestFrameworks getting run.)

**Closed as completed by harrah** 2011-06-23 03:07 UTC
Labels: not-a-🐛

**Comment by ijuma** [comment] 2011-06-23 08:01
"Because the common use case is running tests and not just compiling them (as far as I'm aware), the class loading is simply done sooner than it normally would be."

That is certainly not the case for me. I use test:compile all the time because I want to make sure my tests compile too when I am modifying code.

**Comment by ijuma** [comment] 2011-06-23 08:23
Also, during development, I generally run my tests from IDEA instead of SBT. I think this use-case is not uncommon. Thanks for the setting, it helps quite a bit. :) The output then becomes:

End 29.272883
