### ISSUE TITLE
Scope not respected when re-including a dependency with different classifier

### ISSUE THREAD

**Issue by wpalmeri** [sbt/sbt#1500] opened 2014-08-05 04:29 UTC
When a project depends on both the regular as well as test-classified artifact, the scope is not respected when generating a POM file. For example, given the following build.sbt:

``` scala
name := "Scope Bug"
version := "0.1"
scalaVersion := "2.11.2"
libraryDependencies ++= Seq(
  "com.foo" %% "foo" % "1.0",
  "com.foo" %% "foo" % "1.0" % "test" classifier "tests",
  "com.foo" %% "bar" % "1.0" % "test" classifier "tests"
)
```

running `make-pom` results in:

``` xml
<?xml version='1.0' encoding='UTF-8'?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>classifier-bug</groupId>
    <artifactId>classifier-bug_2.11</artifactId>
    <packaging>jar</packaging>
    <description>Classifier Bug</description>
    <version>0.1</version>
    <name>Classifier Bug</name>
    <organization>
        <name>classifier-bug</name>
    </organization>
    <dependencies>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>2.11.2</version>
        </dependency>
        <dependency>
            <groupId>com.foo</groupId>
            <artifactId>foo_2.11</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.foo</groupId>
            <artifactId>foo_2.11</artifactId>
            <version>1.0</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>com.foo</groupId>
            <artifactId>bar_2.11</artifactId>
            <version>1.0</version>
            <scope>test</scope>
            <classifier>tests</classifier>
        </dependency>
    </dependencies>
</project>
```

The second foo artifact should have the `test` scope defined, but it does not. Dropping the classifier results in only a single `foo` dependency being generated, so perhaps sbt is attempting to do some type of coalescing, but is not taking the scope into account?

This is a particularly nasty bug, as this results in downstream artifacts pulling in the test dependency in compile scope even when I try to explicitly exclude them. If you can suggest a workaround, please do let me know.

I'm happy to submit a PR, but I'm not sure where to begin looking in the source. Thanks.

**Comment by jsuereth** [comment] 2014-08-05 12:44
Here is where pom creation goes: https://github.com/sbt/sbt/blob/0.13/ivy/src/main/scala/sbt/MakePom.scala

First, though, a question:  Is Ivy correctly RESOLVING that definition?  If so, then we just need to fix the pom generation side of things.

**Comment by wpalmeri** [comment] 2014-08-05 16:40
I do believe that Ivy is resolving correctly, as when I use the dependency-graph plugin in the defining project, the compile time dependencies are correct. It's only when downstream projects that pull in the dependency via nexus/maven with the bad pom that the incorrect test deps start showing up.

**Comment by jsuereth** [comment] 2014-08-05 18:01
Ok, seems related to this, perhaps:

https://github.com/sbt/sbt/blob/0.13/ivy/src/main/scala/sbt/Ivy.scala#L540-L568

**Comment by wpalmeri** [comment] 2014-08-06 01:05
@jsuereth definitely seems related to that. The root issue could even be in [Merge Descriptors](https://github.com/sbt/sbt/blob/0.13/ivy/src/main/scala/sbt/ivyint/MergeDescriptors.scala#L17)

For anyone else interested, here's a setting to get around the bug. Can be made more generic as necessary:

``` scala
import scala.xml.{Elem, Node => XMLNode}
pomPostProcess := { (node: XMLNode) =>
        //handle bug where test scope is not added in pom when it should be.
        //modify xml where <classifier>tests</classifier> is defined, and add <scope>test</scope>
        def transformIf(n: XMLNode, pred: XMLNode=>Boolean, trans: XMLNode=>XMLNode): XMLNode =
          if (pred(n)) {
            trans(n)
          } else {
            n match {
              case e: Elem =>
                if (e.descendant.exists(pred))
                  e.copy(e.prefix, e.label, e.attributes, e.scope, false,
                    e.child.map(transformIf(_, pred, trans)))
                else e
              case _ => n
            }
          }

        val depClassifiedWithoutScope: XMLNode => Boolean = (n: XMLNode) =>
          n.label == "dependency" && n.nonEmptyChildren.find(c => c.label == "classifier" && c.child.contains(scala.xml.Text("tests"))).isDefined &&
          n.nonEmptyChildren.find(_.label == "scope").isEmpty
        val addTestScope: XMLNode => XMLNode = _ match {
          case e: Elem => e.copy(child = e.child ++ <scope>test</scope>)
          case _ => throw new Exception("should not happen")
        }
        transformIf(node, depClassifiedWithoutScope, addTestScope)
      }
```

**Comment by eed3si9n** [comment] 2016-06-11 07:26
I'm going to close this as a duplicate of #2002.
This issue was reported earlier but I think more in depth comments are made on #2002.

**Closed as completed by eed3si9n** 2016-06-11 07:26 UTC
Labels: area/maven_integration
