### ISSUE TITLE
Got "build.sbt:0: error:" when replace addSbtPlugin to RootProject (sbt 0.12.0-M2).

### ISSUE THREAD

**Issue by Atry** [sbt/sbt#425] opened 2012-04-10 15:18 UTC
I am trying to port some sbt plugin to Sbt 0.12.0-M2, I replace many `addSbtPlugin` in `project/plugins.sbt` to a `RootProject` in `project/project/PluginBuild.scala`, because the version 0.12 of these plugin are not in repository.

After some work, I got a strange error:

```
C:\Users\Atry\.sbt\staging\01e597aaee60bebc6675\build.sbt:0: error: object sbtrelease is not a member of package <root>
import _root_.sbtrelease.ReleasePlugin._, _root_.com.typesafe.sbtscalariform.ScalariformPlugin._, _root_.sbt.ScriptedPlugin._
              ^
C:\Users\Atry\.sbt\staging\01e597aaee60bebc6675\build.sbt:0: error: object typesafe is not a member of package com
import _root_.sbtrelease.ReleasePlugin._, _root_.com.typesafe.sbtscalariform.ScalariformPlugin._, _root_.sbt.ScriptedPlugin._
                                                     ^
C:\Users\Atry\.sbt\staging\01e597aaee60bebc6675\build.sbt:0: error: object ScriptedPlugin is not a member of package sbt
import _root_.sbtrelease.ReleasePlugin._, _root_.com.typesafe.sbtscalariform.ScalariformPlugin._, _root_.sbt.ScriptedPlugin._
                                                                                                             ^
[error] Type error in expression
```

This error message can be reproducted by:

```
$ git clone git://github.com/Atry/sbteclipse.git && cd sbteclipse && sbt
```

**Comment by harrah** [comment] 2012-05-01 00:55
Looks like a duplicate of #412, fixed in 0.12.0-Beta2.

**Closed as completed by harrah** 2012-05-01 00:55 UTC
Labels: Duplicate
