### ISSUE TITLE
Make sbt more user friendly!  Let it create directory structures.....etc.

### ISSUE THREAD

**Issue by cp10000** [sbt/sbt#4178] opened 2018-05-29 19:33 UTC
- [ ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps
sbt is lacking user-friendliness, for example it does not create directory structure for a project?   Why not?

## problem
sbt is lacking user-friendliness, for example it does not create directory structure for a project?

## expectation
I expect a command tool like sbt to do as much as possible on its own and never, never ask the user to do manually what sbt can do on its own.   There should be a command to create a project directory structure.   There should also be command to generate configuration file templates.

## notes
The golden rule is that a good command-line tool should never ask the user to do something that it can do on its own.   Allow the user to issue a command to create whatever needs to be created.  
 Programmer users have enough to remember!

sbt version: *insert sbt version*
all

**Comment by eed3si9n** [comment] 2018-05-29 20:31
See https://www.scala-sbt.org/1.x/docs/sbt-new-and-Templates.html.
Also this is likely a duplicate of https://github.com/sbt/sbt/issues/3949

**Closed as completed by eed3si9n** 2018-05-29 20:31 UTC
