### ISSUE TITLE
On Windows, the command line options -Dkey=val are not passed correctly

### ISSUE THREAD

**Issue by virpara** [sbt/sbt#4923] opened 2019-06-30 08:07 UTC
OS: Windows 7
sbt version: 1.2.8

When running `sbt -Dsbt.build.version=1.3.0-M4 -Dsbt.build.offline=true` in the latest copy of sbt-launcher-package repository gives the following error,
```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading project definition from G:\github\sbt-launcher-package\project
java.lang.IllegalArgumentException: requirement failed: Revision cannot be empty.
        at scala.Predef$.require(Predef.scala:233)
        at sbt.StringUtilities$.nonEmpty(StringUtilities.scala:11)
        at sbt.impl.GroupArtifactID.$percent(DependencyBuilders.scala:49)
        at $dbd25b147311c8724433$.sbtActual$lzycompute(build.sbt:28)
        at $dbd25b147311c8724433$.sbtActual(build.sbt:28)
        at $dbd25b147311c8724433$$anonfun$dist$9.apply(build.sbt:337)
        at $dbd25b147311c8724433$$anonfun$dist$9.apply(build.sbt:337)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] java.lang.IllegalArgumentException: requirement failed: Revision cannot be empty.
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
```

It works on Linux though.

After some investigation in the sbt.bat, I found that `=` is replaced with a space character. 
e.g. `-Dkey=value` command line options become `-Dkey value`.

## workaround

Put `"-Dkey=value"` in quotes because `=` is treated as whitespace.

**Comment by kwalcock** [comment] 2019-08-10 00:18
This also happens on Windows 10.  It is breaking compatability between my Linux and Windows builds.  Something simple like this shows the problem:
```sbt
name := "Test"

libraryDependencies ++= {
  val param = sys.props.get("hello")
  println("param is " + param)

  Seq()
}
```
```
sbt -Dhello=hi
```

**Comment by kwalcock** [comment] 2019-08-10 00:26
P.S.  Past versions of sbt.bat have the same problem, not just the present one.

**Comment by eed3si9n** [comment] 2019-08-10 03:09
There's a blog post on this topic - https://blogs.oracle.com/quinn/a-little-trick-with-windows-bat-scripts-argument-processing-and-equals-signs

> What worked for me was to write the for loop this way:

```
:recurse
for /F "tokens=1\*" %%a in ("%\*") do
  rem do something
  ...
  if NOT x%%b==x call :recurse %%b
)
```

If someone could research that solution and apply it to https://github.com/sbt/sbt-launcher-package/blob/master/src/universal/bin/sbt.bat, that would be awesome.

**Comment by eed3si9n** [comment] 2019-09-25 01:59
Closing this as a duplicate of #2695.

**Closed as completed by eed3si9n** 2019-09-25 01:59 UTC
Labels: help wanted, area/runner-script, area/windows, workaround exists

**Comment by kwalcock** [comment] 2019-09-25 19:53
Thanks for figuring out the relationship between these two issues.  This may allow me to work around the problem in my particular case.
