### ISSUE TITLE
Arrows keys inside sbt console does not work on Windows

### ISSUE THREAD

**Issue by Juraj-Masiar** [sbt/sbt#2031] opened 2015-05-21 14:28 UTC
When arrow "up" is pressed, "ÓH" is written. Rest of the arrows looks like this:
down: ÓP
left:ÓK
right: ÓM
If I use Shift + arrow_on_numeric_keybord, it works as expected.
This problem is present only on some specific (unknown) configurations. I have it in my Win 8.1 x64 running in Virtualbox, my colleague has in in his laptop Win. 8.1 x64.
Problem first appeared in PlayFramework version 2.3, previous 2.2.x was ok. After testing vanilla SBT I've noticed same problem.
We are using latest 0.13.8 version.

**Comment by eed3si9n** [comment] 2015-05-21 17:00
Possible duplicate of #871.

**Comment by eed3si9n** [comment] 2015-05-21 17:00
Could you try `-Dinput.encoding=Cp1252` please?

**Comment by Juraj-Masiar** [comment] 2015-05-22 08:09
Looks like it is duplicate, sorry about that, I was trying to find such topic using "ÓH" keyword.
Anyway using given encoding switch made it work again. Thanks!
Proper fix for the rest of the people using SBT/Play Framework/... would be also nice. I'm sure there is a lot of them.

**Closed as completed** 2016-01-17 00:32 UTC
Labels: Duplicate
