### ISSUE TITLE
~ is not triggering for files saved in IDEA

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#3819] opened 2017-12-17 21:13 UTC
## steps
empty project
create a `src/main/scala/a.scala` file
start `sbt ~compile`
open the file in IDEA, modify and save

## problem
nothing happens

## expectation
the file is recompiled

## notes
sbt version: 1.0.0-1.0.4
with `-Dsbt.watch.mode=nio` or `-Dsbt.watch.mode=polling`
windows 10

this is a followup to #3775

**Comment by OlegYch** [comment] 2017-12-17 21:53
i have noticed that unlike other tools IDEA updates directory modification time while saving a file in that directory
tried to reproduce that without involving idea but so far coulnd't

**Comment by tomzheng77** [comment] 2017-12-22 06:39
I'm having the same issue.
I'm using Mac OS 10.13.2.
When I save using Sublime Text, however, the changes are detected.

**Comment by Zuchos** [comment] 2018-01-04 12:14
Same issue with macOS 10.12.6 (16G1114)

**Comment by jastice** [comment] 2018-01-08 15:02
I did a little testing:
* did not reproduce with sbt 1.1.0, macOS 10.13.2 and IntelliJ 2017.3.3 EAP
* sort-of reproduced (worked only some of the time) with sbt 1.0.4, macOS 10.13.2 and IntelliJ 2017.3.3 EAP
* fully reproduced with sbt 1.1.0, Windows 10, IntelliJ 2017.3.3 EAP

I noticed that IntelliJ updates the `Birth` field in the file modifications, while other editors do not:
```
[15:58:32] jast@aeolus /Users/jast/playspace/sbt-3819/src/main/scala (0)
*** after IntelliJ modification
> gstat a.scala
  File: a.scala
  Size: 63        	Blocks: 8          IO Block: 4194304 regular file
Device: 1000004h/16777220d	Inode: 8592541163  Links: 1
Access: (0644/-rw-r--r--)  Uid: (  501/    jast)   Gid: (   20/   staff)
Access: 2018-01-08 15:58:40.755229040 +0100
Modify: 2018-01-08 15:58:39.664316791 +0100
Change: 2018-01-08 15:58:39.664747407 +0100
 Birth: 2018-01-08 15:58:39.663901670 +0100
[15:58:43] jast@aeolus /Users/jast/playspace/sbt-3819/src/main/scala (0)
> touch a.scala
[15:58:58] jast@aeolus /Users/jast/playspace/sbt-3819/src/main/scala (0)
> gstat a.scala
  File: a.scala
  Size: 63        	Blocks: 8          IO Block: 4194304 regular file
Device: 1000004h/16777220d	Inode: 8592541163  Links: 1
Access: (0644/-rw-r--r--)  Uid: (  501/    jast)   Gid: (   20/   staff)
Access: 2018-01-08 15:59:00.798703521 +0100
Modify: 2018-01-08 15:58:58.279367000 +0100
Change: 2018-01-08 15:58:58.279387631 +0100
 Birth: 2018-01-08 15:58:39.663901670 +0100
```

Not sure if that is the cause, but maybe sbt does something with these fields?

**Comment by jastice** [comment] 2018-03-09 23:03
Indeed, the problem with IntelliJ is the "safe write" feature (see https://youtrack.jetbrains.com/issue/IDEA-188003), which in facts writes changes to a temporary file, then moves it over the original, effectively recreating the file. Apparently sbt watch can't handle this case.

Disabling it in the IntelliJ Preferences / System settings fixes the sbt file watch problem.

**Comment by OlegYch** [comment] 2018-03-09 23:16
@jastice thanks that works for now

**Comment by eed3si9n** [comment] 2018-06-29 17:32
The new Close Watch based ~ fixed this, I think, so I am optimistically closing this.

**Closed as completed by eed3si9n** 2018-06-29 17:32 UTC
Labels: help wanted, area/watch
