### ISSUE TITLE
Newer version of library evicted by transitive artifact

### ISSUE THREAD

**Issue by avdv** [sbt/sbt#5648] opened 2020-06-24 09:52 UTC
## steps

SBT version: 1.2.8, also tried with 1.3.12 and `useCoursier := false`.

build.sbt:
```
lazy val root = (project in file("."))
  .settings(
    name := "Scala Seed Project",
    libraryDependencies ++= Seq(
      "com.lightbend.akka" %% "akka-stream-alpakka-sqs" % "2.0.0",
      "com.github.matsluni" %% "aws-spi-akka-http" % "0.0.9"
    )
  )
```

Running `sbt --no-global evicted` yields:
```
[info] 	* com.typesafe.akka:akka-http_2.13:10.1.12 is selected over 10.1.11
[info] 	    +- com.github.matsluni:aws-spi-akka-http_2.13:0.0.9   (depends on 10.1.12)
[info] 	    +- com.lightbend.akka:akka-stream-alpakka-sqs_2.13:2.0.0 () (depends on 10.1.11)
```

## problem

The problem occurs when upgrading alpakka SQS to the latest version, namely 2.0.1, which also depends on 
"com.github.matsluni" %% "aws-spi-akka-http" % "0.0.9" directly.

Running `sbt --no-global evicted` now yields:
```
[info]  * com.typesafe.akka:akka-http_2.13:10.1.11 is selected over 10.1.12
[info]      +- com.lightbend.akka:akka-stream-alpakka-sqs_2.13:2.0.1 () (depends on 10.1.11)
[info]      +- com.github.matsluni:aws-spi-akka-http_2.13:0.0.9   (depends on 10.1.12)
```

Only when reversing the dependencies in the Seq:
```
lazy val root = (project in file("."))
  .settings(
    name := "Scala Seed Project",
    libraryDependencies ++= Seq(
      "com.github.matsluni" %% "aws-spi-akka-http" % "0.0.9",
      "com.lightbend.akka" %% "akka-stream-alpakka-sqs" % "2.0.1"
    )
  )
```
I see the expected output:
```
[info]  * com.typesafe.akka:akka-http_2.13:10.1.12 is selected over 10.1.11
[info]      +- com.github.matsluni:aws-spi-akka-http_2.13:0.0.9   (depends on 10.1.12)
[info]      +- com.lightbend.akka:akka-stream-alpakka-sqs_2.13:2.0.1 () (depends on 10.1.11)
```

## expectation

I would expect that the newer akka-http library version 10.1.12 is choosen, regardless of the order of dependencies.

## notes

Also adding the dependency on akka-http 10.1.12 directly (after alpakka-sqs) evicted it by 10.1.11.

**Comment by eed3si9n** [comment] 2020-06-24 15:38
Thanks for the report. sbt 1.2.x uses Apache Ivy as the dependency resolver, and it emulates Maven's nearest-wins semantics (see http://eed3si9n.com/dependency-resolver-semantics) when the artifacts are on Maven style repository.

Using sbt 1.3.12 with Coursier, we get the latest-wins semantics:

```
[info] 	* com.typesafe.akka:akka-http_2.12:10.1.12 is selected over {10.1.11, 10.1.11}
[info] 	    +- com.github.matsluni:aws-spi-akka-http_2.12:0.0.9   (depends on 10.1.12)
[info] 	    +- com.lightbend.akka:akka-stream-alpakka-sqs_2.12:2.0.1 (depends on 10.1.11)
```

so as far as I'm concerned, this looks like everything working as intended (by the dependency resolvers).

**Comment by avdv** [comment] 2020-06-24 17:34
I had seen your blog post about the different resolver strategies (after creating the issue actually), but does this also explain the behavior when changing the order of the dependencies?! 

Surely, I'll re-read your post when I have some time. But this behavior is indeed horrifying, mostly because I never noticed it and were assuming everything is alright... Now it broke our service since using different akka versions is a no-no.

**Comment by eed3si9n** [comment] 2020-06-24 19:07
> I had seen your blog post about the different resolver strategies (after creating the issue actually), but does this also explain the behavior when changing the order of the dependencies?!

I don't think my blog post had any justification on getting different graph depending on the ordering of the input `libraryDependencies`. The problem with _nearest-wins_ as demonstrated by this case, is that the implementation needs to be pick the winner when the distance from the subproject is equal. In this case, akka-http dependencies both have 2 hops from the subproject?

Either case, I don't think there's much we will do about this issue, so I'm going to close this.

**Closed as completed by eed3si9n** 2020-06-24 19:07 UTC
Labels: area/library_management

**Comment by avdv** [comment] 2020-06-24 19:38
> I don't think my blog post had any justification on getting different graph depending on the ordering of the input `libraryDependencies`.

Well, it did! :smile: 

>> Note that if two dependency versions are at the same depth in the dependency tree, the first declaration wins.

> In this case, akka-http dependencies both have 2 hops from the subproject?

Yes, mystery solved... almost. Since, why was akka-http 10.1.12 chosen in the beginning? When alpakka-sqs was at version 2.0.0, it happily evicted the 10.1.11 version although both have the same depth from the project.

And, as noted above, using akka-http as a direct dependency still evicted it in favor of the one from alpakka-sqs...

I guess the plan is to phase out ivy based resolution in the future, and there's nothing warranting changing it, despite of some minor special cases.

Thank you!

--- 

For posterity, I tried this with Maven 3.6.3. 

It indeed used akka-http 10.1.11 with these dependencies:

1. `alpakka-sqs 2.0.0`
2. `aws-spi-akka-http 0.0.9`

(although it put the akka-http source jar in version 10.1.12 on the classpath)

and it used 10.1.12 with these dependencies:

1. `aws-spi-akka-http 0.0.9`
2. `alpakka-sqs 2.0.0`

Using akka-http 10.1.12 as a direct dependency also worked out as described, ie. with:

1. `alpakka-sqs 2.0.0`
2. `aws-spi-akka-http 0.0.9`
3. `akka-http 10.1.12`
