### ISSUE TITLE
ConflictManager.strict doesn't always report conflicts with cached resolution

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3256] opened 2017-06-08 04:47 UTC
We've had reports that under some circumstances that `ConflictManager.strict` doesn't always catch the conflicts.

## steps

1. Build that contains conflicts.

```scala
lazy val finagleVersion = "6.43.0"
lazy val jacksonDatabindVersion = "2.8.8.1"

lazy val app = (project in file("app"))
  .settings(
    conflictManager in ThisBuild := ConflictManager.strict,
    scalaVersion in ThisBuild := "2.11.11",
    libraryDependencies ++= Seq(
      "com.twitter" %% "finagle-http" % finagleVersion,
      "com.twitter" %% "finagle-core" % finagleVersion,
      "com.fasterxml.jackson.core" % "jackson-databind" % jacksonDatabindVersion
    ),
    updateOptions := updateOptions.value.withCachedResolution(true)
  )
```

2. `update`

## problem

`update` succeeds.

## expectation

`update` should fail.

## notes

sbt version: 0.13.15

Eviction warning is not empty if you run `evicted`.

```
[info] Here are other libraries that were evicted:
[info] 	* com.fasterxml.jackson.core:jackson-databind:2.8.4 -> 2.8.8.1 (caller: org.scala-sbt.temp:temp-resolve-be3a39ab4f9850722efd52421b83abae0a33293a:1.0)
[info] 	* com.fasterxml.jackson.core:jackson-annotations:2.8.0 -> 2.8.4 (caller: com.fasterxml.jackson.module:jackson-module-scala_2.11:2.8.4, com.fasterxml.jackson.core:jackson-databind:2.8.4)
[info] 	* com.fasterxml.jackson.core:jackson-core:2.8.4 -> 2.8.8 (caller: com.fasterxml.jackson.core:jackson-databind:2.8.8.1)
[info] 	* org.scala-lang:scala-library:2.11.8 -> 2.11.11 (caller: org.scala-sbt.temp:temp-resolve-a2327a4988b8b897776cc563c2b13a6b14568db5:1.0)
```

**Comment by dwijnand** [comment] 2017-07-26 14:45
Isn't this because to translate Maven semantics the dependencies are "force"'d?

**Comment by spockz** [comment] 2017-08-07 19:18
@eed3si9n why does this still need a reproduction test case? The issue contains a test-case.

**Comment by eed3si9n** [comment] 2017-08-08 03:50
@spockz Not sure. Maybe I edited the issue description later?

**Comment by spockz** [comment] 2017-08-08 21:16
@eed3si9n Any idea if and when this is going to be picked up? Resolving our build without the cache takes ages and we really want to spot dependency divergence.

As a workaround  going to try to create an alias that first unsets the update option and then runs evicted.

**Comment by eed3si9n** [comment] 2017-08-09 02:16
Thus far, the team has been focusing on getting sbt 1.0 out, but now that it's close we might come around to picking this up. In terms of difficulty, it doesn't look too bad to raise error while resolving conflict.

Note to potential contributor, it's here:
https://github.com/sbt/librarymanagement/blob/1.x/ivy/src/main/scala/sbt/internal/librarymanagement/ivyint/CachedResolutionResolveEngine.scala#L695-L726

**Comment by liancheng** [comment] 2017-08-29 01:00
@eed3si9n You probably want to use a permlink instead: https://github.com/sbt/librarymanagement/blob/6fc7bc6dc9241ba1c668a61e5a80c87563d7b21f/ivy/src/main/scala/sbt/internal/librarymanagement/ivyint/CachedResolutionResolveEngine.scala#L700-L731

**Comment by elbakramer** [comment] 2018-08-10 22:28
Possible duplicate of #2246

**Closed as completed** 2019-08-09 20:23 UTC
Labels: area/library_management
