### ISSUE TITLE
SBT project loading extremly slow

### ISSUE THREAD

**Issue by Starofall** [sbt/sbt#3870] opened 2018-01-10 21:57 UTC
Coming from SBT 0.13 I switched to the current version of SBT.

I started SBT and waited over 60 min+ for SBT finish loading the project... and it still did not open it.

I tried to look into the process with VisualVM and it showed my that "computeHashCode" is running all the time.
![image](https://user-images.githubusercontent.com/5400076/34797632-53015234-f659-11e7-9e22-23a9ac20bc16.png)

The console itself shows no more than
"... [debug] Copy resource mappings:" 

sbt version: *1.1.0* on Win10 with Java 8

[update]
it finished loading after waiting even longer... 
so not a real bug - but very very inconvenient compared to 0.13

**Comment by dwijnand** [comment] 2018-02-28 17:41
Duplicate of #3344

**Closed as completed by dwijnand** 2018-02-28 17:41 UTC
