### ISSUE TITLE
source dependency issues

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3918] opened 2018-02-02 22:04 UTC
This is an epic issue to aggregate source dependency issues and topics.

- Document source dependency https://github.com/sbt/sbt/issues/3145
- Unexpected initialization order of settings overriden in source dependencies #3850
- Refreshing Git URI Dependencies https://github.com/sbt/sbt/issues/1120

**Comment by jvican** [comment] 2018-02-03 10:12
An important issue is that `ThisBuild` and `Global` do not work with source dependencies: you would expect them to look for a key first in its own build scope, and then in the global scope, but it goes to the build scope of the top build. To get the correct behaviour, you need to do `in(ThisBuild).in(ref)`, which of course is not really what you strictly want (it looks for the key at the project scope first, before going to the correct build scope). Note that this is only possible when you control all the plugins and logic of all your source deps, which never happens; that's why sbt should do it by default.
  
Another issue that should be fixed is the handling of plugins. The "driver" build should be able to programmatically enable and disable plugins in downstream source dependencies. Why is this important? Because there are many cases in which plugins do not behave as expected (in which case you may want to shut them off), or in which they are required for correctness (in which case you may want to enable it). 
    
Last but not least, it would be great if sbt would classload different builds in different universes. This is *extremely* important because the build dependencies of different source modules are incompatible most of the time (versions are bin compat or libraries have different behaviours). As a result of this, users of source dependencies in sbt must fork every source dependency and spend a significant amount of time cleaning up the builds and changing plugins so that they are compatible. This is an epic, unfriendly task to which sbt can put an end.

**Comment by cchepelov** [comment] 2018-02-05 00:09
"source dependencies" would be absolutely terrific for my workflow if there was a way for sbt to behave as this, which I'd tentatively call "hybrid dependencies":

- if a libraryDependency is expressed with a non-SNAPSHOT version, do the usual binary dependency resolution (i.e. pass to Coursier ;) )
- otherwise, ask a (new) hook what do of the Module. The hook replies with an Option[sbt.Path]:
  - `case None =>` do the usual binary resolution
  - `case Some(path_to_some_build.sbt) if (organization, name, version) in path_to_some_build.sbt matches the requested module /* (i.e. it is itself in the requested x.y.z-SNAPSHOT) */ =>` , wrap the designated project's compile task as a dependency of the appropriate tasks of this project, and add its target to the classpath (I would probably not nest the "test" tasks though).
  - `case Some(_) =>` complain of the version mismatch or lack of expected source file, and do the usual binary resolution come what may.

How I'd use it: inject a plug-in in all house libraries, that would look for `s"../../${organization}/${name}/build.sbt"`. Therefore, when doing a something heavy across the stack, all I'd need to do is to 'open' new -SNAPSHOT versions and express the dependency across the stack, then refactor away until I'm satisfied I'm done, without having to ever stress about whether the misbehaviour in front of me is genuine or caused by a forgotten "publishLocal" somewhere along the stack. 

(note: _"wrap"_ above needs to also impact the dependency resolver. i.e if my project structure is:

- org/one/build.sbt:
```scala
organization := "org"
name := "one"
version := "1.2.0-SNAPSHOT"
````
- org/two/build.sbt:
```scala
organization := "org"
name := "two"
version := "6.4.0-SNAPSHOT"
    
libraryDependencies += "org" %% "one" % "1.2.0-SNAPSHOT"
```
- org/three/build.sbt:
```scala
organization := "org"
name := "three"
version := "3.3.3"
    
libraryDependencies += "org" %% "one" % "1.1.9"
```
- org/four/build.sbt:
```scala
organization := "org"
name := "four"
version := "4.5.6-SNAPSHOT"
    
libraryDependencies += "org" %% "one" % "1.1.7"
```
- org/five/build.sbt:
```scala
organization := "org"
name := "five"
version := "5.2.3-SNAPSHOT"
    
libraryDependencies += "org" %% "one" % "1.1.7"
```
- org/project/build.sbt:
```scala
organization := "org"
name := "project"
version := "0.0.1-SNAPSHOT"
   
libraryDependencies ++= Seq(
   "org" %% "two" % "6.4.0-SNAPSHOT",
   "org" %% "three" % "3.3.3-SNAPSHOT",
   "org" %% "four" % "4.5.6-SNAPSHOT",
   "org" %% "five" % "5.2.0")
```
Then subject to all these libraries being checked out in my local workspace, I expect to see in the eventual classpath of 'project':
- org %% two % 6.4.0-SNAPSHOT (local "unpublished" dependency to _two_'s target directory)
- org %% one % 1.2.0-SNAPSHOT (local "unpublished" dependency to _two_'s target directory)
- org %% three % 3.3.3 (binary resolution)
- an eviction notice that org %% one % 1.1.7 requested by three is evicted by 1.2.0-SNAPSHOT
- org %% four % 4.5.6-SNAPSHOT (local "unpublished" dependency to _two_'s target directory)
- an eviction notice that org %% one % 1.1.7 requested by four is evicted by 1.2.0-SNAPSHOT
- org %% five % 5.2.0 (binary resolution: the local checkout is ignored as we didn't request a SNAPSHOT version)
- an eviction notice for "one" % 1.1.3" requested by five is evicted by 1.2.0-SNAPSHOT

and of course:
- the "clean", "compile", "test", "run" and "assembly" targets of 'project' behave with as little surprise as possible

Bonus: this way of working makes no assumption on the SCM used (even if in my case it is indeed git) not how (mono vs. multi repo etc: entirely neutral)

I think @jvican is right to point out that nested project tasks should indeed be performed in distinct classloaders — this would definitely be the case in my 'hybrid dependencies' suggestion as well.



_PS: Ideally, IDEs (yes, you, IDEA) could notice and do the right thing, stringing together project modules as appropriate, but this is not sbt's responsibility._

**Comment by jvican** [comment] 2018-02-05 10:59
> if a libraryDependency is expressed with a non-SNAPSHOT version, do the usual binary dependency resolution (i.e. pass to Coursier ;) )
  
I have a current implementation of this in bloop, and yeah, it's awesome. https://github.com/scalacenter/bloop

**Comment by dwijnand** [comment] 2018-03-20 17:37
> This is an epic issue to aggregate source dependency issues and topics.

I created a ["source dependencies"](https://github.com/sbt/sbt/labels/source%20dependencies) label to aggregate.

what's the criteria under which this issue is closed?

as far as I see source dependencies support is a feature of sbt. it does have bugs and ways in which it could be improved, and those bugs and improvements should have dedicated issues (following our issue template).

and the new label can be used to aggregate :)

**Closed as completed by dwijnand** 2018-03-20 17:37 UTC
Labels: help wanted, area/library_management, Meta task
