### ISSUE TITLE
Add a warning about modified project files

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#790] opened 2013-06-23 17:29 UTC
E.g. when someone modifies build definition but forgets to do a reload. Would be very useful for beginners as this seems to be a recurring problem. 
Perhaps also auto-reload the definition and provide a way to hook into reloading process so that e.g. sbt-idea plugin could do its work?

**Comment by harrah** [comment] 2013-06-24 02:55
Duplicate of #241.

**Closed as completed by harrah** 2013-06-24 02:55 UTC
Labels: Duplicate
