### ISSUE TITLE
Prevent "sbt new" from loading global plugins

### ISSUE THREAD

**Issue by AugustNagro** [sbt/sbt#2872] opened 2016-12-17 23:07 UTC
## steps
If I run `g8 eed3si9n/hello.g8`, I receive the following: 

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

If `sbt new eed3si9n/hello.g8`,

```
[info] Loading global plugins from /Users/august/.sbt/0.13/plugins
[info] Set current project to test-projects (in build file:/Users/august/Documents/test-projects/)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
``` 

## problem

Unlike `g8`, `sbt new` notices that I have global plugins, and creates a `target` directory in the current directory. It's annoying to have to `rm -rf target` after creating a template. 

## expectation

`sbt new` does not create a `target` directory, or at least removes it automatically.

## notes
 Sbt 0.13.13 and g8 0.7.1 on macOS 10.12.2

I'd be happy to contribute a fix if a little direction can be provided.

**Comment by eed3si9n** [comment] 2016-12-19 19:56
This is a duplicate of https://github.com/sbt/sbt/issues/2835

The fact that target is created doesn't have to do with global plugins actually.
It's because the ivyConfiguration is read from a task, and task uses logging iirc.

**Closed as completed by eed3si9n** 2016-12-19 19:56 UTC
