### ISSUE TITLE
Easy way to set default project in multi-project build

### ISSUE THREAD

**Issue by heathermiller** [sbt/sbt#2405] opened 2016-01-20 16:24 UTC
I have a multi-project build and I wanted to make one of my sub-projects the default project when sbt starts. @jsuereth suggested to open a ticket, as there wasn't a nice clean way to do this out of the box.

Thanks to @pfn, there's a simple work around by using the following setting:

``` scala
onLoad in Global := (onLoad in Global).value andThen (Command.process("project mySubproj", _))
```

While this works, it's maybe not the clearest/cleanest solution to likely a common desire of people with multi-project builds.

PS, I searched around the issue tracker a bit for potential duplicate tickets but I might be using the wrong search terms. Sorry in advance if this is a duplicate ticket!

**Comment by eed3si9n** [comment] 2016-01-20 16:28
I've seen Scala Pickling do it - https://github.com/scala/pickling/blob/c5dd7de556396578be2f5f45f30bf1d328eb749a/.sbtrc

**Comment by heathermiller** [comment] 2016-01-20 16:31
Yep, that was another suggestion in the sbt/sbt gitter channel. But the `onLoad` trick seems more likely to be found by other maintainers. 

...It's particularly hilarious that one of my own projects already did this and I didn't know because it was in this `.sbtrc` file added by someone else that I had never noticed before. So, the `onLoad` approach is maybe more discoverable...

**Comment by dwijnand** [comment] 2016-10-25 23:38
Duplicate of #1224

**Closed as completed by dwijnand** 2016-10-25 23:38 UTC
Labels: Enhancement
