### ISSUE TITLE
flaky tests/do-not-discover due to logging?

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2720] opened 2016-08-30 11:43 UTC
https://travis-ci.org/sbt/sbt/jobs/156133133

```
[info] [info] Set current project to do-not-discover (in build file:/tmp/sbt_6b60dd95/do-not-discover/)
[info] Could not create file /tmp/sbt_6b60dd95/do-not-discover/target/streams/$global/projectDescriptors/$global/streams/outjava.io.IOException: No such file or directory
[info]  at sbt.internal.io.ErrorHandling$.translate(ErrorHandling.scala:10)
[info]  at sbt.io.IO$.touch(IO.scala:167)
[info]  at sbt.std.Streams$$anon$3$$anon$2.make(Streams.scala:132)
[info]  at sbt.std.Streams$$anon$3$$anon$2.text(Streams.scala:116)
[info]  at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:127)
[info]  at sbt.std.TaskStreams$class.log(Streams.scala:59)
[info]  at sbt.std.Streams$$anon$3$$anon$2.log$lzycompute(Streams.scala:105)
[info]  at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:105)
[info]  at sbt.Classpaths$$anonfun$depMap$1.apply(Defaults.scala:1634)
[info]  at sbt.Classpaths$$anonfun$depMap$1.apply(Defaults.scala:1633)
[info]  at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
[info]  at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
[info]  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:44)
[info]  at sbt.internal.util.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[info]  at sbt.std.Transform$$anon$4.work(System.scala:58)
[info]  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:230)
[info]  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:230)
[info]  at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]  at sbt.Execute.work(Execute.scala:239)
[info]  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:230)
[info]  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:230)
[info]  at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:161)
[info]  at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[info]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[info]  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[info]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[info]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[info]  at java.lang.Thread.run(Thread.java:745)
[info] Caused by: java.io.IOException: No such file or directory
[info]  at java.io.UnixFileSystem.createFileExclusively(Native Method)
[info]  at java.io.File.createNewFile(File.java:1006)
[info]  at sbt.io.IO$$anonfun$1.apply$mcZ$sp(IO.scala:167)
[info]  at sbt.io.IO$$anonfun$1.apply(IO.scala:167)
[info]  at sbt.io.IO$$anonfun$1.apply(IO.scala:167)
[info]  at sbt.internal.io.ErrorHandling$.translate(ErrorHandling.scala:10)
[info]  at sbt.io.IO$.touch(IO.scala:167)
[info]  at sbt.std.Streams$$anon$3$$anon$2.make(Streams.scala:132)
[info]  at sbt.std.Streams$$anon$3$$anon$2.text(Streams.scala:116)
[info]  at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:127)
[info]  at sbt.std.TaskStreams$class.log(Streams.scala:59)
[info]  at sbt.std.Streams$$anon$3$$anon$2.log$lzycompute(Streams.scala:105)
[info]  at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:105)
[info]  at sbt.Classpaths$$anonfun$depMap$1.apply(Defaults.scala:1634)
[info]  at sbt.Classpaths$$anonfun$depMap$1.apply(Defaults.scala:1633)
[info]  at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
[info]  at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
[info]  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:44)
[info]  at sbt.internal.util.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[info]  at sbt.std.Transform$$anon$4.work(System.scala:58)
[info]  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:230)
[info]  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:230)
[info]  at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]  at sbt.Execute.work(Execute.scala:239)
[info]  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:230)
[info]  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:230)
[info]  at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:161)
[info]  at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[info]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[info]  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[info]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[info]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[info]  at java.lang.Thread.run(Thread.java:745)
```

**Comment by dwijnand** [comment] 2016-10-14 08:26
Duplicate of #2156

**Closed as completed by dwijnand** 2016-10-14 08:26 UTC
