### ISSUE TITLE
Only start in existing project, no auto generation  of project files

### ISSUE THREAD

**Issue by rparree** [sbt/sbt#7955] opened 2024-12-18 08:41 UTC
Ever so often i run sbt by accident in a directory that is not a project. I then have to manually delete the geneerated files `target/`, 'project/` etc. It would be nice to have a command line argument that would only allow to open sbt in an existing project directory and would fail if it is not.

**Comment by SethTisue** [comment] 2024-12-18 17:40
duplicate of https://github.com/sbt/sbt/issues/2123 ?

**Comment by eed3si9n** [comment] 2024-12-18 18:14
Yea. https://github.com/sbt/sbt/blob/4318b5384b194911b4801befc69731c4d5674f44/sbt#L571 seems to indicate that there was an attempt at this feature, but I guess it's not working. Let's discuss in #2123.

**Closed as not planned by eed3si9n** 2024-12-18 18:14 UTC
