### ISSUE TITLE
Cross-building, cycles and doc problem

### ISSUE THREAD

**Issue by paulbutcher** [sbt/sbt#193] opened 2011-09-20 01:53 UTC
I've hit a problem which I've managed to distil down to the following Build.scala:

``` scala
import sbt._
import Keys._

object DocProblem extends Build {

  override lazy val settings = super.settings ++ Seq(crossScalaVersions := Seq("2.8.1", "2.9.1"))

  lazy val core = Project("Core", file("core"), aggregate = Seq(supplement))

  lazy val supplement: Project = Project("Supplement", file("supplement")) dependsOn(core)
}
```

This, when compiling the source code checked into this GitHub project:

https://github.com/paulbutcher/docproblem

Gives the following:

```
> +doc
Setting version to 2.8.1
[info] Set current project to Core (in build file:/Users/paul/scala/docproblem/)
[info] Updating {file:/Users/paul/scala/docproblem/}Core...
[info] Updating {file:/Users/paul/scala/docproblem/}Supplement...
[info] Done updating.
[info] Done updating.
[info] Generating API documentation for main sources...
[info] Compiling 2 Scala sources to /Users/paul/scala/docproblem/core/target/scala-2.8.1/classes...
model contains 0 documentable templates
[info] Generating API documentation for main sources...
[info] API documentation generation successful.
model contains 0 documentable templates
[info] API documentation generation successful.
[success] Total time: 8 s, completed 20-Sep-2011 02:43:13
Setting version to 2.9.1
[info] Set current project to Core (in build file:/Users/paul/scala/docproblem/)
[info] Updating {file:/Users/paul/scala/docproblem/}Core...
[info] Done updating.
[info] Updating {file:/Users/paul/scala/docproblem/}Supplement...
[info] Generating API documentation for main sources...
[info] Done updating.
[info] Compiling 2 Scala sources to /Users/paul/scala/docproblem/core/target/scala-2.9.1/classes...
[error] error while loading package, Missing dependency 'class com.example.package', required by ./core/target/scala-2.8.1/classes/com/example/package.class
[info] Generating API documentation for main sources...
model contains 4 documentable templates
model contains 4 documentable templates
[info] API documentation generation successful.
[error] one error found
[error] {file:/Users/paul/scala/docproblem/}Core/compile:doc: Scaladoc generation failed
[error] Total time: 4 s, completed 20-Sep-2011 02:43:18
```

Note that it's complaining that it can't find a dependency required by `./core/target/scala-2.8.1/classes/com/example/package.class` when compiling with Scala **2.9.1**.

Remove the cycle between the two projects, or the crossScalaVersions setting, and everything works just fine.

I see the same behaviour in 0.10.1 and 0.11.0-RC0

**Comment by paulbutcher** [comment] 2011-09-20 09:40
Just discovered that it is possible to reproduce this without a dependency cycle - the following Build.scala exhibits the same behaviour:

``` scala
import sbt._
import Keys._

object DocProblem extends Build {

  override lazy val settings = super.settings ++ Seq(crossScalaVersions := Seq("2.8.1", "2.9.1"))

  lazy val root = Project("Root", file(".")) aggregate(core, supplement)

  lazy val core = Project("Core", file("core"))

  lazy val supplement = Project("Supplement", file("supplement")) dependsOn(core)
}
```

Delete the `supplement` project, however, and everything works fine.

**Comment by harrah** [comment] 2011-09-20 11:36
Duplicate of #85?

**Comment by paulbutcher** [comment] 2011-09-20 14:04
Hmm - I don't see how it can be a duplicate of #85, given that #85 is caused a bug that was present in Scala 2.9.0 and 2.9.0-1, but I'm not using either of those. I'm using sbt 0.10.1 which is compiled with 2.8.1 and 0.11.0-RC0 which is compiled with 2.9.1, and cross building for 2.8.1 and 2.9.1, neither of which is affected by the bug, are they?

I'm also confused about how #85 could lead to the apparent "crosstalk" between the 2.8.1 and 2.9.1 builds that I'm seeing?

Having said that, following the suggestion in #85, I _can_ make the problem go away by adding a dummy project as follows:

``` scala
import sbt._
import Keys._

object DocProblem extends Build {

  override lazy val settings = super.settings ++ Seq(crossScalaVersions := Seq("2.8.1", "2.9.1"))

  lazy val root = Project("Root", file(".")) aggregate(core, supplement)

  lazy val dummy = Project("Dummy", file("dummy"))

  lazy val core = Project("Core", file("core")) dependsOn(dummy)

  lazy val supplement = Project("Supplement", file("supplement")) dependsOn(core)
}
```

So it does seem to have something in common with #85.

**Comment by harrah** [comment] 2011-09-20 19:05
It isn't exactly the same bug, but it is the same basic problem:

https://issues.scala-lang.org/browse/SI-4857

Thanks for the reproducible test cases.

**Closed as completed by harrah** 2011-09-20 19:05 UTC
Labels: not-a-🐛
