### ISSUE TITLE
1.4.0-RC1: Enter/echo in sbt terminal not working when calling readLine via code on Windows

### ISSUE THREAD

**Issue by MiroBro** [sbt/sbt#5864] opened 2020-09-17 16:45 UTC
## steps

Enter & echo are not working under these conditions on Windows 10 Pro

```
$ cat build.sbt 
scalaVersion := "2.13.3"

$ cat Main.scala 
object Main {
  def main(args: Array[String]): Unit = {
    println("Say something!")
    val s = scala.io.StdIn.readLine("your response: ")
    println(s"You wrote: $s")
  }
}

$ sbt
[info] welcome to sbt 1.4.0-RC1 (Oracle Corporation Java 1.8.0_251)
```

Run this code and try to write something. Press enter. See input below echoed to terminal:

```
sbt:scalapgk> run
[info] running HelloWorld
Say something!
your response: your response: User is now typing but nothing is echoed. 
Now pressing enter. Pressing enter again, twice fast.
readLine is never ended.
now pressing CTRL+D, nothing is happening.
now pressing Ctrl+C

[warn] Canceling execution...
[error] java.util.concurrent.RejectedExecutionException
[error] Use 'last' for the full log.
```

## problem

The problems are:

- The input text is not echoed when readLine is called via code.
- The text-message given as an argument to readLine is sometimes echoed twice.
- The enter key is not working when trying to complete a readLine by a user.
- When pressing Ctrl+D nothing occurs when having called readLine via code.

## expectation

- The Enter key should work with readline as in sbt 1.3.13
- The text input should be echoed when calling readLine and be printed in the terminal.
- The text message given as argument to readLine should only be printed once

**Comment by eatkins** [comment] 2020-09-17 17:16
Thanks for the report! I'm closing because this is a duplicate of #5863.

**Closed as completed by eatkins** 2020-09-17 17:16 UTC
