### ISSUE TITLE
sbt 1.3.0-RC2+ loves to deadlock after an error

### ISSUE THREAD

**Issue by pshirshov** [sbt/sbt#4893] opened 2019-07-23 00:04 UTC
Repro:

1. Clone https://github.com/7mind/izumi
2. Checkout commit 30fd2a9bb
3. Run sbt
4. type `distage-core/testOnly *.XXX` in sbt shell

```
...
	at sbt.Incomplete.hashCode(Incomplete.scala:24)
	at scala.runtime.Statics.anyHash(Statics.java:122)
	at scala.util.hashing.MurmurHash3.listHash(MurmurHash3.scala:173)
	at scala.util.hashing.MurmurHash3$.seqHash(MurmurHash3.scala:225)
	at scala.collection.LinearSeqLike.hashCode(LinearSeqLike.scala:41)
	at scala.collection.LinearSeqLike.hashCode$(LinearSeqLike.scala:41)
	at scala.collection.immutable.List.hashCode(List.scala:89)
	at scala.runtime.Statics.anyHash(Statics.java:122)
	at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:68)
	at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:215)
	at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:149)
	at sbt.Incomplete.hashCode(Incomplete.scala:24)
	at scala.runtime.Statics.anyHash(Statics.java:122)
	at scala.collection.immutable.HashSet.elemHashCode(HashSet.scala:179)
	at scala.collection.immutable.HashSet.computeHash(HashSet.scala:188)
	at scala.collection.immutable.HashSet.contains(HashSet.scala:58)
	at scala.collection.GenSetLike.apply(GenSetLike.scala:48)
	at scala.collection.GenSetLike.apply$(GenSetLike.scala:48)
	at scala.collection.AbstractSet.apply(Set.scala:51)
	at scala.collection.immutable.HashSet.apply(HashSet.scala:35)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$Lambda$161/0x00000008002a2840.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:250)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:248)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
	at scala.collection.TraversableLike.filterNot(TraversableLike.scala:270)
	at scala.collection.TraversableLike.filterNot$(TraversableLike.scala:270)
	at scala.collection.AbstractTraversable.filterNot(Traversable.scala:108)
	at sbt.internal.Aggregation$.findReload$1(Aggregation.scala:123)
	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:129)
	at sbt.internal.Aggregation$.$anonfun$applyDynamicTasks$4(Aggregation.scala:196)
	at sbt.internal.Aggregation$$$Lambda$4916/0x000000080142f840.apply(Unknown Source)
	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:139)
	at sbt.Command$$$Lambda$692/0x00000008006c7440.apply(Unknown Source)
	at sbt.internal.Act$.$anonfun$actParser0$4(Act.scala:438)
	at sbt.internal.Act$$$Lambda$4839/0x00000008013fdc40.apply(Unknown Source)
	at sbt.Command$.process(Command.scala:183)
	at sbt.MainLoop$.process$1(MainLoop.scala:187)
	at sbt.MainLoop$.processCommand(MainLoop.scala:220)
	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:141)
	at sbt.MainLoop$$$Lambda$636/0x000000080069b040.apply(Unknown Source)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:270)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:274)
	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:141)
	at sbt.MainLoop$$$Lambda$635/0x0000000800699c40.apply(Unknown Source)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
	at sbt.MainLoop$.next(MainLoop.scala:141)
	at sbt.MainLoop$.run(MainLoop.scala:132)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
	at sbt.MainLoop$$$Lambda$628/0x0000000800696040.apply(Unknown Source)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
	at sbt.StandardMain$.runManaged(Main.scala:124)
	at sbt.xMainImpl$.run(Main.scala:67)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.3/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.3/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.3/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.3/Method.java:566)
	at sbt.internal.XMainConfiguration.runXMain(XMainConfiguration.scala:46)
	at sbt.xMain.run(Main.scala:39)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
```

<img width="1509" alt="Screenshot 2019-07-23 at 01 01 49" src="https://user-images.githubusercontent.com/295225/61672986-a0656a80-ace5-11e9-9cf6-65cdc32d7d8c.png">

[stack.txt](https://github.com/sbt/sbt/files/3419531/stack.txt)

**Comment by eatkins** [comment] 2019-07-23 01:28
Thanks for the report! This was fixed in https://github.com/sbt/sbt/pull/4806. The issue is not present in 1.3.0-RC3 or a nightly build (which you may need to use if you're using intellij).

**Closed as completed by eatkins** 2019-07-23 01:28 UTC
