### ISSUE TITLE
Start up time in sbt 1.0.0-RC2 is slower

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3344] opened 2017-07-20 10:08 UTC
```
jvican in /data/rw/code/scala/experiment-performance                                                         [12:04:03] 
> $ vim project/build.properties // change to 0.13.16-M1
                                                                                                                        
jvican in /data/rw/code/scala/experiment-performance                                                         [12:04:11] 
> $ time sbt "exit"             
[info] Loading global plugins from /home/jvican/.sbt/0.13/plugins
[info] Updating {file:/home/jvican/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /home/jvican/.sbt/0.13/plugins/target/scala-2.10/sbt-0.13/classes...
[info] Loading project definition from /data/rw/code/scala/experiment-performance/project
[info] Updating {file:/data/rw/code/scala/experiment-performance/project/}experiment-performance-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to experiment-performance (in build file:/data/rw/code/scala/experiment-performance/)
/home/jvican/bin/sbt "exit"  39.40s user 0.70s system 321% cpu 12.476 total
                                                                                                                        
jvican in /data/rw/code/scala/experiment-performance                                                         [12:04:26] 
> $ time sbt "exit"
[info] Loading global plugins from /home/jvican/.sbt/0.13/plugins
[info] Loading project definition from /data/rw/code/scala/experiment-performance/project
[info] Set current project to experiment-performance (in build file:/data/rw/code/scala/experiment-performance/)
/home/jvican/bin/sbt "exit"  13.05s user 0.25s system 296% cpu 4.493 total
                                                                                                                        
jvican in /data/rw/code/scala/experiment-performance                                                         [12:04:33] 
> $ time sbt "exit"
[info] Loading global plugins from /home/jvican/.sbt/0.13/plugins
[info] Loading project definition from /data/rw/code/scala/experiment-performance/project
[info] Set current project to experiment-performance (in build file:/data/rw/code/scala/experiment-performance/)
/home/jvican/bin/sbt "exit"  12.64s user 0.26s system 294% cpu 4.385 total
                                                                                                                        
jvican in /data/rw/code/scala/experiment-performance                                                         [12:04:48] 
> $ vim project/build.properties // change to sbt 1.0.0-RC2
                                                                                                                        
jvican in /data/rw/code/scala/experiment-performance                                                         [12:04:54] 
> $ time sbt "exit"             
[info] Loading project definition from /data/rw/code/scala/experiment-performance/project

[info] Loading settings from build.sbt ...

[info] Set current project to experiment-performance (in build file:/data/rw/code/scala/experiment-performance/)

/home/jvican/bin/sbt "exit"  22.35s user 0.34s system 291% cpu 7.778 total
                                                                                                                        
jvican in /data/rw/code/scala/experiment-performance                                                         [12:05:04] 
> $ time sbt "exit"
[info] Loading project definition from /data/rw/code/scala/experiment-performance/project

[info] Loading settings from build.sbt ...

[info] Set current project to experiment-performance (in build file:/data/rw/code/scala/experiment-performance/)

/home/jvican/bin/sbt "exit"  14.34s user 0.29s system 267% cpu 5.477 total
                                                                                                                        
jvican in /data/rw/code/scala/experiment-performance                                                         [12:05:13] 
> $ time sbt "exit"
[info] Loading project definition from /data/rw/code/scala/experiment-performance/project

[info] Loading settings from build.sbt ...

[info] Set current project to experiment-performance (in build file:/data/rw/code/scala/experiment-performance/)

/home/jvican/bin/sbt "exit"  13.74s user 0.22s system 266% cpu 5.247 total
                                                                            
```
  
We have to figure out why. The tested project has the following build.sbt:
```
name := "experiment-performance"
organization := "ch.epfl.scala"
libraryDependencies ++= List(
  "io.circe" %% "circe-core" % "0.8.0",
  "io.circe" %% "circe-generic" % "0.8.0",
  "io.circe" %% "circe-parser" % "0.8.0",
  "com.chuusai" %% "shapeless" % "2.3.2"
)
```

**Comment by chengzp** [comment] 2017-10-10 06:28
I am also seeing a regression in start-up time, and much more severe:
```
For 0.13.16:

sbt exit  15.06s user 0.88s system 293% cpu 5.426 total
sbt exit  14.78s user 0.80s system 302% cpu 5.143 total
sbt exit  14.04s user 0.80s system 288% cpu 5.149 total
sbt exit  15.07s user 0.80s system 302% cpu 5.246 total

For 1.0.2 (1.0.1 has similar timings):

sbt exit  27.51s user 1.24s system 293% cpu 9.785 total
sbt exit  27.68s user 1.25s system 294% cpu 9.827 total
sbt exit  29.21s user 1.37s system 289% cpu 10.574 total
sbt exit  30.19s user 1.37s system 291% cpu 10.826 total
```

Commenting out the entire `build.sbt` file except for `name` did not reduce the startup times. 

Commenting out `plugins.sbt` entirely reduced it by about 1-2 seconds (but still worse than before). This is the content:
```
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.6")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.2.2-RC2")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC11")
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")
```

**Comment by jrudolph** [comment] 2017-10-30 10:51
For akka-http it's about 50% slower (on my machine 0.13.16: 11s -> 1.0.3: 15s)

**Comment by jrudolph** [comment] 2017-10-30 10:52
Btw. that's Linux running after the build has been compiled on previous runs.

**Comment by ngbinh** [comment] 2017-10-31 03:59
same here. About 20-30% slower on 1.0.3 compares to 0.13.16

**Comment by imarios** [comment] 2018-01-29 04:30
@dwijnand @eed3si9n this comes out quite often when I mention "guys, we should migrate to sbt 1.x!". Both at open source projects I am involved, as well as at work. 

Here are some numbers (pretty consistent across multiple runs):

```scala
time sbt exit

# on sbt 0.13.11+
real	0m3.887s
user	0m12.514s
sys	0m0.610s

# on sbt 1.1.0
real	0m6.270s
user	0m19.407s
sys	0m0.790s
```

**Comment by schmitch** [comment] 2018-02-04 13:33
this is even worse on first runs (which might often happen in `docker build`-Environments).
The sbt 1.x.x builds hanging forever at `Loading project definition from`.  Well at least dependency resolution is faster when coursier is plugged in...

**Comment by eatkins** [comment] 2018-02-26 23:12
I did some git bisecting and, for me, the performance regression seems to occur in the #3322 pr. This merge unfortunately merges a number of other merge commits that can't be independently tested. I am suspicious that https://github.com/sbt/sbt/pull/3322/commits/347914191a8af2f2ad53abbb120fb4144122380b is the commit that introduced the performance regression.

As a side note, I'd advocate for stricter merge policies (i.e. every merge should independently pass CI) and/or not doing nested merges. It really makes it difficult to bisect and debug changes.

**Comment by yellowmegaman** [comment] 2018-05-31 22:12
Any news here?
```
[info] Updating ProjectRef(uri("file:/drone/src/bitbucket.org/someteam/somrepo/someproject/"), "server-build")... 
  46s
[info] Done updating.   766s
```

sbt 1.1.4

So it's 720 seconds really ((

**Comment by antoniocascais** [comment] 2018-07-17 12:29
We are having the same issus as @yellowmegaman. It takes ~5min until the "Updating ProjectRef" is over :|

We tried with sbt 1.1.1, 1.1.6 and 1.2.0 (the rc candidate), but no improvements in any.

**Comment by yellowmegaman** [comment] 2018-07-17 12:44
Completely forgot to provide new info.
After i've used s3/GCS for ivy2 and coursier cache, problem went away.
So i sync cache manually and then update takes just a few seconds.

In my case i had to do that because our CI/CD agents are spawned on GCP empty.

**Comment by antoniocascais** [comment] 2018-07-20 12:01
In the end it was the same problem with us @yellowmegaman !

We added caching to our CI/CD agents and problem was solved.
Thanks for the help!

**Comment by yellowmegaman** [comment] 2018-07-20 15:28
@antoniocascais Glad it worked for you too)

**Comment by franz-see** [comment] 2018-08-27 17:00
This hangs for us as well on the first run (i.e. if we clear ~/.sbt and ~/.ivy2)

```
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/franzsee/myproject
[info] Updating ProjectRef(uri("file:/Users/franzsee/myproject/"), "myproject-build")...
```

On succeeding runs, it executes way faster. 

Problem though is everytime we test if our dependency management resolvers are configured properly in our project, we clear the ~/.sbt and ~/.ivy2 to test things out. And that reintroduces the high turnaround time on that testing.

**Comment by eed3si9n** [comment] 2018-08-27 17:24
@franz-see If you're clearing out `~/.sbt` then you should reinstall sbt from the official installer of the sbt version you're using so you can take advantage of the preloaded local repo. That should speed up the resolution of sbt itself.

https://www.scala-sbt.org/download.html

**Comment by mdedetrich** [comment] 2018-10-31 16:17
Apologies if I am sounding like a broken record but is there any status update on this issue? This is causing our continuous delivery speeds to be incredibly high, our `Updating` is taking 4 minutes alone, i.e.

```
5:10:35 PM [info] Loading settings for project workspace-build from plugins.sbt ...
5:10:36 PM [info] Loading project definition from /workspace/project
5:10:36 PM [info] Updating ProjectRef(uri("file:/workspace/project/"), "workspace-build")...
5:14:14 PM [info] downloading https://repo1.maven.org/maven2/org/glassfish/hk2/hk2-api/2.4.0-b34/hk2-api-2.4.0-b34.jar ...
```

It would be nice if there was some concentrated effort looking into this, as its a very severe performance regression and it doesn't appear like its a priority.

**Comment by eatkins** [comment] 2018-10-31 18:56
There has been some background discussion about improving the update performance amongst the sbt contributors. There is currently work to add coursier as an alternative to ivy for resolution, which should speed up update for most builds. If you aren't already using it, you might want to look into trying the coursier plugin (add `addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.3")` to project/plugins.sbt).

I am interested in looking into update performance, but I am working on other, non-sbt projects at the moment.

**Comment by eed3si9n** [comment] 2018-10-31 20:31
@mdedetrich Thanks for bring it to our attention again. Like @eatkins mentioned there's been multiple discussions around performance, but perhaps there might be multiple issues involved.
One of the major difference between sbt 0.13 and sbt 1 is the way we persist cache input and output of the `update` task, and that might be hitting you here.

I just opened two performance related issues as action items:
- Exclude "sbt" from the metabuild resolution - https://github.com/sbt/sbt/issues/4437
- update task performance and UpdateReport persistence - https://github.com/sbt/sbt/issues/4438

**Comment by mdedetrich** [comment] 2018-11-01 00:33
@eatkins Thanks for the tip on Coursier cache, we are already using Coursier cache. The problem in our case is not downloading dependencies (which are actually almost always cached on our CD platform), its specifically when SBT is loading the project, i.e. the `Updating ProjectRef(.....` part.

@eed3si9n @eatkins Thanks for the response, I am glad someone is looking into it. Its just been ongoing issue for more then a year now. Many thanks for creating the tickets, visibility is always a pleasure.

**Comment by jrudolph** [comment] 2018-11-06 11:38
@mdedetrich could you share more about the project (e.g. its `plugin.sbt` could be enough for reproducing)? Is that for every start of sbt when the target folders are still missing? Is it better after the first start?

You could try keeping the `project/target/.../resolution-cache` and `project/target/.../update-cache_2.12` folders.

**Comment by mdedetrich** [comment] 2018-11-06 14:25
@jrudolph Thanks, its a commercial project so I will likely create a private lightbend ticket for it

**Comment by almothafar** [comment] 2018-11-13 10:26
I got sbt 1.2.6 and still getting the same issue:

plugin.sbt:

```
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.20")
addSbtPlugin("io.gatling" % "gatling-sbt" % "2.2.2")
```

build.sbt:

```
name := """java-rest-api"""

version := "1.0.0"

def gatlingVersion(scalaBinVer: String): String = scalaBinVer match {
  case "2.11" => "2.2.5"
  case "2.12" => "2.3.1"
}

inThisBuild(
  List(
    scalaVersion := "2.12.7",
    crossScalaVersions := Seq("2.11.12", "2.12.7"),
    dependencyOverrides := Seq(
      "org.codehaus.plexus" % "plexus-utils" % "3.1.0",
      "com.google.code.findbugs" % "jsr305" % "3.0.2",
      "com.google.guava" % "guava" % "26.0-jre"
    )
  )
)


lazy val GatlingTest = config("gatling") extend Test

lazy val root = (project in file(".")).enablePlugins(PlayJava, GatlingPlugin).configs(GatlingTest)
  .settings(inConfig(GatlingTest)(Defaults.testSettings): _*)
  .settings(
    scalaSource in GatlingTest := baseDirectory.value / "/gatling/simulation"
  )


libraryDependencies ++= Seq(
  guice,
  javaJpa,
  "com.microsoft.sqlserver" % "mssql-jdbc" % "7.0.0.jre10",
  "org.mariadb.jdbc" % "mariadb-java-client" % "2.3.0",
  "com.h2database" % "h2" % "1.4.197",
  "org.hibernate" % "hibernate-core" % "5.3.6.Final",
  "io.dropwizard.metrics" % "metrics-core" % "4.0.3",
  "com.palominolabs.http" % "url-builder" % "1.1.0",
  "net.jodah" % "failsafe" % "1.1.0"
)


libraryDependencies += "io.gatling.highcharts" % "gatling-charts-highcharts" % gatlingVersion(scalaBinaryVersion.value) % Test
libraryDependencies += "io.gatling" % "gatling-test-framework" % gatlingVersion(scalaBinaryVersion.value) % Test

PlayKeys.externalizeResources := false
PlayKeys.devSettings := Seq("play.server.http.idleTimeout" -> "180s")

testOptions in Test := Seq(Tests.Argument(TestFrameworks.JUnit, "-a", "-v"))

// You can easily navigate from error pages to IntelliJ directly into the source code,
// by using IntelliJ’s “remote file” REST API with the built in IntelliJ web server on port 63342.
javaOptions += "-Dplay.editor=http://localhost:63342/api/file/?file=%s&line=%s"


```

**Comment by Hervera** [comment] 2019-01-07 06:51
What is the answer guys? Play framework Updating ProjectRef(uri("")) still takes too long, It doesn't finish. Now, there are 20 min waiting to finish updating.

**Comment by balagez** [comment] 2019-01-18 22:04
We still use 0.13 just because of this.

**Comment by gavares** [comment] 2019-01-25 18:12
Also experiencing this problem on sbt 1.1.0. Any update/news or ideas about what we can do to resolve this? One of our new devs has been waiting for ~10 minutes just staring at:

`[info] Updating ProjectRef(uri("file:/Users/.......), xxx)`

**Comment by xcorpio** [comment] 2019-02-20 08:26
30+ mins for the first time

**Comment by geksong** [comment] 2019-03-06 09:37
It's cost 20+ mins in this execution.
```[info] Updating ProjectRef(uri("file:/Users/.......), xxx)```
Maybe it is better to give log output during this execution.

**Comment by aioannidis** [comment] 2019-04-21 10:24
I tried to build an existing project from scratch on my new pc and the process is on the state
[info] Updating ProjectRef(uri("file:/Users/.......), xxx)

for over an hour.

What is the problem after all? 

Will there be a solution any time soon?

**Comment by almothafar** [comment] 2019-04-21 15:27
To be honest, this should be a priority, I think about moving to Gradle because of this issue, it waste our team time especially during deployment, we got 2 play projects inside 1 project and that waste time just because of the deployment for each time (which sometimes many times during the day, sometimes 1 time for the week).

This is from the LinkedIn team where they improve development speed to 400%: https://engineering.linkedin.com/blog/2018/07/how-we-improved-build-time-by-400-percent 
And some discussion: 
https://www.reddit.com/r/scala/comments/am0638/how_we_improved_build_time_by_400_at_linkedin_sbt/

So I think this will take some time and I found many issues with Gradle, so I need to plan for it, which I don't have time for now, hopefully, will try that soon.

**Comment by ScalaWilliam** [comment] 2019-04-21 16:26
@almothafar I had come across multiple people prefer to do Java simply because SBT was too slow to deal with, and Gradle/Maven is not necessarily the best when going with Scala, especially if you want to do Play.

If not fixing the problem itself, one huge leap forward would be a clear-cut way of identifying where these slow-downs are. Right now, all the user can do so far is simply guess.

**Comment by eed3si9n** [comment] 2019-04-21 17:43
@ScalaWilliam 

> If not fixing the problem itself, one huge leap forward would be a clear-cut way of identifying where these slow-downs are. Right now, all the user can do so far is simply guess.

I agree. sbt 1.3.0 will provide a number of ways to surface that out. Like https://twitter.com/eed3si9n/status/1109694906648416256

**Comment by eed3si9n** [comment] 2019-04-21 17:46
For many builds the bottleneck is `update` task so here are some proposals for sbt 1.3.0 that I'm trying:
- Slim down update's UpdateReport by removing evicted modules caller information  (https://github.com/sbt/sbt/pull/4606).
- Coursier dependency resolution integration (https://github.com/sbt/sbt/pull/4614)

**Comment by Jaszkowic** [comment] 2019-05-02 15:29
We are experiencing the same issue with sbt 1.2.7.

Initializing `sbt` on a clean docker image takes ages (some minutes) compared to the rest of the build process. This is significantly slowing down our Gitlab CI/CD pipeline. 

Maybe there is some way of preparing the docker image somehow? Because consecutive `sbt` run in the same docker container consume less time. Anyone experimenting with that or similar ideas?

**Comment by eed3si9n** [comment] 2019-05-02 15:33
I created my own Docker image and wrote about it here. The image should have all JARs ready to go - http://eed3si9n.com/sbt-on-docker

**Comment by Jaszkowic** [comment] 2019-05-02 15:42
The following is our Docker file which we used to built the image where sbt runs. Using this image we don't have to download sbt anymore on first run. We made sure that we download exactly the sbt version we are using in our application. We even run `sbt sbtVersion` once to make sure the initialization already happened. However, the first sbt initialization using this image still takes far too long - so this doesn't really optimize much.

```
FROM openjdk:11

ENV SBT_VERSION=1.2.7

COPY ./build.sbt /build.sbt
COPY ./project /project

RUN \
  apt-get update && \
  apt-get install -y \
    docker.io \
    curl && \
  curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb && \
  dpkg -i sbt-$SBT_VERSION.deb && \
  rm sbt-$SBT_VERSION.deb && \
  apt-get install sbt && \
  sbt sbtVersion

```

**Comment by jrudolph** [comment] 2019-05-02 15:46
> Maybe there is some way of preparing the docker image somehow? Because consecutive `sbt` run in the same docker container consume less time. Anyone experimenting with that or similar ideas?

Don't run from a complete clean docker image but one that has run `sbt update` on the project in question before. That will make sure you will run with a pre-filled ivy cache.

**Comment by Jaszkowic** [comment] 2019-05-02 15:50
> Don't run from a complete clean docker image but one that has run sbt update on the project in question before. That will make sure you will run with a pre-filled ivy cache.

We kind of tried to do that (running `sbt sbtVersion`), but that's not project-based i guess? So that means that in our prebuilt docker image we must already have a project stub (same project name/folder?) and run `sbt update` on that?

**Comment by eatkins** [comment] 2019-07-18 20:12
There are two issues being discussed in this thread: One is that startup time is slow for some builds due to `update`. The other is that sbt 1.x generically starts up more slowly than sbt 0.13.x which is the issue initially reported by @jvican.

These are rough numbers with uncertainty of about a half second, but, on my machine, in an empty project, sbt 0.13.x starts up in about 4.5 seconds and sbt 1.3.x starts up in about 7.5 seconds (as measured by running `time sbt exit`).

Compared to sbt 0.13.x, sbt 1.x will always be slower for startup because the scala 2.12 compiler (by which I mean `scala.tools.nsc.Global`) takes longer to initialize than the scala 2.10 compiler. This can't be fixed and means the best case scenario is that sbt 1.x will start up roughly 0.5-1 seconds slower than 0.13.x, which is more or less what the initial issue reported.

Another thing that slows down start up compared to 0.13.x is that the json based update report is much slower to initially load than whatever 0.13.x was using. Because the update report for sbt itself is fairly large, this delays start up by I think about 1 second even when it's just being read from disk.

I can't fully account for the three second difference, but I think the scala 2.12 compiler and the new json based update report are probably responsible for about two seconds of the difference.

I think this issue should probably be closed because what Jorge initially reported is mostly understood and the update related startup issues should be handled in their own issue.

**Comment by eed3si9n** [comment] 2019-07-18 20:38
> I think this issue should probably be closed because what Jorge initially reported is mostly understood and the update related startup issues should be handled in their own issue.

Sounds good.

**Closed as completed by eed3si9n** 2019-07-18 20:38 UTC
Labels: Enhancement, Regression, area/performance
