### ISSUE TITLE
Found [error] [launcher] error during sbt launcher: java.nio.file.AccessDeniedException: /run/user/0/.sbt on AMI 2023

### ISSUE THREAD

**Issue by nuboat** [sbt/sbt#7515] opened 2024-03-16 06:31 UTC
## steps
I have setup my new TeamCity Agent with AMI 2023

```bash
curl -L https://www.scala-sbt.org/sbt-rpm.repo
sudo yum install sbt
sbt
```

## problem

```scala
java.nio.file.AccessDeniedException: /run/user/0/.sbt
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.checkAccess(UnixFileSystemProvider.java:355)
        at java.base/java.nio.file.Files.createDirectories(Files.java:772)
        at sbt.internal.BootServerSocket.<init>(BootServerSocket.java:291)
        at sbt.xMain$.getSocketOrExit(Main.scala:152)
        at sbt.xMain$.bootServerSocket$lzycompute$1(Main.scala:78)
        at sbt.xMain$.bootServerSocket$1(Main.scala:78)
        at sbt.xMain$.withStreams$1(Main.scala:86)
        at sbt.xMain$.run(Main.scala:123)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
        at sbt.xMain.run(Main.scala:47)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.nio.file.AccessDeniedException: /run/user/0/.sbt
```

BTW, as check on /etc/passwd,  user 0 is root and I can run sbt on root user.
I found this on AMI 2023 only

## expectation
run normally as below

```bash
[info] welcome to sbt 1.9.9 (Amazon.com Inc. Java 21.0.2)
[info] loading project definition from /root/project
[info] set current project to root (in build file:/root/)
[info] sbt server started at local:///root/.sbt/1.0/server/27dc1aa3fdf4049b492d/sock
[info] started sbt server
```

**Comment by eed3si9n** [comment] 2024-03-16 06:44
This sounds kind of similar to https://github.com/sbt/sbt/issues/7056.
Does `echo $HOME` print `/run/user/0/`?

**Comment by eed3si9n** [comment] 2024-03-17 02:44
According to https://github.com/sbt/sbt/blob/f672cb85a9e7c21a17736a34ab95880b7b5dd320/main-command/src/main/java/sbt/internal/BootServerSocket.java#L313-L319

sbt 1.9.9 tries to create a directory under `XDG_RUNTIME_DIR` env variable, following XDG Base Directory Specification; otherwise it would fallback to `System.getProperty("java.io.tmpdir")`. Both should be fair game to create directories, I think. I'm going to close this issue as not a bug for now.

**Closed as not planned by eed3si9n** 2024-03-17 02:44 UTC
Labels: not-a-🐛, area/linux

**Comment by SethTisue** [comment] 2026-02-22 01:26
similar: #7056
