### ISSUE TITLE
"/packages cannot be represented as URI" on JDK 14

### ISSUE THREAD

**Issue by ZviMints** [sbt/sbt#5509] opened 2020-04-21 07:12 UTC
## steps
Trying to run sbt test or sbt compile on my project occurs an error

## problem

sbt crash with versions
## expectation
```
❯ sbt test
[info] Loading global plugins from /Users/Zvi/.sbt/1.0/plugins
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/Zvi/Desktop/Git/App/project
[info] Loading settings from build.sbt ...
[info] Set current project to eligibility (in build file:/Users/Zvi/Desktop/Git/App/)
[info] Compiling 66 Scala sources and 2 Java sources to /Users/Zvi/Desktop/Git/App/target/scala-2.12/classes ...
[error] ## Exception when compiling 68 sources t/Users/Zvi/Desktop/Git/App/target/scala-2.12/classes
[error] java.lang.RuntimeException: /packages cannot be represented as URI
[error] java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
[error] scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:204)
[error] scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:55)
[error] scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] scala.collection.Iterator.foreach(Iterator.scala:944)
[error] scala.collection.Iterator.foreach$(Iterator.scala:944)
[error] scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error] scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] scala.tools.nsc.classpath.AggregateClassPath.asURLs(AggregateClassPath.scala:55)
[error] scala.tools.nsc.typechecker.Macros.findMacroClassLoader(Macros.scala:66)
[error] scala.tools.nsc.typechecker.Macros.findMacroClassLoader$(Macros.scala:65)
[error] scala.tools.nsc.Global$$anon$1.findMacroClassLoader(Global.scala:448)
[error] scala.reflect.macros.runtime.MacroRuntimes.$anonfun$defaultMacroClassloaderCache$2(MacroRuntimes.scala:56)
[error] scala.reflect.internal.SymbolTable$perRunCaches$$anon$1.apply(SymbolTable.scala:459)
....
```

## notes
Versions:
**java:**
```
java --version
openjdk 14 2020-03-17
OpenJDK Runtime Environment (build 14+36-1461)
OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)
```

**scala:**
```
scala --version
Scala code runner version 2.13.1 -- Copyright 2002-2019, LAMP/EPFL and Lightbend, Inc.
```

**sbt:**
```
sbt --version
[INFO] [04/21/2020 10:09:13.839] [Thread-1] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
sbt script version: 1.3.10
```

**Comment by eed3si9n** [comment] 2020-04-22 16:36
@ZviMints Thanks for the report. Could you provide more details on how we can reproduce your problem on _our machines_ please? I am guessing that this happens on a specific set of source or library combinations, but from the repro steps we can't tell what's happening.

**Comment by eed3si9n** [comment] 2020-04-22 16:38
We don't test sbt on JDK 14, so that could also be the problem. Please run it on JDK 8 or 11.

**Comment by eed3si9n** [comment] 2020-04-22 16:43
This actually looks like a duplicate of https://github.com/sbt/sbt/issues/5093.

**Comment by ZviMints** [comment] 2020-04-23 06:40
Hey @eed3si9n 
Im getting the same error with JDK14 and JDK8 and JDK11
```
 scala --version
Scala code runner version 2.13.1 -- Copyright 2002-2019, LAMP/EPFL and Lightbend, Inc.
```
```
❯ java --version
openjdk 11.0.7 2020-04-14 LTS
OpenJDK Runtime Environment Corretto-11.0.7.10.1 (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.7.10.1 (build 11.0.7+10-LTS, mixed mode)
```
```
❯ sbt --version
error: error while loading String, class file '/modules/java.base/java/lang/String.class' is broken
(class java.lang.NullPointerException/null)
sbt script version: 1.3.10
```

Error:
```
❯ sbt test
[info] Loading global plugins from /Users/Zvi/.sbt/1.0/plugins
error: error while loading String, class file '/modules/java.base/java/lang/String.class' is broken
(class java.lang.NullPointerException/null)
[error] java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
[error]         at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
...
```

Thanks! cant solve it yet...

**Comment by eed3si9n** [comment] 2020-04-23 07:56
Did you recently install sbt via Homebrew? If so you might need to set JAVA_HOME for JDK to be respected.

**Comment by ZviMints** [comment] 2020-04-23 08:04
@eed3si9n  I did, but JAVA_HOME is set
```
echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
```
(Mac)

**Comment by eed3si9n** [comment] 2020-04-23 15:55
If you're getting error message about Java modules, then JDK 8 is not being used.
I'd suggest using SDKMAN to install sbt or unzip the download file manually - https://www.scala-sbt.org/download.html

**Comment by ZviMints** [comment] 2020-04-26 08:25
@eed3si9n WHAT! Its worked.
`brew uninstall sbt`
`sdk install sbt`
fixed the problem. 
Thanks!

**Comment by albertoadami** [comment] 2020-04-29 20:11
I'm getting a similar issue, but with JDK 8.
This is my configuration:

- java: 1.8.0_251
- sbt: 1.3.10
- scala: 2.12.6

I've installed sbt using brew on my mac.
The project that gives me the issue it's only one, this project use a multi-project setup.

`[error] ## Exception when compiling 3 sources to /Users/albertoadami/repos/project/service/target/scala-2.12/test-classes
[error] java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
[error] java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
[error] scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:204)
[error] scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:55)
[error] scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] scala.collection.Iterator.foreach(Iterator.scala:944)
[error] scala.collection.Iterator.foreach$(Iterator.scala:944)
[error] scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error] scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] scala.tools.nsc.classpath.AggregateClassPath.asURLs(AggregateClassPath.scala:55)
[error] scala.tools.nsc.typechecker.Macros.findMacroClassLoader(Macros.scala:66)
[error] scala.tools.nsc.typechecker.Macros.findMacroClassLoader$(Macros.scala:65)
[error] scala.tools.nsc.Global$$anon$1.findMacroClassLoader(Global.scala:448)
[error] scala.reflect.macros.runtime.MacroRuntimes.$anonfun$defaultMacroClassloaderCache$2(MacroRuntimes.scala:56)
[error] scala.reflect.internal.SymbolTable$perRunCaches$$anon$1.apply(SymbolTable.scala:459)
[error] scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader(MacroRuntimes.scala:58)
[error] scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader$(MacroRuntimes.scala:58)
[error] scala.tools.nsc.Global$$anon$1.defaultMacroClassloader(Global.scala:448)
[error] scala.reflect.macros.runtime.MacroRuntimes$MacroRuntimeResolver.resolveRuntime(MacroRuntimes.scala:76)
[error] scala.reflect.macros.runtime.MacroRuntimes.$anonfun$standardMacroRuntime$3(MacroRuntimes.scala:38)
[error] scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:206)
[error] scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:203)
[error] scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
[error] scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime(MacroRuntimes.scala:38)
[error] scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime$(MacroRuntimes.scala:31)
[error] scala.tools.nsc.Global$$anon$1.standardMacroRuntime(Global.scala:448)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:448)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:445)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:401)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime(AnalyzerPlugins.scala:445)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime$(AnalyzerPlugins.scala:445)
[error] scala.tools.nsc.Global$$anon$1.pluginsMacroRuntime(Global.scala:448)
[error] scala.reflect.macros.runtime.MacroRuntimes.macroRuntime(MacroRuntimes.scala:25)
[error] scala.reflect.macros.runtime.MacroRuntimes.macroRuntime$(MacroRuntimes.scala:25)
[error] scala.tools.nsc.Global$$anon$1.macroRuntime(Global.scala:448)
[error] scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:619)
[error] scala.tools.nsc.Global.withInfoLevel(Global.scala:219)
[error] scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:613)
[error] scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:600)
[error] scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:764)
[error] scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:762)
[error] scala.tools.nsc.Global$$anon$1.standardMacroExpand(Global.scala:448)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:432)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:429)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:401)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:429)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:429)
[error] scala.tools.nsc.Global$$anon$1.pluginsMacroExpand(Global.scala:448)
[error] scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:757)
[error] scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:757)
[error] scala.tools.nsc.Global$$anon$1.macroExpand(Global.scala:448)
[error] scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1171)
[error] scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1231)
[error] scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5654)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
[error] scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3290)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:477)
[error] scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgWithFormal$1(PatternTypers.scala:108)
[error] scala.tools.nsc.typechecker.PatternTypers$PatternTyper.$anonfun$typedArgsForFormals$4(PatternTypers.scala:122)
[error] scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgsForFormals(PatternTypers.scala:122)
[error] scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgsForFormals$(PatternTypers.scala:103)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedArgsForFormals(Typers.scala:111)
[error] scala.tools.nsc.typechecker.Typers$Typer.handleMonomorphicCall$1(Typers.scala:3635)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$31(Typers.scala:3661)
[error] scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3661)
[error] scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4773)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4801)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5586)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5603)
[error] scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
[error] scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:889)
[error] scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:477)
[error] scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1227)
[error] scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5654)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
[error] scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5723)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5731)
[error] scala.tools.nsc.typechecker.Typers$Typer.adaptToMember(Typers.scala:1300)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adaptToMemberWithArgs$7(Typers.scala:1342)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$silent$2(Typers.scala:714)
[error] scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:714)
[error] scala.tools.nsc.typechecker.Typers$Typer.adaptToMemberWithArgs(Typers.scala:1342)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedSelect$1(Typers.scala:4947)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:5064)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5587)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5603)
[error] scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
[error] scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$38(Typers.scala:4752)
[error] scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:700)
[error] scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4754)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4801)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5586)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5603)
[error] scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
[error] scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5703)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3129)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3274)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3274)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2006)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1829)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5552)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5602)
[error] scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
[error] scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5703)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3129)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3274)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3274)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5262)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5555)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5602)
[error] scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
[error] scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5699)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:104)
[error] scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
[error] scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1(Analyzer.scala:94)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1$adapted(Analyzer.scala:93)
[error] scala.collection.Iterator.foreach(Iterator.scala:944)
[error] scala.collection.Iterator.foreach$(Iterator.scala:944)
[error] scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1446)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1430)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1423)
[error] scala.tools.nsc.Global$Run.compile(Global.scala:1539)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
[error] xsbt.CompilerInterface.run(CompilerInterface.scala:39)
[error] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1765)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1738)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] sbt.Execute.work(Execute.scala:290)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] java.base/java.lang.Thread.run(Thread.java:830)
[error]            
[error] stack trace is suppressed; run last service / Test / compileIncremental for the full output
[error] (service / Test / compileIncremental) java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
[error] Total time: 3 s, completed 29 apr 2020, 22:05:08
`
 With IntelliJ sbt shell I'm able to use the sbt commands without this kind of issue.

**Comment by albertoadami** [comment] 2020-04-29 20:16
> If you're getting error message about Java modules, then JDK 8 is not being used.
> I'd suggest using SDKMAN to install sbt or unzip the download file manually - https://www.scala-sbt.org/download.html

This works also for my issue, thank you!

**Comment by eliothxchan** [comment] 2020-08-12 17:43
@eed3si9n 

SDKMAN worked for me too, thanks!

**Comment by eed3si9n** [comment] 2020-08-12 21:33
Closing this now. https://www.scala-sbt.org/download.html

⚠️ Homebrew maintainers have added a dependency to JDK 13 because they want to use more brew dependencies (https://github.com/Homebrew/homebrew-core/issues/50649). This causes sbt to use JDK 13 even when java available on PATH is JDK 8 or 11. To prevent sbt from running on JDK 13, install [jEnv](https://www.jenv.be/) or switch to using [SDKMAN](https://sdkman.io/).

**Closed as completed by eed3si9n** 2020-08-12 21:33 UTC
Labels: Needs Reproduction Test Case, area/jdk_x

**Comment by RaghavSaxena96** [comment] 2020-09-04 17:27
Like to Thank everyone for the solution
I was frustrated for 2 days
Solution -- brew uninstall sbt
                   sdk install sbt

Worked as sbt by brew was using java 14 even if it was not present as it is not compatible with scala and sbt and by installing sbt by sdk I was able to solve my problem

**Comment by ashutoshrdwivedi** [comment] 2020-10-30 14:18
setting JAVA_HOME as `export JAVA_HOME=$(/usr/libexec/java_home -v 11)` worked for me.

I had installed sbt using homebrew. sbt  -version : 
```
[info] 1.1.2
sbt script version: 1.4.0

**Comment by Mingun** [comment] 2020-11-18 16:42
Is this error is really fixed or I should use the workaround with java 8? Also, how can I get the Scala version, because I didn't install Scala myself because sbt [is download it for me](https://stackoverflow.com/questions/24839385/do-you-need-to-install-scala-separately-if-you-use-sbt)?

**Comment by eed3si9n** [comment] 2020-11-18 16:56
> Is this error is really fixed

No, the Homebrew-installed `sbt` is broken out of the box (https://github.com/Homebrew/homebrew-core/issues/50649) and it requires some kind of a workaround to NOT use JDK 13 that they keep shoving in people's face against sbt project's will.

> I should use the workaround with java 8?

Yes.

> Also, how can I get the Scala version, because I didn't install Scala myself because sbt is download it for me?

Put the following in `build.sbt`:

```scala
ThisBuild / scalaVersion := "2.13.3"
```

For more intro material please read https://www.scala-sbt.org/1.x/docs/sbt-by-example.html
