### ISSUE TITLE
sbt 0.13.0 withSources publishes incorrect dependency type in pom

### ISSUE THREAD

**Issue by thetrav** [sbt/sbt#1025] opened 2013-12-03 04:08 UTC
Related to https://groups.google.com/forum/#!topic/simple-build-tool/b2VtHtCbgpM

publishing a project with a library dependency:

```
"net.databinder" %% "unfiltered" % "0.6.8" withSources()
```

will result in a pom entry:

```
<dependency>
  <groupId>net.databinder</groupId>
  <artifactId>unfiltered_2.10</artifactId>
  <version>0.6.8</version>
  <classifier>sources</classifier>
  <type>src</type>
</dependency>
```

note particularly

```
  <type>src</type>
```

According to:
http://maven.apache.org/pom.html#Dependencies

```
type:
Corresponds to the dependant artifact's packaging type. This defaults to jar. While it usually represents the extension on the filename of the dependency, that is not always the case. A type can be mapped to a different extension and a classifier. The type often corresponds to the packaging used, though this is also not always the case. Some examples are jar, ejb-client and test-jar. New types can be defined by plugins that set extensions to true, so this is not a complete list.
```

The issue this causes is that when another sbt project attempts to pull down the published project with dependencies, it maps the type directly to the extension.

```
http://repo1.maven.org/maven2/net/databinder/unfiltered_2.10/0.6.8/unfiltered_2.10-0.6.8-sources.src
```

where it should be trying to get

```
http://repo1.maven.org/maven2/net/databinder/unfiltered_2.10/0.6.8/unfiltered_2.10-0.6.8-sources.jar
```

I haven't attempted to use the project using other build systems (mvn, gradle etc), but I assume they would have the same problem with that dependency definition

**Comment by harrah** [comment] 2013-12-03 13:33
Duplicate of #728.

**Closed as completed by harrah** 2013-12-03 13:34 UTC
Labels: Duplicate
